## Imports

In [6]:
import os
import re
import time
import itertools

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import datetime as datetime

from scipy import stats
from pyhive import presto
from datetime import datetime, timedelta

from sklearn.model_selection import train_test_split
from sklearn.model_selection import StratifiedShuffleSplit

import warnings
warnings.filterwarnings('ignore')

In [8]:
pd.set_option('display.max_columns', 50)
pd.set_option('display.max_rows', 50)

In [10]:
## Connection
connection = presto.connect(
        
        host='presto-gateway.processing.data.production.internal',
#     presto.processing.yoda.run
#     presto-gateway.processing.data.production.internal',
        port=80,
        protocol='http',
        catalog='hive',
        username='manoj.ravirajan@rapido.bike'
)

In [12]:
cwd = os.getcwd()
print(cwd)
local_datasource = '/Users/E2074/local-datasets/customer/ads-monetisation/holdout-group'
print(local_datasource)

/Users/E2074/analytics/customer/Ads-Monetisation/holdout-group/jas
/Users/E2074/local-datasets/customer/ads-monetisation/holdout-group

## Datasets & Parameter

In [15]:
## Parameter 
current_date = datetime.now()
start_date = '20240401'
end_date = '20240630'

# Convert date strings to datetime objects
start_dt = datetime.strptime(start_date, '%Y%m%d')
end_dt = datetime.strptime(end_date, '%Y%m%d')
segment_date = end_dt.strftime('%Y-%m-%d')
print(start_date, ' to ' ,end_date)

20240401  to  20240630

### AMJ Gross Customers

In [18]:
data_query = f"""

    WITH customer_base as (
    
    SELECT 
        customer_id,
        city_name,
        customer_obj_mobile customer_mobile,
        COUNT(DISTINCT order_id) net_orders,
        COUNT(DISTINCT CASE WHEN service_obj_service_name IN ('Link','Bike Lite','Bike Pink','Bike Metro') THEN order_id END) bike_service,
        COUNT(DISTINCT CASE WHEN service_obj_service_name IN ('Auto','Auto Lite','Auto NCR','Auto Pool','AutoPremium','CityAuto') THEN order_id END) auto_service,
        COUNT(DISTINCT CASE WHEN service_obj_service_name IN ('CabEconomy', 'CabPremium') THEN order_id END) cab_service
    FROM    
        orders.order_logs_snapshot
    WHERE  
        yyyymmdd >= '{start_date}'
        AND yyyymmdd <= '{end_date}'
        AND order_status = 'dropped'
        AND city_name IN ('Chennai', 'Delhi', 'Jaipur', 'Ahmedabad')
        AND service_obj_service_name in ('Auto','Auto Lite','Auto NCR','Auto Pool','AutoPremium','CityAuto','Link','Bike Lite','Bike Pink','Bike Metro','CabEconomy','CabPremium')
        AND channel_host = 'android'
    GROUP BY 1,2,3
    ),
    
    segment AS (
    
    SELECT
        customer_id,
        taxi_ltr_segment ltr_segment,
        taxi_retention_segments retention_segment,
        taxi_lifetime_stage lifetime_stage,
        taxi_service_affinity service_affinity,
        gender_tag gender
    FROM
        datasets.iallocator_customer_segments
    WHERE 
        run_date = '{segment_date}'
    )
    
    SELECT 
        customer_base.*,
        coalesce( ltr_segment, 'UNKNOWN')ltr_segment,
        coalesce( retention_segment, 'UNKNOWN') retention_segment,
        coalesce( lifetime_stage, 'UNKNOWN') lifetime_stage,
        coalesce( service_affinity, 'UNKNOWN') service_affinity,
        coalesce( gender, 'UNKNOWN') gender
    FROM 
        customer_base
    LEFT JOIN 
        segment
        ON customer_base.customer_id = segment.customer_id
"""

# Execute the query and get the result as a DataFrame
df_data = pd.read_sql(data_query, connection)

df_data.to_csv( local_datasource + '/customer_data_{}_{}.csv'.format(start_date, end_date), index=False)

In [19]:
# df_data = pd.read_csv( local_datasource + '/analysis_data_{}_{}.csv'.format(start_date, end_date))

In [20]:
df_data.head(5)

,customer_id,city_name,customer_mobile,net_orders,bike_service,auto_service,cab_service,ltr_segment,retention_segment,lifetime_stage,service_affinity,gender
0,6607ad9aa6f9b95d5f444715,Delhi,7050013704,5,3,1,1,PHH,GOLD,SOFT_CHURN,NO_AFFINITY,MALE
1,5ca0435e8c352421ea0461cc,Chennai,9043509008,7,3,4,0,PHH,GOLD,SUSTENANCE,ONLY_AUTO,MALE
2,6107bdbbe29f55fa087f08cc,Jaipur,8741025143,9,6,3,0,PHH,GOLD,SUSTENANCE,LINK_AUTO,MALE
3,5cfd2a64c0b26018f5df0aa1,Chennai,9551505747,23,18,4,1,PHH,DORMANT,DORMANT,ONLY_LINK,MALE
4,657bccfbf275496377f10753,Jaipur,6377213444,1,1,0,0,HH,DORMANT,DORMANT,ONLY_LINK,MALE

In [21]:
start = '20240701'
end = '20240731'

ads_query = f"""

    WITH ads as (
        
        SELECT     
            userId,
            COUNT(DISTINCT CASE WHEN eventName = 'Ad_Viewable_Impression' THEN adid END) impression_count,
            COUNT(DISTINCT CASE WHEN eventName = 'Ad_Click' THEN adid END) click_count
        FROM 
            canonical.iceberg_log_telemetry_ads_impressions_immutable_full
        
        WHERE  
            yyyymmdd >= '{start}'
            and yyyymmdd <= '{end}'
            and responseType in ('GAMBanner') 
            and eventName in ('Ad_Viewable_Impression', 'Ad_Click')
            and city in ('Chennai', 'Delhi', 'Jaipur', 'Ahmedabad')
        GROUP BY 1
        )
        
        SELECT
            *
        FROM 
            ads
"""

# Execute the query and get the result as a DataFrame
df_ads_data = pd.read_sql(ads_query, connection)

# df_ads_data.to_csv( local_datasource + '/ads_customer_data_{}_{}.csv'.format(start_date, end_date), index=False)

In [22]:
# df_ads_data = pd.to_csv( local_datasource + '/ads_customer_data_{}_{}.csv'.format(start_date, end_date))

In [23]:
df_ads_data.head()

                     userId  impression_count  click_count
0  6358404085b3994aff50c48f                 2            0
1  665f898f3774472df1c78df9                 6            0
2  5de92b2a1a882e3354b48101                13            0
3  64cb72ba3525f250d8b40765                12            0
4  64f163d190e8ec48e3075be3                 5            0

## User defined function

In [25]:
agg_dict = {
    'customers': ('customer_id', 'nunique'),
    'net_orders': ('net_orders', 'sum'),
    'bike_service': ('bike_service', 'sum'),
    'auto_service': ('auto_service', 'sum'),
    'cab_service': ('cab_service', 'sum'),
}

def calculate_percentage(df, numerator, denominator):
    
    percentage = (df[numerator] * 100.00 / df[denominator]).round(2)
    
    return percentage

def calculate_percentage_columns(df):
        
    df['bike'] = calculate_percentage(df, 'bike_service', 'net_orders')
    df['auto'] = calculate_percentage(df, 'auto_service', 'net_orders')
    df['cab'] = calculate_percentage(df, 'cab_service', 'net_orders')
    
    return df

## Sampling

In [27]:
df_data.head(2)

,customer_id,city_name,customer_mobile,net_orders,bike_service,auto_service,cab_service,ltr_segment,retention_segment,lifetime_stage,service_affinity,gender
0,6607ad9aa6f9b95d5f444715,Delhi,7050013704,5,3,1,1,PHH,GOLD,SOFT_CHURN,NO_AFFINITY,MALE
1,5ca0435e8c352421ea0461cc,Chennai,9043509008,7,3,4,0,PHH,GOLD,SUSTENANCE,ONLY_AUTO,MALE

In [28]:
df_data.columns

Index(['customer_id', 'city_name', 'customer_mobile', 'net_orders',
       'bike_service', 'auto_service', 'cab_service', 'ltr_segment',
       'retention_segment', 'lifetime_stage', 'service_affinity', 'gender'],
      dtype='object')

In [29]:
df_analysis2 = df_data\
.groupby(['city_name'])\
.agg(**agg_dict)\
.reset_index()

df_analysis2 = calculate_percentage_columns(df_analysis2)
df_analysis2

,city_name,customers,net_orders,bike_service,auto_service,cab_service,bike,auto,cab
0,Ahmedabad,522010,2769577,1643935,811315,314327,59.36,29.29,11.35
1,Chennai,2167905,15133947,6076816,8140482,916649,40.15,53.79,6.06
2,Delhi,2952255,18128459,12153329,3832103,2143027,67.04,21.14,11.82
3,Jaipur,754877,3270532,2034287,1236245,0,62.20,37.80,0.00

In [30]:
df_data['city_name'].value_counts(True)

city_name
Delhi        0.461502
Chennai      0.338893
Jaipur       0.118004
Ahmedabad    0.081601
Name: proportion, dtype: float64

In [31]:
df_data.shape

(6397102, 12)

In [32]:
df_data.customer_id.nunique()

6323258

In [33]:
duplicated_values = df_data['customer_id'].duplicated(keep=False) 
df_cleaned = df_data[~duplicated_values]
df_cleaned.shape

(6251052, 12)

In [34]:
df_cleaned.customer_id.nunique()

6251052

In [115]:
random_seed = 42

df_train_control, df_test = train_test_split(df_cleaned, 
                                             test_size=0.10, 
                                             random_state=random_seed
                                            )

df_train_control = df_train_control.sample(len(df_train_control), random_state=random_seed)
df_test = df_test.sample(len(df_test), random_state=random_seed)

# Assign group labels
df_train_control['group_tc'] = 'bau'
df_test['group_tc'] = 'global-control'

df_final_sample = pd.concat([df_train_control, df_test])

In [116]:
df_final_sample['group_tc'].value_counts(True)

group_tc
bau               0.9
global-control    0.1
Name: proportion, dtype: float64

In [117]:
df_final_sample.groupby('city_name')['group_tc'].value_counts(True).unstack(fill_value=0)

group_tc        bau  global-control
city_name
Ahmedabad  0.901386        0.098614
Chennai    0.899955        0.100045
Delhi      0.899885        0.100115
Jaipur     0.899626        0.100374

In [118]:
df_final_sample.columns

Index(['customer_id', 'city_name', 'customer_mobile', 'net_orders',
       'bike_service', 'auto_service', 'cab_service', 'ltr_segment',
       'retention_segment', 'lifetime_stage', 'service_affinity', 'gender',
       'group_tc'],
      dtype='object')

In [119]:
df1 = df_final_sample\
.groupby(['city_name','group_tc'])\
.agg(**agg_dict)\
.reset_index()

df1 = calculate_percentage_columns(df1)
df1

,city_name,group_tc,customers,net_orders,bike_service,auto_service,cab_service,bike,auto,cab
0,Ahmedabad,bau,451835,2389738,1422738,699217,267783,59.54,29.26,11.21
1,Ahmedabad,global-control,49432,264927,157118,78107,29702,59.31,29.48,11.21
2,Chennai,bau,1935131,13523205,5420278,7286894,816033,40.08,53.88,6.03
3,Chennai,global-control,215122,1505825,603559,812580,89686,40.08,53.96,5.96
4,Delhi,bau,2600379,16023131,10755928,3380142,1887061,67.13,21.10,11.78
5,Delhi,global-control,289301,1771765,1187342,375222,209201,67.01,21.18,11.81
6,Jaipur,bau,638601,2773995,1724494,1049501,0,62.17,37.83,0.00
7,Jaipur,global-control,71251,312918,195402,117516,0,62.45,37.55,0.00

In [120]:
df2 = df_final_sample\
.groupby(['city_name','ltr_segment', 'group_tc'])\
.agg(**agg_dict)\
.reset_index()

df2 = calculate_percentage_columns(df2)
df2

,city_name,ltr_segment,group_tc,customers,net_orders,bike_service,auto_service,cab_service,bike,auto,cab
0,Ahmedabad,HH,bau,181742,289899,159934,77410,52555,55.17,26.70,18.13
1,Ahmedabad,HH,global-control,19742,31517,17302,8476,5739,54.90,26.89,18.21
2,Ahmedabad,PHH,bau,268775,2098487,1261650,621609,215228,60.12,29.62,10.26
3,Ahmedabad,PHH,global-control,29546,233263,139693,69607,23963,59.89,29.84,10.27
4,Ahmedabad,UNKNOWN,bau,1318,1352,1154,198,0,85.36,14.64,0.00
5,Ahmedabad,UNKNOWN,global-control,144,147,123,24,0,83.67,16.33,0.00
6,Chennai,HH,bau,523233,852300,329124,441941,81235,38.62,51.85,9.53
7,Chennai,HH,global-control,58179,94990,36788,49135,9067,38.73,51.73,9.55
8,Chennai,PHH,bau,1410209,12669182,5089959,6844425,734798,40.18,54.02,5.80
9,Chennai,PHH,global-control,156768,1410655,566651,763385,80619,40.17,54.12,5.72
10,Chennai,UNKNOWN,bau,1689,1723,1195,528,0,69.36,30.64,0.00
11,Chennai,UNKNOWN,global-control,175,180,120,60,0,66.67,33.33,0.00
12,Delhi,HH,bau,989154,1543347,928417,304701,310229,60.16,19.74,20.10
13,Delhi,HH,global-control,110129,171989,103227,34089,34673,60.02,19.82,20.16
14,Delhi,PHH,bau,1606608,14474835,9823367,3074669,1576799,67.87,21.24,10.89
15,Delhi,PHH,global-control,178645,1599203,1083623,341056,174524,67.76,21.33,10.91
16,Delhi,UNKNOWN,bau,4617,4949,4144,772,33,83.73,15.60,0.67
17,Delhi,UNKNOWN,global-control,527,573,492,77,4,85.86,13.44,0.70
18,Jaipur,HH,bau,218930,334980,207204,127776,0,61.86,38.14,0.00
19,Jaipur,HH,global-control,24434,37286,22902,14384,0,61.42,38.58,0.00
20,Jaipur,PHH,bau,418547,2437702,1516460,921242,0,62.21,37.79,0.00
21,Jaipur,PHH,global-control,46673,275465,172387,103078,0,62.58,37.42,0.00
22,Jaipur,UNKNOWN,bau,1124,1313,830,483,0,63.21,36.79,0.00
23,Jaipur,UNKNOWN,global-control,144,167,113,54,0,67.66,32.34,0.00

In [121]:
df3 = df_final_sample\
.groupby(['city_name','retention_segment', 'group_tc'])\
.agg(**agg_dict)\
.reset_index()

df3 = calculate_percentage_columns(df3)
df3

,city_name,retention_segment,group_tc,customers,net_orders,bike_service,auto_service,cab_service,bike,auto,cab
0,Ahmedabad,DORMANT,bau,237336,662410,373048,199790,89572,56.32,30.16,13.52
1,Ahmedabad,DORMANT,global-control,25993,74405,42049,22632,9724,56.51,30.42,13.07
2,Ahmedabad,ELITE,bau,15510,684364,437485,197367,49512,63.93,28.84,7.23
3,Ahmedabad,ELITE,global-control,1724,76361,48987,21750,5624,64.15,28.48,7.37
4,Ahmedabad,GOLD,bau,52175,316525,172882,99572,44071,54.62,31.46,13.92
...,...,...,...,...,...,...,...,...,...,...,...
67,Jaipur,PRIME,global-control,85,2651,2314,337,0,87.29,12.71,0.00
68,Jaipur,SILVER,bau,88176,202917,122807,80110,0,60.52,39.48,0.00
69,Jaipur,SILVER,global-control,9788,22480,13832,8648,0,61.53,38.47,0.00
70,Jaipur,UNKNOWN,bau,1124,1313,830,483,0,63.21,36.79,0.00
71,Jaipur,UNKNOWN,global-control,144,167,113,54,0,67.66,32.34,0.00

In [122]:
df4 = df_final_sample\
.groupby(['city_name','lifetime_stage', 'group_tc'])\
.agg(**agg_dict)\
.reset_index()

df4 = calculate_percentage_columns(df4)
df4

,city_name,lifetime_stage,group_tc,customers,net_orders,bike_service,auto_service,cab_service,bike,auto,cab
0,Ahmedabad,CHURN_OTB,bau,12906,148976,87533,44685,16758,58.76,29.99,11.25
1,Ahmedabad,CHURN_OTB,global-control,1406,15418,8970,4707,1741,58.18,30.53,11.29
2,Ahmedabad,COMMITTED,bau,32665,911047,581519,255685,73843,63.83,28.06,8.11
3,Ahmedabad,COMMITTED,global-control,3704,103435,65324,29626,8485,63.15,28.64,8.20
4,Ahmedabad,DETOX,bau,1085,10151,8877,941,333,87.45,9.27,3.28
...,...,...,...,...,...,...,...,...,...,...,...
75,Jaipur,SOFT_CHURN,global-control,1795,10667,6407,4260,0,60.06,39.94,0.00
76,Jaipur,SUSTENANCE,bau,33947,205508,125162,80346,0,60.90,39.10,0.00
77,Jaipur,SUSTENANCE,global-control,3755,22995,13994,9001,0,60.86,39.14,0.00
78,Jaipur,UNKNOWN,bau,1124,1313,830,483,0,63.21,36.79,0.00
79,Jaipur,UNKNOWN,global-control,144,167,113,54,0,67.66,32.34,0.00

In [123]:
df_final_sample.groupby('city_name')['group_tc'].value_counts(True).unstack(fill_value=0)

group_tc        bau  global-control
city_name
Ahmedabad  0.901386        0.098614
Chennai    0.899955        0.100045
Delhi      0.899885        0.100115
Jaipur     0.899626        0.100374

In [124]:
df_final_sample.groupby(['city_name', 'ltr_segment'])['group_tc'].value_counts(True).unstack(fill_value=0)

group_tc                    bau  global-control
city_name ltr_segment
Ahmedabad HH           0.902017        0.097983
          PHH          0.900959        0.099041
          UNKNOWN      0.901505        0.098495
Chennai   HH           0.899935        0.100065
          PHH          0.899955        0.100045
          UNKNOWN      0.906116        0.093884
Delhi     HH           0.899817        0.100183
          PHH          0.899933        0.100067
          UNKNOWN      0.897551        0.102449
Jaipur    HH           0.899599        0.100401
          PHH          0.899675        0.100325
          UNKNOWN      0.886435        0.113565

In [125]:
df_final_sample.groupby(['city_name', 'retention_segment'])['group_tc'].value_counts(True).unstack(fill_value=0)

group_tc                          bau  global-control
city_name retention_segment
Ahmedabad DORMANT            0.901291        0.098709
          ELITE              0.899965        0.100035
          GOLD               0.903322        0.096678
          HH                 0.902164        0.097836
          INACTIVE           0.891801        0.108199
          PLATINUM           0.898183        0.101817
          PRIME              0.900555        0.099445
          SILVER             0.901984        0.098016
          UNKNOWN            0.901505        0.098495
Chennai   DORMANT            0.899947        0.100053
          ELITE              0.899810        0.100190
          GOLD               0.898905        0.101095
          HH                 0.900413        0.099587
          INACTIVE           0.898582        0.101418
          PLATINUM           0.899649        0.100351
          PRIME              0.901575        0.098425
          SILVER             0.901301        0.098699
          UNKNOWN            0.906116        0.093884
Delhi     DORMANT            0.899604        0.100396
          ELITE              0.900653        0.099347
          GOLD               0.899279        0.100721
          HH                 0.900421        0.099579
          INACTIVE           0.897273        0.102727
          PLATINUM           0.900531        0.099469
          PRIME              0.905782        0.094218
          SILVER             0.900426        0.099574
          UNKNOWN            0.897551        0.102449
Jaipur    DORMANT            0.899599        0.100401
          ELITE              0.899699        0.100301
          GOLD               0.898744        0.101256
          HH                 0.901207        0.098793
          INACTIVE           0.903740        0.096260
          PLATINUM           0.897176        0.102824
          PRIME              0.900701        0.099299
          SILVER             0.900086        0.099914
          UNKNOWN            0.886435        0.113565

### Check

In [127]:
df_final_sample.query("group_tc == 'bau'")["ltr_segment"].value_counts(True)

ltr_segment
PHH        0.658403
HH         0.340042
UNKNOWN    0.001555
Name: proportion, dtype: float64

In [128]:
df_final_sample.query("group_tc == 'global-control'")["ltr_segment"].value_counts(True)

ltr_segment
PHH        0.658500
HH         0.339917
UNKNOWN    0.001584
Name: proportion, dtype: float64

In [129]:
df_final_sample.query("group_tc == 'bau'")["retention_segment"].value_counts(True)

retention_segment
DORMANT     0.502738
GOLD        0.125037
HH          0.116146
SILVER      0.112532
PLATINUM    0.086979
ELITE       0.046221
INACTIVE    0.005862
PRIME       0.002931
UNKNOWN     0.001555
Name: proportion, dtype: float64

In [130]:
df_final_sample.query("group_tc == 'global-control'")["retention_segment"].value_counts(True)

retention_segment
DORMANT     0.503550
GOLD        0.125907
HH          0.115280
SILVER      0.111531
PLATINUM    0.087232
ELITE       0.046114
INACTIVE    0.005993
PRIME       0.002811
UNKNOWN     0.001584
Name: proportion, dtype: float64

In [131]:
df_final_sample.query("group_tc == 'global-control' & city_name == 'Delhi'")["retention_segment"].value_counts(True)

retention_segment
DORMANT     0.513877
HH          0.129388
GOLD        0.115624
SILVER      0.105198
PLATINUM    0.077874
ELITE       0.046616
INACTIVE    0.006381
PRIME       0.003222
UNKNOWN     0.001822
Name: proportion, dtype: float64

In [132]:
df_final_sample.query("group_tc == 'bau' & city_name == 'Delhi'")["retention_segment"].value_counts(True)

retention_segment
DORMANT     0.512280
HH          0.130161
GOLD        0.114851
SILVER      0.105833
PLATINUM    0.078436
ELITE       0.047017
INACTIVE    0.006201
PRIME       0.003446
UNKNOWN     0.001776
Name: proportion, dtype: float64

In [133]:
df_final_sample[(df_final_sample['group_tc'] == 'bau') 
                    &
                (df_final_sample['city_name'] == 'Delhi')]["retention_segment"].value_counts(True)

retention_segment
DORMANT     0.512280
HH          0.130161
GOLD        0.114851
SILVER      0.105833
PLATINUM    0.078436
ELITE       0.047017
INACTIVE    0.006201
PRIME       0.003446
UNKNOWN     0.001776
Name: proportion, dtype: float64

In [134]:
# Get unique values for group_tc and city_name
unique_city_name = df_final_sample['city_name'].unique()
unique_group_tc = df_final_sample['group_tc'].unique()

In [135]:
# Generate all possible combinations
combinations = itertools.product(unique_city_name, unique_group_tc)

In [136]:
# Iterate through combinations and print the results
for city_name_value, group_tc_value in combinations:
    
    print(f"city_name: {city_name_value}, group_tc: {group_tc_value}")
    result = df_final_sample[(df_final_sample['group_tc'] == group_tc_value) & (df_final_sample['city_name'] == city_name_value)]["retention_segment"].value_counts(True)
    print(result)

city_name: Delhi, group_tc: bau
retention_segment
DORMANT     0.512280
HH          0.130161
GOLD        0.114851
SILVER      0.105833
PLATINUM    0.078436
ELITE       0.047017
INACTIVE    0.006201
PRIME       0.003446
UNKNOWN     0.001776
Name: proportion, dtype: float64
city_name: Delhi, group_tc: global-control
retention_segment
DORMANT     0.513877
HH          0.129388
GOLD        0.115624
SILVER      0.105198
PLATINUM    0.077874
ELITE       0.046616
INACTIVE    0.006381
PRIME       0.003222
UNKNOWN     0.001822
Name: proportion, dtype: float64
city_name: Chennai, group_tc: bau
retention_segment
DORMANT     0.467828
GOLD        0.146829
SILVER      0.115393
PLATINUM    0.112571
HH          0.093403
ELITE       0.055934
INACTIVE    0.004684
PRIME       0.002485
UNKNOWN     0.000873
Name: proportion, dtype: float64
city_name: Chennai, group_tc: global-control
retention_segment
DORMANT     0.467869
GOLD        0.148544
SILVER      0.113670
PLATINUM    0.112955
HH          0.092929
ELITE       0.056024
INACTIVE    0.004755
PRIME       0.002440
UNKNOWN     0.000813
Name: proportion, dtype: float64
city_name: Jaipur, group_tc: bau
retention_segment
DORMANT     0.553726
SILVER      0.138077
HH          0.111906
GOLD        0.107245
PLATINUM    0.056921
ELITE       0.021968
INACTIVE    0.007189
UNKNOWN     0.001760
PRIME       0.001207
Name: proportion, dtype: float64
city_name: Jaipur, group_tc: global-control
retention_segment
DORMANT     0.553887
SILVER      0.137374
HH          0.109949
GOLD        0.108293
PLATINUM    0.058469
ELITE       0.021951
INACTIVE    0.006863
UNKNOWN     0.002021
PRIME       0.001193
Name: proportion, dtype: float64
city_name: Ahmedabad, group_tc: bau
retention_segment
DORMANT     0.525271
HH          0.138878
GOLD        0.115474
SILVER      0.102730
PLATINUM    0.069016
ELITE       0.034327
INACTIVE    0.007078
PRIME       0.004309
UNKNOWN     0.002917
Name: proportion, dtype: float64
city_name: Ahmedabad, group_tc: global-control
retention_segment
DORMANT     0.525833
HH          0.137664
GOLD        0.112963
SILVER      0.102039
PLATINUM    0.071512
ELITE       0.034876
INACTIVE    0.007849
PRIME       0.004349
UNKNOWN     0.002913
Name: proportion, dtype: float64

## Impact

In [138]:
df_final_sample.head()

,customer_id,city_name,customer_mobile,net_orders,bike_service,auto_service,cab_service,ltr_segment,retention_segment,lifetime_stage,service_affinity,gender,group_tc
522137,6598ef95cf9e6125cf442379,Delhi,7303914473,1,1,0,0,HH,DORMANT,DORMANT,ONLY_LINK,FEMALE,bau
3926858,638b423bc848b224a071f6fe,Delhi,9643142981,4,0,4,0,HH,HH,HANDHOLDING,ONLY_AUTO,MALE,bau
5239559,61a9ac3dd3152a8796c32fff,Delhi,8285406577,1,0,0,1,PHH,DORMANT,DORMANT,ONLY_CAB,MALE,bau
1990947,5e1b24c92f1e6d5f599c2628,Delhi,7017446338,49,47,2,0,PHH,PRIME,COMMITTED,ONLY_LINK,MALE,bau
6296015,6570747ea1d40e22896670e5,Delhi,9315031394,23,23,0,0,PHH,PLATINUM,COMMITTED,ONLY_LINK,MALE,bau

In [139]:
df_ads_data.head()

                     userId  impression_count  click_count
0  6358404085b3994aff50c48f                 2            0
1  665f898f3774472df1c78df9                 6            0
2  5de92b2a1a882e3354b48101                13            0
3  64cb72ba3525f250d8b40765                12            0
4  64f163d190e8ec48e3075be3                 5            0

In [140]:
df_ads_data.impression_count.sum()

17317599

In [141]:
df_ads_data.click_count.sum()

54420

In [142]:
df_final_check = pd.merge(df_final_sample, df_ads_data, how='left', left_on = 'customer_id', right_on = 'userId')

In [143]:
df_final_check

,customer_id,city_name,customer_mobile,net_orders,bike_service,auto_service,cab_service,ltr_segment,retention_segment,lifetime_stage,service_affinity,gender,group_tc,userId,impression_count,click_count
0,6598ef95cf9e6125cf442379,Delhi,7303914473,1,1,0,0,HH,DORMANT,DORMANT,ONLY_LINK,FEMALE,bau,NaN,NaN,NaN
1,638b423bc848b224a071f6fe,Delhi,9643142981,4,0,4,0,HH,HH,HANDHOLDING,ONLY_AUTO,MALE,bau,638b423bc848b224a071f6fe,5.0,0.0
2,61a9ac3dd3152a8796c32fff,Delhi,8285406577,1,0,0,1,PHH,DORMANT,DORMANT,ONLY_CAB,MALE,bau,61a9ac3dd3152a8796c32fff,3.0,0.0
3,5e1b24c92f1e6d5f599c2628,Delhi,7017446338,49,47,2,0,PHH,PRIME,COMMITTED,ONLY_LINK,MALE,bau,5e1b24c92f1e6d5f599c2628,5.0,0.0
4,6570747ea1d40e22896670e5,Delhi,9315031394,23,23,0,0,PHH,PLATINUM,COMMITTED,ONLY_LINK,MALE,bau,6570747ea1d40e22896670e5,4.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6251047,638ae927a92ee621cb567c71,Jaipur,8815384684,1,1,0,0,PHH,DORMANT,DORMANT,ONLY_LINK,MALE,global-control,NaN,NaN,NaN
6251048,642ecf6608ca753a9ed02a5b,Chennai,9611588056,2,1,1,0,HH,HH,HANDHOLDING,LINK_AUTO,UNKNOWN,global-control,642ecf6608ca753a9ed02a5b,5.0,0.0
6251049,660536309925a4199c0813f0,Jaipur,7014205283,1,1,0,0,HH,DORMANT,DORMANT,ONLY_LINK,FEMALE,global-control,660536309925a4199c0813f0,10.0,0.0
6251050,64b281d1d7d8b4354a1f2be7,Delhi,7024987977,4,0,1,3,PHH,ELITE,COMMITTED,ONLY_LINK,MALE,global-control,NaN,NaN,NaN
6251051,61b1f0e772f1dd522191fa30,Delhi,8448157221,1,1,0,0,PHH,DORMANT,DORMANT,ONLY_LINK,MALE,global-control,NaN,NaN,NaN

In [179]:
df = df_final_check.groupby(['city_name','group_tc']).agg(holdout_group_size = ('customer_id', 'nunique'),
                                                      actual_impact_customers = ('userId', 'nunique'),
                                                      expected_impact_on_impressions = ('impression_count', 'sum'),
                                                      expected_impact_on_clicks = ('click_count', 'sum'),
                                                     ).reset_index()

In [180]:
df

,city_name,group_tc,holdout_group_size,actual_impact_customers,expected_impact_on_impressions,expected_impact_on_clicks
0,Ahmedabad,bau,451835,129405,821784.0,2198.0
1,Ahmedabad,global-control,49432,14343,91582.0,255.0
2,Chennai,bau,1935131,696637,4488676.0,11849.0
3,Chennai,global-control,215122,77451,500480.0,1362.0
4,Delhi,bau,2600379,839090,5569483.0,17466.0
5,Delhi,global-control,289301,93198,619370.0,1921.0
6,Jaipur,bau,638601,198562,1249901.0,4935.0
7,Jaipur,global-control,71251,22360,141700.0,507.0

In [181]:
df[df['group_tc'] == 'global-control']

,city_name,group_tc,holdout_group_size,actual_impact_customers,expected_impact_on_impressions,expected_impact_on_clicks
1,Ahmedabad,global-control,49432,14343,91582.0,255.0
3,Chennai,global-control,215122,77451,500480.0,1362.0
5,Delhi,global-control,289301,93198,619370.0,1921.0
7,Jaipur,global-control,71251,22360,141700.0,507.0

### Export

In [77]:
df_final_sample.head(5)

,customer_id,city_name,customer_mobile,net_orders,bike_service,auto_service,cab_service,ltr_segment,retention_segment,lifetime_stage,service_affinity,gender,group_tc
4326368,6223172182ac75233c329aff,Delhi,9729107902,1,1,0,0,PHH,GOLD,HOOK,UNKNOWN,MALE,bau
1684258,6640bb47f05f5f69ea2cc7e8,Chennai,9884571371,2,0,2,0,HH,DORMANT,DORMANT,UNKNOWN,MALE,bau
7634220,5d21ea613b752c45cf9bda89,Chennai,8838376519,1,1,0,0,PHH,DORMANT,DORMANT,UNKNOWN,MALE,bau
5204993,5dae1ab3341b00418cf314ba,Delhi,8447667147,2,2,0,0,PHH,SILVER,HOOK,UNKNOWN,MALE,bau
574232,66212d931c347208039fd4fd,Chennai,9994441211,4,2,1,1,HH,DORMANT,DORMANT,UNKNOWN,MALE,bau

In [ ]:
# df_train_control['customer_mobile'] = df_train_control['customer_mobile'].astype(float).astype(int)

In [142]:
df_final_sample[df_final_sample['group_tc'] == 'global-control'].to_csv(local_datasource + '/processed/global-control/export.csv', index=False)

In [78]:
df_export = df_final_sample[df_final_sample['group_tc'] == 'global-control']

In [79]:
df_export.shape

(1528494, 13)

In [80]:
df_export.head(5)

,customer_id,city_name,customer_mobile,net_orders,bike_service,auto_service,cab_service,ltr_segment,retention_segment,lifetime_stage,service_affinity,gender,group_tc
7497689,6454c264309f65666beb650b,Delhi,8595191382,1,1,0,0,PHH,SILVER,HOOK,UNKNOWN,UNKNOWN,global-control
3653559,6686dbde25346979e1800542,Chennai,9894117183,1,0,1,0,HH,HH,HANDHOLDING,UNKNOWN,MALE,global-control
3721628,623980b26b6b64a1ac737f9f,Ahmedabad,8104300530,1,1,0,0,PHH,DORMANT,DORMANT,UNKNOWN,MALE,global-control
2556893,613c7d987f5ff756b70258fa,Delhi,7357300227,27,11,16,0,PHH,DORMANT,DORMANT,LINK_AUTO,MALE,global-control
2409427,63801ef42519f5a2f214a4bd,Delhi,9315385605,1,0,1,0,PHH,DORMANT,DORMANT,UNKNOWN,MALE,global-control

In [81]:
df_export\
.groupby(['city_name'])\
.agg(**agg_dict)\
.reset_index()

   city_name  customers  net_orders  bike_service  auto_service  cab_service
0  Ahmedabad     122783      670507        384637        202529        83341
1    Chennai     512888     3751285       1466674       2042720       241891
2      Delhi     727313     4813154       3067458       1093417       652279
3     Jaipur     165510      748142        460530        284136         3476

In [49]:
df_final_sample[['city_name', 'customer_mobile']]

,customer_id,city_name,customer_mobile,net_orders,bike_service,auto_service,cab_service,ltr_segment,retention_segment,lifetime_stage,service_affinity,gender,group_tc
4326368,6223172182ac75233c329aff,Delhi,9729107902,1,1,0,0,PHH,GOLD,HOOK,UNKNOWN,MALE,bau
1684258,6640bb47f05f5f69ea2cc7e8,Chennai,9884571371,2,0,2,0,HH,DORMANT,DORMANT,UNKNOWN,MALE,bau
7634220,5d21ea613b752c45cf9bda89,Chennai,8838376519,1,1,0,0,PHH,DORMANT,DORMANT,UNKNOWN,MALE,bau
5204993,5dae1ab3341b00418cf314ba,Delhi,8447667147,2,2,0,0,PHH,SILVER,HOOK,UNKNOWN,MALE,bau
574232,66212d931c347208039fd4fd,Chennai,9994441211,4,2,1,1,HH,DORMANT,DORMANT,UNKNOWN,MALE,bau
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3143675,6579e1919ca9566fe57f7dd6,Delhi,9250772495,2,2,0,0,HH,HH,HANDHOLDING,UNKNOWN,MALE,global-control
5678032,65f111740f9aeb550a5078c6,Delhi,9310235717,19,17,1,1,PHH,PLATINUM,SOFT_CHURN,ONLY_LINK,MALE,global-control
4308324,6631ef1e8dcc25a0392893ac,Delhi,8920732163,2,0,0,2,HH,DORMANT,DORMANT,UNKNOWN,MALE,global-control
1166382,630cec50744a5c3d14817530,Chennai,6385554331,19,0,13,6,PHH,PLATINUM,COMMITTED,AUTO_CAB,FEMALE,global-control
1717708,645ca8778e5481c84307fbc4,Ahmedabad,9558477290,10,0,10,0,PHH,GOLD,HOOK,ONLY_AUTO,MALE,global-control

In [82]:
local_datasource

'/Users/E2074/local-datasets/customer/ads-monetisation/holdout-group'

In [96]:
print(df_export[df_export['city_name'] == 'Jaipur'].customer_id.nunique())
print(df_export[df_export['city_name'] == 'Jaipur'].customer_id.shape[0])

165510
165510

In [97]:
df_export[df_export['city_name'] == 'Jaipur'][['customer_mobile']]\
.to_csv(local_datasource + '/processed/jas_jaipur_holdout_group.csv', header=False, index=False)

In [101]:
df_chennai = df_export[df_export['city_name'] == 'Chennai'][['customer_mobile']]
df_delhi = df_export[df_export['city_name'] == 'Delhi'][['customer_mobile']]

In [118]:
df_chennai.reset_index(drop=True, inplace=True)
df_delhi.reset_index(drop=True, inplace=True)

In [120]:
df_chennai.shape,df_delhi.shape

((512888, 1), (727313, 1))

In [121]:
local_datasource

'/Users/E2074/local-datasets/customer/ads-monetisation/holdout-group'

In [130]:
df_chennai

       customer_mobile
0           9894117183
1           9962437599
2           9790935181
3           9840963627
4           7397259555
...                ...
512883      9344221351
512884      9566838593
512885      7538810742
512886      8098372820
512887      6385554331

[512888 rows x 1 columns]

In [175]:
def df_split(df,city):
    
    chunk_size = len(df) // 5
    
    for i in range(5):
        start = i * chunk_size
        end = (i + 1) * chunk_size if i < 4 else len(df)
        chunk = df.iloc[start:end]
        chunk.to_csv(f'/Users/E2074/local-datasets/customer/ads-monetisation/holdout-group/processed/jas_{city}_holdout_group_{i+1}.csv', 
                     header=False,
                     index=False)

In [136]:
df_split(df_chennai,'chennai')

In [176]:
df_split(df_delhi,'delhi')

In [8]:
test_df1 = pd.read_csv(local_datasource+'/processed/jas_delhi_holdout_group_1.csv')
test_df2 = pd.read_csv(local_datasource+'/processed/jas_delhi_holdout_group_2.csv')
test_df3 = pd.read_csv(local_datasource+'/processed/jas_delhi_holdout_group_3.csv')
test_df4 = pd.read_csv(local_datasource+'/processed/jas_delhi_holdout_group_4.csv')
test_df5 = pd.read_csv(local_datasource+'/processed/jas_delhi_holdout_group_5.csv')

In [9]:
test_df1.shape,test_df2.shape,test_df3.shape,test_df4.shape,test_df5.shape

((145461, 1), (145461, 1), (145461, 1), (145461, 1), (145464, 1))

In [179]:
test_df = pd.concat([test_df1,test_df2,test_df3,test_df4, test_df5], axis=0)

In [180]:
test_df.shape

(727308, 5)

In [181]:
test_df

          8595191382  9953968998  9027049041  7982811816    9990911331
0       7.357300e+09         NaN         NaN         NaN           NaN
1       9.315386e+09         NaN         NaN         NaN           NaN
2       9.387284e+09         NaN         NaN         NaN           NaN
3       9.015363e+09         NaN         NaN         NaN           NaN
4       8.595711e+09         NaN         NaN         NaN           NaN
...              ...         ...         ...         ...           ...
145459           NaN         NaN         NaN         NaN  7.014382e+09
145460           NaN         NaN         NaN         NaN  8.826965e+09
145461           NaN         NaN         NaN         NaN  9.250772e+09
145462           NaN         NaN         NaN         NaN  9.310236e+09
145463           NaN         NaN         NaN         NaN  8.920732e+09

[727308 rows x 5 columns]