## Imports

In [1]:
import os
import warnings
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from scipy import stats
from pyhive import presto
from datetime import datetime, date, timedelta

import warnings
warnings.filterwarnings('ignore')

In [2]:
pd.set_option('display.max_columns', 50)
pd.set_option('display.max_rows', 300)

In [3]:
## Connection
connection = presto.connect(
        host='presto-gateway.serving.data.production.internal',
#     processing-2.processing.data.production.internal
#     presto-gateway.serving.data.production.internal
        port=80,
        protocol='http',
        catalog='hive',
        username='manoj.ravirajan@rapido.bike'
)

## Datasets & Parameter

In [27]:
## Parameter 
start_date='2024-04-23'
end_date='2024-05-08'

In [28]:
city_name=['Bangalore']
service_level=['Auto','CabEconomy']

## Fetching data

In [49]:
def route_adherence_func(start_date, end_date, city_name, service_name):

    route_adherence_query = f"""
        WITH service_mapping AS (

            SELECT 
                service_detail_id,
                service_level as service_name,
                service_category,
                service_id,
                city_display_name as city,
                city_id
            FROM 
                datasets.service_mapping
            WHERE 
                city_display_name = '{city_name}'
                and service_level = '{service_name}'
            ),

            fe_tbl as (
            
            SELECT
                fare_estimate_id fid,
                api_context,final_amount as final_amount_fare,
                date_format(from_unixtime(epoch / 1000, 'Asia/Kolkata'), '%Y-%m-%d') AS order_date,
                cast(final_amount AS double) AS fe_amount,service_detail_id as service_id_fare,
                epoch fe,ride_distance as d1, estimated_ride_time as t1
            FROM
                pricing.fare_estimates_enriched 
            WHERE 
                yyyymmdd BETWEEN DATE_FORMAT(date('{start_date}'),'%Y%m%d') 
                AND DATE_FORMAT(date('{end_date}'),'%Y%m%d') 
                AND city IN (SELECT city FROM service_mapping)
                AND service_name IN (SELECT service_name FROM service_mapping)
            ),


            orderlogs as (
            
            SELECT 
                *,
                u.id_array as fare_estimate_id
            FROM 
                ( 
                SELECT 
                    order_id, (amount-prev_due) as order_amount,
                    customer_id,captain_id,
                    date_format(from_unixtime(epoch / 1000, 'Asia/Kolkata'), '%Y-%m-%d') AS orderdate,
                    epoch,estimate_id,estimate_ids,ride_time as t3,
                    fare_recalculated_reason, 
                    all_paths,
                    spd_fraud_flag,order_status,
                    service_obj_service_name as service_name,
                    fare_recalculated_diff_amount AS fe_re_diff_amount,service_detail_id,
                    cast(json_parse(estimate_ids) as array<varchar>) AS id_array
                FROM 
                    orders.order_logs_snapshot
                WHERE 
                    yyyymmdd BETWEEN DATE_FORMAT(date('{start_date}'),'%Y%m%d') 
                    AND DATE_FORMAT(date('{end_date}'),'%Y%m%d') 
                    AND city_name IN (SELECT city FROM service_mapping)
                    AND service_obj_service_name IN (SELECT service_name FROM service_mapping)
                ) as t
                CROSS JOIN UNNEST(t.id_array) AS u(id_array)
            ),
            
            immutable AS (
            
            SELECT 
                DATE_FORMAT(DATE_PARSE(yyyymmdd, '%Y%m%d'), '%Y-%m-%d') orderdate,
                order_id,
                cast (event_time as double) event_time
            FROM 
                orders.order_logs_immutable 
            WHERE 
                yyyymmdd BETWEEN DATE_FORMAT(date('{start_date}'),'%Y%m%d') 
                AND DATE_FORMAT(date('{end_date}'),'%Y%m%d') 
                AND event_type = 'started'
                AND city_name IN (SELECT city FROM service_mapping)
                AND service_obj_service_name IN (SELECT service_name FROM service_mapping)
            ),

            nav_metrics AS (
            
            SELECT
                *
            FROM
                (
                SELECT 
                    event_props_order_id,
                    case when device_info_app_version>='5.3.22' then 'Above 5.3.22' else 'Below 5.3.22' end as app_version_type,
                    case when device_info_app_version>='5.3.24' then 'Above 5.3.24' else 'Below 5.3.24' end as app_optimal_version_type,
                    cast  (event_props_epoch as double) event_props_epoch,
                    DATE_FORMAT(DATE_PARSE(yyyymmdd, '%Y%m%d'), '%Y-%m-%d') orderdate,
                    try(cast(event_props_distance_in_meters as double) )/ 1000 d2,
                    row_number() over(partition by yyyymmdd, event_props_order_id order by event_props_epoch) rn
                FROM
                    clevertap.captain_inappnavmetrics_immutable
                WHERE 
                    yyyymmdd BETWEEN DATE_FORMAT(date('{start_date}'),'%Y%m%d') 
                AND DATE_FORMAT(date('{end_date}'),'%Y%m%d') 
                AND event_props_order_status = 'started'
                AND event_props_city IN  (SELECT city FROM service_mapping)
                )        
            WHERE 
                rn = 1
            ), 

            distance2 AS (
            
            SELECT 
                orderdate,
                order_id,
                app_version_type,
                app_optimal_version_type,
                d2
            FROM 
                ( 
                SELECT 
                    imu.orderdate,
                    imu.order_id,
                    app_version_type,
                     app_optimal_version_type,
                    date_diff('minute', from_unixtime(event_time/1000), from_unixtime(event_props_epoch/1000)) AS minDiff,
                    "d2"
                FROM 
                    immutable imu 
                JOIN 
                    nav_metrics nav 
                    ON imu.order_id = nav.event_props_order_id
                )
                --and event_props_epoch >= event_time )
                
            WHERE abs(minDiff) <= 1 -- Relaxing threshold
            
            ),
            
            done as (
            
            SELECT 
                DISTINCT order_id,
                d1,t1,t3,
                epoch,fare_recalculated_reason,
                service_name,rn,
                api_context, (
                fe_amount-order_amount) as amt_diff, 
                all_paths,fid,
                spd_fraud_flag,
                order_status,
                orderdate
            FROM 
                (
                SELECT 
                    *,
                    row_number () over(partition by order_id order by fe) rn 
                FROM 
                    (
                    SELECT 
                        *
                    FROM 
                        orderlogs 
                    JOIN 
                        fe_tbl
                        ON fare_estimate_id = fid 
                        AND service_detail_id = service_id_fare
                    )
                )
            WHERE rn =1
            ),
            
            dthree as (
            
            SELECT 
                DISTINCT order_id, 
                CASE
                    WHEN selectedroute = 'hFRoute' THEN hfdistance
                    WHEN selectedroute = 'actualRoute' THEN directionsresponsedistance
                    WHEN selectedroute = 'estimatedRoute' THEN final_estimated_directions_response_distance
                    ELSE NULL -- Handle other cases if needed
                END AS d3, 
                selectedroute
            FROM
                (
                SELECT 
                    * 
                FROM 
                    (
                    SELECT  
                        *, 
                        row_number () over(partition by order_id order by updatedAt) rn 
                    FROM 
                        (
                         SELECT 
                             yyyymmdd,orderid as order_id, 
                             cast(hfdistance as double)*1000 as hfdistance,
                             cast(pingdensity as double)*100 as pingdensity,
                             cast(directionsresponsedistance as double) as directionsresponsedistance,
                             cast(final_estimated_directions_response_distance as double) as final_estimated_directions_response_distance,
                             selectedroute,updatedAt
                         FROM 
                             raw.captain_distance_response
                         WHERE 
                             yyyymmdd BETWEEN DATE_FORMAT(date('{start_date}'),'%Y%m%d') 
                             AND DATE_FORMAT(date('{end_date}'),'%Y%m%d') 
                        )
                    )
                WHERE 
                    rn = 1
                )
            ),

            merged_tbl as (
            
            SELECT 
                done.order_id,
                done.orderdate,
                d2,d3,d1,
                app_version_type,
                app_optimal_version_type,
                fare_recalculated_reason,spd_fraud_flag,
                order_status,service_name,
                CASE
                WHEN d2 IS NOT NULL then d1-d2 END AS fe_vs_nav,
                d1-(d3*1.00/1000.00) as Est_Nav,
                CASE WHEN d2 IS NOT NULL then d2-(d3*1.00/1000.00) END AS nav_actual
            FROM 
                done
            LEFT JOIN 
                dthree
                ON done.order_id = dthree.order_id
            LEFT JOIN distance2
                ON done.order_id=distance2.order_id
            )


            SELECT 
                service_name,
                orderdate,
                CASE 
                WHEN orderdate >= ('2024-04-23') and (orderdate<='2024-04-28') then 'pre' 
                WHEN orderdate>=('2024-05-03') THEN 'post' end as new_date_type,
                app_version_type,
                count(distinct order_id) as gross_orders,
                count(distinct case when order_status='dropped' and spd_fraud_flag!=True then order_id end) as net_orders,
                (count(distinct case when order_status='dropped' and spd_fraud_flag!=True then order_id end)*100.00)/(count (distinct order_id)) as "G2N",
                count(distinct case when order_status='dropped' and spd_fraud_flag!=True and fare_recalculated_reason='routeDiff' then order_id end) as route_diff_orders,
                (count(distinct case when order_status='dropped' and spd_fraud_flag!=True and fe_vs_nav_bucket='a. Within_500_m' then order_id end)*100.00)/(count( distinct order_id)) as fe_nav_bucket_within_500m_percent,
                (count(distinct case when order_status='dropped' and spd_fraud_flag!=True and nav_actual_bucket='a. Within_500_m' then order_id end)*100.00)/(count( distinct order_id)) as nav_actual_bucket_within_500m_percent,



                count(distinct case when order_status='dropped' and spd_fraud_flag!=True and fe_vs_nav_bucket='a. Within_500_m' then order_id end) as fe_nav_bucket_within_500m,
                count(distinct case when order_status='dropped' and spd_fraud_flag!=True and fe_vs_nav_bucket='b. Less_than_500m' then order_id end) as fe_nav_bucket_less_500m,
                count(distinct case when order_status='dropped' and spd_fraud_flag!=True and fe_vs_nav_bucket='c. Greater_than_500m' then order_id end) as fe_nav_bucket_grt_500m,

                count(distinct case when order_status='dropped' and spd_fraud_flag!=True and nav_actual_bucket='a. Within_500_m' then order_id end) as nav_actual_bucket_within_500m,
                count(distinct case when order_status='dropped' and spd_fraud_flag!=True and nav_actual_bucket='b. Less_than_500m' then order_id end) as nav_actual_bucket_less_500m,
                count(distinct case when order_status='dropped' and spd_fraud_flag!=True and nav_actual_bucket='c. Greater_than_500m' then order_id end) as nav_actual_bucket_grt_500m,

                count(distinct case when order_status='dropped' and spd_fraud_flag!=True and Est_Nav_bucket='a. Within_500_m' then order_id end) as Est_Nav_bucket_within_500m,
                count(distinct case when order_status='dropped' and spd_fraud_flag!=True and Est_Nav_bucket='b. Less_than_500m' then order_id end) as Est_Nav_bucket_less_500m,
                count(distinct case when order_status='dropped' and spd_fraud_flag!=True and Est_Nav_bucket='c. Greater_than_500m' then order_id end) as Est_Nav_bucket_grt_500m


            FROM
                (
                SELECT 
                    *,
                    CASE 
                        WHEN d2 is not NULL and fe_vs_nav>=-0.5 and fe_vs_nav<=0.5 then 'a. Within_500_m'
                        WHEN d2 is not NULL and fe_vs_nav<-0.5 then 'b. Less_than_500m'
                        WHEN d2 is not NULL and fe_vs_nav>0.5 then 'c. Greater_than_500m' end as fe_vs_nav_bucket,
                    CASE 
                        WHEN d2 is not NULL and nav_actual>=-0.5 and nav_actual<=0.5 then 'a. Within_500_m'
                        WHEN d2 is not NULL and nav_actual<-0.5 then 'b. Less_than_500m'
                        WHEN d2 is not NULL and nav_actual>0.5 then 'c. Greater_than_500m' end as nav_actual_bucket,
                    CASE 
                        WHEN Est_Nav>=-0.5 and Est_Nav<=0.5 then 'a. Within_500_m'
                        WHEN Est_Nav<-0.5 then 'b. Less_than_500m'
                        WHEN Est_Nav>0.5 then 'c. Greater_than_500m' end as Est_Nav_bucket
                FROM
                    merged_tbl
                GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14
                )
            GROUP BY 1,2,3,4
            ORDER BY 2
    """
    df_route_adherence = pd.read_sql(route_adherence_query,connection)
    
    return df_route_adherence

In [50]:
total_df_d1_d2 = pd.DataFrame()


for city in city_name:
    print(city)
    
    for service_name in service_level:
        print(service_name)
        
        df_temp = route_adherence_func(start_date,end_date, city, service_name)
        
        df_temp['distance_type']='second_longest'
        df_temp['fe_nav_bucket_within_500m_percent']=((df_temp['fe_nav_bucket_within_500m']*100.00)/df_temp['net_orders']).round(2)
        df_temp['nav_actual_bucket_within_500m_percent']=((df_temp['nav_actual_bucket_within_500m']*100.00)/df_temp['net_orders']).round(2)
        df_temp['route_diff_percent']=((df_temp['route_diff_orders']*100.00)/df_temp['net_orders']).round(2)
        
        total_df_d1_d2=pd.concat([total_df_d1_d2,df_temp])

Bangalore
Auto
CabEconomy

## Analysis

In [51]:
total_df_d1_d2['service_name'].unique()

array(['Auto', 'CabEconomy'], dtype=object)

In [52]:
total_df_d1_d2.shape

(96, 21)

In [53]:
total_df_d1_d2.head(5)

,service_name,orderdate,new_date_type,app_version_type,gross_orders,net_orders,G2N,route_diff_orders,fe_nav_bucket_within_500m_percent,nav_actual_bucket_within_500m_percent,fe_nav_bucket_within_500m,fe_nav_bucket_less_500m,fe_nav_bucket_grt_500m,nav_actual_bucket_within_500m,nav_actual_bucket_less_500m,nav_actual_bucket_grt_500m,Est_Nav_bucket_within_500m,Est_Nav_bucket_less_500m,Est_Nav_bucket_grt_500m,distance_type,route_diff_percent
0,Auto,2024-04-23,pre,None,200593,4170,2.08,992,0.00,0.00,0,0,0,0,0,0,3031,316,823,second_longest,23.79
1,Auto,2024-04-23,pre,Above 5.3.22,40122,39998,99.69,9558,86.33,71.37,34531,2788,2679,28548,3173,8274,29008,3136,7851,second_longest,23.90
2,Auto,2024-04-23,pre,Below 5.3.22,94762,94470,99.69,22532,81.42,67.22,76914,6520,11036,63505,12476,18484,68708,7696,18061,second_longest,23.85
3,Auto,2024-04-24,pre,Below 5.3.22,98399,98089,99.68,20753,81.82,70.31,80253,7069,10767,68969,14032,15081,74367,9615,14099,second_longest,21.16
4,Auto,2024-04-24,pre,None,200886,4062,2.02,812,0.00,0.00,0,0,0,0,0,0,3128,357,577,second_longest,19.99

In [54]:
total_df_d1_d2

,service_name,orderdate,new_date_type,app_version_type,gross_orders,net_orders,G2N,route_diff_orders,fe_nav_bucket_within_500m_percent,nav_actual_bucket_within_500m_percent,fe_nav_bucket_within_500m,fe_nav_bucket_less_500m,fe_nav_bucket_grt_500m,nav_actual_bucket_within_500m,nav_actual_bucket_less_500m,nav_actual_bucket_grt_500m,Est_Nav_bucket_within_500m,Est_Nav_bucket_less_500m,Est_Nav_bucket_grt_500m,distance_type,route_diff_percent
0,Auto,2024-04-23,pre,None,200593,4170,2.08,992,0.00,0.00,0,0,0,0,0,0,3031,316,823,second_longest,23.79
1,Auto,2024-04-23,pre,Above 5.3.22,40122,39998,99.69,9558,86.33,71.37,34531,2788,2679,28548,3173,8274,29008,3136,7851,second_longest,23.90
2,Auto,2024-04-23,pre,Below 5.3.22,94762,94470,99.69,22532,81.42,67.22,76914,6520,11036,63505,12476,18484,68708,7696,18061,second_longest,23.85
3,Auto,2024-04-24,pre,Below 5.3.22,98399,98089,99.68,20753,81.82,70.31,80253,7069,10767,68969,14032,15081,74367,9615,14099,second_longest,21.16
4,Auto,2024-04-24,pre,None,200886,4062,2.02,812,0.00,0.00,0,0,0,0,0,0,3128,357,577,second_longest,19.99
5,Auto,2024-04-24,pre,Above 5.3.22,40140,40024,99.71,8384,86.45,74.11,34602,3020,2402,29661,3692,6663,30443,3784,5789,second_longest,20.95
6,Auto,2024-04-25,pre,Below 5.3.22,103212,102889,99.69,21780,81.31,69.62,83654,7696,11540,71631,14288,16963,77965,9470,15446,second_longest,21.17
7,Auto,2024-04-25,pre,None,265454,4192,1.58,892,0.00,0.00,0,0,0,0,0,0,3168,381,643,second_longest,21.28
8,Auto,2024-04-25,pre,Above 5.3.22,49087,48944,99.71,10500,85.46,73.07,41827,3874,3243,35765,4746,8427,36922,4640,7376,second_longest,21.45
9,Auto,2024-04-26,pre,None,153214,3176,2.07,641,0.00,0.00,0,0,0,0,0,0,2458,280,438,second_longest,20.18
10,Auto,2024-04-26,pre,Above 5.3.22,54123,53953,99.69,11242,87.05,74.42,46967,4182,2805,40154,4750,9046,41385,5004,7560,second_longest,20.84
11,Auto,2024-04-26,pre,Below 5.3.22,57679,57506,99.70,12077,82.13,70.19,47232,4193,6082,40363,8070,9071,44148,5414,7942,second_longest,21.00
12,Auto,2024-04-27,pre,Below 5.3.22,48671,48531,99.71,9862,82.05,70.56,39820,3275,5436,34243,7020,7267,37520,4430,6579,second_longest,20.32
13,Auto,2024-04-27,pre,Above 5.3.22,89578,89296,99.69,18336,87.35,75.14,78000,6619,4677,67093,7835,14363,68840,8266,12185,second_longest,20.53
14,Auto,2024-04-27,pre,None,148742,3759,2.53,783,0.00,0.00,0,0,0,0,0,0,2896,325,538,second_longest,20.83
15,Auto,2024-04-28,pre,Above 5.3.22,109967,109594,99.66,23347,86.56,74.44,94865,8861,5868,81584,9874,18126,83687,10594,15303,second_longest,21.30
16,Auto,2024-04-28,pre,Below 5.3.22,16363,16292,99.57,3454,79.93,69.25,13023,1220,2049,11282,2600,2410,12503,1621,2168,second_longest,21.20
17,Auto,2024-04-28,pre,None,137434,3627,2.64,734,0.00,0.00,0,0,0,0,0,0,2808,349,470,second_longest,20.24
18,Auto,2024-04-29,None,Above 5.3.22,131334,130940,99.70,25347,87.46,75.31,114525,10264,6151,98612,10902,21415,102171,11637,17121,second_longest,19.36
19,Auto,2024-04-29,None,Below 5.3.22,11871,11827,99.63,2146,81.81,70.50,9676,806,1345,8338,1778,1708,9372,1025,1427,second_longest,18.14
20,Auto,2024-04-29,None,None,184541,4209,2.28,759,0.00,0.00,0,0,0,0,0,0,3324,370,515,second_longest,18.03
21,Auto,2024-04-30,None,Below 5.3.22,9991,9954,99.63,1773,82.13,71.07,8175,651,1129,7074,1476,1403,7918,837,1198,second_longest,17.81
22,Auto,2024-04-30,None,None,194428,4094,2.11,756,0.00,0.00,0,0,0,0,0,0,3212,381,501,second_longest,18.47
23,Auto,2024-04-30,None,Above 5.3.22,130875,130502,99.71,25194,87.77,75.44,114538,10616,5348,98454,10849,21184,101553,12160,16774,second_longest,19.31
24,Auto,2024-05-01,None,Above 5.3.22,126200,125638,99.55,25149,87.61,75.87,110077,10762,4799,95320,9952,20359,97843,11767,16021,second_longest,20.02
25,Auto,2024-05-01,None,Below 5.3.22,7783,7748,99.55,1472,81.84,70.69,6341,559,848,5477,1161,1109,6119,700,928,second_longest,19.00
26,Auto,2024-05-01,None,None,130880,3733,2.85,688,0.00,0.00,0,0,0,0,0,0,2953,336,444,second_longest,18.43
27,Auto,2024-05-02,None,Above 5.3.22,140583,140119,99.67,28340,87.42,74.97,122492,10614,7013,105049,11036,24009,107557,11836,20701,second_longest,20.23
28,Auto,2024-05-02,None,Below 5.3.22,7898,7873,99.68,1683,78.79,68.17,6203,544,1126,5367,1248,1258,5971,674,1228,second_longest,21.38
29,Auto,2024-05-02,None,None,259841,4312,1.66,852,0.00,0.00,0,0,0,0,0,0,3325,385,601,second_longest,19.76
30,Auto,2024-05-03,post,Below 5.3.22,7594,7566,99.63,1623,77.57,69.85,5869,455,1242,5285,1074,1199,5705,476,1377,second_longest,21.45
31,Auto,2024-05-03,post,None,200123,4406,2.20,901,0.00,0.00,0,0,0,0,0,0,3349,320,732,second_longest,20.45
32,Auto,2024-05-03,post,Above 5.3.22,141165,140684,99.66,28656,90.84,75.26,127795,7705,5184,105885,9708,24972,107420,10069,23076,second_longest,20.37
33,Auto,2024-05-04,post,Below 5.3.22,6668,6635,99.51,1539,75.60,68.43,5016,392,1227,4540,1070,1024,4902,458,1274,second_longest,23.20
34,Auto,2024-05-04,post,None,181357,4337,2.39,923,0.00,0.00,0,0,0,0,0,0,3304,303,729,second_longest,21.28
35,Auto,2024-05-04,post,Above 5.3.22,147054,146561,99.66,30357,90.76,75.43,133020,8040,5501,110545,10670,25323,112071,11084,23383,second_longest,20.71
36,Auto,2024-05-05,post,Below 5.3.22,4994,4973,99.58,1156,75.71,68.57,3765,291,917,3410,803,760,3666,364,943,second_longest,23.25
37,Auto,2024-05-05,post,None,164821,3652,2.22,805,0.00,0.00,0,0,0,0,0,0,2759,267,626,second_longest,22.04
38,Auto,2024-05-05,post,Above 5.3.22,129049,128607,99.66,26857,91.20,76.06,117291,6950,4366,97823,8768,21996,98602,9538,20447,second_longest,20.88
39,Auto,2024-05-06,post,Below 5.3.22,5284,5263,99.60,1127,77.43,69.33,4075,290,898,3649,806,807,3943,383,936,second_longest,21.41
40,Auto,2024-05-06,post,None,304324,4343,1.43,900,0.00,0.00,0,0,0,0,0,0,3300,311,732,second_longest,20.72
41,Auto,2024-05-06,post,Above 5.3.22,148951,148397,99.63,30475,90.57,75.34,134397,8254,5746,111801,10649,25929,113108,11133,24138,second_longest,20.54
42,Auto,2024-05-07,post,Above 5.3.22,128877,128447,99.67,25463,90.83,76.25,116669,7082,4696,97943,8428,22058,99053,8929,20447,second_longest,19.82
43,Auto,2024-05-07,post,Below 5.3.22,4144,4121,99.44,864,78.04,70.69,3216,254,651,2913,592,616,3111,294,716,second_longest,20.97
44,Auto,2024-05-07,post,None,185792,3638,1.96,717,0.00,0.00,0,0,0,0,0,0,2799,259,579,second_longest,19.71
45,Auto,2024-05-08,post,Below 5.3.22,4164,4145,99.54,898,76.28,69.02,3162,258,725,2861,647,634,3089,301,752,second_longest,21.66
46,Auto,2024-05-08,post,Above 5.3.22,137948,137425,99.62,28043,90.11,74.94,123829,7922,5674,102986,10018,24172,104350,10445,22381,second_longest,20.41
47,Auto,2024-05-08,post,None,266577,4221,1.58,889,0.00,0.00,0,0,0,0,0,0,3142,306,682,second_longest,21.06
0,CabEconomy,2024-04-23,pre,Below 5.3.22,13517,13497,99.85,4638,78.40,62.89,10581,1121,1795,8488,2692,2317,8606,2287,2604,second_longest,34.36
1,CabEconomy,2024-04-23,pre,None,20571,654,3.18,235,0.00,0.00,0,0,0,0,0,0,406,115,133,second_longest,35.93
2,CabEconomy,2024-04-23,pre,Above 5.3.22,6142,6134,99.87,2034,81.89,65.24,5023,503,609,4002,1024,1108,3935,1027,1171,second_longest,33.16
3,CabEconomy,2024-04-24,pre,Above 5.3.22,5975,5969,99.90,1979,81.62,66.31,4872,529,568,3958,1127,884,3851,1171,947,second_longest,33.15
4,CabEconomy,2024-04-24,pre,None,20735,660,3.18,224,0.00,0.00,0,0,0,0,0,0,415,120,125,second_longest,33.94
5,CabEconomy,2024-04-24,pre,Below 5.3.22,14574,14556,99.88,4870,78.63,63.33,11446,1201,1910,9218,3295,2044,9352,2908,2296,second_longest,33.46
6,CabEconomy,2024-04-25,pre,Below 5.3.22,15650,15636,99.91,5044,77.44,63.23,12108,1387,2141,9886,3420,2330,10218,2944,2474,second_longest,32.26
7,CabEconomy,2024-04-25,pre,None,29457,709,2.41,198,0.00,0.00,0,0,0,0,0,0,486,118,105,second_longest,27.93
8,CabEconomy,2024-04-25,pre,Above 5.3.22,7413,7404,99.88,2318,80.63,66.77,5970,669,765,4944,1357,1101,4889,1366,1147,second_longest,31.31
9,CabEconomy,2024-04-26,pre,None,24752,494,2.00,175,0.00,0.00,0,0,0,0,0,0,302,82,110,second_longest,35.43
10,CabEconomy,2024-04-26,pre,Below 5.3.22,9495,9486,99.91,2983,79.05,63.71,7499,839,1148,6044,2033,1408,6254,1786,1445,second_longest,31.45
11,CabEconomy,2024-04-26,pre,Above 5.3.22,9100,9093,99.92,2795,82.61,67.73,7512,815,766,6159,1596,1338,6055,1679,1359,second_longest,30.74
12,CabEconomy,2024-04-27,pre,None,25511,609,2.39,196,0.00,0.00,0,0,0,0,0,0,399,115,95,second_longest,32.18
13,CabEconomy,2024-04-27,pre,Below 5.3.22,7216,7209,99.90,2318,79.19,63.12,5709,576,924,4550,1704,954,4730,1428,1050,second_longest,32.15
14,CabEconomy,2024-04-27,pre,Above 5.3.22,14353,14327,99.82,4438,83.01,67.75,11893,1202,1232,9706,2580,2040,9595,2653,2078,second_longest,30.98
15,CabEconomy,2024-04-28,pre,Above 5.3.22,18717,18697,99.89,5925,81.97,67.21,15326,1744,1627,12566,3357,2772,12298,3540,2857,second_longest,31.69
16,CabEconomy,2024-04-28,pre,Below 5.3.22,2541,2540,99.96,854,75.20,61.18,1910,246,384,1554,642,344,1618,521,401,second_longest,33.62
17,CabEconomy,2024-04-28,pre,None,32675,693,2.12,210,0.00,0.00,0,0,0,0,0,0,468,121,104,second_longest,30.30
18,CabEconomy,2024-04-29,None,Above 5.3.22,19825,19810,99.92,5908,83.22,67.99,16485,1855,1470,13469,3456,2884,13351,3693,2765,second_longest,29.82
19,CabEconomy,2024-04-29,None,None,23445,651,2.78,190,0.00,0.00,0,0,0,0,0,0,433,114,104,second_longest,29.19
20,CabEconomy,2024-04-29,None,Below 5.3.22,1316,1313,99.77,391,79.89,62.76,1049,93,171,824,322,167,886,252,175,second_longest,29.78
21,CabEconomy,2024-04-30,None,None,20652,673,3.26,196,0.00,0.00,0,0,0,0,0,0,457,112,104,second_longest,29.12
22,CabEconomy,2024-04-30,None,Below 5.3.22,1085,1082,99.72,357,79.57,61.00,861,87,134,660,261,161,710,207,165,second_longest,32.99
23,CabEconomy,2024-04-30,None,Above 5.3.22,20447,20421,99.87,6046,82.77,68.76,16903,2191,1327,14042,3193,3184,13906,3709,2804,second_longest,29.61
24,CabEconomy,2024-05-01,None,Below 5.3.22,986,985,99.90,301,79.70,62.03,785,75,125,611,247,127,663,202,120,second_longest,30.56
25,CabEconomy,2024-05-01,None,None,22211,668,3.01,206,0.00,0.00,0,0,0,0,0,0,441,127,100,second_longest,30.84
26,CabEconomy,2024-05-01,None,Above 5.3.22,21217,21194,99.89,6388,83.11,68.91,17614,2302,1278,14605,3408,3180,14288,4065,2840,second_longest,30.14
27,CabEconomy,2024-05-02,None,None,28888,746,2.58,241,0.00,0.00,0,0,0,0,0,0,485,156,105,second_longest,32.31
28,CabEconomy,2024-05-02,None,Above 5.3.22,22196,22175,99.91,6714,83.28,69.09,18468,2119,1588,15320,3414,3438,14998,3818,3356,second_longest,30.28
29,CabEconomy,2024-05-02,None,Below 5.3.22,817,816,99.88,245,76.47,63.36,624,65,128,517,195,105,553,143,120,second_longest,30.02
30,CabEconomy,2024-05-03,post,Below 5.3.22,764,763,99.87,245,71.30,65.01,544,50,169,496,167,100,498,119,146,second_longest,32.11
31,CabEconomy,2024-05-03,post,Above 5.3.22,22431,22409,99.90,6207,87.42,70.92,19590,1633,1186,15892,2916,3592,15791,3137,3472,second_longest,27.70
32,CabEconomy,2024-05-03,post,None,23123,697,3.01,192,0.00,0.00,0,0,0,0,0,0,485,91,119,second_longest,27.55
33,CabEconomy,2024-05-04,post,None,30241,819,2.71,227,0.00,0.00,0,0,0,0,0,0,578,100,140,second_longest,27.72
34,CabEconomy,2024-05-04,post,Above 5.3.22,23946,23911,99.85,7091,87.34,69.92,20883,1744,1284,16719,3221,3965,16454,3576,3875,second_longest,29.66
35,CabEconomy,2024-05-04,post,Below 5.3.22,659,657,99.70,238,67.28,61.34,442,42,173,403,168,86,406,93,158,second_longest,36.23
36,CabEconomy,2024-05-05,post,Below 5.3.22,622,620,99.68,225,69.03,60.65,428,33,159,376,163,81,386,93,141,second_longest,36.29
37,CabEconomy,2024-05-05,post,Above 5.3.22,23847,23829,99.92,6832,87.65,70.83,20887,1674,1268,16879,3208,3737,16635,3482,3707,second_longest,28.67
38,CabEconomy,2024-05-05,post,None,29710,723,2.43,194,0.00,0.00,0,0,0,0,0,0,517,87,119,second_longest,26.83
39,CabEconomy,2024-05-06,post,Below 5.3.22,568,567,99.82,212,68.78,61.02,390,29,148,346,150,71,344,89,134,second_longest,37.39
40,CabEconomy,2024-05-06,post,Above 5.3.22,24282,24228,99.78,6958,87.32,70.54,21157,1672,1399,17091,3196,3939,16849,3416,3961,second_longest,28.72
41,CabEconomy,2024-05-06,post,None,52508,778,1.48,223,0.00,0.00,0,0,0,0,0,0,529,111,138,second_longest,28.66
42,CabEconomy,2024-05-07,post,Above 5.3.22,20532,20519,99.94,5741,87.39,71.07,17932,1450,1138,14582,2583,3355,14459,2774,3286,second_longest,27.98
43,CabEconomy,2024-05-07,post,Below 5.3.22,437,437,100.00,150,69.11,63.84,302,17,118,279,101,57,281,46,110,second_longest,34.32
44,CabEconomy,2024-05-07,post,None,24499,630,2.57,173,0.00,0.00,0,0,0,0,0,0,443,81,106,second_longest,27.46
45,CabEconomy,2024-05-08,post,None,40156,866,2.16,246,0.00,0.00,0,0,0,0,0,0,494,85,125,second_longest,28.41
46,CabEconomy,2024-05-08,post,Below 5.3.22,428,428,100.00,128,68.69,62.38,294,22,112,267,100,52,286,55,78,second_longest,29.91
47,CabEconomy,2024-05-08,post,Above 5.3.22,21971,21953,99.92,6444,86.16,69.10,18915,1732,1306,15170,2836,3517,14825,3163,3535,second_longest,29.35

In [55]:
total_df_d1_d2['Est_Nav_bucket_less_500m_percent']=(total_df_d1_d2['Est_Nav_bucket_less_500m']*100.00)/(total_df_d1_d2['net_orders'])
total_df_d1_d2['Est_Nav_bucket_grt_500m_percent']=(total_df_d1_d2['Est_Nav_bucket_grt_500m']*100.00)/(total_df_d1_d2['net_orders'])

In [56]:
total_df_d1_d2.columns

Index(['service_name', 'orderdate', 'new_date_type', 'app_version_type',
       'gross_orders', 'net_orders', 'G2N', 'route_diff_orders',
       'fe_nav_bucket_within_500m_percent',
       'nav_actual_bucket_within_500m_percent', 'fe_nav_bucket_within_500m',
       'fe_nav_bucket_less_500m', 'fe_nav_bucket_grt_500m',
       'nav_actual_bucket_within_500m', 'nav_actual_bucket_less_500m',
       'nav_actual_bucket_grt_500m', 'Est_Nav_bucket_within_500m',
       'Est_Nav_bucket_less_500m', 'Est_Nav_bucket_grt_500m', 'distance_type',
       'route_diff_percent', 'Est_Nav_bucket_less_500m_percent',
       'Est_Nav_bucket_grt_500m_percent'],
      dtype='object')

In [57]:
total_df_d1_d2.to_clipboard(index=False)

In [18]:
df_k1 = total_df_d1_d2\
        .groupby(['service_name', 'new_date_type', 'app_version_type'])\
        .agg({'gross_orders': 'sum',
              'net_orders': 'sum',
              'route_diff_orders': 'sum',
              'fe_nav_bucket_within_500m': 'sum',
              'nav_actual_bucket_within_500m': 'sum',
              'Est_Nav_bucket_within_500m': 'sum',
              'Est_Nav_bucket_less_500m': 'sum',
              'Est_Nav_bucket_grt_500m': 'sum'
             })\
        .reset_index()
df_k1

,service_name,new_date_type,app_version_type,gross_orders,net_orders,route_diff_orders,fe_nav_bucket_within_500m,nav_actual_bucket_within_500m,Est_Nav_bucket_within_500m,Est_Nav_bucket_less_500m,Est_Nav_bucket_grt_500m
0,Auto,post,Above 5.3.22,565969,564004,116298,520107,435714,430572,41771,90902
1,Auto,post,Below 5.3.22,24532,24429,5441,20496,18577,18202,1679,4526
2,Auto,pre,Above 5.3.22,383023,381814,81368,337259,290340,290289,35424,56065
3,Auto,pre,Below 5.3.22,419096,417787,90461,367926,315530,315218,38247,64297
4,CabEconomy,post,Above 5.3.22,94308,94198,27028,83976,68059,65191,13521,14850
5,CabEconomy,post,Below 5.3.22,2604,2599,915,1966,1760,1621,389,569
6,CabEconomy,pre,Above 5.3.22,61701,61625,19489,51901,42741,40624,11436,9559
7,CabEconomy,pre,Below 5.3.22,62993,62924,20707,52872,43106,40778,11874,10270

In [19]:
df_k1['Est_Nav_bucket_less_500m_percent']=(df_k1['Est_Nav_bucket_less_500m']*100.00)/(df_k1['net_orders'])
df_k1['Est_Nav_bucket_grt_500m_percent']=(df_k1['Est_Nav_bucket_grt_500m']*100.00)/(df_k1['net_orders'])
df_k1['fe_nav_bucket_within_500m_percent']=(df_k1['fe_nav_bucket_within_500m']*100.00)/df_k1['net_orders']
df_k1['nav_actual_bucket_within_500m_percent']=(df_k1['nav_actual_bucket_within_500m']*100.00)/df_k1['net_orders']
df_k1['route_diff_percent']=(df_k1['route_diff_orders']*100.00)/df_k1['net_orders']

In [20]:
df_k1

,service_name,new_date_type,app_version_type,gross_orders,net_orders,route_diff_orders,fe_nav_bucket_within_500m,nav_actual_bucket_within_500m,Est_Nav_bucket_within_500m,Est_Nav_bucket_less_500m,Est_Nav_bucket_grt_500m,Est_Nav_bucket_less_500m_percent,Est_Nav_bucket_grt_500m_percent,fe_nav_bucket_within_500m_percent,nav_actual_bucket_within_500m_percent,route_diff_percent
0,Auto,post,Above 5.3.22,565969,564004,116298,520107,435714,430572,41771,90902,7.406153,16.117262,92.216899,77.253707,20.620067
1,Auto,post,Below 5.3.22,24532,24429,5441,20496,18577,18202,1679,4526,6.872979,18.527160,83.900282,76.044865,22.272709
2,Auto,pre,Above 5.3.22,383023,381814,81368,337259,290340,290289,35424,56065,9.277816,14.683851,88.330706,76.042261,21.310900
3,Auto,pre,Below 5.3.22,419096,417787,90461,367926,315530,315218,38247,64297,9.154665,15.389900,88.065450,75.524131,21.652421
4,CabEconomy,post,Above 5.3.22,94308,94198,27028,83976,68059,65191,13521,14850,14.353808,15.764666,89.148390,72.251003,28.692754
5,CabEconomy,post,Below 5.3.22,2604,2599,915,1966,1760,1621,389,569,14.967295,21.893036,75.644479,67.718353,35.205848
6,CabEconomy,pre,Above 5.3.22,61701,61625,19489,51901,42741,40624,11436,9559,18.557404,15.511562,84.220690,69.356592,31.625152
7,CabEconomy,pre,Below 5.3.22,62993,62924,20707,52872,43106,40778,11874,10270,18.870383,16.321276,84.025173,68.504863,32.907952

## Numbers

In [21]:
total_df_d1_d2.to_csv('d1_new_v2.csv', index=False)

In [22]:
total_df_d1_d2.shape

(84, 23)