In [178]:
import numpy as np
import pandas as pd
from h3 import h3
from pyhive import presto
from datetime import timedelta,datetime
import json
import requests


import warnings
warnings.filterwarnings("ignore")

In [179]:
conn = presto.connect(
    host='presto-gateway.processing.data.production.internal',
    port=80,
    protocol='http',
    catalog='hive',
    username='gandharv.kumar@rapido.bike',
    # requests_kwargs=req_kw,
)

In [180]:
start_date = '20230724'
end_date = '20230726'

In [181]:
def decode_polyline(polyline_str):
    index, lat, lng = 0, 0, 0
    coordinates = []
    changes = {'latitude': 0, 'longitude': 0}

    # Coordinates have variable length when encoded, so just keep
    # track of whether we've hit the end of the string. In each
    # while loop iteration, a single coordinate is decoded.
    while index < len(polyline_str):
        # Gather lat/lon changes, store them in a dictionary to apply them later
        for unit in ['latitude', 'longitude']: 
            shift, result = 0, 0

            while True:
                byte = ord(polyline_str[index]) - 63
                index+=1
                result |= (byte & 0x1f) << shift
                shift += 5
                if not byte >= 0x20:
                    break

            if (result & 1):
                changes[unit] = ~(result >> 1)
            else:
                changes[unit] = (result >> 1)

        lat += changes['latitude']
        lng += changes['longitude']

        coordinates.append([lat / 100000.0, lng / 100000.0])

    return coordinates

In [182]:
def getGeoJson(coordinates):
    geoJson_string = """{ "type": "LineString", "coordinates": """+str([[coord[1], coord[0]] for coord in coordinates])+"""}"""
    return geoJson_string

In [183]:
import json

In [184]:
pri_query = f'''
select 
   data
from 
    g2n.log_dispatch_pool_orders_prioritizer_raw 
where yyyymmdd  between '{start_date}' and '{end_date}'
      and json_extract_scalar(data,'$.data.response.sequence[0].orderId') is not null
'''

In [185]:
ols_query = f'''
select pool_id,
       order_id,
       captain_id,
       polyline,
       case when order_status = 'dropped' then 'dropped'
            when order_status = 'customerCancelled' then 
                 case when cancel_reason = 'order cancelled before rider accepted' then 'COBRA'
                      when cancel_reason = 'Order cancelled before rider was mapped' then 'COBRM'
                      when cancel_reason not in (
                             'order cancelled before rider accepted',
                             'Order cancelled before rider was mapped','') then 'OCARA'
                       end
            else order_status
      end as final_order_status,
      distance_final_distance,
      case 
        when hhmmss between '000000' and '050000' then '1.Night'
        when hhmmss between '050000' and '080000' then '2.Early Morning'
        when hhmmss between '080000' and '110000' then '3.Morning'
        when hhmmss between '110000' and '130000' then '4.Noon'
        when hhmmss between '130000' and '170000' then '5.Early Evening'
        when hhmmss between '170000' and '210000' then '6.Evening'
        when hhmmss between '210000' and '235959' then '7.Late Evening'
        else 'NA' end as tod,
        pickup_location_latitude,
        pickup_location_longitude,
        drop_location_latitude,
        drop_location_longitude
from orders.order_logs_snapshot
where yyyymmdd between '{start_date}' and '{end_date}'
      and service_detail_id = '64060f74fb2b4ec5696417d4'
      and (spd_fraud_flag is null or spd_fraud_flag = false) 
      and pool_id is not null
'''

In [186]:
oli_query = f'''
        with oli_data as (select pool_id,event_type,event_time
        from orders.order_logs_immutable
        where yyyymmdd between '{start_date}' and '{end_date}'
              and event_type in ('started','dropped')
              and pool_id is not null
              and service_detail_id = '64060f74fb2b4ec5696417d4'
        ),
        started_time as (
        select pool_id,min(event_time) as first_started
        from oli_data
        where event_type = 'started'
        group by 1
        ),
        dropped_time as (
        select pool_id,max(event_time) as last_dropped
        from oli_data
        where event_type = 'dropped'
        group by 1
        )

        select started_time.pool_id,first_started,last_dropped
        from started_time
        left join
        dropped_time
        on started_time.pool_id = dropped_time.pool_id
'''

In [187]:
pri_df = pd.read_sql(pri_query,conn)
pri_df.head(2)

                                                data
0  {"eventId":"93e5ff07-ae3b-936a-9053-a00a54b71f...
1  {"eventId":"2859ccaa-d4fe-0785-cd2f-0158b40a68...

In [188]:
ols_df = pd.read_sql(ols_query,conn)
ols_df.head()

,pool_id,order_id,captain_id,polyline,final_order_status,distance_final_distance,tod,pickup_location_latitude,pickup_location_longitude,drop_location_latitude,drop_location_longitude
0,64bf55047f7258c0ba87b8fa,64bf550437629f672b69807e,5dba7e093087fd493629ffb9,ct{mAohuxMgEYs@Ay@BqAC@mDEIIC{@DkANU?eJy@Ml@i@...,dropped,1.260,3.Morning,12.926258,77.610468,12.934875,77.609383
1,64bfd048febd15aa52b87ab3,64bfd048990dce1a751b932b,5c95e5fe8c352421eaf7bf50,kqcnAuizxM\f@x@bAj@W\UuD}ElAu@~BaBrBoBj@k@n@}@...,COBRA,10.430,6.Evening,12.966805,77.636253,12.903157,77.648225
2,64bdf461e911a87e1116a1ba,64bdf461294128614408be1d,5da4add8941a7d1c51e6036d,cnzmAoavxMeBjFhA^l@NlBZnGl@xBVl@LvCRFkJF{ANwBN...,OCARA,2.390,3.Morning,12.920216,77.614494,12.913171,77.625977
3,64c0a1f88a0a2c8fa494fefc,64c0a1f8f2b4de2a430979e7,63d9f0c1aa0c7e8695a62bb7,qsymAemuxM?eEvGVJy@XsA~@oDPo@L}@JqCmOk@PyEFsCM...,COBRA,3.020,3.Morning,12.916000,77.611186,12.914361,77.632448
4,64be7f9cc119bcfb4ac0c1d3,64be7f806ca57336103d72e7,60fbaf5ffe2f605c3b869c3c,ik{mAotayMUi@RIuEmLY}@gG_PcCeHqAoDqBaFoCoHq@_B...,OCARA,5.733,6.Evening,12.925043,77.674365,12.957172,77.699104

In [189]:
oli_df = pd.read_sql(oli_query,conn)
oli_df.head()

                    pool_id  first_started   last_dropped
0  64bfc44d3e5dbb45a7e35c50  1690289580350  1690290819322
1  64bf434dd9aeb76353a3218f  1690257047238  1690260603368
2  64bfc72dd9aeb76353a41dd4  1690290668166  1690291824031
3  64c086447f7258c0ba89233d  1690339447236  1690339684040
4  64bdf771de5226414b1df073  1690172195711  1690173888175

In [190]:
ols_df.shape

(220, 11)

In [191]:
new_df1 = pri_df['data'].apply(json.loads)

In [192]:
len(new_df1)

1133

In [193]:
# matched_with = len(new_df1[0]['data']['orders'][0]['poolableOrdersWithScores'])

In [194]:
pool_ids = []
hex9s = []

for p_id in range(len(new_df1)):
    pool_id = new_df1[p_id]['data']['response']['poolId']
    matched_with = len(new_df1[p_id]['data']['orders'][0]['poolableOrdersWithScores'])
    
    this = ols_df[ols_df.pool_id==pool_id]
    if len(this) != 0:
    
        this.sort_values(['distance_final_distance'],ascending=True,inplace=True)

        long_lm_order_id = this['order_id'].values[1]

        hex9_ring = 'blank'
        for i in range(matched_with):
            if new_df1[p_id]['data']['orders'][0]['poolableOrdersWithScores'][i]['id'] == long_lm_order_id:
                hex9ring = new_df1[p_id]['data']['orders'][0]['poolableOrdersWithScores'][i]['route_preference_strategy_attributes']['hexes']['subsequentOrderHexAdjacencies']
        if hex9_ring == 'blank':
            if new_df1[p_id]['data']['orders'][0]['order']['correlation']['id'] == long_lm_order_id:
                hex9ring = new_df1[p_id]['data']['orders'][0]['poolableOrdersWithScores'][0]['route_preference_strategy_attributes']['hexes']['subsequentOrderHexAdjacencies']

        pool_ids.append(pool_id)
        hex9s.append(hex9ring)
    
res = pd.DataFrame(
    {'pool_id':pool_ids,
     'hex9s':hex9s
    })

In [195]:
res

,pool_id,hex9s
0,64c0aaffd9aeb76353a5222a,"[8961892589bffff, 89618925ccbffff, 89618925137..."
1,64bf49fe64f6ab563a8c6eeb,"[89618925d57ffff, 89618925ea7ffff, 8961892589b..."
2,64c0a1cced7b75c49c9d6e09,"[8961892557bffff, 89618924297ffff, 8961892405b..."
3,64bdfc1fb8c55347fc76fb86,"[89618925ca3ffff, 8961892434bffff, 89618925ea3..."
4,64bf4f7c3e5dbb45a7e28ddc,"[896189259a7ffff, 89618925d57ffff, 89618925d8b..."
...,...,...
105,64bf57d73e5dbb45a7e2a178,"[89618924253ffff, 89618924c5bffff, 89618924147..."
106,64bfcedcec5d76947fdb190e,"[89618925463ffff, 89618920bdbffff, 89618920aa7..."
107,64bfd945814a2ec9a1309f46,"[89618920b53ffff, 89618920a2fffff, 8961892edc3..."
108,64bf593b3e5dbb45a7e2a48c,"[89618925c07ffff, 8961892432bffff, 89618924e97..."
109,64bfda90634ed015a340cdc2,"[89618920bb3ffff, 89618925277ffff, 8961892520f..."

In [196]:
converted_df = res.explode('hex9s')

In [197]:
converted_df

                      pool_id            hex9s
0    64c0aaffd9aeb76353a5222a  8961892589bffff
0    64c0aaffd9aeb76353a5222a  89618925ccbffff
0    64c0aaffd9aeb76353a5222a  89618925137ffff
0    64c0aaffd9aeb76353a5222a  89618925ebbffff
0    64c0aaffd9aeb76353a5222a  89618925c0fffff
..                        ...              ...
109  64bfda90634ed015a340cdc2  8961892ec83ffff
109  64bfda90634ed015a340cdc2  89618920b37ffff
109  64bfda90634ed015a340cdc2  8961892536fffff
109  64bfda90634ed015a340cdc2  8961892edcbffff
109  64bfda90634ed015a340cdc2  89618920b57ffff

[17989 rows x 2 columns]

In [198]:
ols_df['route_geoJson'] = ols_df.apply(lambda row:getGeoJson(decode_polyline(row['polyline'])),axis=1)

In [199]:
rel_ids = ols_df['pool_id'].unique()

In [200]:
ols_df.head(2)

,pool_id,order_id,captain_id,polyline,final_order_status,distance_final_distance,tod,pickup_location_latitude,pickup_location_longitude,drop_location_latitude,drop_location_longitude,route_geoJson
0,64bf55047f7258c0ba87b8fa,64bf550437629f672b69807e,5dba7e093087fd493629ffb9,ct{mAohuxMgEYs@Ay@BqAC@mDEIIC{@DkANU?eJy@Ml@i@...,dropped,1.26,3.Morning,12.926258,77.610468,12.934875,77.609383,"{ ""type"": ""LineString"", ""coordinates"": [[77.61..."
1,64bfd048febd15aa52b87ab3,64bfd048990dce1a751b932b,5c95e5fe8c352421eaf7bf50,kqcnAuizxM\f@x@bAj@W\UuD}ElAu@~BaBrBoBj@k@n@}@...,COBRA,10.43,6.Evening,12.966805,77.636253,12.903157,77.648225,"{ ""type"": ""LineString"", ""coordinates"": [[77.63..."

#### Actual Route Travelled by Captain

In [201]:
def getRiderlocation(captain_id,start_time,end_time,Auth_token):
    
    url = "http://rider-locations-store.production.ops.plectrum.dev/locations"

    payload = json.dumps({
      "userId": captain_id,
      "dateTimeRange": [
        start_time,
        end_time
      ],
      "points": {
        "required": True
      }
    })
    headers = {
      'Authorization': Auth_token,
      'Content-Type': 'application/json'
    }

    response = requests.request("POST", url, headers=headers, data=payload)
    resp = json.loads(response.text)
    return resp

In [202]:
def getTripCoord(sample_trp):
    final_trip_coord = []
    for i in range(len(sample_trp['locations'])):
        temp_list = []

        long = sample_trp['locations'][i]['location'][0]
        lat = sample_trp['locations'][i]['location'][1]
        alt = 0
        epoch = sample_trp['locations'][i]['date']+19800000

        temp_list = [long,lat,alt,epoch]

        final_trip_coord.append(temp_list)
    return final_trip_coord

In [203]:
def getTripGeoJson(data):
    
    data_str = {
              "type": "FeatureCollection",
              "features": [
                {
                  "type": "Feature",
                  "properties": {
                    "vendor":  "A"
                  },
                  "geometry": {
                    "type": "LineString",
                    "coordinates": data
                  }
                }
              ]
            }
    
    return json.dumps(data_str)

In [204]:
auth_token = str(input("Enter Authorization Token"))

Enter Authorization TokenPomerium eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsiYXV0aGVudGljYXRlLm9wcy5wbGVjdHJ1bS5kZXYiLCJsb2NhbGhvc3Q6NDgwMDAiLCJsb2dnaW5nLm9wcy5wbGVjdHJ1bS5kZXYiXSwiZXhwIjoxNjkwNDE1MDk3LCJpYXQiOjE2OTAzNjQ2OTgsImlzcyI6ImF1dGhlbnRpY2F0ZS5vcHMucGxlY3RydW0uZGV2IiwianRpIjoiMWRjZGI5ZmMtMjY1Ni00YTkyLWFkYmYtZjEyY2MzZGZiY2NiIiwibmJmIjoxNjkwMzY0Njk4LCJwcm9ncmFtbWF0aWMiOnRydWUsInN1YiI6IjJmMWY5MDdhLTZmOTMtNGViMi1iZDA0LWMxZjEyMTMwY2ExYSIsInZlciI6Ijc0Njk5OTIyMzg2ODMxMjc1In0.qvIV4tLv4asTfc6_li9aG3v1RUNrkw9vG-3sHuNITnM

In [205]:
pool_id = []
actual_distance = []
actual_route_poly = []
actual_route_trip = []

for i in range(oli_df.shape[0]):
    curr_pool_id = oli_df['pool_id'][i]
    captain_id = ols_df[ols_df.pool_id==curr_pool_id]['captain_id'].unique()[0]
    
    started_epoch = str(oli_df['first_started'][i])
    dropped_epoch = str(oli_df['last_dropped'][i])
    
    print(captain_id,started_epoch,dropped_epoch,sep=' ')
    api_response = getRiderlocation(captain_id,started_epoch,dropped_epoch,auth_token)
    
    actual_dist_t = api_response['distance']
    
    final_trip_coord = getTripCoord(api_response)
    
    trip_poly_coord = [[trip_coord[1],trip_coord[0]] for trip_coord in final_trip_coord]
    
    actual_route_polygon_t = getGeoJson(trip_poly_coord)
    actual_route_trip_t = getTripGeoJson(final_trip_coord)
    
    pool_id.append(curr_pool_id)
    actual_distance.append(actual_dist_t)
    actual_route_poly.append(actual_route_polygon_t)
    actual_route_trip.append(actual_route_trip_t)
    

poly_df = pd.DataFrame(
    {'pool_id':pool_id,
     'actual_distance':actual_distance,
     'actual_route_polygon':actual_route_poly,
     'actual_route_trip':actual_route_trip
    })

5eb520ec5c1647f36158d15a 1690289580350 1690290819322
616cf4654c6ba1f7ced8305a 1690257047238 1690260603368
62b5853a93096e96872f024e 1690290668166 1690291824031
61869571760799ad83289f39 1690339447236 1690339684040
6305d9eb81735cac3f6a1955 1690172195711 1690173888175
61869571760799ad83289f39 1690169914856 1690171340976
63ccbfb77e90d24ed97354b3 1690298559003 1690300644443
5dba7e093087fd493629ffb9 1690261245869 1690261564659
62a2327ad48982a500359b30 1690207590645 1690208208102
60ec027be5cb35437b5a50c5 1690340304376 1690342080908
6158847f77c7e6a1df8f8de4 1690349840433 1690350982915
639b0b02e3d8b52738c7ecd4 1690347884028 1690350028972
5dba7e093087fd493629ffb9 1690171101110 1690173252507
6438a327f6c53c7c55daef54 1690262259144 1690263067843
618abcccfbd1714bbccbbbb1 1690294698490 1690295017580
61869571760799ad83289f39 1690346588408 1690347703057
62b02dcc290a49dbf551685c 1690291966524 1690293586909
60fa7999d417d416b77def81 1690256762190 1690258302423
6325f95529d8052f9b34bace 1690174234111 1690177988942
5ed6521e1f5e408e07ce1c3f 1690343830946 1690344703165
60fbaf5ffe2f605c3b869c3c 1690207434403 1690207967793
5c8250a75e042733c9c5aec8 1690174983024 1690177850568
61a0c4e4f3de6f225f3a91d4 1690345514740 1690347434879
63b933352b7c0da8021f9d67 1690174001962 1690174250877
6050d6e3e23c0065140f484d 1690347813451 1690349881334
61869571760799ad83289f39 1690349023966 1690350284104
5c207ab5d9bacb2f6f9dc0b7 1690342909187 1690343722979
61a74565f3de6f78833f4cfe 1690290281125 1690293498589
5c207ab5d9bacb2f6f9dc0b7 1690345078951 1690348080890
63903ffcf655ec7e8985cfa1 1690343489690 1690346857270
60f7a2e2c2e7b676870eec68 1690169758047 1690171385559
62133825ca4878deb6bf1069 1690203927576 1690206830676
62a2327ad48982a500359b30 1690205476013 1690205960652
6018052e7143232a96c686ab 1690349937858 1690351551478
629dd39b737cf7f4ac8438f7 1690290874151 1690292628623
62c51cc90011cac44c48e73d 1690256207902 1690258261985
5ce9411e377155163c055bf6 1690171570895 1690172529251
6219b95cc1a4e48f2d5dbcc1 1690255589465 1690255945153
610233216c5e5f573dbf52c5 1690256632947 1690258921674
624ec96996ae686f3ff88074 1690343499479 1690343764123
5c207ab5d9bacb2f6f9dc0b7 1690252589927 1690252845606
60f79565d417d4dbf97c6c10 1690290224853 1690290959579
618abcccfbd1714bbccbbbb1 1690291624122 1690292084373
6188c06db281d75080c95038 1690256113847 1690256701192
62b01f7d17af9a43095d1878 1690289759374 1690290553800
5d654547a24c96105e28aa0b 1690292413294 1690292688283
60e7c293569b26150774019f 1690348606137 1690349852646
610104246d607044a247e1b7 1690347843511 1690348781955
6219b95cc1a4e48f2d5dbcc1 1690343522491 1690344159836
61e7f9265e24283587eddbb8 1690175185440 1690176215434
5c207ab5d9bacb2f6f9dc0b7 1690256620394 1690257919322
60f1b3098f34796bd2181586 1690346600653 1690348879299
5c207ab5d9bacb2f6f9dc0b7 1690259429592 1690260884941
6222388c99ea4ddda097350b 1690262900074 1690265071418
63c0f7081047fcbf6c08df51 1690341250658 1690344418427
5c9adf1fb50ab0456be54f2a 1690347908434 1690348271606

In [206]:
final_df = pd.merge(ols_df[['pool_id', 'order_id', 'final_order_status','distance_final_distance','tod','pickup_location_latitude','pickup_location_longitude','drop_location_latitude','drop_location_longitude', 'route_geoJson']],\
        poly_df[['pool_id','actual_distance','actual_route_polygon','actual_route_trip']],\
         how = 'inner',\
         on = 'pool_id'
        )

In [221]:
final_df.head()

,pool_id,order_id,final_order_status,distance_final_distance,tod,pickup_location_latitude,pickup_location_longitude,drop_location_latitude,drop_location_longitude,route_geoJson,actual_distance,actual_route_polygon,actual_route_trip
0,64bf55047f7258c0ba87b8fa,64bf550437629f672b69807e,dropped,1.260,3.Morning,12.926258,77.610468,12.934875,77.609383,"{ ""type"": ""LineString"", ""coordinates"": [[77.61...",1.434423,"{ ""type"": ""LineString"", ""coordinates"": [[77.61...","{""type"": ""FeatureCollection"", ""features"": [{""t..."
1,64bf55047f7258c0ba87b8fa,64bf54e666ffee6f5330ee02,OCARA,4.340,3.Morning,12.927528,77.607648,12.943492,77.585093,"{ ""type"": ""LineString"", ""coordinates"": [[77.60...",1.434423,"{ ""type"": ""LineString"", ""coordinates"": [[77.61...","{""type"": ""FeatureCollection"", ""features"": [{""t..."
2,64be7f9cc119bcfb4ac0c1d3,64be7f806ca57336103d72e7,OCARA,5.733,6.Evening,12.925043,77.674365,12.957172,77.699104,"{ ""type"": ""LineString"", ""coordinates"": [[77.67...",1.459698,"{ ""type"": ""LineString"", ""coordinates"": [[77.67...","{""type"": ""FeatureCollection"", ""features"": [{""t..."
3,64be7f9cc119bcfb4ac0c1d3,64be7f9b30c61e170946408f,dropped,1.212,6.Evening,12.925954,77.674812,12.928167,77.671288,"{ ""type"": ""LineString"", ""coordinates"": [[77.67...",1.459698,"{ ""type"": ""LineString"", ""coordinates"": [[77.67...","{""type"": ""FeatureCollection"", ""features"": [{""t..."
4,64c0a743aac577c6065461f2,64c0a743a49ad51b65abcd7a,dropped,1.260,3.Morning,12.926258,77.610468,12.934393,77.609390,"{ ""type"": ""LineString"", ""coordinates"": [[77.61...",1.057293,"{ ""type"": ""LineString"", ""coordinates"": [[77.61...","{""type"": ""FeatureCollection"", ""features"": [{""t..."

In [218]:
final_df.to_csv(f'pool_data_{start_date}_{end_date}.csv',index=False)

In [ ]:
# final_df[final_df.pool_id.isin(net_df[net_df.final_order_status==2].pool_id.unique())].to_csv(f'pool_data_{start_date}_{end_date}.csv',index=False)

In [220]:
converted_df.to_csv(f'hex_9_rings_{start_date}_{end_date}.csv',index=False)

In [ ]:
# converted_df[converted_df.pool_id.isin(net_df[net_df.final_order_status==2].pool_id.unique())].to_csv(f'hex_9_rings_{start_date}_{end_date}.csv',index=False)

# END of Code

### Viz on Kepler

In [ ]:
from keplergl import KeplerGl

In [ ]:
map1 = KeplerGl()

In [ ]:
config = {"version":"v1","config":{"visState":{"filters":[{"dataId":["f0yctzw89"],"id":"514x9a44f","name":["pool_id"],"type":"multiSelect","value":["64ae19b5392670d9adf32960"],"enlarged":False,"plotType":"histogram","animationWindow":"free","yAxis":None,"speed":1},{"dataId":["h635gngxf"],"id":"ywzql6ax","name":["pool_id"],"type":"multiSelect","value":["64ae19b5392670d9adf32960"],"enlarged":False,"plotType":"histogram","animationWindow":"free","yAxis":None,"speed":1}],"layers":[{"id":"av3ygy","type":"point","config":{"dataId":"f0yctzw89","label":"pickup_location","color":[125,201,127],"highlightColor":[252,242,26,255],"columns":{"lat":"pickup_location_latitude","lng":"pickup_location_longitude","altitude":None},"isVisible":True,"visConfig":{"radius":25,"fixedRadius":False,"opacity":0.8,"outline":False,"thickness":2,"strokeColor":None,"colorRange":{"name":"Global Warming","type":"sequential","category":"Uber","colors":["#5A1846","#900C3F","#C70039","#E3611C","#F1920E","#FFC300"]},"strokeColorRange":{"name":"Global Warming","type":"sequential","category":"Uber","colors":["#5A1846","#900C3F","#C70039","#E3611C","#F1920E","#FFC300"]},"radiusRange":[0,50],"filled":True},"hidden":False,"textLabel":[{"field":None,"color":[255,255,255],"size":18,"offset":[0,0],"anchor":"start","alignment":"center"}]},"visualChannels":{"colorField":None,"colorScale":"quantile","strokeColorField":None,"strokeColorScale":"quantile","sizeField":None,"sizeScale":"linear"}},{"id":"805v33i","type":"point","config":{"dataId":"f0yctzw89","label":"drop_location","color":[227,26,26],"highlightColor":[252,242,26,255],"columns":{"lat":"drop_location_latitude","lng":"drop_location_longitude","altitude":None},"isVisible":True,"visConfig":{"radius":25,"fixedRadius":False,"opacity":1,"outline":False,"thickness":2,"strokeColor":None,"colorRange":{"name":"Global Warming","type":"sequential","category":"Uber","colors":["#5A1846","#900C3F","#C70039","#E3611C","#F1920E","#FFC300"]},"strokeColorRange":{"name":"Global Warming","type":"sequential","category":"Uber","colors":["#5A1846","#900C3F","#C70039","#E3611C","#F1920E","#FFC300"]},"radiusRange":[0,50],"filled":True},"hidden":False,"textLabel":[{"field":None,"color":[255,255,255],"size":18,"offset":[0,0],"anchor":"start","alignment":"center"}]},"visualChannels":{"colorField":None,"colorScale":"quantile","strokeColorField":None,"strokeColorScale":"quantile","sizeField":None,"sizeScale":"linear"}},{"id":"puqsxul","type":"trip","config":{"dataId":"f0yctzw89","label":"Trip","color":[255,251,152],"highlightColor":[252,242,26,255],"columns":{"geojson":"actual_route_trip"},"isVisible":True,"visConfig":{"opacity":0.8,"thickness":3,"colorRange":{"name":"Global Warming","type":"sequential","category":"Uber","colors":["#5A1846","#900C3F","#C70039","#E3611C","#F1920E","#FFC300"]},"trailLength":180,"sizeRange":[0,10]},"hidden":False,"textLabel":[{"field":None,"color":[255,255,255],"size":18,"offset":[0,0],"anchor":"start","alignment":"center"}]},"visualChannels":{"colorField":None,"colorScale":"quantile","sizeField":None,"sizeScale":"linear"}},{"id":"rw8ng6k","type":"geojson","config":{"dataId":"f0yctzw89","label":"route polygon","color":[183,136,94],"highlightColor":[252,242,26,255],"columns":{"geojson":"actual_route_polygon"},"isVisible":True,"visConfig":{"opacity":0.8,"strokeOpacity":0.8,"thickness":2,"strokeColor":[218,112,191],"colorRange":{"name":"Global Warming","type":"sequential","category":"Uber","colors":["#5A1846","#900C3F","#C70039","#E3611C","#F1920E","#FFC300"]},"strokeColorRange":{"name":"Global Warming","type":"sequential","category":"Uber","colors":["#5A1846","#900C3F","#C70039","#E3611C","#F1920E","#FFC300"]},"radius":10,"sizeRange":[0,10],"radiusRange":[0,50],"heightRange":[0,500],"elevationScale":5,"enableElevationZoomFactor":True,"stroked":True,"filled":False,"enable3d":False,"wireframe":False},"hidden":False,"textLabel":[{"field":None,"color":[255,255,255],"size":18,"offset":[0,0],"anchor":"start","alignment":"center"}]},"visualChannels":{"colorField":None,"colorScale":"quantile","strokeColorField":None,"strokeColorScale":"quantile","sizeField":None,"sizeScale":"linear","heightField":None,"heightScale":"linear","radiusField":None,"radiusScale":"linear"}},{"id":"mj3foj","type":"geojson","config":{"dataId":"f0yctzw89","label":"Estimated Route","color":[241,92,23],"highlightColor":[252,242,26,255],"columns":{"geojson":"route_geoJson"},"isVisible":True,"visConfig":{"opacity":0.8,"strokeOpacity":0.8,"thickness":2,"strokeColor":None,"colorRange":{"name":"Global Warming","type":"sequential","category":"Uber","colors":["#5A1846","#900C3F","#C70039","#E3611C","#F1920E","#FFC300"]},"strokeColorRange":{"name":"Custom Palette","type":"custom","category":"Custom","colors":["#2220da","#42b876"]},"radius":10,"sizeRange":[0,10],"radiusRange":[0,50],"heightRange":[0,500],"elevationScale":5,"enableElevationZoomFactor":True,"stroked":True,"filled":False,"enable3d":False,"wireframe":False},"hidden":False,"textLabel":[{"field":None,"color":[255,255,255],"size":18,"offset":[0,0],"anchor":"start","alignment":"center"}]},"visualChannels":{"colorField":None,"colorScale":"quantile","strokeColorField":{"name":"distance_final_distance","type":"real"},"strokeColorScale":"quantize","sizeField":None,"sizeScale":"linear","heightField":None,"heightScale":"linear","radiusField":None,"radiusScale":"linear"}},{"id":"0wm3y48","type":"hexagonId","config":{"dataId":"h635gngxf","label":"hex9s","color":[255,251,152],"highlightColor":[252,242,26,255],"columns":{"hex_id":"hex9s"},"isVisible":True,"visConfig":{"opacity":0.04,"colorRange":{"name":"Global Warming","type":"sequential","category":"Uber","colors":["#5A1846","#900C3F","#C70039","#E3611C","#F1920E","#FFC300"]},"coverage":1,"enable3d":False,"sizeRange":[0,500],"coverageRange":[0,1],"elevationScale":5,"enableElevationZoomFactor":True},"hidden":False,"textLabel":[{"field":None,"color":[255,255,255],"size":18,"offset":[0,0],"anchor":"start","alignment":"center"}]},"visualChannels":{"colorField":None,"colorScale":"quantile","sizeField":None,"sizeScale":"linear","coverageField":None,"coverageScale":"linear"}}],"interactionConfig":{"tooltip":{"fieldsToShow":{"f0yctzw89":[{"name":"pool_id","format":None},{"name":"order_id","format":None},{"name":"final_order_status","format":None},{"name":"distance_final_distance","format":None},{"name":"tod","format":None}],"h635gngxf":[{"name":"pool_id","format":None},{"name":"hex9s","format":None}]},"compareMode":False,"compareType":"absolute","enabled":True},"brush":{"size":0.5,"enabled":False},"geocoder":{"enabled":False},"coordinate":{"enabled":False}},"layerBlending":"normal","splitMaps":[],"animationConfig":{"currentTime":1689155921701.759,"speed":0.01}},"mapState":{"bearing":0,"dragRotate":False,"latitude":12.928446526525011,"longitude":77.61652020141541,"pitch":0,"zoom":13.490958995029843,"isSplit":False},"mapStyle":{"styleType":"dark","topLayerGroups":{},"visibleLayerGroups":{"label":True,"road":True,"border":False,"building":True,"water":True,"land":True,"3d building":False},"threeDBuildingColor":[9.665468314072013,17.18305478057247,31.1442867897876],"mapStyles":{}}}}

In [ ]:
# hex : h635gngxf
# pool_data : av3ygy

In [ ]:
map1 = KeplerGl(height=800, data={'av3ygy': final_df, 'h635gngxf':converted_df}, config=config)

In [ ]:
# map1

# Rough

In [ ]:
# ols_df[['pool_id', 'order_id', 'final_order_status','distance_final_distance','tod','pickup_location_latitude','pickup_location_longitude','drop_location_latitude','drop_location_longitude', 'route_geoJson']].to_csv('route_data.csv',index=False)

In [ ]:
ols_df.head(2)

In [ ]:
new_df1[0]['data']['orders'][0]['poolableOrdersWithScores'][0]

In [ ]:
new_df1[0]['data']['orders'][0]['poolableOrdersWithScores'][1]

In [ ]:
for i in range(len(new_df1)):
    if new_df1[i]['data']['response']['poolId']=='64ae19b5392670d9adf32960':
        print(i)

In [ ]:
new_df1[0]

In [ ]:
ols_df[ols_df.pool_id=='64ae19b5392670d9adf32960'][['order_id','polyline']]

In [ ]:
new_df1[110]['data']['response']['poolId']

In [ ]:
new_df1[91]

In [ ]:
new_df1[91]

In [ ]:
source_order_id = new_df1[91]['data']['response']['sequence'][0]['orderId']

destination_order_id = new_df1[91]['data']['response']['sequence'][3]['orderId']

intermediate_1 = new_df1[91]['data']['response']['sequence'][1]['orderId']

intermediate_2 = new_df1[91]['data']['response']['sequence'][2]['orderId']

In [ ]:
intermediate_2

In [ ]:
source = [12.926422618215238, 77.61474296450615]
destination = [12.9438413,77.6189098]
intermediate = [[12.929969458847621,77.6094563305378],[12.9436191,77.60592079999999]]

getPolylines(source,destination,intermediate)

### Real Time Route using Google API

In [ ]:
def getPickup_LatLong(df,od_id):
    row = df[df.order_id == od_id]
    lat = row['pickup_location_latitude'].values[0]
    long = row['pickup_location_longitude'].values[0]
    
    return [lat,long]

In [ ]:
def getDrop_LatLong(df,od_id):
    row = df[df.order_id == od_id]
    lat = row['drop_location_latitude'].values[0]
    long = row['drop_location_longitude'].values[0]
    
    return [lat,long]

In [ ]:
def getPolylines(source,destination,intermediate):
    headers = {
    'X-Goog-Api-Key': 'AIzaSyAZydYP7Y2AIoXf4DhyMw1FeOCUQpVOZak',
    'X-Goog-FieldMask': 'routes.duration,routes.distanceMeters,routes.polyline',
    'Content-Type': 'application/json',
                }
    
    url = 'https://routespreferred.googleapis.com/v1:computeRoutes'
    
    json_data = {
        'travelMode': 'DRIVE',
        'routingPreference': 'TRAFFIC_AWARE',
        'languageCode': 'en-US',
        'origin': {
            'location': {
                'latLng': {
                    'latitude': source[0],
                    'longitude': source[1],
                },
            },
        },
        'destination': {
            'location': {
                'latLng': {
                    'latitude': destination[0],
                    'longitude': destination[1],
                },
            },
        },
        'intermediates': [
            {
                'vehicleStopover': True,
                'location': {
                    'latLng': {
                        'latitude': intermediate[0][0],
                        'longitude': intermediate[0][1],
                    },
                },
            },
            {
                'vehicleStopover': True,
                'location': {
                    'latLng': {
                        'latitude': intermediate[1][0],
                        'longitude': intermediate[1][1],
                    },
                },
            },
        ],
            }
    
    response = requests.post(url, headers=headers, json=json_data)
    resp = json.loads(response.text)
    return resp['routes'][0]['polyline']['encodedPolyline']

In [ ]:
pool_id = []
actual_route_polyline = []
actual_route = []

for ids in rel_ids:
    this = ols_df[ols_df.pool_id==ids]
    
    for p_id in range(len(new_df1)):
        if new_df1[p_id]['data']['response']['poolId'] == ids:
            source_order_id = new_df1[p_id]['data']['response']['sequence'][0]['orderId']
            destination_order_id = new_df1[p_id]['data']['response']['sequence'][3]['orderId']
            intermediate_1 = new_df1[p_id]['data']['response']['sequence'][1]['orderId']
            intermediate_2 = new_df1[p_id]['data']['response']['sequence'][2]['orderId']
            
            source = getPickup_LatLong(this,source_order_id)
            intermediate_a = getPickup_LatLong(this,intermediate_1)
            intermediate_b = getDrop_LatLong(this,intermediate_2)
            destination = getDrop_LatLong(this,destination_order_id)
            
            actual_route_poly = getPolylines(source,destination,[intermediate_a,intermediate_b])
            
            actual_rt = getGeoJson(decode_polyline(actual_route_poly))
            
            pool_id.append(ids)
            actual_route_polyline.append(actual_route_poly)
            actual_route.append(actual_rt)

poly_df = pd.DataFrame(
    {'pool_id':pool_id,
     'actual_route_polyline':actual_route_polyline,
     'actual_route':actual_route
    })

In [ ]:
pd.set_option('display.max_columns', None)
pd.set_option('display.float_format', lambda x: '%.6f' % x)
poly_df.head()

In [82]:
ols_df[ols_df.order_id== '64b60a9c39ee184e6db7a10c']

,pool_id,order_id,captain_id,polyline,final_order_status,distance_final_distance,tod,pickup_location_latitude,pickup_location_longitude,drop_location_latitude,drop_location_longitude,route_geoJson
23,64b60a9ccc70dac0efdfe0c7,64b60a9c39ee184e6db7a10c,5db0cc61296aa3341cfc596f,whzmAsbvxMg@CMbI?XcBYcBg@g@M_@Gy@[oFkCkAe@kA]g...,dropped,3.375,3.Morning,12.919341,77.614517,12.943942,77.605965,"{ ""type"": ""LineString"", ""coordinates"": [[77.61..."

In [83]:
import h3

In [92]:
coordinates =  [
                {
                    "lat": 12.929390775219803,
                    "lng": 77.66842897724833
                },
                {
                    "lat": 12.92975430493654,
                    "lng": 77.66662851045783
                },
                {
                    "lat": 12.928333272128082,
                    "lng": 77.66539984909521
                },
                {
                    "lat": 12.926548711940987,
                    "lng": 77.66597161951744
                },
                {
                    "lat": 12.925127696385385,
                    "lng": 77.66474298299214
                },
                {
                    "lat": 12.923343125205921,
                    "lng": 77.66531474706655
                },
                {
                    "lat": 12.92297953899207,
                    "lng": 77.66711515148745
                },
                {
                    "lat": 12.921194926237721,
                    "lng": 77.66768691303507
                },
                {
                    "lat": 12.920831296107975,
                    "lng": 77.66948734993137
                },
                {
                    "lat": 12.922252306976922,
                    "lng": 77.67071605646302
                },
                {
                    "lat": 12.921888661175856,
                    "lng": 77.67251655701233
                },
                {
                    "lat": 12.923309686958975,
                    "lng": 77.67374532337911
                },
                {
                    "lat": 12.925094360888588,
                    "lng": 77.67317355419945
                },
                {
                    "lat": 12.92651540392407,
                    "lng": 77.67440234540395
                },
                {
                    "lat": 12.928300066862336,
                    "lng": 77.67383056987845
                },
                {
                    "lat": 12.928663656182575,
                    "lng": 77.67203000696131
                },
                {
                    "lat": 12.930448277539448,
                    "lng": 77.67145822890299
                },
                {
                    "lat": 12.93081182293575,
                    "lng": 77.6696576984536
                },
                {
                    "lat": 12.929390775219803,
                    "lng": 77.66842897724833
                }
            ]

In [100]:
coordinates[1]['lat'],

12.92975430493654

In [94]:
h3.polyfill(coordinates,9,geo_json_conformant=True)

TypeError: Argument 'geojson' has incorrect type (expected dict, got list)

In [96]:
h3.polyfill_geojson(coordinates,9)

TypeError: list indices must be integers or slices, not str

In [134]:
api_response['distance']

11.511522813958921

In [214]:
net_df = final_df[final_df.final_order_status=='dropped'].groupby('pool_id')['final_order_status'].count().reset_index()

In [217]:
net_df[net_df.final_order_status==2].pool_id.unique()

array(['64bdeff6e84654e7fca14ca5', '64bdf16c4cf74b27e8aca1a9',
       '64bdf771de5226414b1df073', '64be0154b3bff00b53aa3fd6',
       '64be045ce84654e7fca19000', '64be73aa7f7258c0ba86d271',
       '64bf4281621f317c1dd1be52', '64bf42988657bdb2a3124790',
       '64bf434dd9aeb76353a3218f', '64bf4d68da0a1bc36f7bb5cb',
       '64bfc72dd9aeb76353a41dd4', '64bfc757634ed015a3409a64',
       '64bfcd163e5dbb45a7e3733e', '64bfcd60a70f0daba640b5d0',
       '64c08e78ed7b75c49c9d33c4', '64c093e7a70f0daba6416783',
       '64c094f58a0a2c8fa494d5c9', '64c09b2fda0a1bc36f7d6a60',
       '64c09e2fed7b75c49c9d62a3', '64c09ff2aac577c606544c9c',
       '64c0a129d9aeb76353a50878', '64c0aa757f56fa3b82428587',
       '64c0aac9621f317c1dd3c357', '64c0aef9ec5d76947fdc11f0'],
      dtype=object)