## Imports

In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import datetime as datetime

from scipy import stats
from pyhive import presto
from datetime import datetime, timedelta

import warnings
warnings.filterwarnings('ignore')

In [2]:
pd.set_option('display.max_columns', 50)
pd.set_option('display.max_rows', 300)

In [3]:
## Connection
connection = presto.connect(
        host='presto-gateway.serving.data.production.internal',
        port=80,
        protocol='http',
        catalog='hive',
        username='manoj.ravirajan@rapido.bike'
)

## Datasets & Parameter

In [4]:
## Parameter 
date = '20250117'

In [7]:
## base

base_query = f"""

    select
        *
    from 
        canonical.iceberg_log_telemetry_customer_debug_events_android_immutable 
    where 
        yyyymmdd = '{date}' 
        and eventname = 'pageAnalytics'
        and eventprops__currentcity = 'Bangalore'
        and event_hh = '09'
"""

df_base_query = pd.read_sql(base_query, connection)
df_base_query

,epoch,yyyymmdd,hhmmss,quarter_hour,hh,updated_epoch,updated_yyyymmdd,updated_hhmmss,updated_quarter_hour,updated_hh,event_epoch,event_yyyymmdd,event_hhmmss,event_quarter_hour,event_hh,id,version,eventid,eventname,ts,profile__identity,eventprops__appversion,eventprops__clevertapid,eventprops__currentcity,eventprops__currentcluster,...,eventprops__screen,eventprops__userid,eventprops__yyyymmdd,_platform_metadata,_corrupt_record,eventprops__eventtype,eventprops__fareestimateid,eventprops__orderid,eventprops__pagename,eventprops__servicedetailid,eventprops__configfetchstatus,eventprops__reason,eventprops__isodrdcustomviewenabled,eventprops__message,eventprops__order_id,eventprops__order_status,eventprops__order_type,eventprops__reasons_for_failure,eventprops__remaining_distance,eventprops__remaining_distance_range_drop,eventprops__remaining_distance_range_pickup,eventprops__servicename,eventprops__status,eventprops__traffic_aware_polyline_drop,eventprops__traffic_aware_polyline_pickup
0,1737084928408,20250117,090528,0900,09,1737084928408,20250117,090528,0900,09,1737084928408,20250117,090528,0900,09,1c45caf0-002e-46be-bfcf-b35fc327d983-1737084928,1.0.1,1c45caf0-002e-46be-bfcf-b35fc327d983-1737084928,pageAnalytics,1737084928408,62a0418671bfd2ae25b7fc0e,8.41.0,__gd2f7f36256e84c658da368f99d697872,Bangalore,BTM Second Stage,...,None,62a0418671bfd2ae25b7fc0e,20250117,"{""datasourceName"":""log.telemetry.customer.debu...",None,page_entry,6789cde51a481a9b675e026b,6789cdf62fb7675e743ff2e4,post_order_screen,5c53562fceb6fc9241980547,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1,1737086070749,20250117,092430,0915,09,1737086070749,20250117,092430,0915,09,1737086070749,20250117,092430,0915,09,4419f5f2-b287-45cb-a0fb-935cc8326131-1737086070,1.0.1,4419f5f2-b287-45cb-a0fb-935cc8326131-1737086070,pageAnalytics,1737086070749,6301db9380b3dbe70719494b,8.37.1,__62e7a75474594aa584562805fb64bae5,Bangalore,Majestic,...,None,6301db9380b3dbe70719494b,20250117,"{""datasourceName"":""log.telemetry.customer.debu...",None,page_entry,None,None,pickup_drop_screen,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2,1737087599889,20250117,094959,0945,09,1737087599889,20250117,094959,0945,09,1737087599889,20250117,094959,0945,09,a3f9dcd3-4b2e-4c16-af41-4e9bc3644fac-1737087599,1.0.1,a3f9dcd3-4b2e-4c16-af41-4e9bc3644fac-1737087599,pageAnalytics,1737087599889,674d58184bfc8f36bc2b94f0,8.41.0,__6ea2cec32e574852b866bfeafb024aa8,Bangalore,BLR_Ashok Nagar,...,None,674d58184bfc8f36bc2b94f0,20250117,"{""datasourceName"":""log.telemetry.customer.debu...",None,page_entry,None,None,pip_overlay_screen,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
3,1737087051215,20250117,094051,0930,09,1737087051215,20250117,094051,0930,09,1737087051215,20250117,094051,0930,09,5e9d4972-f4c2-445b-8af4-0088ccc857fc-1737087051,1.0.1,5e9d4972-f4c2-445b-8af4-0088ccc857fc-1737087051,pageAnalytics,1737087051215,674d58184bfc8f36bc2b94f0,8.41.0,__6ea2cec32e574852b866bfeafb024aa8,Bangalore,BLR_Ashok Nagar,...,None,674d58184bfc8f36bc2b94f0,20250117,"{""datasourceName"":""log.telemetry.customer.debu...",None,page_exit,67892574945bababcace8890,678925b40b2c2c1265d4b90d,post_order_screen,5c53562fceb6fc9241980547,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
4,1737085113808,20250117,090833,0900,09,1737085113808,20250117,090833,0900,09,1737085113808,20250117,090833,0900,09,572427c2-9223-473a-92a0-39f29d01e834-1737085113,1.0.1,572427c2-9223-473a-92a0-39f29d01e834-1737085113,pageAnalytics,1737085113808,674d58184bfc8f36bc2b94f0,8.41.0,__6ea2cec32e574852b866bfeafb024aa8,Bangalore,BLR_Ashok Nagar,...,None,674d58184bfc8f36bc2b94f0,20250117,"{""datasourceName"":""log.telemetry.customer.debu...",None,page_exit,67892574945bababcace8890,678925b40b2c2c1265d4b90d,post_order_screen,5c53562fceb6fc9241980547,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1952780,1737086886975,20250117,093806,0930,09,1737086886975,20250117,093806,0930,09,1737086886975,20250117,093806,0930,09,f3fec2cd-f0c0-49b5-ad27-f27a941a4e53-1737086886,1.0.1,f3fec2cd-f0c0-49b5-ad27-f27a941a4e53-1737086886,pageAnalytics,1737086886975,65bdb62e446c5f2bb9685c22,8.42.0,__cc00e8a95c664c8499e591dabe946608,Bangalore,Doddanekundi,...,None,65bdb62e446c5f2bb9685c22,20250117,"{""datasourceName"":""log.telemetry.customer.debu...",None,page_exit,None,None,home_screen_test,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1952781,1737085477279,20250117,091437,0900,09,1737085477279,20250117,091437,0900,09,1737085477279,20250117,091437,0900,09,23f0c0d1-92c2-4b64-a559-cf700ea6cdad-1737085477,1.0.1,23f0c0d1-92c2-4b64-a559-cf700ea6cdad-1737085477,pageAnalytics,1737085477279,5a434835232df644307800d8,8.42.0,__8cf3ee9f80b84ede8d29dce0bbb2509d,Bangalore,Majestic,...,None,5a434835232df644307800d8,20250117,"{""datasourceName"":""log.telemetry.customer.debu...",None,page_entry,6789cfb7de4530a0fa4d4853,6789cfed0b2c2c1265d4f383,post_order_screen,57370b61a6855d70057417d1,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1952782,1737087081818,20250117,094121,0930,09,1737087081818,20250117,094121,0930,09,1737087081818,20250117,094121,0930,09,b0f1444c-a378-41f7-bd32-2885bab44daf-1737087081,1.0.1,b0f1444c-a378-41f7-bd32-2885bab44daf-1737087081,pageAnalytics,1737087081818,65e87dee8d3671963e95c1b8,8.42.0,__8caec9b53d7e46a7b870a4f0eb2b483b,Bangalore,Ramamurthy Nagar,...,None,65e87dee8d3671963e95c1b8,20250117,"{""datasourceName"":""log.telemetry.customer.debu...",None,page_exit,6789d7bc6b94b5dc35050a7f,6789d7c8e05219119f7d1c6b,post_order_screen,5c53562fceb6fc9241980547,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1952783,1737086997283,20250117,093957,0930,09,1737086997283,20250117,093957,0930,09,1737086997283,20250117,093957,0930,09,2e57c833-d2c9-4550-bee5-713846cb7fd5-1737086997,1.0.1,2e57c833-d2c9-4550-bee5-713846cb7fd5-1737086997,pageAnalytics,1737086997283,675c20b55ab30b1ec838bafe,8.42.0,__16ed705ff71b4e53a0ef20135bbd69d4,Bangalore,South Bidadi,...,None,675c20b55ab30b1ec838bafe,20250117,"{""datasourceName"":""log.telemetry.customer.debu...",None,page_entry,6789d6851a481a36705f25d1,6789d68eff6e046ca5a835cb,post_order_screen,5c53562fceb6fc9241980547,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1952784,1737087937399,20250117,095537,0945,09,1737087937399,20250117,095537,0945,09,1737087937399,20250117,095537,0945,09,520b3fc1-e65b-4718-b8b9-226838478b5c-1737087937,1.0.1,520b3fc1-e65b-4718-b8b9-226838478b5c-1737087937,pageAnalytics,1737087937399,659e996dfb482065533350aa,8.43.0,__a72ad589d4024409b76f7ed19ed2de95,Bangalore,NIMHANS,...,None,659e996dfb482065533350aa,20250117,"{""datasourceName"":""log.telemetry.customer.debu...",None,page_entry,6789da45184ca44be00fe447,6789da521b692b3135e00132,post_order_screen,57370b61a6855d70057417d1,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None

In [8]:
df_base_query.shape

(1952785, 57)

In [10]:
df_base_query.columns

Index(['epoch', 'yyyymmdd', 'hhmmss', 'quarter_hour', 'hh', 'updated_epoch',
       'updated_yyyymmdd', 'updated_hhmmss', 'updated_quarter_hour',
       'updated_hh', 'event_epoch', 'event_yyyymmdd', 'event_hhmmss',
       'event_quarter_hour', 'event_hh', 'id', 'version', 'eventid',
       'eventname', 'ts', 'profile__identity', 'eventprops__appversion',
       'eventprops__clevertapid', 'eventprops__currentcity',
       'eventprops__currentcluster', 'eventprops__epoch', 'eventprops__hhmmss',
       'eventprops__latitude', 'eventprops__locationaccuracy',
       'eventprops__longitude', 'eventprops__occurred_date',
       'eventprops__platform', 'eventprops__screen', 'eventprops__userid',
       'eventprops__yyyymmdd', '_platform_metadata', '_corrupt_record',
       'eventprops__eventtype', 'eventprops__fareestimateid',
       'eventprops__orderid', 'eventprops__pagename',
       'eventprops__servicedetailid', 'eventprops__configfetchstatus',
       'eventprops__reason', 'eventprops__isodrdcustomviewenabled',
       'eventprops__message', 'eventprops__order_id',
       'eventprops__order_status', 'eventprops__order_type',
       'eventprops__reasons_for_failure', 'eventprops__remaining_distance',
       'eventprops__remaining_distance_range_drop',
       'eventprops__remaining_distance_range_pickup',
       'eventprops__servicename', 'eventprops__status',
       'eventprops__traffic_aware_polyline_drop',
       'eventprops__traffic_aware_polyline_pickup'],
      dtype='object')

In [13]:
df_base_query.groupby('eventprops__pagename').agg(customers = ('profile__identity','nunique')).reset_index().sort_values(by='customers', ascending=False)

                  eventprops__pagename  customers
44                    home_screen_test      53870
41                fare_estimate_screen      42275
71                  splash_screen_test      41943
55                   post_order_screen      36261
54                  pip_overlay_screen      31849
27               captain_search_screen      31319
35                          cpl_screen      30909
53                  pickup_drop_screen      26693
11                FirebaseChatActivity      10887
19               SelectFromMapActivity       4587
48                      invoice_screen       3750
13           InAppNotificationActivity       2656
42                      hamburger_menu       1825
32             confirm_new_fare_screen       1513
72        support_host_screen_internal       1124
3                AddressSearchActivity        831
69          send_receive_parcel_screen        766
20                  SignedCallActivity        682
47        invoice_pay_with_cash_screen        615
63                  ride_detail_screen        600
57                   power_pass_screen        375
49                   local_home_screen        372
68         select_local_address_screen        267
22                     WebViewActivity        235
18           ScratchCardBannerActivity        217
61                     referral_screen        214
58                      profile_screen        196
52                      payment_screen        180
28                   chat_bot_web_view        171
70                      setting_screen        134
62            rewards_home_page_screen        122
1                           AdActivity        106
31                        coins_screen        100
46          invoice_pay_at_drop_screen         98
74               ticket_listing_screen         95
17       PlayCoreDialogWrapperActivity         83
6                     CheckoutActivity         80
75                   verify_otp_screen         79
66                 scratch_card_screen         78
25          add_money_to_wallet_screen         73
2             AddMoneyToWalletActivity         73
38           emergency_contacts_screen         65
29              claim_insurance_screen         57
40                          faq_screen         55
39                  faq_article_screen         53
9                   DatePickerActivity         52
34              contacts_picker_screen         51
12                     HotspotActivity         45
59                rapido_wallet_screen         44
50                   onboarding_screen         36
30            coin_transactions_screen         31
64                 ride_history_screen         27
26  add_money_to_wallet_success_screen         27
73          ticket_conversation_screen         27
7              CompleteProfileActivity         25
14           NotificationInboxActivity         24
10                  FavouritesActivity         23
51                     passbook_screen         21
60   rapido_wallet_transactions_screen         21
77    wallet_transaction_detail_screen         20
8           ConversationDetailActivity         19
21             UserPreferencesActivity         18
5                  ChannelListActivity         17
36               create_profile_screen         14
65                       safety_screen         13
45                       invite_screen         12
56              power_pass_info_screen         11
23                   about_page_screen         11
33   contacts_permission_denied_screen         11
0                  APayBrowserActivity         11
67                 search_issue_screen          9
43                         help_screen          7
76                wallet_detail_screen          7
16           PictureAttachmentActivity          3
24  add_money_to_wallet_failure_screen          2
15            PaymentProcessorActivity          1
37             earned_referrals_screen          1
4                      BaseSimplScreen          1

In [15]:
df_base_query[df_base_query['profile__identity'] == '62b869159672e815ff701708']

,epoch,yyyymmdd,hhmmss,quarter_hour,hh,updated_epoch,updated_yyyymmdd,updated_hhmmss,updated_quarter_hour,updated_hh,event_epoch,event_yyyymmdd,event_hhmmss,event_quarter_hour,event_hh,id,version,eventid,eventname,ts,profile__identity,eventprops__appversion,eventprops__clevertapid,eventprops__currentcity,eventprops__currentcluster,...,eventprops__screen,eventprops__userid,eventprops__yyyymmdd,_platform_metadata,_corrupt_record,eventprops__eventtype,eventprops__fareestimateid,eventprops__orderid,eventprops__pagename,eventprops__servicedetailid,eventprops__configfetchstatus,eventprops__reason,eventprops__isodrdcustomviewenabled,eventprops__message,eventprops__order_id,eventprops__order_status,eventprops__order_type,eventprops__reasons_for_failure,eventprops__remaining_distance,eventprops__remaining_distance_range_drop,eventprops__remaining_distance_range_pickup,eventprops__servicename,eventprops__status,eventprops__traffic_aware_polyline_drop,eventprops__traffic_aware_polyline_pickup
41,1737085915475,20250117,092155,0915,09,1737085915475,20250117,092155,0915,09,1737085915475,20250117,092155,0915,09,66530535-0717-497d-ac16-371f6c79ffeb-1737085915,1.0.1,66530535-0717-497d-ac16-371f6c79ffeb-1737085915,pageAnalytics,1737085915475,62b869159672e815ff701708,8.42.0,__g75649e43795d4ded950a7e4dae3c254b,Bangalore,Mathikere,...,None,62b869159672e815ff701708,20250117,"{""datasourceName"":""log.telemetry.customer.debu...",None,page_exit,None,None,cpl_screen,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
33854,1737085880982,20250117,092120,0915,09,1737085880982,20250117,092120,0915,09,1737085880982,20250117,092120,0915,09,a11b6ea5-b599-49cc-82bb-9bf8238a4d56-1737085880,1.0.1,a11b6ea5-b599-49cc-82bb-9bf8238a4d56-1737085880,pageAnalytics,1737085880982,62b869159672e815ff701708,8.42.0,__g75649e43795d4ded950a7e4dae3c254b,Bangalore,Mathikere,...,None,62b869159672e815ff701708,20250117,"{""datasourceName"":""log.telemetry.customer.debu...",None,page_entry,None,None,home_screen_test,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
150630,1737085879638,20250117,092119,0915,09,1737085879638,20250117,092119,0915,09,1737085879638,20250117,092119,0915,09,9aaa2ad4-487f-4227-bd16-2d14dbd423cc-1737085879,1.0.1,9aaa2ad4-487f-4227-bd16-2d14dbd423cc-1737085879,pageAnalytics,1737085879638,62b869159672e815ff701708,8.42.0,__g75649e43795d4ded950a7e4dae3c254b,Bangalore,Mathikere,...,None,62b869159672e815ff701708,20250117,"{""datasourceName"":""log.telemetry.customer.debu...",None,page_entry,None,None,splash_screen_test,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
388221,1737085879651,20250117,092119,0915,09,1737085879651,20250117,092119,0915,09,1737085879651,20250117,092119,0915,09,416cd1e9-9683-4585-9917-d4b19ef1e3d9-1737085879,1.0.1,416cd1e9-9683-4585-9917-d4b19ef1e3d9-1737085879,pageAnalytics,1737085879651,62b869159672e815ff701708,8.42.0,__g75649e43795d4ded950a7e4dae3c254b,Bangalore,Mathikere,...,None,62b869159672e815ff701708,20250117,"{""datasourceName"":""log.telemetry.customer.debu...",None,page_entry,None,None,splash_screen_test,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
466148,1737085881019,20250117,092121,0915,09,1737085881019,20250117,092121,0915,09,1737085881019,20250117,092121,0915,09,c6d342e4-bc98-4667-a1bf-b92eb889fc35-1737085881,1.0.1,c6d342e4-bc98-4667-a1bf-b92eb889fc35-1737085881,pageAnalytics,1737085881019,62b869159672e815ff701708,8.42.0,__g75649e43795d4ded950a7e4dae3c254b,Bangalore,Mathikere,...,None,62b869159672e815ff701708,20250117,"{""datasourceName"":""log.telemetry.customer.debu...",None,page_exit,None,None,splash_screen_test,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
591512,1737085911521,20250117,092151,0915,09,1737085911521,20250117,092151,0915,09,1737085911521,20250117,092151,0915,09,179d3b75-8edd-4c89-bb10-b3aa4c312a5d-1737085911,1.0.1,179d3b75-8edd-4c89-bb10-b3aa4c312a5d-1737085911,pageAnalytics,1737085911521,62b869159672e815ff701708,8.42.0,__g75649e43795d4ded950a7e4dae3c254b,Bangalore,Mathikere,...,None,62b869159672e815ff701708,20250117,"{""datasourceName"":""log.telemetry.customer.debu...",None,page_entry,None,None,confirm_new_fare_screen,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
615239,1737085913741,20250117,092153,0915,09,1737085913741,20250117,092153,0915,09,1737085913741,20250117,092153,0915,09,be92adde-61fe-4543-9d1e-96e4948677ef-1737085913,1.0.1,be92adde-61fe-4543-9d1e-96e4948677ef-1737085913,pageAnalytics,1737085913741,62b869159672e815ff701708,8.42.0,__g75649e43795d4ded950a7e4dae3c254b,Bangalore,Mathikere,...,None,62b869159672e815ff701708,20250117,"{""datasourceName"":""log.telemetry.customer.debu...",None,page_exit,None,None,confirm_new_fare_screen,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
640440,1737085900612,20250117,092140,0915,09,1737085900612,20250117,092140,0915,09,1737085900612,20250117,092140,0915,09,8213b853-0fa9-43d0-8f3b-eb5e0756b122-1737085900,1.0.1,8213b853-0fa9-43d0-8f3b-eb5e0756b122-1737085900,pageAnalytics,1737085900612,62b869159672e815ff701708,8.42.0,__g75649e43795d4ded950a7e4dae3c254b,Bangalore,Mathikere,...,None,62b869159672e815ff701708,20250117,"{""datasourceName"":""log.telemetry.customer.debu...",None,page_exit,None,None,fare_estimate_screen,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
661512,1737085893454,20250117,092133,0915,09,1737085893454,20250117,092133,0915,09,1737085893454,20250117,092133,0915,09,0306c791-8541-45d4-895a-f546164aeab0-1737085893,1.0.1,0306c791-8541-45d4-895a-f546164aeab0-1737085893,pageAnalytics,1737085893454,62b869159672e815ff701708,8.42.0,__g75649e43795d4ded950a7e4dae3c254b,Bangalore,Mathikere,...,None,62b869159672e815ff701708,20250117,"{""datasourceName"":""log.telemetry.customer.debu...",None,page_exit,None,None,home_screen_test,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
991006,1737085913710,20250117,092153,0915,09,1737085913710,20250117,092153,0915,09,1737085913710,20250117,092153,0915,09,dc0ed9f1-4413-4bd1-baff-f1ec4700400b-1737085913,1.0.1,dc0ed9f1-4413-4bd1-baff-f1ec4700400b-1737085913,pageAnalytics,1737085913710,62b869159672e815ff701708,8.42.0,__g75649e43795d4ded950a7e4dae3c254b,Bangalore,Mathikere,...,None,62b869159672e815ff701708,20250117,"{""datasourceName"":""log.telemetry.customer.debu...",None,page_entry,None,None,cpl_screen,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1470205,1737085911527,20250117,092151,0915,09,1737085911527,20250117,092151,0915,09,1737085911527,20250117,092151,0915,09,057e128f-dd15-4e58-bcae-47db1e1d3e5d-1737085911,1.0.1,057e128f-dd15-4e58-bcae-47db1e1d3e5d-1737085911,pageAnalytics,1737085911527,62b869159672e815ff701708,8.42.0,__g75649e43795d4ded950a7e4dae3c254b,Bangalore,Mathikere,...,None,62b869159672e815ff701708,20250117,"{""datasourceName"":""log.telemetry.customer.debu...",None,page_exit,None,None,cpl_screen,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1871468,1737085900615,20250117,092140,0915,09,1737085900615,20250117,092140,0915,09,1737085900615,20250117,092140,0915,09,3bb9d31a-9119-4945-b88c-0630c24d4e2e-1737085900,1.0.1,3bb9d31a-9119-4945-b88c-0630c24d4e2e-1737085900,pageAnalytics,1737085900615,62b869159672e815ff701708,8.42.0,__g75649e43795d4ded950a7e4dae3c254b,Bangalore,Mathikere,...,None,62b869159672e815ff701708,20250117,"{""datasourceName"":""log.telemetry.customer.debu...",None,page_entry,None,None,cpl_screen,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1950103,1737085893439,20250117,092133,0915,09,1737085893439,20250117,092133,0915,09,1737085893439,20250117,092133,0915,09,da27fd0c-1896-453c-a328-5a9a45976330-1737085893,1.0.1,da27fd0c-1896-453c-a328-5a9a45976330-1737085893,pageAnalytics,1737085893439,62b869159672e815ff701708,8.42.0,__g75649e43795d4ded950a7e4dae3c254b,Bangalore,Mathikere,...,None,62b869159672e815ff701708,20250117,"{""datasourceName"":""log.telemetry.customer.debu...",None,page_entry,None,None,fare_estimate_screen,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None

In [11]:
df_base_query.to_parquet('data_dump_for_page_analytics_bangalore.parquet', index=False)

In [12]:
test1 = pd.read_parquet('data_dump_for_page_analytics_bangalore.parquet')

In [13]:
test1.shape

(1338288, 9)

In [15]:
1341310-1338288

3022

In [18]:
## base

base_query = f"""

SELECT
    city AS city,
    pickup_cluster,
    user_id as customer_id,
    fare_estimate_id,service_detail_id as service_id_fare,
    api_context,
    date_format(from_unixtime(epoch / 1000, 'Asia/Kolkata'), '%Y-%m-%d') AS orderdate,
    cast(final_amount AS double) AS fe_amount,polyline,
    epoch
FROM
    hive.pricing.fare_estimates_enriched
WHERE
     yyyymmdd = '20241021'             
     and service_name in ('Link')
     AND city = 'Bangalore'
     AND api_context='/fare/estimate'
"""

df_base_query = pd.read_sql(base_query, connection)
df_base_query

DatabaseError: {'message': 'Query exceeded the maximum execution time limit of 10.00m', 'errorCode': 131075, 'errorName': 'EXCEEDED_TIME_LIMIT', 'errorType': 'INSUFFICIENT_RESOURCES', 'failureInfo': {'type': 'io.trino.spi.TrinoException', 'message': 'Query exceeded the maximum execution time limit of 10.00m', 'suppressed': [], 'stack': ['io.trino.execution.QueryTracker.enforceTimeLimits(QueryTracker.java:187)', 'io.trino.execution.QueryTracker.lambda$start$0(QueryTracker.java:89)', 'com.google.common.util.concurrent.MoreExecutors$ScheduledListeningDecorator$NeverSuccessfulListenableFutureTask.run(MoreExecutors.java:730)', 'java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)', 'java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)', 'java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)', 'java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)', 'java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)', 'java.base/java.lang.Thread.run(Thread.java:829)']}}

In [ ]:
df_base_query.to_parquet('fare_estimates_bangalore_link_20241021.parquet', index=False)