## Imports

In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import datetime as datetime

from scipy import stats
from pyhive import presto
from datetime import datetime, timedelta
from sklearn.model_selection import train_test_split
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.model_selection import StratifiedKFold

import warnings
warnings.filterwarnings('ignore')

In [2]:
pd.set_option('display.max_columns', 100)
pd.set_option('display.max_rows', 300)
pd.set_option('display.max_colwidth', None)

In [3]:
## Connection
connection = presto.connect(
        host = 'bi-presto.serving.data.production.internal',
        # 'bi-trino-2.serving.data.production.internal',
        # 'bi-presto.serving.data.production.internal' ,
        #host='presto-gateway.serving.data.production.internal',
        port=80,
        protocol='http',
        catalog='hive',
        username='manoj.ravirajan@rapido.bike'
)

## Methodology
### Objective: 
- To build an (a/b) experiment customer group for conducting bias-free experimentation.

### Segmentation Criteria: 
- Customer Entry Criteria (Pan-India <> Link & Auto & Cab) 
- Customer Metrics (LTR <> FE <> RR <> NET <> Segment <> COBRA <> COBRM <> OCARA <> expired)

### Collect Data: 
- fare_estimates_enriched <> order_logs_snapshot/immutable/fact <> iallocator_customer_segments
- Create a customer-level aggregated view.

### Stratified Random Sampling: 
- Use randomization to assign customers within each segment to either the control group (A) or the treatment group (B).
- <b>Balance Groups:</b>     
    - Ensure that the size of the groups is balanced. 
    - Conduct a pre-analysis to check if the groups are indeed homogeneous before starting the experiment.
    - This helps in confirming that the segmentation strategy is effective.
- <b>Exclude Outliers:</b>
    - Identify and exclude outliers that might skew the results. 
    - Outliers could be customers with extremely high or low values in the chosen criteria that are not representative of the majority.
	
### Implement the Experiment: 
- Implement the changes for the treatment group and keep the control group unchanged. 
	
### Monitor and Analyse: 
- Monitor the experiment in real-time and, once completed, analyse the results to determine if there are significant differences between the groups.

## Parameter

In [4]:
current_working_directory = os.getcwd()
print(current_working_directory)

/Users/E2074/analytics/customer/Ads-Monetisation/jackport

In [5]:
local_datasets = '/Users/E2074/local-datasets/customer/ads-monetisation/jackport/'

In [6]:
## Parameter 
start_date = '2024-12-20'
end_date = '2025-01-17'
cities = ['Hyderabad', 'Bangalore', 'Delhi', 'Chennai', 'Mumbai', 'Kolkata', 'Ahmedabad', 'Pune', 'Jaipur', 'Vijayawada']

services = ['Auto', 'Auto NCR', 'Auto Pet','Auto Pool','AutoPremium', 'Bike Lite', 'Bike Metro', 'Bike Pink', 'Link', 'CabEconomy', 'CabPremium']

In [7]:
# Convert the lists to comma-separated strings
city_str = "', '".join(city for city in cities)
service_str = "', '".join(service for service in services)

print(city_str)
print(service_str)

Hyderabad', 'Bangalore', 'Delhi', 'Chennai', 'Mumbai', 'Kolkata', 'Ahmedabad', 'Pune', 'Jaipur', 'Vijayawada
Auto', 'Auto NCR', 'Auto Pet', 'Auto Pool', 'AutoPremium', 'Bike Lite', 'Bike Metro', 'Bike Pink', 'Link', 'CabEconomy', 'CabPremium

## Datasets

In [26]:
##customer_funnel
def func_get_customer_base(start_date, end_date, city_str, service_str):
        
    customer_funnel = f"""
    
        WITH base AS (
        
            SELECT
                customerid,
                city,
                COALESCE(SUM(ao_sessions_unique_daily), 0)ao_sessions,
                COALESCE(SUM(fe_sessions_unique_daily), 0)fe_sessions,
                COALESCE(SUM(rr_sessions_unique_daily), 0)rr_sessions,
                
                COALESCE(SUM(CASE WHEN service_name IN ('Bike Lite', 'Bike Metro', 'Bike Pink', 'Link') THEN gross_rides_daily END), 0)link_gross_rides,
                COALESCE(SUM(CASE WHEN service_name IN ('Auto', 'Auto NCR', 'Auto Pet','Auto Pool','AutoPremium') THEN gross_rides_daily END), 0)auto_gross_rides,
                COALESCE(SUM(CASE WHEN service_name IN ('CabEconomy', 'CabPremium') THEN gross_rides_daily END), 0)cab_gross_rides,
                
                COALESCE(SUM(CASE WHEN service_name IN ('Bike Lite', 'Bike Metro', 'Bike Pink', 'Link') THEN net_rides_daily END), 0)link_net_rides,
                COALESCE(SUM(CASE WHEN service_name IN ('Auto', 'Auto NCR', 'Auto Pet','Auto Pool','AutoPremium') THEN net_rides_daily END), 0) auto_net_rides,
                COALESCE(SUM(CASE WHEN service_name IN ('CabEconomy', 'CabPremium') THEN net_rides_daily END), 0) cab_net_rides
                
            FROM
                (
                SELECT 
                    day,
                    customerid,
                    city,
                    service_name,
                    MAX(ao_sessions_unique_daily) ao_sessions_unique_daily,
                    MAX(fe_sessions_unique_daily) fe_sessions_unique_daily,
                    MAX(rr_sessions_unique_daily) rr_sessions_unique_daily,
                    
                    SUM(gross_rides_daily) gross_rides_daily,
                    SUM(net_rides_daily) net_rides_daily
                    
                FROM 
                    datasets.customer_rf_daily_kpi 
                WHERE 
                    day >= '{start_date}' 
                    AND day <= '{end_date}'
                    AND city IN ('{city_str}')
                    -- ('Hyderabad', 'Bangalore', 'Delhi', 'Chennai', 'Mumbai', 'Kolkata', 'Ahmedabad', 'Pune', 'Jaipur', 'Vijayawada')
                    AND service_name IN ('{service_str}')
                    -- IN ('Auto', 'Auto NCR', 'Auto Pet','Auto Pool','AutoPremium', 'Bike Lite', 'Bike Metro', 'Bike Pink', 'Link','CabEconomy', 'CabPremium')
                GROUP BY 1,2,3,4
                )
            GROUP BY 1,2
            )

            SELECT 
                *
            FROM 
                base        
    """
    
    df_customer_funnel = pd.read_sql(customer_funnel, connection)
    print(df_customer_funnel.shape)
    df_customer_funnel.to_csv(local_datasets + 'raw/customer_data.csv',index=False)

func_get_customer_base(start_date, end_date, city_str, service_str)

(21321993, 11)

In [29]:
##customer_funnel
def func_get_customer_segment(start_date, end_date, city_str, service_str):
        
    customer_funnel = f"""
    
        WITH olf AS (
        
            SELECT
                customer_id,
                customer_obj_mobile,
                city_name
            FROM 
                (
                SELECT
                    customer_id,
                    customer_obj_mobile,
                    city_name,
                    row_number() over(partition by customer_id order by order_requested_epoch desc) rn 
                FROM 
                    orders.order_logs_fact
                WHERE
                    yyyymmdd >= '20241220'
                    AND yyyymmdd <= '20250117'
                    AND city_name IN ('{city_str}')
                    AND service_obj_service_name IN ('{service_str}')
                )
            WHERE 
                rn = 1
            ),
            
            segment AS (
            
            SELECT
                customer_id,
                gender_tag as  gender,
                taxi_retention_segments,
                taxi_lifetime_stage,
                taxi_ltr_segment,
                taxi_service_affinity,
                taxi_regularity_segment,
                taxi_fe_regularity_segment
            FROM 
                datasets.iallocator_customer_segments
            WHERE 
                run_date = '2024-12-19'
                AND fe_recency_type IN ('Recent', 'Stationary', 'Dormant')
            )
            
            SELECT
                *
            FROM 
                olf
            LEFT JOIN 
                segment
                ON olf.customer_id = segment.customer_id       
    """
    
    df_customer_funnel = pd.read_sql(customer_funnel, connection)
    print(df_customer_funnel.shape)
    df_customer_funnel.to_csv(local_datasets + 'raw/customer_segment.csv',index=False)

func_get_customer_segment(start_date, end_date, city_str, service_str)

(15604162, 11)

### Reading local extract

In [8]:
df_customer_data = pd.read_csv(local_datasets + 'raw/customer_data.csv')
df_customer_segment = pd.read_csv(local_datasets + 'raw/customer_segment.csv')

In [9]:
df_customer_data.shape

(21321993, 11)

In [10]:
df_customer_segment.shape

(15604162, 11)

In [11]:
df_customer_data.head(1)

,customerid,city,ao_sessions,fe_sessions,rr_sessions,link_gross_rides,auto_gross_rides,cab_gross_rides,link_net_rides,net_rides,cab_net_rides
0,677aa63e96f8353e0483480f,Bangalore,35,32,0,0,0,0,0,0,0

In [12]:
df_customer_data.customerid.nunique()

20372699

In [13]:
df_customer_segment.head(1)

,customer_id,customer_obj_mobile,city_name,customer_id.1,gender,taxi_retention_segments,taxi_lifetime_stage,taxi_ltr_segment,taxi_service_affinity,taxi_regularity_segment,taxi_fe_regularity_segment
0,65733a6024a0f87d756edfdc,8.823815e+09,Ahmedabad,65733a6024a0f87d756edfdc,MALE,GOLD,CHURN_OTB,PHH,UNKNOWN,BI_WEEKLY,BI_WEEKLY

In [14]:
df_customer_segment.customer_id.nunique()

15604162

In [19]:
df_merge = pd.merge(
                    df_customer_data,
                    df_customer_segment,
                    how = 'inner',
                    left_on = ['customerid', 'city'],
                    right_on = ['customer_id', 'city_name']
                   )

In [20]:
df_merge.head(1)

,customerid,city,ao_sessions,fe_sessions,rr_sessions,link_gross_rides,auto_gross_rides,cab_gross_rides,link_net_rides,net_rides,cab_net_rides,customer_id,customer_obj_mobile,city_name,customer_id.1,gender,taxi_retention_segments,taxi_lifetime_stage,taxi_ltr_segment,taxi_service_affinity,taxi_regularity_segment,taxi_fe_regularity_segment
0,5c5297934a267149c7804b96,Chennai,10,10,1,1,0,0,0,0,0,5c5297934a267149c7804b96,9.171172e+09,Chennai,5c5297934a267149c7804b96,MALE,DORMANT,DORMANT,PHH,UNKNOWN,RARE_NEED,MONTHLY

In [21]:
df_merge.shape

(15603622, 22)

In [22]:
df_merge.customerid.nunique()

15603622

In [57]:
df_data = df_merge[[
                    'customerid', 'city', 'customer_obj_mobile',
                    'ao_sessions',	'fe_sessions',	'rr_sessions',
                    'link_gross_rides',	'auto_gross_rides',	'cab_gross_rides',	'link_net_rides',	'net_rides',	'cab_net_rides',
                    'gender',	'taxi_retention_segments',	'taxi_lifetime_stage',	'taxi_ltr_segment',	
                    'taxi_service_affinity',	'taxi_regularity_segment', 'taxi_fe_regularity_segment'
                    ]].copy()

In [58]:
df_data.head(5)

,customerid,city,customer_obj_mobile,ao_sessions,fe_sessions,rr_sessions,link_gross_rides,auto_gross_rides,cab_gross_rides,link_net_rides,net_rides,cab_net_rides,gender,taxi_retention_segments,taxi_lifetime_stage,taxi_ltr_segment,taxi_service_affinity,taxi_regularity_segment,taxi_fe_regularity_segment
0,5c5297934a267149c7804b96,Chennai,9.171172e+09,10,10,1,1,0,0,0,0,0,MALE,DORMANT,DORMANT,PHH,UNKNOWN,RARE_NEED,MONTHLY
1,60cb106f7c2b2649e0686c64,Bangalore,6.300411e+09,300,233,44,45,1,0,39,1,0,MALE,ELITE,COMMITTED,PHH,NO_AFFINITY,DAILY,DAILY
2,62a5ac0d5a4705a8f5a2c016,Delhi,9.971917e+09,18,19,1,0,1,0,0,0,0,MALE,DORMANT,DORMANT,PHH,UNKNOWN,RARE_NEED,BI_WEEKLY
3,64f0ca98b77f5d2a7c9d7b6a,Delhi,9.278336e+09,29,29,2,0,0,3,0,0,2,MALE,PLATINUM,COMMITTED,PHH,LINK_AUTO,MONTHLY,RARE_NEED
4,5cc4631654bc7263ff52a964,Delhi,6.291313e+09,82,59,14,2,14,4,0,4,0,MALE,ELITE,COMMITTED,PHH,UNKNOWN,DAILY,DAILY

In [59]:
df_data['customer_mobile'] = df_data['customer_obj_mobile'].fillna(0).astype(float).astype(int).astype(str)
df_data['is_valid_length'] = df_data['customer_mobile'].str.len() == 10
df_data['is_valid_length'].value_counts()

is_valid_length
True     15603469
False         153
Name: count, dtype: int64

In [60]:
df_data.head(5)

,customerid,city,customer_obj_mobile,ao_sessions,fe_sessions,rr_sessions,link_gross_rides,auto_gross_rides,cab_gross_rides,link_net_rides,net_rides,cab_net_rides,gender,taxi_retention_segments,taxi_lifetime_stage,taxi_ltr_segment,taxi_service_affinity,taxi_regularity_segment,taxi_fe_regularity_segment,customer_mobile,is_valid_length
0,5c5297934a267149c7804b96,Chennai,9.171172e+09,10,10,1,1,0,0,0,0,0,MALE,DORMANT,DORMANT,PHH,UNKNOWN,RARE_NEED,MONTHLY,9171171919,True
1,60cb106f7c2b2649e0686c64,Bangalore,6.300411e+09,300,233,44,45,1,0,39,1,0,MALE,ELITE,COMMITTED,PHH,NO_AFFINITY,DAILY,DAILY,6300410928,True
2,62a5ac0d5a4705a8f5a2c016,Delhi,9.971917e+09,18,19,1,0,1,0,0,0,0,MALE,DORMANT,DORMANT,PHH,UNKNOWN,RARE_NEED,BI_WEEKLY,9971916894,True
3,64f0ca98b77f5d2a7c9d7b6a,Delhi,9.278336e+09,29,29,2,0,0,3,0,0,2,MALE,PLATINUM,COMMITTED,PHH,LINK_AUTO,MONTHLY,RARE_NEED,9278336392,True
4,5cc4631654bc7263ff52a964,Delhi,6.291313e+09,82,59,14,2,14,4,0,4,0,MALE,ELITE,COMMITTED,PHH,UNKNOWN,DAILY,DAILY,6291313175,True

In [63]:
df = df_data[df_data['is_valid_length'] == True][[
                    'customerid', 'city', 'customer_mobile',
                    'ao_sessions',	'fe_sessions',	'rr_sessions',
                    'link_gross_rides',	'auto_gross_rides',	'cab_gross_rides',	'link_net_rides',	'net_rides',	'cab_net_rides',
                    'gender',	'taxi_retention_segments',	'taxi_lifetime_stage',	'taxi_ltr_segment',	
                    'taxi_service_affinity',	'taxi_regularity_segment', 'taxi_fe_regularity_segment'
                    ]]

In [64]:
df.head(5)

,customerid,city,customer_mobile,ao_sessions,fe_sessions,rr_sessions,link_gross_rides,auto_gross_rides,cab_gross_rides,link_net_rides,net_rides,cab_net_rides,gender,taxi_retention_segments,taxi_lifetime_stage,taxi_ltr_segment,taxi_service_affinity,taxi_regularity_segment,taxi_fe_regularity_segment
0,5c5297934a267149c7804b96,Chennai,9171171919,10,10,1,1,0,0,0,0,0,MALE,DORMANT,DORMANT,PHH,UNKNOWN,RARE_NEED,MONTHLY
1,60cb106f7c2b2649e0686c64,Bangalore,6300410928,300,233,44,45,1,0,39,1,0,MALE,ELITE,COMMITTED,PHH,NO_AFFINITY,DAILY,DAILY
2,62a5ac0d5a4705a8f5a2c016,Delhi,9971916894,18,19,1,0,1,0,0,0,0,MALE,DORMANT,DORMANT,PHH,UNKNOWN,RARE_NEED,BI_WEEKLY
3,64f0ca98b77f5d2a7c9d7b6a,Delhi,9278336392,29,29,2,0,0,3,0,0,2,MALE,PLATINUM,COMMITTED,PHH,LINK_AUTO,MONTHLY,RARE_NEED
4,5cc4631654bc7263ff52a964,Delhi,6291313175,82,59,14,2,14,4,0,4,0,MALE,ELITE,COMMITTED,PHH,UNKNOWN,DAILY,DAILY

In [69]:
print(df.shape)
print(df.customerid.nunique())
print(df.customer_mobile.nunique())

(15603469, 19)
15603469
15603443

In [73]:
result = (
    df\
        .groupby('customer_mobile')['customerid']\
        .nunique()\
        .reset_index(name='cux')
    )

result = result[result['cux'] > 1]
exclude_list = result['customer_mobile'].tolist()

['6264897579',
 '6363027744',
 '7022656534',
 '7200581303',
 '7207608298',
 '7838670577',
 '8008278089',
 '8148962694',
 '8248906232',
 '8284884429',
 '8553793353',
 '8555044803',
 '8838354346',
 '8892880561',
 '8939831323',
 '9035456496',
 '9035497784',
 '9066566336',
 '9108287202',
 '9346644740',
 '9599367028',
 '9688196912',
 '9741801141',
 '9845927674',
 '9898361886',
 '9966510499']

In [75]:
df1 = df[~df['customer_mobile'].isin(exclude_list)]

In [76]:
print(df1.shape)
print(df1.customerid.nunique())
print(df1.customer_mobile.nunique())

(15603417, 19)
15603417
15603417

In [77]:
df1[ df1['customerid'].isin(['5cc4631654bc7263ff52a964'])].T

                                                   4
customerid                  5cc4631654bc7263ff52a964
city                                           Delhi
customer_mobile                           6291313175
ao_sessions                                       82
fe_sessions                                       59
rr_sessions                                       14
link_gross_rides                                   2
auto_gross_rides                                  14
cab_gross_rides                                    4
link_net_rides                                     0
net_rides                                          4
cab_net_rides                                      0
gender                                          MALE
taxi_retention_segments                        ELITE
taxi_lifetime_stage                        COMMITTED
taxi_ltr_segment                                 PHH
taxi_service_affinity                        UNKNOWN
taxi_regularity_segment                        DAILY
taxi_fe_regularity_segment                     DAILY

In [78]:
df_stratified_random_sampling = df1.copy()

In [79]:
df_stratified_random_sampling.isnull().sum()

customerid                          0
city                                0
customer_mobile                     0
ao_sessions                         0
fe_sessions                         0
rr_sessions                         0
link_gross_rides                    0
auto_gross_rides                    0
cab_gross_rides                     0
link_net_rides                      0
net_rides                           0
cab_net_rides                       0
gender                        3180938
taxi_retention_segments       3180764
taxi_lifetime_stage           3180764
taxi_ltr_segment              3180764
taxi_service_affinity         3180764
taxi_regularity_segment       3180764
taxi_fe_regularity_segment    3180764
dtype: int64

In [81]:
# Columns to fill null values in
columns_to_fill = ['gender', 'taxi_retention_segments',
                   'taxi_lifetime_stage', 'taxi_ltr_segment', 
                   'taxi_service_affinity', 'taxi_regularity_segment', 'taxi_fe_regularity_segment']

# Fill null values in the specified columns with a specific value (e.g., 0)
df_stratified_random_sampling[columns_to_fill] = df_stratified_random_sampling[columns_to_fill].fillna('NA')

In [82]:
df_stratified_random_sampling.isnull().sum()

customerid                    0
city                          0
customer_mobile               0
ao_sessions                   0
fe_sessions                   0
rr_sessions                   0
link_gross_rides              0
auto_gross_rides              0
cab_gross_rides               0
link_net_rides                0
net_rides                     0
cab_net_rides                 0
gender                        0
taxi_retention_segments       0
taxi_lifetime_stage           0
taxi_ltr_segment              0
taxi_service_affinity         0
taxi_regularity_segment       0
taxi_fe_regularity_segment    0
dtype: int64

In [83]:
df_stratified_random_sampling.info()

<class 'pandas.core.frame.DataFrame'>
Index: 15603417 entries, 0 to 15603621
Data columns (total 19 columns):
 #   Column                      Dtype
---  ------                      -----
 0   customerid                  object
 1   city                        object
 2   customer_mobile             object
 3   ao_sessions                 int64
 4   fe_sessions                 int64
 5   rr_sessions                 int64
 6   link_gross_rides            int64
 7   auto_gross_rides            int64
 8   cab_gross_rides             int64
 9   link_net_rides              int64
 10  net_rides                   int64
 11  cab_net_rides               int64
 12  gender                      object
 13  taxi_retention_segments     object
 14  taxi_lifetime_stage         object
 15  taxi_ltr_segment            object
 16  taxi_service_affinity       object
 17  taxi_regularity_segment     object
 18  taxi_fe_regularity_segment  object
dtypes: int64(9), object(10)
memory usage: 2.3+ GB

## Stratified Random Sampling

In [84]:
df_stratified_random_sampling.shape

(15603417, 19)

In [85]:
df_stratified_random_sampling.customerid.nunique()

15603417

In [86]:
df_stratified_random_sampling.columns

Index(['customerid', 'city', 'customer_mobile', 'ao_sessions', 'fe_sessions',
       'rr_sessions', 'link_gross_rides', 'auto_gross_rides',
       'cab_gross_rides', 'link_net_rides', 'net_rides', 'cab_net_rides',
       'gender', 'taxi_retention_segments', 'taxi_lifetime_stage',
       'taxi_ltr_segment', 'taxi_service_affinity', 'taxi_regularity_segment',
       'taxi_fe_regularity_segment'],
      dtype='object')

In [87]:
stratify_grouper_col =['city', 'ao_sessions', 'fe_sessions',
                       'rr_sessions', 'link_gross_rides', 'auto_gross_rides',
                       'cab_gross_rides', 'link_net_rides', 'net_rides', 'cab_net_rides',
                       'gender', 'taxi_retention_segments', 'taxi_lifetime_stage',
                       'taxi_ltr_segment', 'taxi_service_affinity', 'taxi_regularity_segment',
                       'taxi_fe_regularity_segment'
                      ]

In [92]:
random_seed = 42

# Split the df_stratified_random_sampling into two parts for initial 'control' and 'temp'
df_train_control, df_test = train_test_split(df_stratified_random_sampling, 
                                             test_size=1/2, 
                                             random_state=random_seed
                                             # stratify=df_stratified_random_sampling[stratify_grouper_col]
                                            )

In [93]:

df_train_control = df_train_control.sample(min(500000, len(df_train_control)), random_state=random_seed)
df_test = df_test.sample(min(500000, len(df_test)), random_state=random_seed)

# Assign group labels
df_train_control['group_tc'] = 'control'
df_test['group_tc'] = 'test'

df_final_sample = pd.concat([df_train_control, df_test])

In [94]:
print(df_stratified_random_sampling.shape)
print(df_final_sample.shape)

(15603417, 19)
(1000000, 20)

In [95]:
df_final_sample

,customerid,city,customer_mobile,ao_sessions,fe_sessions,rr_sessions,link_gross_rides,auto_gross_rides,cab_gross_rides,link_net_rides,net_rides,cab_net_rides,gender,taxi_retention_segments,taxi_lifetime_stage,taxi_ltr_segment,taxi_service_affinity,taxi_regularity_segment,taxi_fe_regularity_segment,group_tc
3716388,6705e6eed10b4ab28fd00d85,Delhi,6207413061,39,34,4,5,0,0,3,0,0,MALE,DORMANT,DORMANT,HH,UNKNOWN,UNKNOWN,BI_WEEKLY,control
7344337,5db8ca22c54ee121252b7b72,Hyderabad,6300802372,38,28,4,3,1,0,3,1,0,FEMALE,GOLD,SUSTENANCE,PHH,ONLY_LINK,WEEKLY,WEEKLY,control
853766,646dfe30d87110491d6df3d7,Vijayawada,9966007979,35,25,5,4,1,0,4,1,0,MALE,ELITE,COMMITTED,PHH,UNKNOWN,WEEKLY,WEEKLY,control
6519994,66dc2b682ae68b2390e2ecfb,Pune,9766135494,0,0,0,0,1,0,0,1,0,NA,NA,NA,NA,NA,NA,NA,control
10504843,612f9d6acb05bc1cbf2df219,Hyderabad,8790673944,20,8,2,0,2,0,0,1,0,UNKNOWN,INACTIVE,INACTIVE,HH,UNKNOWN,UNKNOWN,UNKNOWN,control
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5133999,5e5d144001c1d592e3743939,Hyderabad,6301655004,20,20,4,4,0,0,4,0,0,FEMALE,INACTIVE,INACTIVE,PHH,UNKNOWN,RARE_NEED,UNKNOWN,test
5526059,5fbd50c17e483f5ff3fe5af6,Bangalore,8971400959,130,100,17,20,0,0,13,0,0,MALE,DORMANT,DORMANT,PHH,UNKNOWN,MONTHLY,MONTHLY,test
5581249,5f1c0ae9ea5a8b2edc789205,Delhi,9650135370,9,9,2,1,1,1,0,1,0,MALE,SILVER,HOOK,PHH,UNKNOWN,MONTHLY,MONTHLY,test
14654977,629d77f5737cf7f02283e56d,Bangalore,7349771897,0,0,0,0,2,0,0,2,0,NA,NA,NA,NA,NA,NA,NA,test
8754211,64be24d5d949c68d76061874,Bangalore,7483452364,101,80,14,6,4,4,5,4,4,MALE,ELITE,COMMITTED,PHH,NO_AFFINITY,WEEKLY,WEEKLY,test

In [96]:
df_final_sample['customer_mobile'].nunique()

1000000

### Balance Groups

In [97]:
df_final_sample.columns

Index(['customerid', 'city', 'customer_mobile', 'ao_sessions', 'fe_sessions',
       'rr_sessions', 'link_gross_rides', 'auto_gross_rides',
       'cab_gross_rides', 'link_net_rides', 'net_rides', 'cab_net_rides',
       'gender', 'taxi_retention_segments', 'taxi_lifetime_stage',
       'taxi_ltr_segment', 'taxi_service_affinity', 'taxi_regularity_segment',
       'taxi_fe_regularity_segment', 'group_tc'],
      dtype='object')

In [98]:
df_final_sample.head(5)

,customerid,city,customer_mobile,ao_sessions,fe_sessions,rr_sessions,link_gross_rides,auto_gross_rides,cab_gross_rides,link_net_rides,net_rides,cab_net_rides,gender,taxi_retention_segments,taxi_lifetime_stage,taxi_ltr_segment,taxi_service_affinity,taxi_regularity_segment,taxi_fe_regularity_segment,group_tc
3716388,6705e6eed10b4ab28fd00d85,Delhi,6207413061,39,34,4,5,0,0,3,0,0,MALE,DORMANT,DORMANT,HH,UNKNOWN,UNKNOWN,BI_WEEKLY,control
7344337,5db8ca22c54ee121252b7b72,Hyderabad,6300802372,38,28,4,3,1,0,3,1,0,FEMALE,GOLD,SUSTENANCE,PHH,ONLY_LINK,WEEKLY,WEEKLY,control
853766,646dfe30d87110491d6df3d7,Vijayawada,9966007979,35,25,5,4,1,0,4,1,0,MALE,ELITE,COMMITTED,PHH,UNKNOWN,WEEKLY,WEEKLY,control
6519994,66dc2b682ae68b2390e2ecfb,Pune,9766135494,0,0,0,0,1,0,0,1,0,NA,NA,NA,NA,NA,NA,NA,control
10504843,612f9d6acb05bc1cbf2df219,Hyderabad,8790673944,20,8,2,0,2,0,0,1,0,UNKNOWN,INACTIVE,INACTIVE,HH,UNKNOWN,UNKNOWN,UNKNOWN,control

In [100]:
df_final_sample.groupby(['group_tc'])\
.agg(user_base = pd.NamedAgg('customerid', 'nunique'),
     customer_mobile = pd.NamedAgg('customer_mobile', 'nunique'),
     city_distr = pd.NamedAgg(column='city', 
                              aggfunc=lambda x: x.value_counts().to_dict()),
     ao_sessions = pd.NamedAgg('ao_sessions', 'sum'),
     fe_sessions = pd.NamedAgg('fe_sessions', 'sum'),
     rr_sessions = pd.NamedAgg('rr_sessions', 'sum'),
     link_gross_rides = pd.NamedAgg('link_gross_rides', 'sum'),
     auto_gross_rides = pd.NamedAgg('auto_gross_rides', 'sum'),
     cab_gross_rides = pd.NamedAgg('cab_gross_rides', 'sum'),
     link_net_rides = pd.NamedAgg('link_net_rides', 'sum'),
     auto_net_rides = pd.NamedAgg('net_rides', 'sum'),
     cab_net_rides = pd.NamedAgg('cab_net_rides', 'sum'),

     retention_segment_dist = pd.NamedAgg(column='taxi_retention_segments', 
                                        aggfunc=lambda x: x.value_counts().to_dict()), 
     
     lifetime_stage_dist = pd.NamedAgg(column='taxi_lifetime_stage', 
                                        aggfunc=lambda x: x.value_counts().to_dict()), 
     
     ltr_segment_dist = pd.NamedAgg(column='taxi_ltr_segment', 
                                         aggfunc=lambda x: x.value_counts().to_dict()),

     service_affinity_dist = pd.NamedAgg(column='taxi_service_affinity', 
                                         aggfunc=lambda x: x.value_counts().to_dict()),

     regularity_segment_dist = pd.NamedAgg(column='taxi_regularity_segment', 
                                         aggfunc=lambda x: x.value_counts().to_dict()),

     fe_regularity_segment_dist = pd.NamedAgg(column='taxi_fe_regularity_segment', 
                                         aggfunc=lambda x: x.value_counts().to_dict()),
     
     gender_distr = pd.NamedAgg(column='gender', 
                                aggfunc=lambda x: x.value_counts().to_dict()),
        
    ).T

group_tc,control,test
user_base,500000,500000
customer_mobile,500000,500000
city_distr,"{'Hyderabad': 124499, 'Delhi': 109708, 'Bangalore': 91696, 'Chennai': 60773, 'Jaipur': 23084, 'Kolkata': 22697, 'Ahmedabad': 20282, 'Mumbai': 16871, 'Pune': 16542, 'Vijayawada': 13848}","{'Hyderabad': 125522, 'Delhi': 109390, 'Bangalore': 91300, 'Chennai': 60957, 'Jaipur': 22859, 'Kolkata': 22809, 'Ahmedabad': 20004, 'Mumbai': 17144, 'Pune': 16633, 'Vijayawada': 13382}"
ao_sessions,21077871,21089428
fe_sessions,15332761,15319336
rr_sessions,2315338,2314265
link_gross_rides,1116000,1105899
auto_gross_rides,1223260,1225935
cab_gross_rides,476252,478008
link_net_rides,767404,763205
auto_net_rides,808272,811976
cab_net_rides,257745,259713
retention_segment_dist,"{'DORMANT': 111957, 'NA': 102277, 'GOLD': 72237, 'PLATINUM': 66854, 'SILVER': 47877, 'ELITE': 43962, 'INACTIVE': 28241, 'HH': 25293, 'PRIME': 1302}","{'DORMANT': 112406, 'NA': 101887, 'GOLD': 72832, 'PLATINUM': 67182, 'SILVER': 47337, 'ELITE': 43776, 'INACTIVE': 28005, 'HH': 25199, 'PRIME': 1376}"
lifetime_stage_dist,"{'DORMANT': 111957, 'NA': 102277, 'COMMITTED': 82488, 'HOOK': 80946, 'SUSTENANCE': 36567, 'INACTIVE': 28241, 'HANDHOLDING': 25293, 'CHURN_OTB': 19427, 'SOFT_CHURN': 12080, 'DETOX': 724}","{'DORMANT': 112406, 'NA': 101887, 'COMMITTED': 82539, 'HOOK': 81059, 'SUSTENANCE': 36656, 'INACTIVE': 28005, 'HANDHOLDING': 25199, 'CHURN_OTB': 19415, 'SOFT_CHURN': 12090, 'DETOX': 744}"
ltr_segment_dist,"{'PHH': 337446, 'NA': 102277, 'HH': 60277}","{'PHH': 338114, 'NA': 101887, 'HH': 59999}"
service_affinity_dist,"{'UNKNOWN': 244469, 'NA': 102277, 'ONLY_AUTO': 57534, 'ONLY_LINK': 52422, 'NO_AFFINITY': 16438, 'ONLY_CAB': 10187, 'LINK_AUTO': 10077, 'AUTO_CAB': 4885, 'LINK_CAB': 1711}","{'UNKNOWN': 245004, 'NA': 101887, 'ONLY_AUTO': 57702, 'ONLY_LINK': 51897, 'NO_AFFINITY': 16943, 'ONLY_CAB': 10310, 'LINK_AUTO': 9911, 'AUTO_CAB': 4771, 'LINK_CAB': 1575}"
regularity_segment_dist,"{'NA': 102277, 'BI_WEEKLY': 97403, 'WEEKLY': 91238, 'MONTHLY': 65707, 'UNKNOWN': 60277, 'RARE_NEED': 49358, 'DAILY': 33740}","{'NA': 101887, 'BI_WEEKLY': 98186, 'WEEKLY': 91525, 'MONTHLY': 66003, 'UNKNOWN': 59999, 'RARE_NEED': 49017, 'DAILY': 33383}"
fe_regularity_segment_dist,"{'BI_WEEKLY': 119430, 'NA': 102277, 'MONTHLY': 85947, 'WEEKLY': 62084, 'UNKNOWN': 59430, 'DAILY': 40696, 'RARE_NEED': 30136}","{'BI_WEEKLY': 120435, 'NA': 101887, 'MONTHLY': 86012, 'WEEKLY': 62201, 'UNKNOWN': 59130, 'DAILY': 40286, 'RARE_NEED': 30049}"
gender_distr,"{'MALE': 272679, 'FEMALE': 116186, 'NA': 102285, 'UNKNOWN': 7601, 'OTHERS': 1249}","{'MALE': 272748, 'FEMALE': 116531, 'NA': 101890, 'UNKNOWN': 7562, 'OTHERS': 1269}"

In [102]:
df_final_sample.groupby(['city', 'group_tc'])\
.agg(user_base = pd.NamedAgg('customerid', 'nunique'),
     customer_mobile = pd.NamedAgg('customer_mobile', 'nunique'),
     ao_sessions = pd.NamedAgg('ao_sessions', 'sum'),
     fe_sessions = pd.NamedAgg('fe_sessions', 'sum'),
     rr_sessions = pd.NamedAgg('rr_sessions', 'sum'),
     link_gross_rides = pd.NamedAgg('link_gross_rides', 'sum'),
     auto_gross_rides = pd.NamedAgg('auto_gross_rides', 'sum'),
     cab_gross_rides = pd.NamedAgg('cab_gross_rides', 'sum'),
     link_net_rides = pd.NamedAgg('link_net_rides', 'sum'),
     auto_net_rides = pd.NamedAgg('net_rides', 'sum'),
     cab_net_rides = pd.NamedAgg('cab_net_rides', 'sum'),

     retention_segment_dist = pd.NamedAgg(column='taxi_retention_segments', 
                                        aggfunc=lambda x: x.value_counts().to_dict()), 
     
     lifetime_stage_dist = pd.NamedAgg(column='taxi_lifetime_stage', 
                                        aggfunc=lambda x: x.value_counts().to_dict()), 
     
     ltr_segment_dist = pd.NamedAgg(column='taxi_ltr_segment', 
                                         aggfunc=lambda x: x.value_counts().to_dict()),

     service_affinity_dist = pd.NamedAgg(column='taxi_service_affinity', 
                                         aggfunc=lambda x: x.value_counts().to_dict()),

     regularity_segment_dist = pd.NamedAgg(column='taxi_regularity_segment', 
                                         aggfunc=lambda x: x.value_counts().to_dict()),

     fe_regularity_segment_dist = pd.NamedAgg(column='taxi_fe_regularity_segment', 
                                         aggfunc=lambda x: x.value_counts().to_dict()),
     
     gender_distr = pd.NamedAgg(column='gender', 
                                aggfunc=lambda x: x.value_counts().to_dict()),
        
    )

                     user_base  customer_mobile  ao_sessions  fe_sessions  \
city       group_tc
Ahmedabad  control       20282            20282       673320       523458
           test          20004            20004       664349       515314
Bangalore  control       91696            91696      4575974      3369780
           test          91300            91300      4562715      3359770
Chennai    control       60773            60773      2517582      1828664
           test          60957            60957      2531325      1838290
Delhi      control      109708           109708      5480849      3994260
           test         109390           109390      5514524      4007805
Hyderabad  control      124499           124499      5180569      3605479
           test         125522           125522      5223822      3631971
Jaipur     control       23084            23084       830943       617700
           test          22859            22859       800844       595193
Kolkata    control       22697            22697       559187       416803
           test          22809            22809       555520       413864
Mumbai     control       16871            16871       383935       287063
           test          17144            17144       383658       288091
Pune       control       16542            16542       414376       322419
           test          16633            16633       407551       316628
Vijayawada control       13848            13848       461136       367135
           test          13382            13382       445120       352410

                     rr_sessions  link_gross_rides  auto_gross_rides  \
city       group_tc
Ahmedabad  control         82420             49763             33138
           test            81041             47890             34092
Bangalore  control        468431            178021            319239
           test           469004            176573            322257
Chennai    control        274503            131516            165465
           test           276745            131960            168314
Delhi      control        555419            321113            179974
           test           556814            318350            181169
Hyderabad  control        560600            266213            340215
           test           562952            265479            339472
Jaipur     control         91958             47113             48898
           test            88131             44603             45821
Kolkata    control         85595             80045                 0
           test            85237             79644                 0
Mumbai     control         65178                 0             46945
           test            66165                 0             48166
Pune       control         73522                 0             60567
           test            72619                 0             59680
Vijayawada control         57712             42216             28819
           test            55557             41400             26964

                     cab_gross_rides  link_net_rides  auto_net_rides  \
city       group_tc
Ahmedabad  control             21430           30835           21181
           test                20542           30027           21558
Bangalore  control             72677          109675          223580
           test                71956          109024          225573
Chennai    control             31871           90669          123451
           test                31976           90737          125825
Delhi      control            173188          220179           97965
           test               175159          218844           98822
Hyderabad  control             65773          204039          226699
           test                67090          204334          227563
Jaipur     control             20981           30850           25605
           test                21007           29444           24316
Kolkata    control             23452           54103               0
           test                23827           54008               0
Mumbai     control             35285               0           27578
           test                35497               0           28320
Pune       control             30465               0           40659
           test                29725               0           40074
Vijayawada control              1130           27054           21554
           test                 1229           26787           19925

                     cab_net_rides  \
city       group_tc
Ahmedabad  control            9244
           test               9071
Bangalore  control           42777
           test              41885
Chennai    control           19823
           test              19716
Delhi      control           93601
           test              95610
Hyderabad  control           39266
           test              40581
Jaipur     control            8236
           test               8238
Kolkata    control           10980
           test              11039
Mumbai     control           16558
           test              16547
Pune       control           16757
           test              16511
Vijayawada control             503
           test                515

                                                                                                                                             retention_segment_dist  \
city       group_tc
Ahmedabad  control          {'NA': 5525, 'DORMANT': 4568, 'GOLD': 2661, 'PLATINUM': 2006, 'SILVER': 1784, 'HH': 1519, 'ELITE': 1113, 'INACTIVE': 1037, 'PRIME': 69}
           test             {'NA': 5450, 'DORMANT': 4597, 'GOLD': 2571, 'PLATINUM': 1999, 'SILVER': 1719, 'HH': 1403, 'ELITE': 1116, 'INACTIVE': 1083, 'PRIME': 66}
Bangalore  control     {'DORMANT': 19768, 'NA': 16398, 'GOLD': 14323, 'PLATINUM': 13876, 'ELITE': 9547, 'SILVER': 8705, 'INACTIVE': 4583, 'HH': 4296, 'PRIME': 200}
           test        {'DORMANT': 19777, 'NA': 16269, 'GOLD': 14212, 'PLATINUM': 14055, 'ELITE': 9464, 'SILVER': 8611, 'HH': 4350, 'INACTIVE': 4336, 'PRIME': 226}
Chennai    control       {'DORMANT': 14978, 'NA': 10975, 'GOLD': 9065, 'PLATINUM': 8792, 'ELITE': 5763, 'SILVER': 5613, 'INACTIVE': 3072, 'HH': 2366, 'PRIME': 149}
           test          {'DORMANT': 15092, 'NA': 11055, 'GOLD': 9145, 'PLATINUM': 8879, 'ELITE': 5766, 'SILVER': 5541, 'INACTIVE': 2999, 'HH': 2331, 'PRIME': 149}
Delhi      control    {'NA': 25005, 'DORMANT': 23246, 'GOLD': 14309, 'PLATINUM': 13223, 'ELITE': 10533, 'SILVER': 9277, 'HH': 7231, 'INACTIVE': 6494, 'PRIME': 390}
           test       {'NA': 24831, 'DORMANT': 23583, 'GOLD': 14210, 'PLATINUM': 13264, 'ELITE': 10369, 'SILVER': 9141, 'HH': 7235, 'INACTIVE': 6348, 'PRIME': 409}
Hyderabad  control   {'DORMANT': 28694, 'NA': 20666, 'GOLD': 19724, 'PLATINUM': 18648, 'SILVER': 13741, 'ELITE': 10859, 'INACTIVE': 7062, 'HH': 4792, 'PRIME': 313}
           test      {'DORMANT': 28304, 'NA': 20743, 'GOLD': 20551, 'PLATINUM': 18861, 'SILVER': 13751, 'ELITE': 10985, 'INACTIVE': 7157, 'HH': 4826, 'PRIME': 344}
Jaipur     control          {'NA': 5864, 'DORMANT': 5348, 'GOLD': 3067, 'PLATINUM': 2313, 'SILVER': 2311, 'INACTIVE': 1585, 'ELITE': 1305, 'HH': 1247, 'PRIME': 44}
           test             {'NA': 5849, 'DORMANT': 5499, 'GOLD': 2957, 'PLATINUM': 2267, 'SILVER': 2243, 'INACTIVE': 1589, 'ELITE': 1215, 'HH': 1192, 'PRIME': 48}
Kolkata    control          {'NA': 6289, 'DORMANT': 4952, 'GOLD': 2700, 'SILVER': 2234, 'PLATINUM': 2136, 'INACTIVE': 1820, 'HH': 1243, 'ELITE': 1242, 'PRIME': 81}
           test             {'NA': 6293, 'DORMANT': 5024, 'GOLD': 2676, 'SILVER': 2212, 'PLATINUM': 2127, 'INACTIVE': 1877, 'ELITE': 1264, 'HH': 1263, 'PRIME': 73}
Mumbai     control            {'NA': 4981, 'DORMANT': 3507, 'GOLD': 2046, 'PLATINUM': 1669, 'SILVER': 1378, 'INACTIVE': 1226, 'HH': 1104, 'ELITE': 956, 'PRIME': 4}
           test               {'NA': 4868, 'DORMANT': 3704, 'GOLD': 2086, 'PLATINUM': 1693, 'SILVER': 1481, 'INACTIVE': 1231, 'HH': 1133, 'ELITE': 944, 'PRIME': 4}
Pune       control             {'DORMANT': 3769, 'NA': 3614, 'GOLD': 2242, 'PLATINUM': 2197, 'ELITE': 1491, 'SILVER': 1412, 'HH': 916, 'INACTIVE': 896, 'PRIME': 5}
           test                {'DORMANT': 3781, 'NA': 3678, 'GOLD': 2298, 'PLATINUM': 2111, 'ELITE': 1531, 'SILVER': 1412, 'HH': 923, 'INACTIVE': 897, 'PRIME': 2}
Vijayawada control            {'DORMANT': 3127, 'NA': 2960, 'GOLD': 2100, 'PLATINUM': 1994, 'SILVER': 1422, 'ELITE': 1153, 'HH': 579, 'INACTIVE': 466, 'PRIME': 47}
           test               {'DORMANT': 3045, 'NA': 2851, 'GOLD': 2126, 'PLATINUM': 1926, 'SILVER': 1226, 'ELITE': 1122, 'HH': 543, 'INACTIVE': 488, 'PRIME': 55}

                                                                                                                                                                                    lifetime_stage_dist  \
city       group_tc
Ahmedabad  control          {'NA': 5525, 'DORMANT': 4568, 'HOOK': 3005, 'COMMITTED': 2238, 'HANDHOLDING': 1519, 'SUSTENANCE': 1238, 'INACTIVE': 1037, 'CHURN_OTB': 639, 'SOFT_CHURN': 477, 'DETOX': 36}
           test             {'NA': 5450, 'DORMANT': 4597, 'HOOK': 2835, 'COMMITTED': 2293, 'HANDHOLDING': 1403, 'SUSTENANCE': 1191, 'INACTIVE': 1083, 'CHURN_OTB': 612, 'SOFT_CHURN': 504, 'DETOX': 36}
Bangalore  control    {'DORMANT': 19768, 'COMMITTED': 17880, 'NA': 16398, 'HOOK': 14927, 'SUSTENANCE': 7777, 'INACTIVE': 4583, 'HANDHOLDING': 4296, 'CHURN_OTB': 3771, 'SOFT_CHURN': 2250, 'DETOX': 46}
           test       {'DORMANT': 19777, 'COMMITTED': 18021, 'NA': 16269, 'HOOK': 14931, 'SUSTENANCE': 7678, 'HANDHOLDING': 4350, 'INACTIVE': 4336, 'CHURN_OTB': 3716, 'SOFT_CHURN': 2181, 'DETOX': 41}
Chennai    control    {'DORMANT': 14978, 'NA': 10975, 'COMMITTED': 10414, 'HOOK': 10329, 'SUSTENANCE': 4190, 'INACTIVE': 3072, 'CHURN_OTB': 2661, 'HANDHOLDING': 2366, 'SOFT_CHURN': 1729, 'DETOX': 59}
           test       {'DORMANT': 15092, 'NA': 11055, 'COMMITTED': 10444, 'HOOK': 10384, 'SUSTENANCE': 4157, 'INACTIVE': 2999, 'CHURN_OTB': 2742, 'HANDHOLDING': 2331, 'SOFT_CHURN': 1696, 'DETOX': 57}
Delhi      control   {'NA': 25005, 'DORMANT': 23246, 'COMMITTED': 18516, 'HOOK': 15067, 'SUSTENANCE': 7635, 'HANDHOLDING': 7231, 'INACTIVE': 6494, 'CHURN_OTB': 4014, 'SOFT_CHURN': 2225, 'DETOX': 275}
           test      {'NA': 24831, 'DORMANT': 23583, 'COMMITTED': 18394, 'HOOK': 14884, 'SUSTENANCE': 7598, 'HANDHOLDING': 7235, 'INACTIVE': 6348, 'CHURN_OTB': 4041, 'SOFT_CHURN': 2223, 'DETOX': 253}
Hyderabad  control   {'DORMANT': 28694, 'HOOK': 23893, 'COMMITTED': 21279, 'NA': 20666, 'SUSTENANCE': 9369, 'INACTIVE': 7062, 'CHURN_OTB': 5169, 'HANDHOLDING': 4792, 'SOFT_CHURN': 3394, 'DETOX': 181}
           test      {'DORMANT': 28304, 'HOOK': 24551, 'COMMITTED': 21406, 'NA': 20743, 'SUSTENANCE': 9661, 'INACTIVE': 7157, 'CHURN_OTB': 5278, 'HANDHOLDING': 4826, 'SOFT_CHURN': 3377, 'DETOX': 219}
Jaipur     control          {'NA': 5864, 'DORMANT': 5348, 'HOOK': 3458, 'COMMITTED': 2678, 'INACTIVE': 1585, 'SUSTENANCE': 1569, 'HANDHOLDING': 1247, 'CHURN_OTB': 815, 'SOFT_CHURN': 491, 'DETOX': 29}
           test             {'NA': 5849, 'DORMANT': 5499, 'HOOK': 3331, 'COMMITTED': 2521, 'INACTIVE': 1589, 'SUSTENANCE': 1539, 'HANDHOLDING': 1192, 'CHURN_OTB': 779, 'SOFT_CHURN': 527, 'DETOX': 33}
Kolkata    control          {'NA': 6289, 'DORMANT': 4952, 'HOOK': 3252, 'COMMITTED': 2619, 'INACTIVE': 1820, 'SUSTENANCE': 1416, 'HANDHOLDING': 1243, 'CHURN_OTB': 620, 'SOFT_CHURN': 411, 'DETOX': 75}
           test             {'NA': 6293, 'DORMANT': 5024, 'HOOK': 3121, 'COMMITTED': 2620, 'INACTIVE': 1877, 'SUSTENANCE': 1498, 'HANDHOLDING': 1263, 'CHURN_OTB': 596, 'SOFT_CHURN': 431, 'DETOX': 86}
Mumbai     control           {'NA': 4981, 'DORMANT': 3507, 'HOOK': 2021, 'COMMITTED': 2007, 'SUSTENANCE': 1232, 'INACTIVE': 1226, 'HANDHOLDING': 1104, 'CHURN_OTB': 506, 'SOFT_CHURN': 282, 'DETOX': 5}
           test              {'NA': 4868, 'DORMANT': 3704, 'HOOK': 2068, 'COMMITTED': 2011, 'SUSTENANCE': 1303, 'INACTIVE': 1231, 'HANDHOLDING': 1133, 'CHURN_OTB': 492, 'SOFT_CHURN': 332, 'DETOX': 2}
Pune       control             {'DORMANT': 3769, 'NA': 3614, 'COMMITTED': 2651, 'HOOK': 2450, 'SUSTENANCE': 1203, 'HANDHOLDING': 916, 'INACTIVE': 896, 'CHURN_OTB': 640, 'SOFT_CHURN': 396, 'DETOX': 7}
           test                {'DORMANT': 3781, 'NA': 3678, 'COMMITTED': 2636, 'HOOK': 2532, 'SUSTENANCE': 1140, 'HANDHOLDING': 923, 'INACTIVE': 897, 'CHURN_OTB': 621, 'SOFT_CHURN': 424, 'DETOX': 1}
Vijayawada control             {'DORMANT': 3127, 'NA': 2960, 'HOOK': 2544, 'COMMITTED': 2206, 'SUSTENANCE': 938, 'CHURN_OTB': 592, 'HANDHOLDING': 579, 'INACTIVE': 466, 'SOFT_CHURN': 425, 'DETOX': 11}
           test                {'DORMANT': 3045, 'NA': 2851, 'HOOK': 2422, 'COMMITTED': 2193, 'SUSTENANCE': 891, 'HANDHOLDING': 543, 'CHURN_OTB': 538, 'INACTIVE': 488, 'SOFT_CHURN': 395, 'DETOX': 16}

                                             ltr_segment_dist  \
city       group_tc
Ahmedabad  control     {'PHH': 11359, 'NA': 5525, 'HH': 3398}
           test        {'PHH': 11211, 'NA': 5450, 'HH': 3343}
Bangalore  control    {'PHH': 65528, 'NA': 16398, 'HH': 9770}
           test       {'PHH': 65360, 'NA': 16269, 'HH': 9671}
Chennai    control    {'PHH': 43642, 'NA': 10975, 'HH': 6156}
           test       {'PHH': 43911, 'NA': 11055, 'HH': 5991}
Delhi      control   {'PHH': 67722, 'NA': 25005, 'HH': 16981}
           test      {'PHH': 67599, 'NA': 24831, 'HH': 16960}
Hyderabad  control   {'PHH': 92282, 'NA': 20666, 'HH': 11551}
           test      {'PHH': 93195, 'NA': 20743, 'HH': 11584}
Jaipur     control     {'PHH': 14088, 'NA': 5864, 'HH': 3132}
           test        {'PHH': 13913, 'NA': 5849, 'HH': 3097}
Kolkata    control     {'PHH': 13115, 'NA': 6289, 'HH': 3293}
           test        {'PHH': 13188, 'NA': 6293, 'HH': 3328}
Mumbai     control      {'PHH': 9316, 'NA': 4981, 'HH': 2574}
           test         {'PHH': 9605, 'NA': 4868, 'HH': 2671}
Pune       control     {'PHH': 10725, 'NA': 3614, 'HH': 2203}
           test        {'PHH': 10811, 'NA': 3678, 'HH': 2144}
Vijayawada control      {'PHH': 9669, 'NA': 2960, 'HH': 1219}
           test         {'PHH': 9321, 'NA': 2851, 'HH': 1210}

                                                                                                                                                                   service_affinity_dist  \
city       group_tc
Ahmedabad  control          {'UNKNOWN': 10388, 'NA': 5525, 'ONLY_LINK': 1915, 'ONLY_AUTO': 1021, 'NO_AFFINITY': 552, 'ONLY_CAB': 407, 'LINK_AUTO': 255, 'AUTO_CAB': 146, 'LINK_CAB': 73}
           test             {'UNKNOWN': 10212, 'NA': 5450, 'ONLY_LINK': 1929, 'ONLY_AUTO': 1001, 'NO_AFFINITY': 567, 'ONLY_CAB': 418, 'LINK_AUTO': 231, 'AUTO_CAB': 137, 'LINK_CAB': 59}
Bangalore  control   {'UNKNOWN': 42026, 'ONLY_AUTO': 17632, 'NA': 16398, 'ONLY_LINK': 6167, 'NO_AFFINITY': 4290, 'LINK_AUTO': 2351, 'ONLY_CAB': 1456, 'AUTO_CAB': 1248, 'LINK_CAB': 128}
           test      {'UNKNOWN': 41822, 'ONLY_AUTO': 17600, 'NA': 16269, 'ONLY_LINK': 6145, 'NO_AFFINITY': 4312, 'LINK_AUTO': 2406, 'ONLY_CAB': 1368, 'AUTO_CAB': 1253, 'LINK_CAB': 125}
Chennai    control       {'UNKNOWN': 30455, 'NA': 10975, 'ONLY_AUTO': 8940, 'ONLY_LINK': 6220, 'NO_AFFINITY': 1569, 'LINK_AUTO': 1527, 'ONLY_CAB': 558, 'AUTO_CAB': 439, 'LINK_CAB': 90}
           test          {'UNKNOWN': 30448, 'NA': 11055, 'ONLY_AUTO': 9175, 'ONLY_LINK': 6046, 'NO_AFFINITY': 1649, 'LINK_AUTO': 1506, 'ONLY_CAB': 580, 'AUTO_CAB': 434, 'LINK_CAB': 64}
Delhi      control    {'UNKNOWN': 51107, 'NA': 25005, 'ONLY_LINK': 16877, 'ONLY_AUTO': 5178, 'NO_AFFINITY': 4843, 'ONLY_CAB': 3769, 'LINK_AUTO': 1295, 'AUTO_CAB': 914, 'LINK_CAB': 720}
           test       {'UNKNOWN': 51228, 'NA': 24831, 'ONLY_LINK': 16564, 'ONLY_AUTO': 5249, 'NO_AFFINITY': 4955, 'ONLY_CAB': 3754, 'LINK_AUTO': 1243, 'AUTO_CAB': 909, 'LINK_CAB': 657}
Hyderabad  control   {'UNKNOWN': 64673, 'NA': 20666, 'ONLY_AUTO': 16119, 'ONLY_LINK': 13075, 'NO_AFFINITY': 4001, 'LINK_AUTO': 3654, 'ONLY_CAB': 1275, 'AUTO_CAB': 839, 'LINK_CAB': 197}
           test      {'UNKNOWN': 65074, 'NA': 20743, 'ONLY_AUTO': 16236, 'ONLY_LINK': 13287, 'NO_AFFINITY': 4205, 'LINK_AUTO': 3572, 'ONLY_CAB': 1390, 'AUTO_CAB': 841, 'LINK_CAB': 174}
Jaipur     control          {'UNKNOWN': 11746, 'NA': 5864, 'ONLY_LINK': 2400, 'ONLY_AUTO': 1403, 'NO_AFFINITY': 775, 'LINK_AUTO': 458, 'ONLY_CAB': 264, 'AUTO_CAB': 106, 'LINK_CAB': 68}
           test             {'UNKNOWN': 11724, 'NA': 5849, 'ONLY_LINK': 2221, 'ONLY_AUTO': 1282, 'NO_AFFINITY': 832, 'LINK_AUTO': 461, 'ONLY_CAB': 310, 'AUTO_CAB': 115, 'LINK_CAB': 65}
Kolkata    control            {'UNKNOWN': 11230, 'NA': 6289, 'ONLY_LINK': 3714, 'ONLY_CAB': 646, 'LINK_CAB': 423, 'NO_AFFINITY': 188, 'ONLY_AUTO': 148, 'LINK_AUTO': 39, 'AUTO_CAB': 20}
           test               {'UNKNOWN': 11377, 'NA': 6293, 'ONLY_LINK': 3715, 'ONLY_CAB': 637, 'LINK_CAB': 415, 'NO_AFFINITY': 189, 'ONLY_AUTO': 123, 'AUTO_CAB': 31, 'LINK_AUTO': 29}
Mumbai     control               {'UNKNOWN': 7766, 'NA': 4981, 'ONLY_AUTO': 2421, 'ONLY_CAB': 986, 'AUTO_CAB': 468, 'ONLY_LINK': 145, 'NO_AFFINITY': 64, 'LINK_AUTO': 34, 'LINK_CAB': 6}
           test                 {'UNKNOWN': 8182, 'NA': 4868, 'ONLY_AUTO': 2425, 'ONLY_CAB': 1016, 'AUTO_CAB': 444, 'ONLY_LINK': 117, 'NO_AFFINITY': 66, 'LINK_AUTO': 21, 'LINK_CAB': 5}
Pune       control                {'UNKNOWN': 7897, 'NA': 3614, 'ONLY_AUTO': 3435, 'ONLY_CAB': 794, 'AUTO_CAB': 679, 'ONLY_LINK': 73, 'NO_AFFINITY': 28, 'LINK_AUTO': 21, 'LINK_CAB': 1}
           test                   {'UNKNOWN': 7980, 'NA': 3678, 'ONLY_AUTO': 3462, 'ONLY_CAB': 807, 'AUTO_CAB': 594, 'ONLY_LINK': 69, 'NO_AFFINITY': 24, 'LINK_AUTO': 15, 'LINK_CAB': 4}
Vijayawada control              {'UNKNOWN': 7181, 'NA': 2960, 'ONLY_LINK': 1836, 'ONLY_AUTO': 1237, 'LINK_AUTO': 443, 'NO_AFFINITY': 128, 'ONLY_CAB': 32, 'AUTO_CAB': 26, 'LINK_CAB': 5}
           test                 {'UNKNOWN': 6957, 'NA': 2851, 'ONLY_LINK': 1804, 'ONLY_AUTO': 1149, 'LINK_AUTO': 427, 'NO_AFFINITY': 144, 'ONLY_CAB': 30, 'AUTO_CAB': 13, 'LINK_CAB': 7}

                                                                                                                       regularity_segment_dist  \
city       group_tc
Ahmedabad  control          {'NA': 5525, 'BI_WEEKLY': 3653, 'UNKNOWN': 3398, 'MONTHLY': 2598, 'WEEKLY': 2481, 'RARE_NEED': 1708, 'DAILY': 919}
           test             {'NA': 5450, 'BI_WEEKLY': 3463, 'UNKNOWN': 3343, 'WEEKLY': 2522, 'MONTHLY': 2520, 'RARE_NEED': 1813, 'DAILY': 893}
Bangalore  control     {'WEEKLY': 19476, 'BI_WEEKLY': 18702, 'NA': 16398, 'MONTHLY': 11701, 'UNKNOWN': 9770, 'RARE_NEED': 8028, 'DAILY': 7621}
           test        {'WEEKLY': 19716, 'BI_WEEKLY': 18693, 'NA': 16269, 'MONTHLY': 11679, 'UNKNOWN': 9671, 'RARE_NEED': 7822, 'DAILY': 7450}
Chennai    control      {'BI_WEEKLY': 12708, 'WEEKLY': 11975, 'NA': 10975, 'MONTHLY': 8852, 'RARE_NEED': 6377, 'UNKNOWN': 6156, 'DAILY': 3730}
           test         {'BI_WEEKLY': 12740, 'WEEKLY': 12125, 'NA': 11055, 'MONTHLY': 8844, 'RARE_NEED': 6497, 'UNKNOWN': 5991, 'DAILY': 3705}
Delhi      control    {'NA': 25005, 'BI_WEEKLY': 19011, 'WEEKLY': 18293, 'UNKNOWN': 16981, 'MONTHLY': 12037, 'DAILY': 9314, 'RARE_NEED': 9067}
           test       {'NA': 24831, 'BI_WEEKLY': 19206, 'WEEKLY': 18138, 'UNKNOWN': 16960, 'MONTHLY': 12308, 'DAILY': 9135, 'RARE_NEED': 8812}
Hyderabad  control   {'BI_WEEKLY': 26844, 'WEEKLY': 24696, 'NA': 20666, 'MONTHLY': 18935, 'RARE_NEED': 14634, 'UNKNOWN': 11551, 'DAILY': 7173}
           test      {'BI_WEEKLY': 27438, 'WEEKLY': 24980, 'NA': 20743, 'MONTHLY': 18843, 'RARE_NEED': 14661, 'UNKNOWN': 11584, 'DAILY': 7273}
Jaipur     control         {'NA': 5864, 'BI_WEEKLY': 4226, 'WEEKLY': 3232, 'UNKNOWN': 3132, 'MONTHLY': 2999, 'RARE_NEED': 2590, 'DAILY': 1041}

In [103]:
df_final_sample.reset_index(drop=True)

,customerid,city,customer_mobile,ao_sessions,fe_sessions,rr_sessions,link_gross_rides,auto_gross_rides,cab_gross_rides,link_net_rides,net_rides,cab_net_rides,gender,taxi_retention_segments,taxi_lifetime_stage,taxi_ltr_segment,taxi_service_affinity,taxi_regularity_segment,taxi_fe_regularity_segment,group_tc
0,6705e6eed10b4ab28fd00d85,Delhi,6207413061,39,34,4,5,0,0,3,0,0,MALE,DORMANT,DORMANT,HH,UNKNOWN,UNKNOWN,BI_WEEKLY,control
1,5db8ca22c54ee121252b7b72,Hyderabad,6300802372,38,28,4,3,1,0,3,1,0,FEMALE,GOLD,SUSTENANCE,PHH,ONLY_LINK,WEEKLY,WEEKLY,control
2,646dfe30d87110491d6df3d7,Vijayawada,9966007979,35,25,5,4,1,0,4,1,0,MALE,ELITE,COMMITTED,PHH,UNKNOWN,WEEKLY,WEEKLY,control
3,66dc2b682ae68b2390e2ecfb,Pune,9766135494,0,0,0,0,1,0,0,1,0,NA,NA,NA,NA,NA,NA,NA,control
4,612f9d6acb05bc1cbf2df219,Hyderabad,8790673944,20,8,2,0,2,0,0,1,0,UNKNOWN,INACTIVE,INACTIVE,HH,UNKNOWN,UNKNOWN,UNKNOWN,control
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,5e5d144001c1d592e3743939,Hyderabad,6301655004,20,20,4,4,0,0,4,0,0,FEMALE,INACTIVE,INACTIVE,PHH,UNKNOWN,RARE_NEED,UNKNOWN,test
999996,5fbd50c17e483f5ff3fe5af6,Bangalore,8971400959,130,100,17,20,0,0,13,0,0,MALE,DORMANT,DORMANT,PHH,UNKNOWN,MONTHLY,MONTHLY,test
999997,5f1c0ae9ea5a8b2edc789205,Delhi,9650135370,9,9,2,1,1,1,0,1,0,MALE,SILVER,HOOK,PHH,UNKNOWN,MONTHLY,MONTHLY,test
999998,629d77f5737cf7f02283e56d,Bangalore,7349771897,0,0,0,0,2,0,0,2,0,NA,NA,NA,NA,NA,NA,NA,test
999999,64be24d5d949c68d76061874,Bangalore,7483452364,101,80,14,6,4,4,5,4,4,MALE,ELITE,COMMITTED,PHH,NO_AFFINITY,WEEKLY,WEEKLY,test

In [104]:
##Local extract
df_final_sample.to_csv(local_datasets + 'processed/data.csv', index=False)
# df_final_sample = pd.read_csv(local_datasets + 'processed/data.csv')

In [106]:
# Check for common values in 'user_id' among the three DataFrames
common_values_df1_df2 = df_train_control[df_train_control['customerid'].isin(df_test['customerid'])]['customerid'].tolist()
common_values_df1_df2

[]

In [108]:
print(df_train_control.shape)
print(df_test.shape)

print(df_train_control.customerid.nunique())
print(df_test.customerid.nunique())

(500000, 20)
(500000, 20)
500000
500000

In [109]:
df_train_control[df_train_control['customerid'].isin(df_test['customerid'])]

Empty DataFrame
Columns: [customerid, city, customer_mobile, ao_sessions, fe_sessions, rr_sessions, link_gross_rides, auto_gross_rides, cab_gross_rides, link_net_rides, net_rides, cab_net_rides, gender, taxi_retention_segments, taxi_lifetime_stage, taxi_ltr_segment, taxi_service_affinity, taxi_regularity_segment, taxi_fe_regularity_segment, group_tc]
Index: []

In [110]:
df_test[df_test['customerid'].isin(df_train_control['customerid'])]

Empty DataFrame
Columns: [customerid, city, customer_mobile, ao_sessions, fe_sessions, rr_sessions, link_gross_rides, auto_gross_rides, cab_gross_rides, link_net_rides, net_rides, cab_net_rides, gender, taxi_retention_segments, taxi_lifetime_stage, taxi_ltr_segment, taxi_service_affinity, taxi_regularity_segment, taxi_fe_regularity_segment, group_tc]
Index: []

## User Selector for Experiment

In [111]:
df_train_control.reset_index(drop=True)

,customerid,city,customer_mobile,ao_sessions,fe_sessions,rr_sessions,link_gross_rides,auto_gross_rides,cab_gross_rides,link_net_rides,net_rides,cab_net_rides,gender,taxi_retention_segments,taxi_lifetime_stage,taxi_ltr_segment,taxi_service_affinity,taxi_regularity_segment,taxi_fe_regularity_segment,group_tc
0,6705e6eed10b4ab28fd00d85,Delhi,6207413061,39,34,4,5,0,0,3,0,0,MALE,DORMANT,DORMANT,HH,UNKNOWN,UNKNOWN,BI_WEEKLY,control
1,5db8ca22c54ee121252b7b72,Hyderabad,6300802372,38,28,4,3,1,0,3,1,0,FEMALE,GOLD,SUSTENANCE,PHH,ONLY_LINK,WEEKLY,WEEKLY,control
2,646dfe30d87110491d6df3d7,Vijayawada,9966007979,35,25,5,4,1,0,4,1,0,MALE,ELITE,COMMITTED,PHH,UNKNOWN,WEEKLY,WEEKLY,control
3,66dc2b682ae68b2390e2ecfb,Pune,9766135494,0,0,0,0,1,0,0,1,0,NA,NA,NA,NA,NA,NA,NA,control
4,612f9d6acb05bc1cbf2df219,Hyderabad,8790673944,20,8,2,0,2,0,0,1,0,UNKNOWN,INACTIVE,INACTIVE,HH,UNKNOWN,UNKNOWN,UNKNOWN,control
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499995,665490e11c9f5b372e1147a8,Delhi,8368323637,5,14,1,0,2,0,0,0,0,MALE,GOLD,SUSTENANCE,PHH,ONLY_LINK,WEEKLY,BI_WEEKLY,control
499996,670a124a476051ece53b630c,Delhi,7703971722,15,15,2,0,1,2,0,0,1,FEMALE,HH,HANDHOLDING,HH,UNKNOWN,UNKNOWN,RARE_NEED,control
499997,5d0d05cac2a56b449f9e3310,Hyderabad,7879115445,36,37,2,0,1,1,0,1,0,MALE,DORMANT,DORMANT,PHH,UNKNOWN,MONTHLY,MONTHLY,control
499998,6531ded739ce6b6f2da382c6,Chennai,9043331433,4,4,1,2,0,0,0,0,0,MALE,GOLD,SUSTENANCE,PHH,UNKNOWN,BI_WEEKLY,BI_WEEKLY,control
499999,65ae5a6a749337352a2649a6,Mumbai,8369018935,40,21,6,0,7,0,0,7,0,MALE,DORMANT,DORMANT,HH,UNKNOWN,UNKNOWN,RARE_NEED,control

In [112]:
df_test.reset_index(drop=True)

,customerid,city,customer_mobile,ao_sessions,fe_sessions,rr_sessions,link_gross_rides,auto_gross_rides,cab_gross_rides,link_net_rides,net_rides,cab_net_rides,gender,taxi_retention_segments,taxi_lifetime_stage,taxi_ltr_segment,taxi_service_affinity,taxi_regularity_segment,taxi_fe_regularity_segment,group_tc
0,65f01b8502500313d302a12a,Delhi,8348821149,15,11,2,0,3,0,0,1,0,NA,NA,NA,NA,NA,NA,NA,test
1,66de724ef76fe845d6d4f48a,Delhi,9453522807,21,21,2,1,1,0,1,0,0,MALE,SILVER,HOOK,PHH,ONLY_CAB,RARE_NEED,RARE_NEED,test
2,60af1d42c41d740c796fff8f,Hyderabad,9032559753,18,17,2,2,0,0,2,0,0,MALE,GOLD,HOOK,PHH,UNKNOWN,BI_WEEKLY,WEEKLY,test
3,6448b2f786dd2131d33ac350,Hyderabad,8073509872,17,17,3,2,2,0,2,1,0,MALE,GOLD,CHURN_OTB,PHH,ONLY_AUTO,WEEKLY,BI_WEEKLY,test
4,5e103962a10a71228f8d2d5e,Jaipur,7024843628,45,36,8,8,0,1,4,0,0,MALE,DORMANT,DORMANT,PHH,UNKNOWN,RARE_NEED,UNKNOWN,test
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499995,5e5d144001c1d592e3743939,Hyderabad,6301655004,20,20,4,4,0,0,4,0,0,FEMALE,INACTIVE,INACTIVE,PHH,UNKNOWN,RARE_NEED,UNKNOWN,test
499996,5fbd50c17e483f5ff3fe5af6,Bangalore,8971400959,130,100,17,20,0,0,13,0,0,MALE,DORMANT,DORMANT,PHH,UNKNOWN,MONTHLY,MONTHLY,test
499997,5f1c0ae9ea5a8b2edc789205,Delhi,9650135370,9,9,2,1,1,1,0,1,0,MALE,SILVER,HOOK,PHH,UNKNOWN,MONTHLY,MONTHLY,test
499998,629d77f5737cf7f02283e56d,Bangalore,7349771897,0,0,0,0,2,0,0,2,0,NA,NA,NA,NA,NA,NA,NA,test
499999,64be24d5d949c68d76061874,Bangalore,7483452364,101,80,14,6,4,4,5,4,4,MALE,ELITE,COMMITTED,PHH,NO_AFFINITY,WEEKLY,WEEKLY,test

In [115]:
df_train_control['customer_mobile'] = df_train_control['customer_mobile'].astype(float).astype(int)

In [116]:
df_test['customer_mobile'] = df_test['customer_mobile'].astype(float).astype(int)

In [117]:
df_train_control['customer_mobile']

3716388     6207413061
7344337     6300802372
853766      9966007979
6519994     9766135494
10504843    8790673944
               ...
6123665     8368323637
4585547     7703971722
4865414     7879115445
5505476     9043331433
9640581     8369018935
Name: customer_mobile, Length: 500000, dtype: int64

In [118]:
df_test['customer_mobile']

8735817     8348821149
2585278     9453522807
6623667     9032559753
10225742    8073509872
9757232     7024843628
               ...
5133999     6301655004
5526059     8971400959
5581249     9650135370
14654977    7349771897
8754211     7483452364
Name: customer_mobile, Length: 500000, dtype: int64

In [121]:
def split_fn(df, type):

    chunks = np.array_split(df, 5)

    folder = type
    for i, chunk in enumerate(chunks):
        chunk.to_csv(f'/Users/E2074/local-datasets/customer/ads-monetisation/jackport/processed/{folder}_user_selector_{i + 1}.csv', 
                     header=False,
                     index=False
                    )
    
    return print('done')

In [122]:
split_fn(df_train_control[['customer_mobile']], 'control')

done

In [123]:
split_fn(df_test[['customer_mobile']], 'test')

done

In [124]:
df_train_control[['customer_mobile']]

          customer_mobile
3716388        6207413061
7344337        6300802372
853766         9966007979
6519994        9766135494
10504843       8790673944
...                   ...
6123665        8368323637
4585547        7703971722
4865414        7879115445
5505476        9043331433
9640581        8369018935

[500000 rows x 1 columns]

In [125]:
df_test[['customer_mobile']]

          customer_mobile
8735817        8348821149
2585278        9453522807
6623667        9032559753
10225742       8073509872
9757232        7024843628
...                   ...
5133999        6301655004
5526059        8971400959
5581249        9650135370
14654977       7349771897
8754211        7483452364

[500000 rows x 1 columns]

In [ ]:
# Current - 5L vs 5L (mix of 10 cities)

In [ ]:
# Current - 5L vs 5L (mix of 10 cities)