In [27]:
import os
import pandas as pd, math
import numpy as np
from pyhive import presto
from datetime import datetime, date, timedelta
import warnings

# Ignore a specific warning by its type
warnings.filterwarnings("ignore")

pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)

presto_port = '80'
# username = 'airflow-user'
username = 'jatin.rajani1@rapido.bike'

connection1 = presto.connect('bi-presto.serving.data.production.internal', presto_port, username)
connection2 = presto.connect('bi-trino-2.serving.data.production.internal', presto_port, username)
connection3= presto.connect('processing-2.processing.data.production.internal',presto_port,username)
connection4= presto.connect('processing.processing.data.production.internal',presto_port,username)

In [63]:
## For Blr Exp Please Use First Query

In [62]:


city_name = 'Bangalore'
start_date='2024-04-23'
end_date='2024-05-06'
# service_name='CabEconomy'

In [52]:
def route_check_func(city_name,start_date,end_date,service_name):
    route_check=f"""WITH service_mapping AS ( 
            SELECT 
                service_detail_id,
                service_level as service_name,
                service_category,
                service_id,
                city_display_name as city,
                city_id
            FROM 
                datasets.service_mapping
            WHERE 
                city_display_name='{city_name}'
                and service_level='{service_name}'
        ),
        
        fe_tbl as (
                SELECT
                    fare_estimate_id fid,
                    api_context,final_amount as final_amount_fare,
                    date_format(from_unixtime(epoch / 1000, 'Asia/Kolkata'), '%Y-%m-%d') AS order_date,
                    cast(final_amount AS double) AS fe_amount,service_detail_id as service_id_fare,
                    epoch fe,ride_distance as d1, estimated_ride_time as t1
                FROM
                    pricing.fare_estimates_enriched 
                WHERE 
                yyyymmdd BETWEEN DATE_FORMAT(date('{start_date}'),'%Y%m%d') 
                AND DATE_FORMAT(date('{end_date}'),'%Y%m%d') 
                   
        ),
        orderlogs as 
        (SELECT *,u.id_array as fare_estimate_id
        FROM 
        ( SELECT order_id, (amount-prev_due) as order_amount,customer_id,captain_id,
                 date_format(from_unixtime(epoch / 1000, 'Asia/Kolkata'), '%Y-%m-%d') AS orderdate,
                 epoch,estimate_id,estimate_ids,ride_time as t3,
                 fare_recalculated_reason, all_paths,
                 spd_fraud_flag,order_status,
                 service_obj_service_name as service_name,
                 fare_recalculated_diff_amount AS fe_re_diff_amount,service_detail_id,
                 cast(json_parse(estimate_ids) as array<varchar>) AS id_array
          FROM orders.order_logs_snapshot
               WHERE 
                yyyymmdd BETWEEN DATE_FORMAT(date('{start_date}'),'%Y%m%d') 
                AND DATE_FORMAT(date('{end_date}'),'%Y%m%d') 
                AND city_name IN (SELECT city FROM service_mapping)
                AND service_obj_service_name IN (SELECT service_name FROM service_mapping)) as t
        CROSS JOIN UNNEST(t.id_array) AS u(id_array)),
        immutable AS (
            SELECT 
                DATE_FORMAT(DATE_PARSE(yyyymmdd, '%Y%m%d'), '%Y-%m-%d') orderdate,
                order_id,
                cast (event_time as double) event_time
            FROM 
                orders.order_logs_immutable 
               WHERE 
                yyyymmdd BETWEEN DATE_FORMAT(date('{start_date}'),'%Y%m%d') 
                AND DATE_FORMAT(date('{end_date}'),'%Y%m%d') 
                AND event_type = 'started'
                AND city_name IN (SELECT city FROM service_mapping)
                AND service_obj_service_name IN (SELECT service_name FROM service_mapping)
        ),
        
        nav_metrics AS (
            SELECT 
                event_props_order_id,
                case when device_info_app_version>='5.3.22' then 'Above 5.3.22' else 'Below 5.3.22' end as app_version_type,
                case when device_info_app_version>='5.3.24' then 'Above 5.3.24' else 'Below 5.3.24' end as app_optimal_version_type,
                cast  (event_props_epoch as double) event_props_epoch,
                DATE_FORMAT(DATE_PARSE(yyyymmdd, '%Y%m%d'), '%Y-%m-%d') orderdate,
                try(cast(event_props_distance_in_meters as double) )/ 1000 d2
            FROM
                clevertap.captain_inappnavmetrics_immutable
                 WHERE 
                yyyymmdd BETWEEN DATE_FORMAT(date('{start_date}'),'%Y%m%d') 
                AND DATE_FORMAT(date('{end_date}'),'%Y%m%d') 
                AND event_props_order_status = 'started'
        ),
        
        distance2 AS (
            SELECT 
                orderdate,
                order_id,
                app_version_type,
                app_optimal_version_type,
                d2
            FROM 
                ( 
                select 
                    imu.orderdate,
                    imu.order_id,
                    app_version_type,
                     app_optimal_version_type,
                    date_diff('minute', from_unixtime(event_time/1000), from_unixtime(event_props_epoch/1000)) AS minDiff,
                    "d2"
                from 
                    immutable imu 
                join 
                    nav_metrics nav 
                    ON imu.order_id = nav.event_props_order_id
                )
                --and event_props_epoch >= event_time )
            WHERE abs(minDiff) <= 1
        ),
        done as  (select 
                   distinct order_id,d1,t1,t3,epoch,fare_recalculated_reason,service_name,rn,api_context, (fe_amount-order_amount) as amt_diff, all_paths,fid,
                spd_fraud_flag,order_status,orderdate
               
                   from 
                  (SELECT *,row_number () over(partition by order_id order by fe) rn from 
                  (SELECT  *
                   from orderlogs join fe_tbl
                   on fare_estimate_id = fid 
                   and service_detail_id = service_id_fare)
                   )
                   where rn =1
         ),
        dthree as (select distinct order_id, CASE
                WHEN selectedroute = 'hFRoute' THEN hfdistance
                WHEN selectedroute = 'actualRoute' THEN directionsresponsedistance
                WHEN selectedroute = 'estimatedRoute' THEN final_estimated_directions_response_distance
                ELSE NULL -- Handle other cases if needed
            END AS d3, selectedroute
            from
        (select * from (
        select *, row_number () over(partition by order_id order by updatedAt) rn from (
         select yyyymmdd,orderid as order_id, cast(hfdistance as double)*1000 as hfdistance,cast(pingdensity as double)*100 as pingdensity,cast(directionsresponsedistance as double) as directionsresponsedistance,
                     cast(final_estimated_directions_response_distance as double) as final_estimated_directions_response_distance,selectedroute,updatedAt
                     from raw.captain_distance_response
                        WHERE 
                yyyymmdd BETWEEN DATE_FORMAT(date('{start_date}'),'%Y%m%d') 
                AND DATE_FORMAT(date('{end_date}'),'%Y%m%d') 
                       
                    ))
                    where rn = 1
                     )),
                     
        merged_tbl as
        (
        
        
            select done.order_id,d2,done.orderdate,d3,d1,app_version_type,app_optimal_version_type,
            fare_recalculated_reason,spd_fraud_flag,order_status,service_name,
            CASE
                WHEN d2 IS NOT NULL then d1-d2
                END AS fe_vs_nav,
                d1-(d3*1.00/1000.00) as Est_Nav,
                case WHEN d2 IS NOT NULL then d2-(d3*1.00/1000.00)
                END AS nav_actual
            from done
            left join dthree
            on done.order_id=dthree.order_id
            left join distance2
            on done.order_id=distance2.order_id
        )
        
        
        select service_name,
        orderdate,
        CASE WHEN orderdate >= ('2024-04-23') and (orderdate<='2024-04-28') then 'pre' 
        when orderdate>=('2024-05-03') THEN 'post' end as new_date_type,
        app_version_type,
        count(distinct order_id) as gross_orders,
        count(distinct case when order_status='dropped' and spd_fraud_flag!=True then order_id end) as net_orders,
        (count(distinct case when order_status='dropped' and spd_fraud_flag!=True then order_id end)*100.00)/(count (distinct order_id)) as "G2N",
        count(distinct case when order_status='dropped' and spd_fraud_flag!=True and fare_recalculated_reason='routeDiff' then order_id end) as route_diff_orders,
        (count(distinct case when order_status='dropped' and spd_fraud_flag!=True and fe_vs_nav_bucket='a. Within_500_m' then order_id end)*100.00)/(count( distinct order_id)) as fe_nav_bucket_within_500m_percent,
        (count(distinct case when order_status='dropped' and spd_fraud_flag!=True and nav_actual_bucket='a. Within_500_m' then order_id end)*100.00)/(count( distinct order_id)) as nav_actual_bucket_within_500m_percent,
        
        
        
        count(distinct case when order_status='dropped' and spd_fraud_flag!=True and fe_vs_nav_bucket='a. Within_500_m' then order_id end) as fe_nav_bucket_within_500m,
        count(distinct case when order_status='dropped' and spd_fraud_flag!=True and fe_vs_nav_bucket='b. Less_than_500m' then order_id end) as fe_nav_bucket_less_500m,
        count(distinct case when order_status='dropped' and spd_fraud_flag!=True and fe_vs_nav_bucket='c. Greater_than_500m' then order_id end) as fe_nav_bucket_grt_500m,
        
        count(distinct case when order_status='dropped' and spd_fraud_flag!=True and nav_actual_bucket='a. Within_500_m' then order_id end) as nav_actual_bucket_within_500m,
        count(distinct case when order_status='dropped' and spd_fraud_flag!=True and nav_actual_bucket='b. Less_than_500m' then order_id end) as nav_actual_bucket_less_500m,
        count(distinct case when order_status='dropped' and spd_fraud_flag!=True and nav_actual_bucket='c. Greater_than_500m' then order_id end) as nav_actual_bucket_grt_500m,
        
        count(distinct case when order_status='dropped' and spd_fraud_flag!=True and Est_Nav_bucket='a. Within_500_m' then order_id end) as Est_Nav_bucket_within_500m,
        count(distinct case when order_status='dropped' and spd_fraud_flag!=True and Est_Nav_bucket='b. Less_than_500m' then order_id end) as Est_Nav_bucket_less_500m,
        count(distinct case when order_status='dropped' and spd_fraud_flag!=True and Est_Nav_bucket='c. Greater_than_500m' then order_id end) as Est_Nav_bucket_grt_500m
        
        
        
        from(
                select *,case when d2 is not NULL and fe_vs_nav>=-0.5 and fe_vs_nav<=0.5 then 'a. Within_500_m'
                when d2 is not NULL and fe_vs_nav<-0.5 then 'b. Less_than_500m'
                when d2 is not NULL and fe_vs_nav>0.5 then 'c. Greater_than_500m' end as fe_vs_nav_bucket,
                case when  d2 is not NULL and nav_actual>=-0.5 and nav_actual<=0.5 then 'a. Within_500_m'
                when d2 is not NULL and nav_actual<-0.5 then 'b. Less_than_500m'
                when d2 is not NULL and nav_actual>0.5 then 'c. Greater_than_500m' end as nav_actual_bucket,
                case when Est_Nav>=-0.5 and Est_Nav<=0.5 then 'a. Within_500_m'
                when Est_Nav<-0.5 then 'b. Less_than_500m'
                when Est_Nav>0.5 then 'c. Greater_than_500m' end as Est_Nav_bucket
                from merged_tbl
                group by 1,2,3,4,5,6,7,8,9,10,11,12,13,14
        )
        group by 1,2,3,4
        order by 2
"""
    route_check_df=pd.read_sql(route_check,connection4)
    return route_check_df

In [53]:
total_df_d1_d2=pd.DataFrame()
city_name=['Bangalore','Delhi','Hyderabad','Chennai','Jaipur']
service_level=['Link','Auto','CabEconomy']
for i in city_name[0:1]:
    print(i)
    for j in service_level[1:]:
        print(j)
        df=route_check_func(i,start_date,end_date,j)
        # df['distance_type']='second_longest'
        df['fe_nav_bucket_within_500m_percent']=(df['fe_nav_bucket_within_500m']*100.00)/df['net_orders']
        df['nav_actual_bucket_within_500m_percent']=(df['nav_actual_bucket_within_500m']*100.00)/df['net_orders']
        df['route_diff_percent']=(df['route_diff_orders']*100.00)/df['net_orders']
        total_df_d1_d2=pd.concat([total_df_d1_d2,df])

Bangalore
Auto
CabEconomy

In [47]:
total_df_d1_d2

,service_name,orderdate,new_date_type,app_optimal_version_type,gross_orders,net_orders,G2N,route_diff_orders,fe_nav_bucket_within_500m_percent,nav_actual_bucket_within_500m_percent,fe_nav_bucket_within_500m,fe_nav_bucket_less_500m,fe_nav_bucket_grt_500m,nav_actual_bucket_within_500m,nav_actual_bucket_less_500m,nav_actual_bucket_grt_500m,Est_Nav_bucket_within_500m,Est_Nav_bucket_less_500m,Est_Nav_bucket_grt_500m,route_diff_percent,Est_Nav_bucket_less_500m_percent,Est_Nav_bucket_grt_500m_percent
0,Auto,2024-04-23,pre,Above 5.3.24,411,410,99.76,101,89.024390,70.000000,365,27,73,287,79,98,295,33,82,24.634146,8.048780,20.000000
1,Auto,2024-04-23,pre,None,199897,3476,1.74,808,0.000000,0.000000,0,0,0,0,0,0,2546,251,679,23.245109,7.220944,19.533947
2,Auto,2024-04-23,pre,Below 5.3.24,135169,134752,99.69,32173,87.851757,73.322103,118382,10344,15033,98803,16261,28770,97906,10864,25974,23.875712,8.062218,19.275410
3,Auto,2024-04-24,pre,Below 5.3.24,138796,138372,99.69,29185,88.099471,76.170034,121905,11130,14301,105398,18477,23435,105015,13421,19920,21.091695,9.699217,14.395976
4,Auto,2024-04-24,pre,None,200184,3361,1.68,687,0.000000,0.000000,0,0,0,0,0,0,2570,302,489,20.440345,8.985421,14.549241
5,Auto,2024-04-24,pre,Above 5.3.24,445,442,99.33,77,88.461538,79.864253,391,31,69,353,72,69,353,33,56,17.420814,7.466063,12.669683
6,Auto,2024-04-25,pre,None,264669,3410,1.29,730,0.000000,0.000000,0,0,0,0,0,0,2574,316,520,21.407625,9.266862,15.249267
7,Auto,2024-04-25,pre,Below 5.3.24,152637,152172,99.70,32354,87.648188,75.661094,133376,12985,16239,115135,20008,27484,115135,14143,22880,21.261467,9.294088,15.035618
8,Auto,2024-04-25,pre,Above 5.3.24,447,443,99.11,88,90.519187,78.329571,401,23,68,347,72,69,346,32,65,19.864560,7.223476,14.672686
9,Auto,2024-04-26,pre,Below 5.3.24,112088,111744,99.69,23359,88.676797,76.257338,99091,9076,9685,85213,13360,19271,85768,10433,15537,20.904031,9.336519,13.904102
10,Auto,2024-04-26,pre,Above 5.3.24,284,284,100.00,65,86.619718,77.464789,246,27,38,220,50,43,217,29,38,22.887324,10.211268,13.380282
11,Auto,2024-04-26,pre,None,152644,2607,1.71,536,0.000000,0.000000,0,0,0,0,0,0,2006,236,365,20.560031,9.052551,14.000767
12,Auto,2024-04-27,pre,Above 5.3.24,400,397,99.25,86,89.168766,77.581864,354,28,54,308,56,68,305,31,61,21.662469,7.808564,15.365239
13,Auto,2024-04-27,pre,None,147972,2990,2.02,631,0.000000,0.000000,0,0,0,0,0,0,2303,258,429,21.103679,8.628763,14.347826
14,Auto,2024-04-27,pre,Below 5.3.24,138619,138199,99.70,28264,88.831323,76.967995,122764,10792,11158,106369,15503,22855,106648,12732,18812,20.451668,9.212802,13.612255
15,Auto,2024-04-28,pre,Above 5.3.24,343,338,98.54,74,86.982249,72.485207,294,34,43,245,57,75,261,28,49,21.893491,8.284024,14.497041
16,Auto,2024-04-28,pre,Below 5.3.24,126688,126247,99.65,26866,88.162095,76.364587,111302,10769,8870,96408,13135,21430,96478,12250,17509,21.280506,9.703201,13.868844
17,Auto,2024-04-28,pre,None,136733,2928,2.14,595,0.000000,0.000000,0,0,0,0,0,0,2259,286,383,20.321038,9.767760,13.080601
18,Auto,2024-04-29,None,Above 5.3.24,378,376,99.47,76,88.297872,73.404255,332,29,60,276,69,75,287,32,57,20.212766,8.510638,15.159574
19,Auto,2024-04-29,None,None,183791,3460,1.88,616,0.000000,0.000000,0,0,0,0,0,0,2747,291,422,17.803468,8.410405,12.196532
20,Auto,2024-04-29,None,Below 5.3.24,143577,143140,99.70,27560,89.144194,77.264217,127601,11863,8524,110596,13441,24095,111833,12709,18584,19.253877,8.878720,12.983093
21,Auto,2024-04-30,None,None,193662,3331,1.72,622,0.000000,0.000000,0,0,0,0,0,0,2611,315,405,18.673071,9.456620,12.158511
22,Auto,2024-04-30,None,Above 5.3.24,367,365,99.46,72,89.315068,78.356164,326,26,49,286,57,64,278,35,52,19.726027,9.589041,14.246575
23,Auto,2024-04-30,None,Below 5.3.24,141265,140854,99.71,27029,89.455039,77.429111,126001,12167,7345,109062,12946,23643,109794,13028,18016,19.189373,9.249294,12.790549
24,Auto,2024-05-01,None,Below 5.3.24,134153,133556,99.55,26641,89.146875,77.727695,119061,12143,6449,103810,11651,22319,104114,12478,16957,19.947438,9.342897,12.696547
25,Auto,2024-05-01,None,None,130108,2964,2.28,546,0.000000,0.000000,0,0,0,0,0,0,2337,275,352,18.421053,9.278003,11.875843
26,Auto,2024-05-01,None,Above 5.3.24,602,599,99.50,122,87.312187,75.459098,523,63,54,452,68,122,464,50,84,20.367279,8.347245,14.023372
27,Auto,2024-05-02,None,Above 5.3.24,945,943,99.79,185,89.077413,76.352068,840,77,85,720,101,176,733,72,138,19.618240,7.635207,14.634146
28,Auto,2024-05-02,None,None,259054,3527,1.36,688,0.000000,0.000000,0,0,0,0,0,0,2722,314,490,19.506663,8.902750,13.892827
29,Auto,2024-05-02,None,Below 5.3.24,148323,147834,99.67,30002,88.926093,76.853768,131463,12186,9259,113616,12978,26457,113398,12509,21902,20.294384,8.461518,14.815266
30,Auto,2024-05-03,None,Below 5.3.24,148616,148106,99.66,30238,91.873388,77.067776,136070,9271,7420,114142,11340,27292,113017,10570,24392,20.416458,7.136780,16.469286
31,Auto,2024-05-03,None,Above 5.3.24,928,927,99.89,197,89.967638,78.856526,834,49,99,731,83,168,710,41,174,21.251348,4.422869,18.770227
32,Auto,2024-05-03,None,None,199338,3623,1.82,745,0.000000,0.000000,0,0,0,0,0,0,2747,254,619,20.563069,7.010765,17.085288
33,Auto,2024-05-04,post,None,180632,3615,2.00,749,0.000000,0.000000,0,0,0,0,0,0,2775,247,592,20.719225,6.832642,16.376210
34,Auto,2024-05-04,post,Below 5.3.24,153354,152827,99.66,31860,91.926819,77.293279,140489,9586,7882,118125,12352,27572,116654,11535,24614,20.847102,7.547750,16.105793
35,Auto,2024-05-04,post,Above 5.3.24,1093,1091,99.82,210,89.275894,77.726856,974,71,108,848,108,189,848,63,180,19.248396,5.774519,16.498625
36,Auto,2024-05-05,post,Above 5.3.24,800,800,100.00,160,88.375000,76.250000,707,52,83,610,89,154,617,60,122,20.000000,7.500000,15.250000
37,Auto,2024-05-05,post,None,164202,3034,1.85,676,0.000000,0.000000,0,0,0,0,0,0,2284,229,521,22.280817,7.547792,17.172050
38,Auto,2024-05-05,post,Below 5.3.24,133862,133398,99.65,27982,92.032114,77.597865,122769,8091,6243,103514,10037,23642,102126,9880,21373,20.976326,7.406408,16.021979
39,Auto,2024-05-06,post,Below 5.3.24,147799,147255,99.63,30269,91.716410,76.895182,135057,9305,7522,113232,11551,26562,111781,10991,23915,20.555499,7.463923,16.240535
40,Auto,2024-05-06,post,Above 5.3.24,6855,6828,99.61,1403,92.164616,76.698887,6293,399,364,5237,548,1236,5148,514,1118,20.547745,7.527827,16.373755
41,Auto,2024-05-06,post,None,303906,3921,1.29,830,0.000000,0.000000,0,0,0,0,0,0,2754,267,618,21.168069,6.809487,15.761285
0,CabEconomy,2024-04-23,pre,Above 5.3.24,13,13,100.00,3,61.538462,61.538462,8,2,4,8,3,3,10,1,2,23.076923,7.692308,15.384615
1,CabEconomy,2024-04-23,pre,Below 5.3.24,19651,19623,99.86,6672,84.171635,68.185293,16517,1826,2668,13380,3891,3690,12533,3314,3775,34.000917,16.888345,19.237629
2,CabEconomy,2024-04-23,pre,None,20566,649,3.16,232,0.000000,0.000000,0,0,0,0,0,0,404,114,131,35.747304,17.565485,20.184900
3,CabEconomy,2024-04-24,pre,Above 5.3.24,18,18,100.00,6,77.777778,72.222222,14,5,1,13,4,3,11,6,1,33.333333,33.333333,5.555556
4,CabEconomy,2024-04-24,pre,Below 5.3.24,20532,20508,99.88,6842,84.069631,68.607373,17241,1926,2778,14070,4634,3149,13194,4073,3241,33.362590,19.860542,15.803589
5,CabEconomy,2024-04-24,pre,None,20733,658,3.17,224,0.000000,0.000000,0,0,0,0,0,0,413,120,125,34.042553,18.237082,18.996960
6,CabEconomy,2024-04-25,pre,Below 5.3.24,23041,23018,99.90,7359,83.391259,69.006864,19195,2345,3240,15884,5017,3753,15088,4309,3619,31.970632,18.720132,15.722478
7,CabEconomy,2024-04-25,pre,None,29450,702,2.38,195,0.000000,0.000000,0,0,0,0,0,0,482,116,104,27.777778,16.524217,14.814815
8,CabEconomy,2024-04-25,pre,Above 5.3.24,29,29,100.00,6,86.206897,82.758621,25,3,5,24,6,4,23,3,3,20.689655,10.344828,10.344828
9,CabEconomy,2024-04-26,pre,Above 5.3.24,22,22,100.00,6,77.272727,77.272727,17,4,1,17,2,3,15,4,3,27.272727,18.181818,13.636364
10,CabEconomy,2024-04-26,pre,Below 5.3.24,18574,18558,99.91,5773,84.405647,69.193879,15664,1805,2111,12841,3769,2903,12294,3462,2801,31.107878,18.655027,15.093221
11,CabEconomy,2024-04-26,pre,None,24751,493,1.99,174,0.000000,0.000000,0,0,0,0,0,0,302,81,110,35.294118,16.430020,22.312373
12,CabEconomy,2024-04-27,pre,Below 5.3.24,21555,21522,99.85,6753,84.978162,69.361583,18289,1932,2403,14928,4446,3166,14314,4080,3126,31.377195,18.957346,14.524672
13,CabEconomy,2024-04-27,pre,Above 5.3.24,19,19,100.00,7,89.473684,63.157895,17,1,3,12,5,3,12,4,3,36.842105,21.052632,15.789474
14,CabEconomy,2024-04-27,pre,None,25505,603,2.36,192,0.000000,0.000000,0,0,0,0,0,0,397,112,94,31.840796,18.573798,15.588723
15,CabEconomy,2024-04-28,pre,None,32675,693,2.12,210,0.000000,0.000000,0,0,0,0,0,0,468,121,104,30.303030,17.460317,15.007215
16,CabEconomy,2024-04-28,pre,Above 5.3.24,7,7,100.00,2,100.000000,71.428571,7,0,2,5,2,2,5,0,2,28.571429,0.000000,28.571429
17,CabEconomy,2024-04-28,pre,Below 5.3.24,21251,21230,99.90,6777,83.815356,69.128592,17794,2150,2263,14676,4188,3263,13911,4061,3256,31.921809,19.128592,15.336788
18,CabEconomy,2024-04-29,None,Above 5.3.24,11,11,100.00,5,72.727273,72.727273,8,3,0,8,2,1,6,4,1,45.454545,36.363636,9.090909
19,CabEconomy,2024-04-29,None,None,23445,651,2.78,190,0.000000,0.000000,0,0,0,0,0,0,433,114,104,29.185868,17.511521,15.975422
20,CabEconomy,2024-04-29,None,Below 5.3.24,21130,21112,99.91,6294,85.449034,70.135468,18040,2090,1879,14807,3967,3182,14231,3941,2939,29.812429,18.667109,13.920993
21,CabEconomy,2024-04-30,None,Below 5.3.24,21519,21490,99.87,6395,84.755700,70.758492,18214,2443,1691,15206,3640,3493,14611,3909,2968,29.758027,18.189856,13.811075
22,CabEconomy,2024-04-30,None,None,20649,670,3.24,195,0.000000,0.000000,0,0,0,0,0,0,455,112,103,29.104478,16.716418,15.373134
23,CabEconomy,2024-04-30,None,Above 5.3.24,16,16,100.00,9,68.750000,62.500000,11,3,2,10,6,0,7,7,2,56.250000,43.750000,12.500000
24,CabEconomy,2024-05-01,None,Above 5.3.24,38,38,100.00,9,89.473684,71.052632,34,5,2,27,5,8,27,6,5,23.684211,15.789474,13.157895
25,CabEconomy,2024-05-01,None,Below 5.3.24,22172,22148,99.89,6683,84.910601,70.746794,18806,2534,1627,15669,3819,3439,14928,4264,2955,30.174282,19.252303,13.342062
26,CabEconomy,2024-05-01,None,None,22204,661,2.98,203,0.000000,0.000000,0,0,0,0,0,0,437,124,100,30.711044,18.759455,15.128593
27,CabEconomy,2024-05-02,None,Below 5.3.24,22939,22917,99.90,6930,84.993673,71.161147,19478,2370,1992,16308,3793,3689,15508,3946,3460,30.239560,17.218659,15.097962
28,CabEconomy,2024-05-02,None,None,28881,739,2.56,239,0.000000,0.000000,0,0,0,0,0,0,480,154,105,32.341001,20.838972,14.208390
29,CabEconomy,2024-05-02,None,Above 5.3.24,81,81,100.00,31,82.716049,65.432099,67,12,7,53,15,17,48,17,16,38.271605,20.987654,19.753086
30,CabEconomy,2024-05-03,None,Below 5.3.24,23130,23107,99.90,6437,88.869174,73.120699,20535,1877,1594,16896,3237,3849,16242,3253,3603,27.857359,14.077985,15.592678
31,CabEconomy,2024-05-03,None,Above 5.3.24,72,72,100.00,16,84.722222,73.611111,61,8,9,53,7,16,53,4,15,22.222222,5.555556,20.833333
32,CabEconomy,2024-05-03,None,None,23116,690,2.98,191,0.000000,0.000000,0,0,0,0,0,0,479,90,119,27.681159,13.043478,17.246377
33,CabEconomy,2024-05-04,post,Below 5.3.24,24533,24496,99.85,7314,88.712443,71.942358,21731,2024,1728,17623,3573,4259,16803,3662,4025,29.857936,14.949379,16.431254
34,CabEconomy,2024-05-04,post,Above 5.3.24,72,72,100.00,15,86.111111,76.388889,62,6,8,55,10,9,57,7,8,20.833333,9.722222,11.111111
35,CabEconomy,2024-05-04,post,None,30241,819,2.71,227,0.000000,0.000000,0,0,0,0,0,0,578,100,140,27.716728,12.210012,17.094017
36,CabEconomy,2024-05-05,post,Above 5.3.24,86,86,100.00,24,82.558140,80.232558,71,8,14,69,13,10,62,10,14,27.906977,11.627907,16.279070
37,CabEconomy,2024-05-05,post,Below 5.3.24,24367,24347,99.92,7025,88.885694,72.715324,21641,1901,1643,17704,3503,3977,16951,3559,3832,28.853658,14.617817,15.739105
38,CabEconomy,2024-05-05,post,None,29726,739,2.49,202,0.000000,0.000000,0,0,0,0,0,0,525,93,121,27.334235,12.584574,16.373478
39,CabEconomy,2024-05-06,post,None,52726,976,1.85,290,0.000000,0.000000,0,0,0,0,0,0,516,110,134,29.713115,11.270492,13.729508
40,CabEconomy,2024-05-06,post,Above 5.3.24,1004,1000,99.60,275,89.300000,69.400000,893,79,80,694,159,143,661,147,140,27.500000,14.700000,14.000000
41,CabEconomy,2024-05-06,post,Below 5.3.24,23628,23597,99.87,6828,88.714667,70.822562,20934,1850,1710,16712,3274,3900,15973,3262,3780,28.935882,13.823791,16.018985

In [ ]:
total_df_d1_d2['service_name'].nunique()

In [37]:
total_df_d1_d2['Est_Nav_bucket_less_500m_percent']=(total_df_d1_d2['Est_Nav_bucket_less_500m']*100.00)/(total_df_d1_d2['net_orders'])
total_df_d1_d2['Est_Nav_bucket_grt_500m_percent']=(total_df_d1_d2['Est_Nav_bucket_grt_500m']*100.00)/(total_df_d1_d2['net_orders'])

In [42]:
total_df_d1_d2.columns

Index(['service_name', 'orderdate', 'new_date_type',
       'app_optimal_version_type', 'gross_orders', 'net_orders', 'G2N',
       'route_diff_orders', 'fe_nav_bucket_within_500m_percent',
       'nav_actual_bucket_within_500m_percent', 'fe_nav_bucket_within_500m',
       'fe_nav_bucket_less_500m', 'fe_nav_bucket_grt_500m',
       'nav_actual_bucket_within_500m', 'nav_actual_bucket_less_500m',
       'nav_actual_bucket_grt_500m', 'Est_Nav_bucket_within_500m',
       'Est_Nav_bucket_less_500m', 'Est_Nav_bucket_grt_500m',
       'route_diff_percent', 'Est_Nav_bucket_less_500m_percent',
       'Est_Nav_bucket_grt_500m_percent'],
      dtype='object')

In [56]:
k1=total_df_d1_d2.groupby(['service_name', 'new_date_type', 'app_version_type']).agg({
    'gross_orders': 'sum',
    'net_orders': 'sum',
    'route_diff_orders': 'sum',
    'fe_nav_bucket_within_500m': 'sum',
    'nav_actual_bucket_within_500m': 'sum',
    'Est_Nav_bucket_within_500m': 'sum',
    'Est_Nav_bucket_less_500m': 'sum',
    'Est_Nav_bucket_grt_500m': 'sum'
}).reset_index()

In [57]:
k1['Est_Nav_bucket_less_500m_percent']=(k1['Est_Nav_bucket_less_500m']*100.00)/(k1['net_orders'])
k1['Est_Nav_bucket_grt_500m_percent']=(k1['Est_Nav_bucket_grt_500m']*100.00)/(k1['net_orders'])
k1['fe_nav_bucket_within_500m_percent']=(k1['fe_nav_bucket_within_500m']*100.00)/k1['net_orders']
k1['nav_actual_bucket_within_500m_percent']=(k1['nav_actual_bucket_within_500m']*100.00)/k1['net_orders']
k1['route_diff_percent']=(k1['route_diff_orders']*100.00)/k1['net_orders']

In [59]:
k1

,service_name,new_date_type,app_version_type,gross_orders,net_orders,route_diff_orders,fe_nav_bucket_within_500m,nav_actual_bucket_within_500m,Est_Nav_bucket_within_500m,Est_Nav_bucket_less_500m,Est_Nav_bucket_grt_500m,Est_Nav_bucket_less_500m_percent,Est_Nav_bucket_grt_500m_percent,fe_nav_bucket_within_500m_percent,nav_actual_bucket_within_500m_percent,route_diff_percent
0,Auto,post,Above 5.3.22,426782,425293,88052,392133,328733,324650,31836,68161,7.485663,16.026833,92.203022,77.295653,20.703844
1,Auto,post,Below 5.3.22,16980,16905,3832,14156,12833,12523,1207,3161,7.139899,18.698610,83.738539,75.912452,22.667850
2,Auto,pre,Above 5.3.22,385246,384032,81811,339235,292063,292000,35608,56388,9.272144,14.683151,88.335087,76.051735,21.303173
3,Auto,pre,Below 5.3.22,421086,419772,90882,369638,317026,316730,38421,64596,9.152826,15.388354,88.056850,75.523379,21.650324
4,CabEconomy,post,Above 5.3.22,71854,71766,20815,63963,51636,49384,10378,11379,14.460887,15.855698,89.127163,71.950506,29.003985
5,CabEconomy,post,Below 5.3.22,1836,1832,666,1369,1221,1123,269,420,14.683406,22.925764,74.727074,66.648472,36.353712
6,CabEconomy,pre,Above 5.3.22,61711,61635,19495,51907,42745,40628,11441,9560,18.562505,15.510668,84.216760,69.351829,31.629756
7,CabEconomy,pre,Below 5.3.22,63004,62935,20712,52883,43114,40784,11876,10273,18.870263,16.323191,84.027965,68.505601,32.910145

In [60]:
total_df_d1_d2.to_csv('d1_new_v1.csv')

In [25]:
total_df_d1_d2.to_csv('d1_d2_app_version_v2.csv')

In [ ]:
total_df_d1_d2[['orderdate','app_version_type','net_orders','fe_nav_bucket_within_500m_percent']].sort_values(by='orderdate',ascending=True)

In [4]:
route_check_df=pd.read_sql(route_check,connection3)

In [5]:
route_check_df

,service_name,orderdate,gross_orders,net_orders,G2N,route_diff_orders,fe_nav_bucket_within_500m_percent,fe_nav_bucket_within_500m,fe_nav_bucket_less_500m,fe_nav_bucket_grt_500m,nav_actual_bucket_within_500m,nav_actual_bucket_less_500m,nav_actual_bucket_grt_500m,Est_Nav_bucket_within_500m,Est_Nav_bucket_less_500m,Est_Nav_bucket_grt_500m
0,CabEconomy,2024-04-25,52496,23744,45.23,7560,36.60,19215,2347,3244,15904,5022,3756,15591,4426,3725
1,CabEconomy,2024-04-26,43344,19073,44.00,5953,36.18,15681,1809,2112,12858,3771,2906,12611,3547,2914
2,CabEconomy,2024-04-27,47075,22144,47.04,6952,38.89,18306,1933,2406,14940,4451,3169,14723,4196,3223
3,CabEconomy,2024-04-28,53933,21930,40.66,6989,33.01,17801,2150,2265,14681,4190,3265,14384,4182,3362
4,CabEconomy,2024-04-29,44584,21774,48.84,6489,40.48,18048,2093,1879,14815,3969,3183,14670,4059,3044
5,CabEconomy,2024-04-30,42184,22176,52.57,6599,43.20,18225,2446,1693,15216,3646,3493,15073,4028,3073
6,CabEconomy,2024-05-01,44411,22847,51.44,6895,42.42,18840,2539,1629,15696,3824,3447,15392,4394,3060
7,CabEconomy,2024-05-02,51897,23737,45.74,7200,37.66,19545,2382,1999,16361,3808,3706,16036,4117,3581
8,CabEconomy,2024-05-03,46317,23869,51.53,6644,44.47,20595,1885,1603,16948,3244,3865,16774,3347,3737
9,CabEconomy,2024-05-04,54846,25387,46.29,7556,39.73,21793,2030,1736,17678,3583,4268,17438,3769,4173
10,CabEconomy,2024-05-05,54179,25171,46.46,7251,39.79,21556,1894,1639,17161,3411,3853,16922,3577,3834

In [6]:
city_name = 'Bangalore'
start_date='2024-04-25'
end_date='2024-05-05'
service_name='Auto'

In [10]:
route_check1=f"""WITH service_mapping AS ( 
        SELECT 
            service_detail_id,
            service_level as service_name,
            service_category,
            service_id,
            city_display_name as city,
            city_id
        FROM 
            datasets.service_mapping
        WHERE 
            city_display_name='{city_name}'
            and service_level='{service_name}'
    ),
    
    fe_tbl as (
            SELECT
                fare_estimate_id fid,
                api_context,final_amount as final_amount_fare,
                date_format(from_unixtime(epoch / 1000, 'Asia/Kolkata'), '%Y-%m-%d') AS order_date,
                cast(final_amount AS double) AS fe_amount,service_detail_id as service_id_fare,
                epoch fe,ride_distance as d1, estimated_ride_time as t1
            FROM
                pricing.fare_estimates_enriched 
            WHERE 
            yyyymmdd BETWEEN DATE_FORMAT(date('{start_date}'),'%Y%m%d') 
            AND DATE_FORMAT(date('{end_date}'),'%Y%m%d') 
               
    ),
    orderlogs as 
    (SELECT *,u.id_array as fare_estimate_id
    FROM 
    ( SELECT order_id, (amount-prev_due) as order_amount,customer_id,captain_id,
             date_format(from_unixtime(epoch / 1000, 'Asia/Kolkata'), '%Y-%m-%d') AS orderdate,
             epoch,estimate_id,estimate_ids,ride_time as t3,
             fare_recalculated_reason, all_paths,
             spd_fraud_flag,order_status,
             service_obj_service_name as service_name,
             fare_recalculated_diff_amount AS fe_re_diff_amount,service_detail_id,
             cast(json_parse(estimate_ids) as array<varchar>) AS id_array
      FROM orders.order_logs_snapshot
           WHERE 
            yyyymmdd BETWEEN DATE_FORMAT(date('{start_date}'),'%Y%m%d') 
            AND DATE_FORMAT(date('{end_date}'),'%Y%m%d') 
            AND city_name IN (SELECT city FROM service_mapping)
            AND service_obj_service_name IN (SELECT service_name FROM service_mapping)) as t
    CROSS JOIN UNNEST(t.id_array) AS u(id_array)),
    immutable AS (
        SELECT 
            DATE_FORMAT(DATE_PARSE(yyyymmdd, '%Y%m%d'), '%Y-%m-%d') orderdate,
            order_id,
            cast (event_time as double) event_time
        FROM 
            orders.order_logs_immutable 
           WHERE 
            yyyymmdd BETWEEN DATE_FORMAT(date('{start_date}'),'%Y%m%d') 
            AND DATE_FORMAT(date('{end_date}'),'%Y%m%d') 
            AND event_type = 'started'
            AND city_name IN (SELECT city FROM service_mapping)
            AND service_obj_service_name IN (SELECT service_name FROM service_mapping)
    ),
    
    nav_metrics AS (
        SELECT 
            event_props_order_id,
            cast  (event_props_epoch as double) event_props_epoch,
            DATE_FORMAT(DATE_PARSE(yyyymmdd, '%Y%m%d'), '%Y-%m-%d') orderdate,
            try(cast(event_props_distance_in_meters as double) )/ 1000 d2
        FROM
            clevertap.captain_inappnavmetrics_immutable
             WHERE 
            yyyymmdd BETWEEN DATE_FORMAT(date('{start_date}'),'%Y%m%d') 
            AND DATE_FORMAT(date('{end_date}'),'%Y%m%d') 
            AND event_props_order_status = 'started'
    ),
    
    distance2 AS (
        SELECT 
            orderdate,
            order_id,
            d2
        FROM 
            ( 
            select 
                imu.orderdate,
                imu.order_id,
                date_diff('minute', from_unixtime(event_time/1000), from_unixtime(event_props_epoch/1000)) AS minDiff,
                "d2"
            from 
                immutable imu 
            join 
                nav_metrics nav 
                ON imu.order_id = nav.event_props_order_id
            )
            --and event_props_epoch >= event_time )
        WHERE abs(minDiff) <= 1
    ),
    done as  (select 
               distinct order_id,d1,t1,t3,epoch,fare_recalculated_reason,service_name,rn,api_context, (fe_amount-order_amount) as amt_diff, all_paths,fid,
            spd_fraud_flag,order_status,orderdate
           
               from 
              (SELECT *,row_number () over(partition by order_id order by fe) rn from 
              (SELECT  *
               from orderlogs join fe_tbl
               on fare_estimate_id = fid 
               and service_detail_id = service_id_fare)
               )
               where rn =1
     ),
    dthree as (select distinct order_id, CASE
            WHEN selectedroute = 'hFRoute' THEN hfdistance
            WHEN selectedroute = 'actualRoute' THEN directionsresponsedistance
            WHEN selectedroute = 'estimatedRoute' THEN final_estimated_directions_response_distance
            ELSE NULL -- Handle other cases if needed
        END AS d3, selectedroute
        from
    (select * from (
    select *, row_number () over(partition by order_id order by updatedAt) rn from (
     select yyyymmdd,orderid as order_id, cast(hfdistance as double)*1000 as hfdistance,cast(pingdensity as double)*100 as pingdensity,cast(directionsresponsedistance as double) as directionsresponsedistance,
                 cast(final_estimated_directions_response_distance as double) as final_estimated_directions_response_distance,selectedroute,updatedAt
                 from raw.captain_distance_response
                    WHERE 
            yyyymmdd BETWEEN DATE_FORMAT(date('{start_date}'),'%Y%m%d') 
            AND DATE_FORMAT(date('{end_date}'),'%Y%m%d') 
                   
                ))
                where rn = 1
                 )),
                 
    merged_tbl as
    (
    
    
        select done.order_id,d2,done.orderdate,d3,d1,
        -- group_tc,
        fare_recalculated_reason,spd_fraud_flag,order_status,service_name,
        CASE
            WHEN d2 IS NOT NULL then d1-d2
            END AS fe_vs_nav,
            d1-(d3*1.00/1000.00) as Est_Nav,
            case WHEN d2 IS NOT NULL then d2-(d3*1.00/1000.00)
            END AS nav_actual
        from done
        left join dthree
        on done.order_id=dthree.order_id
        left join distance2
        on done.order_id=distance2.order_id
    
    
    
    )
    -- select * from merged_tbl
    -- where orderdate is null
    
    
    select service_name,
    orderdate,
    -- ,
    count(distinct order_id) as gross_orders,
    count(distinct case when order_status='dropped' and spd_fraud_flag!=True then order_id end) as net_orders,
    (count(distinct case when order_status='dropped' and spd_fraud_flag!=True then order_id end)*100.00)/(count (distinct order_id)) as "G2N",
    
    (count(distinct case when order_status='dropped' and spd_fraud_flag!=True and fe_vs_nav_bucket='a. Within_500_m' then order_id end)*100.00)/(count( distinct order_id)) as fe_nav_bucket_within_500m_percent,
    (count(distinct case when order_status='dropped' and spd_fraud_flag!=True and nav_actual_bucket='a. Within_500_m' then order_id end)*100.00)/(count( distinct order_id)) as nav_actual_bucket_within_500m_percent,
    (count(distinct case when order_status='dropped' and spd_fraud_flag!=True and fare_recalculated_reason='routeDiff' then order_id end)*100.00)/(count( distinct order_id)) as route_diff_percent,
    count(distinct case when order_status='dropped' and spd_fraud_flag!=True and fare_recalculated_reason='routeDiff' then order_id end) as route_diff_orders,
    
    
    count(distinct case when order_status='dropped' and spd_fraud_flag!=True and fe_vs_nav_bucket='a. Within_500_m' then order_id end) as fe_nav_bucket_within_500m,
    count(distinct case when order_status='dropped' and spd_fraud_flag!=True and fe_vs_nav_bucket='b. Less_than_500m' then order_id end) as fe_nav_bucket_less_500m,
    count(distinct case when order_status='dropped' and spd_fraud_flag!=True and fe_vs_nav_bucket='c. Greater_than_500m' then order_id end) as fe_nav_bucket_grt_500m,
    
    count(distinct case when order_status='dropped' and spd_fraud_flag!=True and nav_actual_bucket='a. Within_500_m' then order_id end) as nav_actual_bucket_within_500m,
    count(distinct case when order_status='dropped' and spd_fraud_flag!=True and nav_actual_bucket='b. Less_than_500m' then order_id end) as nav_actual_bucket_less_500m,
    count(distinct case when order_status='dropped' and spd_fraud_flag!=True and nav_actual_bucket='c. Greater_than_500m' then order_id end) as nav_actual_bucket_grt_500m,
    
    count(distinct case when order_status='dropped' and spd_fraud_flag!=True and Est_Nav_bucket='a. Within_500_m' then order_id end) as Est_Nav_bucket_within_500m,
    count(distinct case when order_status='dropped' and spd_fraud_flag!=True and Est_Nav_bucket='b. Less_than_500m' then order_id end) as Est_Nav_bucket_less_500m,
    count(distinct case when order_status='dropped' and spd_fraud_flag!=True and Est_Nav_bucket='c. Greater_than_500m' then order_id end) as Est_Nav_bucket_grt_500m
    
    
    
    from(
            select *,case when d2 is not NULL and fe_vs_nav>=-0.5 and fe_vs_nav<=0.5 then 'a. Within_500_m'
            when d2 is not NULL and fe_vs_nav<-0.5 then 'b. Less_than_500m'
            when d2 is not NULL and fe_vs_nav>0.5 then 'c. Greater_than_500m' end as fe_vs_nav_bucket,
            case when  d2 is not NULL and nav_actual>=-0.5 and nav_actual<=0.5 then 'a. Within_500_m'
            when d2 is not NULL and nav_actual<-0.5 then 'b. Less_than_500m'
            when d2 is not NULL and nav_actual>0.5 then 'c. Greater_than_500m' end as nav_actual_bucket,
            case when Est_Nav>=-0.5 and Est_Nav<=0.5 then 'a. Within_500_m'
            when Est_Nav<-0.5 then 'b. Less_than_500m'
            when Est_Nav>0.5 then 'c. Greater_than_500m' end as Est_Nav_bucket
            from merged_tbl
            group by 1,2,3,4,5,6,7,8,9,10,11,12,13
    )
    group by 1,2
    order by 2
"""

In [11]:
route_check_df_1=pd.read_sql(route_check1,connection3)

In [16]:
route_check_df_1['fe_nav_bucket_within_500m_percent']=(route_check_df_1['fe_nav_bucket_within_500m']*100.00)/route_check_df_1['net_orders']
route_check_df_1['nav_actual_bucket_within_500m_percent']=(route_check_df_1['nav_actual_bucket_within_500m']*100.00)/route_check_df_1['net_orders']
route_check_df_1['route_diff_percent']=(route_check_df_1['route_diff_orders']*100.00)/route_check_df_1['net_orders']

In [17]:
33171/156004

0.21262916335478577

In [29]:
route_check_df_1

,service_name,orderdate,gross_orders,net_orders,G2N,fe_nav_bucket_within_500m_percent,nav_actual_bucket_within_500m_percent,route_diff_percent,route_diff_orders,fe_nav_bucket_within_500m,fe_nav_bucket_less_500m,fe_nav_bucket_grt_500m,nav_actual_bucket_within_500m,nav_actual_bucket_less_500m,nav_actual_bucket_grt_500m,Est_Nav_bucket_within_500m,Est_Nav_bucket_less_500m,Est_Nav_bucket_grt_500m
0,Auto,2024-04-25,417522,156004,37.36,85.740109,74.014128,21.262916,33171,133758,13003,16309,115465,20080,27549,118039,14487,23464
1,Auto,2024-04-26,264968,114633,43.26,86.653930,74.525660,20.901486,23960,99334,9104,9723,85431,13410,19314,87990,10698,15939
2,Auto,2024-04-27,286963,141584,49.34,86.956153,75.344672,20.469121,28981,123116,10820,11212,106676,15559,22922,109254,13021,19302
3,Auto,2024-04-28,263751,129513,49.10,86.165868,74.628030,21.260414,27535,111596,10803,8913,96653,13192,21505,98998,12564,17941
4,Auto,2024-04-29,327712,146973,44.85,87.042518,75.434944,19.222578,28252,127929,11892,8585,110869,13510,24170,114865,13031,19063
5,Auto,2024-04-30,335270,144549,43.11,87.393202,75.647012,19.178964,27723,126326,12193,7394,109347,13003,23707,112682,13378,18473
6,Auto,2024-05-01,264856,137119,51.77,87.211838,76.037602,19.916277,27309,119584,12206,6503,104262,11719,22441,106915,12803,17393
7,Auto,2024-05-02,408310,152303,37.30,86.858434,75.062868,20.271433,30874,132288,12263,9342,114323,13077,26631,116853,12895,22529
8,Auto,2024-05-03,348866,152654,43.76,89.662243,75.234845,20.424620,31179,136873,9318,7518,114849,11421,27453,116473,10865,25184
9,Auto,2024-05-04,335079,157533,47.01,89.770397,75.501006,20.833095,32819,141418,9652,7989,118939,12456,27749,120277,11845,25386
10,Auto,2024-05-05,298864,137232,45.92,89.832546,75.540690,20.999475,28818,123279,8129,6316,103666,10084,23697,104619,10127,21941

In [26]:
city_name = 'Jaipur'
start_date='2024-02-09'
end_date='2024-02-14'
service_name='Auto'
route_check2=f"""WITH service_mapping AS ( 
        SELECT 
            service_detail_id,
            service_level as service_name,
            service_category,
            service_id,
            city_display_name as city,
            city_id
        FROM 
            datasets.service_mapping
        WHERE 
            city_display_name='{city_name}'
            and service_level='{service_name}'
    ),
    
    fe_tbl as (
            SELECT
                fare_estimate_id fid,
                api_context,final_amount as final_amount_fare,
                date_format(from_unixtime(epoch / 1000, 'Asia/Kolkata'), '%Y-%m-%d') AS order_date,
                cast(final_amount AS double) AS fe_amount,service_detail_id as service_id_fare,
                epoch fe,ride_distance as d1, estimated_ride_time as t1
            FROM
                pricing.fare_estimates_enriched 
            WHERE 
            yyyymmdd BETWEEN DATE_FORMAT(date('{start_date}'),'%Y%m%d') 
            AND DATE_FORMAT(date('{end_date}'),'%Y%m%d') 
               
    ),
    orderlogs as 
    (SELECT *,u.id_array as fare_estimate_id
    FROM 
    ( SELECT order_id, (amount-prev_due) as order_amount,customer_id,captain_id,
             date_format(from_unixtime(epoch / 1000, 'Asia/Kolkata'), '%Y-%m-%d') AS orderdate,
             epoch,estimate_id,estimate_ids,ride_time as t3,
             fare_recalculated_reason, all_paths,
             spd_fraud_flag,order_status,
             service_obj_service_name as service_name,
             fare_recalculated_diff_amount AS fe_re_diff_amount,service_detail_id,
             cast(json_parse(estimate_ids) as array<varchar>) AS id_array
      FROM orders.order_logs_snapshot
           WHERE 
            yyyymmdd BETWEEN DATE_FORMAT(date('{start_date}'),'%Y%m%d') 
            AND DATE_FORMAT(date('{end_date}'),'%Y%m%d') 
            AND city_name IN (SELECT city FROM service_mapping)
            AND service_obj_service_name IN (SELECT service_name FROM service_mapping)) as t
    CROSS JOIN UNNEST(t.id_array) AS u(id_array)),
    immutable AS (
        SELECT 
            DATE_FORMAT(DATE_PARSE(yyyymmdd, '%Y%m%d'), '%Y-%m-%d') orderdate,
            order_id,
            cast (event_time as double) event_time
        FROM 
            orders.order_logs_immutable 
           WHERE 
            yyyymmdd BETWEEN DATE_FORMAT(date('{start_date}'),'%Y%m%d') 
            AND DATE_FORMAT(date('{end_date}'),'%Y%m%d') 
            AND event_type = 'started'
            AND city_name IN (SELECT city FROM service_mapping)
            AND service_obj_service_name IN (SELECT service_name FROM service_mapping)
    ),
    
    nav_metrics AS (
        SELECT 
            event_props_order_id,
            cast  (event_props_epoch as double) event_props_epoch,
            DATE_FORMAT(DATE_PARSE(yyyymmdd, '%Y%m%d'), '%Y-%m-%d') orderdate,
            try(cast(event_props_distance_in_meters as double) )/ 1000 d2
        FROM
            clevertap.captain_inappnavmetrics_immutable
             WHERE 
            yyyymmdd BETWEEN DATE_FORMAT(date('{start_date}'),'%Y%m%d') 
            AND DATE_FORMAT(date('{end_date}'),'%Y%m%d') 
            AND event_props_order_status = 'started'
    ),
    
    distance2 AS (
        SELECT 
            orderdate,
            order_id,
            d2
        FROM 
            ( 
            select 
                imu.orderdate,
                imu.order_id,
                date_diff('minute', from_unixtime(event_time/1000), from_unixtime(event_props_epoch/1000)) AS minDiff,
                "d2"
            from 
                immutable imu 
            join 
                nav_metrics nav 
                ON imu.order_id = nav.event_props_order_id
            )
            --and event_props_epoch >= event_time )
        WHERE abs(minDiff) <= 1
    ),
    done as  (select 
               distinct order_id,d1,t1,t3,epoch,fare_recalculated_reason,service_name,rn,api_context, (fe_amount-order_amount) as amt_diff, all_paths,fid,
            spd_fraud_flag,order_status,orderdate
           
               from 
              (SELECT *,row_number () over(partition by order_id order by fe) rn from 
              (SELECT  *
               from orderlogs join fe_tbl
               on fare_estimate_id = fid 
               and service_detail_id = service_id_fare)
               )
               where rn =1
     ),
    dthree as (select distinct order_id, CASE
            WHEN selectedroute = 'hFRoute' THEN hfdistance
            WHEN selectedroute = 'actualRoute' THEN directionsresponsedistance
            WHEN selectedroute = 'estimatedRoute' THEN final_estimated_directions_response_distance
            ELSE NULL -- Handle other cases if needed
        END AS d3, selectedroute
        from
    (select * from (
    select *, row_number () over(partition by order_id order by updatedAt) rn from (
     select yyyymmdd,orderid as order_id, cast(hfdistance as double)*1000 as hfdistance,cast(pingdensity as double)*100 as pingdensity,cast(directionsresponsedistance as double) as directionsresponsedistance,
                 cast(final_estimated_directions_response_distance as double) as final_estimated_directions_response_distance,selectedroute,updatedAt
                 from raw.captain_distance_response
                    WHERE 
            yyyymmdd BETWEEN DATE_FORMAT(date('{start_date}'),'%Y%m%d') 
            AND DATE_FORMAT(date('{end_date}'),'%Y%m%d') 
                   
                ))
                where rn = 1
                 )),
                 
    merged_tbl as
    (
    
    
        select done.order_id,d2,done.orderdate,d3,d1,
        -- group_tc,
        fare_recalculated_reason,spd_fraud_flag,order_status,service_name,
        CASE
            WHEN d2 IS NOT NULL then d1-d2
            END AS fe_vs_nav,
            d1-(d3*1.00/1000.00) as Est_Nav,
            case WHEN d2 IS NOT NULL then d2-(d3*1.00/1000.00)
            END AS nav_actual
        from done
        left join dthree
        on done.order_id=dthree.order_id
        left join distance2
        on done.order_id=distance2.order_id
    
    
    
    )
    -- select * from merged_tbl
    -- where orderdate is null
    
    
    select service_name,
    orderdate,
    -- ,
    count(distinct order_id) as gross_orders,
    count(distinct case when order_status='dropped' and spd_fraud_flag!=True then order_id end) as net_orders,
    (count(distinct case when order_status='dropped' and spd_fraud_flag!=True then order_id end)*100.00)/(count (distinct order_id)) as "G2N",
    
    (count(distinct case when order_status='dropped' and spd_fraud_flag!=True and fe_vs_nav_bucket='a. Within_500_m' then order_id end)*100.00)/(count( distinct order_id)) as fe_nav_bucket_within_500m_percent,
    (count(distinct case when order_status='dropped' and spd_fraud_flag!=True and nav_actual_bucket='a. Within_500_m' then order_id end)*100.00)/(count( distinct order_id)) as nav_actual_bucket_within_500m_percent,
    (count(distinct case when order_status='dropped' and spd_fraud_flag!=True and fare_recalculated_reason='routeDiff' then order_id end)*100.00)/(count( distinct order_id)) as route_diff_percent,
    count(distinct case when order_status='dropped' and spd_fraud_flag!=True and fare_recalculated_reason='routeDiff' then order_id end) as route_diff_orders,
    
    
    count(distinct case when order_status='dropped' and spd_fraud_flag!=True and fe_vs_nav_bucket='a. Within_500_m' then order_id end) as fe_nav_bucket_within_500m,
    count(distinct case when order_status='dropped' and spd_fraud_flag!=True and fe_vs_nav_bucket='b. Less_than_500m' then order_id end) as fe_nav_bucket_less_500m,
    count(distinct case when order_status='dropped' and spd_fraud_flag!=True and fe_vs_nav_bucket='c. Greater_than_500m' then order_id end) as fe_nav_bucket_grt_500m,
    
    count(distinct case when order_status='dropped' and spd_fraud_flag!=True and nav_actual_bucket='a. Within_500_m' then order_id end) as nav_actual_bucket_within_500m,
    count(distinct case when order_status='dropped' and spd_fraud_flag!=True and nav_actual_bucket='b. Less_than_500m' then order_id end) as nav_actual_bucket_less_500m,
    count(distinct case when order_status='dropped' and spd_fraud_flag!=True and nav_actual_bucket='c. Greater_than_500m' then order_id end) as nav_actual_bucket_grt_500m,
    
    count(distinct case when order_status='dropped' and spd_fraud_flag!=True and Est_Nav_bucket='a. Within_500_m' then order_id end) as Est_Nav_bucket_within_500m,
    count(distinct case when order_status='dropped' and spd_fraud_flag!=True and Est_Nav_bucket='b. Less_than_500m' then order_id end) as Est_Nav_bucket_less_500m,
    count(distinct case when order_status='dropped' and spd_fraud_flag!=True and Est_Nav_bucket='c. Greater_than_500m' then order_id end) as Est_Nav_bucket_grt_500m
    
    
    
    from(
            select *,case when d2 is not NULL and fe_vs_nav>=-0.5 and fe_vs_nav<=0.5 then 'a. Within_500_m'
            when d2 is not NULL and fe_vs_nav<-0.5 then 'b. Less_than_500m'
            when d2 is not NULL and fe_vs_nav>0.5 then 'c. Greater_than_500m' end as fe_vs_nav_bucket,
            case when  d2 is not NULL and nav_actual>=-0.5 and nav_actual<=0.5 then 'a. Within_500_m'
            when d2 is not NULL and nav_actual<-0.5 then 'b. Less_than_500m'
            when d2 is not NULL and nav_actual>0.5 then 'c. Greater_than_500m' end as nav_actual_bucket,
            case when Est_Nav>=-0.5 and Est_Nav<=0.5 then 'a. Within_500_m'
            when Est_Nav<-0.5 then 'b. Less_than_500m'
            when Est_Nav>0.5 then 'c. Greater_than_500m' end as Est_Nav_bucket
            from merged_tbl
            group by 1,2,3,4,5,6,7,8,9,10,11,12,13
    )
    group by 1,2
    order by 2
"""
route_check_df_2=pd.read_sql(route_check2,connection3)

In [27]:
route_check_df_2['fe_nav_bucket_within_500m_percent']=(route_check_df_2['fe_nav_bucket_within_500m']*100.00)/route_check_df_2['net_orders']
route_check_df_2['nav_actual_bucket_within_500m_percent']=(route_check_df_2['nav_actual_bucket_within_500m']*100.00)/route_check_df_2['net_orders']
route_check_df_2['route_diff_percent']=(route_check_df_2['route_diff_orders']*100.00)/route_check_df_2['net_orders']

In [28]:
route_check_df_2['Est_Nav_bucket_less_500m_Percent']=(route_check_df_2['Est_Nav_bucket_less_500m']*100.00)/route_check_df_2['net_orders']

,service_name,orderdate,gross_orders,net_orders,G2N,fe_nav_bucket_within_500m_percent,nav_actual_bucket_within_500m_percent,route_diff_percent,route_diff_orders,fe_nav_bucket_within_500m,fe_nav_bucket_less_500m,fe_nav_bucket_grt_500m,nav_actual_bucket_within_500m,nav_actual_bucket_less_500m,nav_actual_bucket_grt_500m,Est_Nav_bucket_within_500m,Est_Nav_bucket_less_500m,Est_Nav_bucket_grt_500m
0,Auto,2024-02-09,16647,8241,49.50,82.004611,69.858027,29.959956,2469,6758,772,712,5757,1020,1472,5737,1030,1473
1,Auto,2024-02-10,18560,8546,46.05,75.438802,64.696934,31.383103,2682,6447,1125,639,5529,1065,1609,5821,1294,1430
2,Auto,2024-02-11,20926,7919,37.84,76.019699,63.164541,33.526960,2655,6020,986,600,5002,1035,1563,5216,1242,1460
3,Auto,2024-02-12,24025,11601,48.29,74.622877,62.916990,33.212654,3853,8657,1405,1061,7299,1507,2262,7699,1698,2202
4,Auto,2024-02-13,22846,11521,50.43,75.818071,63.275757,33.009287,3803,8735,1405,943,7290,1474,2279,7658,1736,2124
5,Auto,2024-02-14,32696,12367,37.82,71.512897,61.890515,33.912833,4194,8844,1954,1402,7654,1851,2620,8106,1971,2228

In [30]:
route_check_df['fe_nav_bucket_within_500m_percent']=(route_check_df['fe_nav_bucket_within_500m']*100.00)/route_check_df['net_orders']
route_check_df['nav_actual_bucket_within_500m_percent']=(route_check_df['nav_actual_bucket_within_500m']*100.00)/route_check_df['net_orders']
route_check_df['route_diff_percent']=(route_check_df['route_diff_orders']*100.00)/route_check_df['net_orders']

In [39]:
route_check_df['Est_Nav_bucket_less_500m_Percent']=(route_check_df['Est_Nav_bucket_less_500m']*100.00)/route_check_df['net_orders']

In [41]:
route_check_df['Est_Nav_bucket_grt_500m_Percent']=(route_check_df['Est_Nav_bucket_grt_500m']*100.00)/route_check_df['net_orders']

In [42]:
route_check_df

,service_name,orderdate,gross_orders,net_orders,G2N,route_diff_orders,fe_nav_bucket_within_500m_percent,fe_nav_bucket_within_500m,fe_nav_bucket_less_500m,fe_nav_bucket_grt_500m,nav_actual_bucket_within_500m,nav_actual_bucket_less_500m,nav_actual_bucket_grt_500m,Est_Nav_bucket_within_500m,Est_Nav_bucket_less_500m,Est_Nav_bucket_grt_500m,nav_actual_bucket_within_500m_percent,route_diff_percent,Est_Nav_bucket_less_500m_Percent,Est_Nav_bucket_grt_500m_Percent
0,CabEconomy,2024-04-25,52496,23744,45.23,7560,80.925708,19215,2347,3244,15904,5022,3756,15591,4426,3725,66.981132,31.839623,18.640499,15.688174
1,CabEconomy,2024-04-26,43344,19073,44.00,5953,82.215698,15681,1809,2112,12858,3771,2906,12611,3547,2914,67.414670,31.211660,18.596970,15.278142
2,CabEconomy,2024-04-27,47075,22144,47.04,6952,82.667991,18306,1933,2406,14940,4451,3169,14723,4196,3223,67.467486,31.394509,18.948699,14.554733
3,CabEconomy,2024-04-28,53933,21930,40.66,6989,81.171911,17801,2150,2265,14681,4190,3265,14384,4182,3362,66.944824,31.869585,19.069767,15.330597
4,CabEconomy,2024-04-29,44584,21774,48.84,6489,82.887848,18048,2093,1879,14815,3969,3183,14670,4059,3044,68.039864,29.801598,18.641499,13.979976
5,CabEconomy,2024-04-30,42184,22176,52.57,6599,82.183442,18225,2446,1693,15216,3646,3493,15073,4028,3073,68.614719,29.757395,18.163781,13.857323
6,CabEconomy,2024-05-01,44411,22847,51.44,6895,82.461592,18840,2539,1629,15696,3824,3447,15392,4394,3060,68.700486,30.179017,19.232284,13.393443
7,CabEconomy,2024-05-02,51897,23737,45.74,7200,82.339807,19545,2382,1999,16361,3808,3706,16036,4117,3581,68.926149,30.332392,17.344231,15.086152
8,CabEconomy,2024-05-03,46317,23869,51.53,6644,86.283464,20595,1885,1603,16948,3244,3865,16774,3347,3737,71.004231,27.835268,14.022372,15.656291
9,CabEconomy,2024-05-04,54846,25387,46.29,7556,85.843148,21793,2030,1736,17678,3583,4268,17438,3769,4173,69.634065,29.763265,14.846181,16.437547
10,CabEconomy,2024-05-05,54179,25171,46.46,7251,85.638234,21556,1894,1639,17161,3411,3853,16922,3577,3834,68.177665,28.806960,14.210798,15.231814

In [33]:
route_check_df_1

,service_name,orderdate,gross_orders,net_orders,G2N,fe_nav_bucket_within_500m_percent,nav_actual_bucket_within_500m_percent,route_diff_percent,route_diff_orders,fe_nav_bucket_within_500m,fe_nav_bucket_less_500m,fe_nav_bucket_grt_500m,nav_actual_bucket_within_500m,nav_actual_bucket_less_500m,nav_actual_bucket_grt_500m,Est_Nav_bucket_within_500m,Est_Nav_bucket_less_500m,Est_Nav_bucket_grt_500m
0,Auto,2024-04-25,417522,156004,37.36,85.740109,74.014128,21.262916,33171,133758,13003,16309,115465,20080,27549,118039,14487,23464
1,Auto,2024-04-26,264968,114633,43.26,86.653930,74.525660,20.901486,23960,99334,9104,9723,85431,13410,19314,87990,10698,15939
2,Auto,2024-04-27,286963,141584,49.34,86.956153,75.344672,20.469121,28981,123116,10820,11212,106676,15559,22922,109254,13021,19302
3,Auto,2024-04-28,263751,129513,49.10,86.165868,74.628030,21.260414,27535,111596,10803,8913,96653,13192,21505,98998,12564,17941
4,Auto,2024-04-29,327712,146973,44.85,87.042518,75.434944,19.222578,28252,127929,11892,8585,110869,13510,24170,114865,13031,19063
5,Auto,2024-04-30,335270,144549,43.11,87.393202,75.647012,19.178964,27723,126326,12193,7394,109347,13003,23707,112682,13378,18473
6,Auto,2024-05-01,264856,137119,51.77,87.211838,76.037602,19.916277,27309,119584,12206,6503,104262,11719,22441,106915,12803,17393
7,Auto,2024-05-02,408310,152303,37.30,86.858434,75.062868,20.271433,30874,132288,12263,9342,114323,13077,26631,116853,12895,22529
8,Auto,2024-05-03,348866,152654,43.76,89.662243,75.234845,20.424620,31179,136873,9318,7518,114849,11421,27453,116473,10865,25184
9,Auto,2024-05-04,335079,157533,47.01,89.770397,75.501006,20.833095,32819,141418,9652,7989,118939,12456,27749,120277,11845,25386
10,Auto,2024-05-05,298864,137232,45.92,89.832546,75.540690,20.999475,28818,123279,8129,6316,103666,10084,23697,104619,10127,21941

In [36]:
pd.concat([route_check_df,route_check_df_1]).to_csv('check_orders.csv')

In [130]:
def route_cluster_level(start_date,end_date,service_name,city):
    route_level_longest=f"""with orderlogs as 
    (SELECT *,u.id_array as fare_estimate_id
    FROM 
    ( SELECT order_id, (amount-prev_due) as order_amount,customer_id,captain_id,
             date_format(from_unixtime(epoch / 1000, 'Asia/Kolkata'), '%Y-%m-%d') AS orderdate,
             epoch,estimate_id,estimate_ids,ride_time as t3,
             pickup_cluster || ' to ' || drop_cluster cluster_route,
             city_name,
             service_obj_service_name as service_name,
             fare_recalculated_reason, all_paths,
             fare_recalculated_diff_amount AS fe_re_diff_amount,service_detail_id,
             cast(json_parse(estimate_ids) as array<varchar>) AS id_array
      FROM orders.order_logs_snapshot
         WHERE
                  yyyymmdd >= '{start_date}'
                AND yyyymmdd <= '{end_date}'
        and order_status = 'dropped'
        and (spd_fraud_flag = false or spd_fraud_flag is null) 
        AND service_obj_service_name = '{service_name}' 
        and captain_app_version >= '5.3.22'
       and city_name = '{city}') as t
    CROSS JOIN UNNEST(t.id_array) AS u(id_array))
    
    ,fe_tbl as (
            SELECT
                fare_estimate_id fid,
                api_context,final_amount as final_amount_fare,
                date_format(from_unixtime(epoch / 1000, 'Asia/Kolkata'), '%Y-%m-%d') AS order_date,
                cast(final_amount AS double) AS fe_amount,service_detail_id as service_id_fare,
                epoch fe,ride_distance as d1, estimated_ride_time as t1
            FROM
                pricing.fare_estimates_enriched 
            WHERE
                  yyyymmdd >= '{start_date}'
                AND yyyymmdd <= '{end_date}'
               
    )
    
    ,done as  (select 
               distinct order_id,d1,t1,t3,epoch,orderdate,
               CASE WHEN orderdate <= ('2024-05-01') THEN 'pre' else 'post' end as new_date_type,
               fare_recalculated_reason,rn,api_context, (fe_amount-order_amount) as amt_diff, all_paths,fid,cluster_route,service_name,city_name
               from 
              (SELECT *,row_number () over(partition by order_id order by fe) rn from 
              (SELECT  *
               from orderlogs join fe_tbl
               on fare_estimate_id = fid 
               and service_detail_id = service_id_fare)
               )
               where rn =1
     )
     
    ,dthree as (select distinct order_id, CASE
            WHEN selectedroute = 'hFRoute' THEN hfdistance
            WHEN selectedroute = 'actualRoute' THEN directionsresponsedistance
            WHEN selectedroute = 'estimatedRoute' THEN final_estimated_directions_response_distance
            ELSE NULL -- Handle other cases if needed
        END AS d3, selectedroute
        from
    (select * from (
    select *, row_number () over(partition by order_id order by updatedAt) rn from (
     select yyyymmdd,orderid as order_id, cast(hfdistance as double)*1000 as hfdistance,cast(pingdensity as double)*100 as pingdensity,cast(directionsresponsedistance as double) as directionsresponsedistance,
                 cast(final_estimated_directions_response_distance as double) as final_estimated_directions_response_distance,selectedroute,updatedAt
                 from raw.captain_distance_response
                  WHERE
                  yyyymmdd >= '{start_date}'
                AND yyyymmdd <= '{end_date}'
                   
                ))
                where rn = 1
                 )) 
                 
    ,gtable as (  
    select order_id, d1,t1,t3,d3,orderdate,routes_cnt,city_name,cluster_route,service_name,
    new_date_type,
           ARRAY_SORT(ARRAY[distance1, distance2, distance3])[1] AS dist1,
        ARRAY_SORT(ARRAY[distance1, distance2, distance3])[2] AS dist2,
        ARRAY_SORT(ARRAY[distance1, distance2, distance3])[3] AS dist3,
           ARRAY_SORT(ARRAY[time1, time2, time3])[1] AS time1,
           ARRAY_SORT(ARRAY[time1, time2, time3])[2] AS time2,
           ARRAY_SORT(ARRAY[time1, time2, time3])[3] AS time3
        from
    (select done.order_id,t1,t3,orderdate, d1,json_array_length(all_paths) AS routes_cnt,
    new_date_type,
        cast(json_extract_scalar(all_paths, '$[0].distance') as double) /1000 AS distance1,
        cast(json_extract_scalar(all_paths, '$[0].time') as double)/60 AS time1,
          cast(json_extract_scalar(all_paths, '$[1].distance') as double) /1000 AS distance2,
           cast(json_extract_scalar(all_paths, '$[1].time') as double) /60 AS time2,
           cast(json_extract_scalar(all_paths, '$[2].distance') as double) /1000 AS distance3,
           cast(json_extract_scalar(all_paths, '$[2].time') as double) /60 AS time3,
           d3/1000 as d3,city_name,cluster_route,service_name
           FROM
            done
        join dthree on done.order_id = dthree.order_id 
         ))  
      
    
    ,r1 as (select
        ord, d1,d3,dist1,orderdate,city_name,cluster_route,routes_cnt,service_name,new_date_type,(CASE
        WHEN dist2 IS NOT NULL THEN
            CASE
                WHEN dist1 >= dist2 THEN dist1
                ELSE dist2
            END
        ELSE
            dist1
    END) AS dist2,
    (CASE
        WHEN dist3 IS NOT NULL THEN
            CASE
                WHEN dist3 >= COALESCE(dist2, dist3) AND dist3 >= COALESCE(dist1, dist3) THEN dist3
                WHEN dist2 >= COALESCE(dist1, dist2) THEN dist2
                ELSE dist1
            END
        ELSE
            CASE
                WHEN dist1 >= COALESCE(dist2, dist1) THEN dist1
                ELSE dist2
            END
    END) AS dist3
    
    from (
    select DISTINCT order_id AS ord,orderdate,d1,d3,routes_cnt,new_date_type,dist1,dist2,dist3,t1, t3,time1,time2,time3,city_name,cluster_route,service_name from gtable
    
    ))
    
    
    ,r2 AS (
        SELECT 
             ord,orderdate,city_name,cluster_route,service_name,routes_cnt,new_date_type,
            (d1-d3) as Est_nav
        FROM 
            r1
             
    )
    
     SELECT city_name,cluster_route,
     service_name,new_date_type,MIN(orderdate) || MAX(orderdate),
        count(distinct ord) as orders_count,
        (count(distinct case when est_nav>0.5 then ord END)*100.000) / count(distinct ord) AS "D1-D3>500m % (Negative Fare Shock)",
        (count(distinct case when est_nav<-0.5 then ord END)*100.000) / count(distinct ord) AS "D1-D3<-500m% (Positive Fare Shock)",
        (count(distinct case when est_nav>=-0.5 and  Est_nav<=0.5 then ord END)*100.000) / count(distinct ord) AS "No Fare Shock",
        count(CASE WHEN Est_nav <= -20  THEN ord END)*1.000 / count(ord) AS "< -20",
        count(CASE WHEN Est_nav <= -15 AND Est_nav > -20 THEN ord END)*1.000 / count(ord) AS "-20 to -15",
        count(CASE WHEN Est_nav <= -10 AND Est_nav > -15 THEN ord END)*1.000 / count(ord) AS "-15 to -10",
        count(CASE WHEN Est_nav <= -5 AND Est_nav > -10 THEN ord END)*1.000 / count(ord) AS "-10 to -5",
        count(CASE WHEN Est_nav <= -2 AND Est_nav > -5 THEN ord END)*1.000 / count(ord) AS "-5 to -2",
        count(CASE WHEN Est_nav <= -1 AND Est_nav > -2 THEN ord END)*1.000 / count(ord) AS "-2 to -1",
        count(CASE WHEN Est_nav <= -0.5 AND Est_nav > -1 THEN ord END)*1.000 / count(ord) AS "-1 to -0.5",
        count(CASE WHEN Est_nav <= -0.2 AND Est_nav > -0.5 THEN ord END)*1.000 / count(ord) AS "-0.5 to -0.2",
        count(CASE WHEN Est_nav < 0 AND Est_nav > -0.2 THEN ord END)*1.000 / count(ord) AS "-0.2 to 0",
        count(CASE WHEN Est_nav = 0 THEN ord END)*1.000 / count(ord) AS "0",
        count(CASE WHEN Est_nav <= 0.2 AND Est_nav > 0 THEN ord END)*1.000 / count(ord) AS "0 to 0.2",
        count(CASE WHEN Est_nav <= 0.5 AND Est_nav > 0.2 THEN ord END)*1.000 / count(ord) AS "0.2 to 0.5",
        count(CASE WHEN Est_nav <= 1 AND Est_nav > 0.5 THEN ord END)*1.000 / count(ord) AS "0.5 to 1",
        count(CASE WHEN Est_nav <= 2 AND Est_nav > 1 THEN ord END)*1.000 / count(ord) AS "1 to 2",
        count(CASE WHEN Est_nav <= 5 AND Est_nav > 2 THEN ord END)*1.000 / count(ord) AS "2 to 5",
        count(CASE WHEN Est_nav <= 10 AND Est_nav > 5 THEN ord END)*1.000 / count(ord) AS "5 to 10",
        count(CASE WHEN Est_nav <= 15 AND Est_nav > 10 THEN ord END)*1.000 / count(ord) AS "10 to 15",
        count(CASE WHEN Est_nav <= 20 AND Est_nav > 15 THEN ord END)*1.000 / count(ord) AS "15 to 20",
        count(CASE WHEN  Est_nav > 20 THEN ord END)*1.000 / count(ord) AS ">20"
      FROM r2
      group by 1,2,3,4
     """
    d1=pd.read_sql(route_level_longest,connection4)
    return d1

In [131]:
start_date='20240425'
end_date='20240506'

In [132]:
total_df_second_longest1=pd.DataFrame()
city_name=['Bangalore','Delhi','Hyderabad','Chennai','Jaipur']
service_level=['Link','Auto','CabEconomy']
for i in city_name[0:1]:
    print(i)
    for j in service_level[1:]:
        print(j)
        df=route_cluster_level(start_date,end_date,j,i)
        df['distance_type']='second_longest'
        total_df_second_longest1=pd.concat([total_df_second_longest1,df])

Bangalore
Auto

DatabaseError: {'message': "line 20:21: mismatched input 'app'. Expecting: '%', '(', ')', '*', '+', ',', '-', '.', '/', 'AND', 'AS', 'AT', 'CROSS', 'EXCEPT', 'FETCH', 'FULL', 'GROUP', 'HAVING', 'INNER', 'INTERSECT', 'JOIN', 'LEFT', 'LIMIT', 'MATCH_RECOGNIZE', 'NATURAL', 'OFFSET', 'OR', 'ORDER', 'RIGHT', 'SELECT', 'TABLE', 'TABLESAMPLE', 'UNION', 'VALUES', 'WHERE', 'WINDOW', '[', '||', <EOF>, <identifier>, <predicate>", 'errorCode': 1, 'errorName': 'SYNTAX_ERROR', 'errorType': 'USER_ERROR', 'errorLocation': {'lineNumber': 20, 'columnNumber': 21}, 'failureInfo': {'type': 'io.trino.sql.parser.ParsingException', 'message': "line 20:21: mismatched input 'app'. Expecting: '%', '(', ')', '*', '+', ',', '-', '.', '/', 'AND', 'AS', 'AT', 'CROSS', 'EXCEPT', 'FETCH', 'FULL', 'GROUP', 'HAVING', 'INNER', 'INTERSECT', 'JOIN', 'LEFT', 'LIMIT', 'MATCH_RECOGNIZE', 'NATURAL', 'OFFSET', 'OR', 'ORDER', 'RIGHT', 'SELECT', 'TABLE', 'TABLESAMPLE', 'UNION', 'VALUES', 'WHERE', 'WINDOW', '[', '||', <EOF>, <identifier>, <predicate>", 'cause': {'type': 'org.antlr.v4.runtime.InputMismatchException', 'suppressed': [], 'stack': ['io.trino.sql.parser.SqlParser$2.recoverInline(SqlParser.java:128)', 'org.antlr.v4.runtime.Parser.match(Parser.java:206)', 'io.trino.sql.parser.SqlBaseParser.relationPrimary(SqlBaseParser.java:9477)', 'io.trino.sql.parser.SqlBaseParser.aliasedRelation(SqlBaseParser.java:9193)', 'io.trino.sql.parser.SqlBaseParser.patternRecognition(SqlBaseParser.java:8445)', 'io.trino.sql.parser.SqlBaseParser.sampledRelation(SqlBaseParser.java:8074)', 'io.trino.sql.parser.SqlBaseParser.relation(SqlBaseParser.java:7748)', 'io.trino.sql.parser.SqlBaseParser.querySpecification(SqlBaseParser.java:6681)', 'io.trino.sql.parser.SqlBaseParser.queryPrimary(SqlBaseParser.java:6415)', 'io.trino.sql.parser.SqlBaseParser.queryTerm(SqlBaseParser.java:6220)', 'io.trino.sql.parser.SqlBaseParser.queryNoWith(SqlBaseParser.java:5871)', 'io.trino.sql.parser.SqlBaseParser.query(SqlBaseParser.java:5039)', 'io.trino.sql.parser.SqlBaseParser.namedQuery(SqlBaseParser.java:7451)', 'io.trino.sql.parser.SqlBaseParser.with(SqlBaseParser.java:5101)', 'io.trino.sql.parser.SqlBaseParser.query(SqlBaseParser.java:5034)', 'io.trino.sql.parser.SqlBaseParser.statement(SqlBaseParser.java:2531)', 'io.trino.sql.parser.SqlBaseParser.singleStatement(SqlBaseParser.java:320)', 'io.trino.sql.parser.SqlParser.invokeParser(SqlParser.java:145)', 'io.trino.sql.parser.SqlParser.createStatement(SqlParser.java:85)', 'io.trino.execution.QueryPreparer.prepareQuery(QueryPreparer.java:55)', 'io.trino.dispatcher.DispatchManager.createQueryInternal(DispatchManager.java:180)', 'io.trino.dispatcher.DispatchManager.lambda$createQuery$0(DispatchManager.java:149)', 'io.trino.$gen.Trino_386____20240507_063018_2.run(Unknown Source)', 'java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)', 'java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)', 'java.base/java.lang.Thread.run(Thread.java:829)']}, 'suppressed': [], 'stack': ['io.trino.sql.parser.ErrorHandler.syntaxError(ErrorHandler.java:109)', 'org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)', 'org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:544)', 'org.antlr.v4.runtime.DefaultErrorStrategy.reportInputMismatch(DefaultErrorStrategy.java:327)', 'org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:139)', 'io.trino.sql.parser.SqlBaseParser.relationPrimary(SqlBaseParser.java:9566)', 'io.trino.sql.parser.SqlBaseParser.aliasedRelation(SqlBaseParser.java:9193)', 'io.trino.sql.parser.SqlBaseParser.patternRecognition(SqlBaseParser.java:8445)', 'io.trino.sql.parser.SqlBaseParser.sampledRelation(SqlBaseParser.java:8074)', 'io.trino.sql.parser.SqlBaseParser.relation(SqlBaseParser.java:7748)', 'io.trino.sql.parser.SqlBaseParser.querySpecification(SqlBaseParser.java:6681)', 'io.trino.sql.parser.SqlBaseParser.queryPrimary(SqlBaseParser.java:6415)', 'io.trino.sql.parser.SqlBaseParser.queryTerm(SqlBaseParser.java:6220)', 'io.trino.sql.parser.SqlBaseParser.queryNoWith(SqlBaseParser.java:5871)', 'io.trino.sql.parser.SqlBaseParser.query(SqlBaseParser.java:5039)', 'io.trino.sql.parser.SqlBaseParser.namedQuery(SqlBaseParser.java:7451)', 'io.trino.sql.parser.SqlBaseParser.with(SqlBaseParser.java:5101)', 'io.trino.sql.parser.SqlBaseParser.query(SqlBaseParser.java:5034)', 'io.trino.sql.parser.SqlBaseParser.statement(SqlBaseParser.java:2531)', 'io.trino.sql.parser.SqlBaseParser.singleStatement(SqlBaseParser.java:320)', 'io.trino.sql.parser.SqlParser.invokeParser(SqlParser.java:145)', 'io.trino.sql.parser.SqlParser.createStatement(SqlParser.java:85)', 'io.trino.execution.QueryPreparer.prepareQuery(QueryPreparer.java:55)', 'io.trino.dispatcher.DispatchManager.createQueryInternal(DispatchManager.java:180)', 'io.trino.dispatcher.DispatchManager.lambda$createQuery$0(DispatchManager.java:149)', 'io.trino.$gen.Trino_386____20240507_063018_2.run(Unknown Source)', 'java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)', 'java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)', 'java.base/java.lang.Thread.run(Thread.java:829)'], 'errorLocation': {'lineNumber': 20, 'columnNumber': 21}}}

In [125]:
total_df_second_longest

,city_name,service_name,new_date_type,_col3,orders_count,D1-D3>500m % (Negative Fare Shock),D1-D3<-500m% (Positive Fare Shock),No Fare Shock,< -20,-20 to -15,-15 to -10,-10 to -5,-5 to -2,-2 to -1,-1 to -0.5,-0.5 to -0.2,-0.2 to 0,0,0 to 0.2,0.2 to 0.5,0.5 to 1,1 to 2,2 to 5,5 to 10,10 to 15,15 to 20,>20,distance_type
0,Bangalore,Auto,post,2024-05-022024-05-06,756629,15.962,7.606,76.433,0.000,0.000,0.000,0.002,0.011,0.024,0.038,0.061,0.144,0.001,0.398,0.160,0.089,0.045,0.020,0.004,0.001,0.000,0.000,second_longest
1,Bangalore,Auto,pre,2024-04-252024-05-01,970392,13.567,9.273,77.161,0.000,0.000,0.000,0.002,0.013,0.029,0.047,0.074,0.158,0.001,0.384,0.155,0.080,0.038,0.014,0.002,0.001,0.000,0.000,second_longest
0,Bangalore,CabEconomy,post,2024-05-022024-05-06,122884,15.883,14.990,69.127,0.001,0.001,0.001,0.007,0.031,0.048,0.061,0.080,0.152,0.001,0.319,0.139,0.075,0.044,0.026,0.007,0.003,0.002,0.002,second_longest
1,Bangalore,CabEconomy,pre,2024-04-252024-05-01,153704,14.578,18.763,66.659,0.000,0.001,0.002,0.010,0.041,0.059,0.074,0.090,0.150,0.001,0.293,0.133,0.073,0.043,0.020,0.005,0.002,0.001,0.001,second_longest

In [124]:
total_df_second_longest1.head(10)

,city_name,cluster_route,service_name,new_date_type,_col4,orders_count,D1-D3>500m % (Negative Fare Shock),D1-D3<-500m% (Positive Fare Shock),No Fare Shock,< -20,-20 to -15,-15 to -10,-10 to -5,-5 to -2,-2 to -1,-1 to -0.5,-0.5 to -0.2,-0.2 to 0,0,0 to 0.2,0.2 to 0.5,0.5 to 1,1 to 2,2 to 5,5 to 10,10 to 15,15 to 20,>20,distance_type
0,Bangalore,Singasandra Lake to Koramangala 3rd Block,Auto,pre,2024-04-252024-04-25,1,0.000,0.000,100.000,0.0,0.0,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.000,1.000,0.000,0.000,0.000,0.00,0.0,0.0,0.0,second_longest
1,Bangalore,Kathriguppe to Gattigere,Auto,pre,2024-04-252024-05-01,177,11.864,12.994,75.141,0.0,0.0,0.0,0.000,0.011,0.056,0.062,0.107,0.147,0.0,0.333,0.164,0.085,0.023,0.011,0.00,0.0,0.0,0.0,second_longest
2,Bangalore,Garvebhavipalya Lake to Majestic,Auto,pre,2024-04-252024-05-01,98,18.367,8.163,73.469,0.0,0.0,0.0,0.000,0.010,0.010,0.061,0.092,0.122,0.0,0.255,0.265,0.133,0.031,0.010,0.01,0.0,0.0,0.0,second_longest
3,Bangalore,Kathriguppe to Subramanyapura,Auto,pre,2024-04-252024-05-01,295,12.542,6.780,80.678,0.0,0.0,0.0,0.000,0.017,0.014,0.037,0.098,0.176,0.0,0.414,0.119,0.105,0.017,0.003,0.00,0.0,0.0,0.0,second_longest
4,Bangalore,Marathahalli Ring Road Junc to Munnekollal,Auto,pre,2024-04-252024-05-01,285,9.474,2.456,88.070,0.0,0.0,0.0,0.000,0.004,0.007,0.014,0.049,0.182,0.0,0.551,0.098,0.035,0.035,0.025,0.00,0.0,0.0,0.0,second_longest
5,Bangalore,Sampagni Rama Nagar to Jakkur,Auto,pre,2024-04-252024-04-30,15,13.333,0.000,86.667,0.0,0.0,0.0,0.000,0.000,0.000,0.000,0.133,0.133,0.0,0.400,0.200,0.067,0.067,0.000,0.00,0.0,0.0,0.0,second_longest
6,Bangalore,Koramangala 5th Block to Ejipura,Auto,pre,2024-04-252024-05-01,253,4.348,1.186,94.466,0.0,0.0,0.0,0.000,0.000,0.000,0.012,0.047,0.249,0.0,0.522,0.126,0.032,0.012,0.000,0.00,0.0,0.0,0.0,second_longest
7,Bangalore,Hongasandra to Kudlu Gate,Auto,post,2024-05-022024-05-06,67,5.970,4.478,89.552,0.0,0.0,0.0,0.000,0.015,0.000,0.030,0.045,0.164,0.0,0.567,0.119,0.015,0.045,0.000,0.00,0.0,0.0,0.0,second_longest
8,Bangalore,RTO Rajajinagar to Yelahanka New Town,Auto,pre,2024-04-252024-05-01,64,9.375,17.188,73.438,0.0,0.0,0.0,0.016,0.016,0.094,0.047,0.156,0.047,0.0,0.344,0.188,0.047,0.047,0.000,0.00,0.0,0.0,0.0,second_longest
9,Bangalore,Banashankri South to Banashankri,Auto,post,2024-05-022024-05-06,194,11.340,7.216,81.443,0.0,0.0,0.0,0.000,0.000,0.036,0.036,0.103,0.160,0.0,0.397,0.155,0.088,0.026,0.000,0.00,0.0,0.0,0.0,second_longest

In [119]:
total_df_second_longest.head(10)

,city_name,service_name,new_date_type,_col3,orders_count,D1-D3>500m % (Negative Fare Shock),D1-D3<-500m% (Positive Fare Shock),No Fare Shock,< -20,-20 to -15,-15 to -10,-10 to -5,-5 to -2,-2 to -1,-1 to -0.5,-0.5 to -0.2,-0.2 to 0,0,0 to 0.2,0.2 to 0.5,0.5 to 1,1 to 2,2 to 5,5 to 10,10 to 15,15 to 20,>20,distance_type
0,Bangalore,Auto,post,2024-05-022024-05-06,756629,15.962,7.606,76.433,0.000,0.000,0.000,0.002,0.011,0.024,0.038,0.061,0.144,0.001,0.398,0.160,0.089,0.045,0.020,0.004,0.001,0.000,0.000,second_longest
1,Bangalore,Auto,pre,2024-04-252024-05-01,970392,13.567,9.273,77.161,0.000,0.000,0.000,0.002,0.013,0.029,0.047,0.074,0.158,0.001,0.384,0.155,0.080,0.038,0.014,0.002,0.001,0.000,0.000,second_longest
0,Bangalore,CabEconomy,post,2024-05-022024-05-06,122884,15.883,14.990,69.127,0.001,0.001,0.001,0.007,0.031,0.048,0.061,0.080,0.152,0.001,0.319,0.139,0.075,0.044,0.026,0.007,0.003,0.002,0.002,second_longest
1,Bangalore,CabEconomy,pre,2024-04-252024-05-01,153704,14.578,18.763,66.659,0.000,0.001,0.002,0.010,0.041,0.059,0.074,0.090,0.150,0.001,0.293,0.133,0.073,0.043,0.020,0.005,0.002,0.001,0.001,second_longest

In [106]:
total_df_second_longest[total_df_second_longest['cluster_route']=='BLR_Indiranagar to BLR_Indiranagar']

,city_name,cluster_route,service_name,new_date_type,_col4,orders_count,D1-D3>500m % (Negative Fare Shock),D1-D3<-500m% (Positive Fare Shock),No Fare Shock,< -20,-20 to -15,-15 to -10,-10 to -5,-5 to -2,-2 to -1,-1 to -0.5,-0.5 to -0.2,-0.2 to 0,0,0 to 0.2,0.2 to 0.5,0.5 to 1,1 to 2,2 to 5,5 to 10,10 to 15,15 to 20,>20,distance_type
5095,Bangalore,BLR_Indiranagar to BLR_Indiranagar,Auto,post,2024-05-022024-05-06,2304,4.688,1.476,93.837,0.0,0.0,0.0,0.0,0.002,0.001,0.011,0.039,0.188,0.001,0.545,0.166,0.038,0.007,0.001,0.000,0.000,0.0,0.000,second_longest
61318,Bangalore,BLR_Indiranagar to BLR_Indiranagar,Auto,pre,2024-04-252024-05-01,3005,4.326,1.265,94.409,0.0,0.0,0.0,0.0,0.000,0.003,0.009,0.046,0.221,0.003,0.537,0.138,0.036,0.004,0.001,0.001,0.000,0.0,0.000,second_longest
14279,Bangalore,BLR_Indiranagar to BLR_Indiranagar,CabEconomy,pre,2024-04-252024-05-01,66,4.545,1.515,93.939,0.0,0.0,0.0,0.0,0.000,0.000,0.015,0.076,0.333,0.000,0.455,0.076,0.000,0.015,0.000,0.015,0.000,0.0,0.015,second_longest
35234,Bangalore,BLR_Indiranagar to BLR_Indiranagar,CabEconomy,post,2024-05-022024-05-06,71,8.451,5.634,85.915,0.0,0.0,0.0,0.0,0.000,0.014,0.042,0.113,0.141,0.000,0.521,0.085,0.042,0.000,0.014,0.014,0.014,0.0,0.000,second_longest

In [103]:
total_df_second_longest.sort_values(by='orders_count',ascending=False).head(10)

,city_name,cluster_route,service_name,new_date_type,_col4,orders_count,D1-D3>500m % (Negative Fare Shock),D1-D3<-500m% (Positive Fare Shock),No Fare Shock,< -20,-20 to -15,-15 to -10,-10 to -5,-5 to -2,-2 to -1,-1 to -0.5,-0.5 to -0.2,-0.2 to 0,0,0 to 0.2,0.2 to 0.5,0.5 to 1,1 to 2,2 to 5,5 to 10,10 to 15,15 to 20,>20,distance_type
68888,Bangalore,Electronic City to Electronic City,Auto,pre,2024-04-252024-05-01,7879,11.385,4.036,84.579,0.0,0.0,0.0,0.000,0.002,0.010,0.029,0.051,0.155,0.001,0.464,0.176,0.084,0.024,0.004,0.000,0.001,0.001,0.0,second_longest
11577,Bangalore,Electronic City to Electronic City,Auto,post,2024-05-022024-05-06,5979,13.899,3.295,82.806,0.0,0.0,0.0,0.000,0.002,0.008,0.022,0.040,0.145,0.000,0.466,0.176,0.102,0.031,0.004,0.000,0.000,0.001,0.0,second_longest
30625,Bangalore,Horamavu to Horamavu,Auto,pre,2024-04-252024-05-01,3459,6.736,3.758,89.506,0.0,0.0,0.0,0.000,0.005,0.012,0.021,0.047,0.171,0.000,0.546,0.130,0.055,0.010,0.002,0.000,0.001,0.000,0.0,second_longest
41024,Bangalore,Majestic to Majestic,Auto,pre,2024-04-252024-05-01,3370,14.303,6.558,79.139,0.0,0.0,0.0,0.001,0.004,0.019,0.041,0.062,0.144,0.001,0.341,0.245,0.104,0.035,0.002,0.001,0.001,0.000,0.0,second_longest
61318,Bangalore,BLR_Indiranagar to BLR_Indiranagar,Auto,pre,2024-04-252024-05-01,3005,4.326,1.265,94.409,0.0,0.0,0.0,0.000,0.000,0.003,0.009,0.046,0.221,0.003,0.537,0.138,0.036,0.004,0.001,0.001,0.000,0.000,0.0,second_longest
14357,Bangalore,RTO Rajajinagar to RTO Rajajinagar,Auto,pre,2024-04-252024-05-01,2720,9.926,3.750,86.324,0.0,0.0,0.0,0.000,0.002,0.008,0.028,0.085,0.205,0.001,0.409,0.164,0.079,0.019,0.001,0.001,0.000,0.000,0.0,second_longest
21104,Bangalore,Horamavu to Horamavu,Auto,post,2024-05-022024-05-06,2710,8.266,3.727,88.007,0.0,0.0,0.0,0.000,0.004,0.007,0.026,0.038,0.147,0.000,0.565,0.129,0.062,0.017,0.002,0.001,0.000,0.000,0.0,second_longest
1306,Bangalore,Electronic City Phase 2 to Electronic City,Auto,pre,2024-04-252024-05-01,2687,13.063,5.471,81.466,0.0,0.0,0.0,0.000,0.005,0.015,0.035,0.060,0.156,0.000,0.443,0.156,0.065,0.047,0.017,0.000,0.000,0.001,0.0,second_longest
40685,Bangalore,Majestic to Majestic,Auto,post,2024-05-022024-05-06,2666,17.442,5.064,77.494,0.0,0.0,0.0,0.001,0.003,0.015,0.031,0.058,0.132,0.000,0.333,0.251,0.122,0.046,0.003,0.002,0.001,0.000,0.0,second_longest
45568,Bangalore,Sarjapur Road to Sarjapur Road,Auto,pre,2024-04-252024-05-01,2418,9.098,3.433,87.469,0.0,0.0,0.0,0.001,0.002,0.013,0.018,0.029,0.130,0.000,0.547,0.168,0.065,0.020,0.004,0.001,0.000,0.000,0.0,second_longest

In [101]:
total_df_second_longest[total_df_second_longest['cluster_route']=='Tavarakere to Tavarakere']

,city_name,cluster_route,service_name,new_date_type,_col4,orders_count,D1-D3>500m % (Negative Fare Shock),D1-D3<-500m% (Positive Fare Shock),No Fare Shock,< -20,-20 to -15,-15 to -10,-10 to -5,-5 to -2,-2 to -1,-1 to -0.5,-0.5 to -0.2,-0.2 to 0,0,0 to 0.2,0.2 to 0.5,0.5 to 1,1 to 2,2 to 5,5 to 10,10 to 15,15 to 20,>20,distance_type
0,Bangalore,Tavarakere to Tavarakere,Auto,pre,2024-04-252024-05-01,2012,10.239,1.889,87.873,0.0,0.0,0.0,0.0,0.0,0.003,0.015,0.027,0.172,0.000,0.518,0.161,0.080,0.020,0.002,0.0,0.0,0.00,0.0,second_longest
76033,Bangalore,Tavarakere to Tavarakere,Auto,post,2024-05-022024-05-06,1834,8.724,1.145,90.131,0.0,0.0,0.0,0.0,0.0,0.006,0.005,0.025,0.146,0.001,0.539,0.191,0.059,0.027,0.001,0.0,0.0,0.00,0.0,second_longest
7264,Bangalore,Tavarakere to Tavarakere,CabEconomy,post,2024-05-022024-05-06,20,10.000,5.000,85.000,0.0,0.0,0.0,0.0,0.0,0.000,0.050,0.150,0.250,0.000,0.350,0.100,0.050,0.000,0.000,0.0,0.0,0.05,0.0,second_longest
50637,Bangalore,Tavarakere to Tavarakere,CabEconomy,pre,2024-04-272024-05-01,11,0.000,0.000,100.000,0.0,0.0,0.0,0.0,0.0,0.000,0.000,0.091,0.182,0.000,0.636,0.091,0.000,0.000,0.000,0.0,0.0,0.00,0.0,second_longest

In [100]:
total_df_second_longest.head(10)

,city_name,cluster_route,service_name,new_date_type,_col4,orders_count,D1-D3>500m % (Negative Fare Shock),D1-D3<-500m% (Positive Fare Shock),No Fare Shock,< -20,-20 to -15,-15 to -10,-10 to -5,-5 to -2,-2 to -1,-1 to -0.5,-0.5 to -0.2,-0.2 to 0,0,0 to 0.2,0.2 to 0.5,0.5 to 1,1 to 2,2 to 5,5 to 10,10 to 15,15 to 20,>20,distance_type
0,Bangalore,Tavarakere to Tavarakere,Auto,pre,2024-04-252024-05-01,2012,10.239,1.889,87.873,0.0,0.0,0.0,0.000,0.000,0.003,0.015,0.027,0.172,0.000,0.518,0.161,0.080,0.020,0.002,0.0,0.0,0.0,0.0,second_longest
1,Bangalore,Chanasandra to Kadugodi Forest,Auto,pre,2024-04-252024-05-01,455,1.319,1.758,96.923,0.0,0.0,0.0,0.000,0.000,0.002,0.015,0.057,0.198,0.000,0.598,0.116,0.011,0.002,0.000,0.0,0.0,0.0,0.0,second_longest
2,Bangalore,Metro - MG Road to RTO Rajajinagar,Auto,pre,2024-04-252024-05-01,33,18.182,6.061,75.758,0.0,0.0,0.0,0.000,0.000,0.030,0.030,0.061,0.091,0.000,0.485,0.121,0.121,0.030,0.030,0.0,0.0,0.0,0.0,second_longest
3,Bangalore,Agara Lake to Nagarbhavi,Auto,post,2024-05-052024-05-05,1,0.000,0.000,100.000,0.0,0.0,0.0,0.000,0.000,0.000,0.000,0.000,1.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.0,0.0,0.0,second_longest
4,Bangalore,Peenya 2nd Stage to Banashankri North,Auto,post,2024-05-022024-05-06,40,20.000,12.500,67.500,0.0,0.0,0.0,0.000,0.000,0.050,0.075,0.075,0.200,0.025,0.300,0.075,0.075,0.075,0.050,0.0,0.0,0.0,0.0,second_longest
5,Bangalore,Peenya to Dasarahalli,Auto,pre,2024-04-252024-05-01,321,19.938,4.673,75.389,0.0,0.0,0.0,0.003,0.006,0.012,0.025,0.062,0.218,0.000,0.333,0.140,0.109,0.081,0.009,0.0,0.0,0.0,0.0,second_longest
6,Bangalore,Gottigere to Hsr,Auto,pre,2024-04-252024-05-01,28,7.143,10.714,82.143,0.0,0.0,0.0,0.000,0.000,0.036,0.071,0.036,0.286,0.000,0.357,0.143,0.071,0.000,0.000,0.0,0.0,0.0,0.0,second_longest
7,Bangalore,Hulimavu to Arekere Lake,Auto,post,2024-05-022024-05-06,40,5.000,0.000,95.000,0.0,0.0,0.0,0.000,0.000,0.000,0.000,0.075,0.200,0.000,0.525,0.150,0.050,0.000,0.000,0.0,0.0,0.0,0.0,second_longest
8,Bangalore,BLR_Ashok Nagar to ShivajiNagar - Bangalore,Auto,post,2024-05-022024-05-06,65,10.769,0.000,89.231,0.0,0.0,0.0,0.000,0.000,0.000,0.000,0.015,0.108,0.000,0.615,0.154,0.046,0.062,0.000,0.0,0.0,0.0,0.0,second_longest
9,Bangalore,Arekere Extension to Bannerghatta Road - Hulimavu,Auto,pre,2024-04-252024-05-01,133,5.263,3.008,91.729,0.0,0.0,0.0,0.000,0.000,0.015,0.015,0.015,0.120,0.000,0.602,0.180,0.045,0.008,0.000,0.0,0.0,0.0,0.0,second_longest

In [157]:
city_name = 'Bangalore'
start_date='2024-04-25'
end_date='2024-05-05'
service_name='CabEconomy'

In [158]:
check_app=f"""WITH service_mapping AS ( 
            SELECT 
                service_detail_id,
                service_level as service_name,
                service_category,
                service_id,
                city_display_name as city,
                city_id
            FROM 
                datasets.service_mapping
            WHERE 
                city_display_name='{city_name}'
                and service_level='{service_name}'
        ),
        
        fe_tbl as (
                SELECT
                    fare_estimate_id fid,
                    api_context,final_amount as final_amount_fare,
                    date_format(from_unixtime(epoch / 1000, 'Asia/Kolkata'), '%Y-%m-%d') AS order_date,
                    cast(final_amount AS double) AS fe_amount,service_detail_id as service_id_fare,
                    epoch fe,ride_distance as d1, estimated_ride_time as t1
                FROM
                    pricing.fare_estimates_enriched 
                WHERE 
                yyyymmdd BETWEEN DATE_FORMAT(date('{start_date}'),'%Y%m%d') 
                AND DATE_FORMAT(date('{end_date}'),'%Y%m%d')
                   
        ),
        orderlogs as 
        (SELECT *,u.id_array as fare_estimate_id
        FROM 
        ( SELECT order_id, (amount-prev_due) as order_amount,customer_id,captain_id,
                 date_format(from_unixtime(epoch / 1000, 'Asia/Kolkata'), '%Y-%m-%d') AS orderdate,
                 epoch,estimate_id,estimate_ids,ride_time as t3,
                 fare_recalculated_reason, all_paths,
                 
                 spd_fraud_flag,order_status,
                 service_obj_service_name as service_name,
                 fare_recalculated_diff_amount AS fe_re_diff_amount,service_detail_id,
                 cast(json_parse(estimate_ids) as array<varchar>) AS id_array
          FROM orders.order_logs_snapshot
                WHERE 
                yyyymmdd BETWEEN DATE_FORMAT(date('{start_date}'),'%Y%m%d') 
                AND DATE_FORMAT(date('{end_date}'),'%Y%m%d')
                AND city_name IN (SELECT city FROM service_mapping)
                AND service_obj_service_name IN (SELECT service_name FROM service_mapping)) as t
        CROSS JOIN UNNEST(t.id_array) AS u(id_array)),
        immutable AS (
            SELECT 
                DATE_FORMAT(DATE_PARSE(yyyymmdd, '%Y%m%d'), '%Y-%m-%d') orderdate,
                order_id,
                cast (event_time as double) event_time
            FROM 
                orders.order_logs_immutable 
                 WHERE 
                yyyymmdd BETWEEN DATE_FORMAT(date('{start_date}'),'%Y%m%d') 
                AND DATE_FORMAT(date('{end_date}'),'%Y%m%d')
                AND event_type = 'started'
                AND city_name IN (SELECT city FROM service_mapping)
                AND service_obj_service_name IN (SELECT service_name FROM service_mapping)
        ),
        
        nav_metrics AS 
        (
            SELECT 
                event_props_order_id,device_info_app_version as app_version_type,
                event_props_user_id as user_id,
                -- case when device_info_app_version>='5.3.22' then 'Above 5.3.22' else 'Below 5.3.22' end as app_version_type,
                cast  (event_props_epoch as double) event_props_epoch,
                DATE_FORMAT(DATE_PARSE(yyyymmdd, '%Y%m%d'), '%Y-%m-%d') orderdate,
                try(cast(event_props_distance_in_meters as double) )/ 1000 d2
            FROM
                clevertap.captain_inappnavmetrics_immutable
                 WHERE 
                 yyyymmdd BETWEEN DATE_FORMAT(date('{start_date}'),'%Y%m%d') 
                AND DATE_FORMAT(date('{end_date}'),'%Y%m%d') 
                AND event_props_order_status = 'started'
        )
       select app_version_type,orderdate,(count(distinct case when order_status='dropped' and spd_fraud_flag!=True then order_id end)*100.00)/count(distinct order_id) from (
        select o.order_id,app_version_type,o.orderdate,event_props_order_id,user_id,order_status,spd_fraud_flag
        from orderlogs o left join nav_metrics n on o.order_id=n.event_props_order_id or o.captain_id=n.user_id
        )
        group by 1,2"""

In [159]:
check_app_df=pd.read_sql(check_app,connection3)

KeyboardInterrupt: