In [1]:
import numpy as np
import pandas as pd
from pyhive import presto
from datetime import timedelta,datetime
import json
import requests
import math
import os


pd.set_option('display.max_columns', None)
import warnings
warnings.filterwarnings("ignore")
conn = presto.connect(
        host="presto-gateway.serving.data.plectrum.dev",
        port=80,
        username="manoj.ravirajan@rapido.bike"
    )
presto_port = '80'
username = 'manoj.ravirajan@rapido.bike'
conn1 = presto.connect('bi-presto.serving.data.production.internal', presto_port, username)
conn2 = presto.connect('bi-trino-2.serving.data.production.internal', presto_port, username)
conn3= presto.connect('processing-2.processing.data.production.internal',presto_port,username)
conn4= presto.connect('processing.processing.data.production.internal',presto_port,username)

In [3]:
rf_daily_df = pd.read_sql(f"""select * from hive.experiments_internal.rf_daily_30days_20250317""", conn2)

In [4]:
# olf_g2n_df = pd.read_sql(f"""select * from hive.experiments_internal.olf_g2n_30days_20250317""", conn3)
olf_g2n_df = pd.read_sql(f"""select * from hive.experiments_internal.olf_g2n_30days_20250317_v1""", conn2)

In [5]:
# rha_qc_segment_df = pd.read_sql(f"""select * from hive.experiments_internal.rha_qc_segment_20250406""", conn3)
rha_qc_segment_df = pd.read_sql(f"""select * from hive.experiments_internal.rha_qc_usecase_segment_20250406""", conn2)

In [6]:
olf_geo_usecase_df = pd.read_sql(f"""select * from hive.experiments_internal.olf_geo_usecase_20250317""", conn2)

In [7]:
merged_df = rha_qc_segment_df.merge(olf_g2n_df, on = 'customer_id', how='left')
merged_df = merged_df.merge(rf_daily_df, on = 'customer_id', how='left')
merged_df = merged_df.merge(olf_geo_usecase_df, on = 'customer_id', how='left')
merged_df.head()

,customer_id,segment,office_tag,os,travelridehailing,quick_commerce,rr_count,net_count,cobrm_count,cobra_count,ocara_count,canceltn_count,quick_cobra,quick_ocara,cobra_ttc,ocara_ttc,expired_count,aborted_count,haps_orders,bid_orders,negative_bid,positive_bid,gross_psm_gps,gross_psm_fav_recent_history,gross_psm_google_search,gross_psm_stickylocation,gross_psm_hotspot,net_psm_gps,net_psm_fav_recent_history,net_psm_google_search,net_psm_fav_stickylocation,net_psm_hotspot,ao_session,fe_session,rr_session,office_gross,transit_gross,office_net,transit_net
0,62e118454a9e687fb3ffa869,4-OTHER,other,Android,yes,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,,,NaN,NaN,NaN,NaN
1,65cab07e2b682d8cacc3511f,3-MONTHLY,office,Android,yes,yes,2,2,0,0,0,0,0,0,,,0,0,1,0,0,0,1,0,0,0,1,1,0,0,0,1,6.0,6.0,2.0,0,0,0,0
2,5d975d91941a7d1c51d4baab,2-WEEKLY,office,Android,yes,yes,54,43,0,6,5,11,3,1,70.16666666666667,227.0,0,0,37,8,0,8,37,0,0,3,6,29,0,0,3,4,45.0,38.0,40.0,0,11,0,6
3,67223f7b312bc65a84986978,3-MONTHLY,other,Android,yes,yes,3,3,0,0,0,0,0,0,,,0,0,2,0,0,0,3,0,0,0,0,3,0,0,0,0,3.0,3.0,3.0,0,0,0,0
4,62aeac6790c7986dbdb02877,3-MONTHLY,office,Android,yes,yes,21,8,0,5,7,12,0,0,113.2,487.7142857142857,1,0,6,0,0,0,3,0,0,0,2,1,0,0,0,0,16.0,14.0,14.0,6,0,2,0

In [8]:
merged_df.to_parquet('merged_df.parquet')

In [9]:
# rpc = net rides/net customers
# cobrm/cobra/ocara/quick_cobra/quick_ocara/(expired_count+aborted_count) % = (cobrm/cobra/ocara/quick_cobra/quick_ocara/(expired_count+aborted_count))/rr
# haps% = haps_orders/net_orders
# haps% = haps_orders/net_orders

# positive_bid% = positive_bid/bid_orders
# negative_bid% = negative_bid/bid_orders

#gross_psm_google_search% = gross_psm_google_search/rr
#net_psm_google_search% = net_psm_google_search/rr

#a02fe = fe_session/ao_session
#fe2rr = 
#ao2rr = 
#g2n = net_count/rr_count

#office_gross% = office_gross/rr
#transit_gross% = transit_gross/rr

#office_net% = office_net/rr
#transit_net% = transit_net/rr

In [26]:
merged_df = pd.read_parquet('merged_df.parquet')

In [27]:
merged_df.shape

(4929725, 39)

In [32]:
merged_df = merged_df[~merged_df['os'].isin(['Blank'])]

In [33]:
merged_df.customer_id.nunique()

4727191

In [34]:
merged_df.columns

Index(['customer_id', 'segment', 'office_tag', 'os', 'travelridehailing',
       'quick_commerce', 'rr_count', 'net_count', 'cobrm_count', 'cobra_count',
       'ocara_count', 'canceltn_count', 'quick_cobra', 'quick_ocara',
       'cobra_ttc', 'ocara_ttc', 'expired_count', 'aborted_count',
       'haps_orders', 'bid_orders', 'negative_bid', 'positive_bid',
       'gross_psm_gps', 'gross_psm_fav_recent_history',
       'gross_psm_google_search', 'gross_psm_stickylocation',
       'gross_psm_hotspot', 'net_psm_gps', 'net_psm_fav_recent_history',
       'net_psm_google_search', 'net_psm_fav_stickylocation',
       'net_psm_hotspot', 'ao_session', 'fe_session', 'rr_session',
       'office_gross', 'transit_gross', 'office_net', 'transit_net'],
      dtype='object')

In [35]:
merged_df.rename(columns={'net_psm_fav_stickylocation':'net_psm_stickylocation'}, inplace=True)

In [36]:
cols_to_convert = [  'rr_count', 'net_count', 'cobrm_count', 'cobra_count', 'ocara_count',
       'canceltn_count', 'quick_cobra', 'quick_ocara', 'cobra_ttc',
       'ocara_ttc', 'expired_count', 'aborted_count', 'haps_orders',
       'bid_orders', 'negative_bid', 'positive_bid', 'gross_psm_gps',
       'gross_psm_fav_recent_history', 'gross_psm_google_search', 'gross_psm_stickylocation', 'gross_psm_hotspot',
       'net_psm_gps', 'net_psm_fav_recent_history', 'net_psm_google_search', 'net_psm_stickylocation', 'net_psm_hotspot',
       'ao_session', 'fe_session', 'rr_session', 'office_gross',
       'transit_gross', 'office_net', 'transit_net']

for col in cols_to_convert:
    merged_df[col] = pd.to_numeric(merged_df[col], errors='coerce')

In [37]:
# cobra_ttc	ocara_ttc

In [38]:
merged_df['net_customers'] = merged_df['net_count'].apply(lambda x: 1 if x>0 else 0)
merged_df['gross_customers'] = merged_df['rr_count'].apply(lambda x: 1 if x>0 else 0)

In [39]:
def agg_func(col):
    
    grouper = col
    print(grouper)
    
    segment_agg_df = merged_df\
    .groupby(grouper)\
    .agg(
         gross_customers = ('gross_customers', 'sum'),
         net_customers = ('net_customers', 'sum'),
         
         ao_session = ('ao_session', 'sum'),
         fe_session = ('fe_session', 'sum'),
         rr_session = ('rr_session', 'sum'),

         rr_count = ('rr_count', 'sum'),
         net_count = ('net_count', 'sum'),
         cobrm_count = ('cobrm_count', 'sum'),
         cobra_count = ('cobra_count', 'sum'),
         ocara_count = ('ocara_count', 'sum'),
         expired_count = ('expired_count', 'sum'),
         aborted_count = ('aborted_count', 'sum'),
         canceltn_count = ('canceltn_count', 'sum'),
        
         quick_cobra = ('quick_cobra', 'sum'),
         quick_ocara = ('quick_ocara', 'sum'),
         
         cobra_ttc_mean = ('cobra_ttc', 'mean'),
         cobra_ttc_p50 = ('cobra_ttc', 'median'),
         cobra_ttc_p75=('cobra_ttc', lambda x: x.quantile(0.75)),
         cobra_ttc_p90=('cobra_ttc', lambda x: x.quantile(0.90)),
         cobra_ttc_p95=('cobra_ttc', lambda x: x.quantile(0.95)),
    
         ocara_ttc_mean = ('ocara_ttc', 'mean'),
         ocara_ttc_p50 = ('ocara_ttc', 'median'),
         ocara_ttc_p75=('ocara_ttc', lambda x: x.quantile(0.75)),
         ocara_ttc_p90=('ocara_ttc', lambda x: x.quantile(0.90)),
         ocara_ttc_p95=('ocara_ttc', lambda x: x.quantile(0.95)),
    
         haps_orders = ('haps_orders', 'sum'),
         bid_orders = ('bid_orders', 'sum'),
         negative_bid = ('negative_bid', 'sum'),
         positive_bid = ('positive_bid', 'sum'),
    
         gross_psm_gps = ('gross_psm_gps', 'sum'),
         gross_psm_fav_recent_history = ('gross_psm_fav_recent_history', 'sum'),
         gross_psm_google_search = ('gross_psm_google_search', 'sum'),
         gross_psm_stickylocation = ('gross_psm_stickylocation', 'sum'),
         gross_psm_hotspot = ('gross_psm_hotspot', 'sum'),
        
         net_psm_gps = ('net_psm_gps', 'sum'),
         net_psm_fav_recent_history = ('net_psm_fav_recent_history', 'sum'),
         net_psm_google_search = ('net_psm_google_search', 'sum'),
         net_psm_stickylocation = ('net_psm_stickylocation', 'sum'),
         net_psm_hotspot = ('net_psm_hotspot', 'sum'),
         
         office_gross = ('office_gross', 'sum'),
         transit_gross = ('transit_gross', 'sum'),
         office_net = ('office_net', 'sum'),
         transit_net = ('transit_net', 'sum'),
        )\
    .reset_index()\
    .sort_values(by=grouper, ascending=True)

    segment_agg_df['rpc'] = round(segment_agg_df['net_count']/segment_agg_df['net_customers'],2)

    segment_agg_df['a02fe'] = round(segment_agg_df['fe_session']*100/segment_agg_df['ao_session'],2)
    segment_agg_df['fe2rr'] = round(segment_agg_df['rr_session']*100/segment_agg_df['fe_session'],2)
    segment_agg_df['ao2rr'] = round(segment_agg_df['rr_session']*100/segment_agg_df['ao_session'],2)
    
    segment_agg_df['g2n'] = round(segment_agg_df['net_count']*100/segment_agg_df['rr_count'],2)
    segment_agg_df['haps%'] = round(segment_agg_df['haps_orders']*100/segment_agg_df['net_count'],2)

    # cobrm/cobra/ocara/quick_cobra/quick_ocara/(expired_count+aborted_count) % = (cobrm/cobra/ocara/quick_cobra/quick_ocara/(expired_count+aborted_count))/rr
    for col in ['cobrm_count','cobra_count','ocara_count']:
        segment_agg_df[col.split('_')[0]+'%'] = round(segment_agg_df[col]*100/segment_agg_df['rr_count'],2)
    
    for col in ['quick_cobra','quick_ocara']:
        segment_agg_df[col +'%'] = round(segment_agg_df[col]*100/segment_agg_df['rr_count'],2)
    
    segment_agg_df['expired%'] = round((segment_agg_df['expired_count'] + segment_agg_df['aborted_count'])*100/segment_agg_df['rr_count'],2)

    segment_agg_df['positive_bid%'] = round(segment_agg_df['positive_bid']*100/segment_agg_df['bid_orders'],2)
    segment_agg_df['negative_bid%'] = round(segment_agg_df['negative_bid']*100/segment_agg_df['bid_orders'],2)

    # 'gross_psm_gps','gross_psm_fav_recent_history', 'gross_psm_google_search', 'gross_psm_stickylocation', 'gross_psm_hotspot'
    for col in ['gross_psm_gps','gross_psm_fav_recent_history', 'gross_psm_google_search', 'gross_psm_stickylocation', 'gross_psm_hotspot']:
        segment_agg_df[col +'%'] = round(segment_agg_df[col]*100/segment_agg_df['rr_count'],2)
    # 'net_psm_gps','net_psm_fav_recent_history', 'net_psm_google_search', 'net_psm_fav_stickylocation', 'net_psm_hotspot'
    for col in ['net_psm_gps','net_psm_fav_recent_history', 'net_psm_google_search', 'net_psm_stickylocation', 'net_psm_hotspot']:
        segment_agg_df[col +'%'] = round(segment_agg_df[col]*100/segment_agg_df['net_count'],2)

    for col in ['office_gross','transit_gross']:
        segment_agg_df[col +'%'] = round(segment_agg_df[col]*100/segment_agg_df['rr_count'],2)

    for col in ['office_net','transit_net']:
        segment_agg_df[col +'%'] = round(segment_agg_df[col]*100/segment_agg_df['net_count'],2)

    return segment_agg_df

In [40]:
%%time
segment_agg_df = agg_func('segment')

segment
CPU times: user 2.32 s, sys: 472 ms, total: 2.79 s
Wall time: 2.83 s

In [41]:
# segment	os	travelridehailing	quick_commerce

In [42]:
%%time
segment_agg_df = agg_func(['segment'])

['segment']
CPU times: user 2.37 s, sys: 92.7 ms, total: 2.47 s
Wall time: 2.48 s

In [43]:
segment_agg_df

,segment,gross_customers,net_customers,ao_session,fe_session,rr_session,rr_count,net_count,cobrm_count,cobra_count,ocara_count,expired_count,aborted_count,canceltn_count,quick_cobra,quick_ocara,cobra_ttc_mean,cobra_ttc_p50,cobra_ttc_p75,cobra_ttc_p90,cobra_ttc_p95,ocara_ttc_mean,ocara_ttc_p50,ocara_ttc_p75,ocara_ttc_p90,ocara_ttc_p95,haps_orders,bid_orders,negative_bid,positive_bid,gross_psm_gps,gross_psm_fav_recent_history,gross_psm_google_search,gross_psm_stickylocation,gross_psm_hotspot,net_psm_gps,net_psm_fav_recent_history,net_psm_google_search,net_psm_stickylocation,net_psm_hotspot,office_gross,transit_gross,office_net,transit_net,rpc,a02fe,fe2rr,ao2rr,g2n,haps%,cobrm%,cobra%,ocara%,quick_cobra%,quick_ocara%,expired%,positive_bid%,negative_bid%,gross_psm_gps%,gross_psm_fav_recent_history%,gross_psm_google_search%,gross_psm_stickylocation%,gross_psm_hotspot%,net_psm_gps%,net_psm_fav_recent_history%,net_psm_google_search%,net_psm_stickylocation%,net_psm_hotspot%,office_gross%,transit_gross%,office_net%,transit_net%
0,1-DAILY,108794,108735,5518154.0,4132697.0,3664277.0,7185744.0,4390000.0,45581.0,1136316.0,1212460.0,398315.0,3037.0,2394357.0,170376.0,116458.0,119.734629,114.600000,148.916667,186.000000,214.600000,302.097945,259.714286,364.5,506.409586,626.500000,3480216.0,1836521.0,998236.0,838285.0,2491060.0,807033.0,553322.0,1124730.0,503604.0,1501823.0,503493.0,347600.0,689897.0,303567.0,1239133.0,302852.0,638465.0,168763.0,40.37,74.89,88.67,66.40,61.09,79.28,0.63,15.81,16.87,2.37,1.62,5.59,45.65,54.35,34.67,11.23,7.70,15.65,7.01,34.21,11.47,7.92,15.72,6.91,17.24,4.21,14.54,3.84
1,2-WEEKLY,296361,295982,6310806.0,4784936.0,3804192.0,7319640.0,4384895.0,54635.0,1199228.0,1233499.0,443511.0,3824.0,2487362.0,171810.0,103255.0,119.114419,110.571429,152.250000,200.333333,237.199091,328.508037,262.250000,402.0,602.000000,787.000000,3343613.0,1502824.0,764701.0,738123.0,2854741.0,621029.0,532462.0,1175038.0,529192.0,1694441.0,380817.0,325076.0,706976.0,312786.0,1316735.0,418296.0,656466.0,227661.0,14.81,75.82,79.50,60.28,59.91,76.25,0.75,16.38,16.85,2.35,1.41,6.11,49.12,50.88,39.00,8.48,7.27,16.05,7.23,38.64,8.68,7.41,16.12,7.13,17.99,5.71,14.97,5.19
2,3-MONTHLY,1955298,1826793,13963363.0,10902335.0,7219608.0,13860293.0,8438253.0,121771.0,2246016.0,2235856.0,807481.0,10808.0,4603643.0,292061.0,145875.0,118.866528,106.500000,156.500000,215.500000,257.000000,396.503502,282.000000,488.0,803.300000,1100.733333,6227068.0,2063309.0,849318.0,1213991.0,6465825.0,735854.0,826406.0,2087015.0,925269.0,3921724.0,454705.0,498862.0,1282868.0,556070.0,2151591.0,1092226.0,1130609.0,605715.0,4.62,78.08,66.22,51.70,60.88,73.80,0.88,16.20,16.13,2.11,1.05,5.90,58.84,41.16,46.65,5.31,5.96,15.06,6.68,46.48,5.39,5.91,15.20,6.59,15.52,7.88,13.40,7.18
3,4-OTHER,1016588,922236,5092674.0,3974463.0,2274186.0,3497380.0,2256447.0,34265.0,477536.0,520508.0,205097.0,3494.0,1032309.0,57513.0,28930.0,120.275495,106.333333,160.000000,224.000000,265.500000,471.819777,324.000000,585.0,986.000000,1367.325000,1613146.0,423092.0,145647.0,277445.0,1821826.0,100908.0,184206.0,511209.0,225328.0,1177883.0,62830.0,116002.0,332110.0,144876.0,505809.0,338669.0,294173.0,205081.0,2.45,78.04,57.22,44.66,64.52,71.49,0.98,13.65,14.88,1.64,0.83,5.96,65.58,34.42,52.09,2.89,5.27,14.62,6.44,52.20,2.78,5.14,14.72,6.42,14.46,9.68,13.04,9.09
4,5-INACTIVE,104390,95669,303452.0,271069.0,0.0,658628.0,411256.0,5174.0,106784.0,99830.0,35116.0,465.0,211788.0,13776.0,6754.0,119.095531,107.720779,157.000000,214.000000,254.666667,405.307243,286.500000,492.0,814.000000,1130.450000,308142.0,95962.0,47411.0,48551.0,304688.0,51145.0,45532.0,64281.0,41955.0,189657.0,31866.0,28258.0,40367.0,25820.0,93229.0,56385.0,51285.0,32234.0,4.30,89.33,0.00,0.00,62.44,74.93,0.79,16.21,15.16,2.09,1.03,5.40,50.59,49.41,46.26,7.77,6.91,9.76,6.37,46.12,7.75,6.87,9.82,6.28,14.16,8.56,12.47,7.84

In [34]:
segment_agg_df.to_clipboard(index=False)

In [35]:
segment_os = agg_func(['segment','os'])
segment_os

['segment', 'os']

,segment,os,gross_customers,net_customers,ao_session,fe_session,rr_session,rr_count,net_count,cobrm_count,cobra_count,ocara_count,expired_count,aborted_count,canceltn_count,quick_cobra,quick_ocara,cobra_ttc_mean,cobra_ttc_p50,cobra_ttc_p75,cobra_ttc_p90,cobra_ttc_p95,ocara_ttc_mean,ocara_ttc_p50,ocara_ttc_p75,ocara_ttc_p90,ocara_ttc_p95,haps_orders,bid_orders,negative_bid,positive_bid,gross_psm_gps,gross_psm_fav_recent_history,gross_psm_google_search,gross_psm_stickylocation,gross_psm_hotspot,net_psm_gps,net_psm_fav_recent_history,net_psm_google_search,net_psm_fav_stickylocation,net_psm_hotspot,office_gross,transit_gross,office_net,transit_net,rpc,a02fe,fe2rr,ao2rr,g2n,haps%,cobrm%,cobra%,ocara%,quick_cobra%,quick_ocara%,expired%,positive_bid%,negative_bid%,gross_psm_gps%,gross_psm_fav_recent_history%,gross_psm_google_search%,gross_psm_stickylocation%,gross_psm_hotspot%,net_psm_gps%,net_psm_fav_recent_history%,net_psm_google_search%,net_psm_fav_stickylocation%,net_psm_hotspot%,office_gross%,transit_gross%,office_net%,transit_net%
0,1-DAILY,android,78864,78805,3615143.0,2929731.0,2589457.0,5162198.0,3168403.0,34609.0,851123.0,833753.0,271935.0,2345.0,1719485.0,124614.0,78987.0,118.677288,113.636364,147.111111,183.00,210.800000,310.477442,265.000000,374.307904,524.666667,653.582353,2516896.0,1233462.0,684562.0,548900.0,1920907.0,708457.0,455732.0,567192.0,350249.0,1161041.0,441357.0,287518.0,347490.0,211951.0,819756.0,222041.0,427143.0,123483.0,40.21,81.04,88.39,71.63,61.38,79.44,0.67,16.49,16.15,2.41,1.53,5.31,44.50,55.50,37.21,13.72,8.83,10.99,6.78,36.64,13.93,9.07,10.97,6.69,15.88,4.30,13.48,3.90
1,1-DAILY,iOS,29978,29978,1904141.0,1203822.0,1075549.0,2024697.0,1222268.0,10978.0,285378.0,378941.0,126435.0,692.0,675297.0,45795.0,37500.0,122.466054,117.111111,154.000000,193.48,223.850000,280.194240,248.075000,339.786957,456.660000,557.000000,963869.0,603293.0,313753.0,289540.0,570502.0,98694.0,97654.0,557701.0,153443.0,340983.0,62207.0,60131.0,342515.0,91661.0,419524.0,80867.0,211401.0,45295.0,40.77,63.22,89.34,56.48,60.37,78.86,0.54,14.09,18.72,2.26,1.85,6.28,47.99,52.01,28.18,4.87,4.82,27.54,7.58,27.90,5.09,4.92,28.02,7.50,20.72,3.99,17.30,3.71
2,2-WEEKLY,android,224366,224040,4372641.0,3552586.0,2797929.0,5454522.0,3287295.0,43112.0,917942.0,890897.0,312169.0,3069.0,1851951.0,128170.0,73175.0,117.978379,109.666667,150.375000,197.40,233.279167,338.310111,268.666667,414.666667,624.500000,818.000000,2515578.0,1058177.0,541513.0,516664.0,2309658.0,545980.0,443506.0,616512.0,385109.0,1379152.0,334422.0,271750.0,371157.0,228364.0,899125.0,318809.0,453668.0,173247.0,14.67,81.25,78.76,63.99,60.27,76.52,0.79,16.83,16.33,2.35,1.34,5.78,48.83,51.17,42.34,10.01,8.13,11.30,7.06,41.95,10.17,8.27,11.29,6.95,16.48,5.84,13.80,5.27
3,2-WEEKLY,iOS,72000,71947,1939687.0,1233605.0,1007172.0,1865202.0,1097641.0,11523.0,281302.0,342621.0,131350.0,755.0,635446.0,43640.0,30081.0,122.602868,113.500000,158.000000,209.00,248.000000,298.935098,245.250000,366.000000,535.000000,686.755357,828060.0,444668.0,223199.0,221469.0,545089.0,75062.0,88958.0,558564.0,144099.0,315292.0,46400.0,53328.0,335841.0,84429.0,417632.0,99490.0,202808.0,54416.0,15.26,63.60,81.64,51.92,58.85,75.44,0.62,15.08,18.37,2.34,1.61,7.08,49.81,50.19,29.22,4.02,4.77,29.95,7.73,28.72,4.23,4.86,30.60,7.69,22.39,5.33,18.48,4.96
4,3-MONTHLY,android,1623602,1514751,10711019.0,8773456.0,5678659.0,11115782.0,6796901.0,102816.0,1817876.0,1764490.0,624391.0,9218.0,3685182.0,231326.0,111433.0,118.343401,106.000000,155.571429,214.00,256.000000,410.190648,292.000000,506.000000,832.000000,1139.000000,5025191.0,1567936.0,645524.0,922412.0,5627630.0,654481.0,709699.0,1220445.0,726043.0,3427776.0,404451.0,429813.0,752373.0,437382.0,1587405.0,901057.0,846191.0,499494.0,4.49,81.91,64.73,53.02,61.15,73.93,0.92,16.35,15.87,2.08,1.00,5.70,58.83,41.17,50.63,5.89,6.38,10.98,6.53,50.43,5.95,6.32,11.07,6.44,14.28,8.11,12.45,7.35
5,3-MONTHLY,iOS,362254,337455,3256439.0,2133522.0,1543665.0,2846794.0,1700523.0,19862.0,445704.0,489015.0,190021.0,1650.0,954581.0,62979.0,35796.0,121.218660,108.500000,160.750000,222.00,264.000000,339.451084,246.000000,417.000000,680.000000,922.000000,1244963.0,512619.0,208967.0,303652.0,871168.0,84998.0,122190.0,886151.0,208653.0,512793.0,52426.0,72193.0,542230.0,124167.0,582899.0,199738.0,293936.0,110806.0,5.04,65.52,72.35,47.40,59.73,73.21,0.70,15.66,17.18,2.21,1.26,6.73,59.24,40.76,30.60,2.99,4.29,31.13,7.33,30.16,3.08,4.25,31.89,7.30,20.48,7.02,17.29,6.52
6,4-OTHER,android,888743,806570,4135754.0,3343769.0,1854542.0,2949292.0,1909676.0,28782.0,400683.0,435486.0,171532.0,3105.0,864951.0,47158.0,22060.0,120.553368,106.750000,160.500000,224.00,265.000000,486.874165,336.000000,604.000000,1017.000000,1411.000000,1365914.0,340108.0,118227.0,221881.0,1657435.0,93287.0,167157.0,293169.0,193704.0,1073951.0,57996.0,105489.0,192285.0,124687.0,396256.0,297198.0,234329.0,180256.0,2.37,80.85,55.46,44.84,64.75,71.53,0.98,13.59,14.77,1.60,0.75,5.92,65.24,34.76,56.20,3.16,5.67,9.94,6.57,56.24,3.04,5.52,10.07,6.53,13.44,10.08,12.27,9.44
7,4-OTHER,iOS,158755,141234,957592.0,632662.0,420452.0,618196.0,390069.0,6325.0,87564.0,95920.0,37873.0,440.0,189809.0,11811.0,7814.0,119.020936,105.000000,160.000000,225.00,268.350000,387.028429,265.500000,477.787500,812.000000,1113.150000,277508.0,92483.0,29505.0,62978.0,187278.0,9330.0,20259.0,232347.0,38125.0,117832.0,5826.0,12455.0,149168.0,24271.0,121515.0,48524.0,66677.0,28877.0,2.76,66.07,66.46,43.91,63.10,71.14,1.02,14.16,15.52,1.91,1.26,6.20,68.10,31.90,30.29,1.51,3.28,37.58,6.17,30.21,1.49,3.19,38.24,6.22,19.66,7.85,17.09,7.40
8,5-INACTIVE,android,102718,94185,260706.0,241577.0,0.0,649774.0,406041.0,5149.0,105398.0,98226.0,34498.0,459.0,208773.0,13516.0,6639.0,119.145954,107.666667,156.854396,214.00,254.658333,405.850046,287.000000,492.416667,814.000000,1131.500000,304417.0,95805.0,47340.0,48465.0,303533.0,51121.0,45266.0,63946.0,41782.0,188951.0,31858.0,28091.0,40131.0,25708.0,91618.0,55672.0,50476.0,31854.0,4.31,92.66,0.00,0.00,62.49,74.97,0.79,16.22,15.12,2.08,1.02,5.38,50.59,49.41,46.71,7.87,6.97,9.84,6.43,46.53,7.85,6.92,9.88,6.33,14.10,8.57,12.43,7.85
9,5-INACTIVE,iOS,4686,4178,42846.0,30445.0,0.0,25560.0,15000.0,191.0,4381.0,4437.0,1533.0,18.0,9009.0,737.0,418.0,114.786407,107.500000,153.166667,212.00,251.000000,355.746798,249.200000,435.250000,727.000000,1010.500000,10998.0,2981.0,1484.0,1497.0,6319.0,527.0,648.0,4768.0,1086.0,3554.0,302.0,398.0,2923.0,656.0,4645.0,2086.0,2340.0,1122.0,3.59,71.06,0.00,0.00,58.69,73.32,0.75,17.14,17.36,2.88,1.64,6.07,50.22,49.78,24.72,2.06,2.54,18.65,4.25,23.69,2.01,2.65,19.49,4.37,18.17,8.16,15.60,7.48

In [44]:
segment_os = agg_func(['segment','os'])
segment_os

['segment', 'os']

,segment,os,gross_customers,net_customers,ao_session,fe_session,rr_session,rr_count,net_count,cobrm_count,cobra_count,ocara_count,expired_count,aborted_count,canceltn_count,quick_cobra,quick_ocara,cobra_ttc_mean,cobra_ttc_p50,cobra_ttc_p75,cobra_ttc_p90,cobra_ttc_p95,ocara_ttc_mean,ocara_ttc_p50,ocara_ttc_p75,ocara_ttc_p90,ocara_ttc_p95,haps_orders,bid_orders,negative_bid,positive_bid,gross_psm_gps,gross_psm_fav_recent_history,gross_psm_google_search,gross_psm_stickylocation,gross_psm_hotspot,net_psm_gps,net_psm_fav_recent_history,net_psm_google_search,net_psm_stickylocation,net_psm_hotspot,office_gross,transit_gross,office_net,transit_net,rpc,a02fe,fe2rr,ao2rr,g2n,haps%,cobrm%,cobra%,ocara%,quick_cobra%,quick_ocara%,expired%,positive_bid%,negative_bid%,gross_psm_gps%,gross_psm_fav_recent_history%,gross_psm_google_search%,gross_psm_stickylocation%,gross_psm_hotspot%,net_psm_gps%,net_psm_fav_recent_history%,net_psm_google_search%,net_psm_stickylocation%,net_psm_hotspot%,office_gross%,transit_gross%,office_net%,transit_net%
0,1-DAILY,Android,74038,73980,3315004.0,2734023.0,2415978.0,4828690.0,2970560.0,32809.0,798231.0,773316.0,251530.0,2215.0,1604356.0,116150.0,73129.0,118.684802,113.611111,147.106203,183.000000,210.436364,312.476452,266.352941,377.272727,528.500,658.181818,2359684.0,1140787.0,632010.0,508777.0,1825066.0,693950.0,439559.0,474847.0,328774.0,1104250.0,432515.0,277721.0,291789.0,199490.0,755262.0,207685.0,395835.0,115289.0,40.15,82.47,88.37,72.88,61.52,79.44,0.68,16.53,16.02,2.41,1.51,5.25,44.60,55.40,37.80,14.37,9.10,9.83,6.81,37.17,14.56,9.35,9.82,6.72,15.64,4.30,13.33,3.88
1,1-DAILY,iOS,34756,34755,2203150.0,1398674.0,1248299.0,2357054.0,1419440.0,12772.0,338085.0,439144.0,146785.0,822.0,790001.0,54226.0,43329.0,121.938812,116.714286,153.000000,192.500000,222.500000,280.205694,247.600000,339.320513,457.125,558.333333,1120532.0,695734.0,366226.0,329508.0,665994.0,113083.0,113763.0,649883.0,174830.0,397573.0,70978.0,69879.0,398108.0,104077.0,483871.0,95167.0,242630.0,53474.0,40.84,63.49,89.25,56.66,60.22,78.94,0.54,14.34,18.63,2.30,1.84,6.26,47.36,52.64,28.26,4.80,4.83,27.57,7.42,28.01,5.00,4.92,28.05,7.33,20.53,4.04,17.09,3.77
2,2-WEEKLY,Android,212794,212474,4068013.0,3352361.0,2639827.0,5156335.0,3114796.0,41018.0,867253.0,837555.0,292728.0,2948.0,1745826.0,120177.0,68520.0,118.016054,109.750000,150.416667,197.500000,233.500000,340.747059,270.428571,418.000000,629.500,825.000000,2384578.0,988595.0,502050.0,486545.0,2223723.0,536255.0,429568.0,525104.0,364173.0,1330223.0,328561.0,263804.0,317067.0,216361.0,835558.0,301367.0,423576.0,163893.0,14.66,82.41,78.75,64.89,60.41,76.56,0.80,16.82,16.24,2.33,1.33,5.73,49.22,50.78,43.13,10.40,8.33,10.18,7.06,42.71,10.55,8.47,10.18,6.95,16.20,5.84,13.60,5.26
3,2-WEEKLY,iOS,83567,83508,2242793.0,1432575.0,1164365.0,2163305.0,1270099.0,13617.0,331975.0,395944.0,150783.0,876.0,741536.0,51633.0,34735.0,121.847580,112.866667,157.000000,207.000000,246.000000,298.387840,245.000000,365.444444,534.500,686.425000,959035.0,514229.0,262651.0,251578.0,631018.0,84774.0,102894.0,649934.0,165019.0,364218.0,52256.0,61272.0,389909.0,96425.0,481177.0,116929.0,232890.0,63768.0,15.21,63.87,81.28,51.92,58.71,75.51,0.63,15.35,18.30,2.39,1.61,7.01,48.92,51.08,29.17,3.92,4.76,30.04,7.63,28.68,4.11,4.82,30.70,7.59,22.24,5.41,18.34,5.02
4,3-MONTHLY,Android,1575811,1469487,10222027.0,8445132.0,5451598.0,10703240.0,6554320.0,99579.0,1746613.0,1694837.0,598830.0,8971.0,3541029.0,221214.0,106772.0,118.415497,106.000000,155.750000,214.000000,256.000000,412.738381,294.000000,509.000000,837.000,1146.000000,4846387.0,1493473.0,610269.0,883204.0,5507761.0,644306.0,693283.0,1082722.0,698213.0,3358392.0,398280.0,420405.0,669877.0,421123.0,1506816.0,869706.0,806163.0,482598.0,4.46,82.62,64.55,53.33,61.24,73.94,0.93,16.32,15.83,2.07,1.00,5.68,59.14,40.86,51.46,6.02,6.48,10.12,6.52,51.24,6.08,6.41,10.22,6.43,14.08,8.13,12.30,7.36
5,3-MONTHLY,iOS,379487,357306,3741336.0,2457203.0,1768010.0,3157053.0,1883933.0,22192.0,499403.0,541019.0,208651.0,1837.0,1062614.0,70847.0,39103.0,120.473348,108.000000,159.333333,220.000000,262.000000,337.915112,246.000000,415.000000,675.000,915.350000,1380681.0,569836.0,239049.0,330787.0,958064.0,91548.0,133123.0,1004293.0,227056.0,563332.0,56425.0,78457.0,612991.0,134947.0,644775.0,222520.0,324446.0,123117.0,5.27,65.68,71.95,47.26,59.67,73.29,0.70,15.82,17.14,2.24,1.24,6.67,58.05,41.95,30.35,2.90,4.22,31.81,7.19,29.90,3.00,4.16,32.54,7.16,20.42,7.05,17.22,6.54
6,4-OTHER,Android,877950,796898,4048529.0,3285054.0,1820755.0,2906137.0,1883246.0,29676.0,392584.0,429483.0,168043.0,3078.0,851743.0,46477.0,23747.0,120.450310,106.666667,160.500000,224.000000,265.000000,488.075070,337.000000,606.500000,1020.000,1415.433333,1347380.0,331509.0,114503.0,217006.0,1648929.0,92669.0,165578.0,268397.0,190794.0,1069142.0,57648.0,104555.0,176977.0,122985.0,386349.0,292504.0,229236.0,177503.0,2.36,81.14,55.43,44.97,64.80,71.55,1.02,13.51,14.78,1.60,0.82,5.89,65.46,34.54,56.74,3.19,5.70,9.24,6.57,56.77,3.06,5.55,9.40,6.53,13.29,10.07,12.17,9.43
7,4-OTHER,iOS,138638,125338,1044145.0,689409.0,453431.0,591243.0,373201.0,4589.0,84952.0,91025.0,37054.0,416.0,180566.0,11036.0,5183.0,119.412908,105.500000,159.225000,224.000000,267.000000,385.833433,268.611111,474.214286,795.000,1096.000000,265766.0,91583.0,31144.0,60439.0,172897.0,8239.0,18628.0,242812.0,34534.0,108741.0,5182.0,11447.0,155133.0,21891.0,119460.0,46165.0,64937.0,27578.0,2.98,66.03,65.77,43.43,63.12,71.21,0.78,14.37,15.40,1.87,0.88,6.34,65.99,34.01,29.24,1.39,3.15,41.07,5.84,29.14,1.39,3.07,41.57,5.87,20.20,7.81,17.40,7.39
8,5-INACTIVE,Android,102951,94384,268605.0,239168.0,0.0,650527.0,406501.0,5146.0,105539.0,98353.0,34525.0,460.0,209038.0,13530.0,6643.0,119.209227,107.875000,157.000000,214.000000,254.708333,405.879957,287.000000,492.575000,814.500,1131.750000,304738.0,95760.0,47297.0,48463.0,304250.0,51097.0,45496.0,63888.0,41852.0,189383.0,31840.0,28233.0,40094.0,25748.0,91731.0,55768.0,50537.0,31900.0,4.31,89.04,0.00,0.00,62.49,74.97,0.79,16.22,15.12,2.08,1.02,5.38,50.61,49.39,46.77,7.85,6.99,9.82,6.43,46.59,7.83,6.95,9.86,6.33,14.10,8.57,12.43,7.85
9,5-INACTIVE,iOS,1439,1285,34847.0,31901.0,0.0,8101.0,4755.0,28.0,1245.0,1477.0,591.0,5.0,2750.0,246.0,111.0,110.470643,104.000000,151.000000,209.833333,243.000000,365.270050,250.100000,439.500000,709.500,1027.000000,3404.0,202.0,114.0,88.0,438.0,48.0,36.0,393.0,103.0,274.0,26.0,25.0,273.0,72.0,1498.0,617.0,748.0,334.0,3.70,91.55,0.00,0.00,58.70,71.59,0.35,15.37,18.23,3.04,1.37,7.36,43.56,56.44,5.41,0.59,0.44,4.85,1.27,5.76,0.55,0.53,5.74,1.51,18.49,7.62,15.73,7.02

In [36]:
segment_os.to_clipboard(index=False)

In [37]:
segment_travel = agg_func(['segment','travelridehailing'])
segment_travel

['segment', 'travelridehailing']

,segment,travelridehailing,gross_customers,net_customers,ao_session,fe_session,rr_session,rr_count,net_count,cobrm_count,cobra_count,ocara_count,expired_count,aborted_count,canceltn_count,quick_cobra,quick_ocara,cobra_ttc_mean,cobra_ttc_p50,cobra_ttc_p75,cobra_ttc_p90,cobra_ttc_p95,ocara_ttc_mean,ocara_ttc_p50,ocara_ttc_p75,ocara_ttc_p90,ocara_ttc_p95,haps_orders,bid_orders,negative_bid,positive_bid,gross_psm_gps,gross_psm_fav_recent_history,gross_psm_google_search,gross_psm_stickylocation,gross_psm_hotspot,net_psm_gps,net_psm_fav_recent_history,net_psm_google_search,net_psm_fav_stickylocation,net_psm_hotspot,office_gross,transit_gross,office_net,transit_net,rpc,a02fe,fe2rr,ao2rr,g2n,haps%,cobrm%,cobra%,ocara%,quick_cobra%,quick_ocara%,expired%,positive_bid%,negative_bid%,gross_psm_gps%,gross_psm_fav_recent_history%,gross_psm_google_search%,gross_psm_stickylocation%,gross_psm_hotspot%,net_psm_gps%,net_psm_fav_recent_history%,net_psm_google_search%,net_psm_fav_stickylocation%,net_psm_hotspot%,office_gross%,transit_gross%,office_net%,transit_net%
0,1-DAILY,iOS,29978,29978,1904141.0,1203822.0,1075549.0,2024697.0,1222268.0,10978.0,285378.0,378941.0,126435.0,692.0,675297.0,45795.0,37500.0,122.466054,117.111111,154.000000,193.480000,223.850000,280.194240,248.075000,339.786957,456.660000,557.000000,963869.0,603293.0,313753.0,289540.0,570502.0,98694.0,97654.0,557701.0,153443.0,340983.0,62207.0,60131.0,342515.0,91661.0,419524.0,80867.0,211401.0,45295.0,40.77,63.22,89.34,56.48,60.37,78.86,0.54,14.09,18.72,2.26,1.85,6.28,47.99,52.01,28.18,4.87,4.82,27.54,7.58,27.90,5.09,4.92,28.02,7.50,20.72,3.99,17.30,3.71
1,1-DAILY,no,10614,10594,486846.0,382979.0,336764.0,681495.0,435682.0,4249.0,111792.0,102585.0,26767.0,417.0,218626.0,17512.0,9958.0,110.258570,104.000000,137.000000,174.000000,203.000000,352.086695,296.875000,429.000000,612.886364,769.613333,343363.0,117081.0,62299.0,54782.0,317847.0,78004.0,56239.0,63945.0,30845.0,199607.0,51891.0,37123.0,41419.0,19577.0,74797.0,27322.0,43045.0,15869.0,41.13,78.67,87.93,69.17,63.93,78.81,0.62,16.40,15.05,2.57,1.46,3.99,46.79,53.21,46.64,11.45,8.25,9.38,4.53,45.81,11.91,8.52,9.51,4.49,10.98,4.01,9.88,3.64
2,1-DAILY,yes,68250,68211,3128297.0,2546752.0,2252693.0,4480703.0,2732721.0,30360.0,739331.0,731168.0,245168.0,1928.0,1500859.0,107102.0,69029.0,119.930693,115.090909,148.333333,184.166667,211.735714,304.073969,260.642857,366.307692,510.011765,631.216667,2173533.0,1116381.0,622263.0,494118.0,1603060.0,630453.0,399493.0,503247.0,319404.0,961434.0,389466.0,250395.0,306071.0,192374.0,744959.0,194719.0,384098.0,107614.0,40.06,81.41,88.45,72.01,60.99,79.54,0.68,16.50,16.32,2.39,1.54,5.51,44.26,55.74,35.78,14.07,8.92,11.23,7.13,35.18,14.25,9.16,11.20,7.04,16.63,4.35,14.06,3.94
3,2-WEEKLY,iOS,72000,71947,1939687.0,1233605.0,1007172.0,1865202.0,1097641.0,11523.0,281302.0,342621.0,131350.0,755.0,635446.0,43640.0,30081.0,122.602868,113.500000,158.000000,209.000000,248.000000,298.935098,245.250000,366.000000,535.000000,686.755357,828060.0,444668.0,223199.0,221469.0,545089.0,75062.0,88958.0,558564.0,144099.0,315292.0,46400.0,53328.0,335841.0,84429.0,417632.0,99490.0,202808.0,54416.0,15.26,63.60,81.64,51.92,58.85,75.44,0.62,15.08,18.37,2.34,1.61,7.08,49.81,50.19,29.22,4.02,4.77,29.95,7.73,28.72,4.23,4.86,30.60,7.69,22.39,5.33,18.48,4.96
4,2-WEEKLY,no,37105,37032,707983.0,558549.0,431802.0,855354.0,538627.0,6674.0,139120.0,134148.0,36117.0,662.0,279942.0,19609.0,10685.0,109.787731,100.000000,140.000000,186.633333,222.000000,388.952414,306.333333,479.500000,723.000000,945.000000,407934.0,119342.0,54672.0,64670.0,440827.0,71612.0,61629.0,82871.0,41239.0,273535.0,46832.0,39800.0,53269.0,25559.0,88296.0,50564.0,50591.0,28059.0,14.54,78.89,77.31,60.99,62.97,75.74,0.78,16.26,15.68,2.29,1.25,4.30,54.19,45.81,51.54,8.37,7.21,9.69,4.82,50.78,8.69,7.39,9.89,4.75,10.32,5.91,9.39,5.21
5,2-WEEKLY,yes,187261,187008,3664658.0,2994037.0,2366127.0,4599168.0,2748668.0,36438.0,778822.0,756749.0,276052.0,2407.0,1572009.0,108561.0,62490.0,119.464861,111.461538,152.000000,199.000000,235.100000,328.520876,262.545455,402.750000,602.769444,788.262500,2107644.0,938835.0,486841.0,451994.0,1868831.0,474368.0,381877.0,533641.0,343870.0,1105617.0,287590.0,231950.0,317888.0,202805.0,810829.0,268245.0,403077.0,145188.0,14.70,81.70,79.03,64.57,59.76,76.68,0.79,16.93,16.45,2.36,1.36,6.05,48.14,51.86,40.63,10.31,8.30,11.60,7.48,40.22,10.46,8.44,11.57,7.38,17.63,5.83,14.66,5.28
6,3-MONTHLY,iOS,362254,337455,3256439.0,2133522.0,1543665.0,2846794.0,1700523.0,19862.0,445704.0,489015.0,190021.0,1650.0,954581.0,62979.0,35796.0,121.218660,108.500000,160.750000,222.000000,264.000000,339.451084,246.000000,417.000000,680.000000,922.000000,1244963.0,512619.0,208967.0,303652.0,871168.0,84998.0,122190.0,886151.0,208653.0,512793.0,52426.0,72193.0,542230.0,124167.0,582899.0,199738.0,293936.0,110806.0,5.04,65.52,72.35,47.40,59.73,73.21,0.70,15.66,17.18,2.21,1.26,6.73,59.24,40.76,30.60,2.99,4.29,31.13,7.33,30.16,3.08,4.25,31.89,7.30,20.48,7.02,17.29,6.52
7,3-MONTHLY,no,434244,408308,2782797.0,2212712.0,1360412.0,2728712.0,1711637.0,28317.0,409600.0,438501.0,137486.0,3150.0,876418.0,52011.0,24924.0,112.708058,100.133929,147.333333,204.000000,245.500000,474.713644,344.000000,590.000000,964.000000,1311.000000,1242427.0,300958.0,110989.0,189969.0,1633998.0,120736.0,140195.0,257679.0,132081.0,1019252.0,77472.0,87134.0,165855.0,81655.0,270809.0,236122.0,159388.0,132916.0,4.19,79.51,61.48,48.89,62.73,72.59,1.04,15.01,16.07,1.91,0.91,5.15,63.12,36.88,59.88,4.42,5.14,9.44,4.84,59.55,4.53,5.09,9.69,4.77,9.92,8.65,9.31,7.77
8,3-MONTHLY,yes,1189358,1106443,7928222.0,6560744.0,4318247.0,8387070.0,5085264.0,74499.0,1408276.0,1325989.0,486905.0,6068.0,2808764.0,179315.0,86509.0,119.993219,108.000000,158.000000,217.000000,258.000000,387.941736,276.800000,477.000000,782.333333,1072.000000,3782764.0,1266978.0,534535.0,732443.0,3993632.0,533745.0,569504.0,962766.0,593962.0,2408524.0,326979.0,342679.0,586518.0,355727.0,1316596.0,664935.0,686803.0,366578.0,4.60,82.75,65.82,54.47,60.63,74.39,0.89,16.79,15.81,2.14,1.03,5.88,57.81,42.19,47.62,6.36,6.79,11.48,7.08,47.36,6.43,6.74,11.53,7.00,15.70,7.93,13.51,7.21
9,4-OTHER,iOS,158755,141234,957592.0,632662.0,420452.0,618196.0,390069.0,6325.0,87564.0,95920.0,37873.0,440.0,189809.0,11811.0,7814.0,119.020936,105.000000,160.000000,225.000000,268.350000,387.028429,265.500000,477.787500,812.000000,1113.150000,277508.0,92483.0,29505.0,62978.0,187278.0,9330.0,20259.0,232347.0,38125.0,117832.0,5826.0,12455.0,149168.0,24271.0,121515.0,48524.0,66677.0,28877.0,2.76,66.07,66.46,43.91,63.10,71.14,1.02,14.16,15.52,1.91,1.26,6.20,68.10,31.90,30.29,1.51,3.28,37.58,6.17,30.21,1.49,3.19,38.24,6.22,19.66,7.85,17.09,7.40
10,4-OTHER,no,320941,299107,1528152.0,1192458.0,624622.0,1003015.0,663043.0,10268.0,119007.0,152969.0,56373.0,1346.0,282244.0,14674.0,7212.0,116.247329,102.000000,154.000000,217.000000,260.000000,543.769105,385.000000,682.000000,1132.000000,1555.000000,463077.0,96422.0,32583.0,63839.0,634321.0,22580.0,46160.0,88243.0,53011.0,419124.0,13965.0,29139.0,60124.0,35085.0,102536.0,113241.0,65825.0,70454.0,2.22,78.03,52.38,40.87,66.10,69.84,1.02,11.86,15.25,1.46,0.72,5.75,66.21,33.79,63.24,2.25,4.60,8.80,5.29,63.21,2.11,4.39,9.07,5.29,10.22,11.29,9.93,10.63
11,4-OTHER,yes,567802,507463,2607602.0,2151311.0,1229920.0,1946277.0,1246633.0,18514.0,281676.0,282517.0,115159.0,1759.0,582707.0,32484.0,14848.0,122.380038,108.833333,163.000000,226.500000,267.000000,455.480364,311.500000,561.000000,946.000000,1320.000000,902837.0,243686.0,85644.0,158042.0,1023114.0,70707.0,120997.0,204926.0,140693.0,654827.0,44031.0,76350.0,132161.0,89602.0,293720.0,183957.0,168504.0,109802.0,2.46,82.50,57.17,47.17,64.05,72.42,0.95,14.47,14.52,1.67,0.76,6.01,64.85,35.15,52.57,3.63,6.22,10.53,7.23,52.53,3.53,6.12,10.60,7.19,15.09,9.45,13.52,8.81
12,5-INACTIVE,iOS,4686,4178,42846.0,30445.0,0.0,25560.0,15000.0,191.0,4381.0,4437.0,1533.0,18.0,9009.0,737.0,418.0,114.786407,107.500000,153.166667,212.000000,251.000000,355.746798,249.200000,435.250000,727.000000,1010.500000,10998.0,2981.0,1484.0,1497.0,6319.0,527.0,648.0,4768.0,1086.0,3554.0,302.0,398.0,2923.0,656.0,4645.0,2086.0,2340.0,1122.0,3.59,71.06,0.00,0.00,58.69,73.32,0.75,17.14,17.36,2.88,1.64,6.07,50.22,49.78,24.72,2.06,2.54,18.65,4.25,23.69,2.01,2.65,19.49,4.37,18.17,8.16,15.60,7.48
13,5-INACTIVE,no,26011,24230,84419.0,75612.0,0.0,123923.0,79915.0,1126.0,18669.0,18387.0,5716.0,108.0,38182.0,2430.0,1151.0,113.366880,101.000000,148.000000,206.000000,247.000000,448.591913,325.000000,560.000000,914.600000,1244.800000,57571.0,13556.0,5280.0,8276.0,68672.0,6344.0,7278.0,11010.0,6500.0,44283.0,4082.0,4593.0,7245.0,4133.0,13059.0,12368.0,8099.0,7217.0,3.30,89.57,0.00,0.00,64.49,72.04,0.91,15.07,14.84,1.96,0.93,4.70,61.05,38.95,55.42,5.12,5.87,8.88,5.25,55.41,5.11,5.75,9.07,5.17,10.54,9.98,10.13,9.03
14,5-INACTIVE,yes,76707,69955,176287.0,165965.0,0.0,525851.0,326126.0,4023.0,86729.0,79839.0,28782.0,351.0,170591.0,11086.0,5488.0,120.559706,109.333333,158.666667,215.650000,256.000000,393.460219,277.666667,472.000000,781.321429,1087.000000,246846.0,82249.0,42060.0,40189.0,234861.0,44777.0,37988.0,52936.0,35282.0,144668.0,27776.0,23498.0,32886.0,21575.0,78559.0,43304.0,42377.0,24637.0,4.66,94.14,0.00,0.00,62.02,75.69,0.77,16.49,15.18,2.11,1.04,5.54,48.86,51.14,44.66,8.52,7.22,10.07,6.71,44.36,8.52,7.21,10.08,6.62,14.94,8.24,12.99,7.55

In [38]:
segment_travel.to_clipboard(index=False)

In [39]:
segment_qc = agg_func(['segment','quick_commerce'])
segment_qc

['segment', 'quick_commerce']

,segment,quick_commerce,gross_customers,net_customers,ao_session,fe_session,rr_session,rr_count,net_count,cobrm_count,cobra_count,ocara_count,expired_count,aborted_count,canceltn_count,quick_cobra,quick_ocara,cobra_ttc_mean,cobra_ttc_p50,cobra_ttc_p75,cobra_ttc_p90,cobra_ttc_p95,ocara_ttc_mean,ocara_ttc_p50,ocara_ttc_p75,ocara_ttc_p90,ocara_ttc_p95,haps_orders,bid_orders,negative_bid,positive_bid,gross_psm_gps,gross_psm_fav_recent_history,gross_psm_google_search,gross_psm_stickylocation,gross_psm_hotspot,net_psm_gps,net_psm_fav_recent_history,net_psm_google_search,net_psm_fav_stickylocation,net_psm_hotspot,office_gross,transit_gross,office_net,transit_net,rpc,a02fe,fe2rr,ao2rr,g2n,haps%,cobrm%,cobra%,ocara%,quick_cobra%,quick_ocara%,expired%,positive_bid%,negative_bid%,gross_psm_gps%,gross_psm_fav_recent_history%,gross_psm_google_search%,gross_psm_stickylocation%,gross_psm_hotspot%,net_psm_gps%,net_psm_fav_recent_history%,net_psm_google_search%,net_psm_fav_stickylocation%,net_psm_hotspot%,office_gross%,transit_gross%,office_net%,transit_net%
0,1-DAILY,iOS,29978,29978,1904141.0,1203822.0,1075549.0,2024697.0,1222268.0,10978.0,285378.0,378941.0,126435.0,692.0,675297.0,45795.0,37500.0,122.466054,117.111111,154.000000,193.480000,223.850000,280.194240,248.075000,339.786957,456.660000,557.000000,963869.0,603293.0,313753.0,289540.0,570502.0,98694.0,97654.0,557701.0,153443.0,340983.0,62207.0,60131.0,342515.0,91661.0,419524.0,80867.0,211401.0,45295.0,40.77,63.22,89.34,56.48,60.37,78.86,0.54,14.09,18.72,2.26,1.85,6.28,47.99,52.01,28.18,4.87,4.82,27.54,7.58,27.90,5.09,4.92,28.02,7.50,20.72,3.99,17.30,3.71
1,1-DAILY,no,10481,10451,505901.0,396333.0,335109.0,674950.0,422581.0,5101.0,110939.0,102398.0,33508.0,420.0,218438.0,16388.0,10904.0,117.214619,111.777778,145.578947,182.295238,213.183333,360.209471,303.475000,435.566176,624.950000,791.325000,333504.0,115168.0,72186.0,42982.0,321288.0,80325.0,52768.0,61442.0,31895.0,197449.0,53001.0,34360.0,38516.0,20065.0,69120.0,28529.0,38223.0,15992.0,40.43,78.34,84.55,66.24,62.61,78.92,0.76,16.44,15.17,2.43,1.62,5.03,37.32,62.68,47.60,11.90,7.82,9.10,4.73,46.72,12.54,8.13,9.11,4.75,10.24,4.23,9.05,3.78
2,1-DAILY,yes,68383,68354,3109242.0,2533398.0,2254348.0,4487248.0,2745822.0,29508.0,740184.0,731355.0,238427.0,1925.0,1501047.0,108226.0,68083.0,118.894281,114.000000,147.300000,183.100000,210.500000,302.939016,259.533937,365.102778,508.366667,627.926786,2183392.0,1118294.0,612376.0,505918.0,1599619.0,628132.0,402964.0,505750.0,318354.0,963592.0,388356.0,253158.0,308974.0,191886.0,750636.0,193512.0,388920.0,107491.0,40.17,81.48,88.99,72.50,61.19,79.52,0.66,16.50,16.30,2.41,1.52,5.36,45.24,54.76,35.65,14.00,8.98,11.27,7.09,35.09,14.14,9.22,11.25,6.99,16.73,4.31,14.16,3.91
3,2-WEEKLY,iOS,72000,71947,1939687.0,1233605.0,1007172.0,1865202.0,1097641.0,11523.0,281302.0,342621.0,131350.0,755.0,635446.0,43640.0,30081.0,122.602868,113.500000,158.000000,209.000000,248.000000,298.935098,245.250000,366.000000,535.000000,686.755357,828060.0,444668.0,223199.0,221469.0,545089.0,75062.0,88958.0,558564.0,144099.0,315292.0,46400.0,53328.0,335841.0,84429.0,417632.0,99490.0,202808.0,54416.0,15.26,63.60,81.64,51.92,58.85,75.44,0.62,15.08,18.37,2.34,1.61,7.08,49.81,50.19,29.22,4.02,4.77,29.95,7.73,28.72,4.23,4.86,30.60,7.69,22.39,5.33,18.48,4.96
4,2-WEEKLY,no,33833,33693,678759.0,535575.0,396823.0,780598.0,480303.0,7299.0,126836.0,124761.0,40708.0,687.0,258896.0,17177.0,12130.0,114.713111,105.750000,146.333333,193.750000,231.000000,398.830901,311.500000,489.857143,749.185714,987.200000,364031.0,104489.0,54257.0,50232.0,414911.0,65785.0,55590.0,73991.0,37870.0,253594.0,42011.0,34876.0,46378.0,22615.0,79586.0,47499.0,43165.0,25413.0,14.26,78.91,74.09,58.46,61.53,75.79,0.94,16.25,15.98,2.20,1.55,5.30,48.07,51.93,53.15,8.43,7.12,9.48,4.85,52.80,8.75,7.26,9.66,4.71,10.20,6.08,8.99,5.29
5,2-WEEKLY,yes,190533,190347,3693882.0,3017011.0,2401106.0,4673924.0,2806992.0,35813.0,791106.0,766136.0,271461.0,2382.0,1593055.0,110993.0,61045.0,118.519102,110.333333,151.000000,198.000000,234.000000,327.853331,262.250000,402.000000,602.000000,783.463889,2151547.0,953688.0,487256.0,466432.0,1894747.0,480195.0,387916.0,542521.0,347239.0,1125558.0,292411.0,236874.0,324779.0,205749.0,819539.0,271310.0,410503.0,147834.0,14.75,81.68,79.59,65.00,60.06,76.65,0.77,16.93,16.39,2.37,1.31,5.86,48.91,51.09,40.54,10.27,8.30,11.61,7.43,40.10,10.42,8.44,11.57,7.33,17.53,5.80,14.62,5.27
6,3-MONTHLY,iOS,362254,337455,3256439.0,2133522.0,1543665.0,2846794.0,1700523.0,19862.0,445704.0,489015.0,190021.0,1650.0,954581.0,62979.0,35796.0,121.218660,108.500000,160.750000,222.000000,264.000000,339.451084,246.000000,417.000000,680.000000,922.000000,1244963.0,512619.0,208967.0,303652.0,871168.0,84998.0,122190.0,886151.0,208653.0,512793.0,52426.0,72193.0,542230.0,124167.0,582899.0,199738.0,293936.0,110806.0,5.04,65.52,72.35,47.40,59.73,73.21,0.70,15.66,17.18,2.21,1.26,6.73,59.24,40.76,30.60,2.99,4.29,31.13,7.33,30.16,3.08,4.25,31.89,7.30,20.48,7.02,17.29,6.52
7,3-MONTHLY,no,390223,363266,2581423.0,2054292.0,1225631.0,2463614.0,1518070.0,28944.0,368308.0,400549.0,144634.0,3089.0,797801.0,44690.0,26704.0,116.440118,104.000000,153.000000,210.666667,251.500000,486.761654,350.000000,604.000000,993.000000,1360.525000,1103817.0,256399.0,104349.0,152050.0,1527243.0,106983.0,123635.0,224489.0,116303.0,939833.0,66993.0,75271.0,142034.0,69769.0,241747.0,218550.0,137562.0,120920.0,4.18,79.58,59.66,47.48,61.62,72.71,1.17,14.95,16.26,1.81,1.08,6.00,59.30,40.70,61.99,4.34,5.02,9.11,4.72,61.91,4.41,4.96,9.36,4.60,9.81,8.87,9.06,7.97
8,3-MONTHLY,yes,1233379,1151485,8129596.0,6719164.0,4453028.0,8652168.0,5278831.0,73872.0,1449568.0,1363941.0,479757.0,6129.0,2887381.0,186636.0,84729.0,118.835358,106.500000,156.000000,215.000000,257.000000,387.180780,277.500000,477.000000,779.412500,1065.000000,3921374.0,1311537.0,541175.0,770362.0,4100387.0,547498.0,586064.0,995956.0,609740.0,2487943.0,337458.0,354542.0,610339.0,367613.0,1345658.0,682507.0,708629.0,378574.0,4.58,82.65,66.27,54.78,61.01,74.28,0.85,16.75,15.76,2.16,0.98,5.62,58.74,41.26,47.39,6.33,6.77,11.51,7.05,47.13,6.39,6.72,11.56,6.96,15.55,7.89,13.42,7.17
9,4-OTHER,iOS,158755,141234,957592.0,632662.0,420452.0,618196.0,390069.0,6325.0,87564.0,95920.0,37873.0,440.0,189809.0,11811.0,7814.0,119.020936,105.000000,160.000000,225.000000,268.350000,387.028429,265.500000,477.787500,812.000000,1113.150000,277508.0,92483.0,29505.0,62978.0,187278.0,9330.0,20259.0,232347.0,38125.0,117832.0,5826.0,12455.0,149168.0,24271.0,121515.0,48524.0,66677.0,28877.0,2.76,66.07,66.46,43.91,63.10,71.14,1.02,14.16,15.52,1.91,1.26,6.20,68.10,31.90,30.29,1.51,3.28,37.58,6.17,30.21,1.49,3.19,38.24,6.22,19.66,7.85,17.09,7.40
10,4-OTHER,no,312700,289415,1500069.0,1169646.0,607706.0,969391.0,633586.0,11026.0,114359.0,148141.0,60879.0,1395.0,273526.0,13629.0,7539.0,118.980741,105.000000,158.666667,221.000000,263.000000,558.312253,391.875000,698.000000,1160.000000,1610.000000,443314.0,89055.0,31989.0,57066.0,628492.0,21443.0,44486.0,83457.0,51149.0,411132.0,13176.0,27678.0,56253.0,33412.0,99095.0,112512.0,62463.0,69102.0,2.19,77.97,51.96,40.51,65.36,69.97,1.14,11.80,15.28,1.41,0.78,6.42,64.08,35.92,64.83,2.21,4.59,8.61,5.28,64.89,2.08,4.37,8.88,5.27,10.22,11.61,9.86,10.91
11,4-OTHER,yes,576043,517155,2635685.0,2174123.0,1246836.0,1979901.0,1276090.0,17756.0,286324.0,287345.0,110653.0,1710.0,591425.0,33529.0,14521.0,121.194238,107.166667,161.000000,225.000000,266.000000,449.531776,310.000000,556.000000,933.000000,1296.000000,922600.0,251053.0,86238.0,164815.0,1028943.0,71844.0,122671.0,209712.0,142555.0,662819.0,44820.0,77811.0,136032.0,91275.0,297161.0,184686.0,171866.0,111154.0,2.47,82.49,57.35,47.31,64.45,72.30,0.90,14.46,14.51,1.69,0.73,5.68,65.65,34.35,51.97,3.63,6.20,10.59,7.20,51.94,3.51,6.10,10.66,7.15,15.01,9.33,13.47,8.71
12,5-INACTIVE,iOS,4686,4178,42846.0,30445.0,0.0,25560.0,15000.0,191.0,4381.0,4437.0,1533.0,18.0,9009.0,737.0,418.0,114.786407,107.500000,153.166667,212.000000,251.000000,355.746798,249.200000,435.250000,727.000000,1010.500000,10998.0,2981.0,1484.0,1497.0,6319.0,527.0,648.0,4768.0,1086.0,3554.0,302.0,398.0,2923.0,656.0,4645.0,2086.0,2340.0,1122.0,3.59,71.06,0.00,0.00,58.69,73.32,0.75,17.14,17.36,2.88,1.64,6.07,50.22,49.78,24.72,2.06,2.54,18.65,4.25,23.69,2.01,2.65,19.49,4.37,18.17,8.16,15.60,7.48
13,5-INACTIVE,no,25626,23587,88806.0,79739.0,0.0,125815.0,79900.0,1348.0,18554.0,19267.0,6631.0,113.0,39169.0,2381.0,1489.0,117.907157,106.142857,154.000000,212.000000,252.300000,472.442264,332.000000,579.000000,949.200000,1290.400000,58055.0,13552.0,6001.0,7551.0,70555.0,7142.0,7595.0,10987.0,6457.0,44884.0,4560.0,4668.0,7188.0,4009.0,13509.0,13034.0,7821.0,7518.0,3.39,89.79,0.00,0.00,63.51,72.66,1.07,14.75,15.31,1.89,1.18,5.36,55.72,44.28,56.08,5.68,6.04,8.73,5.13,56.18,5.71,5.84,9.00,5.02,10.74,10.36,9.79,9.41
14,5-INACTIVE,yes,77092,70598,171900.0,161838.0,0.0,523959.0,326141.0,3801.0,86844.0,78959.0,27867.0,346.0,169604.0,11135.0,5150.0,119.444345,108.000000,157.000000,214.000000,255.000000,386.757509,275.333333,467.500000,766.000000,1076.000000,246362.0,82253.0,41339.0,40914.0,232978.0,43979.0,37671.0,52959.0,35325.0,144067.0,27298.0,23423.0,32943.0,21699.0,78109.0,42638.0,42655.0,24336.0,4.62,94.15,0.00,0.00,62.25,75.54,0.73,16.57,15.07,2.13,0.98,5.38,49.74,50.26,44.46,8.39,7.19,10.11,6.74,44.17,8.37,7.18,10.10,6.65,14.91,8.14,13.08,7.46

In [40]:
segment_qc.to_clipboard(index=False)

In [41]:
segment_travel_qc = agg_func(['segment','travelridehailing','quick_commerce'])
segment_travel_qc

['segment', 'travelridehailing', 'quick_commerce']

,segment,travelridehailing,quick_commerce,gross_customers,net_customers,ao_session,fe_session,rr_session,rr_count,net_count,cobrm_count,cobra_count,ocara_count,expired_count,aborted_count,canceltn_count,quick_cobra,quick_ocara,cobra_ttc_mean,cobra_ttc_p50,cobra_ttc_p75,cobra_ttc_p90,cobra_ttc_p95,ocara_ttc_mean,ocara_ttc_p50,ocara_ttc_p75,ocara_ttc_p90,ocara_ttc_p95,haps_orders,bid_orders,negative_bid,positive_bid,gross_psm_gps,gross_psm_fav_recent_history,gross_psm_google_search,gross_psm_stickylocation,gross_psm_hotspot,net_psm_gps,net_psm_fav_recent_history,net_psm_google_search,net_psm_fav_stickylocation,net_psm_hotspot,office_gross,transit_gross,office_net,transit_net,rpc,a02fe,fe2rr,ao2rr,g2n,haps%,cobrm%,cobra%,ocara%,quick_cobra%,quick_ocara%,expired%,positive_bid%,negative_bid%,gross_psm_gps%,gross_psm_fav_recent_history%,gross_psm_google_search%,gross_psm_stickylocation%,gross_psm_hotspot%,net_psm_gps%,net_psm_fav_recent_history%,net_psm_google_search%,net_psm_fav_stickylocation%,net_psm_hotspot%,office_gross%,transit_gross%,office_net%,transit_net%
0,1-DAILY,iOS,iOS,29978,29978,1904141.0,1203822.0,1075549.0,2024697.0,1222268.0,10978.0,285378.0,378941.0,126435.0,692.0,675297.0,45795.0,37500.0,122.466054,117.111111,154.000000,193.480000,223.850000,280.194240,248.075000,339.786957,456.660000,557.000000,963869.0,603293.0,313753.0,289540.0,570502.0,98694.0,97654.0,557701.0,153443.0,340983.0,62207.0,60131.0,342515.0,91661.0,419524.0,80867.0,211401.0,45295.0,40.77,63.22,89.34,56.48,60.37,78.86,0.54,14.09,18.72,2.26,1.85,6.28,47.99,52.01,28.18,4.87,4.82,27.54,7.58,27.90,5.09,4.92,28.02,7.50,20.72,3.99,17.30,3.71
1,1-DAILY,no,no,4561,4543,214536.0,166390.0,143017.0,292184.0,184444.0,2034.0,48265.0,44356.0,12881.0,203.0,94655.0,7426.0,4628.0,113.229690,107.758373,139.983333,176.702381,209.000000,363.314949,309.275641,443.450000,633.000000,798.370000,145096.0,47688.0,28923.0,18765.0,145762.0,30770.0,21912.0,26965.0,12322.0,90336.0,20700.0,14329.0,17117.0,7797.0,29497.0,11334.0,16667.0,6546.0,40.60,77.56,85.95,66.66,63.13,78.67,0.70,16.52,15.18,2.54,1.58,4.48,39.35,60.65,49.89,10.53,7.50,9.23,4.22,48.98,11.22,7.77,9.28,4.23,10.10,3.88,9.04,3.55
2,1-DAILY,no,yes,6053,6051,272310.0,216589.0,193747.0,389311.0,251238.0,2215.0,63527.0,58229.0,13886.0,214.0,123971.0,10086.0,5330.0,108.023568,101.516667,135.000000,170.747222,199.408333,343.672631,289.187500,417.000000,594.066667,754.980000,198267.0,69393.0,33376.0,36017.0,172085.0,47234.0,34327.0,36980.0,18523.0,109271.0,31191.0,22794.0,24302.0,11780.0,45300.0,15988.0,26378.0,9323.0,41.52,79.54,89.45,71.15,64.53,78.92,0.57,16.32,14.96,2.59,1.37,3.62,51.90,48.10,44.20,12.13,8.82,9.50,4.76,43.49,12.41,9.07,9.67,4.69,11.64,4.11,10.50,3.71
3,1-DAILY,yes,no,5920,5908,291365.0,229943.0,192092.0,382766.0,238137.0,3067.0,62674.0,58042.0,20627.0,217.0,123783.0,8962.0,6276.0,120.228582,115.000000,149.000000,185.580000,215.250000,357.827923,300.309524,428.187500,620.162338,783.666667,188408.0,67480.0,43263.0,24217.0,175526.0,49555.0,30856.0,34477.0,19573.0,107113.0,32301.0,20031.0,21399.0,12268.0,39623.0,17195.0,21556.0,9446.0,40.31,78.92,83.54,65.93,62.21,79.12,0.80,16.37,15.16,2.34,1.64,5.45,35.89,64.11,45.86,12.95,8.06,9.01,5.11,44.98,13.56,8.41,8.99,5.15,10.35,4.49,9.05,3.97
4,1-DAILY,yes,yes,62330,62303,2836932.0,2316809.0,2060601.0,4097937.0,2494584.0,27293.0,676657.0,673126.0,224541.0,1711.0,1377076.0,98140.0,62753.0,119.903196,115.111111,148.266667,184.000000,211.333333,299.018584,257.105263,360.571429,500.000000,614.600000,1985125.0,1048901.0,579000.0,469901.0,1427534.0,580898.0,368637.0,468770.0,299831.0,854321.0,357165.0,230364.0,284672.0,180106.0,705336.0,177524.0,362542.0,98168.0,40.04,81.67,88.94,72.63,60.87,79.58,0.67,16.51,16.43,2.39,1.53,5.52,44.80,55.20,34.84,14.18,9.00,11.44,7.32,34.25,14.32,9.23,11.41,7.22,17.21,4.33,14.53,3.94
5,2-WEEKLY,iOS,iOS,72000,71947,1939687.0,1233605.0,1007172.0,1865202.0,1097641.0,11523.0,281302.0,342621.0,131350.0,755.0,635446.0,43640.0,30081.0,122.602868,113.500000,158.000000,209.000000,248.000000,298.935098,245.250000,366.000000,535.000000,686.755357,828060.0,444668.0,223199.0,221469.0,545089.0,75062.0,88958.0,558564.0,144099.0,315292.0,46400.0,53328.0,335841.0,84429.0,417632.0,99490.0,202808.0,54416.0,15.26,63.60,81.64,51.92,58.85,75.44,0.62,15.08,18.37,2.34,1.61,7.08,49.81,50.19,29.22,4.02,4.77,29.95,7.73,28.72,4.23,4.86,30.60,7.69,22.39,5.33,18.48,4.96
6,2-WEEKLY,no,no,15626,15574,312066.0,243300.0,182438.0,363072.0,224497.0,3294.0,59901.0,58136.0,16922.0,321.0,121331.0,8413.0,5009.0,111.077686,101.857143,142.000000,189.000000,224.000000,408.791546,322.000000,501.000000,767.000000,993.816667,169434.0,45538.0,22378.0,23160.0,201733.0,26670.0,23504.0,34404.0,15960.0,123509.0,17033.0,14941.0,21852.0,9670.0,34417.0,21747.0,19165.0,11777.0,14.41,77.96,74.98,58.46,61.83,75.47,0.91,16.50,16.01,2.32,1.38,4.75,50.86,49.14,55.56,7.35,6.47,9.48,4.40,55.02,7.59,6.66,9.73,4.31,9.48,5.99,8.54,5.25
7,2-WEEKLY,no,yes,21479,21458,395917.0,315249.0,249364.0,492282.0,314130.0,3380.0,79219.0,76012.0,19195.0,341.0,158611.0,11196.0,5676.0,108.845740,99.000000,138.237500,184.500000,220.491667,374.444676,295.708333,463.762500,693.419048,911.862500,238500.0,73804.0,32294.0,41510.0,239094.0,44942.0,38125.0,48467.0,25279.0,150026.0,29799.0,24859.0,31417.0,15889.0,53879.0,28817.0,31426.0,16282.0,14.64,79.63,79.10,62.98,63.81,75.92,0.69,16.09,15.44,2.27,1.15,3.97,56.24,43.76,48.57,9.13,7.74,9.85,5.14,47.76,9.49,7.91,10.00,5.06,10.94,5.85,10.00,5.18
8,2-WEEKLY,yes,no,18207,18119,366693.0,292275.0,214385.0,417526.0,255806.0,4005.0,66935.0,66625.0,23786.0,366.0,137565.0,8764.0,7121.0,117.764380,109.000000,149.690476,197.760000,236.000000,390.193312,303.416667,480.500000,738.464286,982.000000,194597.0,58951.0,31879.0,27072.0,213178.0,39115.0,32086.0,39587.0,21910.0,130085.0,24978.0,19935.0,24526.0,12945.0,45169.0,25752.0,24000.0,13636.0,14.12,79.71,73.35,58.46,61.27,76.07,0.96,16.03,15.96,2.10,1.71,5.78,45.92,54.08,51.06,9.37,7.68,9.48,5.25,50.85,9.76,7.79,9.59,5.06,10.82,6.17,9.38,5.33
9,2-WEEKLY,yes,yes,169054,168889,3297965.0,2701762.0,2151742.0,4181642.0,2492862.0,32433.0,711887.0,690124.0,252266.0,2041.0,1434444.0,99797.0,55369.0,119.635630,111.666667,152.333333,199.400000,235.000000,322.110553,259.000000,395.267045,589.333333,766.316667,1913047.0,879884.0,454962.0,424922.0,1655653.0,435253.0,349791.0,494054.0,321960.0,975532.0,262612.0,212015.0,293362.0,189860.0,765660.0,242493.0,379077.0,131552.0,14.76,81.92,79.64,65.24,59.61,76.74,0.78,17.02,16.50,2.39,1.32,6.08,48.29,51.71,39.59,10.41,8.36,11.81,7.70,39.13,10.53,8.50,11.77,7.62,18.31,5.80,15.21,5.28
10,3-MONTHLY,iOS,iOS,362254,337455,3256439.0,2133522.0,1543665.0,2846794.0,1700523.0,19862.0,445704.0,489015.0,190021.0,1650.0,954581.0,62979.0,35796.0,121.218660,108.500000,160.750000,222.000000,264.000000,339.451084,246.000000,417.000000,680.000000,922.000000,1244963.0,512619.0,208967.0,303652.0,871168.0,84998.0,122190.0,886151.0,208653.0,512793.0,52426.0,72193.0,542230.0,124167.0,582899.0,199738.0,293936.0,110806.0,5.04,65.52,72.35,47.40,59.73,73.21,0.70,15.66,17.18,2.21,1.26,6.73,59.24,40.76,30.60,2.99,4.29,31.13,7.33,30.16,3.08,4.25,31.89,7.30,20.48,7.02,17.29,6.52
11,3-MONTHLY,no,no,216141,202411,1420171.0,1115630.0,663817.0,1348770.0,833829.0,16138.0,198214.0,222750.0,76022.0,1805.0,437102.0,24544.0,12984.0,114.156222,102.000000,149.666667,206.000000,248.000000,502.235490,365.000000,624.916667,1020.000000,1389.000000,602176.0,135740.0,52942.0,82798.0,865365.0,51243.0,61780.0,120483.0,59477.0,534196.0,31969.0,37781.0,76705.0,35901.0,125288.0,119692.0,72858.0,66778.0,4.12,78.56,59.50,46.74,61.82,72.22,1.20,14.70,16.52,1.82,0.96,5.77,61.00,39.00,64.16,3.80,4.58,8.93,4.41,64.07,3.83,4.53,9.20,4.31,9.29,8.87,8.74,8.01
12,3-MONTHLY,no,yes,218103,205897,1362626.0,1097082.0,696595.0,1379942.0,877808.0,12179.0,211386.0,215751.0,61464.0,1345.0,439316.0,27467.0,11940.0,111.367407,99.000000,145.333333,202.000000,243.316667,447.151488,324.000000,555.000000,905.500000,1231.700000,640251.0,165218.0,58047.0,107171.0,768633.0,69493.0,78415.0,137196.0,72604.0,485056.0,45503.0,49353.0,89150.0,45754.0,145521.0,116430.0,86530.0,66138.0,4.26,80.51,63.50,51.12,63.61,72.94,0.88,15.32,15.63,1.99,0.87,4.55,64.87,35.13,55.70,5.04,5.68,9.94,5.26,55.26,5.18,5.62,10.16,5.21,10.55,8.44,9.86,7.53
13,3-MONTHLY,yes,no,174082,160855,1161252.0,938662.0,561814.0,1114844.0,684241.0,12806.0,170094.0,177799.0,68612.0,1284.0,360699.0,20146.0,13720.0,119.016072,107.000000,156.000000,215.000000,256.000000,467.444222,331.000000,576.000000,955.750000,1326.000000,501641.0,120659.0,51407.0,69252.0,661878.0,55740.0,61855.0,104006.0,56826.0,405637.0,35024.0,37490.0,65329.0,33868.0,116459.0,98858.0,64704.0,54142.0,4.25,80.83,59.85,48.38,61.38,73.31,1.15,15.26,15.95,1.81,1.23,6.27,57.39,42.61,59.37,5.00,5.55,9.33,5.10,59.28,5.12,5.48,9.55,4.95,10.45,8.87,9.46,7.91
14,3-MONTHLY,yes,yes,1015276,945588,6766970.0,5622082.0,3756433.0,7272226.0,4401023.0,61693.0,1238182.0,1148190.0,418293.0,4784.0,2448065.0,159169.0,72789.0,120.132533,108.000000,158.000000,217.000000,259.000000,375.191790,269.500000,461.750000,753.333333,1027.500000,3281123.0,1146319.0,483128.0,663191.0,3331754.0,478005.0,507649.0,858760.0,537136.0,2002887.0,291955.0,305189.0,521189.0,321859.0,1200137.0,566077.0,622099.0,312436.0,4.65,83.08,66.82,55.51,60.52,74.55,0.85,17.03,15.79,2.19,1.00,5.82,57.85,42.15,45.81,6.57,6.98,11.81,7.39,45.51,6.63,6.93,11.84,7.31,16.50,7.78,14.14,7.10
15,4-OTHER,iOS,iOS,158755,141234,957592.0,632662.0,420452.0,618196.0,390069.0,6325.0,87564.0,95920.0,37873.0,440.0,189809.0,11811.0,7814.0,119.020936,105.000000,160.000000,225.000000,268.350000,387.028429,265.500000,477.787500,812.000000,1113.150000,277508.0,92483.0,29505.0,62978.0,187278.0,9330.0,20259.0,232347.0,38125.0,117832.0,5826.0,12455.0,149168.0,24271.0,121515.0,48524.0,66677.0,28877.0,2.76,66.07,66.46,43.91,63.10,71.14,1.02,14.16,15.52,1.91,1.26,6.20,68.10,31.90,30.29,1.51,3.28,37.58,6.17,30.21,1.49,3.19,38.24,6.22,19.66,7.85,17.09,7.40
16,4-OTHER,no,no,189665,177488,920715.0,706547.0,364805.0,583615.0,383207.0,6585.0,66643.0,90732.0,35558.0,886.0,163960.0,8193.0,4245.0,116.822860,102.000000,156.000000,218.000000,261.500000,570.114120,405.500000,716.500000,1185.000000,1628.016667,265277.0,51474.0,18087.0,33387.0,387557.0,11364.0,24828.0,48911.0,29161.0,254820.0,6838.0,15373.0,33242.0,19065.0,56727.0,69616.0,36343.0,43159.0,2.16,76.74,51.63,39.62,65.66,69.23,1.13,11.42,15.55,1.40,0.73,6.24,64.86,35.14,66.41,1.95,4.25,8.38,5.00,66.50,1.78,4.01,8.67,4.98,9.72,11.93,9.48,11.26
17,4-OTHER,no,yes,131276,121619,607437.0,485911.0,259817.0,419400.0,279836.0,3683.0,52364.0,62237.0,20815.0,460.0,118284.0,6481.0,2967.0,115.517775,101.500000,152.666667,215.000000,259.000000,505.897405,356.500000,633.000000,1057.000000,1440.000000,197800.0,44948.0,14496.0,30452.0,246764.0,11216.0,21332.0,39332.0,23850.0,164304.0,7127.0,13766.0,26882.0,16020.0,45809.0,43625.0,29482.0,27295.0,2.30,79.99,53.47,42.77,66.72,70.68,0.88,12.49,14.84,1.55,0.71,5.07,67.75,32.25,58.84,2.67,5.09,9.38,5.69,58.71,2.55,4.92,9.61,5.72,10.92,10.40,10.54,9.75
18,4-OTHER,yes,no,123035,111927,579354.0,463099.0,242901.0,385776.0,250379.0,4441.0,47716.0,57409.0,25321.0,509.0,109566.0,5436.0,3294.0,121.901301,108.666667,162.500000,226.000000,266.000000,539.784679,370.000000,666.458333,1116.616667,1580.000000,178037.0,37581.0,13902.0,23679.0,240935.0,10079.0,19658.0,34546.0,21988.0,156312.0,6338.0,12305.0,23011.0,14347.0,42368.0,42896.0,26120.0,25943.0,2.24,79.93,52.45,41.93,64.90,71.11,1.15,12.37,14.88,1.41,0.85,6.70,63.01,36.99,62.45,2.61,5.10,8.95,5.70,62.43,2.53,4.91,9.19,5.73,10.98,11.12,10.43,10.36
19,4-OTHER,yes,yes,444767,395536,2028248.0,1688212.0,987019.0,1560501.0,996254.0,14073.0,233960.0,225108.0,89838.0,1250.0,473141.0,27048.0,11554.0,122.481737,109.000000,163.000000,226.510000,268.000000,433.435766,297.666667,534.333333,897.000000,1247.000000,724800.0,206105.0,71742.0,134363.0,782179.0,60628.0,101339.0,170380.0,118705.0,498515.0,37693.0,64045.0,109150.0,75255.0,251352.0,141061.0,142384.0,83859.0,2.52,83.23,58.47,48.66,63.84,72.75,0.90,14.99,14.43,1.73,0.74,5.84,65.19,34.81,50.12,3.89,6.49,10.92,7.61,50.04,3.78,6.43,10.96,7.55,16.11,9.04,14.29,8.42
20,5-INACTIVE,iOS,iOS,4686,4178,42846.0,30445.0,0.0,25560.0,15000.0,191.0,4381.0,4437.0,1533.0,18.0,9009.0,737.0,418.0,114.786407,107.500000,153.166667,212.000000,251.000000,355.746798,249.200000,435.250000,727.000000,1010.500000,10998.0,2981.0,1484.0,1497.0,6319.0,527.0,648.0,4768.0,1086.0,3554.0,302.0,398.0,2923.0,656.0,4645.0,2086.0,2340.0,1122.0,3.59,71.06,0.00,0.00,58.69,73.32,0.75,17.14,17.36,2.88,1.64,6.07,50.22,49.78,24.72,2.06,2.54,18.65,4.25,23.69,2.01,2.65,19.49,4.37,18.17,8.16,15.60,7.48
21,5-INACTIVE,no,no,13365,12435,47761.0,42109.0,0.0,59761.0,38166.0,654.0,8680.0,9153.0,3059.0,47.0,18487.0,1211.0,596.0,114.455909,103.333333,149.000000,208.675000,246.212500,470.721683,340.000000,598.500000,965.100000,1275.600000,27163.0,5779.0,2290.0,3489.0,35174.0,2651.0,3208.0,5253.0,2910.0,22495.0,1699.0,1962.0,3468.0,1831.0,6173.0,6528.0,3750.0,3756.0,3.07,88.17,0.00,0.00,63.86,71.17,1.09,14.52,15.32,2.03,1.00,5.20,60.37,39.63,58.86,4.44,5.37,8.79,4.87,58.94,4.45,5.14,9.09,4.80,10.33,10.92,9.83,9.84
22,5-INACTIVE,no,yes,12646,11795,36658.0,33503.0,0.0,64162.0,41749.0,472.0,9989.0,9234.0,2657.0,61.0,19695.0,1219.0,555.0,112.412491,99.000000,146.375000,203.500000,249.000000,426.068357,310.000000,519.090909,847.900000,1218.350000,30408.0,7777.0,2990.0,4787.0,33498.0,3693.0,4070.0,5757.0,3590.0,21788.0,2383.0,2631.0,3777.0,2302.0,6886.0,5840.0,4349.0,3461.0,3.54,91.39,0.00,0.00,65.07,72.84,0.74,15.57,14.39,1.90,0.86,4.24,61.55,38.45,52.21,5.76,6.34,8.97,5.60,52.19,5.71,6.30,9.05,5.51,10.73,9.10,10.42,8.29
23,5-INACTIVE,yes,no,12261,11152,41045.0,37630.0,0.0,66054.0,41734.0,694.0,9874.0,10114.0,3572.0,66.0,20682.0,1170.0,893.0,121.003712,109.000000,159.200000,216.000000,260.000000,474.223992,326.687500,562.000000,937.700000,1309.700000,30892.0,7773.0,3711.0,4062.0,35381.0,4491.0,4387.0,5734.0,3547.0,22389.0,2861.0,2706.0,3720.0,2178.0,7336.0,6506.0,4071.0,3762.0,3.74,91.68,0.00,0.00,63.18,74.02,1.05,14.95,15.31,1.77,1.35,5.51,52.26,47.74,53.56,6.80,6.64,8.68,5.37,53.65,6.86,6.48,8.91,5.22,11.11,9.85,9.75,9.01
24,5-INACTIVE,yes,yes,64446,58803,135242.0,128335.0,0.0,459797.0,284392.0,3329.0,76855.0,69725.0,25210.0,285.0,149909.0,9916.0,4595.0,120.494913,109.454545,158.500000,215.250000,256.000000,380.181624,270.750000,458.000000,750.000000,1046.083333,215954.0,74476.0,38349.0,36127.0,199480.0,40286.0,33601.0,47202.0,31735.0,122279.0,24915.0,20792.0,29166.0,19397.0,71223.0,36798.0,38306.0,20875.0,4.84,94.89,0.00,0.00,61.85,75.94,0.72,16.71,15.16,2.16,1.00,5.54,48.51,51.49,43.38,8.76,7.31,10.27,6.90,43.00,8.76,7.31,10.26,6.82,15.49,8.00,13.47,7.34

In [42]:
segment_travel_qc.to_clipboard(index=False)

In [43]:
segment_office = agg_func(['segment','office_tag'])
segment_office

['segment', 'office_tag']

,segment,office_tag,gross_customers,net_customers,ao_session,fe_session,rr_session,rr_count,net_count,cobrm_count,cobra_count,ocara_count,expired_count,aborted_count,canceltn_count,quick_cobra,quick_ocara,cobra_ttc_mean,cobra_ttc_p50,cobra_ttc_p75,cobra_ttc_p90,cobra_ttc_p95,ocara_ttc_mean,ocara_ttc_p50,ocara_ttc_p75,ocara_ttc_p90,ocara_ttc_p95,haps_orders,bid_orders,negative_bid,positive_bid,gross_psm_gps,gross_psm_fav_recent_history,gross_psm_google_search,gross_psm_stickylocation,gross_psm_hotspot,net_psm_gps,net_psm_fav_recent_history,net_psm_google_search,net_psm_fav_stickylocation,net_psm_hotspot,office_gross,transit_gross,office_net,transit_net,rpc,a02fe,fe2rr,ao2rr,g2n,haps%,cobrm%,cobra%,ocara%,quick_cobra%,quick_ocara%,expired%,positive_bid%,negative_bid%,gross_psm_gps%,gross_psm_fav_recent_history%,gross_psm_google_search%,gross_psm_stickylocation%,gross_psm_hotspot%,net_psm_gps%,net_psm_fav_recent_history%,net_psm_google_search%,net_psm_fav_stickylocation%,net_psm_hotspot%,office_gross%,transit_gross%,office_net%,transit_net%
0,1-DAILY,office,87290,87281,4581081.0,3397011.0,3021321.0,5928348.0,3605494.0,37492.0,945498.0,1008376.0,329003.0,2459.0,1991366.0,141336.0,94912.0,120.381009,115.200000,149.327957,186.291429,215.0000,297.812437,258.055728,359.60000,495.653623,610.000000,2847104.0,1561452.0,823972.0,737480.0,2017622.0,616059.0,442159.0,973434.0,435825.0,1211982.0,380963.0,275718.0,595179.0,261483.0,1229936.0,252523.0,638544.0,141812.0,41.31,74.15,88.94,65.95,60.82,78.97,0.63,15.95,17.01,2.38,1.60,5.59,47.23,52.77,34.03,10.39,7.46,16.42,7.35,33.61,10.57,7.65,16.51,7.25,20.75,4.26,17.71,3.93
1,1-DAILY,other,21552,21502,938203.0,736542.0,643685.0,1258547.0,785177.0,8095.0,191003.0,204318.0,69367.0,578.0,403416.0,29073.0,21575.0,116.928261,111.750000,147.000000,185.000000,214.0000,319.614021,267.041667,385.65625,553.000000,695.186667,633661.0,275303.0,174343.0,100960.0,473787.0,191092.0,111227.0,151459.0,67867.0,290042.0,122601.0,71931.0,94826.0,42129.0,9344.0,50385.0,0.0,26966.0,36.52,78.51,87.39,68.61,62.39,80.70,0.64,15.18,16.23,2.31,1.71,5.56,36.67,63.33,37.65,15.18,8.84,12.03,5.39,36.94,15.61,9.16,12.08,5.37,0.74,4.00,0.00,3.43
2,2-WEEKLY,office,208986,208887,4705125.0,3529949.0,2833211.0,5452956.0,3251329.0,41189.0,905761.0,916773.0,335161.0,2714.0,1863723.0,128606.0,74181.0,120.366093,112.000000,153.500000,201.000000,237.5000,321.615561,259.833333,394.00000,584.750000,756.729167,2461682.0,1184047.0,586521.0,597526.0,2054099.0,423792.0,384803.0,930703.0,429884.0,1213577.0,257222.0,233589.0,557767.0,253720.0,1288970.0,313714.0,656476.0,171660.0,15.57,75.02,80.26,60.22,59.63,75.71,0.76,16.61,16.81,2.36,1.36,6.20,50.46,49.54,37.67,7.77,7.06,17.07,7.88,37.33,7.91,7.18,17.16,7.80,23.64,5.75,20.19,5.28
3,2-WEEKLY,other,87380,87100,1607203.0,1256242.0,971890.0,1866768.0,1133607.0,13446.0,293483.0,316745.0,108358.0,1110.0,623674.0,43204.0,29075.0,115.873228,107.000000,149.000000,198.333333,236.9625,345.616065,269.142857,425.00000,648.000000,864.466667,881956.0,318798.0,178191.0,140607.0,800648.0,197250.0,147661.0,244373.0,99324.0,480867.0,123600.0,91489.0,149231.0,59073.0,27787.0,104585.0,0.0,56003.0,13.02,78.16,77.36,60.47,60.73,77.80,0.72,15.72,16.97,2.31,1.56,5.86,44.11,55.89,42.89,10.57,7.91,13.09,5.32,42.42,10.90,8.07,13.16,5.21,1.49,5.60,0.00,4.94
4,3-MONTHLY,office,798335,773562,7216680.0,5545021.0,3873522.0,7468364.0,4567828.0,63664.0,1235223.0,1164363.0,432482.0,4760.0,2463250.0,160390.0,75716.0,120.447042,108.800000,157.166667,215.000000,256.0000,371.819832,273.250000,458.50000,737.000000,994.500000,3342729.0,1243636.0,513657.0,729979.0,3247154.0,375652.0,429706.0,1244477.0,580763.0,1978791.0,231683.0,261359.0,765694.0,353669.0,2000255.0,531977.0,1140121.0,295894.0,5.90,76.84,69.86,53.67,61.16,73.18,0.85,16.54,15.59,2.15,1.01,5.85,58.70,41.30,43.48,5.03,5.75,16.66,7.78,43.32,5.07,5.72,16.76,7.74,26.78,7.12,24.96,6.48
5,3-MONTHLY,other,1187521,1078644,6750778.0,5361957.0,3348802.0,6494212.0,3929596.0,59014.0,1028357.0,1089142.0,381930.0,6108.0,2176513.0,133915.0,71513.0,117.559492,104.500000,156.000000,216.000000,258.0000,416.180924,290.333333,514.00000,857.000000,1183.000000,2927425.0,836919.0,340834.0,496085.0,3251644.0,363827.0,402183.0,862119.0,353933.0,1961778.0,225194.0,240647.0,528909.0,207880.0,170049.0,568818.0,6.0,314406.0,3.64,79.43,62.45,49.61,60.51,74.50,0.91,15.83,16.77,2.06,1.10,5.98,59.28,40.72,50.07,5.60,6.19,13.28,5.45,49.92,5.73,6.12,13.46,5.29,2.62,8.76,0.00,8.00
6,4-OTHER,office,200481,198767,1556383.0,1187187.0,768201.0,1180661.0,774731.0,11459.0,167991.0,161223.0,64448.0,801.0,340673.0,20241.0,9999.0,122.675213,110.250000,161.000000,221.000000,263.0000,428.281428,308.000000,529.00000,864.000000,1176.000000,548840.0,166578.0,59038.0,107540.0,554669.0,35255.0,58147.0,205120.0,95374.0,365375.0,22538.0,37730.0,133975.0,63492.0,445036.0,78728.0,300990.0,46099.0,3.90,76.28,64.71,49.36,65.62,70.84,0.97,14.23,13.66,1.71,0.85,5.53,64.56,35.44,46.98,2.99,4.92,17.37,8.08,47.16,2.91,4.87,17.29,8.20,37.69,6.67,38.85,5.95
7,4-OTHER,other,847017,749037,3536963.0,2789244.0,1506793.0,2386827.0,1525014.0,23648.0,320256.0,370183.0,144957.0,2744.0,714087.0,38728.0,19875.0,119.469695,105.000000,160.000000,225.000000,267.0000,482.873905,328.000000,602.00000,1022.000000,1421.000000,1094582.0,266013.0,88694.0,177319.0,1290044.0,67362.0,129269.0,320396.0,136455.0,826408.0,41284.0,80214.0,207478.0,85466.0,72735.0,266994.0,16.0,163034.0,2.04,78.86,54.02,42.60,63.89,71.78,0.99,13.42,15.51,1.62,0.83,6.19,66.66,33.34,54.05,2.82,5.42,13.42,5.72,54.19,2.71,5.26,13.60,5.60,3.05,11.19,0.00,10.69
8,5-INACTIVE,office,31887,31184,2716.0,2074.0,0.0,356310.0,223126.0,2662.0,59015.0,52701.0,18599.0,206.0,114378.0,7615.0,3608.0,120.546413,110.400000,156.000000,210.000000,249.0000,370.901225,274.500000,447.00000,718.333333,973.975000,168043.0,59811.0,31055.0,28756.0,153167.0,29961.0,25144.0,37855.0,25927.0,95420.0,18587.0,15822.0,23716.0,16131.0,88479.0,25303.0,52691.0,14182.0,7.16,76.36,0.00,0.00,62.62,75.31,0.75,16.56,14.79,2.14,1.01,5.28,48.08,51.92,42.99,8.41,7.06,10.62,7.28,42.77,8.33,7.09,10.63,7.23,24.83,7.10,23.61,6.36
9,5-INACTIVE,other,75517,67179,300836.0,269948.0,0.0,319024.0,197915.0,2678.0,50764.0,49962.0,17432.0,271.0,103404.0,6638.0,3449.0,117.881366,105.183333,157.000000,217.000000,258.0000,424.630200,293.000000,519.50000,871.000000,1216.000000,147372.0,38975.0,17769.0,21206.0,156685.0,21687.0,20770.0,30859.0,16941.0,97085.0,13573.0,12667.0,19338.0,10233.0,7784.0,32455.0,125.0,18794.0,2.95,89.73,0.00,0.00,62.04,74.46,0.84,15.91,15.66,2.08,1.08,5.55,54.41,45.59,49.11,6.80,6.51,9.67,5.31,49.05,6.86,6.40,9.77,5.17,2.44,10.17,0.06,9.50

In [45]:
segment_office.to_clipboard(index=False)

In [46]:
segment_office_travel_qc = agg_func(['segment','office_tag','travelridehailing','quick_commerce'])
segment_office_travel_qc

['segment', 'office_tag', 'travelridehailing', 'quick_commerce']

,segment,office_tag,travelridehailing,quick_commerce,gross_customers,net_customers,ao_session,fe_session,rr_session,rr_count,net_count,cobrm_count,cobra_count,ocara_count,expired_count,aborted_count,canceltn_count,quick_cobra,quick_ocara,cobra_ttc_mean,cobra_ttc_p50,cobra_ttc_p75,cobra_ttc_p90,cobra_ttc_p95,ocara_ttc_mean,ocara_ttc_p50,ocara_ttc_p75,ocara_ttc_p90,ocara_ttc_p95,haps_orders,bid_orders,negative_bid,positive_bid,gross_psm_gps,gross_psm_fav_recent_history,gross_psm_google_search,gross_psm_stickylocation,gross_psm_hotspot,net_psm_gps,net_psm_fav_recent_history,net_psm_google_search,net_psm_fav_stickylocation,net_psm_hotspot,office_gross,transit_gross,office_net,transit_net,rpc,a02fe,fe2rr,ao2rr,g2n,haps%,cobrm%,cobra%,ocara%,quick_cobra%,quick_ocara%,expired%,positive_bid%,negative_bid%,gross_psm_gps%,gross_psm_fav_recent_history%,gross_psm_google_search%,gross_psm_stickylocation%,gross_psm_hotspot%,net_psm_gps%,net_psm_fav_recent_history%,net_psm_google_search%,net_psm_fav_stickylocation%,net_psm_hotspot%,office_gross%,transit_gross%,office_net%,transit_net%
0,1-DAILY,office,iOS,iOS,26256,26256,1695370.0,1066830.0,955941.0,1805338.0,1087043.0,9941.0,256014.0,339373.0,112360.0,603.0,605328.0,40997.0,33720.0,123.195501,117.789474,154.391304,193.730909,225.000000,279.917513,248.650000,340.025000,455.000000,554.042857,854541.0,544663.0,275661.0,269002.0,505564.0,84394.0,85745.0,500650.0,139757.0,301060.0,53032.0,52400.0,307072.0,83352.0,417735.0,71817.0,211401.0,40380.0,41.40,62.93,89.61,56.39,60.21,78.61,0.55,14.18,18.80,2.27,1.87,6.26,49.39,50.61,28.00,4.67,4.75,27.73,7.74,27.70,4.88,4.82,28.25,7.67,23.14,3.98,19.45,3.71
1,1-DAILY,office,no,no,3087,3085,154177.0,118548.0,101751.0,207229.0,130806.0,1501.0,34628.0,31260.0,8895.0,138.0,67389.0,5130.0,2976.0,113.764107,109.000000,139.500000,174.533333,202.938462,357.728418,308.000000,434.281955,619.440278,772.303846,102095.0,34671.0,20738.0,13933.0,102341.0,19791.0,14967.0,20204.0,9633.0,63358.0,13189.0,9932.0,12813.0,6015.0,28979.0,8119.0,16667.0,4772.0,42.40,76.89,85.83,66.00,63.12,78.05,0.72,16.71,15.08,2.48,1.44,4.36,40.19,59.81,49.39,9.55,7.22,9.75,4.65,48.44,10.08,7.59,9.80,4.60,13.98,3.92,12.74,3.65
2,1-DAILY,office,no,yes,4302,4302,201380.0,159263.0,141958.0,287155.0,184149.0,1772.0,48056.0,43283.0,9740.0,153.0,93111.0,7483.0,3898.0,107.918005,101.300000,134.500000,170.500000,198.166667,336.456653,284.750000,409.000000,576.450000,716.455556,144409.0,53047.0,25105.0,27942.0,125848.0,32739.0,23999.0,28545.0,14939.0,79578.0,21322.0,15771.0,18611.0,9433.0,44853.0,12356.0,26378.0,7182.0,42.81,79.09,89.13,70.49,64.13,78.42,0.62,16.74,15.07,2.61,1.36,3.45,52.67,47.33,43.83,11.40,8.36,9.94,5.20,43.21,11.58,8.56,10.11,5.12,15.62,4.30,14.32,3.90
3,1-DAILY,office,yes,no,3955,3953,206586.0,161452.0,134413.0,266365.0,165875.0,2086.0,43467.0,40350.0,14424.0,161.0,85903.0,6028.0,3603.0,121.093737,115.909091,149.767857,185.180000,212.953846,355.838763,301.527273,422.812500,607.571429,754.891667,130500.0,47884.0,30595.0,17289.0,119398.0,32103.0,22021.0,25209.0,14590.0,73414.0,20694.0,14207.0,15555.0,9025.0,38399.0,12728.0,21556.0,7038.0,41.96,78.15,83.25,65.06,62.27,78.67,0.78,16.32,15.15,2.26,1.35,5.48,36.11,63.89,44.82,12.05,8.27,9.46,5.48,44.26,12.48,8.56,9.38,5.44,14.42,4.78,13.00,4.24
4,1-DAILY,office,yes,yes,49690,49685,2323568.0,1890918.0,1687258.0,3362261.0,2037621.0,22192.0,563333.0,554110.0,183584.0,1404.0,1139635.0,81698.0,50715.0,120.279269,115.437500,148.333333,184.000000,211.182857,295.747630,256.000000,356.632997,492.333333,602.847222,1615559.0,881187.0,471873.0,409314.0,1164471.0,447032.0,295427.0,398826.0,256906.0,694572.0,272726.0,183408.0,241128.0,153658.0,699970.0,147503.0,362542.0,82440.0,41.01,81.38,89.23,72.61,60.60,79.29,0.66,16.75,16.48,2.43,1.51,5.50,46.45,53.55,34.63,13.30,8.79,11.86,7.64,34.09,13.38,9.00,11.83,7.54,20.82,4.39,17.79,4.05
5,1-DAILY,other,iOS,iOS,3722,3722,208771.0,136992.0,119608.0,219359.0,135225.0,1037.0,29364.0,39568.0,14075.0,89.0,69969.0,4798.0,3780.0,117.025144,112.394444,149.559091,191.691667,220.000000,282.167351,244.400000,338.230769,471.571429,591.986667,109328.0,58630.0,38092.0,20538.0,64938.0,14300.0,11909.0,57051.0,13686.0,39923.0,9175.0,7731.0,35443.0,8309.0,1789.0,9050.0,0.0,4915.0,36.33,65.62,87.31,57.29,61.65,80.85,0.47,13.39,18.04,2.19,1.72,6.46,35.03,64.97,29.60,6.52,5.43,26.01,6.24,29.52,6.78,5.72,26.21,6.14,0.82,4.13,0.00,3.63
6,1-DAILY,other,no,no,1474,1458,60359.0,47842.0,41266.0,84955.0,53638.0,533.0,13637.0,13096.0,3986.0,65.0,27266.0,2296.0,1652.0,112.041479,105.000000,141.200000,181.000000,217.957143,375.136692,311.900000,461.857143,671.375000,840.000000,43001.0,13017.0,8185.0,4832.0,43421.0,10979.0,6945.0,6761.0,2689.0,26978.0,7511.0,4397.0,4304.0,1782.0,518.0,3215.0,0.0,1774.0,36.79,79.26,86.25,68.37,63.14,80.17,0.63,16.05,15.42,2.70,1.94,4.77,37.12,62.88,51.11,12.92,8.17,7.96,3.17,50.30,14.00,8.20,8.02,3.32,0.61,3.78,0.00,3.31
7,1-DAILY,other,no,yes,1751,1749,70930.0,57326.0,51789.0,102156.0,67089.0,443.0,15471.0,14946.0,4146.0,61.0,30860.0,2603.0,1432.0,108.304708,102.000000,136.000000,171.100000,202.000000,361.657136,301.340909,446.401515,641.575000,828.450000,53858.0,16346.0,8271.0,8075.0,46237.0,14495.0,10328.0,8435.0,3584.0,29693.0,9869.0,7023.0,5691.0,2347.0,447.0,3632.0,0.0,2141.0,38.36,80.82,90.34,73.01,65.67,80.28,0.43,15.14,14.63,2.55,1.40,4.12,49.40,50.60,45.26,14.19,10.11,8.26,3.51,44.26,14.71,10.47,8.48,3.50,0.44,3.56,0.00,3.19
8,1-DAILY,other,yes,no,1965,1955,84779.0,68491.0,57679.0,116401.0,72262.0,981.0,19207.0,17692.0,6203.0,56.0,37880.0,2934.0,2673.0,118.410041,112.575000,148.308333,188.000000,218.517857,361.883715,296.373626,441.275000,644.175000,835.200000,57908.0,19596.0,12668.0,6928.0,56128.0,17452.0,8835.0,9268.0,4983.0,33699.0,11607.0,5824.0,5844.0,3243.0,1224.0,4467.0,0.0,2408.0,36.96,80.79,84.21,68.03,62.08,80.14,0.84,16.50,15.20,2.52,2.30,5.38,35.35,64.65,48.22,14.99,7.59,7.96,4.28,46.63,16.06,8.06,8.09,4.49,1.05,3.84,0.00,3.33
9,1-DAILY,other,yes,yes,12640,12618,513364.0,425891.0,373343.0,735676.0,456963.0,5101.0,113324.0,119016.0,40957.0,307.0,237441.0,16442.0,12038.0,118.342790,113.800000,148.000000,184.000000,211.525000,312.037398,263.038462,376.045455,534.187500,662.080966,369566.0,167714.0,107127.0,60587.0,263063.0,133866.0,73210.0,69944.0,42925.0,159749.0,84439.0,46956.0,43544.0,26448.0,5366.0,30021.0,0.0,15728.0,36.22,82.96,87.66,72.72,62.11,80.87,0.69,15.40,16.18,2.23,1.64,5.61,36.13,63.87,35.76,18.20,9.95,9.51,5.83,34.96,18.48,10.28,9.53,5.79,0.73,4.08,0.00,3.44
10,2-WEEKLY,office,iOS,iOS,57125,57098,1598677.0,1011677.0,831859.0,1545920.0,906764.0,9832.0,235266.0,283397.0,110040.0,612.0,528495.0,36003.0,24842.0,123.743078,114.888889,159.175000,209.500000,248.000000,296.481234,246.166667,364.250000,527.500000,671.000000,678868.0,382279.0,186779.0,195500.0,447565.0,58128.0,71896.0,467110.0,125364.0,257656.0,35662.0,42781.0,280276.0,73540.0,411325.0,80668.0,202808.0,44390.0,15.88,63.28,82.23,52.03,58.66,74.87,0.64,15.22,18.33,2.33,1.61,7.16,51.14,48.86,28.95,3.76,4.65,30.22,8.11,28.41,3.93,4.72,30.91,8.11,26.61,5.22,22.37,4.90
11,2-WEEKLY,office,no,no,8887,8879,188189.0,145771.0,109864.0,217894.0,135672.0,2020.0,36308.0,33993.0,9711.0,189.0,72321.0,5013.0,2603.0,111.528226,102.600000,142.000000,188.500000,222.500000,405.386990,321.250000,501.625000,748.650000,973.000000,101512.0,27910.0,13566.0,14344.0,117722.0,14550.0,14093.0,22145.0,10865.0,72647.0,9328.0,9021.0,14119.0,6531.0,32752.0,14009.0,19165.0,7546.0,15.28,77.46,75.37,58.38,62.27,74.82,0.93,16.66,15.60,2.30,1.19,4.54,51.39,48.61,54.03,6.68,6.47,10.16,4.99,53.55,6.88,6.65,10.41,4.81,15.03,6.43,14.13,5.56
12,2-WEEKLY,office,no,yes,13065,13062,254188.0,201743.0,159736.0,315232.0,201271.0,2254.0,51782.0,47922.0,11785.0,216.0,101958.0,7237.0,3426.0,108.712672,99.250000,137.750000,182.000000,217.075000,369.360255,293.450000,453.316964,676.000000,889.910000,152069.0,49201.0,21108.0,28093.0,149741.0,26714.0,24289.0,32710.0,18080.0,93959.0,17563.0,16062.0,21110.0,11378.0,52423.0,19811.0,31426.0,11227.0,15.41,79.37,79.18,62.84,63.85,75.55,0.72,16.43,15.20,2.30,1.09,3.81,57.10,42.90,47.50,8.47,7.71,10.38,5.74,46.68,8.73,7.98,10.49,5.65,16.63,6.28,15.61,5.58
13,2-WEEKLY,office,yes,no,10666,10648,228271.0,180599.0,132452.0,257278.0,158483.0,2512.0,41773.0,40098.0,14178.0,234.0,84383.0,5351.0,3428.0,118.315433,110.000000,149.607692,195.280000,234.000000,388.334898,305.333333,477.600000,724.000000,960.000000,119541.0,36763.0,19590.0,17173.0,129322.0,22367.0,19092.0,26024.0,14636.0,79261.0,14180.0,12020.0,16261.0,8838.0,42457.0,17115.0,24000.0,9022.0,14.88,79.12,73.34,58.02,61.60,75.43,0.98,16.24,15.59,2.08,1.33,5.60,46.71,53.29,50.27,8.69,7.42,10.12,5.69,50.01,8.95,7.58,10.26,5.58,16.50,6.65,15.14,5.69
14,2-WEEKLY,office,yes,yes,119243,119200,2435800.0,1990159.0,1599300.0,3116632.0,1849139.0,24571.0,540632.0,511363.0,189447.0,1463.0,1076566.0,75002.0,39882.0,120.705651,112.692105,153.250000,200.000000,235.333333,317.051141,257.333333,389.000000,575.333333,743.000000,1409692.0,687894.0,345478.0,342416.0,1209749.0,302033.0,255433.0,382714.0,260939.0,710054.0,180489.0,153705.0,226001.0,153433.0,750013.0,182111.0,379077.0,99475.0,15.51,81.70,80.36,65.66,59.33,76.24,0.79,17.35,16.41,2.41,1.28,6.13,49.78,50.22,38.82,9.69,8.20,12.28,8.37,38.40,9.76,8.31,12.22,8.30,24.06,5.84,20.50,5.38
15,2-WEEKLY,other,iOS,iOS,14875,14849,341010.0,221928.0,175313.0,319282.0,190877.0,1691.0,46036.0,59224.0,21310.0,143.0,106951.0,7637.0,5239.0,117.857360,108.000000,152.500000,206.000000,248.185714,308.755201,241.833333,373.666667,567.200000,747.100000,149192.0,62389.0,36420.0,25969.0,97524.0,16934.0,17062.0,91454.0,18735.0,57636.0,10738.0,10547.0,55565.0,10889.0,6307.0,18822.0,0.0,10026.0,12.85,65.08,79.00,51.41,59.78,78.16,0.53,14.42,18.55,2.39,1.64,6.72,41.62,58.38,30.54,5.30,5.34,28.64,5.87,30.20,5.63,5.53,29.11,5.70,1.98,5.90,0.00,5.25
16,2-WEEKLY,other,no,no,6739,6695,123877.0,97529.0,72574.0,145178.0,88825.0,1274.0,23593.0,24143.0,7211.0,132.0,49010.0,3400.0,2406.0,110.452384,100.226190,142.000000,189.250000,227.650000,413.319117,323.562500,497.500000,783.300000,1023.062500,67922.0,17628.0,8812.0,8816.0,84011.0,12120.0,9411.0,12259.0,5095.0,50862.0,7705.0,5920.0,7733.0,3139.0,1665.0,7738.0,0.0,4231.0,13.27,78.73,74.41,58.59,61.18,76.47,0.88,16.25,16.63,2.34,1.66,5.06,50.01,49.99,57.87,8.35,6.48,8.44,3.51,57.26,8.67,6.66,8.71,3.53,1.15,5.33,0.00,4.76
17,2-WEEKLY,other,no,yes,8414,8396,141729.0,113506.0,89628.0,177050.0,112859.0,1126.0,27437.0,28090.0,7410.0,125.0,56653.0,3959.0,2250.0,109.069076,98.500000,139.593750,188.000000,225.000000,382.513952,299.500000,478.410714,719.000000,944.527778,86431.0,24603.0,11186.0,13417.0,89353.0,18228.0,13836.0,15757.0,7199.0,56067.0,12236.0,8797.0,10307.0,4511.0,1456.0,9006.0,0.0,5055.0,13.44,80.09,78.96,63.24,63.74,76.58,0.64,15.50,15.87,2.24,1.27,4.26,54.53,45.47,50.47,10.30,7.81,8.90,4.07,49.68,10.84,7.79,9.13,4.00,0.82,5.09,0.00,4.48
18,2-WEEKLY,other,yes,no,7541,7471,138422.0,111676.0,81933.0,160248.0,97323.0,1493.0,25162.0,26527.0,9608.0,132.0,53182.0,3413.0,3693.0,116.940915,108.000000,149.770833,201.500000,238.000000,392.903730,301.000000,484.000000,757.000000,1013.266667,75056.0,22188.0,12289.0,9899.0,83856.0,16748.0,12994.0,13563.0,7274.0,50824.0,10798.0,7915.0,8265.0,4107.0,2712.0,8637.0,0.0,4614.0,13.03,80.68,73.37,59.19,60.73,77.12,0.93,15.70,16.55,2.13,2.30,6.08,44.61,55.39,52.33,10.45,8.11,8.46,4.54,52.22,11.10,8.13,8.49,4.22,1.69,5.39,0.00,4.74
19,2-WEEKLY,other,yes,yes,49811,49689,862165.0,711603.0,552442.0,1065010.0,643723.0,7862.0,171255.0,178761.0,62819.0,578.0,357878.0,24795.0,15487.0,116.871547,108.800000,150.000000,198.000000,235.000000,334.638602,264.000000,413.750000,625.000000,823.000000,503355.0,191990.0,109484.0,82506.0,445904.0,133220.0,94358.0,111340.0,61021.0,265478.0,82123.0,58310.0,67361.0,36427.0,15647.0,60382.0,0.0,32077.0,12.96,82.54,77.63,64.08,60.44,78.19,0.74,16.08,16.78,2.33,1.45,5.95,42.97,57.03,41.87,12.51,8.86,10.45,5.73,41.24,12.76,9.06,10.46,5.66,1.47,5.67,0.00,4.98
20,3-MONTHLY,office,iOS,iOS,177695,172128,2049107.0,1322496.0,991613.0,1831416.0,1096417.0,12837.0,286920.0,309501.0,124793.0,936.0,609258.0,40237.0,23186.0,123.454467,111.743421,162.666667,222.394737,264.666667,329.116662,247.000000,406.000000,647.000000,865.000000,793544.0,363142.0,148333.0,214809.0,546274.0,50663.0,75433.0,579166.0,147151.0,321549.0,31149.0,44644.0,354944.0,88850.0,545641.0,114082.0,293934.0,63472.0,6.37,64.54,74.98,48.39,59.87,72.38,0.70,15.67,16.90,2.20,1.27,6.87,59.15,40.85,29.83,2.77,4.12,31.62,8.03,29.33,2.84,4.07,32.37,8.10,29.79,6.23,26.81,5.79
21,3-MONTHLY,office,no,no,67597,65517,552751.0,432433.0,268999.0,542203.0,342370.0,6044.0,81641.0,83929.0,27612.0,603.0,171614.0,10071.0,4671.0,114.407548,102.333333,148.500000,203.666667,245.000000,476.269365,355.000000,594.000000,951.000000,1276.000000,245872.0,56673.0,23386.0,33287.0,336338.0,20425.0,24237.0,51665.0,28100.0,211931.0,13004.0,15418.0,33474.0,17339.0,111744.0,44670.0,72857.0,24921.0,5.23,78.23,62.21,48.67,63.14,71.81,1.11,15.06,15.48,1.86,0.86,5.20,58.74,41.26,62.03,3.77,4.47,9.53,5.18,61.90,3.80,4.50,9.78,5.06,20.61,8.24,21.28,7.28
22,3-MONTHLY,office,no,yes,74900,72924,586373.0,470659.0,311387.0,614668.0,396824.0,5223.0,97259.0,90533.0,24303.0,523.0,193015.0,12426.0,4784.0,110.883976,99.000000,143.500000,198.000000,238.000000,425.662346,315.500000,533.000000,849.966667,1131.000000,288255.0,77321.0,27875.0,49446.0,332607.0,29418.0,32863.0,65193.0,37309.0,212718.0,19638.0,21096.0,42541.0,24067.0,132288.0,48510.0,86530.0,27703.0,5.44,80.27,66.16,53.10,64.56,72.64,0.85,15.82,14.73,2.02,0.78,4.04,63.95,36.05,54.11,4.79,5.35,10.61,6.07,53.61,4.95,5.32,10.72,6.06,21.52,7.89,21.81,6.98
23,3-MONTHLY,office,yes,no,56731,54743,475769.0,382029.0,239881.0,474960.0,297869.0,4940.0,73531.0,71008.0,27123.0,485.0,149479.0,8555.0,4459.0,119.639675,108.000000,156.000000,212.000000,252.000000,452.099345,328.000000,558.500000,904.000000,1243.850000,216305.0,51474.0,22532.0,28942.0,273846.0,23007.0,25570.0,46947.0,27887.0,170847.0,14665.0,16011.0,29912.0,17342.0,102094.0,40084.0,64702.0,22134.0,5.44,80.30,62.79,50.42,62.71,72.62,1.04,15.48,14.95,1.80,0.94,5.81,56.23,43.77,57.66,4.84,5.38,9.88,5.87,57.36,4.92,5.38,10.04,5.82,21.50,8.44,21.72,7.43
24,3-MONTHLY,office,yes,yes,421412,408250,3552680.0,2937404.0,2061642.0,4005117.0,2434348.0,34620.0,695872.0,609392.0,228651.0,2213.0,1339884.0,89101.0,38616.0,121.380365,110.000000,158.000000,215.500000,257.000000,357.327352,265.000000,441.000000,702.377143,943.000000,1798753.0,695026.0,291531.0,403495.0,1758089.0,252139.0,271603.0,501506.0,340316.0,1061746.0,153227.0,164190.0,304823.0,206071.0,1108488.0,284631.0,622098.0,157664.0,5.96,82.68,70.19,58.03,60.78,73.89,0.86,17.37,15.22,2.22,0.96,5.76,58.05,41.95,43.90,6.30,6.78,12.52,8.50,43.62,6.29,6.74,12.52,8.47,27.68,7.11,25.56,6.48
25,3-MONTHLY,other,iOS,iOS,184559,165327,1207332.0,811026.0,552052.0,1015378.0,604106.0,7025.0,158784.0,179514.0,65228.0,714.0,345323.0,22742.0,12610.0,118.390168,104.500000,158.414286,221.666667,264.000000,351.996253,245.000000,432.666667,722.533333,990.700000,451419.0,149477.0,60634.0,88843.0,324894.0,34335.0,46757.0,306985.0,61502.0,191244.0,21277.0,27549.0,187286.0,35317.0,37258.0,85656.0,2.0,47334.0,3.65,67.18,68.07,45.72,59.50,74.73,0.69,15.64,17.68,2.24,1.24,6.49,59.44,40.56,32.00,3.38,4.60,30.23,6.06,31.66,3.52,4.56,31.00,5.85,3.67,8.44,0.00,7.84
26,3-MONTHLY,other,no,no,148544,136894,867420.0,683197.0,394818.0,806567.0,491459.0,10094.0,116573.0,138821.0,48410.0,1202.0,265488.0,14473.0,8313.0,114.012972,101.500000,150.000000,207.650000,249.000000,515.475626,371.000000,642.000000,1056.000000,1448.000000,356304.0,79067.0,29556.0,49511.0,529027.0,30818.0,37543.0,68818.0,31377.0,322265.0,18965.0,22363.0,43231.0,18562.0,13544.0,75022.0,1.0,41857.0,3.59,78.76,57.79,45.52,60.93,72.50,1.25,14.45,17.21,1.79,1.03,6.15,62.62,37.38,65.59,3.82,4.65,8.53,3.89,65.57,3.86,4.55,8.80,3.78,1.68,9.30,0.00,8.52
27,3-MONTHLY,other,no,yes,143203,132973,776253.0,626423.0,385208.0,765274.0,480984.0,6956.0,114127.0,125218.0,37161.0,822.0,246301.0,15041.0,7156.0,111.692197,98.900000,147.000000,205.000000,247.000000,460.172822,329.375000,571.000000,941.500000,1287.000000,351996.0,87897.0,30172.0,57725.0,436026.0,40075.0,45552.0,72003.0,35295.0,272338.0,25865.0,28257.0,46609.0,21687.0,13233.0,67920.0,0.0,38435.0,3.62,80.70,61.49,49.62,62.85,73.18,0.91,14.91,16.36,1.97,0.94,4.96,65.67,34.33,56.98,5.24,5.95,9.41,4.61,56.62,5.38,5.87,9.69,4.51,1.73,8.88,0.00,7.99
28,3-MONTHLY,other,yes,no,117351,106112,685483.0,556633.0,321933.0,639884.0,386372.0,7866.0,96563.0,106791.0,41489.0,799.0,211220.0,11591.0,9261.0,118.640528,106.000000,156.333333,217.000000,258.000000,476.027403,333.000000,586.000000,987.000000,1371.000000,285336.0,69185.0,28875.0,40310.0,388032.0,32733.0,36285.0,57059.0,28939.0,234790.0,20359.0,21479.0,35417.0,16526.0,14365.0,58774.0,2.0,32008.0,3.64,81.20,57.84,46.96,60.38,73.85,1.23,15.09,16.69,1.81,1.45,6.61,58.26,41.74,60.64,5.12,5.67,8.92,4.52,60.77,5.27,5.56,9.17,4.28,2.24,9.19,0.00,8.28
29,3-MONTHLY,other,yes,yes,593864,537338,3214290.0,2684678.0,1694791.0,3267109.0,1966675.0,27073.0,542310.0,538798.0,189642.0,2571.0,1108181.0,70068.0,34173.0,118.984431,106.000000,158.000000,218.000000,260.000000,390.695749,274.000000,481.150000,800.000000,1099.000000,1482370.0,451293.0,191597.0,259696.0,1573665.0,225866.0,236046.0,357254.0,196820.0,941141.0,138728.0,140999.0,216366.0,115788.0,91649.0,281446.0,1.0,154772.0,3.66,83.52,63.13,52.73,60.20,75.37,0.83,16.60,16.49,2.14,1.05,5.88,57.54,42.46,48.17,6.91,7.22,10.93,6.02,47.85,7.05,7.17,11.00,5.89,2.81,8.61,0.00,7.87
30,4-OTHER,office,iOS,iOS,39364,39059,405952.0,259635.0,188147.0,268052.0,170988.0,2980.0,38180.0,39248.0,16511.0,142.0,80408.0,5108.0,3575.0,122.949559,109.500000,163.000000,226.000000,273.000000,366.143630,267.550000,448.000000,731.000000,997.175000,119425.0,45991.0,14560.0,31431.0,76149.0,3698.0,7871.0,105299.0,19126.0,48306.0,2382.0,4934.0,68086.0,12648.0,105867.0,14648.0,66673.0,8593.0,4.38,63.96,72.47,46.35,63.79,69.84,1.11,14.24,14.64,1.91,1.33,6.21,68.34,31.66,28.41,1.38,2.94,39.28,7.14,28.25,1.39,2.89,39.82,7.40,39.49,5.46,38.99,5.03
31,4-OTHER,office,no,no,28900,28698,201624.0,154864.0,86774.0,136335.0,92456.0,1346.0,16124.0,19186.0,7065.0,158.0,36656.0,1951.0,896.0,116.495370,104.000000,153.333333,212.350000,255.000000,531.707099,388.000000,671.000000,1080.000000,1470.000000,63966.0,12096.0,4638.0,7458.0,88525.0,2858.0,5248.0,12258.0,8297.0,60030.0,1848.0,3345.0,8488.0,5699.0,47955.0,11159.0,36338.0,6563.0,3.22,76.81,56.03,43.04,67.82,69.19,0.99,11.83,14.07,1.43,0.66,5.30,61.66,38.34,64.93,2.10,3.85,8.99,6.09,64.93,2.00,3.62,9.18,6.16,35.17,8.18,39.30,7.10
32,4-OTHER,office,no,yes,22044,21903,150173.0,119769.0,70245.0,113717.0,77860.0,987.0,14965.0,15295.0,4517.0,93.0,31247.0,1761.0,843.0,115.053865,103.000000,150.000000,205.750000,248.625000,466.575441,346.000000,579.000000,948.000000,1250.700000,54917.0,12794.0,4578.0,8216.0,64127.0,3196.0,5432.0,11702.0,7919.0,43815.0,2175.0,3603.0,8074.0,5554.0,39296.0,8741.0,29480.0,5216.0,3.55,79.75,58.65,46.78,68.47,70.53,0.87,13.16,13.45,1.55,0.74,4.05,64.22,35.78,56.39,2.81,4.78,10.29,6.96,56.27,2.79,4.63,10.37,7.13,34.56,7.69,37.86,6.70
33,4-OTHER,office,yes,no,19770,19621,138274.0,109798.0,63612.0,99655.0,67311.0,965.0,12534.0,12945.0,5818.0,82.0,26444.0,1405.0,682.0,123.119049,111.966667,161.666667,219.000000,263.000000,509.510938,363.000000,621.800000,1035.000000,1429.000000,47472.0,10242.0,4336.0,5906.0,59986.0,2684.0,4647.0,9703.0,6960.0,40512.0,1776.0,3041.0,6575.0,4814.0,35290.0,7765.0,26118.0,4510.0,3.43,79.41,57.94,46.00,67.54,70.53,0.97,12.58,12.99,1.41,0.68,5.92,57.66,42.34,60.19,2.69,4.66,9.74,6.98,60.19,2.64,4.52,9.77,7.15,35.41,7.79,38.80,6.70

In [47]:
segment_office_travel_qc.to_clipboard(index=False)

In [31]:
segment_agg_df

,segment,gross_customers,net_customers,ao_session,fe_session,rr_session,rr_count,net_count,cobrm_count,cobra_count,ocara_count,expired_count,aborted_count,canceltn_count,quick_cobra,quick_ocara,cobra_ttc_mean,cobra_ttc_p50,cobra_ttc_p75,cobra_ttc_p90,cobra_ttc_p95,ocara_ttc_mean,ocara_ttc_p50,ocara_ttc_p75,ocara_ttc_p90,ocara_ttc_p95,haps_orders,bid_orders,negative_bid,positive_bid,gross_psm_gps,gross_psm_fav_recent_history,gross_psm_google_search,gross_psm_stickylocation,gross_psm_hotspot,net_psm_gps,net_psm_fav_recent_history,net_psm_google_search,net_psm_fav_stickylocation,net_psm_hotspot,office_gross,transit_gross,office_net,transit_net,rpc,a02fe,fe2rr,ao2rr,g2n,haps%,cobrm%,cobra%,ocara%,quick_cobra%,quick_ocara%,expired%,positive_bid%,negative_bid%,gross_psm_gps%,gross_psm_fav_recent_history%,gross_psm_google_search%,gross_psm_stickylocation%,gross_psm_hotspot%,net_psm_gps%,net_psm_fav_recent_history%,net_psm_google_search%,net_psm_fav_stickylocation%,net_psm_hotspot%,office_gross%,transit_gross%,office_net%,transit_net%
0,1-DAILY,108842,108783,5519284.0,4133553.0,3665006.0,7186895.0,4390671.0,45587.0,1136501.0,1212694.0,398370.0,3037.0,2394782.0,170409.0,116487.0,119.729164,114.600000,148.909091,186.000000,214.60125,302.081349,259.70,364.465199,506.408715,626.500,3480765.0,1836755.0,998315.0,838440.0,2491409.0,807151.0,553386.0,1124893.0,503692.0,1502024.0,503564.0,347649.0,690005.0,303612.0,1239280.0,302908.0,638544.0,168778.0,40.36,74.89,88.66,66.40,61.09,79.28,0.63,15.81,16.87,2.37,1.62,5.59,45.65,54.35,34.67,11.23,7.70,15.65,7.01,34.21,11.47,7.92,15.72,6.91,17.24,4.21,14.54,3.84
1,2-WEEKLY,296366,295987,6312328.0,4786191.0,3805101.0,7319724.0,4384936.0,54635.0,1199244.0,1233518.0,443519.0,3824.0,2487397.0,171810.0,103256.0,119.115607,110.571429,152.250000,200.333333,237.20000,328.506119,262.25,402.000000,602.000000,787.000,3343638.0,1502845.0,764712.0,738133.0,2854747.0,621042.0,532464.0,1175076.0,529208.0,1694444.0,380822.0,325078.0,706998.0,312793.0,1316757.0,418299.0,656476.0,227663.0,14.81,75.82,79.50,60.28,59.91,76.25,0.75,16.38,16.85,2.35,1.41,6.11,49.12,50.88,39.00,8.48,7.27,16.05,7.23,38.64,8.68,7.41,16.12,7.13,17.99,5.71,14.97,5.19
2,3-MONTHLY,1985856,1852206,13967458.0,10906978.0,7222324.0,13962576.0,8497424.0,122678.0,2263580.0,2253505.0,814412.0,10868.0,4639763.0,294305.0,147229.0,118.915389,106.500000,156.600000,216.000000,257.00000,396.200230,282.00,488.000000,803.000000,1100.000,6270154.0,2080555.0,854491.0,1226064.0,6498798.0,739479.0,831889.0,2106596.0,934696.0,3940569.0,456877.0,502006.0,1294603.0,561549.0,2170304.0,1100795.0,1140127.0,610300.0,4.59,78.09,66.22,51.71,60.86,73.79,0.88,16.21,16.14,2.11,1.05,5.91,58.93,41.07,46.54,5.30,5.96,15.09,6.69,46.37,5.38,5.91,15.24,6.61,15.54,7.88,13.42,7.18
3,4-OTHER,1047498,947804,5093346.0,3976431.0,2274994.0,3567488.0,2299745.0,35107.0,488247.0,531406.0,209405.0,3545.0,1054760.0,58969.0,29874.0,120.280797,106.200000,160.200000,224.000000,266.00000,470.181758,323.00,583.000000,983.000000,1364.000,1643422.0,432591.0,147732.0,284859.0,1844713.0,102617.0,187416.0,525516.0,231829.0,1191783.0,63822.0,117944.0,341453.0,148958.0,517771.0,345722.0,301006.0,209133.0,2.43,78.07,57.21,44.67,64.46,71.46,0.98,13.69,14.90,1.65,0.84,5.97,65.85,34.15,51.71,2.88,5.25,14.73,6.50,51.82,2.78,5.13,14.85,6.48,14.51,9.69,13.09,9.09
4,5-INACTIVE,107404,98363,303552.0,272022.0,0.0,675334.0,421041.0,5340.0,109779.0,102663.0,36031.0,477.0,217782.0,14253.0,7057.0,118.962526,107.666667,156.641026,214.000000,254.00000,403.746654,285.10,490.000000,811.450000,1126.475,315415.0,98786.0,48824.0,49962.0,309852.0,51648.0,45914.0,68714.0,42868.0,192505.0,32160.0,28489.0,43054.0,26364.0,96263.0,57758.0,52816.0,32976.0,4.28,89.61,0.00,0.00,62.35,74.91,0.79,16.26,15.20,2.11,1.04,5.41,50.58,49.42,45.88,7.65,6.80,10.17,6.35,45.72,7.64,6.77,10.23,6.26,14.25,8.55,12.54,7.83