In [1]:
import numpy as np
import pandas as pd
from pyhive import presto
from datetime import timedelta,datetime
import json
import requests
import math
import os


pd.set_option('display.max_columns', None)
import warnings
warnings.filterwarnings("ignore")
conn = presto.connect(
        host="presto-gateway.serving.data.plectrum.dev",
        port=80,
        username="manoj.ravirajan@rapido.bike"
    )
presto_port = '80'
username = 'manoj.ravirajan@rapido.bike'
conn1 = presto.connect('bi-presto.serving.data.production.internal', presto_port, username)
conn2 = presto.connect('bi-trino-2.serving.data.production.internal', presto_port, username)
conn3= presto.connect('processing-2.processing.data.production.internal',presto_port,username)
conn4= presto.connect('processing.processing.data.production.internal',presto_port,username)

### Loading data and merging

In [2]:
daily_segment_df = pd.read_sql(f"""select * from hive.experiments_internal.customer_segmentation_amj2025""", conn2)

In [3]:
# rha_qc_segment_df = pd.read_sql(f"""select * from hive.experiments_internal.rha_qc_segment_20250406""", conn3)
rha_qc_segment_df = pd.read_sql(f"""select customer_id, 
                                           office_tag, os, 
                                           travelridehailing, 
                                           quick_commerce from hive.experiments_internal.rha_qc_usecase_segment_20250406""", conn2)

In [4]:
# rf_daily_df = pd.read_sql(f"""select * from hive.experiments_internal.rf_daily_30days_20250317""", conn2)
rf_daily_df = pd.read_sql(f"""select * from hive.experiments_internal.rf_daily_30days_20250317_v1""", conn2)

In [7]:
# olf_g2n_df = pd.read_sql(f"""select * from hive.experiments_internal.olf_g2n_30days_20250317""", conn3)
# olf_g2n_df = pd.read_sql(f"""select * from hive.experiments_internal.olf_g2n_30days_20250317_v1""", conn2)
olf_g2n_df = pd.read_sql(f"""select * from hive.experiments_internal.olf_g2n_30days_20250317_v2""", conn2)

In [8]:
olf_geo_usecase_df = pd.read_sql(f"""select * from hive.experiments_internal.olf_geo_usecase_20250317""", conn2)

In [9]:
retries_aoferr_df = pd.read_sql(f"""select * from hive.experiments_internal.retries_aoferr_30days_20250317""", conn2)

In [10]:
ccfr_comm_df = pd.read_sql(f"""select * from hive.experiments_internal.ratings_custcapcomm_30days_20250317_30days""", conn2)

In [11]:
sup_tikt_df =  pd.read_sql(f"""select * from hive.experiments_internal.support_ticket_20250317_30days""", conn2)
sup_tikt_df = sup_tikt_df[sup_tikt_df['customer_id']!='customer_id']

In [12]:
cust_rrsessns_df = pd.read_sql(f"""select * from hive.experiments_internal.customer_rr_sessions_20250317_30days""", conn2)

In [13]:
merged_df = daily_segment_df.merge(rha_qc_segment_df, on = 'customer_id', how='left')
merged_df = merged_df.merge(rf_daily_df, on = 'customer_id', how='left')
merged_df = merged_df.merge(olf_g2n_df, on = 'customer_id', how='left')
merged_df = merged_df.merge(olf_geo_usecase_df, on = 'customer_id', how='left')
merged_df = merged_df.merge(retries_aoferr_df, on = 'customer_id', how='left')
merged_df = merged_df.merge(ccfr_comm_df, on = 'customer_id', how='left')
merged_df = merged_df.merge(sup_tikt_df, on = 'customer_id', how='left')
merged_df = merged_df.merge(cust_rrsessns_df, on = 'customer_id', how='left')
merged_df.head()

,customer_id,segment,office_tag,os,travelridehailing,quick_commerce,ao_session,fe_session,rr_session,ao2fe_delta_mean,fe2rr_delta_mean,ao2rr_delta_mean,rr_count,net_count,cobrm_count,cobra_count,ocara_count,canceltn_count,quick_cobra,quick_ocara,cobra_ttc,ocara_ttc,tta,rider_canceltn_count,expired_count,aborted_count,haps_orders,bid_orders,negative_bid,positive_bid,gross_psm_gps,gross_psm_fav_recent_history,gross_psm_google_search,gross_psm_stickylocation,gross_psm_hotspot,net_psm_gps,net_psm_fav_recent_history,net_psm_google_search,net_psm_fav_stickylocation,net_psm_hotspot,office_gross,transit_gross,office_net,transit_net,total_aos,total_ao_days,total_ao_sessions,total_fes,total_fe_days,total_fe_sessions,total_rrs,total_rr_days,total_rr_sessions,gross_orders,feedback_rating,rating_5,rating_4,rating_3,rating_2,rating_1,customer_call_captain,captain_call_customer,customer_msg_captain,captain_msg_customer,call_communication,msg_communication,communication,ocara_no,ocara_with_comm,ocara_without_comm,ocara_with_call,ocara_without_call,support_ticket,customer_rr_sessions
0,5e29174052f0da0a79fb9926,6-QUARTERLY,office,Android,no,yes,4,3,1,119.33333333333333,105.0,105.0,3,1,0,1,1,2,0,0,57.0,250.0,594.5,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,1,0,8,3,4,7.0,2.0,4.0,3.0,1.0,1.0,3,0,0,0,0,0,0,0,2,0,1,2,1,2,1,1,0,1,0,NaN,1
1,61d72742dd82c2c08b2055fd,8-RR-INACTIVE,other,Android,yes,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,67b348c94aa07b7847a59a90,6-QUARTERLY,other,Android,yes,yes,7,7,5,42.2,59.8,108.33333333333333,9,7,0,0,2,2,0,0,,1017.0,169.14285714285714,1,0,0,5,0,0,0,0,4,3,0,2,0,3,3,0,1,0,2,0,1,7,5,7,22.0,8.0,12.0,9.0,6.0,8.0,9,0,0,0,0,0,0,0,5,1,4,5,4,6,2,1,1,1,1,NaN,8
3,634a996109c7bf2528e04bc9,5-MONTHLY,other,iOS,blank,blank,1,1,0,26.0,,,1,1,0,0,0,0,0,0,,,27.0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,4.0,1.0,2.0,1.0,1.0,1.0,1,0,0,0,0,0,0,0,1,0,1,1,1,1,0,0,0,0,0,NaN,1
4,64ddedbb43ffc9ce64b116ac,2-HH-inActive,office,Android,yes,yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
merged_df.columns

Index(['customer_id', 'segment', 'office_tag', 'os', 'travelridehailing',
       'quick_commerce', 'ao_session', 'fe_session', 'rr_session',
       'ao2fe_delta_mean', 'fe2rr_delta_mean', 'ao2rr_delta_mean', 'rr_count',
       'net_count', 'cobrm_count', 'cobra_count', 'ocara_count',
       'canceltn_count', 'quick_cobra', 'quick_ocara', 'cobra_ttc',
       'ocara_ttc', 'tta', 'rider_canceltn_count', 'expired_count',
       'aborted_count', 'haps_orders', 'bid_orders', 'negative_bid',
       'positive_bid', 'gross_psm_gps', 'gross_psm_fav_recent_history',
       'gross_psm_google_search', 'gross_psm_stickylocation',
       'gross_psm_hotspot', 'net_psm_gps', 'net_psm_fav_recent_history',
       'net_psm_google_search', 'net_psm_fav_stickylocation',
       'net_psm_hotspot', 'office_gross', 'transit_gross', 'office_net',
       'transit_net', 'total_aos', 'total_ao_days', 'total_ao_sessions',
       'total_fes', 'total_fe_days', 'total_fe_sessions', 'total_rrs',
       'total_rr_days', 'total_rr_sessions', 'gross_orders', 'feedback_rating',
       'rating_5', 'rating_4', 'rating_3', 'rating_2', 'rating_1',
       'customer_call_captain', 'captain_call_customer',
       'customer_msg_captain', 'captain_msg_customer', 'call_communication',
       'msg_communication', 'communication', 'ocara_no', 'ocara_with_comm',
       'ocara_without_comm', 'ocara_with_call', 'ocara_without_call',
       'support_ticket', 'customer_rr_sessions'],
      dtype='object')

In [15]:
merged_df.to_parquet('merged_df_20250423.parquet')

#### Grouping

In [16]:
merged_df = pd.read_parquet('merged_df_20250423.parquet')

In [17]:
merged_df.shape

(4929725, 74)

In [18]:
merged_df

,customer_id,segment,office_tag,os,travelridehailing,quick_commerce,ao_session,fe_session,rr_session,ao2fe_delta_mean,fe2rr_delta_mean,ao2rr_delta_mean,rr_count,net_count,cobrm_count,cobra_count,ocara_count,canceltn_count,quick_cobra,quick_ocara,cobra_ttc,ocara_ttc,tta,rider_canceltn_count,expired_count,aborted_count,haps_orders,bid_orders,negative_bid,positive_bid,gross_psm_gps,gross_psm_fav_recent_history,gross_psm_google_search,gross_psm_stickylocation,gross_psm_hotspot,net_psm_gps,net_psm_fav_recent_history,net_psm_google_search,net_psm_fav_stickylocation,net_psm_hotspot,office_gross,transit_gross,office_net,transit_net,total_aos,total_ao_days,total_ao_sessions,total_fes,total_fe_days,total_fe_sessions,total_rrs,total_rr_days,total_rr_sessions,gross_orders,feedback_rating,rating_5,rating_4,rating_3,rating_2,rating_1,customer_call_captain,captain_call_customer,customer_msg_captain,captain_msg_customer,call_communication,msg_communication,communication,ocara_no,ocara_with_comm,ocara_without_comm,ocara_with_call,ocara_without_call,support_ticket,customer_rr_sessions
0,5e29174052f0da0a79fb9926,6-QUARTERLY,office,Android,no,yes,4,3,1,119.33333333333333,105.0,105.0,3,1,0,1,1,2,0,0,57.0,250.0,594.5,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,1,0,8,3,4,7.0,2.0,4.0,3.0,1.0,1.0,3,0,0,0,0,0,0,0,2,0,1,2,1,2,1,1,0,1,0,None,1
1,61d72742dd82c2c08b2055fd,8-RR-INACTIVE,other,Android,yes,yes,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2,67b348c94aa07b7847a59a90,6-QUARTERLY,other,Android,yes,yes,7,7,5,42.2,59.8,108.33333333333333,9,7,0,0,2,2,0,0,,1017.0,169.14285714285714,1,0,0,5,0,0,0,0,4,3,0,2,0,3,3,0,1,0,2,0,1,7,5,7,22.0,8.0,12.0,9.0,6.0,8.0,9,0,0,0,0,0,0,0,5,1,4,5,4,6,2,1,1,1,1,None,8
3,634a996109c7bf2528e04bc9,5-MONTHLY,other,iOS,blank,blank,1,1,0,26.0,,,1,1,0,0,0,0,0,0,,,27.0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,4.0,1.0,2.0,1.0,1.0,1.0,1,0,0,0,0,0,0,0,1,0,1,1,1,1,0,0,0,0,0,None,1
4,64ddedbb43ffc9ce64b116ac,2-HH-inActive,office,Android,yes,yes,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4929720,647d936f1edcd31fa9fe5e0a,6-QUARTERLY,office,Android,no,yes,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
4929721,67649fb866024a7fb199e66b,1-HH-Active,office,Android,yes,yes,5,4,1,11.75,39.0,54.0,2,1,0,1,0,1,0,0,51.0,,3.0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,1,0,0,0,0,5,4,5,6.0,3.0,4.0,2.0,1.0,1.0,2,0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,0,0,0,None,1
4929722,645c5e6a5d0cb382822829ea,4-WEEKLY,other,Android,yes,yes,12,9,6,19.0,26.666666666666668,49.2,10,9,0,0,1,1,0,0,,664.0,40.111111111111114,1,0,0,9,0,0,0,2,0,0,7,0,2,0,0,6,0,0,2,0,2,12,10,12,24.0,10.0,13.0,10.0,9.0,10.0,10,3,3,0,0,0,0,0,5,6,4,5,7,9,1,0,1,0,1,1,10
4929723,632989490a5820e31fde3d88,6-QUARTERLY,other,Android,yes,yes,1,0,0,,,,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,1,1,1,,,,,,,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
4929724,6355655785b3991ee34eb395,2-HH-inActive,other,Android,yes,no,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None

In [19]:
merged_df['os'].value_counts(normalize=True)

os
Android    0.817882
iOS        0.141033
Blank      0.041084
Name: proportion, dtype: float64

In [20]:
merged_df = merged_df[~merged_df['os'].isin(['Blank'])]

In [21]:
merged_df.customer_id.nunique()

4727191

In [22]:
merged_df.rename(columns={'net_psm_fav_stickylocation':'net_psm_stickylocation'}, inplace=True)

In [23]:
merged_df.columns

Index(['customer_id', 'segment', 'office_tag', 'os', 'travelridehailing',
       'quick_commerce', 'ao_session', 'fe_session', 'rr_session',
       'ao2fe_delta_mean', 'fe2rr_delta_mean', 'ao2rr_delta_mean', 'rr_count',
       'net_count', 'cobrm_count', 'cobra_count', 'ocara_count',
       'canceltn_count', 'quick_cobra', 'quick_ocara', 'cobra_ttc',
       'ocara_ttc', 'tta', 'rider_canceltn_count', 'expired_count',
       'aborted_count', 'haps_orders', 'bid_orders', 'negative_bid',
       'positive_bid', 'gross_psm_gps', 'gross_psm_fav_recent_history',
       'gross_psm_google_search', 'gross_psm_stickylocation',
       'gross_psm_hotspot', 'net_psm_gps', 'net_psm_fav_recent_history',
       'net_psm_google_search', 'net_psm_stickylocation', 'net_psm_hotspot',
       'office_gross', 'transit_gross', 'office_net', 'transit_net',
       'total_aos', 'total_ao_days', 'total_ao_sessions', 'total_fes',
       'total_fe_days', 'total_fe_sessions', 'total_rrs', 'total_rr_days',
       'total_rr_sessions', 'gross_orders', 'feedback_rating', 'rating_5',
       'rating_4', 'rating_3', 'rating_2', 'rating_1', 'customer_call_captain',
       'captain_call_customer', 'customer_msg_captain', 'captain_msg_customer',
       'call_communication', 'msg_communication', 'communication', 'ocara_no',
       'ocara_with_comm', 'ocara_without_comm', 'ocara_with_call',
       'ocara_without_call', 'support_ticket', 'customer_rr_sessions'],
      dtype='object')

In [24]:
cols_to_convert = [ 'rr_count', 'net_count', 'cobrm_count', 'cobra_count', 'ocara_count',
       'canceltn_count', 'quick_cobra', 'quick_ocara', 'cobra_ttc',
       'ocara_ttc', 'tta', 'rider_canceltn_count', 'expired_count', 'aborted_count', 'haps_orders',
       'bid_orders', 'negative_bid', 'positive_bid', 'gross_psm_gps',
       'gross_psm_fav_recent_history', 'gross_psm_google_search', 'gross_psm_stickylocation', 'gross_psm_hotspot',
       'net_psm_gps', 'net_psm_fav_recent_history', 'net_psm_google_search', 'net_psm_stickylocation', 'net_psm_hotspot',
       'ao_session', 'fe_session', 'rr_session', 'ao2fe_delta_mean', 'fe2rr_delta_mean', 'ao2rr_delta_mean',
        'office_gross', 'transit_gross', 'office_net', 'transit_net', 'total_aos',
       'total_ao_days', 'total_ao_sessions', 'total_fes', 'total_fe_days',
       'total_fe_sessions', 'total_rrs', 'total_rr_days', 'total_rr_sessions',
       'gross_orders', 'feedback_rating', 'rating_5', 'rating_4', 'rating_3',
       'rating_2', 'rating_1', 'customer_call_captain',
       'captain_call_customer', 'customer_msg_captain', 'captain_msg_customer',
       'call_communication', 'msg_communication', 'communication', 'ocara_no',
       'ocara_with_comm', 'ocara_without_comm', 'ocara_with_call',
       'ocara_without_call','support_ticket','customer_rr_sessions']

for col in cols_to_convert:
    merged_df[col] = pd.to_numeric(merged_df[col], errors='coerce')

In [25]:
merged_df['net_customers'] = merged_df['net_count'].apply(lambda x: 1 if x>0 else 0)
merged_df['gross_customers'] = merged_df['rr_count'].apply(lambda x: 1 if x>0 else 0)

In [26]:
# Revise Daily/Weekly/Monthy... threshold
# Retries - effort
    # total fe per total active fe days (ao/fe/rr)
    # total fe per total fe session
# gsr2net
# session length
# Use CT session data as proxy
# acceptance time
# Add p25 for all cancellation metric
# Rating distribution
# Captain cancellation
# Customer/Captain contact %
# Customer support contact ratio
# Rest
# Bad captain mapping %
# Office \ Transit \ Other
# Acquired at transit
# Ocara without contact and with contact
# Drop selection mode
# Median active days

In [27]:
merged_df['aos_per_session'] = round(merged_df['total_aos']/merged_df['total_ao_sessions'],2)
merged_df['aos_per_day'] = round(merged_df['total_aos']/merged_df['total_ao_days'],2)

merged_df['fes_per_session'] = round(merged_df['total_fes']/merged_df['total_fe_sessions'],2)
merged_df['fes_per_day'] = round(merged_df['total_fes']/merged_df['total_fe_days'],2)

merged_df['rrs_per_session'] = round(merged_df['total_rrs']/merged_df['total_rr_sessions'],2)
merged_df['rrs_per_day'] = round(merged_df['total_rrs']/merged_df['total_rr_days'],2)

In [28]:
merged_df.columns

Index(['customer_id', 'segment', 'office_tag', 'os', 'travelridehailing',
       'quick_commerce', 'ao_session', 'fe_session', 'rr_session',
       'ao2fe_delta_mean', 'fe2rr_delta_mean', 'ao2rr_delta_mean', 'rr_count',
       'net_count', 'cobrm_count', 'cobra_count', 'ocara_count',
       'canceltn_count', 'quick_cobra', 'quick_ocara', 'cobra_ttc',
       'ocara_ttc', 'tta', 'rider_canceltn_count', 'expired_count',
       'aborted_count', 'haps_orders', 'bid_orders', 'negative_bid',
       'positive_bid', 'gross_psm_gps', 'gross_psm_fav_recent_history',
       'gross_psm_google_search', 'gross_psm_stickylocation',
       'gross_psm_hotspot', 'net_psm_gps', 'net_psm_fav_recent_history',
       'net_psm_google_search', 'net_psm_stickylocation', 'net_psm_hotspot',
       'office_gross', 'transit_gross', 'office_net', 'transit_net',
       'total_aos', 'total_ao_days', 'total_ao_sessions', 'total_fes',
       'total_fe_days', 'total_fe_sessions', 'total_rrs', 'total_rr_days',
       'total_rr_sessions', 'gross_orders', 'feedback_rating', 'rating_5',
       'rating_4', 'rating_3', 'rating_2', 'rating_1', 'customer_call_captain',
       'captain_call_customer', 'customer_msg_captain', 'captain_msg_customer',
       'call_communication', 'msg_communication', 'communication', 'ocara_no',
       'ocara_with_comm', 'ocara_without_comm', 'ocara_with_call',
       'ocara_without_call', 'support_ticket', 'customer_rr_sessions',
       'net_customers', 'gross_customers', 'aos_per_session', 'aos_per_day',
       'fes_per_session', 'fes_per_day', 'rrs_per_session', 'rrs_per_day'],
      dtype='object')

In [29]:
def agg_func(col):
    
    grouper = col
    print(grouper)
    
    segment_agg_df = merged_df\
    .groupby(grouper)\
    .agg(
         gross_customers = ('gross_customers', 'sum'),
         net_customers = ('net_customers', 'sum'),
         
         ao_session = ('ao_session', 'sum'),
         fe_session = ('fe_session', 'sum'),
         rr_session = ('rr_session', 'sum'),

         rr_count = ('rr_count', 'sum'),
         net_count = ('net_count', 'sum'),
         cobrm_count = ('cobrm_count', 'sum'),
         cobra_count = ('cobra_count', 'sum'),
         ocara_count = ('ocara_count', 'sum'),
         expired_count = ('expired_count', 'sum'),
         aborted_count = ('aborted_count', 'sum'),
         canceltn_count = ('canceltn_count', 'sum'),
         rider_canceltn_count = ('rider_canceltn_count', 'sum'),
        
         quick_cobra = ('quick_cobra', 'sum'),
         quick_ocara = ('quick_ocara', 'sum'),
         
         cobra_ttc_mean = ('cobra_ttc', 'mean'),
         cobra_ttc_p25=('cobra_ttc', lambda x: x.quantile(0.25)),
         cobra_ttc_p50 = ('cobra_ttc', 'median'),
         cobra_ttc_p75=('cobra_ttc', lambda x: x.quantile(0.75)),
         cobra_ttc_p90=('cobra_ttc', lambda x: x.quantile(0.90)),
         cobra_ttc_p95=('cobra_ttc', lambda x: x.quantile(0.95)),
    
         ocara_ttc_mean = ('ocara_ttc', 'mean'),
         ocara_ttc_p25=('ocara_ttc', lambda x: x.quantile(0.25)),
         ocara_ttc_p50 = ('ocara_ttc', 'median'),
         ocara_ttc_p75=('ocara_ttc', lambda x: x.quantile(0.75)),
         ocara_ttc_p90=('ocara_ttc', lambda x: x.quantile(0.90)),
         ocara_ttc_p95=('ocara_ttc', lambda x: x.quantile(0.95)),

         tta_mean = ('tta', 'mean'),
         tta_p25=('tta', lambda x: x.quantile(0.25)),
         tta_p50 = ('tta', 'median'),
         tta_p75=('tta', lambda x: x.quantile(0.75)),
         tta_p90=('tta', lambda x: x.quantile(0.90)),
         tta_p95=('tta', lambda x: x.quantile(0.95)),
    
         haps_orders = ('haps_orders', 'sum'),
         bid_orders = ('bid_orders', 'sum'),
         negative_bid = ('negative_bid', 'sum'),
         positive_bid = ('positive_bid', 'sum'),
    
         gross_psm_gps = ('gross_psm_gps', 'sum'),
         gross_psm_fav_recent_history = ('gross_psm_fav_recent_history', 'sum'),
         gross_psm_google_search = ('gross_psm_google_search', 'sum'),
         gross_psm_stickylocation = ('gross_psm_stickylocation', 'sum'),
         gross_psm_hotspot = ('gross_psm_hotspot', 'sum'),
        
         net_psm_gps = ('net_psm_gps', 'sum'),
         net_psm_fav_recent_history = ('net_psm_fav_recent_history', 'sum'),
         net_psm_google_search = ('net_psm_google_search', 'sum'),
         net_psm_stickylocation = ('net_psm_stickylocation', 'sum'),
         net_psm_hotspot = ('net_psm_hotspot', 'sum'),
         
         office_gross = ('office_gross', 'sum'),
         transit_gross = ('transit_gross', 'sum'),
         office_net = ('office_net', 'sum'),
         transit_net = ('transit_net', 'sum'),

         ao2fe_delta_mean = ('ao2fe_delta_mean', 'mean'),
         ao2fe_delta_p25=('ao2fe_delta_mean', lambda x: x.quantile(0.25)),
         ao2fe_delta_p50 = ('ao2fe_delta_mean', 'median'),
         ao2fe_delta_p75=('ao2fe_delta_mean', lambda x: x.quantile(0.75)),
         ao2fe_delta_p90=('ao2fe_delta_mean', lambda x: x.quantile(0.90)),
         ao2fe_delta_p95=('ao2fe_delta_mean', lambda x: x.quantile(0.95)),

         fe2rr_delta_mean = ('fe2rr_delta_mean', 'mean'),
         fe2rr_delta_p25=('fe2rr_delta_mean', lambda x: x.quantile(0.25)),
         fe2rr_delta_p50 = ('fe2rr_delta_mean', 'median'),
         fe2rr_delta_p75=('fe2rr_delta_mean', lambda x: x.quantile(0.75)),
         fe2rr_delta_p90=('fe2rr_delta_mean', lambda x: x.quantile(0.90)),
         fe2rr_delta_p95=('fe2rr_delta_mean', lambda x: x.quantile(0.95)),

         ao2rr_delta_mean = ('ao2rr_delta_mean', 'mean'),
         ao2rr_delta_p25=('ao2rr_delta_mean', lambda x: x.quantile(0.25)),
         ao2rr_delta_p50 = ('ao2rr_delta_mean', 'median'),
         ao2rr_delta_p75=('ao2rr_delta_mean', lambda x: x.quantile(0.75)),
         ao2rr_delta_p90=('ao2rr_delta_mean', lambda x: x.quantile(0.90)),
         ao2rr_delta_p95=('ao2rr_delta_mean', lambda x: x.quantile(0.95)),

         aos_per_session_mean = ('aos_per_session', 'mean'),
         aos_per_session_p25=('aos_per_session', lambda x: x.quantile(0.25)),
         aos_per_session_p50 = ('aos_per_session', 'median'),
         aos_per_session_p75=('aos_per_session', lambda x: x.quantile(0.75)),
         aos_per_session_p90=('aos_per_session', lambda x: x.quantile(0.90)),
         aos_per_session_p95=('aos_per_session', lambda x: x.quantile(0.95)),

         aos_per_day_mean = ('aos_per_day', 'mean'),
         aos_per_day_p25=('aos_per_day', lambda x: x.quantile(0.25)),
         aos_per_day_p50 = ('aos_per_day', 'median'),
         aos_per_day_p75=('aos_per_day', lambda x: x.quantile(0.75)),
         aos_per_day_p90=('aos_per_day', lambda x: x.quantile(0.90)),
         aos_per_day_p95=('aos_per_day', lambda x: x.quantile(0.95)),

         fes_per_session_mean = ('fes_per_session', 'mean'),
         fes_per_session_p25=('fes_per_session', lambda x: x.quantile(0.25)),
         fes_per_session_p50 = ('fes_per_session', 'median'),
         fes_per_session_p75=('fes_per_session', lambda x: x.quantile(0.75)),
         fes_per_session_p90=('fes_per_session', lambda x: x.quantile(0.90)),
         fes_per_session_p95=('fes_per_session', lambda x: x.quantile(0.95)),

         fes_per_day_mean = ('fes_per_day', 'mean'),
         fes_per_day_p25=('fes_per_day', lambda x: x.quantile(0.25)),
         fes_per_day_p50 = ('fes_per_day', 'median'),
         fes_per_day_p75=('fes_per_day', lambda x: x.quantile(0.75)),
         fes_per_day_p90=('fes_per_day', lambda x: x.quantile(0.90)),
         fes_per_day_p95=('fes_per_day', lambda x: x.quantile(0.95)),

         rrs_per_session_mean = ('rrs_per_session', 'mean'),
         rrs_per_session_p25=('rrs_per_session', lambda x: x.quantile(0.25)),
         rrs_per_session_p50 = ('rrs_per_session', 'median'),
         rrs_per_session_p75=('rrs_per_session', lambda x: x.quantile(0.75)),
         rrs_per_session_p90=('rrs_per_session', lambda x: x.quantile(0.90)),
         rrs_per_session_p95=('rrs_per_session', lambda x: x.quantile(0.95)),

         rrs_per_day_mean = ('rrs_per_day', 'mean'),
         rrs_per_day_p25=('rrs_per_day', lambda x: x.quantile(0.25)),
         rrs_per_day_p50 = ('rrs_per_day', 'median'),
         rrs_per_day_p75=('rrs_per_day', lambda x: x.quantile(0.75)),
         rrs_per_day_p90=('rrs_per_day', lambda x: x.quantile(0.90)),
         rrs_per_day_p95=('rrs_per_day', lambda x: x.quantile(0.95)),

         feedback_rating = ('feedback_rating', 'sum'),
         rating_5 = ('rating_5', 'sum'),
         rating_4 = ('rating_4', 'sum'),
         rating_3 = ('rating_3', 'sum'),
         rating_2 = ('rating_2', 'sum'),
         rating_1 = ('rating_1', 'sum'),
         customer_call_captain = ('customer_call_captain', 'sum'),
         captain_call_customer = ('captain_call_customer', 'sum'), 
         customer_msg_captain = ('customer_msg_captain', 'sum'),
         captain_msg_customer = ('captain_msg_customer', 'sum'),
         call_communication = ('call_communication', 'sum'),
         msg_communication = ('msg_communication', 'sum'),
         communication = ('communication', 'sum'),
         ocara_no = ('ocara_no', 'sum'),
         ocara_with_comm = ('ocara_with_comm', 'sum'),
         ocara_without_comm = ('ocara_without_comm', 'sum'),
         ocara_with_call = ('ocara_with_call', 'sum'),
         ocara_without_call = ('ocara_without_call', 'sum'),
         support_ticket = ('support_ticket', 'sum'),
         customer_rr_sessions = ('customer_rr_sessions', 'sum')
        
        )\
    .reset_index()\
    .sort_values(by=grouper, ascending=True)

    segment_agg_df['gsr2net'] = round(segment_agg_df['net_count']*100/segment_agg_df['customer_rr_sessions'],2)
    segment_agg_df['rpc'] = round(segment_agg_df['net_count']/segment_agg_df['net_customers'],2)

    segment_agg_df['a02fe'] = round(segment_agg_df['fe_session']*100/segment_agg_df['ao_session'],2)
    segment_agg_df['fe2rr'] = round(segment_agg_df['rr_session']*100/segment_agg_df['fe_session'],2)
    segment_agg_df['ao2rr'] = round(segment_agg_df['rr_session']*100/segment_agg_df['ao_session'],2)
    
    segment_agg_df['g2n'] = round(segment_agg_df['net_count']*100/segment_agg_df['rr_count'],2)
    segment_agg_df['haps%'] = round(segment_agg_df['haps_orders']*100/segment_agg_df['net_count'],2)

    # cobrm/cobra/ocara/quick_cobra/quick_ocara/(expired_count+aborted_count) % = (cobrm/cobra/ocara/quick_cobra/quick_ocara/(expired_count+aborted_count))/rr
    for col in ['cobrm_count','cobra_count','ocara_count']:
        segment_agg_df[col.split('_')[0]+'%'] = round(segment_agg_df[col]*100/segment_agg_df['rr_count'],2)
    
    for col in ['quick_cobra','quick_ocara']:
        segment_agg_df[col +'%'] = round(segment_agg_df[col]*100/segment_agg_df['rr_count'],2)
    
    segment_agg_df['expired%'] = round((segment_agg_df['expired_count'] + segment_agg_df['aborted_count'])*100/segment_agg_df['rr_count'],2)

    segment_agg_df['positive_bid%'] = round(segment_agg_df['positive_bid']*100/segment_agg_df['bid_orders'],2)
    segment_agg_df['negative_bid%'] = round(segment_agg_df['negative_bid']*100/segment_agg_df['bid_orders'],2)

    # 'gross_psm_gps','gross_psm_fav_recent_history', 'gross_psm_google_search', 'gross_psm_stickylocation', 'gross_psm_hotspot'
    for col in ['gross_psm_gps','gross_psm_fav_recent_history', 'gross_psm_google_search', 'gross_psm_stickylocation', 'gross_psm_hotspot']:
        segment_agg_df[col +'%'] = round(segment_agg_df[col]*100/segment_agg_df['rr_count'],2)
    # 'net_psm_gps','net_psm_fav_recent_history', 'net_psm_google_search', 'net_psm_fav_stickylocation', 'net_psm_hotspot'
    for col in ['net_psm_gps','net_psm_fav_recent_history', 'net_psm_google_search', 'net_psm_stickylocation', 'net_psm_hotspot']:
        segment_agg_df[col +'%'] = round(segment_agg_df[col]*100/segment_agg_df['net_count'],2)

    for col in ['office_gross','transit_gross']:
        segment_agg_df[col +'%'] = round(segment_agg_df[col]*100/segment_agg_df['rr_count'],2)

    for col in ['office_net','transit_net']:
        segment_agg_df[col +'%'] = round(segment_agg_df[col]*100/segment_agg_df['net_count'],2)

    segment_agg_df['% Bid'] = round(segment_agg_df['bid_orders']*100/segment_agg_df['rr_count'],2)
    
    segment_agg_df['% Gross customers'] = round(segment_agg_df['gross_customers']*100/ segment_agg_df.groupby('segment')['gross_customers'].transform('sum'),2)
    segment_agg_df['% Gross Orders'] = round(segment_agg_df['rr_count']*100/ segment_agg_df.groupby('segment')['rr_count'].transform('sum'),2)
    
    segment_agg_df['% rider_canceltn'] = round(segment_agg_df['rider_canceltn_count']*100/segment_agg_df['rr_count'],2)

    segment_agg_df['% rated_orders'] = round(segment_agg_df['feedback_rating']*100/segment_agg_df['net_count'],2)

    segment_agg_df['% rating_5'] = round(segment_agg_df['rating_5']*100/segment_agg_df['feedback_rating'],2)
    segment_agg_df['% rating_4'] = round(segment_agg_df['rating_4']*100/segment_agg_df['feedback_rating'],2)
    segment_agg_df['% rating_3'] = round(segment_agg_df['rating_3']*100/segment_agg_df['feedback_rating'],2)
    segment_agg_df['% rating_2'] = round(segment_agg_df['rating_2']*100/segment_agg_df['feedback_rating'],2)
    segment_agg_df['% rating_1'] = round(segment_agg_df['rating_1']*100/segment_agg_df['feedback_rating'],2)

    segment_agg_df['average_rating'] =  round(((segment_agg_df['% rating_5']*5) + (segment_agg_df['% rating_4']*4) + (segment_agg_df['% rating_3']*3) + (segment_agg_df['% rating_2']*2) + (segment_agg_df['% rating_1']*1))/100,2)

    segment_agg_df['% call_communication'] = round(segment_agg_df['call_communication']*100/segment_agg_df['rr_count'],2)
    segment_agg_df['% msg_communication'] = round(segment_agg_df['msg_communication']*100/segment_agg_df['rr_count'],2)
    segment_agg_df['% communication'] = round(segment_agg_df['communication']*100/segment_agg_df['rr_count'],2)

    segment_agg_df['% ocara_with_comm'] = round(segment_agg_df['ocara_with_comm']*100/segment_agg_df['ocara_no'],2)
    segment_agg_df['% ocara_without_comm'] = round(segment_agg_df['ocara_without_comm']*100/segment_agg_df['ocara_no'],2)
    segment_agg_df['% ocara_with_call'] = round(segment_agg_df['ocara_with_call']*100/segment_agg_df['ocara_no'],2)
    segment_agg_df['% ocara_without_call'] = round(segment_agg_df['ocara_without_call']*100/segment_agg_df['ocara_no'],2)

    segment_agg_df['% support_ticket'] = round(segment_agg_df['support_ticket']*100/segment_agg_df['net_count'],2)

    cols1 = ['gross_customers', 'net_customers', 'ao_session', 'fe_session', 'rr_session', 'customer_rr_sessions', 'rr_count', 'net_count', 'cobrm_count', 'cobra_count', 'ocara_count', 'expired_count', 'aborted_count', 'canceltn_count', 'quick_cobra', 'quick_ocara', 'cobra_ttc_mean', 'cobra_ttc_p25', 'cobra_ttc_p50', 'cobra_ttc_p75', 'cobra_ttc_p90', 'cobra_ttc_p95', 'ocara_ttc_mean', 'ocara_ttc_p25', 'ocara_ttc_p50', 'ocara_ttc_p75', 'ocara_ttc_p90', 'ocara_ttc_p95', 'haps_orders', 'bid_orders', 'negative_bid', 'positive_bid', 'gross_psm_gps', 'gross_psm_fav_recent_history', 'gross_psm_google_search', 'gross_psm_stickylocation', 'gross_psm_hotspot', 'net_psm_gps', 'net_psm_fav_recent_history', 'net_psm_google_search', 'net_psm_stickylocation', 'net_psm_hotspot', 'office_gross', 'transit_gross', 'office_net', 'transit_net', 'rpc', 'a02fe', 'fe2rr', 'ao2rr', 'g2n', 'cobrm%', 'cobra%', 'ocara%', 'expired%', 'quick_cobra%', 'quick_ocara%', 'haps%', 'gsr2net' , '% Bid', 'positive_bid%', 'negative_bid%', 'gross_psm_gps%', 'gross_psm_fav_recent_history%', 'gross_psm_google_search%', 'gross_psm_stickylocation%', 'gross_psm_hotspot%', 'net_psm_gps%', 'net_psm_fav_recent_history%', 'net_psm_google_search%', 'net_psm_stickylocation%', 'net_psm_hotspot%', 'office_gross%', 'transit_gross%', 'office_net%', 'transit_net%', '% Gross customers', '% Gross Orders', 'ao2fe_delta_mean', 'ao2fe_delta_p25', 'ao2fe_delta_p50', 'ao2fe_delta_p75', 'ao2fe_delta_p90', 'ao2fe_delta_p95', 'fe2rr_delta_mean', 'fe2rr_delta_p25', 'fe2rr_delta_p50', 'fe2rr_delta_p75', 'fe2rr_delta_p90', 'fe2rr_delta_p95', 'ao2rr_delta_mean', 'ao2rr_delta_p25', 'ao2rr_delta_p50', 'ao2rr_delta_p75', 'ao2rr_delta_p90', 'ao2rr_delta_p95', 'aos_per_session_mean', 'aos_per_session_p25', 'aos_per_session_p50', 'aos_per_session_p75', 'aos_per_session_p90', 'aos_per_session_p95', 'aos_per_day_mean', 'aos_per_day_p25', 'aos_per_day_p50', 'aos_per_day_p75', 'aos_per_day_p90', 'aos_per_day_p95', 'fes_per_session_mean', 'fes_per_session_p25', 'fes_per_session_p50', 'fes_per_session_p75', 'fes_per_session_p90', 'fes_per_session_p95', 'fes_per_day_mean', 'fes_per_day_p25', 'fes_per_day_p50', 'fes_per_day_p75', 'fes_per_day_p90', 'fes_per_day_p95', 'rrs_per_session_mean', 'rrs_per_session_p25', 'rrs_per_session_p50', 'rrs_per_session_p75', 'rrs_per_session_p90', 'rrs_per_session_p95', 'rrs_per_day_mean', 'rrs_per_day_p25', 'rrs_per_day_p50', 'rrs_per_day_p75', 'rrs_per_day_p90', 'rrs_per_day_p95']

    cols2 = ['rider_canceltn_count','% rider_canceltn', 'tta_mean', 'tta_p25', 'tta_p50', 'tta_p75', 'tta_p90', 'tta_p95', 'average_rating', 'feedback_rating', '% rated_orders', 'rating_5', '% rating_5',
       'rating_4', '% rating_4', 'rating_3', '% rating_3', 'rating_2', '% rating_2', 'rating_1', '% rating_1',  'customer_call_captain',
       'captain_call_customer', 'customer_msg_captain', 'captain_msg_customer',
       'call_communication', '% call_communication', 'msg_communication', '% msg_communication', 'communication', '% communication', 'ocara_no',
       'ocara_with_comm', '% ocara_with_comm', 'ocara_without_comm','% ocara_without_comm',  'ocara_with_call', '% ocara_with_call', 
       'ocara_without_call', '% ocara_without_call', 'support_ticket', '% support_ticket']

    cols = cols1+cols2
    
    for col in cols:
        segment_agg_df[col] =  segment_agg_df[col].apply(lambda x: round(x,2))
    
    segment_agg_df = segment_agg_df[grouper+cols]
    segment_agg_df = segment_agg_df.drop(['aos_per_session_mean','aos_per_day_mean','fes_per_session_mean','fes_per_day_mean','rrs_per_session_mean','rrs_per_day_mean'],axis=1)
    
    return segment_agg_df.set_index(grouper)

In [30]:
%%time
segment_agg_df = agg_func(['segment'])

['segment']
CPU times: user 10.2 s, sys: 1.93 s, total: 12.2 s
Wall time: 13.1 s

In [31]:
segment_agg_df.shape

(8, 168)

In [32]:
segment_agg_df

,gross_customers,net_customers,ao_session,fe_session,rr_session,customer_rr_sessions,rr_count,net_count,cobrm_count,cobra_count,ocara_count,expired_count,aborted_count,canceltn_count,quick_cobra,quick_ocara,cobra_ttc_mean,cobra_ttc_p25,cobra_ttc_p50,cobra_ttc_p75,cobra_ttc_p90,cobra_ttc_p95,ocara_ttc_mean,ocara_ttc_p25,ocara_ttc_p50,ocara_ttc_p75,ocara_ttc_p90,ocara_ttc_p95,haps_orders,bid_orders,negative_bid,positive_bid,gross_psm_gps,gross_psm_fav_recent_history,gross_psm_google_search,gross_psm_stickylocation,gross_psm_hotspot,net_psm_gps,net_psm_fav_recent_history,net_psm_google_search,net_psm_stickylocation,net_psm_hotspot,office_gross,transit_gross,office_net,transit_net,rpc,a02fe,fe2rr,ao2rr,g2n,cobrm%,cobra%,ocara%,expired%,quick_cobra%,quick_ocara%,haps%,gsr2net,% Bid,positive_bid%,negative_bid%,gross_psm_gps%,gross_psm_fav_recent_history%,gross_psm_google_search%,gross_psm_stickylocation%,gross_psm_hotspot%,net_psm_gps%,net_psm_fav_recent_history%,net_psm_google_search%,net_psm_stickylocation%,net_psm_hotspot%,office_gross%,transit_gross%,office_net%,transit_net%,% Gross customers,% Gross Orders,ao2fe_delta_mean,ao2fe_delta_p25,ao2fe_delta_p50,ao2fe_delta_p75,ao2fe_delta_p90,ao2fe_delta_p95,fe2rr_delta_mean,fe2rr_delta_p25,fe2rr_delta_p50,fe2rr_delta_p75,fe2rr_delta_p90,fe2rr_delta_p95,ao2rr_delta_mean,ao2rr_delta_p25,ao2rr_delta_p50,ao2rr_delta_p75,ao2rr_delta_p90,ao2rr_delta_p95,aos_per_session_p25,aos_per_session_p50,aos_per_session_p75,aos_per_session_p90,aos_per_session_p95,aos_per_day_p25,aos_per_day_p50,aos_per_day_p75,aos_per_day_p90,aos_per_day_p95,fes_per_session_p25,fes_per_session_p50,fes_per_session_p75,fes_per_session_p90,fes_per_session_p95,fes_per_day_p25,fes_per_day_p50,fes_per_day_p75,fes_per_day_p90,fes_per_day_p95,rrs_per_session_p25,rrs_per_session_p50,rrs_per_session_p75,rrs_per_session_p90,rrs_per_session_p95,rrs_per_day_p25,rrs_per_day_p50,rrs_per_day_p75,rrs_per_day_p90,rrs_per_day_p95,rider_canceltn_count,% rider_canceltn,tta_mean,tta_p25,tta_p50,tta_p75,tta_p90,tta_p95,average_rating,feedback_rating,% rated_orders,rating_5,% rating_5,rating_4,% rating_4,rating_3,% rating_3,rating_2,% rating_2,rating_1,% rating_1,customer_call_captain,captain_call_customer,customer_msg_captain,captain_msg_customer,call_communication,% call_communication,msg_communication,% msg_communication,communication,% communication,ocara_no,ocara_with_comm,% ocara_with_comm,ocara_without_comm,% ocara_without_comm,ocara_with_call,% ocara_with_call,ocara_without_call,% ocara_without_call,support_ticket,% support_ticket
segment,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1-HH-Active,434017,379640,1467504.0,1119569.0,547167.0,767072.0,905093.0,548258.0,11658.0,113689.0,165917.0,64200.0,1362.0,291264.0,14749.0,14999.0,118.64,59.00,102.33,161.00,227.50,271.00,525.97,162.00,350.00,658.00,1133.0,1595.07,375625.0,101239.0,28431.0,72808.0,518579.0,15174.0,52722.0,110951.0,54364.0,316894.0,7623.0,30005.0,68703.0,32523.0,133296.0,123730.0,70284.0,69353.0,1.44,76.29,48.87,37.29,60.57,1.29,12.56,18.33,7.24,1.63,1.66,68.51,71.47,11.19,71.92,28.08,57.30,1.68,5.83,12.26,6.01,57.80,1.39,5.47,12.53,5.93,14.73,13.67,12.82,12.65,100.0,100.0,52.69,15.50,29.75,57.67,111.00,171.00,127.96,26.00,50.00,125.00,318.00,524.00,173.24,51.00,92.00,191.00,397.88,606.00,1.0,1.00,1.33,1.71,2.00,1.00,1.50,2.00,3.00,4.00,1.00,1.50,2.00,2.50,3.00,1.50,2.25,3.50,5.00,7.00,1.00,1.00,1.00,1.67,2.00,1.00,1.00,2.00,2.33,3.00,134149.0,14.82,84.87,6.67,20.50,80.00,201.00,335.00,4.55,104614.0,19.08,82286.0,78.66,11203.0,10.71,3623.0,3.46,1600.0,1.53,5902.0,5.64,4757.0,369067.0,204695.0,373323.0,371342.0,41.03,427121.0,47.19,554264.0,61.24,165917.0,109381.0,65.93,56536.0,34.07,65723.0,39.61,100194.0,60.39,5679.0,1.04
2-HH-inActive,17332,14989,552406.0,269578.0,10816.0,14832.0,32734.0,20286.0,484.0,4258.0,5731.0,1935.0,40.0,10473.0,638.0,589.0,110.10,54.00,94.78,149.83,216.50,254.00,496.18,147.00,329.00,608.00,1058.4,1490.70,13907.0,3317.0,958.0,2359.0,19207.0,550.0,1831.0,2724.0,1934.0,12056.0,300.0,986.0,1739.0,1206.0,36687.0,45657.0,21540.0,25824.0,1.35,48.80,4.01,1.96,61.97,1.48,13.01,17.51,6.03,1.95,1.80,68.55,136.77,10.13,71.12,28.88,58.68,1.68,5.59,8.32,5.91,59.43,1.48,4.86,8.57,5.94,112.08,139.48,106.18,127.30,100.0,100.0,48.69,13.00,26.00,51.66,100.00,158.00,121.17,21.00,47.00,117.00,312.00,517.85,215.80,68.00,129.00,255.00,493.30,710.00,1.0,1.00,1.00,1.50,2.00,1.00,1.00,1.50,2.00,3.00,1.00,1.00,1.67,2.00,3.00,1.00,1.00,2.00,3.00,4.00,1.00,1.00,1.00,2.00,2.00,1.00,1.00,1.50,2.00,3.00,4402.0,13.45,77.38,6.00,17.33,73.00,183.67,300.00,4.57,4165.0,20.53,3231.0,77.58,528.0,12.68,159.0,3.82,45.0,1.08,202.0,4.85,80.0,13158.0,955.0,13511.0,13191.0,40.30,13734.0,41.96,19030.0,58.14,5731.0,3430.0,59.85,2301.0,40.15,2133.0,37.22,3598.0,62.78,224.0,1.10
3-DAILY,108395,108292,2178671.0,1912175.0,1575745.0,3529561.0,4527601.0,2834227.0,27967.0,668777.0,757917.0,236714.0,1971.0,1454661.0,104888.0,74869.0,117.19,76.00,110.27,149.00,193.00,226.25,299.30,169.00,249.75,364.00,523.0,658.00,2251877.0,1161519.0,644357.0,517162.0,1589045.0,507845.0,343203.0,776282.0,295255.0,982998.0,325294.0,221131.0,482213.0,183910.0,1238144.0,302303.0,638463.0,168761.0,26.17,87.77,82.41,72.33,62.60,0.62,14.77,16.74,5.27,2.32,1.65,79.45,80.30,25.65,44.52,55.48,35.10,11.22,7.58,17.15,6.52,34.68,11.48,7.80,17.01,6.49,27.35,6.68,22.53,5.95,100.0,100.0,31.92,13.95,22.53,37.86,62.18,83.77,47.27,15.67,29.67,58.93,105.26,145.00,76.15,35.80,57.11,94.30,147.35,190.71,1.0,1.05,1.16,1.30,1.42,1.30,1.55,1.90,2.36,2.74,1.27,1.47,1.74,2.06,2.31,2.30,3.00,3.90,5.00,5.85,1.11,1.21,1.38,1.60,1.80,1.76,2.22,2.78,3.45,3.96,610250.0,13.48,78.54,49.07,70.57,97.83,130.29,156.63,4.79,719123.0,25.37,645167.0,89.72,38880.0,5.41,11375.0,1.58,4812.0,0.67,18889.0,2.63,4346.0,1682131.0,942084.0,1846316.0,1684269.0,37.20,2125361.0,46.94,2690322.0,59.42,757917.0,410382.0,54.15,347535.0,45.85,156390.0,20.63,601527.0,79.37,25963.0,0.92
4-WEEKLY,296184,294416,3567344.0,3029906.0,2231120.0,3683080.0,4601405.0,2819694.0,33728.0,709300.0,770621.0,265579.0,2450.0,1513649.0,105155.0,65833.0,116.93,68.00,106.33,153.00,207.33,247.00,322.59,147.50,248.67,400.00,619.0,817.75,2153025.0,944099.0,492139.0,451960.0,1799086.0,384869.0,328903.0,814013.0,313229.0,1093460.0,241706.0,206266.0,496141.0,190370.0,1315548.0,417897.0,656451.0,227653.0,9.58,84.93,73.64,62.54,61.28,0.73,15.41,16.75,5.82,2.29,1.43,76.36,76.56,20.52,47.87,52.13,39.10,8.36,7.15,17.69,6.81,38.78,8.57,7.32,17.60,6.75,28.59,9.08,23.28,8.07,100.0,100.0,36.66,15.31,25.14,43.14,72.86,101.00,62.91,18.00,35.33,75.67,146.83,209.11,96.91,41.00,68.40,119.67,197.67,263.25,1.0,1.05,1.19,1.35,1.50,1.25,1.50,1.86,2.33,2.67,1.25,1.45,1.75,2.10,2.38,1.90,2.50,3.27,4.22,5.00,1.00,1.17,1.33,1.60,1.83,1.40,1.75,2.25,2.83,3.29,626389.0,13.61,70.42,32.14,56.17,89.27,134.25,174.23,4.74,588045.0,20.85,514620.0,87.51,37910.0,6.45,11326.0,1.93,5114.0,0.87,19075.0,3.24,8196.0,1677608.0,958334.0,1816360.0,1681643.0,36.55,2098214.0,45.60,2678936.0,58.22,770621.0,427275.0,55.45,343346.0,44.55,177693.0,23.06,592928.0,76.94,27003.0,0.96
5-MONTHLY,1569071,1443941,9600833.0,7621413.0,4631003.0,6858923.0,8376891.0,5241512.0,69825.0,1278474.0,1322640.0,458037.0,6342.0,2670939.0,170926.0,87208.0,117.17,63.00,104.00,156.00,217.00,259.00,379.63,138.33,267.50,470.83,778.0,1066.00,3881413.0,1246543.0,540218.0,706325.0,3857276.0,445428.0,490517.0,1396574.0,535993.0,2407867.0,282441.0,305398.0,873304.0,332836.0,2099766.0,1043008.0,1108880.0,583418.0,3.63,79.38,60.76,48.24,62.57,0.83,15.26,15.79,5.54,2.04,1.04,74.05,76.42,14.88,56.66,43.34,46.05,5.32,5.86,16.67,6.40,45.94,5.39,5.83,16.66,6.35,25.07,12.45,21.16,11.13,100.0,100.0,42.24,14.50,25.40,47.00,86.25,128.25,90.33,19.33,39.00,94.00,217.00,345.50,129.38,42.00,75.50,148.00,283.00,417.00,1.0,1.00,1.20,1.50,1.69,1.00,1.40,2.00,2.50,3.00,1.00,1.38,1.77,2.23,2.67,1.50,2.00,3.00,4.25,5.25,1.00,1.00,1.29,1.67,2.00,1.00,1.43,2.00,2.67,3.20,1125299.0,13.43,70.47,11.00,36.33,81.80,154.80,233.00,4.67,1042747.0,19.89,880404.0,84.43,82477.0,7.91,25700.0,2.46,11111.0,1.07,43055.0,4.13,27597.0,3128322.0,1814519.0,3365469.0,3142145.0,37.51,3880866.0,46.33,4965380.0,59.27,1322640.0,785895.0,59.42,536745.0,40.58,372765.0,28.18,949875.0,71.82,50647.0,0.97
6-QUARTERLY,479813,469789,2503313.0,1936357.0,1075131.0,1715124.0,2389248.0,1587558.0,20851.0,328175.0,328310.0,122504.0,1836.0,677336.0,40677.0,19649.0,119.09,66.00,106.83,157.45,217.00,258.00,416.32,156.50,299.00,516.00,847.0,1151.00,1162303.0,309402.0,126117.0,183285.0,1179367.0,99095.0,127310.0,364880.0,151959.0,784160.0,64703.0,84692.0,243044.0,100865.0,469667.0,264291.0,275374.0,164431.0,3.38,77.35,55.52,42.95,66.45,0.87,13.74,13.74,5.20,1.70,0.82,73.21,92.56,12.95,59.24,40.76,49.36,4.15,5.33,15.27,6.36,49.39,4.08,5.33,15.31,6.35,19.66,11.06,17.35,10.36,100.0,100.0,46.01,15.00,26.75,49.67,93.92,142.00,110.00,23.00,47.00,113.85,268.61,432.00,151.16,48.00,86.00,171.00,335.38,502.00,1.0,1.00,1.15,1.50,1.86,1.00,1.33,2.00,2.85,3.47,1.00,1.33,1.80,2.25,2.83,1.33,2.00,3.25,5.00,6.00,1.00,1.00,1.25,1.60,2.00,1.00,1.40,2.00,3.00,3.50,310908.0,13.01,66.74,9.25,33.25,80.00,153.50,230.00,4.67,365343.0,23.01,305410.0,83.60,31690.0,8.67,9447.0,2.59,4030.0,1.10,14766.0,4.04,11891.0,926282.0,485510.0,991885.0,932319.0,39.02,1124999.0,47.09,1451801.0,60.76,328310.0,198586.0,60.49,129724.0,39.51,101509.0,30.92,226801.0,69.08,15789.0,0.99
7-RR-ACTIVE,33021,92,145512.0,91911.0,36415.0,44919.0,52751.0,94.0,1260.0,18599.0,23387.0,9222.0,184.0,43246.0,2306.0,1283.0,119.94,58.62,104.00,164.62,231.00,273.00,484.94,132.00,295.00,598.00,1089.9,1582.95,62.0,6882.0,1660.0,5222.0,25343.0,1810.0,3669.0,8353.0,3442.0,50.0,2.0,5.0,10.0,4.0,12739.0,10834.0,6.0,13.0,1.02,63.16,39.62,25.03,0.18,2.39,35.26,44.33,17.83,4.37,2.43,65.96,0.21,13.05,75.88,24.12,48.04,3.43,6.96,15.83,6.52,53.19,2.13,5.32,10.64,4.26,24.15,20.54,6.38,13.83,100.0,100.0,42.91,13.00,23.00,44.00,86.00,137.00,87.74,17.00,32.00,75.00,204.50,370.17,129.20,38.00,66.00,133.00,290.60,460.55,1.0,1.00,1.00,1.50,2.00,1.00,1.00,2.00,2.50,3.00,1.00,1.33,2.00,2.60,3.00,1.00,2.00,3.00,4.00,5.00,1.00,1.00,1.00,2.00,2.00,1.00,1.00,1.67,2.00,3.00,9175.0,17.39,200.89,10.00,56.00,185.00,497.00,958.00,4.57,30.0,31.91,26.0,86.67,1.0,3.33,0.0,0.00,0.0,0.00,3.0,10.00,418.0,8864.0,5673.0,11727.0,9064.0,17.18,13587.0,25.76,16195.0,30.70,23387.0,15112.0,64.62,8275.0,35.38,8410.0,35.96,14977.0,64.04,182.0,193.62
8-RR-INACTIVE,1933,5,211620.0,124888.0,5247.0,6955.0,3037.0,6.0,74.0,1106.0,1421.0,427.0,3.0,2601.0,142.0,174.0,118.64,55.00,103.25,163.12,240.40,272.40,442.28,108.62,260.00,519.00,1020.9,1428.55,5.0,349.0,99.0,250.0,1481.0,117.0,208.0,268.0,158.0,5.0,0.0,0.0,1.0,0.0,650.0,708.0,0.0,1.0,1.20,59.02,4.20,2.48,0.20,2.44,36.42,46.79,14.16,4.68,5.73,83.33,0.09,11.49,71.63,28.37,48.77,3.85,6.85,8.82,5.20,83.33,0.00,0.00,16.67,0.00,21.40,23.31,0.00,16.67,100.0,100.0,44.26,12.96,24.00,46.00,90.00,142.50,114.95,18.00,40.00,113.00,290.10,500.85,211.96,67.83,128.00,257.50,479.80,676.15,1.0,1.00,1.00,1.50,2.00,1.00,1.00,1.50,2.00,3.00,1.00,1.00,1.60,2.00,3.00,1.00,1.00,2.00,3.00,4.00,1.00,1.00,1.00,2.00,2.00,1.00,1.00,1.34,2.00,3.00,477.0,15.71,191.09,8.50,36.00,149.25,443.40,969.40,4.00,3.0,50.00,2.0,66.67,0.0,0.00,0.0,0.00,1.0,33.33,0.0,0.00,26.0,480.0,79.0,677.0,495.0,16.30,707.0,23.28,877.0,28.88,1421.0,830.0,58.41,591.0,41.59,464.0,32.65,957.0,67.35,8.0,133.33

In [34]:
segment_agg_df.reset_index().to_clipboard(index=False)

In [35]:
segment_os = agg_func(['segment','os'])
segment_os

['segment', 'os']

                       gross_customers  net_customers  ao_session  fe_session  \
segment       os
1-HH-Active   Android           382876         336021   1330282.0   1016969.0
              iOS                51141          43619    137222.0    102600.0
2-HH-inActive Android            17127          14817    503822.0    249692.0
              iOS                  205            172     48584.0     19886.0
3-DAILY       Android            73655          73564   1557746.0   1389492.0
              iOS                34740          34728    620925.0    522683.0
4-WEEKLY      Android           212620         211358   2658399.0   2293592.0
              iOS                83564          83058    908945.0    736314.0
5-MONTHLY     Android          1226544        1130893   7634970.0   6179372.0
              iOS               342527         313048   1965863.0   1442041.0
6-QUARTERLY   Android           397333         388578   2074089.0   1631624.0
              iOS                82480          81211    429224.0    304733.0
7-RR-ACTIVE   Android            25564             83    112067.0     74738.0
              iOS                 7457              9     33445.0     17173.0
8-RR-INACTIVE Android             1860              5    174496.0    108083.0
              iOS                   73              0     37124.0     16805.0

                       rr_session  customer_rr_sessions   rr_count  net_count  \
segment       os
1-HH-Active   Android    487255.0              670296.0   795307.0   483646.0
              iOS         59912.0               96776.0   109786.0    64612.0
2-HH-inActive Android      9622.0               13027.0    32385.0    20084.0
              iOS          1194.0                1805.0      349.0      202.0
3-DAILY       Android   1138053.0             2325284.0  3035890.0  1914360.0
              iOS        437692.0             1204277.0  1491711.0   919867.0
4-WEEKLY      Android   1669833.0             2555653.0  3238352.0  2001640.0
              iOS        561287.0             1127427.0  1363053.0   818054.0
5-MONTHLY     Android   3666360.0             5160015.0  6375401.0  4019198.0
              iOS        964643.0             1698908.0  2001490.0  1222314.0
6-QUARTERLY   Android    885144.0             1352979.0  1962409.0  1308076.0
              iOS        189987.0              362145.0   426839.0   279482.0
7-RR-ACTIVE   Android     28117.0               34357.0    40576.0       85.0
              iOS          8298.0               10562.0    12175.0        9.0
8-RR-INACTIVE Android      4295.0                5500.0     2932.0        6.0
              iOS           952.0                1455.0      105.0        0.0

                       cobrm_count  cobra_count  ocara_count  expired_count  \
segment       os
1-HH-Active   Android      10714.0      97906.0     146183.0        55613.0
              iOS            944.0      15783.0      19734.0         8587.0
2-HH-inActive Android        479.0       4200.0       5665.0         1917.0
              iOS              5.0         58.0         66.0           18.0
3-DAILY       Android      20124.0     468173.0     481879.0       149891.0
              iOS           7843.0     200604.0     276038.0        86823.0
4-WEEKLY      Android      25351.0     512027.0     521869.0       175549.0
              iOS           8377.0     197273.0     248752.0        90030.0
5-MONTHLY     Android      56191.0     978131.0     983616.0       333033.0
              iOS          13634.0     300343.0     339024.0       125004.0
6-QUARTERLY   Android      17692.0     269335.0     267232.0        98470.0
              iOS           3159.0      58840.0      61078.0        24034.0
7-RR-ACTIVE   Android       1003.0      14255.0      18040.0         7039.0
              iOS            257.0       4344.0       5347.0         2183.0
8-RR-INACTIVE Android         72.0       1070.0       1369.0          412.0
              iOS              2.0         36.0         52.0           15.0

                       aborted_count  canceltn_count  quick_cobra  \
segment       os
1-HH-Active   Android         1239.0        254803.0      12831.0
              iOS              123.0         36461.0       1918.0
2-HH-inActive Android           40.0         10344.0        620.0
              iOS                0.0           129.0         18.0
3-DAILY       Android         1439.0        970176.0      70436.0
              iOS              532.0        484485.0      34452.0
4-WEEKLY      Android         1890.0       1059247.0      72854.0
              iOS              560.0        454402.0      32301.0
5-MONTHLY     Android         5182.0       2017938.0     126611.0
              iOS             1160.0        653001.0      44315.0
6-QUARTERLY   Android         1593.0        554259.0      32812.0
              iOS              243.0        123077.0       7865.0
7-RR-ACTIVE   Android          149.0         33298.0       1752.0
              iOS               35.0          9948.0        554.0
8-RR-INACTIVE Android            3.0          2511.0        136.0
              iOS                0.0            90.0          6.0

                       quick_ocara  cobra_ttc_mean  cobra_ttc_p25  \
segment       os
1-HH-Active   Android      13905.0          118.53          59.00
              iOS           1094.0          119.30          58.33
2-HH-inActive Android        579.0          110.54          54.00
              iOS             10.0           79.21          20.25
3-DAILY       Android      46244.0          116.47          76.50
              iOS          28625.0          118.71          74.50
4-WEEKLY      Android      43036.0          116.02          68.00
              iOS          22797.0          119.18          67.00
5-MONTHLY     Android      61399.0          116.80          63.64
              iOS          25809.0          118.35          62.00
6-QUARTERLY   Android      15937.0          119.19          67.00
              iOS           3712.0          118.65          64.00
7-RR-ACTIVE   Android        971.0          119.94          58.00
              iOS            312.0          119.96          59.81
8-RR-INACTIVE Android        167.0          119.40          55.12
              iOS              7.0           97.29          37.50

                       cobra_ttc_p50  cobra_ttc_p75  cobra_ttc_p90  \
segment       os
1-HH-Active   Android         102.33         161.00         227.00
              iOS             102.00         161.00         231.00
2-HH-inActive Android          95.00         150.00         217.00
              iOS              67.50         103.81         162.40
3-DAILY       Android         109.86         147.67         189.33
              iOS             111.50         152.87         200.00
4-WEEKLY      Android         106.00         151.40         204.00
              iOS             108.00         157.00         215.00
5-MONTHLY     Android         104.00         155.00         216.00
              iOS             104.80         159.16         222.00
6-QUARTERLY   Android         107.00         157.33         216.00
              iOS             105.00         157.50         220.53
7-RR-ACTIVE   Android         104.00         165.00         231.95
              iOS             104.38         163.00         229.70
8-RR-INACTIVE Android         103.25         163.88         241.50
              iOS             102.00         147.00         184.90

                       cobra_ttc_p95  ocara_ttc_mean  ocara_ttc_p25  \
segment       os
1-HH-Active   Android         270.00          538.98         166.00
              iOS             277.00          435.59         139.00
2-HH-inActive Android         254.00          497.73         148.00
              iOS             187.65          340.40          79.75
3-DAILY       Android         222.00          310.35         172.36
              iOS             236.00          276.45         163.00
4-WEEKLY      Android         243.50          334.97         151.00
              iOS             255.00          292.99         140.33
5-MONTHLY     Android         257.00          395.94         144.00
              iOS             265.00          327.53         122.00
6-QUARTERLY   Android         257.00          428.31         162.00
              iOS             264.00          361.67         136.00
7-RR-ACTIVE   Android         273.95          507.70         138.00
              iOS             271.00          406.46         115.00
8-RR-INACTIVE Android         277.25          440.61         109.75
              iOS             214.67          481.94          74.50

                       ocara_ttc_p50  ocara_ttc_p75  ocara_ttc_p90  \
segment       os
1-HH-Active   Android         360.00         674.00        1160.00
              iOS             289.50         545.00         935.00
2-HH-inActive Android         329.00         609.00        1060.20
              iOS             271.00         454.67         844.30
3-DAILY       Android         256.50         378.00         546.36
              iOS             237.94         338.16         471.01
4-WEEKLY      Android         257.00         416.00         645.00
              iOS             231.00         363.00         551.21
5-MONTHLY     Android         280.00         491.67         811.00
              iOS             233.50         405.00         669.00
6-QUARTERLY   Android         308.00         531.00         870.00
              iOS             260.07         447.33         736.00
7-RR-ACTIVE   Android         310.00         626.00        1145.20
              iOS             249.00         481.50         892.80
8-RR-INACTIVE Android         262.00         519.00         975.30
              iOS             202.00         496.75        1334.80

                       ocara_ttc_p95  haps_orders  bid_orders  negative_bid  \
segment       os
1-HH-Active   Android        1638.00     332132.0     85594.0       24375.0
              iOS            1282.10      43493.0     15645.0        4056.0
2-HH-inActive Android        1496.60      13770.0      3292.0         946.0
              iOS            1025.00        137.0        25.0          12.0
3-DAILY       Android         690.45    1525510.0    719377.0      407183.0
              iOS             590.60     726367.0    442142.0      237174.0
4-WEEKLY      Android         854.33    1535912.0    618480.0      322370.0
              iOS             720.00     617113.0    325619.0      169769.0
5-MONTHLY     Android        1112.33    2985690.0    884154.0      382447.0
              iOS             907.00     895723.0    362389.0      157771.0
6-QUARTERLY   Android        1185.00     961446.0    241913.0      101558.0
              iOS             992.00     200857.0     67489.0       24559.0
7-RR-ACTIVE   Android        1659.00         55.0      5188.0        1321.0
              iOS            1304.00          7.0      1694.0         339.0
8-RR-INACTIVE Android        1394.40          5.0       348.0          98.0
              iOS            1655.00          0.0         1.0           1.0

                       positive_bid  gross_psm_gps  \
segment       os
1-HH-Active   Android       61219.0       484895.0
              iOS           11589.0        33684.0
2-HH-inActive Android        2346.0        19132.0
              iOS              13.0           75.0
3-DAILY       Android      312194.0      1160259.0
              iOS          204968.0       428786.0
4-WEEKLY      Android      296110.0      1407964.0
              iOS          155850.0       391122.0
5-MONTHLY     Android      501707.0      3269094.0
              iOS          204618.0       588182.0
6-QUARTERLY   Android      140355.0      1056357.0
              iOS           42930.0       123010.0
7-RR-ACTIVE   Android        3867.0        21513.0
              iOS            1355.0         3830.0
8-RR-INACTIVE Android         250.0         1461.0
              iOS               0.0           20.0

                       gross_psm_fav_recent_history  gross_psm_google_search  \
segment       os
1-HH-Active   Android                       14032.0                  49019.0
              iOS                            1142.0                   3703.0
2-HH-inActive Android                         549.0                   1817.0
              iOS                               1.0                     14.0
3-DAILY       Android                      447409.0                 282650.0
              iOS                           60436.0                  60553.0
4-WEEKLY      Android                      341553.0                 274735.0
              iOS                           43316.0                  54168.0
5-MONTHLY     Android                      399217.0                 421624.0
              iOS                           46211.0                  68893.0
6-QUARTERLY   Android                       93357.0                 115585.0
              iOS                            5738.0                  11725.0
7-RR-ACTIVE   Android                        1637.0                   3171.0
              iOS                             173.0                    498.0
8-RR-INACTIVE Android                         116.0                    205.0
              iOS                               1.0                      3.0

                       gross_psm_stickylocation  gross_psm_hotspot  \
segment       os
1-HH-Active   Android                   63487.0            48478.0
              iOS                       47464.0             5886.0
2-HH-inActive Android                    2659.0             1917.0
              iOS                          65.0               17.0
3-DAILY       Android                  276183.0           203338.0
              iOS                      500099.0            91917.0
4-WEEKLY      Android                  310337.0           226704.0
              iOS                      503676.0            86525.0
5-MONTHLY     Android                  618020.0           416561.0
              iOS                      778554.0           119432.0
6-QUARTERLY   Android                  181202.0           129002.0
              iOS                      183678.0            22957.0
7-RR-ACTIVE   Android                    3453.0             2805.0
              iOS                        4900.0              637.0
8-RR-INACTIVE Android                     257.0              158.0
              iOS                          11.0                0.0

                       net_psm_gps  net_psm_fav_recent_history  \
segment       os
1-HH-Active   Android     297173.0                      7065.0
              iOS          19721.0                       558.0
2-HH-inActive Android      12008.0                       299.0
              iOS             48.0                         1.0
3-DAILY       Android     718984.0                    285847.0
              iOS         264014.0                     39447.0
4-WEEKLY      Android     860959.0                    213978.0
              iOS         232501.0                     27728.0
5-MONTHLY     Android    2051792.0                    252987.0
              iOS         356075.0                     29454.0
6-QUARTERLY   Android     703376.0                     60865.0
              iOS          80784.0                      3838.0
7-RR-ACTIVE   Android         48.0                         2.0
              iOS              2.0                         0.0
8-RR-INACTIVE Android          5.0                         0.0
              iOS              0.0                         0.0

                       net_psm_google_search  net_psm_stickylocation  \
segment       os
1-HH-Active   Android                27928.0                 40165.0
              iOS                     2077.0                 28538.0
2-HH-inActive Android                  980.0                  1691.0
              iOS                        6.0                    48.0
3-DAILY       Android               182539.0                174176.0
              iOS                    38592.0                308037.0
4-WEEKLY      Android               173035.0                192129.0
              iOS                    33231.0                304012.0
5-MONTHLY     Android               263764.0                393756.0
              iOS                    41634.0                479548.0
6-QUARTERLY   Android                77082.0                122218.0
              iOS                     7610.0                120826.0
7-RR-ACTIVE   Android                    5.0                     5.0
              iOS                        0.0                     5.0
8-RR-INACTIVE Android                    0.0                     1.0
              iOS                        0.0                     0.0

                       net_psm_hotspot  office_gross  transit_gross  \
segment       os
1-HH-Active   Android          29049.0      109518.0       111389.0
              iOS               3474.0       23778.0        12341.0
2-HH-inActive Android           1193.0       35092.0        44520.0
              iOS                 13.0        1595.0         1137.0
3-DAILY       Android         127076.0      754273.0       207140.0
              iOS              56834.0      483871.0        95163.0
4-WEEKLY      Android         138373.0      834371.0       300974.0
              iOS              51997.0      481177.0       116923.0
5-MONTHLY     Android         259397.0     1463079.0       824863.0
              iOS              73439.0      636687.0       218145.0
6-QUARTERLY   Android          85735.0      369258.0       228190.0
              iOS              15130.0      100409.0        36101.0
7-RR-ACTIVE   Android              4.0        9507.0         9253.0
              iOS                  0.0        3232.0         1581.0
8-RR-INACTIVE Android              0.0         618.0          701.0
              iOS                  0.0          32.0            7.0

                       office_net  transit_net    rpc  a02fe  fe2rr  ao2rr  \
segment       os
1-HH-Active   Android     58570.0      62624.0   1.44  76.45  47.91  36.63
              iOS         11714.0       6729.0   1.48  74.77  58.39  43.66
2-HH-inActive Android     20658.0      25242.0   1.36  49.56   3.85   1.91
              iOS           882.0        582.0   1.17  40.93   6.00   2.46
3-DAILY       Android    395833.0     115287.0  26.02  89.20  81.90  73.06
              iOS        242630.0      53474.0  26.49  84.18  83.74  70.49
4-WEEKLY      Android    423561.0     163885.0   9.47  86.28  72.80  62.81
              iOS        232890.0      63768.0   9.85  81.01  76.23  61.75
5-MONTHLY     Android    787518.0     462182.0   3.55  80.94  59.33  48.02
              iOS        321362.0     121236.0   3.90  73.35  66.89  49.07
6-QUARTERLY   Android    219201.0     141951.0   3.37  78.67  54.25  42.68
              iOS         56173.0      22480.0   3.44  71.00  62.35  44.26
7-RR-ACTIVE   Android         6.0         11.0   1.02  66.69  37.62  25.09
              iOS             0.0          2.0   1.00  51.35  48.32  24.81
8-RR-INACTIVE Android         0.0          1.0   1.20  61.94   3.97   2.46
              iOS             0.0          0.0    NaN  45.27   5.66   2.56

                         g2n  cobrm%  cobra%  ocara%  expired%  quick_cobra%  \
segment       os
1-HH-Active   Android  60.81    1.35   12.31   18.38      7.15          1.61
              iOS      58.85    0.86   14.38   17.97      7.93          1.75
2-HH-inActive Android  62.02    1.48   12.97   17.49      6.04          1.91
              iOS      57.88    1.43   16.62   18.91      5.16          5.16
3-DAILY       Android  63.06    0.66   15.42   15.87      4.98          2.32
              iOS      61.67    0.53   13.45   18.50      5.86          2.31
4-WEEKLY      Android  61.81    0.78   15.81   16.12      5.48          2.25
              iOS      60.02    0.61   14.47   18.25      6.65          2.37

In [36]:
segment_os.reset_index().to_clipboard(index=False)

In [37]:
segment_travel = agg_func(['segment','travelridehailing'])
segment_travel

['segment', 'travelridehailing']

                                 gross_customers  net_customers  ao_session  \
segment       travelridehailing
1-HH-Active   blank                        49292          42209    131726.0
              no                          166935         150727    600139.0
              yes                         217790         186704    735639.0
2-HH-inActive blank                          216            186     58297.0
              no                            6891           6171    203218.0
              yes                          10225           8632    290891.0
3-DAILY       blank                        29919          29910    537009.0
              no                           10503          10473    212546.0
              yes                          67973          67909   1429116.0
4-WEEKLY      blank                        71993          71546    785223.0
              no                           37050          36861    447917.0
              yes                         187141         186009   2334204.0
5-MONTHLY     blank                       298580         272674   1718658.0
              no                          318817         298891   1989206.0
              yes                         951674         872376   5892969.0
6-QUARTERLY   blank                        74801          73656    394558.0
              no                          114723         112975    638993.0
              yes                         290289         283158   1469762.0
7-RR-ACTIVE   blank                         6792              8     30264.0
              no                            5700             28     26372.0
              yes                          20529             56     88876.0
8-RR-INACTIVE blank                           82              0     34255.0
              no                             347              2     47850.0
              yes                           1504              3    129515.0

                                 fe_session  rr_session  customer_rr_sessions  \
segment       travelridehailing
1-HH-Active   blank                 98631.0     58164.0               93452.0
              no                   450079.0    204598.0              289067.0
              yes                  570859.0    284405.0              384553.0
2-HH-inActive blank                 19213.0      1125.0                1700.0
              no                    97347.0      3061.0                4313.0
              yes                  153018.0      6630.0                8819.0
3-DAILY       blank                451375.0    378944.0             1037362.0
              no                   187474.0    152997.0              323184.0
              yes                 1273326.0   1043804.0             2169015.0
4-WEEKLY      blank                634208.0    486352.0              974672.0
              no                   377132.0    269325.0              417084.0
              yes                 2018566.0   1475443.0             2291324.0
5-MONTHLY     blank               1251089.0    843183.0             1479146.0
              no                  1555527.0    879671.0             1259466.0
              yes                 4814797.0   2908149.0             4120311.0
6-QUARTERLY   blank                278518.0    177129.0              332645.0
              no                   490053.0    251859.0              391440.0
              yes                 1167786.0    646143.0              991039.0
7-RR-ACTIVE   blank                 15449.0      7658.0                9567.0
              no                    16552.0      5744.0                7608.0
              yes                   59910.0     23013.0               27744.0
8-RR-INACTIVE blank                 15371.0       886.0                1366.0
              no                    27618.0       819.0                1122.0
              yes                   81899.0      3542.0                4467.0

                                  rr_count  net_count  cobrm_count  \
segment       travelridehailing
1-HH-Active   blank               106277.0    62770.0       1069.0
              no                  347015.0   217607.0       4623.0
              yes                 451801.0   267881.0       5966.0
2-HH-inActive blank                  344.0      217.0          5.0
              no                   13318.0     8520.0        202.0
              yes                  19072.0    11549.0        277.0
3-DAILY       blank              1280867.0   791904.0       6726.0
              no                  424140.0   277914.0       2548.0
              yes                2822594.0  1764409.0      18693.0
4-WEEKLY      blank              1175857.0   707015.0       7095.0
              no                  535162.0   344027.0       4102.0
              yes                2890386.0  1768652.0      22531.0
5-MONTHLY     blank              1738003.0  1064052.0      11598.0
              no                 1578037.0  1021086.0      15352.0
              yes                5060851.0  3156374.0      42875.0
6-QUARTERLY   blank               393383.0   258031.0       3793.0
              no                  549150.0   372767.0       4884.0
              yes                1446715.0   956760.0      12174.0
7-RR-ACTIVE   blank                11037.0        8.0        230.0
              no                    9369.0       29.0        261.0
              yes                  32345.0       57.0        769.0
8-RR-INACTIVE blank                  112.0        0.0          2.0
              no                     554.0        2.0         11.0
              yes                   2371.0        4.0         61.0

                                 cobra_count  ocara_count  expired_count  \
segment       travelridehailing
1-HH-Active   blank                  15078.0      19051.0         8183.0
              no                     37065.0      63821.0        23249.0
              yes                    61546.0      83045.0        32768.0
2-HH-inActive blank                     49.0         53.0           20.0
              no                      1520.0       2252.0          808.0
              yes                     2689.0       3426.0         1107.0
3-DAILY       blank                 169157.0     238029.0        74604.0
              no                     64686.0      63219.0        15494.0
              yes                   434934.0     456669.0       146616.0
4-WEEKLY      blank                 167458.0     215293.0        78509.0
              no                     81733.0      83319.0        21536.0
              yes                   460109.0     472009.0       165534.0
5-MONTHLY     blank                 256846.0     294914.0       109579.0
              no                    222827.0     244924.0        72108.0
              yes                   798801.0     782802.0       276350.0
6-QUARTERLY   blank                  53048.0      56726.0        21559.0
              no                     68554.0      76392.0        25952.0
              yes                   206573.0     195192.0        74993.0
7-RR-ACTIVE   blank                   3902.0       4878.0         1985.0
              no                      2787.0       4726.0         1511.0
              yes                    11910.0      13783.0         5726.0
8-RR-INACTIVE blank                     38.0         55.0           17.0
              no                       169.0        285.0           85.0
              yes                      899.0       1081.0          325.0

                                 aborted_count  canceltn_count  quick_cobra  \
segment       travelridehailing
1-HH-Active   blank                      123.0         35198.0       1830.0
              no                         647.0        105509.0       5150.0
              yes                        592.0        150557.0       7769.0
2-HH-inActive blank                        0.0           107.0         17.0
              no                          16.0          3974.0        254.0
              yes                         24.0          6392.0        367.0
3-DAILY       blank                      443.0        413912.0      29078.0
              no                         276.0        130453.0      10418.0
              yes                       1252.0        910296.0      65392.0
4-WEEKLY      blank                      481.0        389846.0      27322.0
              no                         440.0        169154.0      11797.0
              yes                       1529.0        954649.0      66036.0
5-MONTHLY     blank                     1003.0        563358.0      37854.0
              no                        1732.0        483103.0      28696.0
              yes                       3607.0       1624478.0     104376.0
6-QUARTERLY   blank                      224.0        113567.0       7366.0
              no                         597.0        149830.0       8435.0
              yes                       1015.0        413939.0      24876.0
7-RR-ACTIVE   blank                       34.0          9010.0        499.0
              no                          52.0          7774.0        390.0
              yes                         98.0         26462.0       1417.0
8-RR-INACTIVE blank                        0.0            95.0          5.0
              no                           2.0           465.0         29.0
              yes                          1.0          2041.0        108.0

                                 quick_ocara  cobra_ttc_mean  cobra_ttc_p25  \
segment       travelridehailing
1-HH-Active   blank                   1213.0          119.47          58.00
              no                      4944.0          115.03          57.00
              yes                     8842.0          120.50          61.00
2-HH-inActive blank                      8.0           79.18          17.00
              no                       169.0          105.18          51.62
              yes                      412.0          113.38          55.00
3-DAILY       blank                  24771.0          119.20          74.40
              no                      6256.0          107.98          68.39
              yes                    43842.0          117.64          77.67
4-WEEKLY      blank                  19741.0          119.96          67.00
              no                      6602.0          107.56          62.21
              yes                    39490.0          117.41          69.00
5-MONTHLY     blank                  22603.0          119.09          62.00
              no                     13355.0          110.60          61.00
              yes                    51250.0          118.33          64.00
6-QUARTERLY   blank                   4959.0          117.94          63.00
              no                      3724.0          114.33          64.00
              yes                    10966.0          121.00          68.00
7-RR-ACTIVE   blank                    294.0          120.18          59.50
              no                       252.0          113.24          53.00
              yes                      737.0          121.34          59.58
8-RR-INACTIVE blank                      6.0          112.62          56.75
              no                        41.0          109.76          40.00
              yes                      127.0          120.40          57.00

                                 cobra_ttc_p50  cobra_ttc_p75  cobra_ttc_p90  \
segment       travelridehailing
1-HH-Active   blank                     103.00         161.12         232.00
              no                         99.00         155.50         222.00
              yes                       104.50         163.50         230.00
2-HH-inActive blank                      63.00         103.12         168.60
              no                         90.00         144.92         205.00
              yes                        97.75         154.75         224.00
3-DAILY       blank                     112.00         154.00         201.00
              no                         99.50         138.77         180.27
              yes                       111.21         148.81         190.62
4-WEEKLY      blank                     108.50         158.67         216.75
              no                         95.54         139.67         192.33
              yes                       107.50         153.00         206.00
5-MONTHLY     blank                     105.40         160.50         223.50
              no                         97.75         145.83         203.50
              yes                       105.20         157.50         219.00
6-QUARTERLY   blank                     105.00         157.67         220.00
              no                        102.00         150.00         207.00
              yes                       109.00         159.50         219.81
7-RR-ACTIVE   blank                     105.54         164.00         228.95
              no                         97.00         156.00         217.40
              yes                       105.00         166.50         235.00
8-RR-INACTIVE blank                     117.25         153.00         211.00
              no                         98.00         164.00         226.70
              yes                       105.00         162.00         244.50

                                 cobra_ttc_p95  ocara_ttc_mean  ocara_ttc_p25  \
segment       travelridehailing
1-HH-Active   blank                     278.12          435.42         138.00
              no                        265.00          587.80         192.00
              yes                       272.00          499.94         150.00
2-HH-inActive blank                     189.30          413.89          90.75
              no                        239.75          497.26         160.00
              yes                       257.00          496.71         139.00
3-DAILY       blank                     237.00          276.67         163.18
              no                        213.00          348.57         187.05
              yes                       223.00          302.07         169.80
4-WEEKLY      blank                     257.00          293.53         140.63
              no                        231.00          381.10         167.50
              yes                       245.25          323.33         147.60
5-MONTHLY     blank                     266.00          327.22         122.00
              no                        245.00          454.36         169.00
              yes                       260.00          373.89         137.00
6-QUARTERLY   blank                     263.00          357.87         130.00
              no                        248.00          481.01         189.00
              yes                       260.00          406.44         154.00
7-RR-ACTIVE   blank                     271.00          406.06         114.00
              no                        264.20          603.12         163.00
              yes                       275.00          473.16         131.00
8-RR-INACTIVE blank                     224.15          450.84          73.75
              no                        266.00          537.96         124.00
              yes                       278.00          417.02         105.75

                                 ocara_ttc_p50  ocara_ttc_p75  ocara_ttc_p90  \
segment       travelridehailing
1-HH-Active   blank                     288.00         544.00         939.00
              no                        405.00         741.00        1257.27
              yes                       327.00         620.00        1074.00
2-HH-inActive blank                     276.00         519.50        1041.00
              no                        350.00         620.00        1067.00
              yes                       318.00         596.00        1055.60
3-DAILY       blank                     238.29         338.33         471.67
              no                        286.00         428.00         625.87
              yes                       250.71         367.25         528.17
4-WEEKLY      blank                     231.00         363.35         551.65
              no                        293.00         477.67         742.00
              yes                       249.67         401.00         620.00
5-MONTHLY     blank                     233.29         405.00         668.00
              no                        328.00         568.00         928.00
              yes                       264.00         463.00         764.00
6-QUARTERLY   blank                     256.00         444.00         734.00
              no                        355.00         603.00         978.00
              yes                       291.00         501.00         822.00
7-RR-ACTIVE   blank                     249.00         486.00         895.00
              no                        379.83         751.00        1357.50
              yes                       290.00         581.00        1060.00
8-RR-INACTIVE blank                     198.00         412.75        1213.20
              no                        348.00         659.67        1240.40
              yes                       243.00         481.50         941.60

                                 ocara_ttc_p95  haps_orders  bid_orders  \
segment       travelridehailing
1-HH-Active   blank                    1287.30      42325.0     14921.0
              no                       1738.00     146437.0     32501.0
              yes                      1540.00     186863.0     53817.0
2-HH-inActive blank                    1534.00        146.0        20.0
              no                       1466.40       5637.0      1234.0
              yes                      1498.75       8124.0      2063.0
3-DAILY       blank                     589.79     624674.0    383529.0
              no                        805.48     220133.0     72889.0
              yes                       666.00    1407070.0    705101.0
4-WEEKLY      blank                     718.50     532754.0    281598.0
              no                        969.88     261645.0     74052.0
              yes                       819.50    1358626.0    588449.0
5-MONTHLY     blank                     905.00     779111.0    314808.0
              no                       1261.50     746092.0    171002.0
              yes                      1047.00    2356210.0    760733.0
6-QUARTERLY   blank                     987.88     185798.0     60777.0
              no                       1305.50     268207.0     54145.0
              yes                      1117.00     708298.0    194480.0
7-RR-ACTIVE   blank                    1293.00          6.0      1524.0
              no                       1987.50         19.0      1122.0
              yes                      1556.00         37.0      4236.0
8-RR-INACTIVE blank                    1603.00          0.0         2.0
              no                       1842.20          1.0        60.0
              yes                      1322.70          4.0       287.0

                                 negative_bid  positive_bid  gross_psm_gps  \
segment       travelridehailing
1-HH-Active   blank                    3816.0       11105.0        33429.0
              no                       9587.0       22914.0       225939.0
              yes                     15028.0       38789.0       259211.0
2-HH-inActive blank                      10.0          10.0           90.0
              no                        344.0         890.0         8300.0
              yes                       604.0        1459.0        10817.0
3-DAILY       blank                  203336.0      180193.0       367243.0
              no                      40020.0       32869.0       200060.0
              yes                    401001.0      304100.0      1021742.0
4-WEEKLY      blank                  144095.0      137503.0       338412.0

In [38]:
segment_travel.reset_index().to_clipboard(index=False)

In [39]:
segment_qc = agg_func(['segment','quick_commerce'])
segment_qc

['segment', 'quick_commerce']

                              gross_customers  net_customers  ao_session  \
segment       quick_commerce
1-HH-Active   blank                     49292          42209    131726.0
              no                       165806         148888    605294.0
              yes                      218919         188543    730484.0
2-HH-inActive blank                       216            186     58297.0
              no                         6873           6078    200712.0
              yes                       10243           8725    293397.0
3-DAILY       blank                     29919          29910    537009.0
              no                        10350          10311    232290.0
              yes                       68126          68071   1409372.0
4-WEEKLY      blank                     71993          71546    785223.0
              no                        33723          33456    437110.0
              yes                      190468         189414   2345011.0
5-MONTHLY     blank                    298580         272674   1718658.0
              no                       280624         260472   1837627.0
              yes                      989867         910795   6044548.0
6-QUARTERLY   blank                     74801          73656    394558.0
              no                       106539         104781    616633.0
              yes                      298473         291352   1492122.0
7-RR-ACTIVE   blank                      6792              8     30264.0
              no                         6120             23     28721.0
              yes                       20109             61     86527.0
8-RR-INACTIVE blank                        82              0     34255.0
              no                          388              1     49729.0
              yes                        1463              4    127636.0

                              fe_session  rr_session  customer_rr_sessions  \
segment       quick_commerce
1-HH-Active   blank              98631.0     58164.0               93452.0
              no                457949.0    208705.0              290483.0
              yes               562989.0    280298.0              383137.0
2-HH-inActive blank              19213.0      1125.0                1700.0
              no                 98516.0      3071.0                4257.0
              yes               151849.0      6620.0                8875.0
3-DAILY       blank             451375.0    378944.0             1037362.0
              no                204154.0    160435.0              321925.0
              yes              1256646.0   1036366.0             2170274.0
4-WEEKLY      blank             634208.0    486352.0              974672.0
              no                368793.0    253411.0              383376.0
              yes              2026905.0   1491357.0             2325032.0
5-MONTHLY     blank            1251089.0    843183.0             1479146.0
              no               1448212.0    798337.0             1129975.0
              yes              4922112.0   2989483.0             4249802.0
6-QUARTERLY   blank             278518.0    177129.0              332645.0
              no                476609.0    243496.0              374875.0
              yes              1181230.0    654506.0             1007604.0
7-RR-ACTIVE   blank              15449.0      7658.0                9567.0
              no                 18541.0      6199.0                8048.0
              yes                57921.0     22558.0               27304.0
8-RR-INACTIVE blank              15371.0       886.0                1366.0
              no                 29342.0       828.0                1106.0
              yes                80175.0      3533.0                4483.0

                               rr_count  net_count  cobrm_count  cobra_count  \
segment       quick_commerce
1-HH-Active   blank            106277.0    62770.0       1069.0      15078.0
              no               348530.0   213664.0       5330.0      37111.0
              yes              450286.0   271824.0       5259.0      61500.0
2-HH-inActive blank               344.0      217.0          5.0         49.0
              no                13618.0     8336.0        257.0       1607.0
              yes               18772.0    11733.0        222.0       2602.0
3-DAILY       blank           1280867.0   791904.0       6726.0     169157.0
              no               418457.0   268932.0       3013.0      64164.0
              yes             2828277.0  1773391.0      18228.0     435456.0
4-WEEKLY      blank           1175857.0   707015.0       7095.0     167458.0
              no               486480.0   305949.0       4496.0      74737.0
              yes             2939068.0  1806730.0      22137.0     467105.0
5-MONTHLY     blank           1738003.0  1064052.0      11598.0     256846.0
              no              1405811.0   895269.0      15232.0     199128.0
              yes             5233077.0  3282191.0      42995.0     822500.0
6-QUARTERLY   blank            393383.0   258031.0       3793.0      53048.0
              no               523121.0   352228.0       5015.0      64960.0
              yes             1472744.0   977299.0      12043.0     210167.0
7-RR-ACTIVE   blank             11037.0        8.0        230.0       3902.0
              no                 9958.0       24.0        311.0       2953.0
              yes               31756.0       62.0        719.0      11744.0
8-RR-INACTIVE blank               112.0        0.0          2.0         38.0
              no                  634.0        1.0         12.0        204.0
              yes                2291.0        5.0         60.0        864.0

                              ocara_count  expired_count  aborted_count  \
segment       quick_commerce
1-HH-Active   blank               19051.0         8183.0          123.0
              no                  66716.0        25053.0          654.0
              yes                 80150.0        30964.0          585.0
2-HH-inActive blank                  53.0           20.0            0.0
              no                   2544.0          854.0           20.0
              yes                  3134.0         1061.0           20.0
3-DAILY       blank              238029.0        74604.0          443.0
              no                  62402.0        19677.0          266.0
              yes                457486.0       142433.0         1262.0
4-WEEKLY      blank              215293.0        78509.0          481.0
              no                  76678.0        24166.0          450.0
              yes                478650.0       162904.0         1519.0
5-MONTHLY     blank              294914.0       109579.0         1003.0
              no                 218696.0        75746.0         1729.0
              yes                809030.0       272712.0         3610.0
6-QUARTERLY   blank               56726.0        21559.0          224.0
              no                  72017.0        28312.0          586.0
              yes                199567.0        72633.0         1026.0
7-RR-ACTIVE   blank                4878.0         1985.0           34.0
              no                   4826.0         1790.0           52.0
              yes                 13683.0         5447.0           98.0
8-RR-INACTIVE blank                  55.0           17.0            0.0
              no                    323.0           93.0            1.0
              yes                  1043.0          317.0            2.0

                              canceltn_count  quick_cobra  quick_ocara  \
segment       quick_commerce
1-HH-Active   blank                  35198.0       1830.0       1213.0
              no                    109157.0       5052.0       7212.0
              yes                   146909.0       7867.0       6574.0
2-HH-inActive blank                    107.0         17.0          8.0
              no                      4408.0        259.0        369.0
              yes                     5958.0        362.0        212.0
3-DAILY       blank                 413912.0      29078.0      24771.0
              no                    129579.0       9669.0       6350.0
              yes                   911170.0      66141.0      43748.0
4-WEEKLY      blank                 389846.0      27322.0      19741.0
              no                    155911.0      10237.0       6935.0
              yes                   967892.0      67596.0      39157.0
5-MONTHLY     blank                 563358.0      37854.0      22603.0
              no                    433056.0      24560.0      13262.0
              yes                  1674525.0     108512.0      51343.0
6-QUARTERLY   blank                 113567.0       7366.0       4959.0
              no                    141992.0       7666.0       3498.0
              yes                   421777.0      25645.0      11192.0
7-RR-ACTIVE   blank                   9010.0        499.0        294.0
              no                      8090.0        379.0        286.0
              yes                    26146.0       1428.0        703.0
8-RR-INACTIVE blank                     95.0          5.0          6.0
              no                       539.0         23.0         45.0
              yes                     1967.0        114.0        123.0

                              cobra_ttc_mean  cobra_ttc_p25  cobra_ttc_p50  \
segment       quick_commerce
1-HH-Active   blank                   119.47          58.00         103.00
              no                      117.87          59.00         102.00
              yes                     118.88          60.00         103.00
2-HH-inActive blank                    79.18          17.00          63.00
              no                      108.25          51.50          94.00
              yes                     111.79          55.69          95.25
3-DAILY       blank                   119.20          74.40         112.00
              no                      114.89          74.79         107.26
              yes                     116.64          76.67         110.00
4-WEEKLY      blank                   119.96          67.00         108.50
              no                      112.29          66.50         101.50
              yes                     116.54          68.07         106.44
5-MONTHLY     blank                   119.09          62.00         105.40
              no                      114.57          63.00         102.00
              yes                     117.17          63.50         104.00
6-QUARTERLY   blank                   117.94          63.00         105.00
              no                      118.00          67.00         106.00
              yes                     119.73          67.00         107.50
7-RR-ACTIVE   blank                   120.18          59.50         105.54
              no                      118.17          56.00         102.00
              yes                     120.30          59.00         104.00
8-RR-INACTIVE blank                   112.62          56.75         117.25
              no                      111.04          59.17         105.00
              yes                     120.60          54.06         103.00

                              cobra_ttc_p75  cobra_ttc_p90  cobra_ttc_p95  \
segment       quick_commerce
1-HH-Active   blank                  161.12         232.00         278.12
              no                     160.00         225.50         268.00
              yes                    161.00         227.83         270.00
2-HH-inActive blank                  103.12         168.60         189.30
              no                     145.00         212.25         252.50
              yes                    153.12         218.00         254.00
3-DAILY       blank                  154.00         201.00         237.00
              no                     146.73         187.67         220.50
              yes                    147.67         189.86         222.00
4-WEEKLY      blank                  158.67         216.75         257.00
              no                     146.00         199.00         238.00
              yes                    152.00         205.00         244.00
5-MONTHLY     blank                  160.50         223.50         266.00
              no                     151.00         210.00         251.00
              yes                    156.00         217.00         258.75
6-QUARTERLY   blank                  157.67         220.00         263.00
              no                     155.00         213.00         254.00
              yes                    158.00         218.00         258.00
7-RR-ACTIVE   blank                  164.00         228.95         271.00
              no                     163.38         229.00         270.75
              yes                    165.00         233.00         275.00
8-RR-INACTIVE blank                  153.00         211.00         224.15
              no                     156.75         199.80         230.60
              yes                    167.75         250.80         281.96

                              ocara_ttc_mean  ocara_ttc_p25  ocara_ttc_p50  \
segment       quick_commerce
1-HH-Active   blank                   435.42         138.00         288.00
              no                      590.53         188.00         403.00
              yes                     498.26         153.00         330.00
2-HH-inActive blank                   413.89          90.75         276.00
              no                      516.40         159.00         345.00
              yes                     483.37         139.00         320.00
3-DAILY       blank                   276.67         163.18         238.29
              no                      357.89         192.26         294.60
              yes                     300.79         169.29         250.00
4-WEEKLY      blank                   293.53         140.63         231.00
              no                      394.83         173.00         298.00
              yes                     322.00         147.40         249.12
5-MONTHLY     blank                   327.22         122.00         233.29
              no                      466.07         172.00         333.00
              yes                     373.54         137.00         264.67
6-QUARTERLY   blank                   357.87         130.00         256.00
              no                      501.48         197.00         366.00
              yes                     401.13         152.50         289.00
7-RR-ACTIVE   blank                   406.06         114.00         249.00
              no                      600.04         160.50         375.00
              yes                     472.97         132.00         290.50
8-RR-INACTIVE blank                   450.84          73.75         198.00
              no                      522.98         129.00         330.00
              yes                     417.97         105.00         244.50

                              ocara_ttc_p75  ocara_ttc_p90  ocara_ttc_p95  \
segment       quick_commerce
1-HH-Active   blank                  544.00         939.00        1287.30
              no                     749.00        1269.00        1774.00
              yes                    617.00        1069.00        1507.52
2-HH-inActive blank                  519.50        1041.00        1534.00
              no                     652.75        1094.00        1503.00
              yes                    581.75        1048.20        1484.10
3-DAILY       blank                  338.33         471.67         589.79
              no                     438.34         639.00         836.00
              yes                    365.98         526.00         662.33
4-WEEKLY      blank                  363.35         551.65         718.50
              no                     491.00         774.00        1022.00
              yes                    400.67         616.68         814.00
5-MONTHLY     blank                  405.00         668.00         905.00
              no                     580.00         950.00        1310.00
              yes                    464.00         763.00        1043.00
6-QUARTERLY   blank                  444.00         734.00         987.88
              no                     622.00        1010.05        1363.77
              yes                    498.00         813.50        1103.80
7-RR-ACTIVE   blank                  486.00         895.00        1293.00
              no                     765.50        1363.80        1907.90
              yes                    580.25        1055.15        1550.00
8-RR-INACTIVE blank                  412.75        1213.20        1603.00
              no                     632.75        1203.50        1821.88
              yes                    483.62         920.00        1325.30

                              haps_orders  bid_orders  negative_bid  \
segment       quick_commerce
1-HH-Active   blank               42325.0     14921.0        3816.0
              no                 143795.0     32918.0        9749.0
              yes                189505.0     53400.0       14866.0
2-HH-inActive blank                 146.0        20.0          10.0
              no                   5535.0      1395.0         374.0
              yes                  8226.0      1902.0         574.0
3-DAILY       blank              624674.0    383529.0      203336.0
              no                 213144.0     72160.0       46512.0
              yes               1414059.0    705830.0      394509.0
4-WEEKLY      blank              532754.0    281598.0      144095.0
              no                 232699.0     64762.0       34922.0
              yes               1387572.0    597739.0      313122.0
5-MONTHLY     blank              779111.0    314808.0      134284.0
              no                 655778.0    143167.0       62774.0
              yes               2446524.0    788568.0      343160.0
6-QUARTERLY   blank              185798.0     60777.0       21500.0
              no                 254955.0     48751.0       21200.0
              yes                721550.0    199874.0       83417.0
7-RR-ACTIVE   blank                   6.0      1524.0         291.0
              no                     15.0      1141.0         318.0
              yes                    41.0      4217.0        1051.0
8-RR-INACTIVE blank                   0.0         2.0           0.0
              no                      1.0        70.0          13.0
              yes                     4.0       277.0          86.0

                              positive_bid  gross_psm_gps  \
segment       quick_commerce
1-HH-Active   blank                11105.0        33429.0
              no                   23169.0       229639.0
              yes                  38534.0       255511.0
2-HH-inActive blank                   10.0           90.0
              no                    1021.0         8545.0
              yes                   1328.0        10572.0
3-DAILY       blank               180193.0       367243.0
              no                   25648.0       200757.0
              yes                 311321.0      1021045.0
4-WEEKLY      blank               137503.0       338412.0
              no                   29840.0       260383.0
              yes                 284617.0      1200291.0
5-MONTHLY     blank               180524.0       515507.0
              no                   80393.0       870390.0
              yes                 445408.0      2471379.0
6-QUARTERLY   blank                39277.0       116420.0
              no                   27551.0       333896.0
              yes                 116457.0       729051.0
7-RR-ACTIVE   blank                 1233.0         3564.0
              no                     823.0         5957.0
              yes                   3166.0        15822.0

In [40]:
segment_qc.reset_index().to_clipboard(index=False)

In [43]:
segment_travel_qc = agg_func(['segment','travelridehailing','quick_commerce'])
segment_travel_qc

['segment', 'travelridehailing', 'quick_commerce']

                                                gross_customers  \
segment       travelridehailing quick_commerce
1-HH-Active   blank             blank                     49292
              no                no                       105241
                                yes                       61694
              yes               no                        60565
                                yes                      157225
2-HH-inActive blank             blank                       216
              no                no                         4150
                                yes                        2741
              yes               no                         2723
                                yes                        7502
3-DAILY       blank             blank                     29919
              no                no                         4486
                                yes                        6017
              yes               no                         5864
                                yes                       62109
4-WEEKLY      blank             blank                     71993
              no                no                        15586
                                yes                       21464
              yes               no                        18137
                                yes                      169004
5-MONTHLY     blank             blank                    298580
              no                no                       152199
                                yes                      166618
              yes               no                       128425
                                yes                      823249
6-QUARTERLY   blank             blank                     74801
              no                no                        59514
                                yes                       55209
              yes               no                        47025
                                yes                      243264
7-RR-ACTIVE   blank             blank                      6792
              no                no                         2984
                                yes                        2716
              yes               no                         3136
                                yes                       17393
8-RR-INACTIVE blank             blank                        82
              no                no                          182
                                yes                         165
              yes               no                          206
                                yes                        1298

                                                net_customers  ao_session  \
segment       travelridehailing quick_commerce
1-HH-Active   blank             blank                   42209    131726.0
              no                no                      95677    384032.0
                                yes                     55050    216107.0
              yes               no                      53211    221262.0
                                yes                    133493    514377.0
2-HH-inActive blank             blank                     186     58297.0
              no                no                       3743    118519.0
                                yes                      2428     84699.0
              yes               no                       2335     82193.0
                                yes                      6297    208698.0
3-DAILY       blank             blank                   29910    537009.0
              no                no                       4465     94190.0
                                yes                      6008    118356.0
              yes               no                       5846    138100.0
                                yes                     62063   1291016.0
4-WEEKLY      blank             blank                   71546    785223.0
              no                no                      15483    196343.0
                                yes                     21378    251574.0
              yes               no                      17973    240767.0
                                yes                    168036   2093437.0
5-MONTHLY     blank             blank                  272674   1718658.0
              no                no                     142411    982155.0
                                yes                    156480   1007051.0
              yes               no                     118061    855472.0
                                yes                    754315   5037497.0
6-QUARTERLY   blank             blank                   73656    394558.0
              no                no                      58650    349047.0
                                yes                     54325    289946.0
              yes               no                      46131    267586.0
                                yes                    237027   1202176.0
7-RR-ACTIVE   blank             blank                       8     30264.0
              no                no                         18     13807.0
                                yes                        10     12565.0
              yes               no                          5     14914.0
                                yes                        51     73962.0
8-RR-INACTIVE blank             blank                       0     34255.0
              no                no                          1     24769.0
                                yes                         1     23081.0
              yes               no                          0     24960.0
                                yes                         3    104555.0

                                                fe_session  rr_session  \
segment       travelridehailing quick_commerce
1-HH-Active   blank             blank              98631.0     58164.0
              no                no                288292.0    129569.0
                                yes               161787.0     75029.0
              yes               no                169657.0     79136.0
                                yes               401202.0    205269.0
2-HH-inActive blank             blank              19213.0      1125.0
              no                no                 57121.0      1747.0
                                yes                40226.0      1314.0
              yes               no                 41395.0      1324.0
                                yes               111623.0      5306.0
3-DAILY       blank             blank             451375.0    378944.0
              no                no                 82680.0     66092.0
                                yes               104794.0     86905.0
              yes               no                121474.0     94343.0
                                yes              1151852.0    949461.0
4-WEEKLY      blank             blank             634208.0    486352.0
              no                no                164744.0    114225.0
                                yes               212388.0    155100.0
              yes               no                204049.0    139186.0
                                yes              1814517.0   1336257.0
5-MONTHLY     blank             blank            1251089.0    843183.0
              no                no                767434.0    421180.0
                                yes               788093.0    458491.0
              yes               no                680778.0    377157.0
                                yes              4134019.0   2530992.0
6-QUARTERLY   blank             blank             278518.0    177129.0
              no                no                268605.0    136561.0
                                yes               221448.0    115298.0
              yes               no                208004.0    106935.0
                                yes               959782.0    539208.0
7-RR-ACTIVE   blank             blank              15449.0      7658.0
              no                no                  8820.0      2988.0
                                yes                 7732.0      2756.0
              yes               no                  9721.0      3211.0
                                yes                50189.0     19802.0
8-RR-INACTIVE blank             blank              15371.0       886.0
              no                no                 14400.0       376.0
                                yes                13218.0       443.0
              yes               no                 14942.0       452.0
                                yes                66957.0      3090.0

                                                customer_rr_sessions  \
segment       travelridehailing quick_commerce
1-HH-Active   blank             blank                        93452.0
              no                no                          183286.0
                                yes                         105781.0
              yes               no                          107197.0
                                yes                         277356.0
2-HH-inActive blank             blank                         1700.0
              no                no                            2439.0
                                yes                           1874.0
              yes               no                            1818.0
                                yes                           7001.0
3-DAILY       blank             blank                      1037362.0
              no                no                          137095.0
                                yes                         186089.0
              yes               no                          184830.0
                                yes                        1984185.0
4-WEEKLY      blank             blank                       974672.0
              no                no                          175727.0
                                yes                         241357.0
              yes               no                          207649.0
                                yes                        2083675.0
5-MONTHLY     blank             blank                      1479146.0
              no                no                          606365.0
                                yes                         653101.0
              yes               no                          523610.0
                                yes                        3596701.0
6-QUARTERLY   blank             blank                       332645.0
              no                no                          213242.0
                                yes                         178198.0
              yes               no                          161633.0
                                yes                         829406.0
7-RR-ACTIVE   blank             blank                         9567.0
              no                no                            3987.0
                                yes                           3621.0
              yes               no                            4061.0
                                yes                          23683.0
8-RR-INACTIVE blank             blank                         1366.0
              no                no                             532.0
                                yes                            590.0
              yes               no                             574.0
                                yes                           3893.0

                                                 rr_count  net_count  \
segment       travelridehailing quick_commerce
1-HH-Active   blank             blank            106277.0    62770.0
              no                no               220782.0   137778.0
                                yes              126233.0    79829.0
              yes               no               127748.0    75886.0
                                yes              324053.0   191995.0
2-HH-inActive blank             blank               344.0      217.0
              no                no                 8252.0     5207.0
                                yes                5066.0     3313.0
              yes               no                 5366.0     3129.0
                                yes               13706.0     8420.0
3-DAILY       blank             blank           1280867.0   791904.0
              no                no               179475.0   116738.0
                                yes              244665.0   161176.0
              yes               no               238982.0   152194.0
                                yes             2583612.0  1612215.0
4-WEEKLY      blank             blank           1175857.0   707015.0
              no                no               226425.0   142899.0
                                yes              308737.0   201128.0
              yes               no               260055.0   163050.0
                                yes             2630331.0  1605602.0
5-MONTHLY     blank             blank           1738003.0  1064052.0
              no                no               761359.0   486578.0
                                yes              816678.0   534508.0
              yes               no               644452.0   408691.0
                                yes             4416399.0  2747683.0
6-QUARTERLY   blank             blank            393383.0   258031.0
              no                no               294557.0   198442.0
                                yes              254593.0   174325.0
              yes               no               228564.0   153786.0
                                yes             1218151.0   802974.0
7-RR-ACTIVE   blank             blank             11037.0        8.0
              no                no                 4917.0       19.0
                                yes                4452.0       10.0
              yes               no                 5041.0        5.0
                                yes               27304.0       52.0
8-RR-INACTIVE blank             blank               112.0        0.0
              no                no                  310.0        1.0
                                yes                 244.0        1.0
              yes               no                  324.0        0.0
                                yes                2047.0        4.0

                                                cobrm_count  cobra_count  \
segment       travelridehailing quick_commerce
1-HH-Active   blank             blank                1069.0      15078.0
              no                no                   3147.0      22673.0
                                yes                  1476.0      14392.0
              yes               no                   2183.0      14438.0
                                yes                  3783.0      47108.0
2-HH-inActive blank             blank                   5.0         49.0
              no                no                    149.0        924.0
                                yes                    53.0        596.0
              yes               no                    108.0        683.0
                                yes                   169.0       2006.0
3-DAILY       blank             blank                6726.0     169157.0
              no                no                   1128.0      27420.0
                                yes                  1420.0      37266.0
              yes               no                   1885.0      36744.0
                                yes                 16808.0     398190.0
4-WEEKLY      blank             blank                7095.0     167458.0
              no                no                   2035.0      35305.0
                                yes                  2067.0      46428.0
              yes               no                   2461.0      39432.0
                                yes                 20070.0     420677.0
5-MONTHLY     blank             blank               11598.0     256846.0
              no                no                   8520.0     105889.0
                                yes                  6832.0     116938.0
              yes               no                   6712.0      93239.0
                                yes                 36163.0     705562.0
6-QUARTERLY   blank             blank                3793.0      53048.0
              no                no                   2834.0      35953.0
                                yes                  2050.0      32601.0
              yes               no                   2181.0      29007.0
                                yes                  9993.0     177566.0
7-RR-ACTIVE   blank             blank                 230.0       3902.0
              no                no                    152.0       1372.0
                                yes                   109.0       1415.0
              yes               no                    159.0       1581.0
                                yes                   610.0      10329.0
8-RR-INACTIVE blank             blank                   2.0         38.0
              no                no                      5.0         93.0
                                yes                     6.0         76.0
              yes               no                      7.0        111.0
                                yes                    54.0        788.0

                                                ocara_count  expired_count  \
segment       travelridehailing quick_commerce
1-HH-Active   blank             blank               19051.0         8183.0
              no                no                  41300.0        15439.0
                                yes                 22521.0         7810.0
              yes               no                  25416.0         9614.0
                                yes                 57629.0        23154.0
2-HH-inActive blank             blank                  53.0           20.0
              no                no                   1433.0          527.0
                                yes                   819.0          281.0
              yes               no                   1111.0          327.0
                                yes                  2315.0          780.0
3-DAILY       blank             blank              238029.0        74604.0
              no                no                  26798.0         7258.0
                                yes                 36421.0         8236.0
              yes               no                  35604.0        12419.0
                                yes                421065.0       134197.0
4-WEEKLY      blank             blank              215293.0        78509.0
              no                no                  35817.0        10159.0
                                yes                 47502.0        11377.0
              yes               no                  40861.0        14007.0
                                yes                431148.0       151527.0
5-MONTHLY     blank             blank              294914.0       109579.0
              no                no                 120377.0        39023.0
                                yes                124547.0        33085.0
              yes               no                  98319.0        36723.0
                                yes                684483.0       239627.0
6-QUARTERLY   blank             blank               56726.0        21559.0
              no                no                  41567.0        15389.0
                                yes                 34825.0        10563.0
              yes               no                  30450.0        12923.0
                                yes                164742.0        62070.0
7-RR-ACTIVE   blank             blank                4878.0         1985.0

In [44]:
segment_travel_qc.reset_index().to_clipboard(index=False)

In [41]:
segment_office = agg_func(['segment','office_tag'])
segment_office

['segment', 'office_tag']

                          gross_customers  net_customers  ao_session  \
segment       office_tag
1-HH-Active   office                69231          64987    253508.0
              other                364786         314653   1213996.0
2-HH-inActive office                 2494           2318     43597.0
              other                 14838          12671    508809.0
3-DAILY       office                87009          86960   1759595.0
              other                 21386          21332    419076.0
4-WEEKLY      office               208956         208024   2559200.0
              other                 87228          86392   1008144.0
5-MONTHLY     office               683412         650168   4620346.0
              other                885659         793773   4980487.0
6-QUARTERLY   office               135120         133170    827961.0
              other                344693         336619   1675352.0
7-RR-ACTIVE   office                   44              3       401.0
              other                 32977             89    145111.0
8-RR-INACTIVE office                    2              0       561.0
              other                  1931              5    211059.0

                          fe_session  rr_session  customer_rr_sessions  \
segment       office_tag
1-HH-Active   office        198858.0     98665.0              139722.0
              other         920711.0    448502.0              627350.0
2-HH-inActive office         21575.0      1253.0                1703.0
              other         248003.0      9563.0               13129.0
3-DAILY       office       1541566.0   1271510.0             2905782.0
              other         370609.0    304235.0              623779.0
4-WEEKLY      office       2178765.0   1614173.0             2734068.0
              other         851141.0    616947.0              949012.0
5-MONTHLY     office       3757750.0   2385104.0             3716502.0
              other        3863663.0   2245899.0             3142421.0
6-QUARTERLY   office        676611.0    412310.0              708743.0
              other        1259746.0    662821.0             1006381.0
7-RR-ACTIVE   office           253.0       140.0                 192.0
              other          91658.0     36275.0               44727.0
8-RR-INACTIVE office           415.0       232.0                 329.0
              other         124473.0      5015.0                6626.0

                           rr_count  net_count  cobrm_count  cobra_count  \
segment       office_tag
1-HH-Active   office       164066.0   104712.0       1752.0      20207.0
              other        741027.0   443546.0       9906.0      93482.0
2-HH-inActive office         5189.0     3491.0         73.0        619.0
              other         27545.0    16795.0        411.0       3639.0
3-DAILY       office      3735070.0  2327465.0      23222.0     556075.0
              other        792531.0   506762.0       4745.0     112702.0
4-WEEKLY      office      3431082.0  2092405.0      25486.0     536262.0
              other       1170323.0   727289.0       8242.0     173038.0
5-MONTHLY     office      4602329.0  2879487.0      38090.0     718442.0
              other       3774562.0  2362025.0      31735.0     560032.0
6-QUARTERLY   office      1045888.0   681464.0       9633.0     154069.0
              other       1343360.0   906094.0      11218.0     174106.0
7-RR-ACTIVE   office           68.0        3.0          2.0         23.0
              other         52683.0       91.0       1258.0      18576.0
8-RR-INACTIVE office            5.0        0.0          0.0          5.0
              other          3032.0        6.0         74.0       1101.0

                          ocara_count  expired_count  aborted_count  \
segment       office_tag
1-HH-Active   office          26257.0        10932.0          205.0
              other          139660.0        53268.0         1157.0
2-HH-inActive office            733.0          267.0            6.0
              other            4998.0         1668.0           34.0
3-DAILY       office         631242.0       195446.0         1601.0
              other          126675.0        41268.0          370.0
4-WEEKLY      office         573964.0       201210.0         1737.0
              other          196657.0        64369.0          713.0
5-MONTHLY     office         709908.0       253456.0         2925.0
              other          612732.0       204581.0         3417.0
6-QUARTERLY   office         144654.0        55405.0          657.0
              other          183656.0        67099.0         1179.0
7-RR-ACTIVE   office             29.0           10.0            1.0
              other           23358.0         9212.0          183.0
8-RR-INACTIVE office              0.0            0.0            0.0
              other            1421.0          427.0            3.0

                          canceltn_count  quick_cobra  quick_ocara  \
segment       office_tag
1-HH-Active   office             48216.0       2444.0       1951.0
              other             243048.0      12305.0      13048.0
2-HH-inActive office              1425.0         93.0         46.0
              other               9048.0        545.0        543.0
3-DAILY       office           1210539.0      87136.0      61915.0
              other             244122.0      17752.0      12954.0
4-WEEKLY      office           1135712.0      79071.0      48183.0
              other             377937.0      26084.0      17650.0
5-MONTHLY     office           1466440.0      96539.0      48118.0
              other            1204499.0      74387.0      39090.0
6-QUARTERLY   office            308356.0      19203.0       9401.0
              other             368980.0      21474.0      10248.0
7-RR-ACTIVE   office                54.0          1.0          1.0
              other              43192.0       2305.0       1282.0
8-RR-INACTIVE office                 5.0          0.0          0.0
              other               2596.0        142.0        174.0

                          cobra_ttc_mean  cobra_ttc_p25  cobra_ttc_p50  \
segment       office_tag
1-HH-Active   office              121.57          62.00         106.00
              other               118.06          59.00         101.92
2-HH-inActive office              109.60          50.00          95.00
              other               110.18          54.50          94.50
3-DAILY       office              117.75          76.72         110.83
              other               114.74          72.31         108.00
4-WEEKLY      office              118.21          69.00         107.67
              other               113.50          64.60         103.00
5-MONTHLY     office              118.51          65.33         105.71
              other               115.82          61.00         102.00
6-QUARTERLY   office              121.29          69.67         110.00
              other               117.74          64.50         105.00
7-RR-ACTIVE   office              141.64          73.75         129.00
              other               119.91          58.54         104.00
8-RR-INACTIVE office               95.83          86.42          95.83
              other               118.69          54.88         103.25

                          cobra_ttc_p75  cobra_ttc_p90  cobra_ttc_p95  \
segment       office_tag
1-HH-Active   office             165.00         229.00         272.00
              other              160.00         227.00         270.00
2-HH-inActive office             152.75         211.10         248.28
              other              149.00         216.60         255.00
3-DAILY       office             149.25         193.00         227.00
              other              148.00         191.86         223.67
4-WEEKLY      office             154.00         208.50         248.00
              other              149.40         204.00         243.00
5-MONTHLY     office             157.00         217.00         259.00
              other              155.00         217.00         259.00
6-QUARTERLY   office             158.67         217.00         258.00
              other              156.75         217.00         259.00
7-RR-ACTIVE   office             186.25         245.70         332.60
              other              164.50         231.00         273.00
8-RR-INACTIVE office             105.25         110.90         112.78
              other              163.62         240.80         272.80

                          ocara_ttc_mean  ocara_ttc_p25  ocara_ttc_p50  \
segment       office_tag
1-HH-Active   office              504.16         164.00         342.38
              other               530.01         162.00         352.00
2-HH-inActive office              519.08         167.75         360.50
              other               492.76         145.00         324.67
3-DAILY       office              295.15         168.77         248.30
              other               316.75         169.63         256.50
4-WEEKLY      office              315.96         148.00         246.29
              other               339.58         147.00         255.58
5-MONTHLY     office              359.62         139.00         260.00
              other               398.34         137.50         276.00
6-QUARTERLY   office              393.11         158.00         289.80
              other               429.68         155.50         305.00
7-RR-ACTIVE   office              427.12         135.50         303.00
              other               485.02         132.00         295.00
8-RR-INACTIVE office                 NaN            NaN            NaN
              other               442.28         108.62         260.00

                          ocara_ttc_p75  ocara_ttc_p90  ocara_ttc_p95  \
segment       office_tag
1-HH-Active   office             626.00        1066.23        1458.00
              other              664.00        1146.00        1621.85
2-HH-inActive office             657.00        1108.60        1529.90
              other              602.50        1054.60        1481.60
3-DAILY       office             359.41         513.00         645.57
              other              385.32         565.50         718.50
4-WEEKLY      office             392.25         600.67         791.00
              other              421.65         662.51         889.00
5-MONTHLY     office             447.00         726.00         980.00
              other              494.00         830.00        1144.00
6-QUARTERLY   office             485.42         785.00        1058.32
              other              536.00         881.00        1199.00
7-RR-ACTIVE   office             582.25        1006.65        1181.62
              other              598.00        1090.00        1583.15
8-RR-INACTIVE office                NaN            NaN            NaN
              other              519.00        1020.90        1428.55

                          haps_orders  bid_orders  negative_bid  positive_bid  \
segment       office_tag
1-HH-Active   office          68725.0     19710.0        5304.0       14406.0
              other          306900.0     81529.0       23127.0       58402.0
2-HH-inActive office           2319.0       535.0         154.0         381.0
              other           11588.0      2782.0         804.0        1978.0
3-DAILY       office        1842120.0    986585.0      531678.0      454907.0
              other          409757.0    174934.0      112679.0       62255.0
4-WEEKLY      office        1586010.0    745112.0      377836.0      367276.0
              other          567015.0    198987.0      114303.0       84684.0
5-MONTHLY     office        2113172.0    767376.0      330941.0      436435.0
              other         1768241.0    479167.0      209277.0      269890.0
6-QUARTERLY   office         494961.0    156178.0       64461.0       91717.0
              other          667342.0    153224.0       61656.0       91568.0
7-RR-ACTIVE   office              3.0        21.0           9.0          12.0
              other              59.0      6861.0        1651.0        5210.0
8-RR-INACTIVE office              0.0         2.0           0.0           2.0
              other               5.0       347.0          99.0         248.0

                          gross_psm_gps  gross_psm_fav_recent_history  \
segment       office_tag
1-HH-Active   office            87848.0                        2492.0
              other            430731.0                       12682.0
2-HH-inActive office             3011.0                          72.0
              other             16196.0                         478.0
3-DAILY       office          1287425.0                      385936.0
              other            301620.0                      121909.0
4-WEEKLY      office          1294544.0                      262660.0
              other            504542.0                      122209.0
5-MONTHLY     office          1985322.0                      229150.0
              other           1871954.0                      216278.0
6-QUARTERLY   office           476751.0                       45627.0
              other            702616.0                       53468.0
7-RR-ACTIVE   office               31.0                           0.0
              other             25312.0                        1810.0
8-RR-INACTIVE office                2.0                           0.0
              other              1479.0                         117.0

                          gross_psm_google_search  gross_psm_stickylocation  \
segment       office_tag
1-HH-Active   office                       8780.0                   24285.0
              other                       43942.0                   86666.0
2-HH-inActive office                        243.0                     444.0
              other                        1588.0                    2280.0
3-DAILY       office                     272808.0                  676619.0
              other                       70395.0                   99663.0
4-WEEKLY      office                     236990.0                  650279.0
              other                       91913.0                  163734.0
5-MONTHLY     office                     258955.0                  852759.0
              other                      231562.0                  543815.0
6-QUARTERLY   office                      55935.0                  176713.0
              other                       71375.0                  188167.0
7-RR-ACTIVE   office                          7.0                      10.0
              other                        3662.0                    8343.0
8-RR-INACTIVE office                          2.0                       1.0
              other                         206.0                     267.0

                          gross_psm_hotspot  net_psm_gps  \
segment       office_tag
1-HH-Active   office                13150.0      56459.0
              other                 41214.0     260435.0
2-HH-inActive office                  456.0       2026.0
              other                  1478.0      10030.0
3-DAILY       office               254400.0     793478.0
              other                 40855.0     189520.0
4-WEEKLY      office               253625.0     783462.0
              other                 59604.0     309998.0
5-MONTHLY     office               339122.0    1238883.0
              other                196871.0    1168984.0
6-QUARTERLY   office                79601.0     311368.0
              other                 72358.0     472792.0
7-RR-ACTIVE   office                    6.0          3.0
              other                  3436.0         47.0
8-RR-INACTIVE office                    0.0          0.0
              other                   158.0          5.0

                          net_psm_fav_recent_history  net_psm_google_search  \
segment       office_tag
1-HH-Active   office                          1373.0                 5303.0
              other                           6250.0                24702.0
2-HH-inActive office                            38.0                  157.0
              other                            262.0                  829.0
3-DAILY       office                        245164.0               174570.0
              other                          80130.0                46561.0
4-WEEKLY      office                        162948.0               147728.0
              other                          78758.0                58538.0
5-MONTHLY     office                        144705.0               161371.0
              other                         137736.0               144027.0
6-QUARTERLY   office                         29177.0                36488.0
              other                          35526.0                48204.0
7-RR-ACTIVE   office                             0.0                    0.0
              other                              2.0                    5.0
8-RR-INACTIVE office                             0.0                    0.0
              other                              0.0                    0.0

                          net_psm_stickylocation  net_psm_hotspot  \
segment       office_tag
1-HH-Active   office                     15396.0           8704.0
              other                      53307.0          23819.0
2-HH-inActive office                       296.0            316.0
              other                       1443.0            890.0
3-DAILY       office                    419129.0         157782.0
              other                      63084.0          26128.0
4-WEEKLY      office                    394750.0         153851.0
              other                     101391.0          36519.0
5-MONTHLY     office                    531651.0         212147.0
              other                     341653.0         120689.0
6-QUARTERLY   office                    114664.0          52204.0
              other                     128380.0          48661.0
7-RR-ACTIVE   office                         0.0              0.0
              other                         10.0              4.0
8-RR-INACTIVE office                         0.0              0.0
              other                          1.0              0.0

                          office_gross  transit_gross  office_net  \
segment       office_tag
1-HH-Active   office           98562.0        16038.0     70277.0
              other            34734.0       107692.0         7.0
2-HH-inActive office           27587.0         4711.0     21510.0
              other             9100.0        40946.0        30.0
3-DAILY       office         1229689.0       252284.0    638463.0
              other             8455.0        50019.0         0.0
4-WEEKLY      office         1288713.0       313670.0    656451.0
              other            26835.0       104227.0         0.0
5-MONTHLY     office         1949281.0       520404.0   1108875.0
              other           150485.0       522604.0         5.0
6-QUARTERLY   office          430328.0        89583.0    275354.0
              other            39339.0       174708.0        20.0
7-RR-ACTIVE   office              41.0           16.0         6.0
              other            12698.0        10818.0         0.0
8-RR-INACTIVE office               0.0            2.0         0.0
              other              650.0          706.0         0.0

                          transit_net    rpc  a02fe  fe2rr  ao2rr    g2n  \
segment       office_tag
1-HH-Active   office           8015.0   1.61  78.44  49.62  38.92  63.82
              other           61338.0   1.41  75.84  48.71  36.94  59.86
2-HH-inActive office           2314.0   1.51  49.49   5.81   2.87  67.28
              other           23510.0   1.33  48.74   3.86   1.88  60.97
3-DAILY       office         141796.0  26.76  87.61  82.48  72.26  62.31

In [42]:
segment_office.reset_index().to_clipboard(index=False)

In [45]:
segment_office_travel_qc = agg_func(['segment','office_tag','travelridehailing','quick_commerce'])
segment_office_travel_qc

['segment', 'office_tag', 'travelridehailing', 'quick_commerce']

                                                           gross_customers  \
segment       office_tag travelridehailing quick_commerce
1-HH-Active   office     blank             blank                     10507
                         no                no                        14590
                                           yes                        8845
                         yes               no                         8694
                                           yes                       26595
...                                                                    ...
8-RR-INACTIVE other      blank             blank                        81
                         no                no                          182
                                           yes                         165
                         yes               no                          206
                                           yes                        1297

                                                           net_customers  \
segment       office_tag travelridehailing quick_commerce
1-HH-Active   office     blank             blank                    9794
                         no                no                      13910
                                           yes                      8379
                         yes               no                       8214
                                           yes                     24690
...                                                                  ...
8-RR-INACTIVE other      blank             blank                       0
                         no                no                          1
                                           yes                         1
                         yes               no                          0
                                           yes                         3

                                                           ao_session  \
segment       office_tag travelridehailing quick_commerce
1-HH-Active   office     blank             blank              30529.0
                         no                no                 57926.0
                                           yes                34288.0
                         yes               no                 34484.0
                                           yes                96281.0
...                                                               ...
8-RR-INACTIVE other      blank             blank              34160.0
                         no                no                 24727.0
                                           yes                23051.0
                         yes               no                 24852.0
                                           yes               104269.0

                                                           fe_session  \
segment       office_tag travelridehailing quick_commerce
1-HH-Active   office     blank             blank              24106.0
                         no                no                 44261.0
                                           yes                26372.0
                         yes               no                 27112.0
                                           yes                77007.0
...                                                               ...
8-RR-INACTIVE other      blank             blank              15298.0
                         no                no                 14372.0
                                           yes                13190.0
                         yes               no                 14864.0
                                           yes                66749.0

                                                           rr_session  \
segment       office_tag travelridehailing quick_commerce
1-HH-Active   office     blank             blank              14370.0
                         no                no                 20039.0
                                           yes                11964.0
                         yes               no                 12701.0
                                           yes                39591.0
...                                                               ...
8-RR-INACTIVE other      blank             blank                836.0
                         no                no                   363.0
                                           yes                  433.0
                         yes               no                   407.0
                                           yes                 2976.0

                                                           customer_rr_sessions  \
segment       office_tag travelridehailing quick_commerce
1-HH-Active   office     blank             blank                        23471.0
                         no                no                           28304.0
                                           yes                          16834.0
                         yes               no                           17268.0
                                           yes                          53845.0
...                                                                         ...
8-RR-INACTIVE other      blank             blank                         1290.0
                         no                no                             511.0
                                           yes                            571.0
                         yes               no                             519.0
                                           yes                           3735.0

                                                           rr_count  \
segment       office_tag travelridehailing quick_commerce
1-HH-Active   office     blank             blank            26962.0
                         no                no               33483.0
                                           yes              20012.0
                         yes               no               20149.0
                                           yes              63460.0
...                                                             ...
8-RR-INACTIVE other      blank             blank              110.0
                         no                no                 310.0
                                           yes                244.0
                         yes               no                 324.0
                                           yes               2044.0

                                                           net_count  \
segment       office_tag travelridehailing quick_commerce
1-HH-Active   office     blank             blank             16308.0
                         no                no                22318.0
                                           yes               13469.0
                         yes               no                13062.0
                                           yes               39555.0
...                                                              ...
8-RR-INACTIVE other      blank             blank                 0.0
                         no                no                    1.0
                                           yes                   1.0
                         yes               no                    0.0
                                           yes                   4.0

                                                           cobrm_count  \
segment       office_tag travelridehailing quick_commerce
1-HH-Active   office     blank             blank                 213.0
                         no                no                    377.0
                                           yes                   203.0
                         yes               no                    276.0
                                           yes                   683.0
...                                                                ...
8-RR-INACTIVE other      blank             blank                   2.0
                         no                no                      5.0
                                           yes                     6.0
                         yes               no                      7.0
                                           yes                    54.0

                                                           cobra_count  \
segment       office_tag travelridehailing quick_commerce
1-HH-Active   office     blank             blank                3744.0
                         no                no                   3192.0
                                           yes                  2170.0
                         yes               no                   2082.0
                                           yes                  9019.0
...                                                                ...
8-RR-INACTIVE other      blank             blank                  36.0
                         no                no                     93.0
                                           yes                    76.0
                         yes               no                    111.0
                                           yes                   785.0

                                                           ocara_count  \
segment       office_tag travelridehailing quick_commerce
1-HH-Active   office     blank             blank                4420.0
                         no                no                   5583.0
                                           yes                  3113.0
                         yes               no                   3417.0
                                           yes                  9724.0
...                                                                ...
8-RR-INACTIVE other      blank             blank                  55.0
                         no                no                    160.0
                                           yes                   125.0
                         yes               no                    163.0
                                           yes                   918.0

                                                           expired_count  \
segment       office_tag travelridehailing quick_commerce
1-HH-Active   office     blank             blank                  2249.0
                         no                no                     1954.0
                                           yes                    1027.0
                         yes               no                     1281.0
                                           yes                    4421.0
...                                                                  ...
8-RR-INACTIVE other      blank             blank                    17.0
                         no                no                       50.0
                                           yes                      35.0
                         yes               no                       43.0
                                           yes                     282.0

                                                           aborted_count  \
segment       office_tag travelridehailing quick_commerce
1-HH-Active   office     blank             blank                    28.0
                         no                no                       59.0
                                           yes                      30.0
                         yes               no                       31.0
                                           yes                      57.0
...                                                                  ...
8-RR-INACTIVE other      blank             blank                     0.0
                         no                no                        1.0
                                           yes                       1.0
                         yes               no                        0.0
                                           yes                       1.0

                                                           canceltn_count  \
segment       office_tag travelridehailing quick_commerce
1-HH-Active   office     blank             blank                   8377.0
                         no                no                      9152.0
                                           yes                     5486.0
                         yes               no                      5775.0
                                           yes                    19426.0
...                                                                   ...
8-RR-INACTIVE other      blank             blank                     93.0
                         no                no                       258.0
                                           yes                      207.0
                         yes               no                       281.0
                                           yes                     1757.0

                                                           quick_cobra  \
segment       office_tag travelridehailing quick_commerce
1-HH-Active   office     blank             blank                 427.0
                         no                no                    431.0
                                           yes                   253.0
                         yes               no                    225.0
                                           yes                  1108.0
...                                                                ...
8-RR-INACTIVE other      blank             blank                   5.0
                         no                no                     15.0
                                           yes                    14.0
                         yes               no                      8.0
                                           yes                   100.0

                                                           quick_ocara  \
segment       office_tag travelridehailing quick_commerce
1-HH-Active   office     blank             blank                 242.0
                         no                no                    432.0
                                           yes                   175.0
                         yes               no                    420.0
                                           yes                   682.0
...                                                                ...
8-RR-INACTIVE other      blank             blank                   6.0
                         no                no                     23.0
                                           yes                    18.0
                         yes               no                     22.0
                                           yes                   105.0

                                                           cobra_ttc_mean  \
segment       office_tag travelridehailing quick_commerce
1-HH-Active   office     blank             blank                   127.46
                         no                no                      115.00
                                           yes                     116.98
                         yes               no                      119.66
                                           yes                     123.12
...                                                                   ...
8-RR-INACTIVE other      blank             blank                   113.84
                         no                no                      105.06
                                           yes                     114.90
                         yes               no                      115.29
                                           yes                     121.13

                                                           cobra_ttc_p25  \
segment       office_tag travelridehailing quick_commerce
1-HH-Active   office     blank             blank                   63.00
                         no                no                      55.00
                                           yes                     60.00
                         yes               no                      63.08
                                           yes                     64.00
...                                                                  ...
8-RR-INACTIVE other      blank             blank                   55.00
                         no                no                      42.00
                                           yes                     38.75
                         yes               no                      70.00
                                           yes                     56.00

                                                           cobra_ttc_p50  \
segment       office_tag travelridehailing quick_commerce
1-HH-Active   office     blank             blank                  111.00
                         no                no                     100.00
                                           yes                    103.00
                         yes               no                     103.43
                                           yes                    108.50
...                                                                  ...
8-RR-INACTIVE other      blank             blank                  119.00
                         no                no                     100.00
                                           yes                     89.80
                         yes               no                     115.00
                                           yes                    103.00

                                                           cobra_ttc_p75  \
segment       office_tag travelridehailing quick_commerce
1-HH-Active   office     blank             blank                  173.00
                         no                no                     154.26
                                           yes                    157.00
                         yes               no                     160.00
                                           yes                    167.00
...                                                                  ...
8-RR-INACTIVE other      blank             blank                  156.00
                         no                no                     158.00
                                           yes                    185.25
                         yes               no                     155.00
                                           yes                    167.00

                                                           cobra_ttc_p90  \
segment       office_tag travelridehailing quick_commerce
1-HH-Active   office     blank             blank                  243.00
                         no                no                     218.00
                                           yes                    219.20
                         yes               no                     225.00
                                           yes                    229.00
...                                                                  ...
8-RR-INACTIVE other      blank             blank                  211.67
                         no                no                     217.20
                                           yes                    250.60
                         yes               no                     181.40
                                           yes                    249.80

                                                           cobra_ttc_p95  \
segment       office_tag travelridehailing quick_commerce
1-HH-Active   office     blank             blank                  285.25
                         no                no                     264.00
                                           yes                    261.00
                         yes               no                     261.00
                                           yes                    271.00

In [46]:
segment_office_travel_qc.reset_index().to_clipboard(index=False)