## Import

In [4]:
import re
import os 
import pandas as pd
import matplotlib.pyplot as plt 
import numpy as np
from pyhive import presto
from datetime import date
from collections import Counter

from scipy import stats
from pyhive import presto
from datetime import datetime, timedelta

presto_port = '80'
username = 'manoj.ravirajan@rapido.bike'

conn=presto.connect('presto-gateway.processing.data.production.internal',presto_port,username)

connection1 = presto.connect('bi-presto.serving.data.production.internal', presto_port, username)
connection2 = presto.connect('bi-trino-2.serving.data.production.internal', presto_port, username)
connection3= presto.connect('processing-2.processing.data.production.internal',presto_port,username)
connection4= presto.connect('processing.processing.data.production.internal',presto_port,username)


pd.set_option('display.max_columns', None)

## Overall

In [6]:
overall_query=f"""
with rr_net AS (
    SELECT 
        yyyymmdd, 
        customer_id,
        order_id, 
        order_status, 
        modified_order_status, 
        spd_fraud_flag,
        quarter_hour,
        CASE 
            WHEN modified_order_status IN ('OCARA', 'COBRA', 'COBRM') 
            THEN (customer_cancelled_epoch / 1000 - order_requested_epoch / 1000) 
        END AS time_spent_in_sec,
        CASE 
            WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') 
            THEN (rider_accepted_epoch / 1000 - order_requested_epoch / 1000)
        END AS time_taken_to_accp,
        case when SUBSTR(customer_id, -1) in ('1','3','5','7','9','e','a','d') then 'test' else 'control' end as test_group
    
    FROM 
        orders.order_logs_fact fact
    WHERE 
         yyyymmdd >= '20240911' AND yyyymmdd <= '20240916'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city_name = 'Delhi'
        AND service_obj_service_name in ('Auto','Auto Lite','Auto NCR','Auto Pool','AutoPremium','CityAuto','Link','Bike Lite','Bike Pink','CabEconomy','Bike Metro', 'CabPremium')
        AND channel_host='android'
        and customer_id in(
                select
                    user_id
        from 
            clevertap.clevertap_customer_order_activity
        where 
            yyyymmdd >= '20240911' AND yyyymmdd <= '20240916'
            AND order_activity_source = 'appOpen'
            and current_city = 'Delhi'
            and platform='Android'
            and app_version>='8.30.0'
            
            
            )
),





view_tbl as(
        select 
            profile_identity as user_id,
            yyyymmdd,
            'viewed' as event_type
        from
            clevertap.customer_notification_viewed_immutable 
        where yyyymmdd >= '20240911' AND yyyymmdd <= '20240916'
        and event_props_campaign_id = '1725970812' 

),

click_tbl as(
        select
            profile_identity as user_id,
            CASE
                when event_props_wzrk_c2a='Button 2' then 'play_click'
                else 'close_click'
            end as click_type,
            yyyymmdd
        from
            clevertap.customer_notification_clicked_immutable 
        where yyyymmdd >= '20240911' AND yyyymmdd <= '20240916' 
        and event_props_campaign_id = '1725970812' 
),

merge as(
        select rr_net.*,view_tbl.event_type,click_tbl.click_type
        from rr_net
        left join 
            view_tbl
                on rr_net.customer_id=view_tbl.user_id
                and rr_net.yyyymmdd=view_tbl.yyyymmdd
        left join 
            click_tbl
            on view_tbl.user_id=click_tbl.user_id
            and view_tbl.yyyymmdd=click_tbl.yyyymmdd
        )

SELECT
        test_group,
        -- event_type,
        -- click_type,
        customers,

        gross_count,
        net_count,
        
        COALESCE(TRY(net_count*100.00/gross_count), 0) g2n,
        
        COALESCE(TRY(tot_accepted*100.00/gross_count), 0) "aor",
        
        
        median_cobrm_time,
        median_cobra_time,
        median_ocara_time,
        median_cancellation_time,
        median_acceptance_time,
        
        COALESCE(TRY(cobrm*100.00/gross_count), 0) "% cobrm",
        COALESCE(TRY(cobra*100.00/gross_count), 0) "% cobra",
        COALESCE(TRY(ocara*100.00/gross_count), 0) "% ocara",
        COALESCE(TRY(expired*100.00/gross_count), 0) "% expired",
        cobrm, 
        cobra,
        ocara,
        expired
    FROM    
        (
        SELECT
            test_group,
            -- event_type,
            -- click_type,
            COUNT(DISTINCT customer_id) customers,
            COUNT(DISTINCT order_id) gross_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' AND spd_fraud_flag != true THEN order_id END) net_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN order_id END) AS tot_accepted,

        
           
            
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRM' THEN order_id END) cobrm,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRA' THEN order_id END) cobra,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'OCARA' THEN order_id END) ocara,
            COUNT(DISTINCT CASE WHEN order_status = 'expired' THEN order_id END) expired,
            
            approx_percentile(CASE WHEN modified_order_status = 'COBRM' THEN time_spent_in_sec END,0.50) as median_cobrm_time,
            approx_percentile(CASE WHEN modified_order_status = 'COBRA' THEN time_spent_in_sec END,0.50) as median_cobra_time,
            approx_percentile(CASE WHEN modified_order_status = 'OCARA' THEN time_spent_in_sec END,0.50) as median_ocara_time,
            approx_percentile(CASE WHEN modified_order_status in ('COBRA','COBRM','OCARA') THEN time_spent_in_sec END,0.50) as median_cancellation_time,
            approx_percentile(CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN time_taken_to_accp END,0.50) as median_acceptance_time
            
        FROM 
            merge
        where 
            yyyymmdd is not null
           and NOT (test_group = 'control' AND event_type IS NOT NULL)
           and NOT (event_type IS NULL AND click_type IS NOT NULL)
        GROUP BY 1
        )
    ORDER BY 1
    
    
"""
overall=pd.read_sql(overall_query,conn)

/var/folders/j7/5rtfb17j30s9g9q790v9nr0h0000gn/T/ipykernel_62370/2770846961.py:154: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  overall=pd.read_sql(overall_query,conn)

In [7]:
overall

,test_group,customers,gross_count,net_count,g2n,aor,median_cobrm_time,median_cobra_time,median_ocara_time,median_cancellation_time,median_acceptance_time,% cobrm,% cobra,% ocara,% expired,cobrm,cobra,ocara,expired
0,control,426083,1495502,726604,48.59,66.94,106,132,310,174,14,1.63,20.10,17.98,11.31,24367,300574,268872,169149
1,test,426987,1499498,726049,48.42,66.75,106,131,311,174,14,1.63,20.14,17.95,11.46,24489,302038,269165,171869

In [11]:
overall.to_clipboard(index=False)

## Level 1 breakdown

In [9]:
overall_query=f"""
with rr_net AS (
    SELECT 
        yyyymmdd, 
        customer_id,
        order_id, 
        order_status, 
        modified_order_status, 
        spd_fraud_flag,
        quarter_hour,
        CASE 
            WHEN modified_order_status IN ('OCARA', 'COBRA', 'COBRM') 
            THEN (customer_cancelled_epoch / 1000 - order_requested_epoch / 1000) 
        END AS time_spent_in_sec,
        CASE 
            WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') 
            THEN (rider_accepted_epoch / 1000 - order_requested_epoch / 1000)
        END AS time_taken_to_accp,
        case when SUBSTR(customer_id, -1) in ('1','3','5','7','9','e','a','d') then 'test' else 'control' end as test_group
    
    FROM 
        orders.order_logs_fact fact
    WHERE 
         yyyymmdd >= '20240911' AND yyyymmdd <= '20240916'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city_name = 'Delhi'
        AND service_obj_service_name in ('Auto','Auto Lite','Auto NCR','Auto Pool','AutoPremium','CityAuto','Link','Bike Lite','Bike Pink','CabEconomy','Bike Metro', 'CabPremium')
        AND channel_host='android'
        and customer_id in(
                select
                    user_id
        from 
            clevertap.clevertap_customer_order_activity
        where 
            yyyymmdd >= '20240911' AND yyyymmdd <= '20240916'
            AND order_activity_source = 'appOpen'
            and current_city = 'Delhi'
            and platform='Android'
            and app_version>='8.30.0'
            
            
            )
),





view_tbl as(
        select 
            profile_identity as user_id,
            yyyymmdd,
            'viewed' as event_type
        from
            clevertap.customer_notification_viewed_immutable 
        where yyyymmdd >= '20240911' AND yyyymmdd <= '20240916'
        and event_props_campaign_id = '1725970812' 

),

click_tbl as(
        select
            profile_identity as user_id,
            CASE
                when event_props_wzrk_c2a='Button 2' then 'play_click'
                else 'close_click'
            end as click_type,
            yyyymmdd
        from
            clevertap.customer_notification_clicked_immutable 
        where yyyymmdd >= '20240911' AND yyyymmdd <= '20240916' 
        and event_props_campaign_id = '1725970812' 
),

merge as(
        select rr_net.*,view_tbl.event_type,click_tbl.click_type
        from rr_net
        left join 
            view_tbl
                on rr_net.customer_id=view_tbl.user_id
                and rr_net.yyyymmdd=view_tbl.yyyymmdd
        left join 
            click_tbl
            on view_tbl.user_id=click_tbl.user_id
            and view_tbl.yyyymmdd=click_tbl.yyyymmdd
        )

SELECT
        test_group,
        event_type,
        click_type,
        customers,

        gross_count,
        net_count,
        
        COALESCE(TRY(net_count*100.00/gross_count), 0) g2n,
        
        COALESCE(TRY(tot_accepted*100.00/gross_count), 0) "aor",
        
        
        median_cobrm_time,
        median_cobra_time,
        median_ocara_time,
        median_cancellation_time,
        median_acceptance_time,
        
        COALESCE(TRY(cobrm*100.00/gross_count), 0) "% cobrm",
        COALESCE(TRY(cobra*100.00/gross_count), 0) "% cobra",
        COALESCE(TRY(ocara*100.00/gross_count), 0) "% ocara",
        COALESCE(TRY(expired*100.00/gross_count), 0) "% expired",
        cobrm, 
        cobra,
        ocara,
        expired
    FROM    
        (
        SELECT
            test_group,
            event_type,
            click_type,
            COUNT(DISTINCT customer_id) customers,
            COUNT(DISTINCT order_id) gross_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' AND spd_fraud_flag != true THEN order_id END) net_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN order_id END) AS tot_accepted,

        
           
            
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRM' THEN order_id END) cobrm,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRA' THEN order_id END) cobra,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'OCARA' THEN order_id END) ocara,
            COUNT(DISTINCT CASE WHEN order_status = 'expired' THEN order_id END) expired,
            
            approx_percentile(CASE WHEN modified_order_status = 'COBRM' THEN time_spent_in_sec END,0.50) as median_cobrm_time,
            approx_percentile(CASE WHEN modified_order_status = 'COBRA' THEN time_spent_in_sec END,0.50) as median_cobra_time,
            approx_percentile(CASE WHEN modified_order_status = 'OCARA' THEN time_spent_in_sec END,0.50) as median_ocara_time,
            approx_percentile(CASE WHEN modified_order_status in ('COBRA','COBRM','OCARA') THEN time_spent_in_sec END,0.50) as median_cancellation_time,
            approx_percentile(CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN time_taken_to_accp END,0.50) as median_acceptance_time
            
        FROM 
            merge
        where 
            yyyymmdd is not null
           and NOT (test_group = 'control' AND event_type IS NOT NULL)
           and NOT (event_type IS NULL AND click_type IS NOT NULL)
        GROUP BY 1,2,3
        )
    ORDER BY 1,2,3

    
    
    
    
"""
overall1=pd.read_sql(overall_query,conn)

/var/folders/j7/5rtfb17j30s9g9q790v9nr0h0000gn/T/ipykernel_62370/3292753032.py:157: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  overall1=pd.read_sql(overall_query,conn)

In [12]:
overall1

,test_group,event_type,click_type,customers,gross_count,net_count,g2n,aor,median_cobrm_time,median_cobra_time,median_ocara_time,median_cancellation_time,median_acceptance_time,% cobrm,% cobra,% ocara,% expired,cobrm,cobra,ocara,expired
0,control,None,None,426083,1495502,726604,48.59,66.94,106,132,310,174,14,1.63,20.10,17.98,11.31,24367,300574,268872,169149
1,test,viewed,close_click,315748,826810,400370,48.42,66.68,112,134,319,178,14,1.58,20.10,17.88,11.63,13062,166171,147818,96118
2,test,viewed,play_click,32360,68335,30131,44.09,63.98,104,130,319,172,15,1.94,20.71,19.46,13.34,1327,14152,13301,9118
3,test,viewed,None,10982,22090,11297,51.14,72.39,110,132,315,191,12,1.16,15.00,20.79,11.41,257,3314,4593,2520
4,test,None,None,200427,582671,284380,48.81,66.94,98,128,300,167,14,1.69,20.34,17.77,11.02,9851,118510,103539,64186

In [14]:
overall1.to_clipboard(index=False)

## Pre-Post

In [15]:
overall_query=f"""
with rr_net AS (
    SELECT 
        yyyymmdd, 
        customer_id,
        order_id, 
        order_status, 
        modified_order_status, 
        spd_fraud_flag,
        quarter_hour,
        CASE 
            WHEN modified_order_status IN ('OCARA', 'COBRA', 'COBRM') 
            THEN (customer_cancelled_epoch / 1000 - order_requested_epoch / 1000) 
        END AS time_spent_in_sec,
        CASE 
            WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') 
            THEN (rider_accepted_epoch / 1000 - order_requested_epoch / 1000)
        END AS time_taken_to_accp,
        case when SUBSTR(customer_id, -1) in ('1','3','5','7','9','e','a','d') then 'test' else 'control' end as test_group
    
    FROM 
        orders.order_logs_fact fact
    WHERE 
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240910'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city_name = 'Delhi'
        AND service_obj_service_name in ('Auto','Auto Lite','Auto NCR','Auto Pool','AutoPremium','CityAuto','Link','Bike Lite','Bike Pink','CabEconomy','Bike Metro', 'CabPremium')
        AND channel_host='android'
        and customer_id in(
                select
                    user_id
        from 
            clevertap.clevertap_customer_order_activity
        where 
            yyyymmdd >= '20240905' AND yyyymmdd <= '20240910'
            AND order_activity_source = 'appOpen'
            and current_city = 'Delhi'
            and platform='Android'
            and app_version>='8.30.0'
            
            
            )
),





view_tbl as(
        select 
            profile_identity as user_id,
            yyyymmdd,
            'viewed' as event_type
        from
            clevertap.customer_notification_viewed_immutable 
        where yyyymmdd >= '20240905' AND yyyymmdd <= '20240910'
        and event_props_campaign_id = '1725970812' 

),

click_tbl as(
        select
            profile_identity as user_id,
            CASE
                when event_props_wzrk_c2a='Button 2' then 'play_click'
                else 'close_click'
            end as click_type,
            yyyymmdd
        from
            clevertap.customer_notification_clicked_immutable 
        where yyyymmdd >= '20240905' AND yyyymmdd <= '20240910' 
        and event_props_campaign_id = '1725970812' 
),

merge as(
        select rr_net.*,view_tbl.event_type,click_tbl.click_type
        from rr_net
        left join 
            view_tbl
                on rr_net.customer_id=view_tbl.user_id
                and rr_net.yyyymmdd=view_tbl.yyyymmdd
        left join 
            click_tbl
            on view_tbl.user_id=click_tbl.user_id
            and view_tbl.yyyymmdd=click_tbl.yyyymmdd
        )

SELECT
        test_group,
        -- event_type,
        -- click_type,
        customers,

        gross_count,
        net_count,
        
        COALESCE(TRY(net_count*100.00/gross_count), 0) g2n,
        
        COALESCE(TRY(tot_accepted*100.00/gross_count), 0) "aor",
        
        
        median_cobrm_time,
        median_cobra_time,
        median_ocara_time,
        median_cancellation_time,
        median_acceptance_time,
        
        COALESCE(TRY(cobrm*100.00/gross_count), 0) "% cobrm",
        COALESCE(TRY(cobra*100.00/gross_count), 0) "% cobra",
        COALESCE(TRY(ocara*100.00/gross_count), 0) "% ocara",
        COALESCE(TRY(expired*100.00/gross_count), 0) "% expired",
        cobrm, 
        cobra,
        ocara,
        expired
    FROM    
        (
        SELECT
            test_group,
            -- event_type,
            -- click_type,
            COUNT(DISTINCT customer_id) customers,
            COUNT(DISTINCT order_id) gross_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' AND spd_fraud_flag != true THEN order_id END) net_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN order_id END) AS tot_accepted,

        
           
            
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRM' THEN order_id END) cobrm,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRA' THEN order_id END) cobra,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'OCARA' THEN order_id END) ocara,
            COUNT(DISTINCT CASE WHEN order_status = 'expired' THEN order_id END) expired,
            
            approx_percentile(CASE WHEN modified_order_status = 'COBRM' THEN time_spent_in_sec END,0.50) as median_cobrm_time,
            approx_percentile(CASE WHEN modified_order_status = 'COBRA' THEN time_spent_in_sec END,0.50) as median_cobra_time,
            approx_percentile(CASE WHEN modified_order_status = 'OCARA' THEN time_spent_in_sec END,0.50) as median_ocara_time,
            approx_percentile(CASE WHEN modified_order_status in ('COBRA','COBRM','OCARA') THEN time_spent_in_sec END,0.50) as median_cancellation_time,
            approx_percentile(CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN time_taken_to_accp END,0.50) as median_acceptance_time
            
        FROM 
            merge
        where 
            yyyymmdd is not null
           and NOT (test_group = 'control' AND event_type IS NOT NULL)
           and NOT (event_type IS NULL AND click_type IS NOT NULL)
        GROUP BY 1
        )
    ORDER BY 1
    
    
"""
pre_overall=pd.read_sql(overall_query,conn)

/var/folders/j7/5rtfb17j30s9g9q790v9nr0h0000gn/T/ipykernel_62370/2275741643.py:154: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pre_overall=pd.read_sql(overall_query,conn)

In [16]:
pre_overall

,test_group,customers,gross_count,net_count,g2n,aor,median_cobrm_time,median_cobra_time,median_ocara_time,median_cancellation_time,median_acceptance_time,% cobrm,% cobra,% ocara,% expired,cobrm,cobra,ocara,expired
0,control,378291,1291512,695940,53.89,73.18,104,128,299,177,13,1.16,16.99,18.89,8.66,14974,219455,243923,111799
1,test,377944,1289573,695496,53.93,73.13,104,128,302,178,14,1.10,17.01,18.81,8.74,14159,219396,242615,112735

In [17]:
pre_overall.to_clipboard(index=False)

## Cobra distr

In [27]:
overall_query=f"""
with rr_net AS (
    SELECT 
        yyyymmdd, 
        customer_id,
        order_id, 
        order_status, 
        modified_order_status, 
        spd_fraud_flag,
        quarter_hour,
        CASE 
            WHEN modified_order_status IN ('OCARA', 'COBRA', 'COBRM') 
            THEN (customer_cancelled_epoch / 1000 - order_requested_epoch / 1000) 
        END AS time_spent_in_sec,
        CASE 
            WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') 
            THEN (rider_accepted_epoch / 1000 - order_requested_epoch / 1000)
        END AS time_taken_to_accp,
        case when SUBSTR(customer_id, -1) in ('1','3','5','7','9','e','a','d') then 'test' else 'control' end as test_group
    
    FROM 
        orders.order_logs_fact fact
    WHERE 
         yyyymmdd >= '20240911' AND yyyymmdd <= '20240916'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city_name = 'Delhi'
        AND service_obj_service_name in ('Auto','Auto Lite','Auto NCR','Auto Pool','AutoPremium','CityAuto','Link','Bike Lite','Bike Pink','CabEconomy','Bike Metro', 'CabPremium')
        AND channel_host='android'
        and customer_id in(
                select
                    user_id
        from 
            clevertap.clevertap_customer_order_activity
        where 
            yyyymmdd >= '20240911' AND yyyymmdd <= '20240916'
            AND order_activity_source = 'appOpen'
            and current_city = 'Delhi'
            and platform='Android'
            and app_version>='8.30.0'
            
            
            )
),





view_tbl as(
        select 
            profile_identity as user_id,
            yyyymmdd,
            'viewed' as event_type
        from
            clevertap.customer_notification_viewed_immutable 
        where yyyymmdd >= '20240911' AND yyyymmdd <= '20240916'
        and event_props_campaign_id = '1725970812' 

),

click_tbl as(
        select
            profile_identity as user_id,
            CASE
                when event_props_wzrk_c2a='Button 2' then 'play_click'
                else 'close_click'
            end as click_type,
            yyyymmdd
        from
            clevertap.customer_notification_clicked_immutable 
        where yyyymmdd >= '20240911' AND yyyymmdd <= '20240916' 
        and event_props_campaign_id = '1725970812' 
),

merge as(
        select rr_net.*,view_tbl.event_type,click_tbl.click_type
        from rr_net
        left join 
            view_tbl
                on rr_net.customer_id=view_tbl.user_id
                and rr_net.yyyymmdd=view_tbl.yyyymmdd
        left join 
            click_tbl
            on view_tbl.user_id=click_tbl.user_id
            and view_tbl.yyyymmdd=click_tbl.yyyymmdd
        )

SELECT
        test_group,
        -- event_type,
        -- click_type,
        cobra_ttc_bucket,
        customers,

        gross_count,
        net_count,
        
        COALESCE(TRY(net_count*100.00/gross_count), 0) g2n,
        
        COALESCE(TRY(tot_accepted*100.00/gross_count), 0) "aor",
        
        
        median_cobrm_time,
        median_cobra_time,
        median_ocara_time,
        median_cancellation_time,
        median_acceptance_time,
        
        COALESCE(TRY(cobrm*100.00/gross_count), 0) "% cobrm",
        COALESCE(TRY(cobra*100.00/gross_count), 0) "% cobra",
        COALESCE(TRY(ocara*100.00/gross_count), 0) "% ocara",
        COALESCE(TRY(expired*100.00/gross_count), 0) "% expired",
        cobrm, 
        cobra,
        ocara,
        expired
    FROM    
        (
        SELECT
            test_group,
            -- event_type,
            -- click_type,


            CASE 
            WHEN modified_order_status = 'COBRA' AND time_spent_in_sec <= 15 THEN 'a. 0-15 sec' 
            WHEN modified_order_status = 'COBRA' AND time_spent_in_sec BETWEEN 16 AND 30 THEN 'b. 16-30 sec' 
            WHEN modified_order_status = 'COBRA' AND time_spent_in_sec BETWEEN 31 AND 60 THEN 'c. 31-60 sec' 
            WHEN modified_order_status = 'COBRA' AND time_spent_in_sec BETWEEN 61 AND 180 THEN 'd. 61-180 sec' 
            WHEN modified_order_status = 'COBRA' AND time_spent_in_sec > 180 THEN 'e. 180+ sec' 
            WHEN modified_order_status != 'COBRA' THEN 'f. NO COBRA'
            ELSE 'Check' END cobra_ttc_bucket,
            
            COUNT(DISTINCT customer_id) customers,
            COUNT(DISTINCT order_id) gross_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' AND spd_fraud_flag != true THEN order_id END) net_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN order_id END) AS tot_accepted,

        
           
            
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRM' THEN order_id END) cobrm,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRA' THEN order_id END) cobra,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'OCARA' THEN order_id END) ocara,
            COUNT(DISTINCT CASE WHEN order_status = 'expired' THEN order_id END) expired,
            
            approx_percentile(CASE WHEN modified_order_status = 'COBRM' THEN time_spent_in_sec END,0.50) as median_cobrm_time,
            approx_percentile(CASE WHEN modified_order_status = 'COBRA' THEN time_spent_in_sec END,0.50) as median_cobra_time,
            approx_percentile(CASE WHEN modified_order_status = 'OCARA' THEN time_spent_in_sec END,0.50) as median_ocara_time,
            approx_percentile(CASE WHEN modified_order_status in ('COBRA','COBRM','OCARA') THEN time_spent_in_sec END,0.50) as median_cancellation_time,
            approx_percentile(CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN time_taken_to_accp END,0.50) as median_acceptance_time
            
        FROM 
            merge
        where 
            yyyymmdd is not null
           and NOT (test_group = 'control' AND event_type IS NOT NULL)
           and NOT (event_type IS NULL AND click_type IS NOT NULL)

           and click_type = 'play_click'

           
        GROUP BY 1,2
        )
    ORDER BY 1,2
    
    
"""
overall_ttc_breakup=pd.read_sql(overall_query,conn)

/var/folders/j7/5rtfb17j30s9g9q790v9nr0h0000gn/T/ipykernel_62370/543812215.py:170: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  overall_ttc_breakup=pd.read_sql(overall_query,conn)

In [28]:
overall_ttc_breakup

,test_group,cobra_ttc_bucket,customers,gross_count,net_count,g2n,aor,median_cobrm_time,median_cobra_time,median_ocara_time,median_cancellation_time,median_acceptance_time,% cobrm,% cobra,% ocara,% expired,cobrm,cobra,ocara,expired
0,test,a. 0-15 sec,650,701,0,0.00,0.00,NaN,11.0,NaN,11,NaN,0.00,100.0,0.00,0.00,0,701,0,0
1,test,b. 16-30 sec,774,823,0,0.00,0.00,NaN,22.0,NaN,22,NaN,0.00,100.0,0.00,0.00,0,823,0,0
2,test,c. 31-60 sec,1299,1527,0,0.00,0.00,NaN,46.0,NaN,46,NaN,0.00,100.0,0.00,0.00,0,1527,0,0
3,test,d. 61-180 sec,4432,6538,0,0.00,0.00,NaN,116.0,NaN,116,NaN,0.00,100.0,0.00,0.00,0,6538,0,0
4,test,e. 180+ sec,3577,4563,0,0.00,0.00,NaN,251.0,NaN,251,NaN,0.00,100.0,0.00,0.00,0,4563,0,0
5,test,f. NO COBRA,30317,54183,30131,55.61,80.69,104.0,NaN,318.0,281,15.0,2.45,0.0,24.55,16.83,1327,0,13301,9118

In [29]:
overall_ttc_breakup.gross_count.sum()

68335

In [30]:
68335-54183

14152

In [31]:
overall_ttc_breakup.to_clipboard(index=False)

## Other

In [145]:
overall_daywise_query=f"""
with rr_net AS (
    SELECT 
        yyyymmdd, 
        customer_id,
        order_id, 
        order_status, 
        modified_order_status, 
        spd_fraud_flag,
        quarter_hour,
        CASE 
            WHEN modified_order_status IN ('OCARA', 'COBRA', 'COBRM') 
            THEN (customer_cancelled_epoch / 1000 - order_requested_epoch / 1000) 
        END AS time_spent_in_sec,
        CASE 
            WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') 
            THEN (rider_accepted_epoch / 1000 - order_requested_epoch / 1000)
        END AS time_taken_to_accp,
        case when SUBSTR(customer_id, -1) in ('1','3','5','7','9','e','a','d') then 'test' else 'control' end as test_group
    
    FROM 
        orders.order_logs_fact fact
    WHERE 
         yyyymmdd >= '20240911' AND yyyymmdd <= '20240916'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city_name = 'Delhi'
        AND service_obj_service_name in ('Auto','Auto Lite','Auto NCR','Auto Pool','AutoPremium','CityAuto','Link','Bike Lite','Bike Pink','CabEconomy','Bike Metro', 'CabPremium')
        AND channel_host='android'
        and customer_id in(
                select
                    user_id
        from 
            clevertap.clevertap_customer_order_activity
        where 
            yyyymmdd >= '20240911' AND yyyymmdd <= '20240916'
            AND order_activity_source = 'appOpen'
            and current_city = 'Delhi'
            and platform='Android'
            and app_version>='8.30.0'
            
            
            )
),





view_tbl as(
        select 
            profile_identity as user_id,
            yyyymmdd,
            'viewed' as event_type
        from
            clevertap.customer_notification_viewed_immutable 
        where yyyymmdd >= '20240911' AND yyyymmdd <= '20240916'
        and event_props_campaign_id = '1725970812' 

),

click_tbl as(
        select
            profile_identity as user_id,
            CASE
                when event_props_wzrk_c2a='Button 2' then 'play_click'
                else 'close_click'
            end as click_type,
            yyyymmdd
        from
            clevertap.customer_notification_clicked_immutable 
        where yyyymmdd >= '20240911' AND yyyymmdd <= '20240916' 
        and event_props_campaign_id = '1725970812' 
),

merge as(
        select rr_net.*,view_tbl.event_type,click_tbl.click_type
        from rr_net
        left join 
            view_tbl
                on rr_net.customer_id=view_tbl.user_id
                and rr_net.yyyymmdd=view_tbl.yyyymmdd
        left join 
            click_tbl
            on view_tbl.user_id=click_tbl.user_id
            and view_tbl.yyyymmdd=click_tbl.yyyymmdd
        )

SELECT
        yyyymmdd,
        test_group,
        event_type,
        click_type,
        customers,

        gross_count,
        net_count,
        
        COALESCE(TRY(net_count*100.00/gross_count), 0) g2n,
        
        COALESCE(TRY(tot_accepted*100.00/gross_count), 0) "aor",
        
        
        median_cobrm_time,
        median_cobra_time,
        median_ocara_time,
        median_cancellation_time,
        median_acceptance_time,
        
        COALESCE(TRY(cobrm*100.00/gross_count), 0) "% cobrm",
        COALESCE(TRY(cobra*100.00/gross_count), 0) "% cobra",
        COALESCE(TRY(ocara*100.00/gross_count), 0) "% ocara",
        COALESCE(TRY(expired*100.00/gross_count), 0) "% expired",
        cobrm, 
        cobra,
        ocara,
        expired
    FROM    
        (
        SELECT
            yyyymmdd,
            test_group,
            event_type,
            click_type,
            COUNT(DISTINCT customer_id) customers,
            COUNT(DISTINCT order_id) gross_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' AND spd_fraud_flag != true THEN order_id END) net_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN order_id END) AS tot_accepted,

        
           
            
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRM' THEN order_id END) cobrm,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRA' THEN order_id END) cobra,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'OCARA' THEN order_id END) ocara,
            COUNT(DISTINCT CASE WHEN order_status = 'expired' THEN order_id END) expired,
            
            approx_percentile(CASE WHEN modified_order_status = 'COBRM' THEN time_spent_in_sec END,0.50) as median_cobrm_time,
            approx_percentile(CASE WHEN modified_order_status = 'COBRA' THEN time_spent_in_sec END,0.50) as median_cobra_time,
            approx_percentile(CASE WHEN modified_order_status = 'OCARA' THEN time_spent_in_sec END,0.50) as median_ocara_time,
            approx_percentile(CASE WHEN modified_order_status in ('COBRA','COBRM','OCARA') THEN time_spent_in_sec END,0.50) as median_cancellation_time,
            approx_percentile(CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN time_taken_to_accp END,0.50) as median_acceptance_time
            
        FROM 
            merge
        where 
            yyyymmdd is not null
           and NOT (test_group = 'control' AND event_type IS NOT NULL)
           and NOT (event_type IS NULL AND click_type IS NOT NULL)
        GROUP BY 1,2,3,4
        )
    ORDER BY 1,2,3,4

    
    
    
    
"""
overall_daywise_df=pd.read_sql(overall_daywise_query,conn)

/var/folders/km/1ltm54y105x6dzlcf44g881c0000gn/T/ipykernel_31458/3833155388.py:159: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  overall_daywise_df=pd.read_sql(overall_daywise_query,conn)

In [146]:
overall_daywise_df

,yyyymmdd,test_group,event_type,click_type,customers,gross_count,net_count,g2n,aor,median_cobrm_time,median_cobra_time,median_ocara_time,median_cancellation_time,median_acceptance_time,% cobrm,% cobra,% ocara,% expired,cobrm,cobra,ocara,expired
0,20240911,control,None,None,132673,248221,135276,54.50,73.96,100,124,297,174,14,1.18,16.82,19.04,8.02,2934,41763,47257,19906
1,20240911,test,viewed,close_click,76793,140182,76298,54.43,73.71,115,127,308,177,13,1.20,17.10,18.90,7.98,1686,23968,26499,11181
2,20240911,test,viewed,play_click,6688,12582,6363,50.57,71.67,98,116,289,166,15,1.24,17.95,20.73,9.14,156,2258,2608,1150
3,20240911,test,viewed,None,2323,4137,2446,59.12,79.79,116,128,297,192,12,0.70,11.48,20.23,7.98,29,475,837,330
4,20240911,test,None,None,46714,91191,49892,54.71,74.19,92,121,290,170,15,1.28,16.85,19.06,7.66,1165,15368,17378,6989
5,20240912,control,None,None,131658,263152,122118,46.41,65.24,103,127,313,169,17,1.60,22.36,18.46,10.78,4202,58828,48589,28369
6,20240912,test,viewed,close_click,66587,132937,60498,45.51,64.54,109,129,322,173,17,1.57,22.53,18.64,11.35,2082,29950,24774,15083
7,20240912,test,viewed,play_click,5880,12103,5069,41.88,62.51,104,126,315,167,18,1.85,22.75,20.17,12.85,224,2753,2441,1555
8,20240912,test,viewed,None,1872,3681,1721,46.75,68.57,119,131,323,188,15,1.28,18.28,21.49,11.84,47,673,791,436
9,20240912,test,None,None,57945,117056,55593,47.49,65.79,98,125,294,163,17,1.54,22.55,17.94,10.11,1807,26391,21001,11833
10,20240913,control,None,None,155042,378008,111480,29.49,44.30,108,141,345,169,23,2.20,31.88,14.54,21.61,8313,120504,54967,81688
11,20240913,test,viewed,close_click,87946,209827,60969,29.06,43.73,110,142,353,171,23,2.18,31.68,14.41,22.40,4574,66467,30241,46991
12,20240913,test,viewed,play_click,7435,17952,4744,26.43,41.68,101,142,360,171,23,2.85,30.73,14.95,24.70,512,5517,2684,4434
13,20240913,test,viewed,None,2255,5107,1686,33.01,51.07,107,142,359,187,17,1.39,24.55,17.68,22.97,71,1254,903,1173
14,20240913,test,None,None,58083,147477,44199,29.97,44.53,106,137,338,164,24,2.06,32.06,14.28,21.34,3045,47280,21066,31468
15,20240914,control,None,None,118930,214882,123076,57.28,77.42,109,126,301,183,12,1.56,13.95,19.70,7.04,3350,29977,42340,15136
16,20240914,test,viewed,close_click,64584,115918,66494,57.36,77.16,119,129,315,187,12,1.53,14.04,19.36,7.25,1773,16274,22440,8401
17,20240914,test,viewed,play_click,5007,9126,4843,53.07,74.88,101,120,306,180,13,1.81,14.94,21.31,8.33,165,1363,1945,760
18,20240914,test,viewed,None,1707,3007,1776,59.06,81.94,147,126,314,203,11,0.86,10.18,22.02,6.98,26,306,662,210
19,20240914,test,None,None,47201,86648,49430,57.05,76.93,93,122,285,171,12,1.88,14.38,19.54,6.79,1627,12457,16935,5885
20,20240915,control,None,None,99911,180491,103536,57.36,77.60,106,125,294,179,11,1.69,13.61,19.82,7.09,3044,24561,35768,12792
21,20240915,test,viewed,close_click,56453,100564,56890,56.57,76.84,112,129,304,183,11,1.51,14.11,19.82,7.53,1515,14186,19929,7572
22,20240915,test,viewed,play_click,4288,7876,4120,52.31,75.06,112,127,322,180,12,1.92,14.72,22.27,8.30,151,1159,1754,654
23,20240915,test,viewed,None,1431,2562,1421,55.46,80.25,126,116,302,193,10,1.52,11.05,24.32,7.10,39,283,623,182
24,20240915,test,None,None,37888,69542,40873,58.77,78.91,95,122,285,174,11,1.90,12.76,19.72,6.41,1323,8877,13713,4460
25,20240916,control,None,None,120915,210466,130982,62.23,81.61,105,124,293,185,11,1.20,11.82,18.96,5.34,2517,24871,39902,11236
26,20240916,test,viewed,close_click,73314,127287,79168,62.20,81.40,107,127,295,186,11,1.12,12.03,18.78,5.41,1430,15318,23906,6887
27,20240916,test,viewed,play_click,4912,8690,4989,57.41,79.41,130,119,311,185,11,1.36,12.68,21.51,6.49,118,1102,1869,564
28,20240916,test,viewed,None,2031,3588,2244,62.54,84.42,91,117,273,185,10,1.25,9.03,21.52,5.24,45,324,772,188
29,20240916,test,None,None,40480,70477,44287,62.84,82.30,92,120,281,178,11,1.24,11.41,19.01,5.00,877,8043,13397,3524

In [150]:
overall_daywise_df.to_clipboard(index=False)

In [132]:
overall_daywise_df.to_csv('overall_daywise_df.csv',index=False)

In [151]:
session_query=f"""
with rr_net AS (
    SELECT 
        yyyymmdd, 
        customer_id,
        order_id, 
        order_status, 
        modified_order_status, 
        spd_fraud_flag,
        quarter_hour,
        CASE 
            WHEN modified_order_status IN ('OCARA', 'COBRA', 'COBRM') 
            THEN (customer_cancelled_epoch / 1000 - order_requested_epoch / 1000) 
        END AS time_spent_in_sec,
        CASE 
            WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') 
            THEN (rider_accepted_epoch / 1000 - order_requested_epoch / 1000)
        END AS time_taken_to_accp,
        case when SUBSTR(customer_id, -1) in ('1','3','5','7','9','e','a','d') then 'test' else 'control' end as test_group
    
    FROM 
        orders.order_logs_fact fact
    WHERE 
         yyyymmdd >= '20240911' AND yyyymmdd <= '20240916'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city_name = 'Delhi'
        AND service_obj_service_name in ('Auto','Auto Lite','Auto NCR','Auto Pool','AutoPremium','CityAuto','Link','Bike Lite','Bike Pink','CabEconomy','Bike Metro', 'CabPremium')
        AND channel_host='android'
        and customer_id in(
                select
                    user_id
        from 
            clevertap.clevertap_customer_order_activity
        where 
            yyyymmdd >= '20240911' AND yyyymmdd <= '20240916'
            AND order_activity_source = 'appOpen'
            and current_city = 'Delhi'
            and platform='Android'
            and app_version>='8.30.0'
            
            
            )
),





view_tbl as(
        select 
            profile_identity as user_id,
            yyyymmdd,
            'viewed' as event_type
        from
            clevertap.customer_notification_viewed_immutable 
        where yyyymmdd >= '20240911' AND yyyymmdd <= '20240916'
        and event_props_campaign_id = '1725970812' 

),

click_tbl as(
        select
            profile_identity as user_id,
            CASE
                when event_props_wzrk_c2a='Button 2' then 'play_click'
                else 'close_click'
            end as click_type,
            yyyymmdd
        from
            clevertap.customer_notification_clicked_immutable 
        where yyyymmdd >= '20240911' AND yyyymmdd <= '20240916' 
        and event_props_campaign_id = '1725970812' 
),

merge as(
        select rr_net.*,view_tbl.event_type,click_tbl.click_type
        from rr_net
        left join 
            view_tbl
                on rr_net.customer_id=view_tbl.user_id
                and rr_net.yyyymmdd=view_tbl.yyyymmdd
        left join 
            click_tbl
            on view_tbl.user_id=click_tbl.user_id
            and view_tbl.yyyymmdd=click_tbl.yyyymmdd
        )

SELECT
        test_group,
        event_type,
        click_type,
        time_period,
        customers,

        gross_count,
        net_count,
        
        COALESCE(TRY(net_count*100.00/gross_count), 0) g2n,
        
        COALESCE(TRY(tot_accepted*100.00/gross_count), 0) "aor",
        
        
        median_cobrm_time,
        median_cobra_time,
        median_ocara_time,
        median_cancellation_time,
        median_acceptance_time,
        
        COALESCE(TRY(cobrm*100.00/gross_count), 0) "% cobrm",
        COALESCE(TRY(cobra*100.00/gross_count), 0) "% cobra",
        COALESCE(TRY(ocara*100.00/gross_count), 0) "% ocara",
        COALESCE(TRY(expired*100.00/gross_count), 0) "% expired",
        cobrm, 
        cobra,
        ocara,
        expired
    FROM    
        (
        SELECT
            test_group,
            event_type,
            click_type,
            case
                WHEN quarter_hour >= '0800' AND quarter_hour < '1100' THEN 'morning'
                WHEN quarter_hour >= '1100' AND quarter_hour < '1700' THEN 'afternoon'
                WHEN quarter_hour >= '1700' AND quarter_hour < '2100' THEN 'evening'
                WHEN quarter_hour >= '0000' AND quarter_hour < '0800' THEN 'rest_morning'
                ELSE 'rest_evening'
            end as time_period,
            COUNT(DISTINCT customer_id) customers,
            COUNT(DISTINCT order_id) gross_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' AND spd_fraud_flag != true THEN order_id END) net_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN order_id END) AS tot_accepted,

        
           
            
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRM' THEN order_id END) cobrm,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRA' THEN order_id END) cobra,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'OCARA' THEN order_id END) ocara,
            COUNT(DISTINCT CASE WHEN order_status = 'expired' THEN order_id END) expired,
            
            approx_percentile(CASE WHEN modified_order_status = 'COBRM' THEN time_spent_in_sec END,0.50) as median_cobrm_time,
            approx_percentile(CASE WHEN modified_order_status = 'COBRA' THEN time_spent_in_sec END,0.50) as median_cobra_time,
            approx_percentile(CASE WHEN modified_order_status = 'OCARA' THEN time_spent_in_sec END,0.50) as median_ocara_time,
            approx_percentile(CASE WHEN modified_order_status in ('COBRA','COBRM','OCARA') THEN time_spent_in_sec END,0.50) as median_cancellation_time,
            approx_percentile(CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN time_taken_to_accp END,0.50) as median_acceptance_time
            
        FROM 
            merge
        where 
            yyyymmdd is not null
           and NOT (test_group = 'control' AND event_type IS NOT NULL)
           and NOT (event_type IS NULL AND click_type IS NOT NULL)
        GROUP BY 1,2,3,4
        )
    ORDER BY 1,2,3,4

    
    
    
    
"""
session_df=pd.read_sql(session_query,conn)

/var/folders/km/1ltm54y105x6dzlcf44g881c0000gn/T/ipykernel_31458/3233821542.py:165: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  session_df=pd.read_sql(session_query,conn)

In [152]:
session_df

,test_group,event_type,click_type,time_period,customers,gross_count,net_count,g2n,aor,median_cobrm_time,median_cobra_time,median_ocara_time,median_cancellation_time,median_acceptance_time,% cobrm,% cobra,% ocara,% expired,cobrm,cobra,ocara,expired
0,control,None,None,afternoon,205733,438073,250827,57.26,76.61,105,127,309,183,11,1.25,14.22,18.96,7.91,5494,62300,83060,34667
1,control,None,None,evening,193280,478646,187429,39.16,56.51,103,132,322,169,16,1.53,25.31,17.01,16.63,7301,121148,81417,79600
2,control,None,None,morning,133869,299946,158523,52.85,69.56,107,132,286,168,15,1.10,20.12,16.42,9.22,3295,60354,49255,27641
3,control,None,None,rest_evening,74195,137305,64916,47.28,69.02,97,128,323,180,16,1.84,19.88,21.10,9.13,2528,27293,28978,12531
4,control,None,None,rest_morning,69515,141250,64773,45.86,64.72,113,139,308,173,12,4.07,20.82,18.49,10.40,5742,29409,26113,14688
5,test,viewed,close_click,afternoon,139382,252121,143576,56.95,76.14,115,130,318,187,11,1.15,14.48,18.80,8.23,2906,36504,47396,20737
6,test,viewed,close_click,evening,130781,266185,103082,38.73,56.05,109,134,328,172,15,1.54,25.31,16.98,17.08,4104,67368,45211,45453
7,test,viewed,close_click,morning,89817,158865,83933,52.83,69.48,113,134,292,170,15,1.06,20.08,16.35,9.38,1677,31903,25980,14909
8,test,viewed,close_click,rest_evening,45878,74289,34999,47.11,68.55,97,130,331,183,16,1.90,19.85,20.80,9.57,1408,14745,15452,7106
9,test,viewed,close_click,rest_morning,42764,75255,34727,46.15,64.76,118,141,326,178,12,3.94,20.79,18.27,10.51,2965,15643,13750,7910
10,test,viewed,play_click,afternoon,12758,20845,10970,52.63,74.00,101,125,320,184,12,1.50,15.06,20.97,9.44,312,3139,4371,1968
11,test,viewed,play_click,evening,12422,22728,8155,35.88,54.12,103,133,322,168,17,1.84,25.20,17.87,18.80,418,5728,4061,4273
12,test,viewed,play_click,morning,7596,11849,5578,47.08,65.20,116,127,287,160,16,1.31,22.53,17.83,10.97,155,2669,2113,1300
13,test,viewed,play_click,rest_evening,4467,6765,3017,44.60,67.46,82,124,343,187,19,2.28,18.99,22.14,11.12,154,1285,1498,752
14,test,viewed,play_click,rest_morning,3530,6142,2408,39.21,60.24,117,136,320,174,14,4.67,21.67,20.48,13.42,287,1331,1258,824
15,test,viewed,None,afternoon,4437,6774,3998,59.02,80.94,124,127,300,201,10,0.71,10.33,21.39,8.02,48,700,1449,543
16,test,viewed,None,evening,4206,7147,2984,41.75,62.32,96,131,332,183,14,1.20,19.55,20.12,16.87,86,1397,1438,1206
17,test,viewed,None,morning,3170,4396,2530,57.55,76.68,147,137,280,185,12,0.64,14.01,18.88,8.67,28,616,830,381
18,test,viewed,None,rest_evening,1378,2016,925,45.88,70.39,111,122,337,197,14,2.18,16.87,23.66,10.32,44,340,477,208
19,test,viewed,None,rest_morning,1182,1749,857,49.00,71.76,98,139,358,190,10,2.92,14.98,22.53,10.35,51,262,394,181
20,test,None,None,afternoon,85386,160163,92576,57.80,77.23,94,121,294,174,11,1.31,14.10,19.04,7.35,2098,22589,30497,11773
21,test,None,None,evening,82940,184813,72665,39.32,56.37,96,130,312,166,17,1.52,25.59,16.76,16.49,2804,47294,30974,30482
22,test,None,None,morning,66077,125961,67004,53.19,69.59,107,131,276,163,16,1.02,20.38,16.10,9.01,1284,25665,20275,11347
23,test,None,None,rest_evening,30578,53143,25392,47.78,68.80,90,124,315,172,16,2.16,20.09,20.41,8.86,1147,10675,10849,4707
24,test,None,None,rest_morning,31428,58311,26637,45.68,64.75,102,133,302,165,13,4.31,20.91,18.68,10.03,2511,12193,10895,5850

In [153]:
session_df.to_clipboard(index=False)

In [135]:
session_df.to_csv('session_df.csv',index=False)

In [136]:
ltr_segment_games_query=f"""
with rr_net AS (
    SELECT 
        yyyymmdd, 
        customer_id,
        order_id, 
        order_status, 
        modified_order_status, 
        spd_fraud_flag,
        quarter_hour,
        CASE 
            WHEN modified_order_status IN ('OCARA', 'COBRA', 'COBRM') 
            THEN (customer_cancelled_epoch / 1000 - order_requested_epoch / 1000) 
        END AS time_spent_in_sec,
        CASE 
            WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') 
            THEN (rider_accepted_epoch / 1000 - order_requested_epoch / 1000)
        END AS time_taken_to_accp,
        case when SUBSTR(customer_id, -1) in ('1','3','5','7','9','e','a','d') then 'test' else 'control' end as test_group
    
    FROM 
        orders.order_logs_fact fact
    WHERE 
         yyyymmdd >= '20240911' AND yyyymmdd <= '20240915'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city_name = 'Delhi'
        AND service_obj_service_name in ('Auto','Auto Lite','Auto NCR','Auto Pool','AutoPremium','CityAuto','Link','Bike Lite','Bike Pink','CabEconomy','Bike Metro', 'CabPremium')
        AND channel_host='android'
        and customer_id in(
                select
                    user_id
        from 
            clevertap.clevertap_customer_order_activity
        where 
            yyyymmdd >= '20240911' AND yyyymmdd <= '20240915'
            AND order_activity_source = 'appOpen'
            and current_city = 'Delhi'
            and platform='Android'
            and app_version>='8.30.0'
            
            
            )
),





view_tbl as(
        select 
            profile_identity as user_id,
            yyyymmdd,
            'viewed' as event_type
        from
            clevertap.customer_notification_viewed_immutable 
        where yyyymmdd >= '20240911' AND yyyymmdd <= '20240915'
        and event_props_campaign_id = '1725970812' 

),

click_tbl as(
        select
            profile_identity as user_id,
            CASE
                when event_props_wzrk_c2a='Button 2' then 'play_click'
                else 'close_click'
            end as click_type,
            yyyymmdd
        from
            clevertap.customer_notification_clicked_immutable 
        where yyyymmdd >= '20240911' AND yyyymmdd <= '20240915' 
        and event_props_campaign_id = '1725970812' 
),

segment AS (
    
    SELECT
        customer_id,
        taxi_ltr_segment ltr_segment,
        taxi_retention_segments retention_segment,
        taxi_lifetime_stage lifetime_stage,
        taxi_service_affinity service_affinity,
        gender_tag gender
    FROM
        datasets.iallocator_customer_segments
    WHERE 
        run_date = '2024-09-11'
    
),

merge as(
        select rr_net.*,
        view_tbl.event_type,
        click_tbl.click_type,
        segment.ltr_segment
        from 
            rr_net
        left join 
            view_tbl
                on rr_net.customer_id=view_tbl.user_id
                and rr_net.yyyymmdd=view_tbl.yyyymmdd
        left join 
            click_tbl
            on view_tbl.user_id=click_tbl.user_id
            and view_tbl.yyyymmdd=click_tbl.yyyymmdd
        LEFT JOIN 
            segment
        ON rr_net.customer_id=segment.customer_id
        )

SELECT
        test_group,
        event_type,
        click_type,
        ltr_segment,
        customers,

        gross_count,
        net_count,
        
        COALESCE(TRY(net_count*100.00/gross_count), 0) g2n,
        
        COALESCE(TRY(tot_accepted*100.00/gross_count), 0) "aor",
        
        
        median_cobrm_time,
        median_cobra_time,
        median_ocara_time,
        median_cancellation_time,
        median_acceptance_time,
        
        COALESCE(TRY(cobrm*100.00/gross_count), 0) "% cobrm",
        COALESCE(TRY(cobra*100.00/gross_count), 0) "% cobra",
        COALESCE(TRY(ocara*100.00/gross_count), 0) "% ocara",
        COALESCE(TRY(expired*100.00/gross_count), 0) "% expired",
        cobrm, 
        cobra,
        ocara,
        expired
    FROM    
        (
        SELECT
            test_group,
            event_type,
            click_type,
            ltr_segment,
            COUNT(DISTINCT customer_id) customers,
            COUNT(DISTINCT order_id) gross_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' AND spd_fraud_flag != true THEN order_id END) net_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN order_id END) AS tot_accepted,

        
           
            
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRM' THEN order_id END) cobrm,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRA' THEN order_id END) cobra,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'OCARA' THEN order_id END) ocara,
            COUNT(DISTINCT CASE WHEN order_status = 'expired' THEN order_id END) expired,
            
            approx_percentile(CASE WHEN modified_order_status = 'COBRM' THEN time_spent_in_sec END,0.50) as median_cobrm_time,
            approx_percentile(CASE WHEN modified_order_status = 'COBRA' THEN time_spent_in_sec END,0.50) as median_cobra_time,
            approx_percentile(CASE WHEN modified_order_status = 'OCARA' THEN time_spent_in_sec END,0.50) as median_ocara_time,
            approx_percentile(CASE WHEN modified_order_status in ('COBRA','COBRM','OCARA') THEN time_spent_in_sec END,0.50) as median_cancellation_time,
            approx_percentile(CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN time_taken_to_accp END,0.50) as median_acceptance_time
            
        FROM 
            merge
        where 
            yyyymmdd is not null
           and NOT (test_group = 'control' AND event_type IS NOT NULL)
           and NOT (event_type IS NULL AND click_type IS NOT NULL)
        GROUP BY 1,2,3,4
        )
    ORDER BY 1,2,3,4

    
    
    
    
"""
ltr_segment_games_df=pd.read_sql(ltr_segment_games_query,conn)

/var/folders/km/1ltm54y105x6dzlcf44g881c0000gn/T/ipykernel_31458/3587971687.py:182: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  ltr_segment_games_df=pd.read_sql(ltr_segment_games_query,conn)

In [137]:
ltr_segment_games_df

,test_group,event_type,click_type,ltr_segment,customers,gross_count,net_count,g2n,aor,median_cobrm_time,median_cobra_time,median_ocara_time,median_cancellation_time,median_acceptance_time,% cobrm,% cobra,% ocara,% expired,cobrm,cobra,ocara,expired
0,control,None,None,HH,64553,149254,63920,42.83,62.85,114,144,361,190,15,2.23,20.46,19.54,14.43,3335,30531,29163,21530
1,control,None,None,PHH,285313,1050787,499143,47.50,65.02,105,130,302,170,14,1.44,21.81,17.19,11.71,15154,229144,180613,123061
2,control,None,None,UNKNOWN,9526,24583,5458,22.20,55.38,86,133,304,168,14,7.75,19.54,32.59,17.30,1906,4803,8011,4252
3,control,None,None,None,20818,45829,18648,40.69,62.22,116,147,437,213,14,2.71,18.73,20.87,16.30,1243,8584,9565,7469
4,test,viewed,close_click,HH,48780,97137,41451,42.67,62.48,127,145,370,195,14,2.17,20.10,19.35,15.21,2105,19526,18793,14776
5,test,viewed,close_click,PHH,214492,560687,264166,47.11,64.52,111,132,311,172,15,1.43,21.99,17.07,12.04,8035,123306,95736,67506
6,test,viewed,close_click,UNKNOWN,5578,12573,3028,24.08,55.58,90,139,269,162,13,5.78,20.09,30.85,18.50,727,2526,3879,2326
7,test,viewed,close_click,None,11718,25010,9913,39.64,60.94,111,150,414,210,14,2.85,19.36,20.68,16.82,713,4841,5173,4207
8,test,viewed,play_click,HH,4707,8819,3482,39.48,61.75,138,143,392,203,15,2.36,19.65,21.65,16.20,208,1733,1909,1429
9,test,viewed,play_click,PHH,21236,46149,20212,43.80,62.10,104,127,300,164,16,1.61,22.64,17.96,13.62,743,10447,8290,6287
10,test,viewed,play_click,UNKNOWN,688,1470,275,18.71,57.82,78,135,290,177,13,5.78,18.78,38.78,17.62,85,276,570,259
11,test,viewed,play_click,None,1279,2813,952,33.84,56.99,68,141,439,191,14,5.79,18.88,22.36,18.31,163,531,629,515
12,test,viewed,None,HH,1072,1834,742,40.46,66.47,140,122,386,203,12,1.91,14.45,25.30,17.01,35,265,464,312
13,test,viewed,None,PHH,7653,15767,8050,51.06,70.91,118,135,311,189,13,0.93,16.41,19.45,11.71,146,2587,3067,1847
14,test,viewed,None,UNKNOWN,136,289,36,12.46,58.13,65,112,350,175,10,6.92,15.92,45.67,19.03,20,46,132,55
15,test,viewed,None,None,264,498,143,28.71,59.04,114,120,565,223,16,2.21,16.27,28.92,22.29,11,81,144,111
16,test,None,None,HH,21442,42754,19383,45.34,65.50,114,140,343,185,13,2.11,19.50,19.69,12.85,903,8337,8418,5494
17,test,None,None,PHH,141410,431537,205620,47.65,64.89,103,127,292,164,15,1.39,22.14,16.93,11.55,6014,95544,73052,49863
18,test,None,None,UNKNOWN,4492,10246,2191,21.38,56.88,75,125,337,164,14,9.64,18.21,34.97,15.24,988,1866,3583,1562
19,test,None,None,None,9961,18036,7516,41.67,63.55,87,142,414,193,13,5.12,16.59,21.41,14.70,924,2993,3861,2652

In [138]:
retention_segment_games_query=f"""
with rr_net AS (
    SELECT 
        yyyymmdd, 
        customer_id,
        order_id, 
        order_status, 
        modified_order_status, 
        spd_fraud_flag,
        quarter_hour,
        CASE 
            WHEN modified_order_status IN ('OCARA', 'COBRA', 'COBRM') 
            THEN (customer_cancelled_epoch / 1000 - order_requested_epoch / 1000) 
        END AS time_spent_in_sec,
        CASE 
            WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') 
            THEN (rider_accepted_epoch / 1000 - order_requested_epoch / 1000)
        END AS time_taken_to_accp,
        case when SUBSTR(customer_id, -1) in ('1','3','5','7','9','e','a','d') then 'test' else 'control' end as test_group
    
    FROM 
        orders.order_logs_fact fact
    WHERE 
         yyyymmdd >= '20240911' AND yyyymmdd <= '20240915'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city_name = 'Delhi'
        AND service_obj_service_name in ('Auto','Auto Lite','Auto NCR','Auto Pool','AutoPremium','CityAuto','Link','Bike Lite','Bike Pink','CabEconomy','Bike Metro', 'CabPremium')
        AND channel_host='android'
        and customer_id in(
                select
                    user_id
        from 
            clevertap.clevertap_customer_order_activity
        where 
            yyyymmdd >= '20240911' AND yyyymmdd <= '20240915'
            AND order_activity_source = 'appOpen'
            and current_city = 'Delhi'
            and platform='Android'
            and app_version>='8.30.0'
            
            
            )
),





view_tbl as(
        select 
            profile_identity as user_id,
            yyyymmdd,
            'viewed' as event_type
        from
            clevertap.customer_notification_viewed_immutable 
        where yyyymmdd >= '20240911' AND yyyymmdd <= '20240915'
        and event_props_campaign_id = '1725970812' 

),

click_tbl as(
        select
            profile_identity as user_id,
            CASE
                when event_props_wzrk_c2a='Button 2' then 'play_click'
                else 'close_click'
            end as click_type,
            yyyymmdd
        from
            clevertap.customer_notification_clicked_immutable 
        where yyyymmdd >= '20240911' AND yyyymmdd <= '20240915' 
        and event_props_campaign_id = '1725970812' 
),

segment AS (
    
    SELECT
        customer_id,
        taxi_ltr_segment ltr_segment,
        taxi_retention_segments retention_segment,
        taxi_lifetime_stage lifetime_stage,
        taxi_service_affinity service_affinity,
        gender_tag gender
    FROM
        datasets.iallocator_customer_segments
    WHERE 
        run_date = '2024-09-11'
    
),

merge as(
        select rr_net.*,
        view_tbl.event_type,
        click_tbl.click_type,
        segment.retention_segment
        from 
            rr_net
        left join 
            view_tbl
                on rr_net.customer_id=view_tbl.user_id
                and rr_net.yyyymmdd=view_tbl.yyyymmdd
        left join 
            click_tbl
            on view_tbl.user_id=click_tbl.user_id
            and view_tbl.yyyymmdd=click_tbl.yyyymmdd
        LEFT JOIN 
            segment
        ON rr_net.customer_id=segment.customer_id
        )

SELECT
        test_group,
        event_type,
        click_type,
        retention_segment,
        customers,

        gross_count,
        net_count,
        
        COALESCE(TRY(net_count*100.00/gross_count), 0) g2n,
        
        COALESCE(TRY(tot_accepted*100.00/gross_count), 0) "aor",
        
        
        median_cobrm_time,
        median_cobra_time,
        median_ocara_time,
        median_cancellation_time,
        median_acceptance_time,
        
        COALESCE(TRY(cobrm*100.00/gross_count), 0) "% cobrm",
        COALESCE(TRY(cobra*100.00/gross_count), 0) "% cobra",
        COALESCE(TRY(ocara*100.00/gross_count), 0) "% ocara",
        COALESCE(TRY(expired*100.00/gross_count), 0) "% expired",
        cobrm, 
        cobra,
        ocara,
        expired
    FROM    
        (
        SELECT
            test_group,
            event_type,
            click_type,
            retention_segment,
            COUNT(DISTINCT customer_id) customers,
            COUNT(DISTINCT order_id) gross_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' AND spd_fraud_flag != true THEN order_id END) net_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN order_id END) AS tot_accepted,

        
           
            
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRM' THEN order_id END) cobrm,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRA' THEN order_id END) cobra,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'OCARA' THEN order_id END) ocara,
            COUNT(DISTINCT CASE WHEN order_status = 'expired' THEN order_id END) expired,
            
            approx_percentile(CASE WHEN modified_order_status = 'COBRM' THEN time_spent_in_sec END,0.50) as median_cobrm_time,
            approx_percentile(CASE WHEN modified_order_status = 'COBRA' THEN time_spent_in_sec END,0.50) as median_cobra_time,
            approx_percentile(CASE WHEN modified_order_status = 'OCARA' THEN time_spent_in_sec END,0.50) as median_ocara_time,
            approx_percentile(CASE WHEN modified_order_status in ('COBRA','COBRM','OCARA') THEN time_spent_in_sec END,0.50) as median_cancellation_time,
            approx_percentile(CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN time_taken_to_accp END,0.50) as median_acceptance_time
            
        FROM 
            merge
        where 
            yyyymmdd is not null
           and NOT (test_group = 'control' AND event_type IS NOT NULL)
           and NOT (event_type IS NULL AND click_type IS NOT NULL)
        GROUP BY 1,2,3,4
        )
    ORDER BY 1,2,3,4

    
    
    
    
"""
retention_segment_games_df=pd.read_sql(retention_segment_games_query,conn)

/var/folders/km/1ltm54y105x6dzlcf44g881c0000gn/T/ipykernel_31458/3682328015.py:182: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  retention_segment_games_df=pd.read_sql(retention_segment_games_query,conn)

In [139]:
retention_segment_games_df

,test_group,event_type,click_type,retention_segment,customers,gross_count,net_count,g2n,aor,median_cobrm_time,median_cobra_time,median_ocara_time,median_cancellation_time,median_acceptance_time,% cobrm,% cobra,% ocara,% expired,cobrm,cobra,ocara,expired
0,control,None,None,DORMANT,53528,112442,44427,39.51,60.25,117.0,141,343,186,15,2.07,22.03,20.27,15.61,2324,24776,22796,17556
1,control,None,None,ELITE,61979,387715,194261,50.10,66.84,97.0,124,279,160,15,1.20,21.62,16.44,10.33,4636,83819,63722,40055
2,control,None,None,GOLD,64497,189977,88117,46.38,64.21,110.0,133,322,174,14,1.64,21.92,17.48,12.20,3125,41648,33216,23173
3,control,None,None,HH,36905,93157,43364,46.55,64.91,114.0,142,357,187,14,2.05,20.00,17.94,13.01,1911,18631,16711,12123
4,control,None,None,INACTIVE,25267,50782,19305,38.02,60.09,110.0,150,366,197,15,2.37,20.91,21.56,16.57,1206,10621,10948,8417
5,control,None,None,PLATINUM,68828,259935,121979,46.93,64.32,102.0,128,295,165,14,1.43,22.55,17.09,11.68,3729,58625,44414,30348
6,control,None,None,PRIME,3418,23178,12582,54.28,70.48,97.0,121,266,156,14,1.08,20.77,15.88,7.65,250,4815,3681,1774
7,control,None,None,SILVER,35444,82855,39028,47.10,64.74,125.0,141,337,187,14,1.58,20.20,17.24,13.45,1308,16740,14288,11145
8,control,None,None,UNKNOWN,9526,24583,5458,22.20,55.38,86.0,133,305,168,14,7.75,19.54,32.59,17.30,1906,4803,8011,4252
9,control,None,None,None,20818,45829,18648,40.69,62.22,116.0,147,437,213,14,2.71,18.73,20.87,16.30,1243,8584,9565,7469
10,test,viewed,close_click,DORMANT,39107,73153,28970,39.60,59.71,129.0,144,352,191,15,1.99,22.01,19.70,16.25,1458,16104,14408,11890
11,test,viewed,close_click,ELITE,48361,177111,88807,50.14,66.70,98.0,124,283,160,14,1.14,21.81,16.26,10.34,2016,38622,28790,18318
12,test,viewed,close_click,GOLD,48993,113349,52582,46.39,63.99,116.0,136,331,178,14,1.57,21.84,17.24,12.58,1777,24761,19543,14259
13,test,viewed,close_click,HH,28717,60255,27732,46.02,64.56,128.0,142,367,192,14,2.00,19.66,18.12,13.75,1205,11848,10920,8285
14,test,viewed,close_click,INACTIVE,17149,31112,11871,38.16,59.55,130.0,149,372,199,15,2.18,21.00,20.81,17.22,678,6533,6473,5356
15,test,viewed,close_click,PLATINUM,52566,141589,66612,47.05,64.25,100.0,130,300,167,14,1.37,22.67,16.95,11.69,1935,32099,23993,16555
16,test,viewed,close_click,PRIME,2666,9931,5368,54.05,69.06,108.0,122,285,157,13,1.36,21.69,14.77,7.88,135,2154,1467,783
17,test,viewed,close_click,SILVER,25713,51324,23675,46.13,63.95,120.0,140,349,185,15,1.82,20.87,17.41,13.32,936,10711,8935,6836
18,test,viewed,close_click,UNKNOWN,5578,12573,3028,24.08,55.58,90.0,138,269,164,13,5.78,20.09,30.85,18.50,727,2526,3879,2326
19,test,viewed,close_click,None,11718,25010,9913,39.64,60.94,111.0,150,415,210,14,2.85,19.36,20.68,16.82,713,4841,5173,4207
20,test,viewed,play_click,DORMANT,3540,6442,2249,34.91,57.26,124.0,148,342,193,15,2.58,21.84,21.70,18.30,166,1407,1398,1179
21,test,viewed,play_click,ELITE,5790,15138,7158,47.28,63.95,95.0,120,268,153,16,1.34,22.82,16.44,11.88,203,3454,2489,1799
22,test,viewed,play_click,GOLD,4368,8492,3766,44.35,62.98,105.0,132,331,173,16,1.79,21.79,18.23,13.41,152,1850,1548,1139
23,test,viewed,play_click,HH,2789,5408,2335,43.18,63.39,131.0,137,383,197,14,2.16,19.08,19.62,15.31,117,1032,1061,828
24,test,viewed,play_click,INACTIVE,1635,2916,952,32.65,56.89,125.0,148,391,206,16,2.09,21.71,23.77,19.24,61,633,693,561
25,test,viewed,play_click,PLATINUM,5245,11641,5019,43.11,61.39,102.0,122,282,156,15,1.48,24.08,17.95,13.05,172,2803,2089,1519
26,test,viewed,play_click,PRIME,393,980,538,54.90,70.20,81.0,118,273,161,15,1.33,20.00,15.10,8.47,13,196,148,83
27,test,viewed,play_click,SILVER,2183,3951,1677,42.44,62.41,110.0,139,359,188,16,1.70,20.37,19.56,15.39,67,805,773,608
28,test,viewed,play_click,UNKNOWN,688,1470,275,18.71,57.82,78.0,135,290,177,13,5.78,18.78,38.78,17.62,85,276,570,259
29,test,viewed,play_click,None,1279,2813,952,33.84,56.99,68.0,141,439,189,14,5.79,18.88,22.36,18.31,163,531,629,515
30,test,viewed,None,DORMANT,852,1414,551,38.97,65.70,94.0,137,379,207,13,1.98,18.60,25.81,13.58,28,263,365,192
31,test,viewed,None,ELITE,2742,6547,3573,54.57,72.90,131.0,135,288,186,12,0.66,15.61,17.86,10.81,43,1022,1169,708
32,test,viewed,None,GOLD,1442,2601,1297,49.87,70.40,126.0,138,344,195,13,1.58,16.69,20.15,11.30,41,434,524,294
33,test,viewed,None,HH,671,1168,533,45.63,68.41,164.0,119,347,196,11,1.46,13.70,22.52,16.35,17,160,263,191
34,test,viewed,None,INACTIVE,354,576,170,29.51,60.24,123.0,123,416,216,14,2.08,15.63,30.03,21.88,12,90,173,126
35,test,viewed,None,PLATINUM,1939,3962,2016,50.88,69.84,109.0,130,314,182,13,0.71,17.31,18.63,12.09,28,686,738,479
36,test,viewed,None,PRIME,132,301,185,61.46,78.74,NaN,107,227,147,12,0.00,16.94,17.28,4.32,0,51,52,13
37,test,viewed,None,SILVER,593,1032,467,45.25,69.48,136.0,152,279,200,13,1.16,14.15,23.93,15.12,12,146,247,156
38,test,viewed,None,UNKNOWN,136,289,36,12.46,58.13,65.0,112,350,175,10,6.92,15.92,45.67,19.03,20,46,132,55
39,test,viewed,None,None,264,498,143,28.71,59.04,114.0,120,565,223,16,2.21,16.27,28.92,22.29,11,81,144,111
40,test,None,None,DORMANT,16665,31333,12937,41.29,62.23,108.0,138,334,181,14,2.01,21.11,20.52,14.61,631,6613,6430,4578
41,test,None,None,ELITE,45400,189484,94274,49.75,66.24,98.0,122,273,156,15,1.19,22.09,16.18,10.46,2264,41866,30655,19823
42,test,None,None,GOLD,27165,66299,30521,46.04,63.69,111.0,135,318,174,14,1.64,22.04,17.32,12.62,1084,14610,11485,8367
43,test,None,None,HH,13434,28342,13811,48.73,66.30,114.0,137,345,181,13,1.97,19.84,17.18,11.87,558,5624,4870,3365
44,test,None,None,INACTIVE,8339,15161,6012,39.65,63.00,114.0,144,341,188,14,2.25,19.44,22.82,15.25,341,2948,3460,2312
45,test,None,None,PLATINUM,35898,103180,47686,46.22,63.66,101.0,127,286,162,15,1.40,23.02,17.14,11.89,1449,23756,17683,12271
46,test,None,None,PRIME,2707,12855,6816,53.02,68.28,87.0,120,274,153,14,1.29,22.66,14.94,7.76,166,2913,1920,997
47,test,None,None,SILVER,13244,27637,12946,46.84,65.16,118.0,135,328,181,15,1.53,20.09,17.97,13.19,424,5551,4967,3644
48,test,None,None,UNKNOWN,4492,10246,2191,21.38,56.88,75.0,125,336,163,13,9.64,18.21,34.97,15.24,988,1866,3583,1562
49,test,None,None,None,9961,18036,7516,41.67,63.55,87.0,142,413,193,13,5.12,16.59,21.41,14.70,924,2993,3861,2652

In [140]:
service_games_query=f"""
with rr_net AS (
    SELECT 
        yyyymmdd, 
        customer_id,
        order_id, 
        order_status, 
        modified_order_status, 
        spd_fraud_flag,
        quarter_hour,
        CASE 
            WHEN modified_order_status IN ('OCARA', 'COBRA', 'COBRM') 
            THEN (customer_cancelled_epoch / 1000 - order_requested_epoch / 1000) 
        END AS time_spent_in_sec,
        CASE 
            WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') 
            THEN (rider_accepted_epoch / 1000 - order_requested_epoch / 1000)
        END AS time_taken_to_accp,
        case when SUBSTR(customer_id, -1) in ('1','3','5','7','9','e','a','d') then 'test' else 'control' end as test_group,
        CASE 
            WHEN service_obj_service_name IN ('Auto', 'Auto Lite', 'Auto NCR', 'Auto Pool', 'AutoPremium', 'CityAuto') THEN 'auto'
            WHEN service_obj_service_name IN ('Bike Lite', 'Bike Pink', 'Bike Metro', 'Link') THEN 'bike'
            WHEN service_obj_service_name IN ('CabEconomy', 'CabPremium') THEN 'cab'
            ELSE 'other'
        END AS service_category
    
    FROM 
        orders.order_logs_fact fact
    WHERE 
         yyyymmdd >= '20240911' AND yyyymmdd <= '20240915'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city_name = 'Delhi'
        AND service_obj_service_name in ('Auto','Auto Lite','Auto NCR','Auto Pool','AutoPremium','CityAuto','Link','Bike Lite','Bike Pink','CabEconomy','Bike Metro', 'CabPremium')
        AND channel_host='android'
        and customer_id in(
                select
                    user_id
        from 
            clevertap.clevertap_customer_order_activity
        where 
            yyyymmdd >= '20240911' AND yyyymmdd <= '20240915'
            AND order_activity_source = 'appOpen'
            and current_city = 'Delhi'
            and platform='Android'
            and app_version>='8.30.0'
            
            
            )
),





view_tbl as(
        select 
            profile_identity as user_id,
            yyyymmdd,
            'viewed' as event_type
        from
            clevertap.customer_notification_viewed_immutable 
        where yyyymmdd >= '20240911' AND yyyymmdd <= '20240915'
        and event_props_campaign_id = '1725970812' 

),

click_tbl as(
        select
            profile_identity as user_id,
            CASE
                when event_props_wzrk_c2a='Button 2' then 'play_click'
                else 'close_click'
            end as click_type,
            yyyymmdd
        from
            clevertap.customer_notification_clicked_immutable 
        where yyyymmdd >= '20240911' AND yyyymmdd <= '20240915' 
        and event_props_campaign_id = '1725970812' 
),

segment AS (
    
    SELECT
        customer_id,
        taxi_ltr_segment ltr_segment,
        taxi_retention_segments retention_segment,
        taxi_lifetime_stage lifetime_stage,
        taxi_service_affinity service_affinity,
        gender_tag gender
    FROM
        datasets.iallocator_customer_segments
    WHERE 
        run_date = '2024-09-11'
    
),

merge as(
        select rr_net.*,
        view_tbl.event_type,
        click_tbl.click_type,
        segment.retention_segment
        from 
            rr_net
        left join 
            view_tbl
                on rr_net.customer_id=view_tbl.user_id
                and rr_net.yyyymmdd=view_tbl.yyyymmdd
        left join 
            click_tbl
            on view_tbl.user_id=click_tbl.user_id
            and view_tbl.yyyymmdd=click_tbl.yyyymmdd
        LEFT JOIN 
            segment
        ON rr_net.customer_id=segment.customer_id
        )

SELECT
        test_group,
        event_type,
        click_type,
        service_category,
        customers,

        gross_count,
        net_count,
        
        COALESCE(TRY(net_count*100.00/gross_count), 0) g2n,
        
        COALESCE(TRY(tot_accepted*100.00/gross_count), 0) "aor",
        
        
        median_cobrm_time,
        median_cobra_time,
        median_ocara_time,
        median_cancellation_time,
        median_acceptance_time,
        
        COALESCE(TRY(cobrm*100.00/gross_count), 0) "% cobrm",
        COALESCE(TRY(cobra*100.00/gross_count), 0) "% cobra",
        COALESCE(TRY(ocara*100.00/gross_count), 0) "% ocara",
        COALESCE(TRY(expired*100.00/gross_count), 0) "% expired",
        cobrm, 
        cobra,
        ocara,
        expired
    FROM    
        (
        SELECT
            test_group,
            event_type,
            click_type,
            service_category,
            COUNT(DISTINCT customer_id) customers,
            COUNT(DISTINCT order_id) gross_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' AND spd_fraud_flag != true THEN order_id END) net_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN order_id END) AS tot_accepted,

        
           
            
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRM' THEN order_id END) cobrm,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRA' THEN order_id END) cobra,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'OCARA' THEN order_id END) ocara,
            COUNT(DISTINCT CASE WHEN order_status = 'expired' THEN order_id END) expired,
            
            approx_percentile(CASE WHEN modified_order_status = 'COBRM' THEN time_spent_in_sec END,0.50) as median_cobrm_time,
            approx_percentile(CASE WHEN modified_order_status = 'COBRA' THEN time_spent_in_sec END,0.50) as median_cobra_time,
            approx_percentile(CASE WHEN modified_order_status = 'OCARA' THEN time_spent_in_sec END,0.50) as median_ocara_time,
            approx_percentile(CASE WHEN modified_order_status in ('COBRA','COBRM','OCARA') THEN time_spent_in_sec END,0.50) as median_cancellation_time,
            approx_percentile(CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN time_taken_to_accp END,0.50) as median_acceptance_time
            
        FROM 
            merge
        where 
            yyyymmdd is not null
           and NOT (test_group = 'control' AND event_type IS NOT NULL)
           and NOT (event_type IS NULL AND click_type IS NOT NULL)
        GROUP BY 1,2,3,4
        )
    ORDER BY 1,2,3,4

    
    
    
    
"""
service_games_df=pd.read_sql(service_games_query,conn)

/var/folders/km/1ltm54y105x6dzlcf44g881c0000gn/T/ipykernel_31458/1397612730.py:188: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  service_games_df=pd.read_sql(service_games_query,conn)

In [141]:
service_games_df

,test_group,event_type,click_type,service_category,customers,gross_count,net_count,g2n,aor,median_cobrm_time,median_cobra_time,median_ocara_time,median_cancellation_time,median_acceptance_time,% cobrm,% cobra,% ocara,% expired,cobrm,cobra,ocara,expired
0,control,None,None,auto,159326,405395,136774,33.74,47.64,112,129,289,153,15,2.91,27.80,13.86,21.64,11789,112712,56197,87719
1,control,None,None,bike,235395,625683,353743,56.54,76.42,104,128,314,184,15,1.13,17.04,19.22,5.39,7056,106629,120262,33714
2,control,None,None,cab,106732,239375,96652,40.38,61.77,81,147,340,196,13,1.17,22.44,21.26,14.57,2793,53721,50893,34879
3,test,viewed,close_click,auto,110778,230277,77616,33.71,47.52,116,131,297,155,15,2.98,27.56,13.77,21.94,6862,63453,31707,50519
4,test,viewed,close_click,bike,164673,327911,185867,56.68,76.62,112,130,326,188,15,1.03,16.85,19.26,5.47,3374,55258,63154,17948
5,test,viewed,close_click,cab,71323,137219,55075,40.14,61.19,92,151,354,203,14,0.98,22.95,20.93,14.83,1344,31488,28720,20348
6,test,viewed,play_click,auto,9908,18947,5713,30.15,44.29,111,129,295,151,15,3.44,27.82,14.07,24.44,651,5271,2665,4631
7,test,viewed,play_click,bike,16615,28989,15159,52.29,74.17,97,123,324,182,16,1.43,17.96,21.13,6.42,415,5205,6126,1861
8,test,viewed,play_click,cab,6225,11315,4049,35.78,58.91,58,149,337,200,14,1.18,22.19,23.04,17.66,133,2511,2607,1998
9,test,viewed,None,auto,3084,5616,2118,37.71,53.85,121,134,294,164,13,1.98,21.37,16.04,22.79,111,1200,901,1280
10,test,viewed,None,bike,5464,9407,5393,57.33,79.89,110,126,329,203,12,0.82,13.55,21.80,5.72,77,1275,2051,538
11,test,viewed,None,cab,1975,3365,1460,43.39,69.03,83,146,342,227,12,0.71,14.98,25.41,15.07,24,504,855,507
12,test,None,None,auto,68654,154679,52506,33.95,47.86,108,127,276,148,15,2.82,28.21,13.87,21.11,4364,43633,21452,32649
13,test,None,None,bike,111244,259831,146145,56.25,75.56,91,126,304,175,15,1.32,17.61,18.72,5.49,3438,45757,48640,14253
14,test,None,None,cab,43725,88063,36059,40.95,62.44,81,143,330,192,13,1.17,21.97,21.37,14.39,1027,19350,18822,12669

In [179]:
overall_cluster_query=f"""
with rr_net AS (
    SELECT 
        yyyymmdd, 
        customer_id,
        order_id, 
        order_status, 
        modified_order_status, 
        spd_fraud_flag,
        quarter_hour,
        CASE 
            WHEN pickup_cluster IN (              
                'Gurgaon Rural', 
                'NCR N sec 6354', 
                'Dashrathpuri_Del_East', 
                'NCR N sec 2262', 
                'NCR N Sharda University 2', 
                'NCR N Gharoli', 
                'NCR G Vijay Nagar 2', 
                'NCR N Venice Mall', 
                'Dwarka_Del', 
                'NCR N WaveCity Center'
            ) THEN pickup_cluster
            ELSE 'Other_clusters'
        END AS cluster_name,
        CASE 
            WHEN modified_order_status IN ('OCARA', 'COBRA', 'COBRM') 
            THEN (customer_cancelled_epoch / 1000 - order_requested_epoch / 1000) 
        END AS time_spent_in_sec,
        CASE 
            WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') 
            THEN (rider_accepted_epoch / 1000 - order_requested_epoch / 1000)
        END AS time_taken_to_accp,
        case when SUBSTR(customer_id, -1) in ('1','3','5','7','9','e','a','d') then 'test' else 'control' end as test_group
    
    FROM 
        orders.order_logs_fact fact
    WHERE 
         yyyymmdd >= '20240911' AND yyyymmdd <= '20240916'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city_name = 'Delhi'
        AND service_obj_service_name in ('Auto','Auto Lite','Auto NCR','Auto Pool','AutoPremium','CityAuto','Link','Bike Lite','Bike Pink','CabEconomy','Bike Metro', 'CabPremium')
        AND channel_host='android'
        and customer_id in(
                select
                    user_id
        from 
            clevertap.clevertap_customer_order_activity
        where 
            yyyymmdd >= '20240911' AND yyyymmdd <= '20240916'
            AND order_activity_source = 'appOpen'
            and current_city = 'Delhi'
            and platform='Android'
            and app_version>='8.30.0'
            
            
            )
),





view_tbl as(
        select 
            profile_identity as user_id,
            yyyymmdd,
            'viewed' as event_type
        from
            clevertap.customer_notification_viewed_immutable 
        where yyyymmdd >= '20240911' AND yyyymmdd <= '20240916'
        and event_props_campaign_id = '1725970812' 

),

click_tbl as(
        select
            profile_identity as user_id,
            CASE
                when event_props_wzrk_c2a='Button 2' then 'play_click'
                else 'close_click'
            end as click_type,
            yyyymmdd
        from
            clevertap.customer_notification_clicked_immutable 
        where yyyymmdd >= '20240911' AND yyyymmdd <= '20240916' 
        and event_props_campaign_id = '1725970812' 
),

merge as(
        select rr_net.*,view_tbl.event_type,click_tbl.click_type
        from rr_net
        left join 
            view_tbl
                on rr_net.customer_id=view_tbl.user_id
                and rr_net.yyyymmdd=view_tbl.yyyymmdd
        left join 
            click_tbl
            on view_tbl.user_id=click_tbl.user_id
            and view_tbl.yyyymmdd=click_tbl.yyyymmdd
        )

SELECT
        test_group,
        event_type,
        click_type,
        cluster_name,
        customers,

        gross_count,
        net_count,
        
        COALESCE(TRY(net_count*100.00/gross_count), 0) g2n,
        
        COALESCE(TRY(tot_accepted*100.00/gross_count), 0) "aor",
        
        
        median_cobrm_time,
        median_cobra_time,
        median_ocara_time,
        median_cancellation_time,
        median_acceptance_time,
        
        COALESCE(TRY(cobrm*100.00/gross_count), 0) "% cobrm",
        COALESCE(TRY(cobra*100.00/gross_count), 0) "% cobra",
        COALESCE(TRY(ocara*100.00/gross_count), 0) "% ocara",
        COALESCE(TRY(expired*100.00/gross_count), 0) "% expired",
        cobrm, 
        cobra,
        ocara,
        expired
    FROM    
        (
        SELECT
            test_group,
            event_type,
            click_type,
            cluster_name,
            COUNT(DISTINCT customer_id) customers,
            COUNT(DISTINCT order_id) gross_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' AND spd_fraud_flag != true THEN order_id END) net_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN order_id END) AS tot_accepted,

                    
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRM' THEN order_id END) cobrm,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRA' THEN order_id END) cobra,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'OCARA' THEN order_id END) ocara,
            COUNT(DISTINCT CASE WHEN order_status = 'expired' THEN order_id END) expired,
            
            approx_percentile(CASE WHEN modified_order_status = 'COBRM' THEN time_spent_in_sec END,0.50) as median_cobrm_time,
            approx_percentile(CASE WHEN modified_order_status = 'COBRA' THEN time_spent_in_sec END,0.50) as median_cobra_time,
            approx_percentile(CASE WHEN modified_order_status = 'OCARA' THEN time_spent_in_sec END,0.50) as median_ocara_time,
            approx_percentile(CASE WHEN modified_order_status in ('COBRA','COBRM','OCARA') THEN time_spent_in_sec END,0.50) as median_cancellation_time,
            approx_percentile(CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN time_taken_to_accp END,0.50) as median_acceptance_time
            
        FROM 
            merge
        where 
            yyyymmdd is not null
           and NOT (test_group = 'control' AND event_type IS NOT NULL)
           and NOT (event_type IS NULL AND click_type IS NOT NULL)
        GROUP BY 1,2,3,4
        )
    ORDER BY 1,2,3,4   
    
"""
overall_cluster=pd.read_sql(overall_cluster_query,conn)

/var/folders/km/1ltm54y105x6dzlcf44g881c0000gn/T/ipykernel_31458/4261486077.py:168: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  overall_cluster=pd.read_sql(overall_cluster_query,conn)

In [182]:
overall_cluster

,test_group,event_type,click_type,cluster_name,customers,gross_count,net_count,g2n,aor,median_cobrm_time,median_cobra_time,median_ocara_time,median_cancellation_time,median_acceptance_time,% cobrm,% cobra,% ocara,% expired,cobrm,cobra,ocara,expired
18,test,viewed,play_click,Dashrathpuri_Del_East,696,1195,530,44.35,66.03,178.0,143,342,194,19,0.42,24.02,21.34,9.54,5,287,255,114
19,test,viewed,play_click,Dwarka_Del,213,315,159,50.48,67.94,201.0,124,204,145,12,0.63,17.46,16.19,13.97,2,55,51,44
20,test,viewed,play_click,Gurgaon Rural,316,554,238,42.96,60.65,37.0,141,317,176,14,0.18,25.81,17.51,13.36,1,143,97,74
21,test,viewed,play_click,NCR G Vijay Nagar 2,474,640,408,63.75,81.09,NaN,126,283,176,12,0.00,15.00,17.19,3.91,0,96,110,25
22,test,viewed,play_click,NCR N Gharoli,673,972,540,55.56,77.26,76.0,135,367,214,15,0.62,14.09,21.09,8.02,6,137,205,78
23,test,viewed,play_click,NCR N Sharda University 2,536,1054,299,28.37,43.64,58.0,107,296,123,10,1.23,40.80,14.99,14.33,13,430,158,151
24,test,viewed,play_click,NCR N Venice Mall,377,866,280,32.33,46.88,145.0,121,255,143,10,7.27,33.60,13.97,12.24,63,291,121,106
25,test,viewed,play_click,NCR N WaveCity Center,273,394,216,54.82,78.43,188.0,121,377,211,12,0.25,15.48,22.84,5.84,1,61,90,23
26,test,viewed,play_click,Other_clusters,30158,62339,27458,44.05,64.05,103.0,130,318,174,15,1.98,20.30,19.59,13.64,1235,12652,12214,8502

In [189]:
overall_cluster=overall_cluster[overall_cluster['click_type']=='play_click']

In [190]:
overall_cluster.to_clipboard(index=False)

In [183]:
overall_cluster_session_query=f"""
with rr_net AS (
    SELECT 
        yyyymmdd, 
        customer_id,
        order_id, 
        order_status, 
        modified_order_status, 
        spd_fraud_flag,
        quarter_hour,
        CASE 
            WHEN pickup_cluster IN (
                'Gurgaon Rural', 
                'NCR N sec 6354', 
                'Dashrathpuri_Del_East', 
                'NCR N sec 2262', 
                'NCR N Sharda University 2', 
                'NCR N Gharoli', 
                'NCR G Vijay Nagar 2', 
                'NCR N Venice Mall', 
                'Dwarka_Del', 
                'NCR N WaveCity Center'
            ) THEN pickup_cluster
            ELSE 'Other_clusters'
        END AS cluster_name,
        CASE 
            WHEN modified_order_status IN ('OCARA', 'COBRA', 'COBRM') 
            THEN (customer_cancelled_epoch / 1000 - order_requested_epoch / 1000) 
        END AS time_spent_in_sec,
        CASE 
            WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') 
            THEN (rider_accepted_epoch / 1000 - order_requested_epoch / 1000)
        END AS time_taken_to_accp,
        case when SUBSTR(customer_id, -1) in ('1','3','5','7','9','e','a','d') then 'test' else 'control' end as test_group
    
    FROM 
        orders.order_logs_fact fact
    WHERE 
         yyyymmdd >= '20240911' AND yyyymmdd <= '20240916'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city_name = 'Delhi'
        AND service_obj_service_name in ('Auto','Auto Lite','Auto NCR','Auto Pool','AutoPremium','CityAuto','Link','Bike Lite','Bike Pink','CabEconomy','Bike Metro', 'CabPremium')
        AND channel_host='android'
        and customer_id in(
                select
                    user_id
        from 
            clevertap.clevertap_customer_order_activity
        where 
            yyyymmdd >= '20240911' AND yyyymmdd <= '20240916'
            AND order_activity_source = 'appOpen'
            and current_city = 'Delhi'
            and platform='Android'
            and app_version>='8.30.0'
            
            
            )
),





view_tbl as(
        select 
            profile_identity as user_id,
            yyyymmdd,
            'viewed' as event_type
        from
            clevertap.customer_notification_viewed_immutable 
        where yyyymmdd >= '20240911' AND yyyymmdd <= '20240916'
        and event_props_campaign_id = '1725970812' 

),

click_tbl as(
        select
            profile_identity as user_id,
            CASE
                when event_props_wzrk_c2a='Button 2' then 'play_click'
                else 'close_click'
            end as click_type,
            yyyymmdd
        from
            clevertap.customer_notification_clicked_immutable 
        where yyyymmdd >= '20240911' AND yyyymmdd <= '20240916' 
        and event_props_campaign_id = '1725970812' 
),

merge as(
        select rr_net.*,view_tbl.event_type,click_tbl.click_type
        from rr_net
        left join 
            view_tbl
                on rr_net.customer_id=view_tbl.user_id
                and rr_net.yyyymmdd=view_tbl.yyyymmdd
        left join 
            click_tbl
            on view_tbl.user_id=click_tbl.user_id
            and view_tbl.yyyymmdd=click_tbl.yyyymmdd
        )

SELECT
        test_group,
        event_type,
        click_type,
        time_period,
        cluster_name,
        customers,

        gross_count,
        net_count,
        
        COALESCE(TRY(net_count*100.00/gross_count), 0) g2n,
        
        COALESCE(TRY(tot_accepted*100.00/gross_count), 0) "aor",
        
        
        median_cobrm_time,
        median_cobra_time,
        median_ocara_time,
        median_cancellation_time,
        median_acceptance_time,
        
        COALESCE(TRY(cobrm*100.00/gross_count), 0) "% cobrm",
        COALESCE(TRY(cobra*100.00/gross_count), 0) "% cobra",
        COALESCE(TRY(ocara*100.00/gross_count), 0) "% ocara",
        COALESCE(TRY(expired*100.00/gross_count), 0) "% expired",
        cobrm, 
        cobra,
        ocara,
        expired
    FROM    
        (
        SELECT
            test_group,
            event_type,
            click_type,
            case
                WHEN quarter_hour >= '0800' AND quarter_hour < '1100' THEN 'morning'
                WHEN quarter_hour >= '1100' AND quarter_hour < '1700' THEN 'afternoon'
                WHEN quarter_hour >= '1700' AND quarter_hour < '2100' THEN 'evening'
                WHEN quarter_hour >= '0000' AND quarter_hour < '0800' THEN 'rest_morning'
                ELSE 'rest_evening'
            end as time_period,
            cluster_name,
            COUNT(DISTINCT customer_id) customers,
            COUNT(DISTINCT order_id) gross_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' AND spd_fraud_flag != true THEN order_id END) net_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN order_id END) AS tot_accepted,

                    
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRM' THEN order_id END) cobrm,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRA' THEN order_id END) cobra,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'OCARA' THEN order_id END) ocara,
            COUNT(DISTINCT CASE WHEN order_status = 'expired' THEN order_id END) expired,
            
            approx_percentile(CASE WHEN modified_order_status = 'COBRM' THEN time_spent_in_sec END,0.50) as median_cobrm_time,
            approx_percentile(CASE WHEN modified_order_status = 'COBRA' THEN time_spent_in_sec END,0.50) as median_cobra_time,
            approx_percentile(CASE WHEN modified_order_status = 'OCARA' THEN time_spent_in_sec END,0.50) as median_ocara_time,
            approx_percentile(CASE WHEN modified_order_status in ('COBRA','COBRM','OCARA') THEN time_spent_in_sec END,0.50) as median_cancellation_time,
            approx_percentile(CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN time_taken_to_accp END,0.50) as median_acceptance_time
            
        FROM 
            merge
        where 
            yyyymmdd is not null
           and NOT (test_group = 'control' AND event_type IS NOT NULL)
           and NOT (event_type IS NULL AND click_type IS NOT NULL)
        GROUP BY 1,2,3,4,5
        )
    ORDER BY 1,2,3,4,5  
    
"""
overall_cluster_session=pd.read_sql(overall_cluster_session_query,conn)

/var/folders/km/1ltm54y105x6dzlcf44g881c0000gn/T/ipykernel_31458/1746420347.py:176: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  overall_cluster_session=pd.read_sql(overall_cluster_session_query,conn)

In [184]:
overall_cluster_session=overall_cluster_session[overall_cluster_session['click_type']=='play_click']

In [185]:
overall_cluster_session

,test_group,event_type,click_type,time_period,cluster_name,customers,gross_count,net_count,g2n,aor,median_cobrm_time,median_cobra_time,median_ocara_time,median_cancellation_time,median_acceptance_time,% cobrm,% cobra,% ocara,% expired,cobrm,cobra,ocara,expired
90,test,viewed,play_click,afternoon,Dashrathpuri_Del_East,262,440,192,43.64,67.95,249.0,148.0,324.0,212.0,19,0.23,23.41,24.09,8.41,1,103,106,37
91,test,viewed,play_click,afternoon,Dwarka_Del,79,99,62,62.63,75.76,NaN,147.0,556.0,165.0,8,0.00,12.12,12.12,12.12,0,12,12,12
92,test,viewed,play_click,afternoon,Gurgaon Rural,134,221,93,42.08,61.54,NaN,137.0,394.0,191.0,14,0.00,24.89,19.46,13.57,0,55,43,30
93,test,viewed,play_click,afternoon,NCR G Vijay Nagar 2,170,196,162,82.65,94.39,NaN,125.0,267.0,173.0,11,0.00,5.10,11.73,0.51,0,10,23,1
94,test,viewed,play_click,afternoon,NCR N Gharoli,220,269,182,67.66,91.82,198.0,88.0,384.0,296.0,10,0.74,4.46,23.79,2.97,2,12,64,8
95,test,viewed,play_click,afternoon,NCR N Sharda University 2,287,498,154,30.92,47.39,31.0,103.0,303.0,116.0,9,0.20,40.16,16.47,12.25,1,200,82,61
96,test,viewed,play_click,afternoon,NCR N Venice Mall,153,263,117,44.49,65.40,150.0,119.0,227.0,154.0,8,6.46,17.11,20.15,11.03,17,45,53,29
97,test,viewed,play_click,afternoon,NCR N WaveCity Center,77,97,67,69.07,95.88,NaN,117.0,464.0,426.0,9,0.00,3.09,24.74,1.03,0,3,24,1
98,test,viewed,play_click,afternoon,Other_clusters,11680,18762,9941,52.98,74.52,96.0,126.0,319.0,186.0,12,1.55,14.39,21.13,9.54,291,2699,3964,1789
99,test,viewed,play_click,evening,Dashrathpuri_Del_East,192,309,122,39.48,58.90,180.0,153.0,435.0,182.0,17,0.32,26.86,19.09,13.92,1,83,59,43
100,test,viewed,play_click,evening,Dwarka_Del,66,104,38,36.54,57.69,201.0,119.0,309.0,153.0,22,0.96,27.88,20.19,13.46,1,29,21,14
101,test,viewed,play_click,evening,Gurgaon Rural,96,143,72,50.35,65.73,NaN,119.0,250.0,153.0,12,0.00,20.98,15.38,13.29,0,30,22,19
102,test,viewed,play_click,evening,NCR G Vijay Nagar 2,116,142,88,61.97,81.69,NaN,81.0,317.0,192.0,11,0.00,14.79,19.72,3.52,0,21,28,5
103,test,viewed,play_click,evening,NCR N Gharoli,191,295,137,46.44,65.08,NaN,126.0,369.0,200.0,22,0.00,21.02,17.97,13.90,0,62,53,41
104,test,viewed,play_click,evening,NCR N Sharda University 2,202,410,73,17.80,29.27,123.0,120.0,302.0,126.0,16,0.98,49.27,10.98,20.49,4,202,45,84
105,test,viewed,play_click,evening,NCR N Venice Mall,143,257,85,33.07,48.64,104.0,127.0,273.0,156.0,13,6.61,32.30,14.40,12.45,17,83,37,32
106,test,viewed,play_click,evening,NCR N WaveCity Center,71,85,50,58.82,87.06,NaN,137.0,334.0,148.0,11,0.00,5.88,28.24,7.06,0,5,24,6
107,test,viewed,play_click,evening,Other_clusters,11541,20983,7490,35.70,54.03,103.0,133.0,321.0,170.0,18,1.88,24.84,17.98,19.20,395,5213,3772,4029
108,test,viewed,play_click,morning,Dashrathpuri_Del_East,145,193,91,47.15,68.91,178.0,106.0,239.0,160.0,22,0.52,21.76,21.24,8.81,1,42,41,17
109,test,viewed,play_click,morning,Dwarka_Del,33,43,30,69.77,95.35,NaN,262.0,144.0,144.0,8,0.00,2.33,23.26,2.33,0,1,10,1
110,test,viewed,play_click,morning,Gurgaon Rural,76,127,44,34.65,45.67,NaN,148.0,214.0,158.0,17,0.00,39.37,11.02,14.96,0,50,14,19
111,test,viewed,play_click,morning,NCR G Vijay Nagar 2,131,175,89,50.86,69.71,NaN,128.0,384.0,175.0,29,0.00,23.43,18.86,6.86,0,41,33,12
112,test,viewed,play_click,morning,NCR N Gharoli,151,191,118,61.78,81.68,NaN,143.0,324.0,189.0,22,0.00,12.57,19.37,5.76,0,24,37,11
113,test,viewed,play_click,morning,NCR N Sharda University 2,88,120,61,50.83,73.33,240.0,89.0,289.0,147.0,8,3.33,20.00,22.50,3.33,4,24,27,4
114,test,viewed,play_click,morning,NCR N Venice Mall,89,245,51,20.82,28.57,116.0,122.0,277.0,128.0,13,3.67,56.73,7.76,11.02,9,139,19,27
115,test,viewed,play_click,morning,NCR N WaveCity Center,89,142,61,42.96,61.27,NaN,116.0,446.0,193.0,35,0.00,30.99,18.31,7.75,0,44,26,11
116,test,viewed,play_click,morning,Other_clusters,6853,10613,5033,47.42,65.67,114.0,128.0,287.0,161.0,16,1.33,21.71,17.96,11.29,141,2304,1906,1198
117,test,viewed,play_click,rest_evening,Dashrathpuri_Del_East,87,125,59,47.20,70.40,99.0,106.0,415.0,198.0,23,1.60,19.20,22.40,8.80,2,24,28,11
118,test,viewed,play_click,rest_evening,Dwarka_Del,28,41,18,43.90,51.22,65.0,128.0,229.0,124.0,12,2.44,24.39,4.88,21.95,1,10,2,9
119,test,viewed,play_click,rest_evening,Gurgaon Rural,24,32,14,43.75,81.25,37.0,200.0,424.0,319.0,25,3.13,6.25,34.38,9.38,1,2,11,3
120,test,viewed,play_click,rest_evening,NCR G Vijay Nagar 2,42,61,33,54.10,68.85,NaN,169.0,318.0,171.0,12,0.00,21.31,13.11,9.84,0,13,8,6
121,test,viewed,play_click,rest_evening,NCR N Gharoli,89,130,63,48.46,76.92,76.0,153.0,397.0,256.0,17,2.31,14.62,26.92,6.15,3,19,35,8
122,test,viewed,play_click,rest_evening,NCR N Sharda University 2,16,22,8,36.36,54.55,58.0,176.0,236.0,82.0,6,18.18,18.18,13.64,9.09,4,4,3,2
123,test,viewed,play_click,rest_evening,NCR N Venice Mall,19,29,11,37.93,62.07,128.0,82.0,412.0,128.0,7,6.90,24.14,24.14,6.90,2,7,7,2
124,test,viewed,play_click,rest_evening,NCR N WaveCity Center,32,36,22,61.11,91.67,NaN,72.0,519.0,88.0,16,0.00,8.33,27.78,0.00,0,3,10,0
125,test,viewed,play_click,rest_evening,Other_clusters,4160,6289,2789,44.35,67.16,84.0,124.0,343.0,186.0,19,2.24,19.13,22.17,11.31,141,1203,1394,711
126,test,viewed,play_click,rest_morning,Dashrathpuri_Del_East,82,128,66,51.56,67.97,NaN,176.0,506.0,209.0,14,0.00,27.34,16.41,4.69,0,35,21,6
127,test,viewed,play_click,rest_morning,Dwarka_Del,22,28,11,39.29,60.71,NaN,112.0,203.0,165.0,13,0.00,10.71,21.43,28.57,0,3,6,8
128,test,viewed,play_click,rest_morning,Gurgaon Rural,22,31,15,48.39,70.97,NaN,174.0,312.0,206.0,16,0.00,19.35,22.58,9.68,0,6,7,3
129,test,viewed,play_click,rest_morning,NCR G Vijay Nagar 2,46,66,36,54.55,81.82,NaN,139.0,211.0,144.0,9,0.00,16.67,27.27,1.52,0,11,18,1
130,test,viewed,play_click,rest_morning,NCR N Gharoli,55,87,40,45.98,64.37,10.0,144.0,528.0,179.0,11,1.15,22.99,18.39,11.49,1,20,16,10
131,test,viewed,play_click,rest_morning,NCR N Sharda University 2,4,4,3,75.00,100.00,NaN,NaN,240.0,240.0,8,0.00,0.00,25.00,0.00,0,0,1,0
132,test,viewed,play_click,rest_morning,NCR N Venice Mall,33,72,16,22.22,29.17,165.0,113.0,201.0,147.0,11,25.00,23.61,6.94,22.22,18,17,5,16
133,test,viewed,play_click,rest_morning,NCR N WaveCity Center,23,34,16,47.06,64.71,188.0,175.0,391.0,188.0,7,2.94,17.65,17.65,14.71,1,6,6,5
134,test,viewed,play_click,rest_morning,Other_clusters,3283,5692,2205,38.74,60.03,114.0,135.0,323.0,173.0,14,4.69,21.66,20.70,13.62,267,1233,1178,775

In [193]:
overall_cluster_session.to_clipboard(index=False)

In [186]:
city_benchmark=f"""
with rr_net AS (
    SELECT 
        yyyymmdd, 
        customer_id,
        order_id, 
        order_status, 
        modified_order_status, 
        spd_fraud_flag,
        quarter_hour,
        CASE 
            WHEN pickup_cluster IN (
                'Gurgaon Rural', 
                'NCR N sec 6354', 
                'Dashrathpuri_Del_East', 
                'NCR N sec 2262', 
                'NCR N Sharda University 2', 
                'NCR N Gharoli', 
                'NCR G Vijay Nagar 2', 
                'NCR N Venice Mall', 
                'Dwarka_Del', 
                'NCR N WaveCity Center'
            ) THEN pickup_cluster
            ELSE 'Other_clusters'
        END AS cluster_name,
        CASE 
            WHEN modified_order_status IN ('OCARA', 'COBRA', 'COBRM') 
            THEN (customer_cancelled_epoch / 1000 - order_requested_epoch / 1000) 
        END AS time_spent_in_sec,
        CASE 
            WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') 
            THEN (rider_accepted_epoch / 1000 - order_requested_epoch / 1000)
        END AS time_taken_to_accp,
        case when SUBSTR(customer_id, -1) in ('1','3','5','7','9','e','a','d') then 'test' else 'control' end as test_group
    
    FROM 
        orders.order_logs_fact fact
    WHERE 
         yyyymmdd >= '20240911' AND yyyymmdd <= '20240916'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city_name = 'Delhi'
        AND service_obj_service_name in ('Auto','Auto Lite','Auto NCR','Auto Pool','AutoPremium','CityAuto','Link','Bike Lite','Bike Pink','CabEconomy','Bike Metro', 'CabPremium')
        AND channel_host='android'
        and customer_id in(
                select
                    user_id
        from 
            clevertap.clevertap_customer_order_activity
        where 
            yyyymmdd >= '20240911' AND yyyymmdd <= '20240916'
            AND order_activity_source = 'appOpen'
            and current_city = 'Delhi'
            and platform='Android'
            and app_version>='8.30.0'
            
            
            )
)








SELECT
        
        cluster_name,
        customers,

        gross_count,
        net_count,
        
        COALESCE(TRY(net_count*100.00/gross_count), 0) g2n,
        
        COALESCE(TRY(tot_accepted*100.00/gross_count), 0) "aor",
        
        
        median_cobrm_time,
        median_cobra_time,
        median_ocara_time,
        median_cancellation_time,
        median_acceptance_time,
        
        COALESCE(TRY(cobrm*100.00/gross_count), 0) "% cobrm",
        COALESCE(TRY(cobra*100.00/gross_count), 0) "% cobra",
        COALESCE(TRY(ocara*100.00/gross_count), 0) "% ocara",
        COALESCE(TRY(expired*100.00/gross_count), 0) "% expired",
        cobrm, 
        cobra,
        ocara,
        expired
    FROM    
        (
        SELECT
            cluster_name,
            COUNT(DISTINCT customer_id) customers,
            COUNT(DISTINCT order_id) gross_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' AND spd_fraud_flag != true THEN order_id END) net_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN order_id END) AS tot_accepted,

                    
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRM' THEN order_id END) cobrm,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRA' THEN order_id END) cobra,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'OCARA' THEN order_id END) ocara,
            COUNT(DISTINCT CASE WHEN order_status = 'expired' THEN order_id END) expired,
            
            approx_percentile(CASE WHEN modified_order_status = 'COBRM' THEN time_spent_in_sec END,0.50) as median_cobrm_time,
            approx_percentile(CASE WHEN modified_order_status = 'COBRA' THEN time_spent_in_sec END,0.50) as median_cobra_time,
            approx_percentile(CASE WHEN modified_order_status = 'OCARA' THEN time_spent_in_sec END,0.50) as median_ocara_time,
            approx_percentile(CASE WHEN modified_order_status in ('COBRA','COBRM','OCARA') THEN time_spent_in_sec END,0.50) as median_cancellation_time,
            approx_percentile(CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN time_taken_to_accp END,0.50) as median_acceptance_time
            
        FROM 
            rr_net
        where 
            yyyymmdd is not null
           
        GROUP BY 1
        )
    ORDER BY 1
    
"""

city_benchmark_df=pd.read_sql(city_benchmark,conn)

/var/folders/km/1ltm54y105x6dzlcf44g881c0000gn/T/ipykernel_31458/3457448014.py:127: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  city_benchmark_df=pd.read_sql(city_benchmark,conn)

In [187]:
city_benchmark_df

,cluster_name,customers,gross_count,net_count,g2n,aor,median_cobrm_time,median_cobra_time,median_ocara_time,median_cancellation_time,median_acceptance_time,% cobrm,% cobra,% ocara,% expired,cobrm,cobra,ocara,expired
0,Dashrathpuri_Del_East,21963,49745,24594,49.44,68.05,110,136,343,186,18,0.59,21.09,18.30,10.26,293,10489,9103,5104
1,Dwarka_Del,6807,14768,8369,56.67,72.68,116,141,318,182,12,0.91,17.65,15.59,8.71,134,2607,2303,1287
2,Gurgaon Rural,10184,24206,11306,46.71,63.46,99,132,306,169,15,0.43,23.08,16.56,13.02,103,5587,4008,3152
3,NCR G Vijay Nagar 2,15108,31759,20789,65.46,82.94,82,132,276,179,11,0.68,12.49,17.05,3.88,216,3967,5414,1233
4,NCR N Gharoli,20586,43528,25924,59.56,79.88,101,130,321,199,14,0.54,14.03,19.86,5.53,237,6106,8644,2409
5,NCR N Sharda University 2,16499,47285,14783,31.26,44.85,82,109,264,126,10,1.30,37.65,13.19,16.19,616,17801,6238,7657
6,NCR N Venice Mall,11798,33623,13178,39.19,54.00,100,118,282,138,9,5.81,27.90,14.27,12.29,1952,9380,4799,4131
7,NCR N WaveCity Center,8797,17596,10641,60.47,80.77,98,127,306,192,11,0.83,13.40,19.93,4.99,146,2357,3507,878
8,Other_clusters,808280,2732646,1323003,48.41,66.87,107,132,311,176,14,1.65,19.92,18.08,11.54,45170,544351,494092,315265

In [191]:
city_benchmark_df.to_clipboard(index=False)

In [188]:
city_benchmark_s_c=f"""
with rr_net AS (
    SELECT 
        yyyymmdd, 
        customer_id,
        order_id, 
        order_status, 
        modified_order_status, 
        spd_fraud_flag,
        quarter_hour,
        CASE 
            WHEN pickup_cluster IN (
                'Gurgaon Rural', 
                'NCR N sec 6354', 
                'Dashrathpuri_Del_East', 
                'NCR N sec 2262', 
                'NCR N Sharda University 2', 
                'NCR N Gharoli', 
                'NCR G Vijay Nagar 2', 
                'NCR N Venice Mall', 
                'Dwarka_Del', 
                'NCR N WaveCity Center'
            ) THEN pickup_cluster
            ELSE 'Other_clusters'
        END AS cluster_name,
        CASE 
            WHEN modified_order_status IN ('OCARA', 'COBRA', 'COBRM') 
            THEN (customer_cancelled_epoch / 1000 - order_requested_epoch / 1000) 
        END AS time_spent_in_sec,
        CASE 
            WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') 
            THEN (rider_accepted_epoch / 1000 - order_requested_epoch / 1000)
        END AS time_taken_to_accp,
        case when SUBSTR(customer_id, -1) in ('1','3','5','7','9','e','a','d') then 'test' else 'control' end as test_group
    
    FROM 
        orders.order_logs_fact fact
    WHERE 
         yyyymmdd >= '20240911' AND yyyymmdd <= '20240916'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city_name = 'Delhi'
        AND service_obj_service_name in ('Auto','Auto Lite','Auto NCR','Auto Pool','AutoPremium','CityAuto','Link','Bike Lite','Bike Pink','CabEconomy','Bike Metro', 'CabPremium')
        AND channel_host='android'
        and customer_id in(
                select
                    user_id
        from 
            clevertap.clevertap_customer_order_activity
        where 
            yyyymmdd >= '20240911' AND yyyymmdd <= '20240916'
            AND order_activity_source = 'appOpen'
            and current_city = 'Delhi'
            and platform='Android'
            and app_version>='8.30.0'
            
            
            )
)



SELECT
        time_period,
        cluster_name,
        customers,

        gross_count,
        net_count,
        
        COALESCE(TRY(net_count*100.00/gross_count), 0) g2n,
        
        COALESCE(TRY(tot_accepted*100.00/gross_count), 0) "aor",
        
        
        median_cobrm_time,
        median_cobra_time,
        median_ocara_time,
        median_cancellation_time,
        median_acceptance_time,
        
        COALESCE(TRY(cobrm*100.00/gross_count), 0) "% cobrm",
        COALESCE(TRY(cobra*100.00/gross_count), 0) "% cobra",
        COALESCE(TRY(ocara*100.00/gross_count), 0) "% ocara",
        COALESCE(TRY(expired*100.00/gross_count), 0) "% expired",
        cobrm, 
        cobra,
        ocara,
        expired
    FROM    
        (
        SELECT
            case
                WHEN quarter_hour >= '0800' AND quarter_hour < '1100' THEN 'morning'
                WHEN quarter_hour >= '1100' AND quarter_hour < '1700' THEN 'afternoon'
                WHEN quarter_hour >= '1700' AND quarter_hour < '2100' THEN 'evening'
                WHEN quarter_hour >= '0000' AND quarter_hour < '0800' THEN 'rest_morning'
                ELSE 'rest_evening'
            end as time_period,
            cluster_name,
            COUNT(DISTINCT customer_id) customers,
            COUNT(DISTINCT order_id) gross_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' AND spd_fraud_flag != true THEN order_id END) net_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN order_id END) AS tot_accepted,

                    
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRM' THEN order_id END) cobrm,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRA' THEN order_id END) cobra,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'OCARA' THEN order_id END) ocara,
            COUNT(DISTINCT CASE WHEN order_status = 'expired' THEN order_id END) expired,
            
            approx_percentile(CASE WHEN modified_order_status = 'COBRM' THEN time_spent_in_sec END,0.50) as median_cobrm_time,
            approx_percentile(CASE WHEN modified_order_status = 'COBRA' THEN time_spent_in_sec END,0.50) as median_cobra_time,
            approx_percentile(CASE WHEN modified_order_status = 'OCARA' THEN time_spent_in_sec END,0.50) as median_ocara_time,
            approx_percentile(CASE WHEN modified_order_status in ('COBRA','COBRM','OCARA') THEN time_spent_in_sec END,0.50) as median_cancellation_time,
            approx_percentile(CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN time_taken_to_accp END,0.50) as median_acceptance_time
            
        FROM 
            rr_net
        where 
            yyyymmdd is not null
           
        GROUP BY 1,2
        )
    ORDER BY 1,2
    
"""

city_benchmark_s_c_df=pd.read_sql(city_benchmark_s_c,conn)

/var/folders/km/1ltm54y105x6dzlcf44g881c0000gn/T/ipykernel_31458/3988337630.py:129: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  city_benchmark_s_c_df=pd.read_sql(city_benchmark_s_c,conn)

In [169]:
city_benchmark_s_c_df

,time_period,cluster_name,customers,gross_count,net_count,g2n,aor,median_cobrm_time,median_cobra_time,median_ocara_time,median_cancellation_time,median_acceptance_time,% cobrm,% cobra,% ocara,% expired,cobrm,cobra,ocara,expired
0,afternoon,Gurgaon Rural,4683,8827,4261,48.27,65.82,97,129,342,176,16,0.24,22.82,17.36,11.12,21,2014,1532,982
1,afternoon,NCR N Gharoli,7834,11781,8528,72.39,92.36,93,108,302,230,10,0.31,5.35,19.43,1.98,37,630,2289,233
2,afternoon,NCR N Sharda University 2,9633,20524,7282,35.48,49.29,60,108,245,126,9,0.39,35.92,13.35,14.40,80,7372,2740,2955
3,afternoon,NCR N sec 22/62,5217,7748,6070,78.34,94.00,69,80,246,175,10,0.28,4.57,15.14,1.15,22,354,1173,89
4,afternoon,Other_clusters,382059,791101,452796,57.24,76.85,107,128,309,185,11,1.34,13.87,19.21,7.94,10582,109742,151978,62835
5,afternoon,Sec-10A,3659,6938,3176,45.78,62.90,50,136,332,174,14,0.25,23.28,16.86,13.58,17,1615,1170,942
6,afternoon,Sec-39,4393,7301,4578,62.70,81.56,109,130,275,183,11,0.19,12.14,18.59,6.11,14,886,1357,446
7,afternoon,Sec-55,3681,6365,3972,62.40,82.61,131,117,280,182,11,0.39,11.28,19.97,5.72,25,718,1271,364
8,afternoon,Sec-57,5709,9801,6027,61.49,80.98,89,126,277,180,11,0.45,12.34,19.21,6.23,44,1209,1883,611
9,afternoon,Sector 45-46,4835,7691,5278,68.63,87.23,54,118,278,190,11,0.27,9.34,18.41,3.16,21,718,1416,243
10,evening,Gurgaon Rural,3159,5680,2884,50.77,69.00,82,125,291,164,10,0.44,19.47,18.05,11.07,25,1106,1025,629
11,evening,NCR N Gharoli,6953,13150,6551,49.82,70.74,53,131,332,191,18,0.26,19.65,20.54,9.33,34,2584,2701,1227
12,evening,NCR N Sharda University 2,7481,19014,3691,19.41,30.39,60,109,310,123,16,0.94,46.51,10.70,22.16,179,8843,2034,4213
13,evening,NCR N sec 22/62,6257,13669,5978,43.73,60.30,82,132,333,173,26,0.10,27.87,16.22,11.70,13,3809,2217,1599
14,evening,Other_clusters,357749,860545,335648,39.00,56.55,104,134,324,171,17,1.66,24.93,17.21,16.83,14293,214571,148077,144787
15,evening,Sec-10A,2429,4448,1886,42.40,60.05,104,133,304,168,12,0.49,23.34,17.49,16.10,22,1038,778,716
16,evening,Sec-39,4355,10017,4025,40.18,53.98,88,135,278,159,15,0.32,25.95,13.64,19.73,32,2599,1366,1976
17,evening,Sec-55,3865,9397,3507,37.32,52.42,84,136,296,165,16,0.56,27.99,14.83,19.03,53,2630,1394,1788
18,evening,Sec-57,5017,10924,4667,42.72,58.19,62,140,282,172,13,0.35,22.78,15.27,18.66,38,2488,1668,2038
19,evening,Sector 45-46,5841,12817,5503,42.94,57.75,100,131,282,160,20,0.26,25.83,14.63,16.16,33,3310,1875,2071
20,morning,Gurgaon Rural,2881,6450,2568,39.81,53.53,131,144,293,168,22,0.25,28.25,13.61,17.97,16,1822,878,1159
21,morning,NCR N Gharoli,5414,10915,6521,59.74,78.13,104,131,330,188,18,0.39,16.60,18.04,4.87,43,1812,1969,532
22,morning,NCR N Sharda University 2,3044,5160,2726,52.83,73.93,94,106,229,142,7,0.85,20.33,20.54,4.88,44,1049,1060,252
23,morning,NCR N sec 22/62,3351,7632,4961,65.00,78.13,66,138,292,175,13,0.20,16.73,12.68,4.94,15,1277,968,377
24,morning,Other_clusters,240723,529861,278911,52.64,69.31,109,132,288,167,15,1.18,20.25,16.38,9.26,6243,107294,86780,49043
25,morning,Sec-10A,2587,5097,2750,53.95,73.10,118,129,264,167,16,0.12,17.79,18.91,8.99,6,907,964,458
26,morning,Sec-39,3666,8379,4840,57.76,74.34,137,132,245,166,17,0.23,17.16,16.41,8.27,19,1438,1375,693
27,morning,Sec-55,2701,6129,3274,53.42,70.53,63,147,246,177,15,0.29,18.60,17.00,10.57,18,1140,1042,648
28,morning,Sec-57,4330,11055,5098,46.11,62.12,96,136,239,159,18,0.17,23.95,15.87,13.76,19,2648,1754,1521
29,morning,Sector 45-46,4300,10395,5948,57.22,73.75,142,129,231,161,17,0.15,17.40,16.27,8.70,16,1809,1691,904
30,rest_evening,Gurgaon Rural,866,1410,648,45.96,67.52,96,115,254,158,11,0.92,19.57,21.13,11.84,13,276,298,167
31,rest_evening,NCR N Gharoli,2214,3389,1913,56.45,80.79,80,128,342,217,16,0.62,13.57,23.34,4.87,21,460,791,165
32,rest_evening,NCR N Sharda University 2,839,1353,667,49.30,67.41,90,111,248,139,9,5.54,18.85,17.52,8.20,75,255,237,111
33,rest_evening,NCR N sec 22/62,1300,2144,1207,56.30,74.63,68,114,273,148,14,2.33,18.10,17.77,4.85,50,388,381,104
34,rest_evening,Other_clusters,139691,255474,119626,46.83,68.45,96,129,329,181,17,1.95,20.09,21.00,9.36,4992,51336,53637,23922
35,rest_evening,Sec-10A,717,1231,486,39.48,60.52,105,125,269,161,11,1.95,21.36,20.23,15.84,24,263,249,195
36,rest_evening,Sec-39,1240,1989,1123,56.46,77.02,122,116,250,165,11,0.96,14.78,19.91,7.19,19,294,396,143
37,rest_evening,Sec-55,1115,1802,943,52.33,71.42,125,119,301,161,11,1.22,19.03,18.42,8.32,22,343,332,150
38,rest_evening,Sec-57,1381,2257,1233,54.63,75.76,71,123,248,164,10,1.82,14.71,20.65,7.67,41,332,466,173
39,rest_evening,Sector 45-46,1524,2513,1419,56.47,75.73,65,116,261,156,12,1.03,15.80,18.94,7.36,26,397,476,185
40,rest_morning,Gurgaon Rural,967,1839,945,51.39,66.72,127,130,258,155,12,1.52,20.07,14.95,11.69,28,369,275,215
41,rest_morning,NCR N Gharoli,2414,4293,2411,56.16,77.31,117,140,293,187,11,2.38,14.44,20.82,5.87,102,620,894,252
42,rest_morning,NCR N Sharda University 2,633,1234,417,33.79,47.65,99,120,273,127,7,19.29,22.85,13.53,10.21,238,282,167,126
43,rest_morning,NCR N sec 22/62,1303,2507,1352,53.93,70.20,102,139,253,155,10,3.23,19.39,15.88,7.18,81,486,398,180
44,rest_morning,Other_clusters,129607,261217,118192,45.25,64.33,113,139,317,175,13,4.10,21.00,18.71,10.57,10712,54856,48864,27612
45,rest_morning,Sec-10A,919,1795,944,52.59,70.70,167,128,200,151,10,2.12,16.16,17.60,11.03,38,290,316,198
46,rest_morning,Sec-39,1254,2358,1308,55.47,69.68,98,131,297,156,11,1.65,19.08,13.91,9.58,39,450,328,226
47,rest_morning,Sec-55,1075,2181,1079,49.47,65.80,104,131,264,153,13,5.23,19.99,15.96,8.99,114,436,348,196
48,rest_morning,Sec-57,1439,2748,1454,52.91,68.38,104,126,251,144,9,4.84,18.34,15.32,8.44,133,504,421,232
49,rest_morning,Sector 45-46,1341,2611,1315,50.36,66.14,92,129,258,149,11,2.87,22.06,15.66,8.92,75,576,409,233

In [192]:
city_benchmark_s_c_df.to_clipboard(index=False)

In [18]:
click_bucket=f"""
with olf as (

    SELECT
        yyyymmdd,
        customer_id,
        order_id,
        order_requested_epoch,
        customer_cancelled_epoch,
        dropped_epoch,
        expired_epoch,
        rider_accepted_epoch
        
    FROM 
        orders.order_logs_fact
    WHERE
        yyyymmdd >= '20240911' AND yyyymmdd <= '20240916'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city_name = 'Delhi'
        
    ),




click as(
select
           yyyymmdd,
           profile_identity as user_id,
            epoch as click_epoch
        from
            clevertap.customer_notification_clicked_immutable 
        where yyyymmdd >= '20240911' AND yyyymmdd <= '20240916' 
        and event_props_wzrk_c2a='Button 2'
        and event_props_campaign_id = '1725970812' 
        
        -- group by 1,2
        
),


merge AS (
    
    SELECT 
        olf.*,
        click_epoch,
        (click_epoch / 1000 - order_requested_epoch / 1000) time_to_click
        --row_number() over(partition by olf.yyyymmdd,olf.customer_id,olf.order_id order by click_epoch) seq_no
    FROM 
        olf
    JOIN 
        click
        on olf.yyyymmdd = click.yyyymmdd
        and olf.customer_id = click.user_id
        and olf.order_requested_epoch < click.click_epoch
        and (olf.customer_cancelled_epoch > click.click_epoch or dropped_epoch > click.click_epoch or 
        expired_epoch > click.click_epoch or rider_accepted_epoch> click.click_epoch)
    )
    
    
   
    
    
    SELECT
        
        case 
        when time_to_click <= 15 then 'a. 15 Sec'
        when time_to_click between 16 and 30 then 'b. 16-30 Sec'
        when time_to_click between 31 and 60 then 'c. 30-60 Sec'
        when time_to_click between 61 and 120 then 'd. 1-2 min'
        when time_to_click between 121 and 240 then 'e. 3-4 min'
        when time_to_click > 240 then 'f. 4+ min' 
        else 'check' end as click_bucket,
        count(distinct customer_id) customers
    FROM 
        merge
    -- WHERE 
    --     --seq_no = 1
    GROUP BY 1
    ORDER BY 1

"""
click_bucket_df = pd.read_sql(click_bucket,conn)

/var/folders/j7/5rtfb17j30s9g9q790v9nr0h0000gn/T/ipykernel_62370/3278354793.py:84: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  click_bucket_df = pd.read_sql(click_bucket,conn)

In [20]:
click_bucket_df

   click_bucket  customers
0     a. 15 Sec      27299
1  b. 16-30 Sec       3613
2  c. 30-60 Sec       1438
3    d. 1-2 min        865
4    e. 3-4 min        659
5     f. 4+ min        519

In [24]:
click_bucket_df.to_clipboard(index=False)

In [22]:
32360-34393

-2033

In [23]:
27299-2033

25266

In [21]:
click_bucket_df.customers.sum()

34393

In [204]:
total_customers = click_bucket_df['customers'].sum()

# Calculate the percentage of customers for each click_bucket
click_bucket_df['customer_percentage'] = (click_bucket_df['customers'] / total_customers) * 100

# Round the percentage to 2 decimal places
click_bucket_df['customer_percentage'] = click_bucket_df['customer_percentage'].round(2)