In [1]:
import re
import os 
import pandas as pd
import matplotlib.pyplot as plt 
import numpy as np
from pyhive import presto
from datetime import date
from collections import Counter

from scipy import stats
from pyhive import presto
from datetime import datetime, timedelta

presto_port = '80'
username = 'manoj.ravirajan@rapido.bike'

conn=presto.connect('presto-gateway.processing.data.production.internal',presto_port,username)

connection1 = presto.connect('bi-presto.serving.data.production.internal', presto_port, username)
connection2 = presto.connect('bi-trino-2.serving.data.production.internal', presto_port, username)
connection3= presto.connect('processing-2.processing.data.production.internal',presto_port,username)
connection4= presto.connect('processing.processing.data.production.internal',presto_port,username)


pd.set_option('display.max_columns', None)

## Overall

In [2]:
overall_query=f"""
with exp_category as(
select
    userid as user_id,
    case    when name='CaptainSearchSportsNewsTest' then 'test' 
            else 'control'
    end as test_group
from
   canonical.user_selector
where
    yyyymmdd = '20240905'
    and selectorid in ('66d9e70d8e21590001b635ac','66d9e97fdac1090001c05d83')

),

rr_net AS (
    SELECT 
        yyyymmdd, 
        customer_id,
        order_id, 
        order_status, 
        modified_order_status, 
        spd_fraud_flag,
        quarter_hour,
        CASE 
            WHEN modified_order_status IN ('OCARA', 'COBRA', 'COBRM') 
            THEN (customer_cancelled_epoch / 1000 - order_requested_epoch / 1000) 
        END AS time_spent_in_sec,
        CASE 
            WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') 
            THEN (rider_accepted_epoch / 1000 - order_requested_epoch / 1000)
        END AS time_taken_to_accp
        
    
    FROM 
        orders.order_logs_fact fact
    WHERE 
         yyyymmdd >= '20240911' AND yyyymmdd <= '20240916'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city_name = 'Hyderabad'
        AND service_obj_service_name in ('Auto','Auto Lite','Auto NCR','Auto Pool','AutoPremium','CityAuto','Link','Bike Lite','Bike Pink','CabEconomy','Bike Metro', 'CabPremium')
        AND channel_host='android'
        and customer_id in(
                select
                    user_id
        from 
            clevertap.clevertap_customer_order_activity
        where 
            yyyymmdd >= '20240911' AND yyyymmdd <= '20240916'
            AND order_activity_source = 'appOpen'
            and current_city = 'Hyderabad'
            and platform='Android'
            and app_version>='8.30.0'           
            )
         
),

view_tbl as(

    select
        yyyymmdd,
        profile_identity as user_id,
        'viewed' as event_type
    from 
        clevertap.customer_notification_viewed_immutable 
    where yyyymmdd >= '20240911' and yyyymmdd<='20240916'
    and event_props_campaign_id = '1725971334'

),

click_tbl as(
    select
        yyyymmdd,
        profile_identity as user_id,
        CASE
                    when event_props_wzrk_c2a='Button 2' then 'play_click'
                    else 'close_click'
        end as click_type
    from 
        clevertap.customer_notification_clicked_immutable
    where yyyymmdd >= '20240911' and yyyymmdd<='20240916'
    and event_props_campaign_id = '1725971334'

),
merge as(
    select exp_category.*,
            rr_net.yyyymmdd,
            rr_net.order_id,
            rr_net.order_status,
            rr_net.modified_order_status,
            rr_net.spd_fraud_flag,
            rr_net.quarter_hour,
            rr_net.time_spent_in_sec,
            rr_net.time_taken_to_accp,
            view_tbl.event_type,
            click_tbl.click_type
    from
        exp_category
    left join 
            rr_net 
        on exp_category.user_id=rr_net.customer_id
    left join
            view_tbl
        on rr_net.customer_id=view_tbl.user_id
           and rr_net.yyyymmdd=view_tbl.yyyymmdd
    left join
            click_tbl
        on view_tbl.user_id=click_tbl.user_id
        and view_tbl.yyyymmdd=click_tbl.yyyymmdd

)

SELECT
        test_group,
        -- event_type,
        -- click_type,
        customers,

        gross_count,
        net_count,
        
        COALESCE(TRY(net_count*100.00/gross_count), 0) g2n,
        
        COALESCE(TRY(tot_accepted*100.00/gross_count), 0) "aor",
        
        
        median_cobrm_time,
        median_cobra_time,
        median_ocara_time,
        median_cancellation_time,
        median_acceptance_time,
        
        COALESCE(TRY(cobrm*100.00/gross_count), 0) "% cobrm",
        COALESCE(TRY(cobra*100.00/gross_count), 0) "% cobra",
        COALESCE(TRY(ocara*100.00/gross_count), 0) "% ocara",
        COALESCE(TRY(expired*100.00/gross_count), 0) "% expired",
        cobrm, 
        cobra,
        ocara,
        expired
    FROM    
        (
        SELECT
            test_group,
            -- event_type,
            -- click_type,
            COUNT(DISTINCT user_id) customers,
            COUNT(DISTINCT order_id) gross_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' AND spd_fraud_flag != true THEN order_id END) net_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN order_id END) AS tot_accepted,

        
           
            
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRM' THEN order_id END) cobrm,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRA' THEN order_id END) cobra,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'OCARA' THEN order_id END) ocara,
            COUNT(DISTINCT CASE WHEN order_status = 'expired' THEN order_id END) expired,
            
            approx_percentile(CASE WHEN modified_order_status = 'COBRM' THEN time_spent_in_sec END,0.50) as median_cobrm_time,
            approx_percentile(CASE WHEN modified_order_status = 'COBRA' THEN time_spent_in_sec END,0.50) as median_cobra_time,
            approx_percentile(CASE WHEN modified_order_status = 'OCARA' THEN time_spent_in_sec END,0.50) as median_ocara_time,
            approx_percentile(CASE WHEN modified_order_status in ('COBRA','COBRM','OCARA') THEN time_spent_in_sec END,0.50) as median_cancellation_time,
            approx_percentile(CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN time_taken_to_accp END,0.50) as median_acceptance_time
            
        FROM 
            merge
        where 
            yyyymmdd is not null
           and NOT (test_group = 'control' AND event_type IS NOT NULL)
           and NOT (event_type IS NULL AND click_type IS NOT NULL)
        GROUP BY 1
        )
    ORDER BY 1,2,3

"""

overall_sports=pd.read_sql(overall_query,conn)

/var/folders/j7/5rtfb17j30s9g9q790v9nr0h0000gn/T/ipykernel_62376/2332381144.py:179: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  overall_sports=pd.read_sql(overall_query,conn)

In [10]:
overall_sports

,test_group,customers,gross_count,net_count,g2n,aor,median_cobrm_time,median_cobra_time,median_ocara_time,median_cancellation_time,median_acceptance_time,% cobrm,% cobra,% ocara,% expired,cobrm,cobra,ocara,expired
0,control,49649,146295,100582,68.75,85.58,83,108,255,159,10,0.59,10.66,16.39,3.16,860,15601,23981,4628
1,test,49282,148749,102576,68.96,85.71,66,108,245,157,10,0.63,10.45,16.32,3.20,941,15538,24271,4761

In [11]:
overall_sports.to_clipboard(index=False)

In [5]:
overall_query=f"""
with exp_category as(
select
    userid as user_id,
    case    when name='CaptainSearchSportsNewsTest' then 'test' 
            else 'control'
    end as test_group
from
   canonical.user_selector
where
    yyyymmdd = '20240905'
    and selectorid in ('66d9e70d8e21590001b635ac','66d9e97fdac1090001c05d83')

),

rr_net AS (
    SELECT 
        yyyymmdd, 
        customer_id,
        order_id, 
        order_status, 
        modified_order_status, 
        spd_fraud_flag,
        quarter_hour,
        CASE 
            WHEN modified_order_status IN ('OCARA', 'COBRA', 'COBRM') 
            THEN (customer_cancelled_epoch / 1000 - order_requested_epoch / 1000) 
        END AS time_spent_in_sec,
        CASE 
            WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') 
            THEN (rider_accepted_epoch / 1000 - order_requested_epoch / 1000)
        END AS time_taken_to_accp
        
    
    FROM 
        orders.order_logs_fact fact
    WHERE 
         yyyymmdd >= '20240911' AND yyyymmdd <= '20240916'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city_name = 'Hyderabad'
        AND service_obj_service_name in ('Auto','Auto Lite','Auto NCR','Auto Pool','AutoPremium','CityAuto','Link','Bike Lite','Bike Pink','CabEconomy','Bike Metro', 'CabPremium')
        AND channel_host='android'
        and customer_id in(
                select
                    user_id
        from 
            clevertap.clevertap_customer_order_activity
        where 
            yyyymmdd >= '20240911' AND yyyymmdd <= '20240916'
            AND order_activity_source = 'appOpen'
            and current_city = 'Hyderabad'
            and platform='Android'
            and app_version>='8.30.0'           
            )
         
),

view_tbl as(

    select
        yyyymmdd,
        profile_identity as user_id,
        'viewed' as event_type
    from 
        clevertap.customer_notification_viewed_immutable 
    where yyyymmdd >= '20240911' and yyyymmdd<='20240916'
    and event_props_campaign_id = '1725971334'

),

click_tbl as(
    select
        yyyymmdd,
        profile_identity as user_id,
        CASE
                    when event_props_wzrk_c2a='Button 2' then 'play_click'
                    else 'close_click'
        end as click_type
    from 
        clevertap.customer_notification_clicked_immutable
    where yyyymmdd >= '20240911' and yyyymmdd<='20240916'
    and event_props_campaign_id = '1725971334'

),
merge as(
    select exp_category.*,
            rr_net.yyyymmdd,
            rr_net.order_id,
            rr_net.order_status,
            rr_net.modified_order_status,
            rr_net.spd_fraud_flag,
            rr_net.quarter_hour,
            rr_net.time_spent_in_sec,
            rr_net.time_taken_to_accp,
            view_tbl.event_type,
            click_tbl.click_type
    from
        exp_category
    left join 
            rr_net 
        on exp_category.user_id=rr_net.customer_id
    left join
            view_tbl
        on rr_net.customer_id=view_tbl.user_id
           and rr_net.yyyymmdd=view_tbl.yyyymmdd
    left join
            click_tbl
        on view_tbl.user_id=click_tbl.user_id
        and view_tbl.yyyymmdd=click_tbl.yyyymmdd

)

SELECT
        test_group,
        event_type,
        click_type,
        customers,

        gross_count,
        net_count,
        
        COALESCE(TRY(net_count*100.00/gross_count), 0) g2n,
        
        COALESCE(TRY(tot_accepted*100.00/gross_count), 0) "aor",
        
        
        median_cobrm_time,
        median_cobra_time,
        median_ocara_time,
        median_cancellation_time,
        median_acceptance_time,
        
        COALESCE(TRY(cobrm*100.00/gross_count), 0) "% cobrm",
        COALESCE(TRY(cobra*100.00/gross_count), 0) "% cobra",
        COALESCE(TRY(ocara*100.00/gross_count), 0) "% ocara",
        COALESCE(TRY(expired*100.00/gross_count), 0) "% expired",
        cobrm, 
        cobra,
        ocara,
        expired
    FROM    
        (
        SELECT
            test_group,
            event_type,
            click_type,
            COUNT(DISTINCT user_id) customers,
            COUNT(DISTINCT order_id) gross_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' AND spd_fraud_flag != true THEN order_id END) net_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN order_id END) AS tot_accepted,

        
           
            
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRM' THEN order_id END) cobrm,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRA' THEN order_id END) cobra,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'OCARA' THEN order_id END) ocara,
            COUNT(DISTINCT CASE WHEN order_status = 'expired' THEN order_id END) expired,
            
            approx_percentile(CASE WHEN modified_order_status = 'COBRM' THEN time_spent_in_sec END,0.50) as median_cobrm_time,
            approx_percentile(CASE WHEN modified_order_status = 'COBRA' THEN time_spent_in_sec END,0.50) as median_cobra_time,
            approx_percentile(CASE WHEN modified_order_status = 'OCARA' THEN time_spent_in_sec END,0.50) as median_ocara_time,
            approx_percentile(CASE WHEN modified_order_status in ('COBRA','COBRM','OCARA') THEN time_spent_in_sec END,0.50) as median_cancellation_time,
            approx_percentile(CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN time_taken_to_accp END,0.50) as median_acceptance_time
            
        FROM 
            merge
        where 
            yyyymmdd is not null
           and NOT (test_group = 'control' AND event_type IS NOT NULL)
           and NOT (event_type IS NULL AND click_type IS NOT NULL)
        GROUP BY 1,2,3
        )
    ORDER BY 1,2,3

"""

overall_sportsl1=pd.read_sql(overall_query,conn)

/var/folders/j7/5rtfb17j30s9g9q790v9nr0h0000gn/T/ipykernel_62376/3688866530.py:179: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  overall_sportsl1=pd.read_sql(overall_query,conn)

In [12]:
overall_sportsl1

,test_group,event_type,click_type,customers,gross_count,net_count,g2n,aor,median_cobrm_time,median_cobra_time,median_ocara_time,median_cancellation_time,median_acceptance_time,% cobrm,% cobra,% ocara,% expired,cobrm,cobra,ocara,expired
0,control,None,None,49649,146295,100582,68.75,85.58,83,108,255,159,10,0.59,10.66,16.39,3.16,860,15601,23981,4628
1,test,viewed,close_click,36440,104935,72217,68.82,85.41,67,109,247,158,10,0.67,10.66,16.16,3.25,698,11190,16957,3415
2,test,viewed,play_click,2178,4092,2498,61.05,81.84,39,97,203,129,10,0.90,13.42,20.33,3.84,37,549,832,157
3,test,viewed,None,1396,2740,1784,65.11,86.75,41,108,183,141,9,0.84,8.94,21.13,3.43,23,245,579,94
4,test,None,None,15462,37054,26100,70.44,86.90,75,106,248,159,10,0.51,9.61,16.01,2.98,188,3561,5931,1104

In [13]:
overall_sportsl1.to_clipboard(index=False)

In [64]:
overall_sports.to_csv('overall_sports.csv',index=False)

## Pre-post

In [7]:
overall_query=f"""
with exp_category as(
select
    userid as user_id,
    case    when name='CaptainSearchSportsNewsTest' then 'test' 
            else 'control'
    end as test_group
from
   canonical.user_selector
where
    yyyymmdd = '20240905'
    and selectorid in ('66d9e70d8e21590001b635ac','66d9e97fdac1090001c05d83')

),

rr_net AS (
    SELECT 
        yyyymmdd, 
        customer_id,
        order_id, 
        order_status, 
        modified_order_status, 
        spd_fraud_flag,
        quarter_hour,
        CASE 
            WHEN modified_order_status IN ('OCARA', 'COBRA', 'COBRM') 
            THEN (customer_cancelled_epoch / 1000 - order_requested_epoch / 1000) 
        END AS time_spent_in_sec,
        CASE 
            WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') 
            THEN (rider_accepted_epoch / 1000 - order_requested_epoch / 1000)
        END AS time_taken_to_accp
        
    
    FROM 
        orders.order_logs_fact fact
    WHERE 
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240910'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city_name = 'Hyderabad'
        AND service_obj_service_name in ('Auto','Auto Lite','Auto NCR','Auto Pool','AutoPremium','CityAuto','Link','Bike Lite','Bike Pink','CabEconomy','Bike Metro', 'CabPremium')
        AND channel_host='android'
        and customer_id in(
                select
                    user_id
        from 
            clevertap.clevertap_customer_order_activity
        where 
            yyyymmdd >= '20240905' AND yyyymmdd <= '20240910'
            AND order_activity_source = 'appOpen'
            and current_city = 'Hyderabad'
            and platform='Android'
            and app_version>='8.30.0'           
            )
         
),

view_tbl as(

    select
        yyyymmdd,
        profile_identity as user_id,
        'viewed' as event_type
    from 
        clevertap.customer_notification_viewed_immutable 
    where yyyymmdd >= '20240905' AND yyyymmdd <= '20240910'
    and event_props_campaign_id = '1725971334'

),

click_tbl as(
    select
        yyyymmdd,
        profile_identity as user_id,
        CASE
                    when event_props_wzrk_c2a='Button 2' then 'play_click'
                    else 'close_click'
        end as click_type
    from 
        clevertap.customer_notification_clicked_immutable
    where yyyymmdd >= '20240905' AND yyyymmdd <= '20240910'
    and event_props_campaign_id = '1725971334'

),
merge as(
    select exp_category.*,
            rr_net.yyyymmdd,
            rr_net.order_id,
            rr_net.order_status,
            rr_net.modified_order_status,
            rr_net.spd_fraud_flag,
            rr_net.quarter_hour,
            rr_net.time_spent_in_sec,
            rr_net.time_taken_to_accp,
            view_tbl.event_type,
            click_tbl.click_type
    from
        exp_category
    left join 
            rr_net 
        on exp_category.user_id=rr_net.customer_id
    left join
            view_tbl
        on rr_net.customer_id=view_tbl.user_id
           and rr_net.yyyymmdd=view_tbl.yyyymmdd
    left join
            click_tbl
        on view_tbl.user_id=click_tbl.user_id
        and view_tbl.yyyymmdd=click_tbl.yyyymmdd

)

SELECT
        test_group,
        -- event_type,
        -- click_type,
        customers,

        gross_count,
        net_count,
        
        COALESCE(TRY(net_count*100.00/gross_count), 0) g2n,
        
        COALESCE(TRY(tot_accepted*100.00/gross_count), 0) "aor",
        
        
        median_cobrm_time,
        median_cobra_time,
        median_ocara_time,
        median_cancellation_time,
        median_acceptance_time,
        
        COALESCE(TRY(cobrm*100.00/gross_count), 0) "% cobrm",
        COALESCE(TRY(cobra*100.00/gross_count), 0) "% cobra",
        COALESCE(TRY(ocara*100.00/gross_count), 0) "% ocara",
        COALESCE(TRY(expired*100.00/gross_count), 0) "% expired",
        cobrm, 
        cobra,
        ocara,
        expired
    FROM    
        (
        SELECT
            test_group,
            -- event_type,
            -- click_type,
            COUNT(DISTINCT user_id) customers,
            COUNT(DISTINCT order_id) gross_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' AND spd_fraud_flag != true THEN order_id END) net_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN order_id END) AS tot_accepted,

        
           
            
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRM' THEN order_id END) cobrm,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRA' THEN order_id END) cobra,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'OCARA' THEN order_id END) ocara,
            COUNT(DISTINCT CASE WHEN order_status = 'expired' THEN order_id END) expired,
            
            approx_percentile(CASE WHEN modified_order_status = 'COBRM' THEN time_spent_in_sec END,0.50) as median_cobrm_time,
            approx_percentile(CASE WHEN modified_order_status = 'COBRA' THEN time_spent_in_sec END,0.50) as median_cobra_time,
            approx_percentile(CASE WHEN modified_order_status = 'OCARA' THEN time_spent_in_sec END,0.50) as median_ocara_time,
            approx_percentile(CASE WHEN modified_order_status in ('COBRA','COBRM','OCARA') THEN time_spent_in_sec END,0.50) as median_cancellation_time,
            approx_percentile(CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN time_taken_to_accp END,0.50) as median_acceptance_time
            
        FROM 
            merge
        where 
            yyyymmdd is not null
           and NOT (test_group = 'control' AND event_type IS NOT NULL)
           and NOT (event_type IS NULL AND click_type IS NOT NULL)
        GROUP BY 1
        )
    ORDER BY 1,2,3

"""

overall_sportspre=pd.read_sql(overall_query,conn)

/var/folders/j7/5rtfb17j30s9g9q790v9nr0h0000gn/T/ipykernel_62376/3545597203.py:179: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  overall_sportspre=pd.read_sql(overall_query,conn)

In [14]:
overall_sportspre

,test_group,customers,gross_count,net_count,g2n,aor,median_cobrm_time,median_cobra_time,median_ocara_time,median_cancellation_time,median_acceptance_time,% cobrm,% cobra,% ocara,% expired,cobrm,cobra,ocara,expired
0,control,48765,154753,90750,58.64,74.62,67,117,259,150,11,0.66,18.21,15.61,6.51,1026,28176,24158,10076
1,test,48702,156637,92985,59.36,75.22,74,117,259,150,12,0.70,17.73,15.47,6.34,1096,27769,24234,9935

In [15]:
overall_sportspre.to_clipboard(index=False)

## COBRA TTC

In [26]:
overall_query=f"""
with exp_category as(
select
    userid as user_id,
    case    when name='CaptainSearchSportsNewsTest' then 'test' 
            else 'control'
    end as test_group
from
   canonical.user_selector
where
    yyyymmdd = '20240905'
    and selectorid in ('66d9e70d8e21590001b635ac','66d9e97fdac1090001c05d83')

),

rr_net AS (
    SELECT 
        yyyymmdd, 
        customer_id,
        order_id, 
        order_status, 
        modified_order_status, 
        spd_fraud_flag,
        quarter_hour,
        CASE 
            WHEN modified_order_status IN ('OCARA', 'COBRA', 'COBRM') 
            THEN (customer_cancelled_epoch / 1000 - order_requested_epoch / 1000) 
        END AS time_spent_in_sec,
        CASE 
            WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') 
            THEN (rider_accepted_epoch / 1000 - order_requested_epoch / 1000)
        END AS time_taken_to_accp
        
    
    FROM 
        orders.order_logs_fact fact
    WHERE 
         yyyymmdd >= '20240911' AND yyyymmdd <= '20240916'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city_name = 'Hyderabad'
        AND service_obj_service_name in ('Auto','Auto Lite','Auto NCR','Auto Pool','AutoPremium','CityAuto','Link','Bike Lite','Bike Pink','CabEconomy','Bike Metro', 'CabPremium')
        AND channel_host='android'
        and customer_id in(
                select
                    user_id
        from 
            clevertap.clevertap_customer_order_activity
        where 
            yyyymmdd >= '20240911' AND yyyymmdd <= '20240916'
            AND order_activity_source = 'appOpen'
            and current_city = 'Hyderabad'
            and platform='Android'
            and app_version>='8.30.0'           
            )
         
),

view_tbl as(

    select
        yyyymmdd,
        profile_identity as user_id,
        'viewed' as event_type
    from 
        clevertap.customer_notification_viewed_immutable 
    where yyyymmdd >= '20240911' and yyyymmdd<='20240916'
    and event_props_campaign_id = '1725971334'

),

click_tbl as(
    select
        yyyymmdd,
        profile_identity as user_id,
        CASE
                    when event_props_wzrk_c2a='Button 2' then 'play_click'
                    else 'close_click'
        end as click_type
    from 
        clevertap.customer_notification_clicked_immutable
    where yyyymmdd >= '20240911' and yyyymmdd<='20240916'
    and event_props_campaign_id = '1725971334'

),
merge as(
    select exp_category.*,
            rr_net.yyyymmdd,
            rr_net.order_id,
            rr_net.order_status,
            rr_net.modified_order_status,
            rr_net.spd_fraud_flag,
            rr_net.quarter_hour,
            rr_net.time_spent_in_sec,
            rr_net.time_taken_to_accp,
            view_tbl.event_type,
            click_tbl.click_type
    from
        exp_category
    left join 
            rr_net 
        on exp_category.user_id=rr_net.customer_id
    left join
            view_tbl
        on rr_net.customer_id=view_tbl.user_id
           and rr_net.yyyymmdd=view_tbl.yyyymmdd
    left join
            click_tbl
        on view_tbl.user_id=click_tbl.user_id
        and view_tbl.yyyymmdd=click_tbl.yyyymmdd

)

SELECT
        test_group,
        -- event_type,
        -- click_type,
        cobra_ttc_bucket,
        customers,

        gross_count,
        net_count,
        
        COALESCE(TRY(net_count*100.00/gross_count), 0) g2n,
        
        COALESCE(TRY(tot_accepted*100.00/gross_count), 0) "aor",
        
        
        median_cobrm_time,
        median_cobra_time,
        median_ocara_time,
        median_cancellation_time,
        median_acceptance_time,
        
        COALESCE(TRY(cobrm*100.00/gross_count), 0) "% cobrm",
        COALESCE(TRY(cobra*100.00/gross_count), 0) "% cobra",
        COALESCE(TRY(ocara*100.00/gross_count), 0) "% ocara",
        COALESCE(TRY(expired*100.00/gross_count), 0) "% expired",
        cobrm, 
        cobra,
        ocara,
        expired
    FROM    
        (
        SELECT
            test_group,
            -- event_type,
            -- click_type,

            CASE 
            WHEN modified_order_status = 'COBRA' AND time_spent_in_sec <= 15 THEN 'a. 0-15 sec' 
            WHEN modified_order_status = 'COBRA' AND time_spent_in_sec BETWEEN 16 AND 30 THEN 'b. 16-30 sec' 
            WHEN modified_order_status = 'COBRA' AND time_spent_in_sec BETWEEN 31 AND 60 THEN 'c. 31-60 sec' 
            WHEN modified_order_status = 'COBRA' AND time_spent_in_sec BETWEEN 61 AND 180 THEN 'd. 61-180 sec' 
            WHEN modified_order_status = 'COBRA' AND time_spent_in_sec > 180 THEN 'e. 180+ sec' 
            WHEN modified_order_status != 'COBRA' THEN 'f. NO COBRA'
            ELSE 'Check' END cobra_ttc_bucket,
            
            COUNT(DISTINCT user_id) customers,
            COUNT(DISTINCT order_id) gross_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' AND spd_fraud_flag != true THEN order_id END) net_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN order_id END) AS tot_accepted,

        
           
            
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRM' THEN order_id END) cobrm,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRA' THEN order_id END) cobra,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'OCARA' THEN order_id END) ocara,
            COUNT(DISTINCT CASE WHEN order_status = 'expired' THEN order_id END) expired,
            
            approx_percentile(CASE WHEN modified_order_status = 'COBRM' THEN time_spent_in_sec END,0.50) as median_cobrm_time,
            approx_percentile(CASE WHEN modified_order_status = 'COBRA' THEN time_spent_in_sec END,0.50) as median_cobra_time,
            approx_percentile(CASE WHEN modified_order_status = 'OCARA' THEN time_spent_in_sec END,0.50) as median_ocara_time,
            approx_percentile(CASE WHEN modified_order_status in ('COBRA','COBRM','OCARA') THEN time_spent_in_sec END,0.50) as median_cancellation_time,
            approx_percentile(CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN time_taken_to_accp END,0.50) as median_acceptance_time
            
        FROM 
            merge
        where 
            yyyymmdd is not null
           and NOT (test_group = 'control' AND event_type IS NOT NULL)
           and NOT (event_type IS NULL AND click_type IS NOT NULL)

           and click_type = 'play_click'
           
        GROUP BY 1,2
        )
    ORDER BY 1,2

"""

overall_sports_ttc=pd.read_sql(overall_query,conn)

/var/folders/j7/5rtfb17j30s9g9q790v9nr0h0000gn/T/ipykernel_62376/2534316204.py:193: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  overall_sports_ttc=pd.read_sql(overall_query,conn)

In [27]:
overall_sports_ttc

,test_group,cobra_ttc_bucket,customers,gross_count,net_count,g2n,aor,median_cobrm_time,median_cobra_time,median_ocara_time,median_cancellation_time,median_acceptance_time,% cobrm,% cobra,% ocara,% expired,cobrm,cobra,ocara,expired
0,test,a. 0-15 sec,46,52,0,0.00,0.00,NaN,11.0,NaN,11,NaN,0.00,100.0,0.00,0.00,0,52,0,0
1,test,b. 16-30 sec,56,58,0,0.00,0.00,NaN,22.0,NaN,22,NaN,0.00,100.0,0.00,0.00,0,58,0,0
2,test,c. 31-60 sec,61,69,0,0.00,0.00,NaN,47.0,NaN,47,NaN,0.00,100.0,0.00,0.00,0,69,0,0
3,test,d. 61-180 sec,175,258,0,0.00,0.00,NaN,112.0,NaN,112,NaN,0.00,100.0,0.00,0.00,0,258,0,0
4,test,e. 180+ sec,95,112,0,0.00,0.00,NaN,225.0,NaN,225,NaN,0.00,100.0,0.00,0.00,0,112,0,0
5,test,f. NO COBRA,2080,3543,2498,70.51,94.52,39.0,NaN,203.0,191,10.0,1.04,0.0,23.48,4.43,37,0,832,157

In [28]:
overall_sports_ttc.to_clipboard(index=False)

## other

In [82]:
overall_query_daywise=f"""
with exp_category as(
select
    userid as user_id,
    case    when name='CaptainSearchSportsNewsTest' then 'test' 
            else 'control'
    end as test_group
from
   canonical.user_selector
where
    yyyymmdd = '20240905'
    and selectorid in ('66d9e70d8e21590001b635ac','66d9e97fdac1090001c05d83')

),

rr_net AS (
    SELECT 
        yyyymmdd, 
        customer_id,
        order_id, 
        order_status, 
        modified_order_status, 
        spd_fraud_flag,
        quarter_hour,
        CASE 
            WHEN modified_order_status IN ('OCARA', 'COBRA', 'COBRM') 
            THEN (customer_cancelled_epoch / 1000 - order_requested_epoch / 1000) 
        END AS time_spent_in_sec,
        CASE 
            WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') 
            THEN (rider_accepted_epoch / 1000 - order_requested_epoch / 1000)
        END AS time_taken_to_accp
        
    
    FROM 
        orders.order_logs_fact fact
    WHERE 
         yyyymmdd >= '20240911' AND yyyymmdd <= '20240916'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city_name = 'Hyderabad'
        AND service_obj_service_name in ('Auto','Auto Lite','Auto NCR','Auto Pool','AutoPremium','CityAuto','Link','Bike Lite','Bike Pink','CabEconomy','Bike Metro', 'CabPremium')
        AND channel_host='android'
        and customer_id in(
                select
                    user_id
                from 
                    clevertap.clevertap_customer_order_activity
                where 
                    yyyymmdd >= '20240911' AND yyyymmdd <= '20240916'
                    AND order_activity_source = 'appOpen'
                    and current_city = 'Hyderabad'
                    and platform='Android'
                    and app_version>='8.30.0'           
            )
         
),

view_tbl as(

    select
        yyyymmdd,
        profile_identity as user_id,
        'viewed' as event_type
    from 
        clevertap.customer_notification_viewed_immutable 
    where yyyymmdd >= '20240911' and yyyymmdd<='20240916'
    and event_props_campaign_id = '1725971334'

),

click_tbl as(
    select
        yyyymmdd,
        profile_identity as user_id,
        CASE
                    when event_props_wzrk_c2a='Button 2' then 'play_click'
                    else 'close_click'
        end as click_type
    from 
        clevertap.customer_notification_clicked_immutable
    where yyyymmdd >= '20240911' and yyyymmdd<='20240916'
    and event_props_campaign_id = '1725971334'

),
merge as(
    select exp_category.*,
            rr_net.yyyymmdd,
            rr_net.order_id,
            rr_net.order_status,
            rr_net.modified_order_status,
            rr_net.spd_fraud_flag,
            rr_net.quarter_hour,
            rr_net.time_spent_in_sec,
            rr_net.time_taken_to_accp,
            view_tbl.event_type,
            click_tbl.click_type
    from
        exp_category
    left join 
            rr_net 
        on exp_category.user_id=rr_net.customer_id
    left join
            view_tbl
        on rr_net.customer_id=view_tbl.user_id
           and rr_net.yyyymmdd=view_tbl.yyyymmdd
    left join
            click_tbl
        on view_tbl.user_id=click_tbl.user_id
        and view_tbl.yyyymmdd=click_tbl.yyyymmdd

)

SELECT
        yyyymmdd,
        test_group,
        event_type,
        click_type,
        customers,

        gross_count,
        net_count,
        
        COALESCE(TRY(net_count*100.00/gross_count), 0) g2n,
        
        COALESCE(TRY(tot_accepted*100.00/gross_count), 0) "aor",
        
        
        median_cobrm_time,
        median_cobra_time,
        median_ocara_time,
        median_cancellation_time,
        median_acceptance_time,
        
        COALESCE(TRY(cobrm*100.00/gross_count), 0) "% cobrm",
        COALESCE(TRY(cobra*100.00/gross_count), 0) "% cobra",
        COALESCE(TRY(ocara*100.00/gross_count), 0) "% ocara",
        COALESCE(TRY(expired*100.00/gross_count), 0) "% expired",
        cobrm, 
        cobra,
        ocara,
        expired
    FROM    
        (
        SELECT
            yyyymmdd,
            test_group,
            event_type,
            click_type,
            COUNT(DISTINCT user_id) customers,
            COUNT(DISTINCT order_id) gross_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' AND spd_fraud_flag != true THEN order_id END) net_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN order_id END) AS tot_accepted,

        
           
            
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRM' THEN order_id END) cobrm,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRA' THEN order_id END) cobra,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'OCARA' THEN order_id END) ocara,
            COUNT(DISTINCT CASE WHEN order_status = 'expired' THEN order_id END) expired,
            
            approx_percentile(CASE WHEN modified_order_status = 'COBRM' THEN time_spent_in_sec END,0.50) as median_cobrm_time,
            approx_percentile(CASE WHEN modified_order_status = 'COBRA' THEN time_spent_in_sec END,0.50) as median_cobra_time,
            approx_percentile(CASE WHEN modified_order_status = 'OCARA' THEN time_spent_in_sec END,0.50) as median_ocara_time,
            approx_percentile(CASE WHEN modified_order_status in ('COBRA','COBRM','OCARA') THEN time_spent_in_sec END,0.50) as median_cancellation_time,
            approx_percentile(CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN time_taken_to_accp END,0.50) as median_acceptance_time
            
        FROM 
            merge
        where 
            yyyymmdd is not null
           and NOT (test_group = 'control' AND event_type IS NOT NULL)
           and NOT (event_type IS NULL AND click_type IS NOT NULL)
        GROUP BY 1,2,3,4
        )
    ORDER BY 1,2,3,4

"""

overall_sports_daywise=pd.read_sql(overall_query_daywise,conn)

/var/folders/km/1ltm54y105x6dzlcf44g881c0000gn/T/ipykernel_49271/2737540206.py:181: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  overall_sports_daywise=pd.read_sql(overall_query_daywise,conn)

In [83]:
overall_sports_daywise

,yyyymmdd,test_group,event_type,click_type,customers,gross_count,net_count,g2n,aor,median_cobrm_time,median_cobra_time,median_ocara_time,median_cancellation_time,median_acceptance_time,% cobrm,% cobra,% ocara,% expired,cobrm,cobra,ocara,expired
0,20240911,control,None,None,14510,24860,17050,68.58,84.72,95.0,106,250,153,10,0.54,11.27,15.70,3.46,135,2802,3904,861
1,20240911,test,viewed,close_click,7130,13061,8826,67.58,84.83,90.0,112,222,152,10,0.67,10.99,16.79,3.51,88,1436,2193,458
2,20240911,test,viewed,play_click,306,637,362,56.83,78.34,46.0,99,152,119,11,1.41,15.38,21.35,4.87,9,98,136,31
3,20240911,test,viewed,None,216,391,257,65.73,85.93,NaN,91,271,169,10,0.00,9.97,19.95,4.09,0,39,78,16
4,20240911,test,None,None,7048,11347,8045,70.90,86.92,84.0,104,249,158,10,0.43,9.61,15.59,3.03,49,1091,1769,344
5,20240912,control,None,None,14706,24791,17203,69.39,85.73,80.0,111,254,161,10,0.61,10.30,15.95,3.36,150,2554,3955,832
6,20240912,test,viewed,close_click,10648,18566,12831,69.11,84.97,72.0,107,250,151,10,0.81,10.75,15.50,3.46,151,1996,2878,643
7,20240912,test,viewed,play_click,405,679,430,63.33,81.44,22.0,100,247,110,10,0.59,13.99,17.97,3.98,4,95,122,27
8,20240912,test,viewed,None,289,508,363,71.46,90.55,35.0,127,248,159,9,0.59,6.89,18.31,1.97,3,35,93,10
9,20240912,test,None,None,3428,5547,3977,71.70,87.29,55.0,106,229,153,10,0.50,9.00,15.05,3.21,28,499,835,178
10,20240913,control,None,None,15140,25235,17755,70.36,86.64,70.0,102,256,156,10,0.53,10.04,15.82,2.78,135,2533,3993,702
11,20240913,test,viewed,close_click,11346,19524,13607,69.69,85.90,49.0,110,248,156,10,0.62,10.55,15.76,2.92,122,2059,3077,570
12,20240913,test,viewed,play_click,398,648,400,61.73,83.33,336.0,83,194,128,11,0.31,12.65,20.83,3.70,2,82,135,24
13,20240913,test,viewed,None,272,515,307,59.61,82.14,65.0,92,153,112,10,1.36,11.46,21.94,5.05,7,59,113,26
14,20240913,test,None,None,3370,5458,3898,71.42,87.93,61.0,99,247,158,10,0.40,8.87,16.12,2.80,22,484,880,153
15,20240914,control,None,None,14872,24709,17426,70.52,87.91,94.0,108,247,163,9,0.72,8.71,16.95,2.66,179,2151,4188,657
16,20240914,test,viewed,close_click,11064,18783,13300,70.81,87.69,51.0,103,250,161,9,0.68,8.84,16.37,2.76,128,1661,3075,518
17,20240914,test,viewed,play_click,454,786,499,63.49,83.72,70.0,82,213,139,11,1.02,11.07,19.59,4.20,8,87,154,33
18,20240914,test,viewed,None,269,479,306,63.88,87.68,42.0,120,141,127,8,1.88,8.56,23.17,1.67,9,41,111,8
19,20240914,test,None,None,3158,5264,3738,71.01,88.15,27.0,109,244,166,9,0.53,9.02,16.58,2.28,28,475,873,120
20,20240915,control,None,None,12719,21160,14653,69.25,87.50,80.0,107,250,165,9,0.52,9.51,17.84,2.46,109,2013,3774,520
21,20240915,test,viewed,close_click,9324,15737,11035,70.12,87.62,81.0,101,252,164,9,0.64,9.12,17.09,2.61,100,1436,2690,411
22,20240915,test,viewed,play_click,365,655,410,62.60,85.50,40.0,105,149,121,9,0.92,11.91,22.29,1.68,6,78,146,11
23,20240915,test,viewed,None,238,387,278,71.83,94.32,NaN,142,119,129,8,0.00,4.39,21.71,1.29,0,17,84,5
24,20240915,test,None,None,2790,4379,3139,71.68,89.13,107.0,116,262,173,9,0.41,8.31,16.88,2.15,18,364,739,94
25,20240916,control,None,None,14570,25494,16465,64.58,81.36,71.0,115,267,159,11,0.59,13.89,16.33,4.13,151,3540,4163,1054
26,20240916,test,viewed,close_click,10916,19248,12606,65.49,81.67,72.0,117,251,160,11,0.57,13.52,15.80,4.23,109,2602,3041,815
27,20240916,test,viewed,play_click,385,687,397,57.79,78.46,23.0,108,273,148,11,1.16,15.87,20.23,4.51,8,109,139,31
28,20240916,test,viewed,None,255,461,274,59.44,81.13,32.0,160,204,181,10,0.87,11.71,21.69,6.29,4,54,100,29
29,20240916,test,None,None,3029,5044,3302,65.46,82.28,97.0,107,262,154,11,0.85,12.65,16.51,4.20,43,638,833,212

In [85]:
overall_sports_daywise.to_clipboard(index=False)

In [67]:
overall_sports_daywise.to_csv('overall_sports_daywise.csv',index=False)

In [87]:
session_query=f"""
with exp_category as(
select
    userid as user_id,
    case    when name='CaptainSearchSportsNewsTest' then 'test' 
            else 'control'
    end as test_group
from
   canonical.user_selector
where
    yyyymmdd = '20240905'
    and selectorid in ('66d9e70d8e21590001b635ac','66d9e97fdac1090001c05d83')

),

rr_net AS (
    SELECT 
        yyyymmdd, 
        customer_id,
        order_id, 
        order_status, 
        modified_order_status, 
        spd_fraud_flag,
        quarter_hour,
        CASE 
            WHEN modified_order_status IN ('OCARA', 'COBRA', 'COBRM') 
            THEN (customer_cancelled_epoch / 1000 - order_requested_epoch / 1000) 
        END AS time_spent_in_sec,
        CASE 
            WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') 
            THEN (rider_accepted_epoch / 1000 - order_requested_epoch / 1000)
        END AS time_taken_to_accp
        
    
    FROM 
        orders.order_logs_fact fact
    WHERE 
         yyyymmdd >= '20240911' AND yyyymmdd <= '20240916'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city_name = 'Hyderabad'
        AND service_obj_service_name in ('Auto','Auto Lite','Auto NCR','Auto Pool','AutoPremium','CityAuto','Link','Bike Lite','Bike Pink','CabEconomy','Bike Metro', 'CabPremium')
        AND channel_host='android' 
        AND customer_id in (
                select
                    user_id
        from 
            clevertap.clevertap_customer_order_activity
        where 
            yyyymmdd >= '20240911' AND yyyymmdd <= '20240916'
            AND order_activity_source = 'appOpen'
            and current_city = 'Hyderabad'
            and platform='Android'
            and app_version>='8.30.0'           
            )
         
),

view_tbl as(

    select
        yyyymmdd,
        profile_identity as user_id,
        'viewed' as event_type
    from 
        clevertap.customer_notification_viewed_immutable 
    where yyyymmdd >= '20240911' and yyyymmdd<='20240916'
    and event_props_campaign_id = '1725971334'

),

click_tbl as(
    select
        yyyymmdd,
        profile_identity as user_id,
        CASE
                    when event_props_wzrk_c2a='Button 2' then 'play_click'
                    else 'close_click'
        end as click_type
    from 
        clevertap.customer_notification_clicked_immutable
    where yyyymmdd >= '20240911' and yyyymmdd<='20240916'
    and event_props_campaign_id = '1725971334'

),
merge as(
    select exp_category.*,
            rr_net.yyyymmdd,
            rr_net.order_id,
            rr_net.order_status,
            rr_net.modified_order_status,
            rr_net.spd_fraud_flag,
            rr_net.quarter_hour,
            rr_net.time_spent_in_sec,
            rr_net.time_taken_to_accp,
            view_tbl.event_type,
            click_tbl.click_type
    from
        exp_category
    left join 
            rr_net 
        on exp_category.user_id=rr_net.customer_id
    left join
            view_tbl
        on rr_net.customer_id=view_tbl.user_id
           and rr_net.yyyymmdd=view_tbl.yyyymmdd
    left join
            click_tbl
        on rr_net.customer_id=click_tbl.user_id
        and view_tbl.yyyymmdd=click_tbl.yyyymmdd

)

SELECT
        test_group,
        event_type,
        click_type,
        time_period,
        customers,

        gross_count,
        net_count,
        
        COALESCE(TRY(net_count*100.00/gross_count), 0) g2n,
        
        COALESCE(TRY(tot_accepted*100.00/gross_count), 0) "aor",
        
        
        median_cobrm_time,
        median_cobra_time,
        median_ocara_time,
        median_cancellation_time,
        median_acceptance_time,
        
        COALESCE(TRY(cobrm*100.00/gross_count), 0) "% cobrm",
        COALESCE(TRY(cobra*100.00/gross_count), 0) "% cobra",
        COALESCE(TRY(ocara*100.00/gross_count), 0) "% ocara",
        COALESCE(TRY(expired*100.00/gross_count), 0) "% expired",
        cobrm, 
        cobra,
        ocara,
        expired
    FROM    
        (
        SELECT
            test_group,
            event_type,
            click_type,
            case
                WHEN quarter_hour >= '0800' AND quarter_hour < '1100' THEN 'morning'
                WHEN quarter_hour >= '1100' AND quarter_hour < '1700' THEN 'afternoon'
                WHEN quarter_hour >= '1700' AND quarter_hour < '2100' THEN 'evening'
                WHEN quarter_hour >= '0000' AND quarter_hour < '0800' THEN 'rest_morning'
                ELSE 'rest_evening'
            end as time_period,
            COUNT(DISTINCT user_id) customers,
            COUNT(DISTINCT order_id) gross_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' AND spd_fraud_flag != true THEN order_id END) net_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN order_id END) AS tot_accepted,

        
           
            
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRM' THEN order_id END) cobrm,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRA' THEN order_id END) cobra,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'OCARA' THEN order_id END) ocara,
            COUNT(DISTINCT CASE WHEN order_status = 'expired' THEN order_id END) expired,
            
            approx_percentile(CASE WHEN modified_order_status = 'COBRM' THEN time_spent_in_sec END,0.50) as median_cobrm_time,
            approx_percentile(CASE WHEN modified_order_status = 'COBRA' THEN time_spent_in_sec END,0.50) as median_cobra_time,
            approx_percentile(CASE WHEN modified_order_status = 'OCARA' THEN time_spent_in_sec END,0.50) as median_ocara_time,
            approx_percentile(CASE WHEN modified_order_status in ('COBRA','COBRM','OCARA') THEN time_spent_in_sec END,0.50) as median_cancellation_time,
            approx_percentile(CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN time_taken_to_accp END,0.50) as median_acceptance_time
            
        FROM 
            merge
        where 
            yyyymmdd is not null
           and NOT (test_group = 'control' AND event_type IS NOT NULL)
           and NOT (event_type IS NULL AND click_type IS NOT NULL)
        GROUP BY 1,2,3,4
        )
    ORDER BY 1,2,3,4

"""

session_sports=pd.read_sql(session_query,conn)

/var/folders/km/1ltm54y105x6dzlcf44g881c0000gn/T/ipykernel_49271/2198619014.py:187: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  session_sports=pd.read_sql(session_query,conn)

In [88]:
session_sports

,test_group,event_type,click_type,time_period,customers,gross_count,net_count,g2n,aor,median_cobrm_time,median_cobra_time,median_ocara_time,median_cancellation_time,median_acceptance_time,% cobrm,% cobra,% ocara,% expired,cobrm,cobra,ocara,expired
0,control,None,None,afternoon,25543,48700,36083,74.09,90.21,74.0,104,251,166,9,0.37,7.34,15.71,2.09,178,3576,7653,1016
1,control,None,None,evening,21187,39943,25932,64.92,82.72,84.0,108,275,161,12,0.87,12.48,17.36,3.91,349,4983,6935,1560
2,control,None,None,morning,14611,27422,18702,68.20,82.44,81.0,113,242,149,11,0.49,13.02,13.91,4.06,134,3569,3815,1113
3,control,None,None,rest_evening,9964,16277,10394,63.86,83.34,90.0,108,261,163,12,0.56,12.79,18.88,3.27,91,2082,3073,532
4,control,None,None,rest_morning,8736,13907,9441,67.89,86.37,94.0,111,219,149,8,0.77,9.94,17.98,2.91,107,1383,2501,405
5,test,viewed,close_click,afternoon,18578,34991,25935,74.12,90.11,60.0,108,249,170,8,0.46,7.21,15.61,2.23,160,2522,5463,780
6,test,viewed,close_click,evening,15335,28553,18703,65.50,83.02,57.0,111,259,159,12,0.91,12.01,17.06,4.03,261,3429,4870,1152
7,test,viewed,close_click,morning,10732,20439,13794,67.49,81.56,78.0,115,233,147,10,0.65,13.65,13.80,4.14,132,2789,2820,847
8,test,viewed,close_click,rest_evening,7120,11573,7374,63.72,83.64,55.0,98,263,162,12,0.49,12.82,19.26,3.00,57,1484,2229,347
9,test,viewed,close_click,rest_morning,5959,9363,6399,68.34,85.66,111.0,105,201,141,7,0.94,10.32,16.79,3.09,88,966,1572,289
10,test,viewed,play_click,afternoon,886,1360,888,65.29,86.62,19.0,99,189,123,9,0.96,9.49,20.66,2.94,13,129,281,40
11,test,viewed,play_click,evening,821,1186,711,59.95,80.35,46.0,88,189,125,11,1.52,13.24,20.15,4.89,18,157,239,58
12,test,viewed,play_click,morning,459,699,396,56.65,74.82,27.0,105,201,128,11,0.29,19.31,18.03,5.58,2,135,126,39
13,test,viewed,play_click,rest_evening,370,505,296,58.61,80.40,217.0,102,282,175,15,0.59,16.63,21.19,2.38,3,84,107,12
14,test,viewed,play_click,rest_morning,247,342,207,60.53,84.50,243.0,81,159,114,7,0.29,12.87,23.10,2.34,1,44,79,8
15,test,viewed,None,afternoon,620,917,647,70.56,91.82,32.0,93,154,134,8,0.55,6.32,20.61,1.31,5,58,189,12
16,test,viewed,None,evening,498,755,453,60.00,81.32,48.0,120,204,147,12,2.25,11.66,20.53,4.77,17,88,155,36
17,test,viewed,None,morning,366,515,335,65.05,85.24,NaN,123,186,145,10,0.00,9.90,19.81,4.85,0,51,102,25
18,test,viewed,None,rest_evening,235,339,205,60.47,85.25,41.0,86,235,153,10,0.29,11.80,24.78,2.36,1,40,84,8
19,test,viewed,None,rest_morning,156,215,145,67.44,90.23,NaN,94,136,109,7,0.00,3.72,22.79,6.05,0,8,49,13
20,test,None,None,afternoon,7183,12456,9390,75.39,91.54,41.0,99,246,169,8,0.43,6.09,15.72,1.94,54,758,1958,242
21,test,None,None,evening,5839,9901,6716,67.83,85.26,60.0,109,264,166,11,0.56,10.92,16.92,3.26,55,1081,1675,323
22,test,None,None,morning,4164,6900,4749,68.83,82.01,88.0,110,222,140,10,0.55,13.09,12.99,4.35,38,903,896,300
23,test,None,None,rest_evening,2704,4030,2652,65.81,85.29,106.0,102,278,169,11,0.37,11.24,18.81,3.05,15,453,758,123
24,test,None,None,rest_morning,2552,3752,2592,69.08,86.81,156.0,107,227,154,8,0.69,9.49,17.11,3.01,26,356,642,113

In [89]:
session_sports.to_clipboard(index=False)

In [70]:
session_sports.to_csv('session_sports.csv',index=False)

In [71]:
ltr_segment_query=f"""
with exp_category as(
select
    userid as user_id,
    case    when name='CaptainSearchSportsNewsTest' then 'test' 
            else 'control'
    end as test_group
from
   canonical.user_selector
where
    yyyymmdd = '20240905'
    and selectorid in ('66d9e70d8e21590001b635ac','66d9e97fdac1090001c05d83')

),

rr_net AS (
    SELECT 
        yyyymmdd, 
        customer_id,
        order_id, 
        order_status, 
        modified_order_status, 
        spd_fraud_flag,
        quarter_hour,
        CASE 
            WHEN modified_order_status IN ('OCARA', 'COBRA', 'COBRM') 
            THEN (customer_cancelled_epoch / 1000 - order_requested_epoch / 1000) 
        END AS time_spent_in_sec,
        CASE 
            WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') 
            THEN (rider_accepted_epoch / 1000 - order_requested_epoch / 1000)
        END AS time_taken_to_accp
        
    
    FROM 
        orders.order_logs_fact fact
    WHERE 
         yyyymmdd >= '20240911' AND yyyymmdd <= '20240915'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city_name = 'Hyderabad'
        AND service_obj_service_name in ('Auto','Auto Lite','Auto NCR','Auto Pool','AutoPremium','CityAuto','Link','Bike Lite','Bike Pink','CabEconomy','Bike Metro', 'CabPremium')
        AND channel_host='android'
        and customer_id in(
                select
                    user_id
        from 
            clevertap.clevertap_customer_order_activity
        where 
            yyyymmdd >= '20240911' AND yyyymmdd <= '20240915'
            AND order_activity_source = 'appOpen'
            and current_city = 'Hyderabad'
            and platform='Android'
            and app_version>='8.30.0'           
            )
         
),

view_tbl as(

    select
        yyyymmdd,
        profile_identity as user_id,
        'viewed' as event_type
    from 
        clevertap.customer_notification_viewed_immutable 
    where yyyymmdd >= '20240911' and yyyymmdd<='20240915'
    and event_props_campaign_id = '1725971334'

),

click_tbl as(
    select
        yyyymmdd,
        profile_identity as user_id,
        CASE
                    when event_props_wzrk_c2a='Button 2' then 'play_click'
                    else 'close_click'
        end as click_type
    from 
        clevertap.customer_notification_clicked_immutable
    where yyyymmdd >= '20240911' and yyyymmdd<='20240915'
    and event_props_campaign_id = '1725971334'

),

segment AS (
    
    SELECT
        customer_id,
        taxi_ltr_segment ltr_segment,
        taxi_retention_segments retention_segment,
        taxi_lifetime_stage lifetime_stage,
        taxi_service_affinity service_affinity,
        gender_tag gender
    FROM
        datasets.iallocator_customer_segments
    WHERE 
        run_date = '2024-09-11'
    
),


merge as(
    select exp_category.*,
            rr_net.yyyymmdd,
            rr_net.order_id,
            rr_net.order_status,
            rr_net.modified_order_status,
            rr_net.spd_fraud_flag,
            rr_net.quarter_hour,
            rr_net.time_spent_in_sec,
            rr_net.time_taken_to_accp,
            view_tbl.event_type,
            click_tbl.click_type,
            segment.ltr_segment
    from
        exp_category
    left join 
            rr_net 
        on exp_category.user_id=rr_net.customer_id
    left join
            view_tbl
        on rr_net.customer_id=view_tbl.user_id
           and rr_net.yyyymmdd=view_tbl.yyyymmdd
    left join
            click_tbl
        on view_tbl.user_id=click_tbl.user_id
        and view_tbl.yyyymmdd=click_tbl.yyyymmdd
    LEFT JOIN 
            segment
        ON rr_net.customer_id=segment.customer_id

)

SELECT
        test_group,
        event_type,
        click_type,
        ltr_segment,
        customers,

        gross_count,
        net_count,
        
        COALESCE(TRY(net_count*100.00/gross_count), 0) g2n,
        
        COALESCE(TRY(tot_accepted*100.00/gross_count), 0) "aor",
        
        
        median_cobrm_time,
        median_cobra_time,
        median_ocara_time,
        median_cancellation_time,
        median_acceptance_time,
        
        COALESCE(TRY(cobrm*100.00/gross_count), 0) "% cobrm",
        COALESCE(TRY(cobra*100.00/gross_count), 0) "% cobra",
        COALESCE(TRY(ocara*100.00/gross_count), 0) "% ocara",
        COALESCE(TRY(expired*100.00/gross_count), 0) "% expired",
        cobrm, 
        cobra,
        ocara,
        expired
    FROM    
        (
        SELECT
            test_group,
            event_type,
            click_type,
            ltr_segment,
            COUNT(DISTINCT user_id) customers,
            COUNT(DISTINCT order_id) gross_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' AND spd_fraud_flag != true THEN order_id END) net_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN order_id END) AS tot_accepted,

        
           
            
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRM' THEN order_id END) cobrm,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRA' THEN order_id END) cobra,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'OCARA' THEN order_id END) ocara,
            COUNT(DISTINCT CASE WHEN order_status = 'expired' THEN order_id END) expired,
            
            approx_percentile(CASE WHEN modified_order_status = 'COBRM' THEN time_spent_in_sec END,0.50) as median_cobrm_time,
            approx_percentile(CASE WHEN modified_order_status = 'COBRA' THEN time_spent_in_sec END,0.50) as median_cobra_time,
            approx_percentile(CASE WHEN modified_order_status = 'OCARA' THEN time_spent_in_sec END,0.50) as median_ocara_time,
            approx_percentile(CASE WHEN modified_order_status in ('COBRA','COBRM','OCARA') THEN time_spent_in_sec END,0.50) as median_cancellation_time,
            approx_percentile(CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN time_taken_to_accp END,0.50) as median_acceptance_time
            
        FROM 
            merge
        where 
            yyyymmdd is not null
           and NOT (test_group = 'control' AND event_type IS NOT NULL)
           and NOT (event_type IS NULL AND click_type IS NOT NULL)
        GROUP BY 1,2,3,4
        )
    ORDER BY 1,2,3,4

"""

ltr_segment_sports=pd.read_sql(ltr_segment_query,conn)

/var/folders/km/1ltm54y105x6dzlcf44g881c0000gn/T/ipykernel_49271/657598224.py:203: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  ltr_segment_sports=pd.read_sql(ltr_segment_query,conn)

In [72]:
ltr_segment_sports

,test_group,event_type,click_type,ltr_segment,customers,gross_count,net_count,g2n,aor,median_cobrm_time,median_cobra_time,median_ocara_time,median_cancellation_time,median_acceptance_time,% cobrm,% cobra,% ocara,% expired,cobrm,cobra,ocara,expired
0,control,None,None,HH,2092,3980,2457,61.73,86.71,90.0,112.0,193.0,143.0,8.0,1.08,9.20,24.35,3.02,43,366,969,120
1,control,None,None,PHH,41446,114664,80138,69.89,86.43,84.0,107.0,255.0,161.0,10.0,0.55,10.04,16.12,2.97,635,11511,18488,3407
2,control,None,None,UNKNOWN,125,357,93,26.05,83.19,108.0,111.0,147.0,115.0,8.0,6.44,7.84,56.30,2.52,23,28,201,9
3,control,None,None,None,6,6,6,100.00,100.00,NaN,NaN,NaN,NaN,8.0,0.00,0.00,0.00,0.00,0,0,0,0
4,test,viewed,close_click,HH,1634,3201,1924,60.11,84.82,49.0,99.0,227.0,157.0,9.0,2.37,8.59,23.96,4.22,76,275,767,135
5,test,viewed,close_click,PHH,29901,81419,56935,69.93,86.29,65.0,107.0,247.0,157.0,10.0,0.61,10.09,15.94,2.99,500,8218,12982,2434
6,test,viewed,close_click,UNKNOWN,83,227,58,25.55,80.18,144.0,113.0,107.0,110.0,8.0,5.29,9.69,54.19,4.85,12,22,123,11
7,test,viewed,play_click,HH,120,225,113,50.22,81.33,114.0,89.0,165.0,128.0,10.0,2.67,8.89,30.67,7.11,6,20,69,16
8,test,viewed,play_click,PHH,1687,3121,1967,63.02,83.08,36.0,96.0,189.0,124.0,10.0,0.51,13.20,19.61,3.20,16,412,612,100
9,test,viewed,play_click,UNKNOWN,10,32,1,3.13,34.38,70.0,87.0,50.0,70.0,5.0,18.75,18.75,28.13,28.13,6,6,9,9
10,test,viewed,play_click,None,1,1,0,0.00,0.00,NaN,NaN,NaN,NaN,NaN,0.00,0.00,0.00,100.00,0,0,0,1
11,test,viewed,None,HH,34,72,22,30.56,93.06,NaN,30.0,36.0,33.0,5.0,0.00,5.56,61.11,1.39,0,4,44,1
12,test,viewed,None,PHH,1129,2162,1471,68.04,87.88,65.0,105.0,210.0,148.0,9.0,0.79,8.46,19.24,2.82,17,183,416,61
13,test,viewed,None,UNKNOWN,5,20,0,0.00,85.00,35.0,NaN,41.0,40.0,5.0,10.00,0.00,85.00,5.00,2,0,17,1
14,test,None,None,HH,447,706,461,65.30,91.22,27.0,146.0,203.0,168.0,8.0,1.56,4.96,25.07,2.27,11,35,177,16
15,test,None,None,PHH,13249,30297,21622,71.37,87.52,61.0,106.0,246.0,160.0,10.0,0.42,9.24,15.68,2.82,126,2799,4752,853
16,test,None,None,UNKNOWN,56,100,44,44.00,85.00,119.0,82.0,396.0,203.0,9.0,4.00,8.00,41.00,3.00,4,8,41,3

In [73]:
retention_segment_query=f"""
with exp_category as(
select
    userid as user_id,
    case    when name='CaptainSearchSportsNewsTest' then 'test' 
            else 'control'
    end as test_group
from
   canonical.user_selector
where
    yyyymmdd = '20240905'
    and selectorid in ('66d9e70d8e21590001b635ac','66d9e97fdac1090001c05d83')

),

rr_net AS (
    SELECT 
        yyyymmdd, 
        customer_id,
        order_id, 
        order_status, 
        modified_order_status, 
        spd_fraud_flag,
        quarter_hour,
        CASE 
            WHEN modified_order_status IN ('OCARA', 'COBRA', 'COBRM') 
            THEN (customer_cancelled_epoch / 1000 - order_requested_epoch / 1000) 
        END AS time_spent_in_sec,
        CASE 
            WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') 
            THEN (rider_accepted_epoch / 1000 - order_requested_epoch / 1000)
        END AS time_taken_to_accp
        
    
    FROM 
        orders.order_logs_fact fact
    WHERE 
         yyyymmdd >= '20240911' AND yyyymmdd <= '20240915'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city_name = 'Hyderabad'
        AND service_obj_service_name in ('Auto','Auto Lite','Auto NCR','Auto Pool','AutoPremium','CityAuto','Link','Bike Lite','Bike Pink','CabEconomy','Bike Metro', 'CabPremium')
        AND channel_host='android'
        and customer_id in(
                select
                    user_id
        from 
            clevertap.clevertap_customer_order_activity
        where 
            yyyymmdd >= '20240911' AND yyyymmdd <= '20240915'
            AND order_activity_source = 'appOpen'
            and current_city = 'Hyderabad'
            and platform='Android'
            and app_version>='8.30.0'           
            )
         
),

view_tbl as(

    select
        yyyymmdd,
        profile_identity as user_id,
        'viewed' as event_type
    from 
        clevertap.customer_notification_viewed_immutable 
    where yyyymmdd >= '20240911' and yyyymmdd<='20240915'
    and event_props_campaign_id = '1725971334'

),

click_tbl as(
    select
        yyyymmdd,
        profile_identity as user_id,
        CASE
                    when event_props_wzrk_c2a='Button 2' then 'play_click'
                    else 'close_click'
        end as click_type
    from 
        clevertap.customer_notification_clicked_immutable
    where yyyymmdd >= '20240911' and yyyymmdd<='20240915'
    and event_props_campaign_id = '1725971334'

),

segment AS (
    
    SELECT
        customer_id,
        taxi_ltr_segment ltr_segment,
        taxi_retention_segments retention_segment,
        taxi_lifetime_stage lifetime_stage,
        taxi_service_affinity service_affinity,
        gender_tag gender
    FROM
        datasets.iallocator_customer_segments
    WHERE 
        run_date = '2024-09-11'
    
),


merge as(
    select exp_category.*,
            rr_net.yyyymmdd,
            rr_net.order_id,
            rr_net.order_status,
            rr_net.modified_order_status,
            rr_net.spd_fraud_flag,
            rr_net.quarter_hour,
            rr_net.time_spent_in_sec,
            rr_net.time_taken_to_accp,
            view_tbl.event_type,
            click_tbl.click_type,
            segment.retention_segment
    from
        exp_category
    left join 
            rr_net 
        on exp_category.user_id=rr_net.customer_id
    left join
            view_tbl
        on rr_net.customer_id=view_tbl.user_id
           and rr_net.yyyymmdd=view_tbl.yyyymmdd
    left join
            click_tbl
        on view_tbl.user_id=click_tbl.user_id
        and view_tbl.yyyymmdd=click_tbl.yyyymmdd
    LEFT JOIN 
            segment
        ON rr_net.customer_id=segment.customer_id

)

SELECT
        test_group,
        event_type,
        click_type,
        retention_segment,
        customers,

        gross_count,
        net_count,
        
        COALESCE(TRY(net_count*100.00/gross_count), 0) g2n,
        
        COALESCE(TRY(tot_accepted*100.00/gross_count), 0) "aor",
        
        
        median_cobrm_time,
        median_cobra_time,
        median_ocara_time,
        median_cancellation_time,
        median_acceptance_time,
        
        COALESCE(TRY(cobrm*100.00/gross_count), 0) "% cobrm",
        COALESCE(TRY(cobra*100.00/gross_count), 0) "% cobra",
        COALESCE(TRY(ocara*100.00/gross_count), 0) "% ocara",
        COALESCE(TRY(expired*100.00/gross_count), 0) "% expired",
        cobrm, 
        cobra,
        ocara,
        expired
    FROM    
        (
        SELECT
            test_group,
            event_type,
            click_type,
            retention_segment,
            COUNT(DISTINCT user_id) customers,
            COUNT(DISTINCT order_id) gross_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' AND spd_fraud_flag != true THEN order_id END) net_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN order_id END) AS tot_accepted,

        
           
            
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRM' THEN order_id END) cobrm,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRA' THEN order_id END) cobra,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'OCARA' THEN order_id END) ocara,
            COUNT(DISTINCT CASE WHEN order_status = 'expired' THEN order_id END) expired,
            
            approx_percentile(CASE WHEN modified_order_status = 'COBRM' THEN time_spent_in_sec END,0.50) as median_cobrm_time,
            approx_percentile(CASE WHEN modified_order_status = 'COBRA' THEN time_spent_in_sec END,0.50) as median_cobra_time,
            approx_percentile(CASE WHEN modified_order_status = 'OCARA' THEN time_spent_in_sec END,0.50) as median_ocara_time,
            approx_percentile(CASE WHEN modified_order_status in ('COBRA','COBRM','OCARA') THEN time_spent_in_sec END,0.50) as median_cancellation_time,
            approx_percentile(CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN time_taken_to_accp END,0.50) as median_acceptance_time
            
        FROM 
            merge
        where 
            yyyymmdd is not null
           and NOT (test_group = 'control' AND event_type IS NOT NULL)
           and NOT (event_type IS NULL AND click_type IS NOT NULL)
        GROUP BY 1,2,3,4
        )
    ORDER BY 1,2,3,4

"""

retention_segment_sports=pd.read_sql(retention_segment_query,conn)

/var/folders/km/1ltm54y105x6dzlcf44g881c0000gn/T/ipykernel_49271/1887586811.py:203: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  retention_segment_sports=pd.read_sql(retention_segment_query,conn)

In [74]:
retention_segment_sports

,test_group,event_type,click_type,retention_segment,customers,gross_count,net_count,g2n,aor,median_cobrm_time,median_cobra_time,median_ocara_time,median_cancellation_time,median_acceptance_time,% cobrm,% cobra,% ocara,% expired,cobrm,cobra,ocara,expired
0,control,None,None,DORMANT,5676,9929,6415,64.61,86.48,113.0,119.0,240.0,169.0,9.0,0.65,10.02,21.38,2.84,65,995,2123,282
1,control,None,None,ELITE,8758,41460,29426,70.97,86.23,62.0,98.0,242.0,149.0,10.0,0.44,10.48,14.90,2.85,181,4345,6177,1181
2,control,None,None,GOLD,10313,21589,15025,69.60,86.67,86.0,113.0,272.0,170.0,10.0,0.67,9.61,16.60,3.03,144,2075,3583,654
3,control,None,None,HH,1431,2810,1808,64.34,87.15,107.0,117.0,233.0,163.0,8.0,0.78,8.97,22.06,3.10,22,252,620,87
4,control,None,None,INACTIVE,384,681,311,45.67,83.26,71.0,90.0,42.0,55.0,7.0,1.76,10.87,37.00,4.11,12,74,252,28
5,control,None,None,PLATINUM,12023,31798,22528,70.85,86.88,83.0,108.0,262.0,163.0,9.0,0.50,9.73,15.63,2.88,160,3093,4970,916
6,control,None,None,PRIME,445,2373,1654,69.70,82.22,92.0,100.0,221.0,128.0,11.0,2.40,11.34,12.26,4.05,57,269,291,96
7,control,None,None,SILVER,4508,8004,5428,67.82,86.33,68.0,124.0,287.0,183.0,10.0,0.46,9.67,18.00,3.54,37,774,1441,283
8,control,None,None,UNKNOWN,125,357,93,26.05,83.19,108.0,111.0,147.0,115.0,8.0,6.44,7.84,56.30,2.52,23,28,201,9
9,control,None,None,None,6,6,6,100.00,100.00,NaN,NaN,NaN,NaN,8.0,0.00,0.00,0.00,0.00,0,0,0,0
10,test,viewed,close_click,DORMANT,4070,7009,4662,66.51,86.73,90.0,114.0,255.0,168.0,9.0,0.88,9.47,19.67,2.91,62,664,1379,204
11,test,viewed,close_click,ELITE,6684,30053,21239,70.67,86.24,49.0,100.0,226.0,143.0,10.0,0.63,10.39,15.21,2.72,189,3122,4570,818
12,test,viewed,close_click,GOLD,6979,14392,10092,70.12,87.03,69.0,116.0,291.0,180.0,9.0,0.57,9.64,16.44,2.75,82,1388,2366,396
13,test,viewed,close_click,HH,1074,2113,1353,64.03,84.81,32.0,115.0,269.0,169.0,9.0,2.22,8.47,20.07,4.50,47,179,424,95
14,test,viewed,close_click,INACTIVE,272,526,236,44.87,81.94,166.0,95.0,159.0,137.0,9.0,3.42,9.70,36.88,4.94,18,51,194,26
15,test,viewed,close_click,PLATINUM,8859,22944,16001,69.74,86.16,68.0,106.0,252.0,160.0,10.0,0.53,10.15,16.02,3.14,122,2329,3676,721
16,test,viewed,close_click,PRIME,385,2089,1517,72.62,84.11,77.0,106.0,183.0,129.0,11.0,0.86,10.15,10.87,4.88,18,212,227,102
17,test,viewed,close_click,SILVER,3212,5494,3759,68.42,85.55,89.0,126.0,249.0,173.0,10.0,0.69,9.97,16.62,3.77,38,548,913,207
18,test,viewed,close_click,UNKNOWN,83,227,58,25.55,80.18,144.0,113.0,107.0,110.0,8.0,5.29,9.69,54.19,4.85,12,22,123,11
19,test,viewed,play_click,DORMANT,176,255,141,55.29,83.53,NaN,155.0,96.0,126.0,9.0,0.00,11.76,27.06,4.71,0,30,69,12
20,test,viewed,play_click,ELITE,507,1137,739,65.00,82.50,17.0,91.0,209.0,116.0,11.0,0.62,14.25,17.06,2.64,7,162,194,30
21,test,viewed,play_click,GOLD,364,625,365,58.40,80.32,95.0,105.0,168.0,125.0,8.0,0.80,15.36,21.60,3.52,5,96,135,22
22,test,viewed,play_click,HH,84,148,90,60.81,84.46,NaN,89.0,202.0,122.0,12.0,0.00,12.16,22.97,3.38,0,18,34,5
23,test,viewed,play_click,INACTIVE,20,57,8,14.04,68.42,114.0,158.0,132.0,126.0,10.0,10.53,1.75,54.39,19.30,6,1,31,11
24,test,viewed,play_click,PLATINUM,446,786,521,66.28,86.26,13.0,93.0,184.0,120.0,10.0,0.25,10.94,19.72,2.54,2,86,155,20
25,test,viewed,play_click,PRIME,36,81,53,65.43,80.25,19.0,70.0,170.0,105.0,15.0,1.23,12.35,12.35,6.17,1,10,10,5
26,test,viewed,play_click,SILVER,174,257,163,63.42,84.05,22.0,93.0,240.0,177.0,10.0,0.39,11.28,20.62,4.28,1,29,53,11
27,test,viewed,play_click,UNKNOWN,10,32,1,3.13,34.38,70.0,87.0,50.0,70.0,5.0,18.75,18.75,28.13,28.13,6,6,9,9
28,test,viewed,play_click,None,1,1,0,0.00,0.00,NaN,NaN,NaN,NaN,NaN,0.00,0.00,0.00,100.00,0,0,0,1
29,test,viewed,None,DORMANT,89,149,68,45.64,87.25,27.0,71.0,94.0,79.0,8.0,2.01,9.40,39.60,1.34,3,14,59,2
30,test,viewed,None,ELITE,452,1032,742,71.90,87.50,127.0,100.0,235.0,157.0,10.0,0.48,8.62,15.02,3.39,5,89,155,35
31,test,viewed,None,GOLD,191,302,184,60.93,85.76,75.0,138.0,172.0,142.0,8.0,2.65,8.61,24.50,2.98,8,26,74,9
32,test,viewed,None,HH,27,55,18,32.73,92.73,NaN,30.0,34.0,30.0,6.0,0.00,5.45,58.18,1.82,0,3,32,1
33,test,viewed,None,INACTIVE,4,14,1,7.14,85.71,NaN,34.0,38.0,34.0,4.0,0.00,14.29,78.57,0.00,0,2,11,0
34,test,viewed,None,PLATINUM,309,503,385,76.54,92.05,7.0,117.0,301.0,203.0,9.0,0.20,6.36,15.31,1.19,1,32,77,6
35,test,viewed,None,PRIME,24,75,41,54.67,86.67,NaN,52.0,233.0,194.0,17.0,0.00,8.00,30.67,5.33,0,6,23,4
36,test,viewed,None,SILVER,67,104,54,51.92,80.77,NaN,142.0,124.0,134.0,8.0,0.00,14.42,27.88,4.81,0,15,29,5
37,test,viewed,None,UNKNOWN,5,20,0,0.00,85.00,35.0,NaN,41.0,40.0,5.0,10.00,0.00,85.00,5.00,2,0,17,1
38,test,None,None,DORMANT,1340,2217,1343,60.58,84.66,90.0,114.0,217.0,161.0,9.0,0.77,11.14,23.46,3.43,17,247,520,76
39,test,None,None,ELITE,3079,10651,7814,73.36,88.04,63.0,100.0,243.0,154.0,10.0,0.32,8.72,14.21,2.92,34,929,1514,311
40,test,None,None,GOLD,3264,5832,4175,71.59,88.27,129.0,116.0,270.0,178.0,10.0,0.26,8.64,16.24,2.83,15,504,947,165
41,test,None,None,HH,333,515,376,73.01,92.23,169.0,157.0,384.0,247.0,8.0,0.97,5.05,18.25,1.75,5,26,94,9
42,test,None,None,INACTIVE,86,179,86,48.04,87.15,22.0,171.0,32.0,38.0,6.0,2.79,7.26,38.55,2.79,5,13,69,5
43,test,None,None,PLATINUM,4138,8927,6415,71.86,87.59,48.0,107.0,237.0,154.0,9.0,0.58,9.28,15.37,2.54,52,828,1372,227
44,test,None,None,PRIME,160,651,474,72.81,84.64,107.0,86.0,217.0,117.0,10.0,0.31,12.44,11.06,2.61,2,81,72,17
45,test,None,None,SILVER,1296,2031,1400,68.93,86.56,13.0,103.0,263.0,172.0,9.0,0.34,10.14,16.79,2.90,7,206,341,59
46,test,None,None,UNKNOWN,56,100,44,44.00,85.00,119.0,82.0,396.0,203.0,9.0,4.00,8.00,41.00,3.00,4,8,41,3

In [75]:
service_query=f"""
with exp_category as(
select
    userid as user_id,
    case    when name='CaptainSearchSportsNewsTest' then 'test' 
            else 'control'
    end as test_group
from
   canonical.user_selector
where
    yyyymmdd = '20240905'
    and selectorid in ('66d9e70d8e21590001b635ac','66d9e97fdac1090001c05d83')

),

rr_net AS (
    SELECT 
        yyyymmdd, 
        customer_id,
        order_id, 
        order_status, 
        modified_order_status, 
        spd_fraud_flag,
        quarter_hour,
        CASE 
            WHEN modified_order_status IN ('OCARA', 'COBRA', 'COBRM') 
            THEN (customer_cancelled_epoch / 1000 - order_requested_epoch / 1000) 
        END AS time_spent_in_sec,
        CASE 
            WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') 
            THEN (rider_accepted_epoch / 1000 - order_requested_epoch / 1000)
        END AS time_taken_to_accp,
        CASE 
            WHEN service_obj_service_name IN ('Auto', 'Auto Lite', 'Auto NCR', 'Auto Pool', 'AutoPremium', 'CityAuto') THEN 'auto'
            WHEN service_obj_service_name IN ('Bike Lite', 'Bike Pink', 'Bike Metro', 'Link') THEN 'bike'
            WHEN service_obj_service_name IN ('CabEconomy', 'CabPremium') THEN 'cab'
            ELSE 'other'
        END AS service_category
        
    
    FROM 
        orders.order_logs_fact fact
    WHERE 
         yyyymmdd >= '20240911' AND yyyymmdd <= '20240915'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city_name = 'Hyderabad'
        AND service_obj_service_name in ('Auto','Auto Lite','Auto NCR','Auto Pool','AutoPremium','CityAuto','Link','Bike Lite','Bike Pink','CabEconomy','Bike Metro', 'CabPremium')
        AND channel_host='android'
        and customer_id in(
                select
                    user_id
        from 
            clevertap.clevertap_customer_order_activity
        where 
            yyyymmdd >= '20240911' AND yyyymmdd <= '20240915'
            AND order_activity_source = 'appOpen'
            and current_city = 'Hyderabad'
            and platform='Android'
            and app_version>='8.30.0'           
            )
         
),

view_tbl as(

    select
        yyyymmdd,
        profile_identity as user_id,
        'viewed' as event_type
    from 
        clevertap.customer_notification_viewed_immutable 
    where yyyymmdd >= '20240911' and yyyymmdd<='20240915'
    and event_props_campaign_id = '1725971334'

),

click_tbl as(
    select
        yyyymmdd,
        profile_identity as user_id,
        CASE
                    when event_props_wzrk_c2a='Button 2' then 'play_click'
                    else 'close_click'
        end as click_type
    from 
        clevertap.customer_notification_clicked_immutable
    where yyyymmdd >= '20240911' and yyyymmdd<='20240915'
    and event_props_campaign_id = '1725971334'

),

segment AS (
    
    SELECT
        customer_id,
        taxi_ltr_segment ltr_segment,
        taxi_retention_segments retention_segment,
        taxi_lifetime_stage lifetime_stage,
        taxi_service_affinity service_affinity,
        gender_tag gender
    FROM
        datasets.iallocator_customer_segments
    WHERE 
        run_date = '2024-09-11'
    
),


merge as(
    select exp_category.*,
            rr_net.service_category,
            rr_net.yyyymmdd,
            rr_net.order_id,
            rr_net.order_status,
            rr_net.modified_order_status,
            rr_net.spd_fraud_flag,
            rr_net.quarter_hour,
            rr_net.time_spent_in_sec,
            rr_net.time_taken_to_accp,
            view_tbl.event_type,
            click_tbl.click_type,
            segment.retention_segment
    from
        exp_category
    left join 
            rr_net 
        on exp_category.user_id=rr_net.customer_id
    left join
            view_tbl
        on rr_net.customer_id=view_tbl.user_id
           and rr_net.yyyymmdd=view_tbl.yyyymmdd
    left join
            click_tbl
        on view_tbl.user_id=click_tbl.user_id
        and view_tbl.yyyymmdd=click_tbl.yyyymmdd
    LEFT JOIN 
            segment
        ON rr_net.customer_id=segment.customer_id

)

SELECT
        test_group,
        event_type,
        click_type,
        service_category,
        customers,

        gross_count,
        net_count,
        
        COALESCE(TRY(net_count*100.00/gross_count), 0) g2n,
        
        COALESCE(TRY(tot_accepted*100.00/gross_count), 0) "aor",
        
        
        median_cobrm_time,
        median_cobra_time,
        median_ocara_time,
        median_cancellation_time,
        median_acceptance_time,
        
        COALESCE(TRY(cobrm*100.00/gross_count), 0) "% cobrm",
        COALESCE(TRY(cobra*100.00/gross_count), 0) "% cobra",
        COALESCE(TRY(ocara*100.00/gross_count), 0) "% ocara",
        COALESCE(TRY(expired*100.00/gross_count), 0) "% expired",
        cobrm, 
        cobra,
        ocara,
        expired
    FROM    
        (
        SELECT
            test_group,
            event_type,
            click_type,
            service_category,
            COUNT(DISTINCT user_id) customers,
            COUNT(DISTINCT order_id) gross_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' AND spd_fraud_flag != true THEN order_id END) net_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN order_id END) AS tot_accepted,

        
           
            
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRM' THEN order_id END) cobrm,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRA' THEN order_id END) cobra,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'OCARA' THEN order_id END) ocara,
            COUNT(DISTINCT CASE WHEN order_status = 'expired' THEN order_id END) expired,
            
            approx_percentile(CASE WHEN modified_order_status = 'COBRM' THEN time_spent_in_sec END,0.50) as median_cobrm_time,
            approx_percentile(CASE WHEN modified_order_status = 'COBRA' THEN time_spent_in_sec END,0.50) as median_cobra_time,
            approx_percentile(CASE WHEN modified_order_status = 'OCARA' THEN time_spent_in_sec END,0.50) as median_ocara_time,
            approx_percentile(CASE WHEN modified_order_status in ('COBRA','COBRM','OCARA') THEN time_spent_in_sec END,0.50) as median_cancellation_time,
            approx_percentile(CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN time_taken_to_accp END,0.50) as median_acceptance_time
            
        FROM 
            merge
        where 
            yyyymmdd is not null
           and NOT (test_group = 'control' AND event_type IS NOT NULL)
           and NOT (event_type IS NULL AND click_type IS NOT NULL)
        GROUP BY 1,2,3,4
        )
    ORDER BY 1,2,3,4

"""

service_sports=pd.read_sql(service_query,conn)

/var/folders/km/1ltm54y105x6dzlcf44g881c0000gn/T/ipykernel_49271/728547421.py:210: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  service_sports=pd.read_sql(service_query,conn)

In [76]:
service_sports

,test_group,event_type,click_type,service_category,customers,gross_count,net_count,g2n,aor,median_cobrm_time,median_cobra_time,median_ocara_time,median_cancellation_time,median_acceptance_time,% cobrm,% cobra,% ocara,% expired,cobrm,cobra,ocara,expired
0,control,None,None,auto,21232,46041,31648,68.74,87.59,75.0,115,241,173,7,1.00,7.88,18.78,3.53,460,3627,8647,1623
1,control,None,None,bike,27130,63105,45764,72.52,87.73,97.0,98,251,150,11,0.31,9.50,14.47,2.46,194,5996,9131,1552
2,control,None,None,cab,5089,9861,5282,53.56,72.69,102.0,117,301,156,19,0.48,23.14,19.07,3.66,47,2282,1880,361
3,test,viewed,close_click,auto,15504,33595,23026,68.54,87.30,51.0,108,242,169,7,1.16,7.89,18.69,3.64,389,2649,6279,1224
4,test,viewed,close_click,bike,19189,44050,32055,72.77,87.70,85.0,101,238,147,11,0.34,9.50,14.18,2.45,150,4183,6246,1078
5,test,viewed,close_click,cab,3712,7202,3836,53.26,72.06,96.0,119,286,159,19,0.68,23.37,18.70,3.86,49,1683,1347,278
6,test,viewed,play_click,auto,715,1218,730,59.93,83.83,22.0,105,180,133,8,1.81,10.10,23.81,4.27,22,123,290,52
7,test,viewed,play_click,bike,1160,1880,1241,66.01,85.21,172.0,82,170,111,11,0.32,11.22,18.40,3.24,6,211,346,61
8,test,viewed,play_click,cab,151,281,110,39.15,58.36,NaN,105,308,133,22,0.00,37.01,19.22,4.63,0,104,54,13
9,test,viewed,None,auto,494,847,561,66.23,90.20,65.0,134,108,111,7,1.77,5.55,23.97,2.48,15,47,203,21
10,test,viewed,None,bike,698,1235,853,69.07,88.34,27.0,94,249,162,11,0.24,8.26,18.14,3.16,3,102,224,39
11,test,viewed,None,cab,94,172,79,45.93,75.00,127.0,102,118,107,18,0.58,22.09,29.07,1.74,1,38,50,3
12,test,None,None,auto,5764,10881,7722,70.97,89.19,64.0,117,256,184,7,0.95,6.73,18.14,3.13,103,732,1974,341
13,test,None,None,bike,8924,17997,13173,73.20,88.22,86.0,98,237,148,11,0.12,9.17,14.25,2.48,22,1650,2565,447
14,test,None,None,cab,1265,2225,1232,55.37,74.79,55.0,120,241,150,17,0.72,20.67,19.37,3.78,16,460,431,84

In [93]:
cluster_level=f"""
with exp_category as(
select
    userid as user_id,
    case    when name='CaptainSearchSportsNewsTest' then 'test' 
            else 'control'
    end as test_group
from
   canonical.user_selector
where
    yyyymmdd = '20240905'
    and selectorid in ('66d9e70d8e21590001b635ac','66d9e97fdac1090001c05d83')

),

rr_net AS (
    SELECT 
        yyyymmdd, 
        customer_id,
        order_id, 
        order_status, 
        modified_order_status, 
        spd_fraud_flag,
        quarter_hour,
        CASE 
            WHEN pickup_cluster IN (              
                'Hitech City', 
                'Shamshabad', 
                'Kukatpally 3', 
                'Bodduppal', 
                'Mehedipatnam', 
                'Kothaguda 2', 
                'Mothinagar', 
                'Banjara Hills', 
                'Gandipet', 
                'Manikonda',
                'Marredpally'
            ) THEN pickup_cluster
            ELSE 'Other_clusters'
        END AS cluster_name,
        CASE 
            WHEN modified_order_status IN ('OCARA', 'COBRA', 'COBRM') 
            THEN (customer_cancelled_epoch / 1000 - order_requested_epoch / 1000) 
        END AS time_spent_in_sec,
        CASE 
            WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') 
            THEN (rider_accepted_epoch / 1000 - order_requested_epoch / 1000)
        END AS time_taken_to_accp,
        CASE 
            WHEN service_obj_service_name IN ('Auto', 'Auto Lite', 'Auto NCR', 'Auto Pool', 'AutoPremium', 'CityAuto') THEN 'auto'
            WHEN service_obj_service_name IN ('Bike Lite', 'Bike Pink', 'Bike Metro', 'Link') THEN 'bike'
            WHEN service_obj_service_name IN ('CabEconomy', 'CabPremium') THEN 'cab'
            ELSE 'other'
        END AS service_category
        
    
    FROM 
        orders.order_logs_fact fact
    WHERE 
         yyyymmdd >= '20240911' AND yyyymmdd <= '20240915'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city_name = 'Hyderabad'
        AND service_obj_service_name in ('Auto','Auto Lite','Auto NCR','Auto Pool','AutoPremium','CityAuto','Link','Bike Lite','Bike Pink','CabEconomy','Bike Metro', 'CabPremium')
        AND channel_host='android'
        and customer_id in(
                select
                    user_id
        from 
            clevertap.clevertap_customer_order_activity
        where 
            yyyymmdd >= '20240911' AND yyyymmdd <= '20240915'
            AND order_activity_source = 'appOpen'
            and current_city = 'Hyderabad'
            and platform='Android'
            and app_version>='8.30.0'           
            )
         
),

view_tbl as(

    select
        yyyymmdd,
        profile_identity as user_id,
        'viewed' as event_type
    from 
        clevertap.customer_notification_viewed_immutable 
    where yyyymmdd >= '20240911' and yyyymmdd<='20240915'
    and event_props_campaign_id = '1725971334'

),

click_tbl as(
    select
        yyyymmdd,
        profile_identity as user_id,
        CASE
                    when event_props_wzrk_c2a='Button 2' then 'play_click'
                    else 'close_click'
        end as click_type
    from 
        clevertap.customer_notification_clicked_immutable
    where yyyymmdd >= '20240911' and yyyymmdd<='20240915'
    and event_props_campaign_id = '1725971334'

),



merge as(
    select exp_category.*,
            rr_net.service_category,
            rr_net.yyyymmdd,
            rr_net.order_id,
            rr_net.cluster_name,
            rr_net.order_status,
            rr_net.modified_order_status,
            rr_net.spd_fraud_flag,
            rr_net.quarter_hour,
            rr_net.time_spent_in_sec,
            rr_net.time_taken_to_accp,
            view_tbl.event_type,
            click_tbl.click_type
            
    from
        exp_category
    left join 
            rr_net 
        on exp_category.user_id=rr_net.customer_id
    left join
            view_tbl
        on rr_net.customer_id=view_tbl.user_id
           and rr_net.yyyymmdd=view_tbl.yyyymmdd
    left join
            click_tbl
        on view_tbl.user_id=click_tbl.user_id
        and view_tbl.yyyymmdd=click_tbl.yyyymmdd
    
)

SELECT
        test_group,
        event_type,
        click_type,
        cluster_name,
        customers,

        gross_count,
        net_count,
        
        COALESCE(TRY(net_count*100.00/gross_count), 0) g2n,
        
        COALESCE(TRY(tot_accepted*100.00/gross_count), 0) "aor",
        
        
        median_cobrm_time,
        median_cobra_time,
        median_ocara_time,
        median_cancellation_time,
        median_acceptance_time,
        
        COALESCE(TRY(cobrm*100.00/gross_count), 0) "% cobrm",
        COALESCE(TRY(cobra*100.00/gross_count), 0) "% cobra",
        COALESCE(TRY(ocara*100.00/gross_count), 0) "% ocara",
        COALESCE(TRY(expired*100.00/gross_count), 0) "% expired",
        cobrm, 
        cobra,
        ocara,
        expired
    FROM    
        (
        SELECT
            test_group,
            event_type,
            click_type,
            cluster_name,
            COUNT(DISTINCT user_id) customers,
            COUNT(DISTINCT order_id) gross_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' AND spd_fraud_flag != true THEN order_id END) net_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN order_id END) AS tot_accepted,

        
           
            
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRM' THEN order_id END) cobrm,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRA' THEN order_id END) cobra,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'OCARA' THEN order_id END) ocara,
            COUNT(DISTINCT CASE WHEN order_status = 'expired' THEN order_id END) expired,
            
            approx_percentile(CASE WHEN modified_order_status = 'COBRM' THEN time_spent_in_sec END,0.50) as median_cobrm_time,
            approx_percentile(CASE WHEN modified_order_status = 'COBRA' THEN time_spent_in_sec END,0.50) as median_cobra_time,
            approx_percentile(CASE WHEN modified_order_status = 'OCARA' THEN time_spent_in_sec END,0.50) as median_ocara_time,
            approx_percentile(CASE WHEN modified_order_status in ('COBRA','COBRM','OCARA') THEN time_spent_in_sec END,0.50) as median_cancellation_time,
            approx_percentile(CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN time_taken_to_accp END,0.50) as median_acceptance_time
            
        FROM 
            merge
        where 
            yyyymmdd is not null
           and NOT (test_group = 'control' AND event_type IS NOT NULL)
           and NOT (event_type IS NULL AND click_type IS NOT NULL)
        GROUP BY 1,2,3,4
        )
    ORDER BY 1,2,3,4

"""

cluster_sports=pd.read_sql(cluster_level,conn)

/var/folders/km/1ltm54y105x6dzlcf44g881c0000gn/T/ipykernel_49271/1617297090.py:209: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  cluster_sports=pd.read_sql(cluster_level,conn)

In [95]:
cluster_sports=cluster_sports[cluster_sports['click_type']=='play_click']

In [96]:
cluster_sports

,test_group,event_type,click_type,cluster_name,customers,gross_count,net_count,g2n,aor,median_cobrm_time,median_cobra_time,median_ocara_time,median_cancellation_time,median_acceptance_time,% cobrm,% cobra,% ocara,% expired,cobrm,cobra,ocara,expired
24,test,viewed,play_click,Banjara Hills,45,68,35,51.47,77.94,119.0,148.0,227,148,13,1.47,14.71,26.47,5.88,1,10,18,4
25,test,viewed,play_click,Bodduppal,48,72,48,66.67,87.50,NaN,7.0,71,57,7,0.00,8.33,20.83,4.17,0,6,15,3
26,test,viewed,play_click,Gandipet,32,46,21,45.65,71.74,NaN,187.0,478,311,11,0.00,15.22,23.91,13.04,0,7,11,6
27,test,viewed,play_click,Hitech City,97,135,85,62.96,79.26,NaN,118.0,197,140,10,0.00,18.52,15.56,2.22,0,25,21,3
28,test,viewed,play_click,Kothaguda 2,40,59,35,59.32,72.88,NaN,116.0,92,98,10,0.00,16.95,13.56,10.17,0,10,8,6
29,test,viewed,play_click,Kukatpally 3,54,102,48,47.06,79.41,114.0,22.0,258,146,10,4.90,5.88,31.37,9.80,5,6,32,10
30,test,viewed,play_click,Manikonda,36,54,32,59.26,88.89,NaN,153.0,48,88,13,0.00,11.11,27.78,0.00,0,6,15,0
31,test,viewed,play_click,Marredpally,30,37,28,75.68,91.89,NaN,78.0,229,175,15,0.00,5.41,16.22,2.70,0,2,6,1
32,test,viewed,play_click,Mehedipatnam,43,65,38,58.46,81.54,NaN,96.0,160,124,11,0.00,15.38,23.08,3.08,0,10,15,2
33,test,viewed,play_click,Mothinagar,31,45,27,60.00,82.22,NaN,91.0,159,95,9,0.00,17.78,22.22,0.00,0,8,10,0
34,test,viewed,play_click,Other_clusters,1494,2616,1620,61.93,82.57,27.0,95.0,183,120,10,0.84,13.19,20.18,3.40,22,345,528,89
35,test,viewed,play_click,Shamshabad,64,83,66,79.52,92.77,NaN,90.0,812,260,7,0.00,4.82,13.25,2.41,0,4,11,2

In [97]:
cluster_sports.to_clipboard(index=False)

In [102]:
city_cluster_level=f"""


with rr_net AS (
    SELECT 
        yyyymmdd, 
        customer_id,
        order_id, 
        order_status, 
        modified_order_status, 
        spd_fraud_flag,
        quarter_hour,
        CASE 
            WHEN pickup_cluster IN (              
                'Hitech City', 
                'Shamshabad', 
                'Kukatpally 3', 
                'Bodduppal', 
                'Mehedipatnam', 
                'Kothaguda 2', 
                'Mothinagar', 
                'Banjara Hills', 
                'Gandipet', 
                'Manikonda',
                'Marredpally'
            ) THEN pickup_cluster
            ELSE 'Other_clusters'
        END AS cluster_name,
        CASE 
            WHEN modified_order_status IN ('OCARA', 'COBRA', 'COBRM') 
            THEN (customer_cancelled_epoch / 1000 - order_requested_epoch / 1000) 
        END AS time_spent_in_sec,
        CASE 
            WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') 
            THEN (rider_accepted_epoch / 1000 - order_requested_epoch / 1000)
        END AS time_taken_to_accp,
        CASE 
            WHEN service_obj_service_name IN ('Auto', 'Auto Lite', 'Auto NCR', 'Auto Pool', 'AutoPremium', 'CityAuto') THEN 'auto'
            WHEN service_obj_service_name IN ('Bike Lite', 'Bike Pink', 'Bike Metro', 'Link') THEN 'bike'
            WHEN service_obj_service_name IN ('CabEconomy', 'CabPremium') THEN 'cab'
            ELSE 'other'
        END AS service_category
        
    
    FROM 
        orders.order_logs_fact fact
    WHERE 
         yyyymmdd >= '20240911' AND yyyymmdd <= '20240915'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city_name = 'Hyderabad'
        AND service_obj_service_name in ('Auto','Auto Lite','Auto NCR','Auto Pool','AutoPremium','CityAuto','Link','Bike Lite','Bike Pink','CabEconomy','Bike Metro', 'CabPremium')
        AND channel_host='android'
        and customer_id in(
                select
                    user_id
        from 
            clevertap.clevertap_customer_order_activity
        where 
            yyyymmdd >= '20240911' AND yyyymmdd <= '20240915'
            AND order_activity_source = 'appOpen'
            and current_city = 'Hyderabad'
            and platform='Android'
            and app_version>='8.30.0'           
            )
         
)



SELECT
        
        cluster_name,
        customers,

        gross_count,
        net_count,
        
        COALESCE(TRY(net_count*100.00/gross_count), 0) g2n,
        
        COALESCE(TRY(tot_accepted*100.00/gross_count), 0) "aor",
        
        
        median_cobrm_time,
        median_cobra_time,
        median_ocara_time,
        median_cancellation_time,
        median_acceptance_time,
        
        COALESCE(TRY(cobrm*100.00/gross_count), 0) "% cobrm",
        COALESCE(TRY(cobra*100.00/gross_count), 0) "% cobra",
        COALESCE(TRY(ocara*100.00/gross_count), 0) "% ocara",
        COALESCE(TRY(expired*100.00/gross_count), 0) "% expired",
        cobrm, 
        cobra,
        ocara,
        expired
    FROM    
        (
        SELECT
            
            cluster_name,
            COUNT(DISTINCT customer_id) customers,
            COUNT(DISTINCT order_id) gross_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' AND spd_fraud_flag != true THEN order_id END) net_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN order_id END) AS tot_accepted,

        
           
            
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRM' THEN order_id END) cobrm,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRA' THEN order_id END) cobra,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'OCARA' THEN order_id END) ocara,
            COUNT(DISTINCT CASE WHEN order_status = 'expired' THEN order_id END) expired,
            
            approx_percentile(CASE WHEN modified_order_status = 'COBRM' THEN time_spent_in_sec END,0.50) as median_cobrm_time,
            approx_percentile(CASE WHEN modified_order_status = 'COBRA' THEN time_spent_in_sec END,0.50) as median_cobra_time,
            approx_percentile(CASE WHEN modified_order_status = 'OCARA' THEN time_spent_in_sec END,0.50) as median_ocara_time,
            approx_percentile(CASE WHEN modified_order_status in ('COBRA','COBRM','OCARA') THEN time_spent_in_sec END,0.50) as median_cancellation_time,
            approx_percentile(CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN time_taken_to_accp END,0.50) as median_acceptance_time
            
        FROM 
            rr_net
        where 
            yyyymmdd is not null
           
        GROUP BY 1
        )
    ORDER BY 1

"""

city_cluster_level_sports=pd.read_sql(city_cluster_level,conn)

/var/folders/km/1ltm54y105x6dzlcf44g881c0000gn/T/ipykernel_49271/1215307344.py:133: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  city_cluster_level_sports=pd.read_sql(city_cluster_level,conn)

In [103]:
city_cluster_level_sports

,cluster_name,customers,gross_count,net_count,g2n,aor,median_cobrm_time,median_cobra_time,median_ocara_time,median_cancellation_time,median_acceptance_time,% cobrm,% cobra,% ocara,% expired,cobrm,cobra,ocara,expired
0,Banjara Hills,26839,48199,30155,62.56,81.51,58,112,292,174,15,1.10,12.42,18.59,4.95,531,5987,8962,2385
1,Bodduppal,17235,29578,23840,80.60,94.70,46,104,242,182,7,0.26,3.54,13.58,1.50,78,1046,4017,444
2,Gandipet,5888,11493,6298,54.80,74.66,97,126,270,167,10,1.70,16.91,19.46,6.72,195,1943,2236,772
3,Hitech City,48650,93937,58193,61.95,79.71,61,111,236,152,11,0.98,13.90,17.46,5.40,919,13058,16399,5070
4,Kothaguda 2,15429,28542,18166,63.65,81.43,88,117,265,164,11,0.77,12.87,17.41,4.92,220,3673,4969,1404
5,Kukatpally 3,23890,39811,29656,74.49,91.20,29,101,248,174,9,0.46,5.73,16.24,2.60,182,2282,6466,1037
6,Manikonda,15328,28261,19683,69.65,87.18,31,113,254,169,10,0.27,9.29,17.20,3.25,76,2625,4862,919
7,Marredpally,14962,24039,17707,73.66,90.17,37,105,272,180,10,0.21,7.54,16.12,2.06,51,1813,3874,495
8,Mehedipatnam,26973,48199,33653,69.82,87.44,59,105,270,176,11,0.89,7.80,17.25,3.86,430,3760,8315,1861
9,Mothinagar,14314,26627,17350,65.16,83.74,98,115,279,178,11,0.99,10.76,18.26,4.50,264,2864,4863,1199
10,Other_clusters,758227,1839171,1269662,69.03,86.29,74,112,270,173,10,0.76,9.34,16.86,3.60,13899,171832,310097,66237
11,Shamshabad,40218,69883,51090,73.11,91.68,89,108,252,184,7,0.42,5.95,18.12,1.94,293,4157,12660,1359

In [104]:
city_cluster_level_sports.to_clipboard(index=False)

In [105]:
cluster_session_level=f"""
with exp_category as(
select
    userid as user_id,
    case    when name='CaptainSearchSportsNewsTest' then 'test' 
            else 'control'
    end as test_group
from
   canonical.user_selector
where
    yyyymmdd = '20240905'
    and selectorid in ('66d9e70d8e21590001b635ac','66d9e97fdac1090001c05d83')

),

rr_net AS (
    SELECT 
        yyyymmdd, 
        customer_id,
        order_id, 
        order_status, 
        modified_order_status, 
        spd_fraud_flag,
        quarter_hour,
        CASE 
            WHEN pickup_cluster IN (              
                'Hitech City', 
                'Shamshabad', 
                'Kukatpally 3', 
                'Bodduppal', 
                'Mehedipatnam', 
                'Kothaguda 2', 
                'Mothinagar', 
                'Banjara Hills', 
                'Gandipet', 
                'Manikonda',
                'Marredpally'
            ) THEN pickup_cluster
            ELSE 'Other_clusters'
        END AS cluster_name,
        CASE 
            WHEN modified_order_status IN ('OCARA', 'COBRA', 'COBRM') 
            THEN (customer_cancelled_epoch / 1000 - order_requested_epoch / 1000) 
        END AS time_spent_in_sec,
        CASE 
            WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') 
            THEN (rider_accepted_epoch / 1000 - order_requested_epoch / 1000)
        END AS time_taken_to_accp,
        CASE 
            WHEN service_obj_service_name IN ('Auto', 'Auto Lite', 'Auto NCR', 'Auto Pool', 'AutoPremium', 'CityAuto') THEN 'auto'
            WHEN service_obj_service_name IN ('Bike Lite', 'Bike Pink', 'Bike Metro', 'Link') THEN 'bike'
            WHEN service_obj_service_name IN ('CabEconomy', 'CabPremium') THEN 'cab'
            ELSE 'other'
        END AS service_category
        
    
    FROM 
        orders.order_logs_fact fact
    WHERE 
         yyyymmdd >= '20240911' AND yyyymmdd <= '20240915'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city_name = 'Hyderabad'
        AND service_obj_service_name in ('Auto','Auto Lite','Auto NCR','Auto Pool','AutoPremium','CityAuto','Link','Bike Lite','Bike Pink','CabEconomy','Bike Metro', 'CabPremium')
        AND channel_host='android'
        and customer_id in(
                select
                    user_id
        from 
            clevertap.clevertap_customer_order_activity
        where 
            yyyymmdd >= '20240911' AND yyyymmdd <= '20240915'
            AND order_activity_source = 'appOpen'
            and current_city = 'Hyderabad'
            and platform='Android'
            and app_version>='8.30.0'           
            )
         
),

view_tbl as(

    select
        yyyymmdd,
        profile_identity as user_id,
        'viewed' as event_type
    from 
        clevertap.customer_notification_viewed_immutable 
    where yyyymmdd >= '20240911' and yyyymmdd<='20240915'
    and event_props_campaign_id = '1725971334'

),

click_tbl as(
    select
        yyyymmdd,
        profile_identity as user_id,
        CASE
                    when event_props_wzrk_c2a='Button 2' then 'play_click'
                    else 'close_click'
        end as click_type
    from 
        clevertap.customer_notification_clicked_immutable
    where yyyymmdd >= '20240911' and yyyymmdd<='20240915'
    and event_props_campaign_id = '1725971334'

),



merge as(
    select exp_category.*,
            rr_net.service_category,
            rr_net.yyyymmdd,
            rr_net.order_id,
            rr_net.cluster_name,
            rr_net.order_status,
            rr_net.modified_order_status,
            rr_net.spd_fraud_flag,
            rr_net.quarter_hour,
            rr_net.time_spent_in_sec,
            rr_net.time_taken_to_accp,
            view_tbl.event_type,
            click_tbl.click_type
            
    from
        exp_category
    left join 
            rr_net 
        on exp_category.user_id=rr_net.customer_id
    left join
            view_tbl
        on rr_net.customer_id=view_tbl.user_id
           and rr_net.yyyymmdd=view_tbl.yyyymmdd
    left join
            click_tbl
        on view_tbl.user_id=click_tbl.user_id
        and view_tbl.yyyymmdd=click_tbl.yyyymmdd
    
)

SELECT
        test_group,
        event_type,
        click_type,
        time_period,
        cluster_name,
        customers,

        gross_count,
        net_count,
        
        COALESCE(TRY(net_count*100.00/gross_count), 0) g2n,
        
        COALESCE(TRY(tot_accepted*100.00/gross_count), 0) "aor",
        
        
        median_cobrm_time,
        median_cobra_time,
        median_ocara_time,
        median_cancellation_time,
        median_acceptance_time,
        
        COALESCE(TRY(cobrm*100.00/gross_count), 0) "% cobrm",
        COALESCE(TRY(cobra*100.00/gross_count), 0) "% cobra",
        COALESCE(TRY(ocara*100.00/gross_count), 0) "% ocara",
        COALESCE(TRY(expired*100.00/gross_count), 0) "% expired",
        cobrm, 
        cobra,
        ocara,
        expired
    FROM    
        (
        SELECT
            test_group,
            event_type,
            click_type,
            case
                WHEN quarter_hour >= '0800' AND quarter_hour < '1100' THEN 'morning'
                WHEN quarter_hour >= '1100' AND quarter_hour < '1700' THEN 'afternoon'
                WHEN quarter_hour >= '1700' AND quarter_hour < '2100' THEN 'evening'
                WHEN quarter_hour >= '0000' AND quarter_hour < '0800' THEN 'rest_morning'
                ELSE 'rest_evening'
            end as time_period,
            cluster_name,
            COUNT(DISTINCT user_id) customers,
            COUNT(DISTINCT order_id) gross_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' AND spd_fraud_flag != true THEN order_id END) net_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN order_id END) AS tot_accepted,

        
           
            
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRM' THEN order_id END) cobrm,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRA' THEN order_id END) cobra,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'OCARA' THEN order_id END) ocara,
            COUNT(DISTINCT CASE WHEN order_status = 'expired' THEN order_id END) expired,
            
            approx_percentile(CASE WHEN modified_order_status = 'COBRM' THEN time_spent_in_sec END,0.50) as median_cobrm_time,
            approx_percentile(CASE WHEN modified_order_status = 'COBRA' THEN time_spent_in_sec END,0.50) as median_cobra_time,
            approx_percentile(CASE WHEN modified_order_status = 'OCARA' THEN time_spent_in_sec END,0.50) as median_ocara_time,
            approx_percentile(CASE WHEN modified_order_status in ('COBRA','COBRM','OCARA') THEN time_spent_in_sec END,0.50) as median_cancellation_time,
            approx_percentile(CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN time_taken_to_accp END,0.50) as median_acceptance_time
            
        FROM 
            merge
        where 
            yyyymmdd is not null
           and NOT (test_group = 'control' AND event_type IS NOT NULL)
           and NOT (event_type IS NULL AND click_type IS NOT NULL)
        GROUP BY 1,2,3,4,5
        )
    ORDER BY 1,2,3,4,5

"""

cluster_session_level_sports=pd.read_sql(cluster_session_level,conn)

/var/folders/km/1ltm54y105x6dzlcf44g881c0000gn/T/ipykernel_49271/290345653.py:217: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  cluster_session_level_sports=pd.read_sql(cluster_session_level,conn)

In [110]:
cluster_session_level_sports

,test_group,event_type,click_type,time_period,cluster_name,customers,gross_count,net_count,g2n,aor,median_cobrm_time,median_cobra_time,median_ocara_time,median_cancellation_time,median_acceptance_time,% cobrm,% cobra,% ocara,% expired,cobrm,cobra,ocara,expired
120,test,viewed,play_click,afternoon,Banjara Hills,17,24,17,70.83,83.33,NaN,148.0,101.0,137.0,9.0,0.00,8.33,12.50,8.33,0,2,3,2
121,test,viewed,play_click,afternoon,Bodduppal,18,20,16,80.00,90.00,NaN,6.0,984.0,57.0,7.0,0.00,10.00,10.00,0.00,0,2,2,0
122,test,viewed,play_click,afternoon,Gandipet,13,17,8,47.06,76.47,NaN,387.0,525.0,478.0,7.0,0.00,11.76,23.53,11.76,0,2,4,2
123,test,viewed,play_click,afternoon,Hitech City,38,49,35,71.43,91.84,NaN,104.0,196.0,135.0,8.0,0.00,8.16,18.37,0.00,0,4,9,0
124,test,viewed,play_click,afternoon,Kothaguda 2,10,11,8,72.73,90.91,NaN,136.0,344.0,136.0,6.0,0.00,9.09,18.18,0.00,0,1,2,0
125,test,viewed,play_click,afternoon,Kukatpally 3,23,41,18,43.90,85.37,114.0,22.0,290.0,149.0,10.0,4.88,2.44,39.02,7.32,2,1,16,3
126,test,viewed,play_click,afternoon,Manikonda,17,22,14,63.64,86.36,NaN,13.0,169.0,144.0,13.0,0.00,13.64,22.73,0.00,0,3,5,0
127,test,viewed,play_click,afternoon,Marredpally,13,14,12,85.71,92.86,NaN,NaN,4240.0,4240.0,17.0,0.00,0.00,7.14,7.14,0,0,1,1
128,test,viewed,play_click,afternoon,Mehedipatnam,14,20,11,55.00,70.00,NaN,96.0,133.0,96.0,15.0,0.00,30.00,15.00,0.00,0,6,3,0
129,test,viewed,play_click,afternoon,Mothinagar,13,19,13,68.42,94.74,NaN,20.0,46.0,46.0,8.0,0.00,5.26,26.32,0.00,0,1,5,0
130,test,viewed,play_click,afternoon,Other_clusters,593,903,587,65.01,86.38,17.0,104.0,132.0,107.0,9.0,1.00,9.52,20.82,3.10,9,86,188,28
131,test,viewed,play_click,afternoon,Shamshabad,27,30,24,80.00,93.33,NaN,16.0,570.0,71.0,8.0,0.00,3.33,13.33,3.33,0,1,4,1
132,test,viewed,play_click,evening,Banjara Hills,17,26,9,34.62,57.69,119.0,148.0,227.0,159.0,16.0,3.85,30.77,23.08,7.69,1,8,6,2
133,test,viewed,play_click,evening,Bodduppal,12,18,11,61.11,100.00,NaN,NaN,54.0,54.0,7.0,0.00,0.00,38.89,0.00,0,0,7,0
134,test,viewed,play_click,evening,Gandipet,9,13,8,61.54,76.92,NaN,NaN,326.0,326.0,13.0,0.00,0.00,15.38,23.08,0,0,2,3
135,test,viewed,play_click,evening,Hitech City,37,50,25,50.00,64.00,NaN,125.0,145.0,130.0,11.0,0.00,30.00,14.00,6.00,0,15,7,3
136,test,viewed,play_click,evening,Kothaguda 2,12,14,10,71.43,85.71,NaN,204.0,92.0,92.0,13.0,0.00,14.29,14.29,0.00,0,2,2,0
137,test,viewed,play_click,evening,Kukatpally 3,12,17,10,58.82,70.59,248.0,NaN,275.0,248.0,12.0,11.76,0.00,11.76,17.65,2,0,2,3
138,test,viewed,play_click,evening,Manikonda,6,7,6,85.71,100.00,NaN,NaN,44.0,44.0,14.0,0.00,0.00,14.29,0.00,0,0,1,0
139,test,viewed,play_click,evening,Marredpally,11,15,8,53.33,86.67,NaN,78.0,175.0,78.0,14.0,0.00,13.33,33.33,0.00,0,2,5,0
140,test,viewed,play_click,evening,Mehedipatnam,14,20,10,50.00,85.00,NaN,154.0,160.0,154.0,9.0,0.00,10.00,35.00,5.00,0,2,7,1
141,test,viewed,play_click,evening,Mothinagar,5,6,5,83.33,100.00,NaN,NaN,353.0,353.0,6.0,0.00,0.00,16.67,0.00,0,0,1,0
142,test,viewed,play_click,evening,Other_clusters,543,745,454,60.94,82.55,37.0,72.0,193.0,121.0,11.0,1.34,11.68,21.34,4.43,10,87,159,33
143,test,viewed,play_click,evening,Shamshabad,24,27,23,85.19,100.00,NaN,NaN,1587.0,1587.0,7.0,0.00,0.00,14.81,0.00,0,0,4,0
144,test,viewed,play_click,morning,Banjara Hills,5,7,4,57.14,100.00,NaN,NaN,105.0,105.0,34.0,0.00,0.00,42.86,0.00,0,0,3,0
145,test,viewed,play_click,morning,Bodduppal,13,19,12,63.16,84.21,NaN,8.0,265.0,151.0,8.0,0.00,10.53,21.05,5.26,0,2,4,1
146,test,viewed,play_click,morning,Gandipet,7,10,4,40.00,80.00,NaN,311.0,1038.0,311.0,16.0,0.00,20.00,40.00,0.00,0,2,4,0
147,test,viewed,play_click,morning,Hitech City,10,12,7,58.33,66.67,NaN,159.0,398.0,159.0,17.0,0.00,33.33,8.33,0.00,0,4,1,0
148,test,viewed,play_click,morning,Kothaguda 2,12,24,9,37.50,45.83,NaN,98.0,904.0,116.0,26.0,0.00,29.17,8.33,25.00,0,7,2,6
149,test,viewed,play_click,morning,Kukatpally 3,8,13,6,46.15,53.85,NaN,87.0,290.0,108.0,11.0,0.00,23.08,7.69,23.08,0,3,1,3
150,test,viewed,play_click,morning,Manikonda,10,16,8,50.00,93.75,NaN,153.0,19.0,25.0,18.0,0.00,6.25,43.75,0.00,0,1,7,0
151,test,viewed,play_click,morning,Marredpally,3,4,4,100.00,100.00,NaN,NaN,NaN,NaN,8.0,0.00,0.00,0.00,0.00,0,0,0,0
152,test,viewed,play_click,morning,Mehedipatnam,6,9,5,55.56,66.67,NaN,131.0,265.0,131.0,13.0,0.00,22.22,11.11,11.11,0,2,1,1
153,test,viewed,play_click,morning,Mothinagar,10,12,6,50.00,58.33,NaN,95.0,122.0,108.0,17.0,0.00,41.67,8.33,0.00,0,5,1,0
154,test,viewed,play_click,morning,Other_clusters,293,424,254,59.91,77.12,27.0,112.0,190.0,134.0,10.0,0.24,19.10,16.98,3.54,1,81,72,15
155,test,viewed,play_click,morning,Shamshabad,7,10,7,70.00,80.00,NaN,196.0,935.0,196.0,74.0,0.00,20.00,10.00,0.00,0,2,1,0
156,test,viewed,play_click,rest_evening,Banjara Hills,5,6,3,50.00,100.00,NaN,NaN,254.0,254.0,14.0,0.00,0.00,50.00,0.00,0,0,3,0
157,test,viewed,play_click,rest_evening,Bodduppal,7,8,6,75.00,87.50,NaN,153.0,283.0,283.0,5.0,0.00,12.50,12.50,0.00,0,1,1,0
158,test,viewed,play_click,rest_evening,Gandipet,4,6,1,16.67,33.33,NaN,82.0,1167.0,88.0,305.0,0.00,50.00,16.67,16.67,0,3,1,1
159,test,viewed,play_click,rest_evening,Hitech City,15,17,12,70.59,88.24,NaN,183.0,197.0,183.0,16.0,0.00,11.76,17.65,0.00,0,2,3,0
160,test,viewed,play_click,rest_evening,Kothaguda 2,6,6,6,100.00,100.00,NaN,NaN,NaN,NaN,8.0,0.00,0.00,0.00,0.00,0,0,0,0
161,test,viewed,play_click,rest_evening,Kukatpally 3,8,10,6,60.00,70.00,217.0,195.0,27.0,217.0,7.0,10.00,10.00,10.00,10.00,1,1,1,1
162,test,viewed,play_click,rest_evening,Manikonda,5,6,3,50.00,66.67,NaN,279.0,376.0,279.0,7.0,0.00,33.33,16.67,0.00,0,2,1,0
163,test,viewed,play_click,rest_evening,Marredpally,3,3,3,100.00,100.00,NaN,NaN,NaN,NaN,19.0,0.00,0.00,0.00,0.00,0,0,0,0
164,test,viewed,play_click,rest_evening,Mehedipatnam,10,11,8,72.73,100.00,NaN,NaN,690.0,690.0,8.0,0.00,0.00,27.27,0.00,0,0,3,0
165,test,viewed,play_click,rest_evening,Mothinagar,3,4,3,75.00,100.00,NaN,NaN,39.0,39.0,12.0,0.00,0.00,25.00,0.00,0,0,1,0
166,test,viewed,play_click,rest_evening,Other_clusters,238,327,187,57.19,78.90,95.0,94.0,266.0,145.0,16.0,0.31,18.35,21.10,2.45,1,60,69,8
167,test,viewed,play_click,rest_evening,Shamshabad,12,15,11,73.33,86.67,NaN,58.0,812.0,260.0,7.0,0.00,6.67,13.33,6.67,0,1,2,1
168,test,viewed,play_click,rest_morning,Banjara Hills,4,5,2,40.00,100.00,NaN,NaN,18.0,18.0,5.0,0.00,0.00,60.00,0.00,0,0,3,0
169,test,viewed,play_click,rest_morning,Bodduppal,5,7,3,42.86,57.14,NaN,7.0,43.0,43.0,13.0,0.00,14.29,14.29,28.57,0,1,1,2
170,test,viewed,play_click,rest_morning,Hitech City,7,7,6,85.71,100.00,NaN,NaN,235.0,235.0,5.0,0.00,0.00,14.29,0.00,0,0,1,0
171,test,viewed,play_click,rest_morning,Kothaguda 2,4,4,2,50.00,100.00,NaN,NaN,999.0,999.0,9.0,0.00,0.00,50.00,0.00,0,0,2,0
172,test,viewed,play_click,rest_morning,Kukatpally 3,10,21,8,38.10,95.24,NaN,53.0,135.0,135.0,10.0,0.00,4.76,57.14,0.00,0,1,12,0
173,test,viewed,play_click,rest_morning,Manikonda,3,3,1,33.33,100.00,NaN,NaN,857.0,857.0,13.0,0.00,0.00,33.33,0.00,0,0,1,0
174,test,viewed,play_click,rest_morning,Marredpally,1,1,1,100.00,100.00,NaN,NaN,NaN,NaN,4.0,0.00,0.00,0.00,0.00,0,0,0,0
175,test,viewed,play_click,rest_morning,Mehedipatnam,4,5,4,80.00,100.00,NaN,NaN,24.0,24.0,24.0,0.00,0.00,20.00,0.00,0,0,1,0
176,test,viewed,play_click,rest_morning,Mothinagar,1,4,0,0.00,50.00,NaN,82.0,174.0,159.0,73.0,0.00,50.00,50.00,0.00,0,2,2,0
177,test,viewed,play_click,rest_morning,Other_clusters,163,217,138,63.59,82.95,243.0,80.0,155.0,103.0,7.0,0.46,14.29,18.43,2.30,1,31,40,5
178,test,viewed,play_click,rest_morning,Shamshabad,1,1,1,100.00,100.00,NaN,NaN,NaN,NaN,5.0,0.00,0.00,0.00,0.00,0,0,0,0

In [109]:
cluster_session_level_sports=cluster_session_level_sports[cluster_session_level_sports['click_type']=='play_click']

In [111]:
cluster_session_level_sports.to_clipboard(index=False)

In [107]:
city_cluster_level_benchmark=f"""


with rr_net AS (
    SELECT 
        yyyymmdd, 
        customer_id,
        order_id, 
        order_status, 
        modified_order_status, 
        spd_fraud_flag,
        quarter_hour,
        CASE 
            WHEN pickup_cluster IN (              
                'Hitech City', 
                'Shamshabad', 
                'Kukatpally 3', 
                'Bodduppal', 
                'Mehedipatnam', 
                'Kothaguda 2', 
                'Mothinagar', 
                'Banjara Hills', 
                'Gandipet', 
                'Manikonda',
                'Marredpally'
            ) THEN pickup_cluster
            ELSE 'Other_clusters'
        END AS cluster_name,
        CASE 
            WHEN modified_order_status IN ('OCARA', 'COBRA', 'COBRM') 
            THEN (customer_cancelled_epoch / 1000 - order_requested_epoch / 1000) 
        END AS time_spent_in_sec,
        CASE 
            WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') 
            THEN (rider_accepted_epoch / 1000 - order_requested_epoch / 1000)
        END AS time_taken_to_accp,
        CASE 
            WHEN service_obj_service_name IN ('Auto', 'Auto Lite', 'Auto NCR', 'Auto Pool', 'AutoPremium', 'CityAuto') THEN 'auto'
            WHEN service_obj_service_name IN ('Bike Lite', 'Bike Pink', 'Bike Metro', 'Link') THEN 'bike'
            WHEN service_obj_service_name IN ('CabEconomy', 'CabPremium') THEN 'cab'
            ELSE 'other'
        END AS service_category
        
    
    FROM 
        orders.order_logs_fact fact
    WHERE 
         yyyymmdd >= '20240911' AND yyyymmdd <= '20240915'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city_name = 'Hyderabad'
        AND service_obj_service_name in ('Auto','Auto Lite','Auto NCR','Auto Pool','AutoPremium','CityAuto','Link','Bike Lite','Bike Pink','CabEconomy','Bike Metro', 'CabPremium')
        AND channel_host='android'
        and customer_id in(
                select
                    user_id
        from 
            clevertap.clevertap_customer_order_activity
        where 
            yyyymmdd >= '20240911' AND yyyymmdd <= '20240915'
            AND order_activity_source = 'appOpen'
            and current_city = 'Hyderabad'
            and platform='Android'
            and app_version>='8.30.0'           
            )
         
)



SELECT
        time_period,
        cluster_name,
        customers,

        gross_count,
        net_count,
        
        COALESCE(TRY(net_count*100.00/gross_count), 0) g2n,
        
        COALESCE(TRY(tot_accepted*100.00/gross_count), 0) "aor",
        
        
        median_cobrm_time,
        median_cobra_time,
        median_ocara_time,
        median_cancellation_time,
        median_acceptance_time,
        
        COALESCE(TRY(cobrm*100.00/gross_count), 0) "% cobrm",
        COALESCE(TRY(cobra*100.00/gross_count), 0) "% cobra",
        COALESCE(TRY(ocara*100.00/gross_count), 0) "% ocara",
        COALESCE(TRY(expired*100.00/gross_count), 0) "% expired",
        cobrm, 
        cobra,
        ocara,
        expired
    FROM    
        (
        SELECT
            case
                WHEN quarter_hour >= '0800' AND quarter_hour < '1100' THEN 'morning'
                WHEN quarter_hour >= '1100' AND quarter_hour < '1700' THEN 'afternoon'
                WHEN quarter_hour >= '1700' AND quarter_hour < '2100' THEN 'evening'
                WHEN quarter_hour >= '0000' AND quarter_hour < '0800' THEN 'rest_morning'
                ELSE 'rest_evening'
            end as time_period,
            cluster_name,
            COUNT(DISTINCT customer_id) customers,
            COUNT(DISTINCT order_id) gross_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' AND spd_fraud_flag != true THEN order_id END) net_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN order_id END) AS tot_accepted,

        
           
            
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRM' THEN order_id END) cobrm,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRA' THEN order_id END) cobra,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'OCARA' THEN order_id END) ocara,
            COUNT(DISTINCT CASE WHEN order_status = 'expired' THEN order_id END) expired,
            
            approx_percentile(CASE WHEN modified_order_status = 'COBRM' THEN time_spent_in_sec END,0.50) as median_cobrm_time,
            approx_percentile(CASE WHEN modified_order_status = 'COBRA' THEN time_spent_in_sec END,0.50) as median_cobra_time,
            approx_percentile(CASE WHEN modified_order_status = 'OCARA' THEN time_spent_in_sec END,0.50) as median_ocara_time,
            approx_percentile(CASE WHEN modified_order_status in ('COBRA','COBRM','OCARA') THEN time_spent_in_sec END,0.50) as median_cancellation_time,
            approx_percentile(CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN time_taken_to_accp END,0.50) as median_acceptance_time
            
        FROM 
            rr_net
        where 
            yyyymmdd is not null
           
        GROUP BY 1,2
        )
    ORDER BY 1,2

"""

city_cluster_level_sports_benchmark=pd.read_sql(city_cluster_level_benchmark,conn)

/var/folders/km/1ltm54y105x6dzlcf44g881c0000gn/T/ipykernel_49271/2430106976.py:139: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  city_cluster_level_sports_benchmark=pd.read_sql(city_cluster_level_benchmark,conn)

In [108]:
city_cluster_level_sports_benchmark

,time_period,cluster_name,customers,gross_count,net_count,g2n,aor,median_cobrm_time,median_cobra_time,median_ocara_time,median_cancellation_time,median_acceptance_time,% cobrm,% cobra,% ocara,% expired,cobrm,cobra,ocara,expired
0,afternoon,Banjara Hills,12097,17456,12200,69.89,87.89,51,113,285,184,12,0.52,8.81,17.71,2.78,90,1538,3091,486
1,afternoon,Bodduppal,7836,11007,9144,83.07,96.24,56,108,253,205,6,0.09,2.54,12.69,1.13,10,280,1397,124
2,afternoon,Gandipet,2627,4144,2443,58.95,78.21,82,120,257,160,9,1.35,15.18,18.99,5.26,56,629,787,218
3,afternoon,Hitech City,19223,27480,20754,75.52,92.77,53,90,225,165,8,0.52,4.97,16.90,1.75,142,1366,4644,480
4,afternoon,Kothaguda 2,6412,9064,6757,74.55,91.38,100,102,257,183,9,0.50,5.78,16.49,2.34,45,524,1495,212
5,afternoon,Kukatpally 3,10241,14279,11130,77.95,93.99,69,96,264,191,8,0.29,4.15,15.64,1.57,42,592,2233,224
6,afternoon,Manikonda,6549,9624,7187,74.68,91.41,26,101,246,173,9,0.25,6.11,16.51,2.23,24,588,1589,215
7,afternoon,Marredpally,6938,9748,7139,73.24,89.55,60,106,299,190,11,0.19,7.77,15.99,2.48,19,757,1559,242
8,afternoon,Mehedipatnam,12660,19227,13793,71.74,89.17,34,102,274,182,11,0.68,6.90,17.09,3.26,130,1326,3286,627
9,afternoon,Mothinagar,5884,8567,6220,72.60,90.76,74,106,277,187,10,0.93,6.16,17.87,2.15,80,528,1531,184
10,afternoon,Other_clusters,381829,670013,486446,72.60,89.50,64,112,278,187,9,0.54,7.16,16.55,2.80,3602,47951,110871,18761
11,afternoon,Shamshabad,17877,25977,19467,74.94,92.34,84,110,262,194,7,0.28,5.55,16.96,1.82,73,1443,4405,474
12,evening,Banjara Hills,9674,16305,8147,49.97,71.09,63,113,310,168,33,1.87,18.85,20.71,8.15,305,3074,3377,1329
13,evening,Bodduppal,5197,7028,5787,82.34,96.16,24,85,245,192,6,0.27,2.18,13.20,1.39,19,153,928,98
14,evening,Gandipet,2052,3594,1760,48.97,69.34,80,128,310,174,14,1.11,20.73,19.89,8.82,40,745,715,317
15,evening,Hitech City,19216,34872,16489,47.28,65.79,64,119,257,150,19,1.46,22.80,18.24,9.93,508,7952,6359,3464
16,evening,Kothaguda 2,4749,7279,4536,62.32,83.21,111,113,264,168,15,0.66,12.53,20.48,3.57,48,912,1491,260
17,evening,Kukatpally 3,7211,10163,7647,75.24,92.77,20,76,242,179,11,0.35,3.88,16.99,2.98,36,394,1727,303
18,evening,Manikonda,4902,7235,5042,69.69,88.42,31,109,285,184,11,0.17,8.93,18.31,2.47,12,646,1325,179
19,evening,Marredpally,4776,6536,4736,72.46,90.68,30,105,267,182,11,0.20,7.18,17.82,1.91,13,469,1165,125
20,evening,Mehedipatnam,9077,13210,8789,66.53,85.40,73,103,285,177,12,1.33,8.35,18.53,4.90,176,1103,2448,647
21,evening,Mothinagar,3852,5217,3798,72.80,92.29,21,94,304,226,9,0.25,4.77,19.13,2.68,13,249,998,140
22,evening,Other_clusters,296761,499027,335808,67.29,85.37,73,110,279,174,11,0.97,9.55,17.66,4.08,4863,47671,88104,20378
23,evening,Shamshabad,13313,17971,13684,76.14,95.36,101,94,266,207,7,0.31,3.36,18.72,0.95,55,603,3364,171
24,morning,Banjara Hills,3893,6167,4886,79.23,92.05,61,94,238,158,12,0.57,4.91,12.58,2.46,35,303,776,152
25,morning,Bodduppal,4314,6368,5190,81.50,93.61,27,101,233,163,8,0.13,4.44,11.75,1.82,8,283,748,116
26,morning,Gandipet,1183,1963,1268,64.60,84.41,146,123,220,164,9,0.46,11.67,19.46,3.46,9,229,382,68
27,morning,Hitech City,9364,15986,10224,63.96,79.04,59,107,223,140,12,1.00,14.89,14.85,5.07,160,2380,2374,811
28,morning,Kothaguda 2,3964,7828,3894,49.74,64.81,84,127,269,155,15,1.32,23.19,14.88,10.69,103,1815,1165,837
29,morning,Kukatpally 3,4870,7654,5390,70.42,85.21,26,112,250,159,12,0.69,9.60,14.52,4.48,53,735,1111,343
30,morning,Manikonda,3885,6926,4370,63.10,78.95,40,123,241,158,14,0.35,14.54,15.59,6.14,24,1007,1080,425
31,morning,Marredpally,2719,3944,3125,79.23,91.78,21,98,238,160,9,0.08,6.57,12.15,1.55,3,259,479,61
32,morning,Mehedipatnam,4398,7007,5052,72.10,85.81,51,108,237,152,10,1.04,8.55,13.49,4.60,73,599,945,322
33,morning,Mothinagar,4221,8231,4255,51.69,69.41,94,124,290,168,21,0.98,20.06,17.59,9.55,81,1651,1448,786
34,morning,Other_clusters,192338,330566,229629,69.47,83.90,71,114,250,158,10,0.61,11.16,14.16,4.32,2022,36902,46801,14285
35,morning,Shamshabad,7472,10674,8374,78.45,94.08,78,108,223,172,6,0.32,4.23,15.22,1.38,34,451,1625,147
36,rest_evening,Banjara Hills,3570,5216,2889,55.39,76.17,56,114,315,179,16,1.25,16.43,20.40,6.13,65,857,1064,320
37,rest_evening,Bodduppal,1810,2354,1673,71.07,90.78,55,131,266,197,9,0.38,6.54,18.86,2.29,9,154,444,54
38,rest_evening,Gandipet,577,940,410,43.62,65.43,94,130,292,163,13,3.51,20.74,20.85,10.11,33,195,196,95
39,rest_evening,Hitech City,7165,10009,6478,64.72,85.53,70,97,222,149,13,0.82,11.11,20.36,2.51,82,1112,2038,251
40,rest_evening,Kothaguda 2,1672,2272,1513,66.59,86.71,78,110,298,180,10,0.40,10.48,19.19,2.42,9,238,436,55
41,rest_evening,Kukatpally 3,2850,3835,2601,67.82,88.55,63,110,251,184,10,0.73,7.59,19.92,3.13,28,291,764,120
42,rest_evening,Manikonda,1692,2357,1558,66.10,87.82,45,108,240,174,9,0.34,9.12,21.13,2.67,8,215,498,63
43,rest_evening,Marredpally,1670,2161,1510,69.88,88.06,28,105,299,176,11,0.28,9.58,17.68,2.08,6,207,382,45
44,rest_evening,Mehedipatnam,4082,5494,3702,67.38,86.53,80,115,293,190,11,0.56,9.48,18.55,3.39,31,521,1019,186
45,rest_evening,Mothinagar,1596,2079,1401,67.39,88.89,140,100,266,183,9,0.29,8.80,20.54,1.88,6,183,427,39
46,rest_evening,Other_clusters,123972,189314,115381,60.95,81.24,77,114,291,177,12,0.88,13.55,19.70,4.27,1675,25647,37295,8092
47,rest_evening,Shamshabad,6190,8971,5350,59.64,81.90,86,111,279,175,9,0.64,13.15,21.69,4.29,57,1180,1946,385
48,rest_morning,Banjara Hills,2175,3055,2033,66.55,88.58,66,104,246,172,9,1.18,7.04,21.41,3.21,36,215,654,98
49,rest_morning,Bodduppal,1953,2821,2046,72.53,90.78,68,100,198,142,7,1.13,6.24,17.72,1.84,32,176,500,52
50,rest_morning,Gandipet,495,852,417,48.94,67.61,113,135,274,176,8,6.69,17.02,18.31,8.69,57,145,156,74
51,rest_morning,Hitech City,3992,5590,4248,75.99,93.94,54,81,198,152,6,0.48,4.44,17.60,1.14,27,248,984,64
52,rest_morning,Kothaguda 2,1467,2099,1466,69.84,88.61,59,94,244,148,8,0.71,8.77,18.20,1.91,15,184,382,40
53,rest_morning,Kukatpally 3,2891,3880,2888,74.43,91.24,33,109,205,147,7,0.59,6.96,16.26,1.21,23,270,631,47
54,rest_morning,Manikonda,1438,2119,1526,72.02,89.90,91,103,233,163,8,0.38,7.98,17.46,1.75,8,169,370,37
55,rest_morning,Marredpally,1188,1650,1197,72.55,90.73,85,119,192,160,8,0.61,7.33,17.52,1.33,10,121,289,22
56,rest_morning,Mehedipatnam,2322,3261,2317,71.05,90.49,80,112,209,162,9,0.61,6.47,18.92,2.42,20,211,617,79
57,rest_morning,Mothinagar,1626,2533,1676,66.17,84.72,140,108,203,147,9,3.32,9.99,18.12,1.97,84,253,459,50
58,rest_morning,Other_clusters,100074,150251,102398,68.15,86.61,92,112,228,156,8,1.16,9.09,17.99,3.14,1737,13661,27026,4721
59,rest_morning,Shamshabad,4426,6290,4215,67.01,88.30,94,117,183,147,6,1.18,7.63,20.99,2.89,74,480,1320,182

In [112]:
city_cluster_level_sports_benchmark.to_clipboard(index=False)

In [19]:
click_bucket=f"""
with olf as (

    SELECT
        yyyymmdd,
        customer_id,
        order_id,
        order_requested_epoch,
        customer_cancelled_epoch,
        dropped_epoch,
        expired_epoch,
        rider_accepted_epoch
        
    FROM 
        orders.order_logs_fact
    WHERE
        yyyymmdd >= '20240911' AND yyyymmdd <= '20240916'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city_name = 'Hyderabad'
        
    ),




click as(
    select
        yyyymmdd,
        profile_identity as user_id,
        epoch as click_epoch
    from 
        clevertap.customer_notification_clicked_immutable
    where yyyymmdd >= '20240911' and yyyymmdd<='20240916'
    and event_props_wzrk_c2a='Button 2'
    and event_props_campaign_id = '1725971334'

),


merge AS (
    
    SELECT 
        olf.*,
        click_epoch,
        (click_epoch / 1000 - order_requested_epoch / 1000) time_to_click
        --row_number() over(partition by olf.yyyymmdd,olf.customer_id,olf.order_id order by click_epoch) seq_no
    FROM 
        olf
    JOIN 
        click
        on olf.yyyymmdd = click.yyyymmdd
        and olf.customer_id = click.user_id
        and olf.order_requested_epoch < click.click_epoch
        and (olf.customer_cancelled_epoch > click.click_epoch or dropped_epoch > click.click_epoch or 
        expired_epoch > click.click_epoch or rider_accepted_epoch> click.click_epoch)
    )
    
    
   
    
    
    SELECT
        
        case 
        when time_to_click <= 15 then 'a. 15 Sec'
        when time_to_click between 16 and 30 then 'b. 16-30 Sec'
        when time_to_click between 31 and 60 then 'c. 30-60 Sec'
        when time_to_click between 61 and 120 then 'd. 1-2 min'
        when time_to_click between 121 and 240 then 'e. 3-4 min'
        when time_to_click > 240 then 'f. 4+ min' 
        else 'check' end as click_bucket,
        count(distinct customer_id) customers
    FROM 
        merge
    -- WHERE 
    --     --seq_no = 1
    GROUP BY 1
    ORDER BY 1

"""
click_bucket_df = pd.read_sql(click_bucket,conn)

/var/folders/j7/5rtfb17j30s9g9q790v9nr0h0000gn/T/ipykernel_62376/650900096.py:82: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  click_bucket_df = pd.read_sql(click_bucket,conn)

In [20]:
click_bucket_df

   click_bucket  customers
0     a. 15 Sec       1737
1  b. 16-30 Sec        274
2  c. 30-60 Sec        123
3    d. 1-2 min         81
4    e. 3-4 min         35
5     f. 4+ min         33

In [21]:
click_bucket_df.customers.sum()

2283

In [22]:
2178-2283

-105

In [24]:
1737-105

1632

In [23]:
click_bucket_df.to_clipboard(index=False)

In [117]:
total_customers = click_bucket_df['customers'].sum()

# Calculate the percentage of customers for each click_bucket
click_bucket_df['customer_percentage'] = (click_bucket_df['customers'] / total_customers) * 100

# Round the percentage to 2 decimal places
click_bucket_df['customer_percentage'] = click_bucket_df['customer_percentage'].round(2)

In [119]:
click_bucket_df.to_clipboard(index=False)