In [1]:
import re
import os 
import pandas as pd
import matplotlib.pyplot as plt 
import numpy as np
from pyhive import presto
from datetime import date
from collections import Counter

from scipy import stats
from pyhive import presto
from datetime import datetime, timedelta

presto_port = '80'
username = 'manoj.ravirajan@rapido.bike'

conn=presto.connect('presto-gateway.processing.data.production.internal',presto_port,username)

connection1 = presto.connect('bi-presto.serving.data.production.internal', presto_port, username)
connection2 = presto.connect('bi-trino-2.serving.data.production.internal', presto_port, username)
connection3= presto.connect('processing-2.processing.data.production.internal',presto_port,username)
connection4= presto.connect('processing.processing.data.production.internal',presto_port,username)


pd.set_option('display.max_columns', None)

In [2]:
overall_query=f"""
with exp_category as(
select
    userid as user_id,
    case    when name='CaptainSearchEntertainmentNewsTest' then 'test' 
            else 'control'
    end as test_group
from
   canonical.user_selector
where
    yyyymmdd = '20240905'
    and selectorid in ('66d9ebe38a94b100011bfea8','66d9ed054c9b3100015a374a')

),

rr_net AS (
    SELECT 
        yyyymmdd, 
        customer_id,
        order_id, 
        order_status, 
        modified_order_status, 
        spd_fraud_flag,
        quarter_hour,
        CASE 
            WHEN modified_order_status IN ('OCARA', 'COBRA', 'COBRM') 
            THEN (customer_cancelled_epoch / 1000 - order_requested_epoch / 1000) 
        END AS time_spent_in_sec,
        CASE 
            WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') 
            THEN (rider_accepted_epoch / 1000 - order_requested_epoch / 1000)
        END AS time_taken_to_accp
        
    
    FROM 
        orders.order_logs_fact fact
    WHERE 
         yyyymmdd >= '20240911' AND yyyymmdd <= '20240916'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city_name = 'Hyderabad'
        AND service_obj_service_name in ('Auto','Auto Lite','Auto NCR','Auto Pool','AutoPremium','CityAuto','Link','Bike Lite','Bike Pink','CabEconomy','Bike Metro', 'CabPremium')
        AND channel_host='android'
        AND customer_id in (
                select
                    user_id
        from 
            clevertap.clevertap_customer_order_activity
        where 
            yyyymmdd >= '20240911' AND yyyymmdd <= '20240916'
            AND order_activity_source = 'appOpen'
            and current_city = 'Hyderabad'
            and platform='Android'
            and app_version>='8.30.0'           
            )
         
),

view_tbl as(

    select
        yyyymmdd,
        profile_identity as user_id,
        'viewed' as event_type
    from 
        clevertap.customer_notification_viewed_immutable 
    where yyyymmdd >= '20240911' and yyyymmdd<='20240916'
    and event_props_campaign_id = '1725971599'

),

click_tbl as(
    select
        yyyymmdd,
        profile_identity as user_id,
        CASE
                    when event_props_wzrk_c2a='Button 2' then 'play_click'
                    else 'close_click'
        end as click_type
    from 
        clevertap.customer_notification_clicked_immutable
    where yyyymmdd >= '20240911' and yyyymmdd<='20240916'
    and event_props_campaign_id = '1725971599'

),
merge as(
    select exp_category.*,
            rr_net.yyyymmdd,
            rr_net.order_id,
            rr_net.order_status,
            rr_net.modified_order_status,
            rr_net.spd_fraud_flag,
            rr_net.quarter_hour,
            rr_net.time_spent_in_sec,
            rr_net.time_taken_to_accp,
            view_tbl.event_type,
            click_tbl.click_type
    from
        exp_category
    left join 
            rr_net 
        on exp_category.user_id=rr_net.customer_id
    left join
            view_tbl
        on rr_net.customer_id=view_tbl.user_id
           and rr_net.yyyymmdd=view_tbl.yyyymmdd
    left join
            click_tbl
        on rr_net.customer_id=click_tbl.user_id
        and view_tbl.yyyymmdd=click_tbl.yyyymmdd

)

SELECT
        test_group,
        -- event_type,
        -- click_type,
        customers,

        gross_count,
        net_count,
        
        COALESCE(TRY(net_count*100.00/gross_count), 0) g2n,
        
        COALESCE(TRY(tot_accepted*100.00/gross_count), 0) "aor",
        
        
        median_cobrm_time,
        median_cobra_time,
        median_ocara_time,
        median_cancellation_time,
        median_acceptance_time,
        
        COALESCE(TRY(cobrm*100.00/gross_count), 0) "% cobrm",
        COALESCE(TRY(cobra*100.00/gross_count), 0) "% cobra",
        COALESCE(TRY(ocara*100.00/gross_count), 0) "% ocara",
        COALESCE(TRY(expired*100.00/gross_count), 0) "% expired",
        cobrm, 
        cobra,
        ocara,
        expired
    FROM    
        (
        SELECT
            test_group,
            -- event_type,
            -- click_type,
            COUNT(DISTINCT user_id) customers,
            COUNT(DISTINCT order_id) gross_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' AND spd_fraud_flag != true THEN order_id END) net_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN order_id END) AS tot_accepted,

        
           
            
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRM' THEN order_id END) cobrm,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRA' THEN order_id END) cobra,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'OCARA' THEN order_id END) ocara,
            COUNT(DISTINCT CASE WHEN order_status = 'expired' THEN order_id END) expired,
            
            approx_percentile(CASE WHEN modified_order_status = 'COBRM' THEN time_spent_in_sec END,0.50) as median_cobrm_time,
            approx_percentile(CASE WHEN modified_order_status = 'COBRA' THEN time_spent_in_sec END,0.50) as median_cobra_time,
            approx_percentile(CASE WHEN modified_order_status = 'OCARA' THEN time_spent_in_sec END,0.50) as median_ocara_time,
            approx_percentile(CASE WHEN modified_order_status in ('COBRA','COBRM','OCARA') THEN time_spent_in_sec END,0.50) as median_cancellation_time,
            approx_percentile(CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN time_taken_to_accp END,0.50) as median_acceptance_time
            
        FROM 
            merge
        where 
            yyyymmdd is not null
           and NOT (test_group = 'control' AND event_type IS NOT NULL)
           and NOT (event_type IS NULL AND click_type IS NOT NULL)
        GROUP BY 1
        )
    ORDER BY 1,2,3

"""

overall_entertainment=pd.read_sql(overall_query,conn)

/var/folders/j7/5rtfb17j30s9g9q790v9nr0h0000gn/T/ipykernel_62377/158498091.py:179: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  overall_entertainment=pd.read_sql(overall_query,conn)

In [3]:
overall_entertainment

,test_group,customers,gross_count,net_count,g2n,aor,median_cobrm_time,median_cobra_time,median_ocara_time,median_cancellation_time,median_acceptance_time,% cobrm,% cobra,% ocara,% expired,cobrm,cobra,ocara,expired
0,control,59899,181010,123661,68.32,85.28,65,111,254,163,10,0.64,10.17,16.63,3.91,1156,18408,30104,7075
1,test,60083,181597,123740,68.14,85.32,72,114,259,167,10,0.73,10.19,16.86,3.75,1331,18499,30622,6817

In [6]:
overall_query=f"""
with exp_category as(
select
    userid as user_id,
    case    when name='CaptainSearchEntertainmentNewsTest' then 'test' 
            else 'control'
    end as test_group
from
   canonical.user_selector
where
    yyyymmdd = '20240905'
    and selectorid in ('66d9ebe38a94b100011bfea8','66d9ed054c9b3100015a374a')

),

rr_net AS (
    SELECT 
        yyyymmdd, 
        customer_id,
        order_id, 
        order_status, 
        modified_order_status, 
        spd_fraud_flag,
        quarter_hour,
        CASE 
            WHEN modified_order_status IN ('OCARA', 'COBRA', 'COBRM') 
            THEN (customer_cancelled_epoch / 1000 - order_requested_epoch / 1000) 
        END AS time_spent_in_sec,
        CASE 
            WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') 
            THEN (rider_accepted_epoch / 1000 - order_requested_epoch / 1000)
        END AS time_taken_to_accp
        
    
    FROM 
        orders.order_logs_fact fact
    WHERE 
         yyyymmdd >= '20240911' AND yyyymmdd <= '20240916'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city_name = 'Hyderabad'
        AND service_obj_service_name in ('Auto','Auto Lite','Auto NCR','Auto Pool','AutoPremium','CityAuto','Link','Bike Lite','Bike Pink','CabEconomy','Bike Metro', 'CabPremium')
        AND channel_host='android'
        AND customer_id in (
                select
                    user_id
        from 
            clevertap.clevertap_customer_order_activity
        where 
            yyyymmdd >= '20240911' AND yyyymmdd <= '20240916'
            AND order_activity_source = 'appOpen'
            and current_city = 'Hyderabad'
            and platform='Android'
            and app_version>='8.30.0'           
            )
         
),

view_tbl as(

    select
        yyyymmdd,
        profile_identity as user_id,
        'viewed' as event_type
    from 
        clevertap.customer_notification_viewed_immutable 
    where yyyymmdd >= '20240911' and yyyymmdd<='20240916'
    and event_props_campaign_id = '1725971599'

),

click_tbl as(
    select
        yyyymmdd,
        profile_identity as user_id,
        CASE
                    when event_props_wzrk_c2a='Button 2' then 'play_click'
                    else 'close_click'
        end as click_type
    from 
        clevertap.customer_notification_clicked_immutable
    where yyyymmdd >= '20240911' and yyyymmdd<='20240916'
    and event_props_campaign_id = '1725971599'

),
merge as(
    select exp_category.*,
            rr_net.yyyymmdd,
            rr_net.order_id,
            rr_net.order_status,
            rr_net.modified_order_status,
            rr_net.spd_fraud_flag,
            rr_net.quarter_hour,
            rr_net.time_spent_in_sec,
            rr_net.time_taken_to_accp,
            view_tbl.event_type,
            click_tbl.click_type
    from
        exp_category
    left join 
            rr_net 
        on exp_category.user_id=rr_net.customer_id
    left join
            view_tbl
        on rr_net.customer_id=view_tbl.user_id
           and rr_net.yyyymmdd=view_tbl.yyyymmdd
    left join
            click_tbl
        on rr_net.customer_id=click_tbl.user_id
        and view_tbl.yyyymmdd=click_tbl.yyyymmdd

)

SELECT
        test_group,
        event_type,
        click_type,
        customers,

        gross_count,
        net_count,
        
        COALESCE(TRY(net_count*100.00/gross_count), 0) g2n,
        
        COALESCE(TRY(tot_accepted*100.00/gross_count), 0) "aor",
        
        
        median_cobrm_time,
        median_cobra_time,
        median_ocara_time,
        median_cancellation_time,
        median_acceptance_time,
        
        COALESCE(TRY(cobrm*100.00/gross_count), 0) "% cobrm",
        COALESCE(TRY(cobra*100.00/gross_count), 0) "% cobra",
        COALESCE(TRY(ocara*100.00/gross_count), 0) "% ocara",
        COALESCE(TRY(expired*100.00/gross_count), 0) "% expired",
        cobrm, 
        cobra,
        ocara,
        expired
    FROM    
        (
        SELECT
            test_group,
            event_type,
            click_type,
            COUNT(DISTINCT user_id) customers,
            COUNT(DISTINCT order_id) gross_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' AND spd_fraud_flag != true THEN order_id END) net_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN order_id END) AS tot_accepted,

        
           
            
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRM' THEN order_id END) cobrm,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRA' THEN order_id END) cobra,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'OCARA' THEN order_id END) ocara,
            COUNT(DISTINCT CASE WHEN order_status = 'expired' THEN order_id END) expired,
            
            approx_percentile(CASE WHEN modified_order_status = 'COBRM' THEN time_spent_in_sec END,0.50) as median_cobrm_time,
            approx_percentile(CASE WHEN modified_order_status = 'COBRA' THEN time_spent_in_sec END,0.50) as median_cobra_time,
            approx_percentile(CASE WHEN modified_order_status = 'OCARA' THEN time_spent_in_sec END,0.50) as median_ocara_time,
            approx_percentile(CASE WHEN modified_order_status in ('COBRA','COBRM','OCARA') THEN time_spent_in_sec END,0.50) as median_cancellation_time,
            approx_percentile(CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN time_taken_to_accp END,0.50) as median_acceptance_time
            
        FROM 
            merge
        where 
            yyyymmdd is not null
           and NOT (test_group = 'control' AND event_type IS NOT NULL)
           and NOT (event_type IS NULL AND click_type IS NOT NULL)
        GROUP BY 1,2,3
        )
    ORDER BY 1,2,3

"""

overall_entertainment=pd.read_sql(overall_query,conn)

/var/folders/j7/5rtfb17j30s9g9q790v9nr0h0000gn/T/ipykernel_62377/2026902862.py:179: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  overall_entertainment=pd.read_sql(overall_query,conn)

In [10]:
overall_entertainment

,test_group,event_type,click_type,customers,gross_count,net_count,g2n,aor,median_cobrm_time,median_cobra_time,median_ocara_time,median_cancellation_time,median_acceptance_time,% cobrm,% cobra,% ocara,% expired,cobrm,cobra,ocara,expired
0,control,None,None,59899,181010,123661,68.32,85.28,65,110,254,163,10,0.64,10.17,16.63,3.91,1156,18408,30104,7075
1,test,viewed,close_click,45849,133546,90750,67.95,85.04,75,114,264,171,10,0.70,10.41,16.79,3.84,929,13902,22427,5134
2,test,viewed,play_click,2629,4793,2998,62.55,82.41,56,94,216,141,10,1.15,12.21,19.36,4.24,55,585,928,203
3,test,viewed,None,1948,3883,2655,68.37,87.41,39,108,199,151,9,0.75,7.67,18.72,4.17,29,298,727,162
4,test,None,None,16797,39434,27376,69.42,86.40,74,113,255,166,10,0.81,9.44,16.61,3.35,318,3721,6551,1320

In [17]:
overall_entertainment.to_clipboard(index=False)

## pre-post

In [12]:
overall_query=f"""
with exp_category as(
select
    userid as user_id,
    case    when name='CaptainSearchEntertainmentNewsTest' then 'test' 
            else 'control'
    end as test_group
from
   canonical.user_selector
where
    yyyymmdd = '20240905'
    and selectorid in ('66d9ebe38a94b100011bfea8','66d9ed054c9b3100015a374a')

),

rr_net AS (
    SELECT 
        yyyymmdd, 
        customer_id,
        order_id, 
        order_status, 
        modified_order_status, 
        spd_fraud_flag,
        quarter_hour,
        CASE 
            WHEN modified_order_status IN ('OCARA', 'COBRA', 'COBRM') 
            THEN (customer_cancelled_epoch / 1000 - order_requested_epoch / 1000) 
        END AS time_spent_in_sec,
        CASE 
            WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') 
            THEN (rider_accepted_epoch / 1000 - order_requested_epoch / 1000)
        END AS time_taken_to_accp
        
    
    FROM 
        orders.order_logs_fact fact
    WHERE 
         yyyymmdd >= '20240905' AND yyyymmdd <= '20240910'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city_name = 'Hyderabad'
        AND service_obj_service_name in ('Auto','Auto Lite','Auto NCR','Auto Pool','AutoPremium','CityAuto','Link','Bike Lite','Bike Pink','CabEconomy','Bike Metro', 'CabPremium')
        AND channel_host='android'
        AND customer_id in (
                select
                    user_id
        from 
            clevertap.clevertap_customer_order_activity
        where 
            yyyymmdd >= '20240905' AND yyyymmdd <= '20240910'
            AND order_activity_source = 'appOpen'
            and current_city = 'Hyderabad'
            and platform='Android'
            and app_version>='8.30.0'           
            )
         
),

view_tbl as(

    select
        yyyymmdd,
        profile_identity as user_id,
        'viewed' as event_type
    from 
        clevertap.customer_notification_viewed_immutable 
    where yyyymmdd >= '20240905' AND yyyymmdd <= '20240910'
    and event_props_campaign_id = '1725971599'

),

click_tbl as(
    select
        yyyymmdd,
        profile_identity as user_id,
        CASE
                    when event_props_wzrk_c2a='Button 2' then 'play_click'
                    else 'close_click'
        end as click_type
    from 
        clevertap.customer_notification_clicked_immutable
    where yyyymmdd >= '20240905' AND yyyymmdd <= '20240910'
    and event_props_campaign_id = '1725971599'

),
merge as(
    select exp_category.*,
            rr_net.yyyymmdd,
            rr_net.order_id,
            rr_net.order_status,
            rr_net.modified_order_status,
            rr_net.spd_fraud_flag,
            rr_net.quarter_hour,
            rr_net.time_spent_in_sec,
            rr_net.time_taken_to_accp,
            view_tbl.event_type,
            click_tbl.click_type
    from
        exp_category
    left join 
            rr_net 
        on exp_category.user_id=rr_net.customer_id
    left join
            view_tbl
        on rr_net.customer_id=view_tbl.user_id
           and rr_net.yyyymmdd=view_tbl.yyyymmdd
    left join
            click_tbl
        on rr_net.customer_id=click_tbl.user_id
        and view_tbl.yyyymmdd=click_tbl.yyyymmdd

)

SELECT
        test_group,
        -- event_type,
        -- click_type,
        customers,

        gross_count,
        net_count,
        
        COALESCE(TRY(net_count*100.00/gross_count), 0) g2n,
        
        COALESCE(TRY(tot_accepted*100.00/gross_count), 0) "aor",
        
        
        median_cobrm_time,
        median_cobra_time,
        median_ocara_time,
        median_cancellation_time,
        median_acceptance_time,
        
        COALESCE(TRY(cobrm*100.00/gross_count), 0) "% cobrm",
        COALESCE(TRY(cobra*100.00/gross_count), 0) "% cobra",
        COALESCE(TRY(ocara*100.00/gross_count), 0) "% ocara",
        COALESCE(TRY(expired*100.00/gross_count), 0) "% expired",
        cobrm, 
        cobra,
        ocara,
        expired
    FROM    
        (
        SELECT
            test_group,
            -- event_type,
            -- click_type,
            COUNT(DISTINCT user_id) customers,
            COUNT(DISTINCT order_id) gross_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' AND spd_fraud_flag != true THEN order_id END) net_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN order_id END) AS tot_accepted,

        
           
            
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRM' THEN order_id END) cobrm,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRA' THEN order_id END) cobra,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'OCARA' THEN order_id END) ocara,
            COUNT(DISTINCT CASE WHEN order_status = 'expired' THEN order_id END) expired,
            
            approx_percentile(CASE WHEN modified_order_status = 'COBRM' THEN time_spent_in_sec END,0.50) as median_cobrm_time,
            approx_percentile(CASE WHEN modified_order_status = 'COBRA' THEN time_spent_in_sec END,0.50) as median_cobra_time,
            approx_percentile(CASE WHEN modified_order_status = 'OCARA' THEN time_spent_in_sec END,0.50) as median_ocara_time,
            approx_percentile(CASE WHEN modified_order_status in ('COBRA','COBRM','OCARA') THEN time_spent_in_sec END,0.50) as median_cancellation_time,
            approx_percentile(CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN time_taken_to_accp END,0.50) as median_acceptance_time
            
        FROM 
            merge
        where 
            yyyymmdd is not null
           and NOT (test_group = 'control' AND event_type IS NOT NULL)
           and NOT (event_type IS NULL AND click_type IS NOT NULL)
        GROUP BY 1
        )
    ORDER BY 1,2,3

"""

overall_entertainmentpre=pd.read_sql(overall_query,conn)

/var/folders/j7/5rtfb17j30s9g9q790v9nr0h0000gn/T/ipykernel_62377/4259449240.py:179: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  overall_entertainmentpre=pd.read_sql(overall_query,conn)

In [18]:
overall_entertainmentpre

,test_group,customers,gross_count,net_count,g2n,aor,median_cobrm_time,median_cobra_time,median_ocara_time,median_cancellation_time,median_acceptance_time,% cobrm,% cobra,% ocara,% expired,cobrm,cobra,ocara,expired
0,control,58334,187403,110872,59.16,75.39,54,120,265,158,11,0.64,16.96,15.92,7.00,1206,31787,29842,13115
1,test,58571,187428,111383,59.43,75.68,74,121,270,159,11,0.66,16.66,15.97,6.99,1243,31229,29932,13098

In [20]:
overall_entertainmentpre.to_clipboard(index=False)

## COBRA TTC

In [25]:
overall_query=f"""
with exp_category as(
select
    userid as user_id,
    case    when name='CaptainSearchEntertainmentNewsTest' then 'test' 
            else 'control'
    end as test_group
from
   canonical.user_selector
where
    yyyymmdd = '20240905'
    and selectorid in ('66d9ebe38a94b100011bfea8','66d9ed054c9b3100015a374a')

),

rr_net AS (
    SELECT 
        yyyymmdd, 
        customer_id,
        order_id, 
        order_status, 
        modified_order_status, 
        spd_fraud_flag,
        quarter_hour,
        CASE 
            WHEN modified_order_status IN ('OCARA', 'COBRA', 'COBRM') 
            THEN (customer_cancelled_epoch / 1000 - order_requested_epoch / 1000) 
        END AS time_spent_in_sec,
        CASE 
            WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') 
            THEN (rider_accepted_epoch / 1000 - order_requested_epoch / 1000)
        END AS time_taken_to_accp
        
    
    FROM 
        orders.order_logs_fact fact
    WHERE 
         yyyymmdd >= '20240911' AND yyyymmdd <= '20240916'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city_name = 'Hyderabad'
        AND service_obj_service_name in ('Auto','Auto Lite','Auto NCR','Auto Pool','AutoPremium','CityAuto','Link','Bike Lite','Bike Pink','CabEconomy','Bike Metro', 'CabPremium')
        AND channel_host='android'
        AND customer_id in (
                select
                    user_id
        from 
            clevertap.clevertap_customer_order_activity
        where 
            yyyymmdd >= '20240911' AND yyyymmdd <= '20240916'
            AND order_activity_source = 'appOpen'
            and current_city = 'Hyderabad'
            and platform='Android'
            and app_version>='8.30.0'           
            )
         
),

view_tbl as(

    select
        yyyymmdd,
        profile_identity as user_id,
        'viewed' as event_type
    from 
        clevertap.customer_notification_viewed_immutable 
    where yyyymmdd >= '20240911' and yyyymmdd<='20240916'
    and event_props_campaign_id = '1725971599'

),

click_tbl as(
    select
        yyyymmdd,
        profile_identity as user_id,
        CASE
                    when event_props_wzrk_c2a='Button 2' then 'play_click'
                    else 'close_click'
        end as click_type
    from 
        clevertap.customer_notification_clicked_immutable
    where yyyymmdd >= '20240911' and yyyymmdd<='20240916'
    and event_props_campaign_id = '1725971599'

),
merge as(
    select exp_category.*,
            rr_net.yyyymmdd,
            rr_net.order_id,
            rr_net.order_status,
            rr_net.modified_order_status,
            rr_net.spd_fraud_flag,
            rr_net.quarter_hour,
            rr_net.time_spent_in_sec,
            rr_net.time_taken_to_accp,
            view_tbl.event_type,
            click_tbl.click_type
    from
        exp_category
    left join 
            rr_net 
        on exp_category.user_id=rr_net.customer_id
    left join
            view_tbl
        on rr_net.customer_id=view_tbl.user_id
           and rr_net.yyyymmdd=view_tbl.yyyymmdd
    left join
            click_tbl
        on rr_net.customer_id=click_tbl.user_id
        and view_tbl.yyyymmdd=click_tbl.yyyymmdd

)

SELECT
        test_group,
        -- event_type,
        -- click_type,
        cobra_ttc_bucket,
        
        customers,

        gross_count,
        net_count,
        
        COALESCE(TRY(net_count*100.00/gross_count), 0) g2n,
        
        COALESCE(TRY(tot_accepted*100.00/gross_count), 0) "aor",
        
        
        median_cobrm_time,
        median_cobra_time,
        median_ocara_time,
        median_cancellation_time,
        median_acceptance_time,
        
        COALESCE(TRY(cobrm*100.00/gross_count), 0) "% cobrm",
        COALESCE(TRY(cobra*100.00/gross_count), 0) "% cobra",
        COALESCE(TRY(ocara*100.00/gross_count), 0) "% ocara",
        COALESCE(TRY(expired*100.00/gross_count), 0) "% expired",
        cobrm, 
        cobra,
        ocara,
        expired
    FROM    
        (
        SELECT
            test_group,
            -- event_type,
            -- click_type,

            CASE 
            WHEN modified_order_status = 'COBRA' AND time_spent_in_sec <= 15 THEN 'a. 0-15 sec' 
            WHEN modified_order_status = 'COBRA' AND time_spent_in_sec BETWEEN 16 AND 30 THEN 'b. 16-30 sec' 
            WHEN modified_order_status = 'COBRA' AND time_spent_in_sec BETWEEN 31 AND 60 THEN 'c. 31-60 sec' 
            WHEN modified_order_status = 'COBRA' AND time_spent_in_sec BETWEEN 61 AND 180 THEN 'd. 61-180 sec' 
            WHEN modified_order_status = 'COBRA' AND time_spent_in_sec > 180 THEN 'e. 180+ sec' 
            WHEN modified_order_status != 'COBRA' THEN 'f. NO COBRA'
            ELSE 'Check' END cobra_ttc_bucket,
            
            COUNT(DISTINCT user_id) customers,
            COUNT(DISTINCT order_id) gross_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' AND spd_fraud_flag != true THEN order_id END) net_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN order_id END) AS tot_accepted,

        
           
            
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRM' THEN order_id END) cobrm,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRA' THEN order_id END) cobra,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'OCARA' THEN order_id END) ocara,
            COUNT(DISTINCT CASE WHEN order_status = 'expired' THEN order_id END) expired,
            
            approx_percentile(CASE WHEN modified_order_status = 'COBRM' THEN time_spent_in_sec END,0.50) as median_cobrm_time,
            approx_percentile(CASE WHEN modified_order_status = 'COBRA' THEN time_spent_in_sec END,0.50) as median_cobra_time,
            approx_percentile(CASE WHEN modified_order_status = 'OCARA' THEN time_spent_in_sec END,0.50) as median_ocara_time,
            approx_percentile(CASE WHEN modified_order_status in ('COBRA','COBRM','OCARA') THEN time_spent_in_sec END,0.50) as median_cancellation_time,
            approx_percentile(CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN time_taken_to_accp END,0.50) as median_acceptance_time
            
        FROM 
            merge
        where 
            yyyymmdd is not null
           and NOT (test_group = 'control' AND event_type IS NOT NULL)
           and NOT (event_type IS NULL AND click_type IS NOT NULL)
           and click_type = 'play_click'
           
        GROUP BY 1,2
        )
    ORDER BY 1,2,3

"""

overall_entertainment_ttc=pd.read_sql(overall_query,conn)

/var/folders/j7/5rtfb17j30s9g9q790v9nr0h0000gn/T/ipykernel_62377/1744123129.py:193: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  overall_entertainment_ttc=pd.read_sql(overall_query,conn)

In [26]:
overall_entertainment_ttc

,test_group,cobra_ttc_bucket,customers,gross_count,net_count,g2n,aor,median_cobrm_time,median_cobra_time,median_ocara_time,median_cancellation_time,median_acceptance_time,% cobrm,% cobra,% ocara,% expired,cobrm,cobra,ocara,expired
0,test,a. 0-15 sec,56,58,0,0.00,0.00,NaN,12.0,NaN,12,NaN,0.00,100.0,0.00,0.00,0,58,0,0
1,test,b. 16-30 sec,73,76,0,0.00,0.00,NaN,21.0,NaN,21,NaN,0.00,100.0,0.00,0.00,0,76,0,0
2,test,c. 31-60 sec,73,81,0,0.00,0.00,NaN,45.0,NaN,45,NaN,0.00,100.0,0.00,0.00,0,81,0,0
3,test,d. 61-180 sec,194,251,0,0.00,0.00,NaN,114.0,NaN,114,NaN,0.00,100.0,0.00,0.00,0,251,0,0
4,test,e. 180+ sec,102,119,0,0.00,0.00,NaN,235.0,NaN,235,NaN,0.00,100.0,0.00,0.00,0,119,0,0
5,test,f. NO COBRA,2515,4208,2998,71.25,93.87,56.0,NaN,216.0,201,10.0,1.31,0.0,22.05,4.82,55,0,928,203

In [27]:
overall_entertainment_ttc.to_clipboard(index=False)

## Other

In [24]:
overall_sports.to_csv('overall_entertainment.csv',index=False)

In [5]:
overall_daywise_query=f"""
with exp_category as(
select
    userid as user_id,
    case    when name='CaptainSearchEntertainmentNewsTest' then 'test' 
            else 'control'
    end as test_group
from
   canonical.user_selector
where
    yyyymmdd = '20240905'
    and selectorid in ('66d9ebe38a94b100011bfea8','66d9ed054c9b3100015a374a')

),

rr_net AS (
    SELECT 
        yyyymmdd, 
        customer_id,
        order_id, 
        order_status, 
        modified_order_status, 
        spd_fraud_flag,
        quarter_hour,
        CASE 
            WHEN modified_order_status IN ('OCARA', 'COBRA', 'COBRM') 
            THEN (customer_cancelled_epoch / 1000 - order_requested_epoch / 1000) 
        END AS time_spent_in_sec,
        CASE 
            WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') 
            THEN (rider_accepted_epoch / 1000 - order_requested_epoch / 1000)
        END AS time_taken_to_accp
        
    
    FROM 
        orders.order_logs_fact fact
    WHERE 
         yyyymmdd >= '20240911' AND yyyymmdd <= '20240916'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city_name = 'Hyderabad'
        AND service_obj_service_name in ('Auto','Auto Lite','Auto NCR','Auto Pool','AutoPremium','CityAuto','Link','Bike Lite','Bike Pink','CabEconomy','Bike Metro', 'CabPremium')
        AND channel_host='android'
        AND customer_id in (
                select
                    user_id
        from 
            clevertap.clevertap_customer_order_activity
        where 
            yyyymmdd >= '20240911' AND yyyymmdd <= '20240916'
            AND order_activity_source = 'appOpen'
            and current_city = 'Hyderabad'
            and platform='Android'
            and app_version>='8.30.0'           
            )
         
),

view_tbl as(

    select
        yyyymmdd,
        profile_identity as user_id,
        'viewed' as event_type
    from 
        clevertap.customer_notification_viewed_immutable 
    where yyyymmdd >= '20240911' and yyyymmdd<='20240916'
    and event_props_campaign_id = '1725971599'

),

click_tbl as(
    select
        yyyymmdd,
        profile_identity as user_id,
        CASE
                    when event_props_wzrk_c2a='Button 2' then 'play_click'
                    else 'close_click'
        end as click_type
    from 
        clevertap.customer_notification_clicked_immutable
    where yyyymmdd >= '20240911' and yyyymmdd<='20240916'
    and event_props_campaign_id = '1725971599'

),
merge as(
    select exp_category.*,
            rr_net.yyyymmdd,
            rr_net.order_id,
            rr_net.order_status,
            rr_net.modified_order_status,
            rr_net.spd_fraud_flag,
            rr_net.quarter_hour,
            rr_net.time_spent_in_sec,
            rr_net.time_taken_to_accp,
            view_tbl.event_type,
            click_tbl.click_type
    from
        exp_category
    left join 
            rr_net 
        on exp_category.user_id=rr_net.customer_id
    left join
            view_tbl
        on rr_net.customer_id=view_tbl.user_id
           and rr_net.yyyymmdd=view_tbl.yyyymmdd
    left join
            click_tbl
        on rr_net.customer_id=click_tbl.user_id
        and view_tbl.yyyymmdd=click_tbl.yyyymmdd

)

SELECT
        yyyymmdd,
        test_group,
        event_type,
        click_type,
        customers,

        gross_count,
        net_count,
        
        COALESCE(TRY(net_count*100.00/gross_count), 0) g2n,
        
        COALESCE(TRY(tot_accepted*100.00/gross_count), 0) "aor",
        
        
        median_cobrm_time,
        median_cobra_time,
        median_ocara_time,
        median_cancellation_time,
        median_acceptance_time,
        
        COALESCE(TRY(cobrm*100.00/gross_count), 0) "% cobrm",
        COALESCE(TRY(cobra*100.00/gross_count), 0) "% cobra",
        COALESCE(TRY(ocara*100.00/gross_count), 0) "% ocara",
        COALESCE(TRY(expired*100.00/gross_count), 0) "% expired",
        cobrm, 
        cobra,
        ocara,
        expired
    FROM    
        (
        SELECT
            yyyymmdd,
            test_group,
            event_type,
            click_type,
            COUNT(DISTINCT user_id) customers,
            COUNT(DISTINCT order_id) gross_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' AND spd_fraud_flag != true THEN order_id END) net_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN order_id END) AS tot_accepted,

        
           
            
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRM' THEN order_id END) cobrm,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRA' THEN order_id END) cobra,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'OCARA' THEN order_id END) ocara,
            COUNT(DISTINCT CASE WHEN order_status = 'expired' THEN order_id END) expired,
            
            approx_percentile(CASE WHEN modified_order_status = 'COBRM' THEN time_spent_in_sec END,0.50) as median_cobrm_time,
            approx_percentile(CASE WHEN modified_order_status = 'COBRA' THEN time_spent_in_sec END,0.50) as median_cobra_time,
            approx_percentile(CASE WHEN modified_order_status = 'OCARA' THEN time_spent_in_sec END,0.50) as median_ocara_time,
            approx_percentile(CASE WHEN modified_order_status in ('COBRA','COBRM','OCARA') THEN time_spent_in_sec END,0.50) as median_cancellation_time,
            approx_percentile(CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN time_taken_to_accp END,0.50) as median_acceptance_time
            
        FROM 
            merge
        where 
            yyyymmdd is not null
           and NOT (test_group = 'control' AND event_type IS NOT NULL)
           and NOT (event_type IS NULL AND click_type IS NOT NULL)
        GROUP BY 1,2,3,4
        )
    ORDER BY 1,2,3,4

"""

overall_daywise_entertainment=pd.read_sql(overall_daywise_query,conn)

/var/folders/j7/5rtfb17j30s9g9q790v9nr0h0000gn/T/ipykernel_62377/274808176.py:181: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  overall_daywise_entertainment=pd.read_sql(overall_daywise_query,conn)

In [38]:
overall_daywise_entertainment

,yyyymmdd,test_group,event_type,click_type,customers,gross_count,net_count,g2n,aor,median_cobrm_time,median_cobra_time,median_ocara_time,median_cancellation_time,median_acceptance_time,% cobrm,% cobra,% ocara,% expired,cobrm,cobra,ocara,expired
0,20240911,control,None,None,18235,31529,21527,68.28,84.95,67,109,253,163,10,0.60,10.19,16.35,4.25,190,3213,5155,1341
1,20240911,test,viewed,close_click,9895,18199,11950,65.66,83.13,84,110,256,161,10,0.99,11.14,17.18,4.72,180,2028,3127,859
2,20240911,test,viewed,play_click,406,782,498,63.68,82.10,91,98,193,136,11,0.64,12.66,17.52,4.60,5,99,137,36
3,20240911,test,viewed,None,321,555,373,67.21,87.93,18,107,181,142,8,0.90,7.21,20.36,3.96,5,40,113,22
4,20240911,test,None,None,7677,12216,8639,70.72,87.12,69,112,272,174,10,0.63,8.94,16.04,3.30,77,1092,1960,403
5,20240912,control,None,None,17992,30804,21302,69.15,85.51,56,109,235,155,10,0.68,9.82,16.00,3.99,211,3025,4930,1228
6,20240912,test,viewed,close_click,13575,23601,16384,69.42,85.25,81,113,252,161,10,0.70,10.05,15.57,3.99,166,2372,3674,942
7,20240912,test,viewed,play_click,530,938,571,60.87,79.64,50,103,200,135,10,2.45,12.47,18.34,5.44,23,117,172,51
8,20240912,test,viewed,None,422,756,497,65.74,84.66,25,90,203,137,8,1.32,7.80,18.78,6.22,10,59,142,47
9,20240912,test,None,None,3557,5716,4002,70.01,86.44,60,110,232,149,10,1.03,9.45,16.08,3.08,59,540,919,176
10,20240913,control,None,None,18456,31243,21841,69.91,86.36,52,104,244,159,10,0.52,9.51,16.10,3.60,164,2971,5030,1125
11,20240913,test,viewed,close_click,13895,24001,16690,69.54,86.08,85,112,251,162,10,0.62,9.95,16.28,3.35,149,2387,3908,803
12,20240913,test,viewed,play_click,518,851,544,63.92,83.55,25,91,211,132,11,0.35,11.28,19.27,4.82,3,96,164,41
13,20240913,test,viewed,None,398,666,472,70.87,90.09,73,98,212,147,9,0.75,6.46,18.77,2.70,5,43,125,18
14,20240913,test,None,None,3595,5677,4049,71.32,87.92,37,108,258,172,10,0.37,8.31,16.24,3.36,21,472,922,191
15,20240914,control,None,None,18295,31440,21697,69.01,86.43,79,110,256,166,9,0.87,9.00,17.07,3.68,275,2830,5366,1156
16,20240914,test,viewed,close_click,14031,24026,16927,70.45,87.66,56,114,277,185,9,0.72,8.43,16.92,3.17,174,2025,4066,762
17,20240914,test,viewed,play_click,511,829,539,65.02,84.56,82,82,253,148,9,0.97,11.22,19.30,3.26,8,93,160,27
18,20240914,test,viewed,None,356,639,461,72.14,89.51,39,154,201,180,9,0.63,7.20,17.21,2.66,4,46,110,17
19,20240914,test,None,None,3413,5642,3905,69.21,86.97,107,114,249,166,9,1.51,8.05,17.37,3.46,85,454,980,195
20,20240915,control,None,None,15117,25869,17719,68.50,86.93,59,112,260,175,9,0.53,9.44,18.11,3.08,138,2442,4686,798
21,20240915,test,viewed,close_click,11533,19887,13497,67.87,86.53,64,113,261,174,9,0.52,9.73,18.30,3.22,103,1935,3639,641
22,20240915,test,viewed,play_click,416,691,414,59.91,83.07,60,92,216,137,9,1.30,13.02,22.29,2.60,9,90,154,18
23,20240915,test,viewed,None,324,572,415,72.55,88.99,10,101,218,136,8,0.17,7.17,16.08,3.67,1,41,92,21
24,20240915,test,None,None,2886,4690,3223,68.72,88.14,28,113,244,170,9,0.62,8.64,19.02,2.58,29,405,892,121
25,20240916,control,None,None,17251,30079,19543,64.97,81.61,63,116,271,164,11,0.59,13.05,16.38,4.74,178,3924,4927,1426
26,20240916,test,viewed,close_click,13393,23817,15291,64.20,81.35,79,121,275,170,11,0.66,13.24,16.84,4.73,157,3154,4010,1127
27,20240916,test,viewed,play_click,401,700,430,61.43,81.86,164,99,241,148,10,1.00,12.86,20.14,4.29,7,90,141,30
28,20240916,test,viewed,None,377,695,437,62.88,84.17,74,109,188,151,9,0.58,9.93,20.86,5.32,4,69,145,37
29,20240916,test,None,None,3246,5498,3563,64.81,81.10,67,121,244,155,11,0.85,13.79,15.97,4.26,47,758,878,234

In [39]:
overall_daywise_entertainment.to_clipboard(index=False)

In [27]:
overall_daywise_entertainment.to_csv('overall_daywise_entertainment.csv',index=False)

In [41]:
overall_session_query=f"""
with exp_category as(
select
    userid as user_id,
    case    when name='CaptainSearchEntertainmentNewsTest' then 'test' 
            else 'control'
    end as test_group
from
   canonical.user_selector
where
    yyyymmdd = '20240905'
    and selectorid in ('66d9ebe38a94b100011bfea8','66d9ed054c9b3100015a374a')

),

rr_net AS (
    SELECT 
        yyyymmdd, 
        customer_id,
        order_id, 
        order_status, 
        modified_order_status, 
        spd_fraud_flag,
        quarter_hour,
        CASE 
            WHEN modified_order_status IN ('OCARA', 'COBRA', 'COBRM') 
            THEN (customer_cancelled_epoch / 1000 - order_requested_epoch / 1000) 
        END AS time_spent_in_sec,
        CASE 
            WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') 
            THEN (rider_accepted_epoch / 1000 - order_requested_epoch / 1000)
        END AS time_taken_to_accp
        
    
    FROM 
        orders.order_logs_fact fact
    WHERE 
         yyyymmdd >= '20240911' AND yyyymmdd <= '20240916'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city_name = 'Hyderabad'
        AND service_obj_service_name in ('Auto','Auto Lite','Auto NCR','Auto Pool','AutoPremium','CityAuto','Link','Bike Lite','Bike Pink','CabEconomy','Bike Metro', 'CabPremium')
        AND channel_host='android'
        AND customer_id in (
                select
                    user_id
        from 
            clevertap.clevertap_customer_order_activity
        where 
            yyyymmdd >= '20240911' AND yyyymmdd <= '20240916'
            AND order_activity_source = 'appOpen'
            and current_city = 'Hyderabad'
            and platform='Android'
            and app_version>='8.30.0'           
            )
         
),

view_tbl as(

    select
        yyyymmdd,
        profile_identity as user_id,
        'viewed' as event_type
    from 
        clevertap.customer_notification_viewed_immutable 
    where yyyymmdd >= '20240911' and yyyymmdd<='20240916'
    and event_props_campaign_id = '1725971599'

),

click_tbl as(
    select
        yyyymmdd,
        profile_identity as user_id,
        CASE
                    when event_props_wzrk_c2a='Button 2' then 'play_click'
                    else 'close_click'
        end as click_type
    from 
        clevertap.customer_notification_clicked_immutable
    where yyyymmdd >= '20240911' and yyyymmdd<='20240916'
    and event_props_campaign_id = '1725971599'

),
merge as(
    select exp_category.*,
            rr_net.yyyymmdd,
            rr_net.order_id,
            rr_net.order_status,
            rr_net.modified_order_status,
            rr_net.spd_fraud_flag,
            rr_net.quarter_hour,
            rr_net.time_spent_in_sec,
            rr_net.time_taken_to_accp,
            view_tbl.event_type,
            click_tbl.click_type
    from
        exp_category
    left join 
            rr_net 
        on exp_category.user_id=rr_net.customer_id
    left join
            view_tbl
        on rr_net.customer_id=view_tbl.user_id
           and rr_net.yyyymmdd=view_tbl.yyyymmdd
    left join
            click_tbl
        on rr_net.customer_id=click_tbl.user_id
        and view_tbl.yyyymmdd=click_tbl.yyyymmdd

)

SELECT
        
        test_group,
        event_type,
        click_type,
        time_period,
        customers,

        gross_count,
        net_count,
        
        COALESCE(TRY(net_count*100.00/gross_count), 0) g2n,
        
        COALESCE(TRY(tot_accepted*100.00/gross_count), 0) "aor",
        
        
        median_cobrm_time,
        median_cobra_time,
        median_ocara_time,
        median_cancellation_time,
        median_acceptance_time,
        
        COALESCE(TRY(cobrm*100.00/gross_count), 0) "% cobrm",
        COALESCE(TRY(cobra*100.00/gross_count), 0) "% cobra",
        COALESCE(TRY(ocara*100.00/gross_count), 0) "% ocara",
        COALESCE(TRY(expired*100.00/gross_count), 0) "% expired",
        cobrm, 
        cobra,
        ocara,
        expired
    FROM    
        (
        SELECT
           
            test_group,
            event_type,
            click_type,
            case
                WHEN quarter_hour >= '0800' AND quarter_hour < '1100' THEN 'morning'
                WHEN quarter_hour >= '1100' AND quarter_hour < '1700' THEN 'afternoon'
                WHEN quarter_hour >= '1700' AND quarter_hour < '2100' THEN 'evening'
                WHEN quarter_hour >= '0000' AND quarter_hour < '0800' THEN 'rest_morning'
                ELSE 'rest_evening'
            end as time_period,
            COUNT(DISTINCT user_id) customers,
            COUNT(DISTINCT order_id) gross_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' AND spd_fraud_flag != true THEN order_id END) net_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN order_id END) AS tot_accepted,

        
           
            
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRM' THEN order_id END) cobrm,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRA' THEN order_id END) cobra,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'OCARA' THEN order_id END) ocara,
            COUNT(DISTINCT CASE WHEN order_status = 'expired' THEN order_id END) expired,
            
            approx_percentile(CASE WHEN modified_order_status = 'COBRM' THEN time_spent_in_sec END,0.50) as median_cobrm_time,
            approx_percentile(CASE WHEN modified_order_status = 'COBRA' THEN time_spent_in_sec END,0.50) as median_cobra_time,
            approx_percentile(CASE WHEN modified_order_status = 'OCARA' THEN time_spent_in_sec END,0.50) as median_ocara_time,
            approx_percentile(CASE WHEN modified_order_status in ('COBRA','COBRM','OCARA') THEN time_spent_in_sec END,0.50) as median_cancellation_time,
            approx_percentile(CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN time_taken_to_accp END,0.50) as median_acceptance_time
            
        FROM 
            merge
        where 
            yyyymmdd is not null
           and NOT (test_group = 'control' AND event_type IS NOT NULL)
           and NOT (event_type IS NULL AND click_type IS NOT NULL)
        GROUP BY 1,2,3,4
        )
    ORDER BY 1,2,3,4

"""

overall_session_entertainment=pd.read_sql(overall_session_query,conn)

/var/folders/km/1ltm54y105x6dzlcf44g881c0000gn/T/ipykernel_52024/4137295872.py:189: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  overall_session_entertainment=pd.read_sql(overall_session_query,conn)

In [42]:
overall_session_entertainment

,test_group,event_type,click_type,time_period,customers,gross_count,net_count,g2n,aor,median_cobrm_time,median_cobra_time,median_ocara_time,median_cancellation_time,median_acceptance_time,% cobrm,% cobra,% ocara,% expired,cobrm,cobra,ocara,expired
0,control,None,None,afternoon,32665,64634,46978,72.68,89.28,61.0,106,260,175,9,0.44,7.43,16.29,2.85,285,4802,10529,1840
1,control,None,None,evening,26411,50312,33069,65.73,83.61,54.0,112,266,169,12,0.85,10.74,17.53,4.78,430,5404,8819,2407
2,control,None,None,morning,17618,33889,23001,67.87,82.04,61.0,112,232,147,10,0.61,12.50,13.90,4.85,206,4237,4712,1642
3,control,None,None,rest_evening,10896,17865,10999,61.57,81.32,93.0,111,265,163,12,0.65,13.84,19.24,4.15,117,2472,3437,742
4,control,None,None,rest_morning,8861,14264,9582,67.18,85.62,88.0,112,205,149,8,0.83,10.45,18.21,3.11,118,1490,2597,443
5,test,viewed,close_click,afternoon,24662,47931,34692,72.38,88.77,63.0,113,267,179,9,0.41,7.90,16.13,2.92,198,3788,7729,1398
6,test,viewed,close_click,evening,20105,37637,24638,65.46,83.80,60.0,110,272,172,12,0.86,10.68,18.05,4.64,324,4021,6794,1746
7,test,viewed,close_click,morning,13292,24887,16754,67.32,81.97,55.0,117,249,155,10,0.61,13.03,14.41,4.39,153,3242,3586,1093
8,test,viewed,close_click,rest_evening,8106,13201,8033,60.85,80.99,51.0,117,270,172,12,0.67,13.84,19.64,4.45,89,1827,2593,588
9,test,viewed,close_click,rest_morning,6220,9875,6622,67.06,84.84,124.0,120,227,157,7,1.67,10.36,17.44,3.13,165,1023,1722,309
10,test,viewed,play_click,afternoon,1106,1698,1128,66.43,86.93,41.0,90,211,146,8,0.82,9.07,19.91,3.18,14,154,338,54
11,test,viewed,play_click,evening,1032,1491,907,60.83,80.35,126.0,99,202,140,12,1.54,12.81,19.11,5.30,23,191,285,79
12,test,viewed,play_click,morning,582,799,485,60.70,78.47,109.0,85,238,132,11,0.75,16.40,17.52,4.38,6,131,140,35
13,test,viewed,play_click,rest_evening,339,482,275,57.05,78.22,53.0,106,332,159,10,1.87,15.98,20.75,3.94,9,77,100,19
14,test,viewed,play_click,rest_morning,233,321,201,62.62,84.11,25.0,57,143,98,7,0.93,9.97,20.25,4.98,3,32,65,16
15,test,viewed,None,afternoon,887,1396,978,70.06,90.26,25.0,96,188,149,8,0.64,5.73,19.91,3.37,9,80,278,47
16,test,viewed,None,evening,774,1179,764,64.80,85.41,62.0,106,240,159,11,0.93,9.16,20.19,4.50,11,108,238,53
17,test,viewed,None,morning,514,703,501,71.27,85.63,45.0,142,180,155,8,1.14,7.82,14.22,5.41,8,55,100,38
18,test,viewed,None,rest_evening,251,323,225,69.66,85.76,NaN,154,243,182,9,0.00,9.60,15.48,4.64,0,31,50,15
19,test,viewed,None,rest_morning,203,282,187,66.31,87.94,18.0,102,136,111,6,0.35,8.51,21.63,3.19,1,24,61,9
20,test,None,None,afternoon,8076,13901,10310,74.17,90.53,85.0,110,256,177,9,0.52,6.57,16.01,2.38,72,913,2226,331
21,test,None,None,evening,6303,10728,7122,66.39,84.48,54.0,115,266,169,11,0.92,10.51,17.70,4.05,99,1127,1899,435
22,test,None,None,morning,4440,7448,5113,68.65,83.28,59.0,111,235,150,11,0.58,11.98,14.45,4.16,43,892,1076,310
23,test,None,None,rest_evening,2639,3912,2558,65.39,84.64,29.0,118,292,181,12,0.56,11.20,18.76,3.58,22,438,734,140
24,test,None,None,rest_morning,2323,3450,2278,66.03,84.43,105.0,114,194,141,8,2.38,10.17,17.86,3.01,82,351,616,104

In [43]:
overall_session_entertainment.to_clipboard(index=False)

In [30]:
overall_session_entertainment.to_csv('overall_session_entertainment.csv',index=False)

In [45]:
overall_cluster_query=f"""
with exp_category as(
select
    userid as user_id,
    case    when name='CaptainSearchEntertainmentNewsTest' then 'test' 
            else 'control'
    end as test_group
from
   canonical.user_selector
where
    yyyymmdd = '20240905'
    and selectorid in ('66d9ebe38a94b100011bfea8','66d9ed054c9b3100015a374a')

),

rr_net AS (
    SELECT 
        yyyymmdd, 
        customer_id,
        order_id, 
        order_status, 
        modified_order_status, 
        spd_fraud_flag,
        quarter_hour,
        CASE 
            WHEN pickup_cluster IN (              
                'Hitech City', 
                'Shamshabad', 
                'Kukatpally 3', 
                'Bodduppal', 
                'Mehedipatnam', 
                'Kothaguda 2', 
                'Mothinagar', 
                'Banjara Hills', 
                'Gandipet', 
                'Manikonda',
                'Marredpally'
            ) THEN pickup_cluster
            ELSE 'Other_clusters'
        END AS cluster_name,
        CASE 
            WHEN modified_order_status IN ('OCARA', 'COBRA', 'COBRM') 
            THEN (customer_cancelled_epoch / 1000 - order_requested_epoch / 1000) 
        END AS time_spent_in_sec,
        CASE 
            WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') 
            THEN (rider_accepted_epoch / 1000 - order_requested_epoch / 1000)
        END AS time_taken_to_accp
        
    
    FROM 
        orders.order_logs_fact fact
    WHERE 
         yyyymmdd >= '20240911' AND yyyymmdd <= '20240916'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city_name = 'Hyderabad'
        AND service_obj_service_name in ('Auto','Auto Lite','Auto NCR','Auto Pool','AutoPremium','CityAuto','Link','Bike Lite','Bike Pink','CabEconomy','Bike Metro', 'CabPremium')
        AND channel_host='android'
        AND customer_id in (
                select
                    user_id
        from 
            clevertap.clevertap_customer_order_activity
        where 
            yyyymmdd >= '20240911' AND yyyymmdd <= '20240916'
            AND order_activity_source = 'appOpen'
            and current_city = 'Hyderabad'
            and platform='Android'
            and app_version>='8.30.0'           
            )
         
),

view_tbl as(

    select
        yyyymmdd,
        profile_identity as user_id,
        'viewed' as event_type
    from 
        clevertap.customer_notification_viewed_immutable 
    where yyyymmdd >= '20240911' and yyyymmdd<='20240916'
    and event_props_campaign_id = '1725971599'

),

click_tbl as(
    select
        yyyymmdd,
        profile_identity as user_id,
        CASE
                    when event_props_wzrk_c2a='Button 2' then 'play_click'
                    else 'close_click'
        end as click_type
    from 
        clevertap.customer_notification_clicked_immutable
    where yyyymmdd >= '20240911' and yyyymmdd<='20240916'
    and event_props_campaign_id = '1725971599'

),
merge as(
    select exp_category.*,
            rr_net.yyyymmdd,
            rr_net.order_id,
            rr_net.order_status,
            rr_net.modified_order_status,
            rr_net.spd_fraud_flag,
            rr_net.quarter_hour,
            rr_net.time_spent_in_sec,
            rr_net.time_taken_to_accp,
            rr_net.cluster_name,
            view_tbl.event_type,
            click_tbl.click_type
    from
        exp_category
    left join 
            rr_net 
        on exp_category.user_id=rr_net.customer_id
    left join
            view_tbl
        on rr_net.customer_id=view_tbl.user_id
           and rr_net.yyyymmdd=view_tbl.yyyymmdd
    left join
            click_tbl
        on rr_net.customer_id=click_tbl.user_id
        and view_tbl.yyyymmdd=click_tbl.yyyymmdd

)

SELECT
        test_group,
        event_type,
        click_type,
        cluster_name,
        customers,

        gross_count,
        net_count,
        
        COALESCE(TRY(net_count*100.00/gross_count), 0) g2n,
        
        COALESCE(TRY(tot_accepted*100.00/gross_count), 0) "aor",
        
        
        median_cobrm_time,
        median_cobra_time,
        median_ocara_time,
        median_cancellation_time,
        median_acceptance_time,
        
        COALESCE(TRY(cobrm*100.00/gross_count), 0) "% cobrm",
        COALESCE(TRY(cobra*100.00/gross_count), 0) "% cobra",
        COALESCE(TRY(ocara*100.00/gross_count), 0) "% ocara",
        COALESCE(TRY(expired*100.00/gross_count), 0) "% expired",
        cobrm, 
        cobra,
        ocara,
        expired
    FROM    
        (
        SELECT
            test_group,
            event_type,
            click_type,
            cluster_name,
            COUNT(DISTINCT user_id) customers,
            COUNT(DISTINCT order_id) gross_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' AND spd_fraud_flag != true THEN order_id END) net_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN order_id END) AS tot_accepted,

        
           
            
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRM' THEN order_id END) cobrm,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRA' THEN order_id END) cobra,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'OCARA' THEN order_id END) ocara,
            COUNT(DISTINCT CASE WHEN order_status = 'expired' THEN order_id END) expired,
            
            approx_percentile(CASE WHEN modified_order_status = 'COBRM' THEN time_spent_in_sec END,0.50) as median_cobrm_time,
            approx_percentile(CASE WHEN modified_order_status = 'COBRA' THEN time_spent_in_sec END,0.50) as median_cobra_time,
            approx_percentile(CASE WHEN modified_order_status = 'OCARA' THEN time_spent_in_sec END,0.50) as median_ocara_time,
            approx_percentile(CASE WHEN modified_order_status in ('COBRA','COBRM','OCARA') THEN time_spent_in_sec END,0.50) as median_cancellation_time,
            approx_percentile(CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN time_taken_to_accp END,0.50) as median_acceptance_time
            
        FROM 
            merge
        where 
            yyyymmdd is not null
           and NOT (test_group = 'control' AND event_type IS NOT NULL)
           and NOT (event_type IS NULL AND click_type IS NOT NULL)
        GROUP BY 1,2,3,4
        )
    ORDER BY 1,2,3,4

"""

overall_cluster_entertainment=pd.read_sql(overall_cluster_query,conn)

/var/folders/km/1ltm54y105x6dzlcf44g881c0000gn/T/ipykernel_52024/3318123340.py:198: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  overall_cluster_entertainment=pd.read_sql(overall_cluster_query,conn)

In [47]:
overall_cluster_entertainment=overall_cluster_entertainment[overall_cluster_entertainment['click_type']=='play_click']

In [48]:
overall_cluster_entertainment

,test_group,event_type,click_type,cluster_name,customers,gross_count,net_count,g2n,aor,median_cobrm_time,median_cobra_time,median_ocara_time,median_cancellation_time,median_acceptance_time,% cobrm,% cobra,% ocara,% expired,cobrm,cobra,ocara,expired
24,test,viewed,play_click,Banjara Hills,59,86,52,60.47,79.07,NaN,95,214,191,23,0.00,15.12,18.60,5.81,0,13,16,5
25,test,viewed,play_click,Bodduppal,27,35,27,77.14,94.29,NaN,209,176,176,6,0.00,2.86,17.14,2.86,0,1,6,1
26,test,viewed,play_click,Gandipet,20,26,16,61.54,73.08,NaN,16,208,105,7,0.00,15.38,11.54,11.54,0,4,3,3
27,test,viewed,play_click,Hitech City,154,231,114,49.35,72.73,58.0,64,137,109,11,0.87,18.61,23.38,7.79,2,43,54,18
28,test,viewed,play_click,Kothaguda 2,41,64,34,53.13,75.00,151.0,114,226,184,9,1.56,12.50,21.88,10.94,1,8,14,7
29,test,viewed,play_click,Kukatpally 3,64,88,58,65.91,88.64,11.0,138,187,138,11,1.14,5.68,21.59,4.55,1,5,19,4
30,test,viewed,play_click,Manikonda,50,75,45,60.00,82.67,NaN,185,272,233,9,0.00,12.00,22.67,5.33,0,9,17,4
31,test,viewed,play_click,Marredpally,54,65,48,73.85,89.23,NaN,115,186,136,12,0.00,10.77,15.38,0.00,0,7,10,0
32,test,viewed,play_click,Mehedipatnam,77,118,74,62.71,78.81,NaN,73,488,111,10,0.00,17.80,15.25,3.39,0,21,18,4
33,test,viewed,play_click,Mothinagar,44,66,41,62.12,77.27,11.0,119,189,119,11,1.52,15.15,15.15,6.06,1,10,10,4
34,test,viewed,play_click,Other_clusters,2217,3799,2404,63.28,82.86,58.0,94,226,142,10,1.32,11.90,19.01,3.92,50,452,722,149
35,test,viewed,play_click,Shamshabad,98,138,83,60.14,88.41,NaN,91,149,106,6,0.00,8.70,28.26,2.90,0,12,39,4

In [49]:
overall_cluster_entertainment.to_clipboard(index=False)

In [52]:
overall_cluster_query_benchmark=f"""


with rr_net AS (
    SELECT 
        yyyymmdd, 
        customer_id,
        order_id, 
        order_status, 
        modified_order_status, 
        spd_fraud_flag,
        quarter_hour,
        CASE 
            WHEN pickup_cluster IN (              
                'Hitech City', 
                'Shamshabad', 
                'Kukatpally 3', 
                'Bodduppal', 
                'Mehedipatnam', 
                'Kothaguda 2', 
                'Mothinagar', 
                'Banjara Hills', 
                'Gandipet', 
                'Manikonda',
                'Marredpally'
            ) THEN pickup_cluster
            ELSE 'Other_clusters'
        END AS cluster_name,
        CASE 
            WHEN modified_order_status IN ('OCARA', 'COBRA', 'COBRM') 
            THEN (customer_cancelled_epoch / 1000 - order_requested_epoch / 1000) 
        END AS time_spent_in_sec,
        CASE 
            WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') 
            THEN (rider_accepted_epoch / 1000 - order_requested_epoch / 1000)
        END AS time_taken_to_accp
        
    
    FROM 
        orders.order_logs_fact fact
    WHERE 
         yyyymmdd >= '20240911' AND yyyymmdd <= '20240916'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city_name = 'Hyderabad'
        AND service_obj_service_name in ('Auto','Auto Lite','Auto NCR','Auto Pool','AutoPremium','CityAuto','Link','Bike Lite','Bike Pink','CabEconomy','Bike Metro', 'CabPremium')
        AND channel_host='android'
        AND customer_id in (
                select
                    user_id
        from 
            clevertap.clevertap_customer_order_activity
        where 
            yyyymmdd >= '20240911' AND yyyymmdd <= '20240916'
            AND order_activity_source = 'appOpen'
            and current_city = 'Hyderabad'
            and platform='Android'
            and app_version>='8.30.0'           
            )
         
)




SELECT
        
        cluster_name,
        customers,

        gross_count,
        net_count,
        
        COALESCE(TRY(net_count*100.00/gross_count), 0) g2n,
        
        COALESCE(TRY(tot_accepted*100.00/gross_count), 0) "aor",
        
        
        median_cobrm_time,
        median_cobra_time,
        median_ocara_time,
        median_cancellation_time,
        median_acceptance_time,
        
        COALESCE(TRY(cobrm*100.00/gross_count), 0) "% cobrm",
        COALESCE(TRY(cobra*100.00/gross_count), 0) "% cobra",
        COALESCE(TRY(ocara*100.00/gross_count), 0) "% ocara",
        COALESCE(TRY(expired*100.00/gross_count), 0) "% expired",
        cobrm, 
        cobra,
        ocara,
        expired
    FROM    
        (
        SELECT
            
            cluster_name,
            COUNT(DISTINCT customer_id) customers,
            COUNT(DISTINCT order_id) gross_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' AND spd_fraud_flag != true THEN order_id END) net_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN order_id END) AS tot_accepted,

        
           
            
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRM' THEN order_id END) cobrm,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRA' THEN order_id END) cobra,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'OCARA' THEN order_id END) ocara,
            COUNT(DISTINCT CASE WHEN order_status = 'expired' THEN order_id END) expired,
            
            approx_percentile(CASE WHEN modified_order_status = 'COBRM' THEN time_spent_in_sec END,0.50) as median_cobrm_time,
            approx_percentile(CASE WHEN modified_order_status = 'COBRA' THEN time_spent_in_sec END,0.50) as median_cobra_time,
            approx_percentile(CASE WHEN modified_order_status = 'OCARA' THEN time_spent_in_sec END,0.50) as median_ocara_time,
            approx_percentile(CASE WHEN modified_order_status in ('COBRA','COBRM','OCARA') THEN time_spent_in_sec END,0.50) as median_cancellation_time,
            approx_percentile(CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN time_taken_to_accp END,0.50) as median_acceptance_time
            
        FROM 
            rr_net
        where 
            yyyymmdd is not null
           
        GROUP BY 1
        )
    ORDER BY 1

"""

overall_cluster_entertainment_benchmark=pd.read_sql(overall_cluster_query_benchmark,conn)

/var/folders/km/1ltm54y105x6dzlcf44g881c0000gn/T/ipykernel_52024/1331892875.py:128: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  overall_cluster_entertainment_benchmark=pd.read_sql(overall_cluster_query_benchmark,conn)

In [53]:
overall_cluster_entertainment_benchmark

,cluster_name,customers,gross_count,net_count,g2n,aor,median_cobrm_time,median_cobra_time,median_ocara_time,median_cancellation_time,median_acceptance_time,% cobrm,% cobra,% ocara,% expired,cobrm,cobra,ocara,expired
0,Banjara Hills,31257,58019,36406,62.75,81.58,60,114,293,175,15,1.08,12.40,18.47,4.92,628,7196,10718,2856
1,Bodduppal,20126,35946,28865,80.30,94.50,55,102,243,182,7,0.28,3.72,13.69,1.50,100,1338,4922,539
2,Gandipet,6944,13920,7712,55.40,74.95,103,125,273,167,10,1.65,16.81,19.15,6.57,230,2340,2665,914
3,Hitech City,57528,116724,72058,61.73,79.29,61,111,238,152,12,1.00,14.25,17.26,5.45,1167,16637,20147,6356
4,Kothaguda 2,18078,34797,22162,63.69,81.25,87,116,267,163,11,0.76,13.05,17.21,4.93,263,4541,5987,1716
5,Kukatpally 3,28348,49167,36279,73.79,90.13,30,104,252,173,9,0.47,6.54,15.90,2.85,230,3217,7818,1401
6,Manikonda,17866,34212,23986,70.11,87.28,35,112,254,170,10,0.27,9.17,16.84,3.26,93,3137,5760,1116
7,Marredpally,17377,29046,21097,72.63,89.32,57,108,278,181,10,0.22,8.20,16.29,2.24,64,2382,4731,651
8,Mehedipatnam,31442,58502,40223,68.75,86.41,58,109,278,177,11,0.88,8.60,17.30,4.09,516,5033,10120,2393
9,Mothinagar,16857,32854,21412,65.17,83.35,97,115,282,177,11,0.89,11.08,17.87,4.68,291,3641,5871,1536
10,Other_clusters,871074,2248433,1536500,68.34,85.51,74,114,274,173,10,0.74,9.96,16.78,3.78,16716,223913,377392,85006
11,Shamshabad,47390,86102,61867,71.85,90.47,91,111,259,184,7,0.44,6.75,18.19,2.33,382,5813,15663,2002

In [54]:
overall_cluster_entertainment_benchmark.to_clipboard(index=False)

In [55]:
overall_cluster_session_query=f"""
with exp_category as(
select
    userid as user_id,
    case    when name='CaptainSearchEntertainmentNewsTest' then 'test' 
            else 'control'
    end as test_group
from
   canonical.user_selector
where
    yyyymmdd = '20240905'
    and selectorid in ('66d9ebe38a94b100011bfea8','66d9ed054c9b3100015a374a')

),

rr_net AS (
    SELECT 
        yyyymmdd, 
        customer_id,
        order_id, 
        order_status, 
        modified_order_status, 
        spd_fraud_flag,
        quarter_hour,
        CASE 
            WHEN pickup_cluster IN (              
                'Hitech City', 
                'Shamshabad', 
                'Kukatpally 3', 
                'Bodduppal', 
                'Mehedipatnam', 
                'Kothaguda 2', 
                'Mothinagar', 
                'Banjara Hills', 
                'Gandipet', 
                'Manikonda',
                'Marredpally'
            ) THEN pickup_cluster
            ELSE 'Other_clusters'
        END AS cluster_name,
        CASE 
            WHEN modified_order_status IN ('OCARA', 'COBRA', 'COBRM') 
            THEN (customer_cancelled_epoch / 1000 - order_requested_epoch / 1000) 
        END AS time_spent_in_sec,
        CASE 
            WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') 
            THEN (rider_accepted_epoch / 1000 - order_requested_epoch / 1000)
        END AS time_taken_to_accp
        
    
    FROM 
        orders.order_logs_fact fact
    WHERE 
         yyyymmdd >= '20240911' AND yyyymmdd <= '20240916'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city_name = 'Hyderabad'
        AND service_obj_service_name in ('Auto','Auto Lite','Auto NCR','Auto Pool','AutoPremium','CityAuto','Link','Bike Lite','Bike Pink','CabEconomy','Bike Metro', 'CabPremium')
        AND channel_host='android'
        AND customer_id in (
                select
                    user_id
        from 
            clevertap.clevertap_customer_order_activity
        where 
            yyyymmdd >= '20240911' AND yyyymmdd <= '20240916'
            AND order_activity_source = 'appOpen'
            and current_city = 'Hyderabad'
            and platform='Android'
            and app_version>='8.30.0'           
            )
         
),

view_tbl as(

    select
        yyyymmdd,
        profile_identity as user_id,
        'viewed' as event_type
    from 
        clevertap.customer_notification_viewed_immutable 
    where yyyymmdd >= '20240911' and yyyymmdd<='20240916'
    and event_props_campaign_id = '1725971599'

),

click_tbl as(
    select
        yyyymmdd,
        profile_identity as user_id,
        CASE
                    when event_props_wzrk_c2a='Button 2' then 'play_click'
                    else 'close_click'
        end as click_type
    from 
        clevertap.customer_notification_clicked_immutable
    where yyyymmdd >= '20240911' and yyyymmdd<='20240916'
    and event_props_campaign_id = '1725971599'

),
merge as(
    select exp_category.*,
            rr_net.yyyymmdd,
            rr_net.order_id,
            rr_net.order_status,
            rr_net.modified_order_status,
            rr_net.spd_fraud_flag,
            rr_net.quarter_hour,
            rr_net.time_spent_in_sec,
            rr_net.time_taken_to_accp,
            rr_net.cluster_name,
            view_tbl.event_type,
            click_tbl.click_type
    from
        exp_category
    left join 
            rr_net 
        on exp_category.user_id=rr_net.customer_id
    left join
            view_tbl
        on rr_net.customer_id=view_tbl.user_id
           and rr_net.yyyymmdd=view_tbl.yyyymmdd
    left join
            click_tbl
        on rr_net.customer_id=click_tbl.user_id
        and view_tbl.yyyymmdd=click_tbl.yyyymmdd

)

SELECT
        test_group,
        event_type,
        click_type,
        time_period,
        cluster_name,
        customers,

        gross_count,
        net_count,
        
        COALESCE(TRY(net_count*100.00/gross_count), 0) g2n,
        
        COALESCE(TRY(tot_accepted*100.00/gross_count), 0) "aor",
        
        
        median_cobrm_time,
        median_cobra_time,
        median_ocara_time,
        median_cancellation_time,
        median_acceptance_time,
        
        COALESCE(TRY(cobrm*100.00/gross_count), 0) "% cobrm",
        COALESCE(TRY(cobra*100.00/gross_count), 0) "% cobra",
        COALESCE(TRY(ocara*100.00/gross_count), 0) "% ocara",
        COALESCE(TRY(expired*100.00/gross_count), 0) "% expired",
        cobrm, 
        cobra,
        ocara,
        expired
    FROM    
        (
        SELECT
            test_group,
            event_type,
            click_type,
            case
                WHEN quarter_hour >= '0800' AND quarter_hour < '1100' THEN 'morning'
                WHEN quarter_hour >= '1100' AND quarter_hour < '1700' THEN 'afternoon'
                WHEN quarter_hour >= '1700' AND quarter_hour < '2100' THEN 'evening'
                WHEN quarter_hour >= '0000' AND quarter_hour < '0800' THEN 'rest_morning'
                ELSE 'rest_evening'
            end as time_period,
            cluster_name,
            COUNT(DISTINCT user_id) customers,
            COUNT(DISTINCT order_id) gross_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' AND spd_fraud_flag != true THEN order_id END) net_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN order_id END) AS tot_accepted,

        
           
            
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRM' THEN order_id END) cobrm,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRA' THEN order_id END) cobra,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'OCARA' THEN order_id END) ocara,
            COUNT(DISTINCT CASE WHEN order_status = 'expired' THEN order_id END) expired,
            
            approx_percentile(CASE WHEN modified_order_status = 'COBRM' THEN time_spent_in_sec END,0.50) as median_cobrm_time,
            approx_percentile(CASE WHEN modified_order_status = 'COBRA' THEN time_spent_in_sec END,0.50) as median_cobra_time,
            approx_percentile(CASE WHEN modified_order_status = 'OCARA' THEN time_spent_in_sec END,0.50) as median_ocara_time,
            approx_percentile(CASE WHEN modified_order_status in ('COBRA','COBRM','OCARA') THEN time_spent_in_sec END,0.50) as median_cancellation_time,
            approx_percentile(CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN time_taken_to_accp END,0.50) as median_acceptance_time
            
        FROM 
            merge
        where 
            yyyymmdd is not null
           and NOT (test_group = 'control' AND event_type IS NOT NULL)
           and NOT (event_type IS NULL AND click_type IS NOT NULL)
        GROUP BY 1,2,3,4,5
        )
    ORDER BY 1,2,3,4,5

"""

overall_cluster_entertainment_session=pd.read_sql(overall_cluster_session_query,conn)

/var/folders/km/1ltm54y105x6dzlcf44g881c0000gn/T/ipykernel_52024/2913115380.py:206: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  overall_cluster_entertainment_session=pd.read_sql(overall_cluster_session_query,conn)

In [56]:
overall_cluster_entertainment_session=overall_cluster_entertainment_session[overall_cluster_entertainment_session['click_type']=='play_click']

In [57]:
overall_cluster_entertainment_session

,test_group,event_type,click_type,time_period,cluster_name,customers,gross_count,net_count,g2n,aor,median_cobrm_time,median_cobra_time,median_ocara_time,median_cancellation_time,median_acceptance_time,% cobrm,% cobra,% ocara,% expired,cobrm,cobra,ocara,expired
120,test,viewed,play_click,afternoon,Banjara Hills,19,26,14,53.85,92.31,NaN,185.0,407.0,311.0,11.0,0.00,3.85,38.46,3.85,0,1,10,1
121,test,viewed,play_click,afternoon,Bodduppal,8,9,6,66.67,88.89,NaN,209.0,2229.0,209.0,6.0,0.00,11.11,22.22,0.00,0,1,2,0
122,test,viewed,play_click,afternoon,Gandipet,10,12,8,66.67,83.33,NaN,11.0,1016.0,105.0,8.0,0.00,8.33,16.67,8.33,0,1,2,1
123,test,viewed,play_click,afternoon,Hitech City,56,61,47,77.05,95.08,15.0,27.0,97.0,47.0,8.0,1.64,3.28,18.03,0.00,1,2,11,0
124,test,viewed,play_click,afternoon,Kothaguda 2,17,24,16,66.67,91.67,NaN,110.0,173.0,144.0,9.0,0.00,8.33,25.00,0.00,0,2,6,0
125,test,viewed,play_click,afternoon,Kukatpally 3,24,33,22,66.67,96.97,NaN,138.0,412.0,412.0,8.0,0.00,3.03,27.27,0.00,0,1,9,0
126,test,viewed,play_click,afternoon,Manikonda,17,24,15,62.50,87.50,NaN,173.0,397.0,173.0,8.0,0.00,4.17,25.00,8.33,0,1,6,2
127,test,viewed,play_click,afternoon,Marredpally,17,18,15,83.33,94.44,NaN,15.0,186.0,186.0,14.0,0.00,5.56,11.11,0.00,0,1,2,0
128,test,viewed,play_click,afternoon,Mehedipatnam,34,55,32,58.18,74.55,NaN,73.0,488.0,82.0,10.0,0.00,18.18,16.36,7.27,0,10,9,4
129,test,viewed,play_click,afternoon,Mothinagar,11,14,11,78.57,92.86,NaN,NaN,55.0,55.0,10.0,0.00,0.00,14.29,7.14,0,0,2,1
130,test,viewed,play_click,afternoon,Other_clusters,922,1373,916,66.72,86.38,41.0,94.0,216.0,149.0,8.0,0.95,9.47,19.01,3.20,13,130,261,44
131,test,viewed,play_click,afternoon,Shamshabad,38,49,26,53.06,89.80,NaN,68.0,86.0,68.0,6.0,0.00,8.16,36.73,2.04,0,4,18,1
132,test,viewed,play_click,evening,Banjara Hills,26,36,19,52.78,66.67,NaN,95.0,214.0,179.0,57.0,0.00,22.22,13.89,11.11,0,8,5,4
133,test,viewed,play_click,evening,Bodduppal,8,8,8,100.00,100.00,NaN,NaN,NaN,NaN,7.0,0.00,0.00,0.00,0.00,0,0,0,0
134,test,viewed,play_click,evening,Gandipet,6,7,3,42.86,42.86,NaN,16.0,NaN,16.0,5.0,0.00,28.57,0.00,28.57,0,2,0,2
135,test,viewed,play_click,evening,Hitech City,67,111,36,32.43,58.56,58.0,96.0,141.0,110.0,20.0,0.90,26.13,26.13,14.41,1,29,29,16
136,test,viewed,play_click,evening,Kothaguda 2,12,16,9,56.25,87.50,NaN,227.0,340.0,340.0,6.0,0.00,6.25,31.25,6.25,0,1,5,1
137,test,viewed,play_click,evening,Kukatpally 3,15,23,12,52.17,78.26,11.0,165.0,106.0,133.0,17.0,4.35,4.35,26.09,13.04,1,1,6,3
138,test,viewed,play_click,evening,Manikonda,12,14,10,71.43,85.71,NaN,12.0,621.0,115.0,16.0,0.00,7.14,14.29,7.14,0,1,2,1
139,test,viewed,play_click,evening,Marredpally,22,25,19,76.00,92.00,NaN,136.0,289.0,136.0,13.0,0.00,8.00,16.00,0.00,0,2,4,0
140,test,viewed,play_click,evening,Mehedipatnam,25,37,22,59.46,72.97,NaN,116.0,810.0,116.0,11.0,0.00,27.03,13.51,0.00,0,10,5,0
141,test,viewed,play_click,evening,Mothinagar,16,18,15,83.33,100.00,NaN,NaN,189.0,189.0,9.0,0.00,0.00,16.67,0.00,0,0,3,0
142,test,viewed,play_click,evening,Other_clusters,824,1147,721,62.86,82.04,129.0,104.0,216.0,145.0,12.0,1.83,11.60,18.66,4.53,21,133,214,52
143,test,viewed,play_click,evening,Shamshabad,38,49,33,67.35,91.84,NaN,14.0,194.0,115.0,6.0,0.00,8.16,24.49,0.00,0,4,12,0
144,test,viewed,play_click,morning,Banjara Hills,9,9,8,88.89,100.00,NaN,NaN,161.0,161.0,8.0,0.00,0.00,11.11,0.00,0,0,1,0
145,test,viewed,play_click,morning,Bodduppal,11,13,9,69.23,92.31,NaN,NaN,163.0,163.0,6.0,0.00,0.00,23.08,7.69,0,0,3,1
146,test,viewed,play_click,morning,Gandipet,6,7,5,71.43,85.71,NaN,127.0,208.0,208.0,13.0,0.00,14.29,14.29,0.00,0,1,1,0
147,test,viewed,play_click,morning,Hitech City,23,26,12,46.15,76.92,NaN,60.0,130.0,109.0,9.0,0.00,19.23,30.77,3.85,0,5,8,1
148,test,viewed,play_click,morning,Kothaguda 2,11,21,6,28.57,42.86,151.0,114.0,387.0,228.0,79.0,4.76,23.81,14.29,28.57,1,5,3,6
149,test,viewed,play_click,morning,Kukatpally 3,12,13,12,92.31,100.00,NaN,NaN,128.0,128.0,11.0,0.00,0.00,7.69,0.00,0,0,1,0
150,test,viewed,play_click,morning,Manikonda,15,25,13,52.00,76.00,NaN,250.0,416.0,272.0,11.0,0.00,20.00,24.00,4.00,0,5,6,1
151,test,viewed,play_click,morning,Marredpally,6,9,6,66.67,77.78,NaN,262.0,57.0,57.0,10.0,0.00,22.22,11.11,0.00,0,2,1,0
152,test,viewed,play_click,morning,Mehedipatnam,12,13,10,76.92,100.00,NaN,NaN,900.0,900.0,7.0,0.00,0.00,15.38,0.00,0,0,2,0
153,test,viewed,play_click,morning,Mothinagar,11,22,9,40.91,50.00,11.0,115.0,522.0,119.0,110.0,4.55,36.36,9.09,9.09,1,8,2,2
154,test,viewed,play_click,morning,Other_clusters,460,622,383,61.58,78.94,109.0,79.0,243.0,120.0,11.0,0.64,16.88,17.20,3.54,4,105,107,22
155,test,viewed,play_click,morning,Shamshabad,18,19,12,63.16,89.47,NaN,NaN,979.0,979.0,5.0,0.00,0.00,26.32,10.53,0,0,5,2
156,test,viewed,play_click,rest_evening,Banjara Hills,7,9,6,66.67,66.67,NaN,214.0,NaN,214.0,19.0,0.00,33.33,0.00,0.00,0,3,0,0
157,test,viewed,play_click,rest_evening,Bodduppal,1,1,1,100.00,100.00,NaN,NaN,NaN,NaN,4.0,0.00,0.00,0.00,0.00,0,0,0,0
158,test,viewed,play_click,rest_evening,Hitech City,18,21,13,61.90,80.95,NaN,106.0,348.0,133.0,10.0,0.00,14.29,19.05,4.76,0,3,4,1
159,test,viewed,play_click,rest_evening,Kothaguda 2,1,2,2,100.00,100.00,NaN,NaN,NaN,NaN,6.0,0.00,0.00,0.00,0.00,0,0,0,0
160,test,viewed,play_click,rest_evening,Kukatpally 3,6,8,5,62.50,75.00,NaN,38.0,481.0,481.0,10.0,0.00,12.50,12.50,12.50,0,1,1,1
161,test,viewed,play_click,rest_evening,Manikonda,4,6,3,50.00,100.00,NaN,NaN,184.0,184.0,5.0,0.00,0.00,50.00,0.00,0,0,3,0
162,test,viewed,play_click,rest_evening,Marredpally,4,5,2,40.00,60.00,NaN,252.0,753.0,252.0,5.0,0.00,40.00,20.00,0.00,0,2,1,0
163,test,viewed,play_click,rest_evening,Mehedipatnam,5,5,5,100.00,100.00,NaN,NaN,NaN,NaN,10.0,0.00,0.00,0.00,0.00,0,0,0,0
164,test,viewed,play_click,rest_evening,Mothinagar,6,8,4,50.00,62.50,NaN,196.0,301.0,196.0,7.0,0.00,25.00,12.50,12.50,0,2,1,1
165,test,viewed,play_click,rest_evening,Other_clusters,287,407,230,56.51,78.13,53.0,102.0,324.0,151.0,11.0,2.21,15.97,21.13,3.69,9,65,86,15
166,test,viewed,play_click,rest_evening,Shamshabad,8,10,4,40.00,80.00,NaN,157.0,863.0,706.0,46.0,0.00,10.00,40.00,10.00,0,1,4,1
167,test,viewed,play_click,rest_morning,Banjara Hills,5,6,5,83.33,83.33,NaN,13.0,NaN,13.0,8.0,0.00,16.67,0.00,0.00,0,1,0,0
168,test,viewed,play_click,rest_morning,Bodduppal,3,4,3,75.00,100.00,NaN,NaN,176.0,176.0,11.0,0.00,0.00,25.00,0.00,0,0,1,0
169,test,viewed,play_click,rest_morning,Hitech City,11,12,6,50.00,66.67,NaN,13.0,339.0,16.0,6.0,0.00,33.33,16.67,0.00,0,4,2,0
170,test,viewed,play_click,rest_morning,Kothaguda 2,1,1,1,100.00,100.00,NaN,NaN,NaN,NaN,5.0,0.00,0.00,0.00,0.00,0,0,0,0
171,test,viewed,play_click,rest_morning,Kukatpally 3,8,11,7,63.64,81.82,NaN,105.0,78.0,78.0,14.0,0.00,18.18,18.18,0.00,0,2,2,0
172,test,viewed,play_click,rest_morning,Manikonda,5,6,4,66.67,66.67,NaN,185.0,NaN,185.0,6.0,0.00,33.33,0.00,0.00,0,2,0,0
173,test,viewed,play_click,rest_morning,Marredpally,7,8,6,75.00,100.00,NaN,NaN,77.0,77.0,22.0,0.00,0.00,25.00,0.00,0,0,2,0
174,test,viewed,play_click,rest_morning,Mehedipatnam,5,8,5,62.50,87.50,NaN,112.0,114.0,112.0,6.0,0.00,12.50,25.00,0.00,0,1,2,0
175,test,viewed,play_click,rest_morning,Mothinagar,4,4,2,50.00,100.00,NaN,NaN,54.0,54.0,5.0,0.00,0.00,50.00,0.00,0,0,2,0
176,test,viewed,play_click,rest_morning,Other_clusters,180,250,154,61.60,84.80,25.0,57.0,159.0,117.0,7.0,1.20,7.60,21.60,6.40,3,19,54,16
177,test,viewed,play_click,rest_morning,Shamshabad,8,11,8,72.73,72.73,NaN,140.0,NaN,140.0,7.0,0.00,27.27,0.00,0.00,0,3,0,0

In [58]:
overall_cluster_entertainment_session.to_clipboard(index=False)

In [59]:
overall_cluster_session_query_benchmark=f"""


with rr_net AS (
    SELECT 
        yyyymmdd, 
        customer_id,
        order_id, 
        order_status, 
        modified_order_status, 
        spd_fraud_flag,
        quarter_hour,
        CASE 
            WHEN pickup_cluster IN (              
                'Hitech City', 
                'Shamshabad', 
                'Kukatpally 3', 
                'Bodduppal', 
                'Mehedipatnam', 
                'Kothaguda 2', 
                'Mothinagar', 
                'Banjara Hills', 
                'Gandipet', 
                'Manikonda',
                'Marredpally'
            ) THEN pickup_cluster
            ELSE 'Other_clusters'
        END AS cluster_name,
        CASE 
            WHEN modified_order_status IN ('OCARA', 'COBRA', 'COBRM') 
            THEN (customer_cancelled_epoch / 1000 - order_requested_epoch / 1000) 
        END AS time_spent_in_sec,
        CASE 
            WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') 
            THEN (rider_accepted_epoch / 1000 - order_requested_epoch / 1000)
        END AS time_taken_to_accp
        
    
    FROM 
        orders.order_logs_fact fact
    WHERE 
         yyyymmdd >= '20240911' AND yyyymmdd <= '20240916'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city_name = 'Hyderabad'
        AND service_obj_service_name in ('Auto','Auto Lite','Auto NCR','Auto Pool','AutoPremium','CityAuto','Link','Bike Lite','Bike Pink','CabEconomy','Bike Metro', 'CabPremium')
        AND channel_host='android'
        AND customer_id in (
                select
                    user_id
        from 
            clevertap.clevertap_customer_order_activity
        where 
            yyyymmdd >= '20240911' AND yyyymmdd <= '20240916'
            AND order_activity_source = 'appOpen'
            and current_city = 'Hyderabad'
            and platform='Android'
            and app_version>='8.30.0'           
            )
         
)




SELECT
        time_period,
        cluster_name,
        customers,

        gross_count,
        net_count,
        
        COALESCE(TRY(net_count*100.00/gross_count), 0) g2n,
        
        COALESCE(TRY(tot_accepted*100.00/gross_count), 0) "aor",
        
        
        median_cobrm_time,
        median_cobra_time,
        median_ocara_time,
        median_cancellation_time,
        median_acceptance_time,
        
        COALESCE(TRY(cobrm*100.00/gross_count), 0) "% cobrm",
        COALESCE(TRY(cobra*100.00/gross_count), 0) "% cobra",
        COALESCE(TRY(ocara*100.00/gross_count), 0) "% ocara",
        COALESCE(TRY(expired*100.00/gross_count), 0) "% expired",
        cobrm, 
        cobra,
        ocara,
        expired
    FROM    
        (
        SELECT
            case
                WHEN quarter_hour >= '0800' AND quarter_hour < '1100' THEN 'morning'
                WHEN quarter_hour >= '1100' AND quarter_hour < '1700' THEN 'afternoon'
                WHEN quarter_hour >= '1700' AND quarter_hour < '2100' THEN 'evening'
                WHEN quarter_hour >= '0000' AND quarter_hour < '0800' THEN 'rest_morning'
                ELSE 'rest_evening'
            end as time_period,
            cluster_name,
            COUNT(DISTINCT customer_id) customers,
            COUNT(DISTINCT order_id) gross_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' AND spd_fraud_flag != true THEN order_id END) net_count,
            COUNT(DISTINCT CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN order_id END) AS tot_accepted,

        
           
            
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRM' THEN order_id END) cobrm,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'COBRA' THEN order_id END) cobra,
            COUNT(DISTINCT CASE WHEN modified_order_status = 'OCARA' THEN order_id END) ocara,
            COUNT(DISTINCT CASE WHEN order_status = 'expired' THEN order_id END) expired,
            
            approx_percentile(CASE WHEN modified_order_status = 'COBRM' THEN time_spent_in_sec END,0.50) as median_cobrm_time,
            approx_percentile(CASE WHEN modified_order_status = 'COBRA' THEN time_spent_in_sec END,0.50) as median_cobra_time,
            approx_percentile(CASE WHEN modified_order_status = 'OCARA' THEN time_spent_in_sec END,0.50) as median_ocara_time,
            approx_percentile(CASE WHEN modified_order_status in ('COBRA','COBRM','OCARA') THEN time_spent_in_sec END,0.50) as median_cancellation_time,
            approx_percentile(CASE WHEN order_status = 'dropped' OR modified_order_status IN ('OCARA', 'aborted') THEN time_taken_to_accp END,0.50) as median_acceptance_time
            
        FROM 
            rr_net
        where 
            yyyymmdd is not null
           
        GROUP BY 1,2
        )
    ORDER BY 1,2

"""

overall_cluster_session__entertainment_benchmark=pd.read_sql(overall_cluster_session_query_benchmark,conn)

/var/folders/km/1ltm54y105x6dzlcf44g881c0000gn/T/ipykernel_52024/2006519071.py:134: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  overall_cluster_session__entertainment_benchmark=pd.read_sql(overall_cluster_session_query_benchmark,conn)

In [60]:
overall_cluster_session__entertainment_benchmark

,time_period,cluster_name,customers,gross_count,net_count,g2n,aor,median_cobrm_time,median_cobra_time,median_ocara_time,median_cancellation_time,median_acceptance_time,% cobrm,% cobra,% ocara,% expired,cobrm,cobra,ocara,expired
0,afternoon,Banjara Hills,14197,20861,14647,70.21,88.19,52,114,288,187,12,0.50,8.57,17.69,2.74,104,1788,3690,572
1,afternoon,Bodduppal,9295,13336,11068,82.99,96.21,70,107,255,202,6,0.10,2.64,12.73,1.06,13,352,1698,141
2,afternoon,Gandipet,3134,5029,2972,59.10,78.25,87,124,261,163,8,1.39,15.15,18.85,5.21,70,762,948,262
3,afternoon,Hitech City,22798,33435,25382,75.91,92.82,54,90,225,166,8,0.51,4.97,16.58,1.70,170,1661,5542,568
4,afternoon,Kothaguda 2,7589,11000,8231,74.83,91.52,94,103,262,182,9,0.53,5.65,16.40,2.30,58,622,1804,253
5,afternoon,Kukatpally 3,12133,17273,13413,77.65,93.47,54,98,265,187,8,0.30,4.45,15.40,1.79,51,768,2660,309
6,afternoon,Manikonda,7773,11670,8744,74.93,91.37,22,102,250,174,9,0.24,6.02,16.22,2.37,28,703,1893,276
7,afternoon,Marredpally,8138,11646,8502,73.00,89.33,60,106,299,189,11,0.20,7.90,15.99,2.57,23,920,1862,299
8,afternoon,Mehedipatnam,14807,23165,16469,71.09,88.60,36,106,283,184,11,0.63,7.34,17.18,3.43,145,1701,3979,794
9,afternoon,Mothinagar,7080,10540,7707,73.12,90.87,73,108,282,192,10,0.81,6.12,17.46,2.20,85,645,1840,232
10,afternoon,Other_clusters,446007,812974,587671,72.29,89.02,64,113,280,187,9,0.51,7.55,16.38,2.92,4154,61366,133148,23770
11,afternoon,Shamshabad,21363,32058,23640,73.74,91.15,79,112,269,189,7,0.29,6.40,16.99,2.16,93,2052,5447,693
12,evening,Banjara Hills,11380,19598,9924,50.64,71.34,64,114,310,168,33,1.87,18.70,20.29,8.06,367,3664,3977,1580
13,evening,Bodduppal,6228,8641,7048,81.56,95.65,33,82,247,189,7,0.29,2.68,13.52,1.37,25,232,1168,118
14,evening,Gandipet,2439,4318,2142,49.61,70.03,84,124,308,172,14,0.95,20.61,20.03,8.41,41,890,865,363
15,evening,Hitech City,23086,44126,20473,46.40,64.75,62,119,264,152,20,1.46,23.62,18.09,10.16,644,10422,7981,4484
16,evening,Kothaguda 2,5633,8892,5456,61.36,81.71,117,114,272,165,15,0.69,13.80,19.97,3.77,61,1227,1776,335
17,evening,Kukatpally 3,8645,12384,9399,75.90,93.06,17,80,248,185,10,0.34,3.81,16.68,2.77,42,472,2066,343
18,evening,Manikonda,5790,8781,6112,69.60,87.89,31,108,280,181,10,0.16,9.27,17.87,2.66,14,814,1569,234
19,evening,Marredpally,5606,7941,5650,71.15,89.67,30,107,276,182,11,0.18,8.08,18.16,2.04,14,642,1442,162
20,evening,Mehedipatnam,10701,15992,10508,65.71,84.61,65,107,295,179,13,1.34,8.95,18.57,5.07,214,1432,2969,811
21,evening,Mothinagar,4617,6427,4645,72.27,91.96,21,92,309,224,9,0.23,5.20,19.34,2.61,15,334,1243,168
22,evening,Other_clusters,348630,610315,405990,66.52,84.58,72,112,284,176,12,0.96,10.18,17.65,4.27,5842,62127,107731,26048
23,evening,Shamshabad,15962,22330,16489,73.84,93.29,111,102,274,201,7,0.32,4.77,18.97,1.60,72,1065,4237,357
24,morning,Banjara Hills,4587,7511,5884,78.34,91.40,60,100,233,159,12,0.57,5.35,12.83,2.68,43,402,964,201
25,morning,Bodduppal,5099,7711,6271,81.33,93.62,29,98,234,165,8,0.16,4.36,11.96,1.87,12,336,922,144
26,morning,Gandipet,1453,2431,1601,65.86,84.49,146,121,213,157,9,0.49,11.19,18.26,3.83,12,272,444,93
27,morning,Hitech City,11343,20018,13090,65.39,80.31,67,106,224,140,12,0.96,14.23,14.68,4.50,193,2848,2938,900
28,morning,Kothaguda 2,4683,9595,4838,50.42,65.26,84,124,271,151,15,1.23,22.98,14.67,10.53,118,2205,1408,1010
29,morning,Kukatpally 3,6003,10008,6697,66.92,81.02,29,115,257,154,12,0.77,12.75,13.85,5.46,77,1276,1386,546
30,morning,Manikonda,4590,8398,5400,64.30,79.95,56,121,241,159,13,0.38,13.81,15.37,5.83,32,1160,1291,490
31,morning,Marredpally,3197,4890,3757,76.83,89.84,60,111,256,171,10,0.10,8.06,12.62,1.98,5,394,617,97
32,morning,Mehedipatnam,5169,8478,5919,69.82,83.42,51,113,251,154,10,1.04,10.17,13.39,5.38,88,862,1135,456
33,morning,Mothinagar,5012,10254,5266,51.36,68.15,94,124,292,164,22,0.96,20.92,16.68,9.98,98,2145,1710,1023
34,morning,Other_clusters,227098,407853,278230,68.22,82.61,72,117,253,158,10,0.61,12.21,14.12,4.56,2506,49818,57582,18615
35,morning,Shamshabad,8799,12870,10063,78.19,93.71,78,110,224,173,6,0.29,4.46,15.13,1.54,37,574,1947,198
36,rest_evening,Banjara Hills,4176,6190,3468,56.03,76.98,53,117,308,182,16,1.18,16.06,20.57,5.77,73,994,1273,357
37,rest_evening,Bodduppal,2133,2849,1996,70.06,90.10,60,117,268,192,9,0.42,7.30,19.20,2.18,12,208,547,62
38,rest_evening,Gandipet,685,1112,498,44.78,65.56,94,128,309,161,12,3.15,21.58,19.69,9.44,35,240,219,105
39,rest_evening,Hitech City,8510,12295,7866,63.98,84.83,71,97,222,151,13,1.00,11.49,20.46,2.64,123,1413,2515,324
40,rest_evening,Kothaguda 2,1975,2715,1820,67.03,87.33,78,112,290,185,10,0.37,9.87,19.37,2.43,10,268,526,66
41,rest_evening,Kukatpally 3,3408,4596,3170,68.97,88.95,63,109,252,184,10,0.63,7.44,19.19,2.94,29,342,882,135
42,rest_evening,Manikonda,1993,2817,1872,66.45,87.18,45,109,250,176,10,0.28,9.73,20.09,2.73,8,274,566,77
43,rest_evening,Marredpally,1942,2531,1763,69.66,87.91,28,104,286,175,11,0.32,9.64,17.70,2.09,8,244,448,53
44,rest_evening,Mehedipatnam,4877,6682,4463,66.79,86.10,81,116,283,186,11,0.64,10.09,18.66,3.13,43,674,1247,209
45,rest_evening,Mothinagar,1919,2521,1708,67.75,89.13,100,99,274,187,9,0.36,8.25,20.51,2.14,9,208,517,54
46,rest_evening,Other_clusters,146142,228163,138843,60.85,81.01,74,114,289,176,12,0.93,13.67,19.59,4.33,2117,31183,44690,9872
47,rest_evening,Shamshabad,7470,10961,6470,59.03,81.23,84,115,283,180,10,0.66,13.49,21.70,4.59,72,1479,2379,503
48,rest_morning,Banjara Hills,2679,3859,2483,64.34,86.14,71,112,267,181,10,1.06,9.02,21.09,3.78,41,348,814,146
49,rest_morning,Bodduppal,2335,3409,2482,72.81,90.55,70,103,195,146,7,1.11,6.16,17.22,2.17,38,210,587,74
50,rest_morning,Gandipet,588,1030,499,48.45,67.09,118,136,276,177,7,6.99,17.09,18.35,8.83,72,176,189,91
51,rest_morning,Hitech City,4879,6850,5247,76.60,94.01,54,84,192,147,6,0.54,4.28,17.09,1.17,37,293,1171,80
52,rest_morning,Kothaguda 2,1789,2595,1817,70.02,88.94,71,93,229,147,8,0.62,8.44,18.23,2.00,16,219,473,52
53,rest_morning,Kukatpally 3,3591,4906,3600,73.38,90.66,70,106,209,148,7,0.63,7.32,16.80,1.39,31,359,824,68
54,rest_morning,Manikonda,1706,2546,1858,72.98,90.73,79,110,234,168,8,0.43,7.31,17.32,1.53,11,186,441,39
55,rest_morning,Marredpally,1431,2038,1425,69.92,88.42,147,119,211,162,8,0.69,8.93,17.76,1.96,14,182,362,40
56,rest_morning,Mehedipatnam,2943,4185,2864,68.43,87.74,85,111,229,165,9,0.62,8.70,18.88,2.94,26,364,790,123
57,rest_morning,Mothinagar,1993,3112,2086,67.03,85.48,140,106,206,148,9,2.70,9.93,18.03,1.90,84,309,561,59
58,rest_morning,Other_clusters,122718,189128,125766,66.50,85.08,93,115,234,158,8,1.11,10.27,18.10,3.54,2097,19419,34241,6701
59,rest_morning,Shamshabad,5468,7883,5205,66.03,87.29,100,118,199,153,6,1.37,8.16,20.97,3.18,108,643,1653,251

In [61]:
overall_cluster_session__entertainment_benchmark.to_clipboard(index=False)

In [15]:
click_bucket=f"""
with olf as (

    SELECT
        yyyymmdd,
        customer_id,
        order_id,
        order_requested_epoch,
        customer_cancelled_epoch,
        dropped_epoch,
        expired_epoch,
        rider_accepted_epoch
        
    FROM 
        orders.order_logs_fact
    WHERE
        yyyymmdd >= '20240911' AND yyyymmdd <= '20240916'
        --yyyymmdd >= date_format({{start_date}},'%Y%m%d')
        --AND yyyymmdd <= date_format({{end_date}},'%Y%m%d')
        AND city_name = 'Hyderabad'
        
    ),




click as(
    select
        yyyymmdd,
        profile_identity as user_id,
        epoch as click_epoch
    from 
        clevertap.customer_notification_clicked_immutable
    where yyyymmdd >= '20240911' and yyyymmdd<='20240916'
    and event_props_wzrk_c2a='Button 2'
    and event_props_campaign_id = '1725971599'

),


merge AS (
    
    SELECT 
        olf.*,
        click_epoch,
        (click_epoch / 1000 - order_requested_epoch / 1000) time_to_click
        --row_number() over(partition by olf.yyyymmdd,olf.customer_id,olf.order_id order by click_epoch) seq_no
    FROM 
        olf
    JOIN 
        click
        on olf.yyyymmdd = click.yyyymmdd
        and olf.customer_id = click.user_id
        and olf.order_requested_epoch < click.click_epoch
        and (olf.customer_cancelled_epoch > click.click_epoch or dropped_epoch > click.click_epoch or 
        expired_epoch > click.click_epoch or rider_accepted_epoch> click.click_epoch)
    )
    
    
   
    
    
    SELECT
        
        case 
        when time_to_click <= 15 then 'a. 15 Sec'
        when time_to_click between 16 and 30 then 'b. 16-30 Sec'
        when time_to_click between 31 and 60 then 'c. 30-60 Sec'
        when time_to_click between 61 and 120 then 'd. 1-2 min'
        when time_to_click between 121 and 240 then 'e. 3-4 min'
        when time_to_click > 240 then 'f. 4+ min' 
        else 'check' end as click_bucket,
        count(distinct customer_id) customers
    FROM 
        merge
    -- WHERE 
    --     --seq_no = 1
    GROUP BY 1
    ORDER BY 1

"""
click_bucket_df = pd.read_sql(click_bucket,conn)

/var/folders/j7/5rtfb17j30s9g9q790v9nr0h0000gn/T/ipykernel_62377/198338273.py:82: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  click_bucket_df = pd.read_sql(click_bucket,conn)

In [16]:
click_bucket_df

   click_bucket  customers
0     a. 15 Sec       2036
1  b. 16-30 Sec        405
2  c. 30-60 Sec        146
3    d. 1-2 min         76
4    e. 3-4 min         53
5     f. 4+ min         32

In [21]:
click_bucket_df.customers.sum()

2748

In [22]:
2629 - 2748

-119

In [23]:
2036-119

1917

In [ ]:
click_bucket_df

In [64]:
total_customers = click_bucket_df['customers'].sum()

# Calculate the percentage of customers for each click_bucket
click_bucket_df['customer_percentage'] = (click_bucket_df['customers'] / total_customers) * 100

# Round the percentage to 2 decimal places
click_bucket_df['customer_percentage'] = click_bucket_df['customer_percentage'].round(2)

In [24]:
click_bucket_df.to_clipboard(index=False)