<div class="alert alert-block alert-info">

### Imports & Connection
</div>

In [2]:
import os
import glob
import numpy as np
import pandas as pd
import seaborn as sns
import plotly.express as px
import matplotlib.pyplot as plt
import datetime as datetime
import plotly.graph_objects as go

from scipy import stats
from pyhive import presto
from IPython.display import display
from datetime import datetime, timedelta
# from scipy.stats import gaussian_kde

import warnings
warnings.filterwarnings('ignore')

In [3]:
pd.set_option('display.max_columns', 50)
pd.set_option('display.max_rows', 100)

In [4]:
## Connection
connection = presto.connect(
        host='presto-gateway.serving.data.production.internal',
        # 'presto-gateway.processing.data.production.internal',
        # 'presto-gateway.serving.data.production.internal',
        port=80,
        protocol='http',
        catalog='hive',
        username='manoj.ravirajan@rapido.bike'
)

In [5]:
start_date = '20241121'
end_date = '20241126'

<div class="alert alert-block alert-info">

### Datasets
</div>

In [6]:
def func_get_data():
    datasets = [
                'monet_vivo_videobanner_21nov2024v4_view',
                'monet_vivo_videobanner_22nov2024v1_view',
                'monet_vivo_videobanner_23nov2024_view',
                'monet_vivo_videobanner_24nov2024_view',
                'monetcluster1_vivo_videobanner_25nov2024v4_view',
                'monetcluster_vivo_videobanner_26nov2024_view'
               ] 
    datasets_list = []

    for dataset in datasets:  
        # query = f""" SELECT * FROM reports_internal.{dataset} """
        # df = pd.read_sql(query, connection)
        
        # df.to_parquet('/Users/E2074/local-datasets/customer/ads-monetisation/vivo-video-campaign/{}.parquet'.format(dataset), index=False)
        df = pd.read_parquet('/Users/E2074/local-datasets/customer/ads-monetisation/vivo-video-campaign/{}.parquet'.format(dataset))
        datasets_list.append(df)
    df_base = pd.concat(datasets_list, ignore_index=True)

    return df_base

df_campaign = func_get_data()
df_campaign.shape

(16521612, 18)

In [7]:
def func_get_customer_mobile_model(start_date, end_date):
    
    query = f"""

        with base as (
        
        select
            customer_id,
            manufacturer,
            model,
            channel_host
        from
            (
            select 
                customer_id,
                channel_host,
                case 
                when length(customer_obj_device_manufacturer) > 0 then lower(customer_obj_device_manufacturer)
                else 'unknown' end as manufacturer, 
                case
                when length(customer_obj_device_model) > 0 then lower(customer_obj_device_model)
                else 'unknown' end as model,
                order_id,
                epoch,
                row_number() over(partition by customer_id order by epoch) rn
            from
                orders.order_logs_snapshot 
            where 
                yyyymmdd >= '{start_date}'
                and yyyymmdd <= '{end_date}'
            )
        where 
            rn = 1
        ),
        
        app_cat as (
            select 
                * 
            from 
                reports.sql_ingestion_customer_appography_category_view 
            where 
                yyyymmdd = '20241229'
        
        )
        
            select
                base.*,
                ai,
                camerafilter,
                courier,
                dating,
                deliveryfood,
                deliverygrocery,
                devotional,
                driverapp,
                ecommerce,
                educational,
                entertainment,
                fantasysports,
                financeinvestment,
                financenews,
                financetransactions,
                gaming,
                government,
                health,
                homesecurity,
                insurance,
                jobsearch,
                news,
                office,
                ott,
                social,
                streamingmusic,
                telecom,
                tools,
                travelbookings,
                travelmetro,
                travelridehailing,
                vehicle,
                wearable
            from 
                base
            left join 
                app_cat
                on base.customer_id = app_cat.userid
        
        
    """
    # df = pd.read_sql(query, connection)
    # df.to_parquet('/Users/E2074/local-datasets/customer/ads-monetisation/vivo-video-campaign/customer_mobile_model.parquet', index=False)

    df = pd.read_parquet('/Users/E2074/local-datasets/customer/ads-monetisation/vivo-video-campaign/customer_mobile_model.parquet')

    return df

df_customer_mobile_model = func_get_customer_mobile_model(start_date, end_date)
df_customer_mobile_model.shape

(8084558, 37)

In [8]:
df_campaign.head(2)

,yyyymmdd,userid,pagename,slotname,orderstatus,format,service,metadata1,response_id,impression_id,viewable_impression_id,click_id,taxi_ltr_segment,taxi_retention_segments,taxi_income_segment,taxi_service_affinity,taxi_regularity_segment,taxi_fe_regularity_segment
0,20241121,573f28f49b0ffc283676f5aa,PostOrderScreen,PostOrderArrived3,arrived,gamCombinedBanner,Auto,"{title=vivo Y300 5G, body=The style game just ...",102ead4f-15c6-49b3-97a5-45d806458a4d573f28f49b...,102ead4f-15c6-49b3-97a5-45d806458a4d573f28f49b...,102ead4f-15c6-49b3-97a5-45d806458a4d573f28f49b...,None,PHH,ELITE,HIGH_INCOME,ONLY_AUTO,DAILY,DAILY
1,20241121,573f28f49b0ffc283676f7a8,PostOrderScreen,PostOrderArrived3,arrived,gamCombinedBanner,CabEconomy,"{title=vivo Y300 5G, body=The style game just ...",5153887c-5a36-4143-9f32-ef9cf7b6e682573f28f49b...,5153887c-5a36-4143-9f32-ef9cf7b6e682573f28f49b...,5153887c-5a36-4143-9f32-ef9cf7b6e682573f28f49b...,None,PHH,PLATINUM,HIGH_INCOME,ONLY_AUTO,WEEKLY,WEEKLY

In [9]:
df_customer_mobile_model.head(2)

,customer_id,manufacturer,model,channel_host,ai,camerafilter,courier,dating,deliveryfood,deliverygrocery,devotional,driverapp,ecommerce,educational,entertainment,fantasysports,financeinvestment,financenews,financetransactions,gaming,government,health,homesecurity,insurance,jobsearch,news,office,ott,social,streamingmusic,telecom,tools,travelbookings,travelmetro,travelridehailing,vehicle,wearable
0,62a34af517af9a2bc4531565,unknown,unknown,android,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0
1,5e0c470f89355c2289a49890,vivo,vivo 1724,ios,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0

In [10]:
df = pd.merge(df_campaign, df_customer_mobile_model, how = 'left', left_on = 'userid', right_on = 'customer_id' )
df.head(1).T

                                                                            0
yyyymmdd                                                             20241121
userid                                               573f28f49b0ffc283676f5aa
pagename                                                      PostOrderScreen
slotname                                                    PostOrderArrived3
orderstatus                                                           arrived
format                                                      gamCombinedBanner
service                                                                  Auto
metadata1                   {title=vivo Y300 5G, body=The style game just ...
response_id                 102ead4f-15c6-49b3-97a5-45d806458a4d573f28f49b...
impression_id               102ead4f-15c6-49b3-97a5-45d806458a4d573f28f49b...
viewable_impression_id      102ead4f-15c6-49b3-97a5-45d806458a4d573f28f49b...
click_id                                                                 None
taxi_ltr_segment                                                          PHH
taxi_retention_segments                                                 ELITE
taxi_income_segment                                               HIGH_INCOME
taxi_service_affinity                                               ONLY_AUTO
taxi_regularity_segment                                                 DAILY
taxi_fe_regularity_segment                                              DAILY
customer_id                                          573f28f49b0ffc283676f5aa
manufacturer                                                          samsung
model                                                                sm-s911b
channel_host                                                          android
ai                                                                        0.0
camerafilter                                                              0.0
courier                                                                   1.0
dating                                                                    0.0
deliveryfood                                                              1.0
deliverygrocery                                                           1.0
devotional                                                                0.0
driverapp                                                                 0.0
ecommerce                                                                 1.0
educational                                                               0.0
entertainment                                                             0.0
fantasysports                                                             0.0
financeinvestment                                                         1.0
financenews                                                               0.0
financetransactions                                                       1.0
gaming                                                                    1.0
government                                                                0.0
health                                                                    1.0
homesecurity                                                              1.0
insurance                                                                 0.0
jobsearch                                                                 1.0
news                                                                      0.0
office                                                                    1.0
ott                                                                       1.0
social                                                                    1.0
streamingmusic                                                            1.0
telecom                                                                   0.0
tools                                                                     1.0
travelbookings                                                            1.0
travelmetro                                                               0.0
travelridehailing                                                         1.0
vehicle                                                                   0.0
wearable                                                                  1.0

<div class="alert alert-block alert-info">

### Data Manipulation
</div>

In [11]:
df['slot'] = df['slotname'].str.replace(r'\d+$', '', regex=True)
df['title'] = df['metadata1'].str.extract(r'title=(.*?),')
df['overall'] = 'Overall'

conditions = [
    (df['yyyymmdd'] == '20241121') & (df['title'] == 'vivo Y300 5G') ,
    (df['yyyymmdd'].isin(['20241121', '20241122', '20241123', '20241124', '20241125'])) & (df['title'] == 'vivo Y300') ,
    (df['yyyymmdd'] == '20241126') & (df['title'] == 'vivo Y300')
]
choices = ['1. Learn More', '2. Prebook Now', '3. Buy Now']

df['campaign'] = np.select(conditions, choices, default='None')
df = df[~df['campaign'].isin(['None']) ]

In [12]:
df.shape

(16520760, 59)

### Understanding

In [13]:
df['campaign'].value_counts()

campaign
1. Learn More     8525062
2. Prebook Now    5959327
3. Buy Now        2036371
Name: count, dtype: int64

<div class="alert alert-block alert-info">

### Analysis
</div>

In [14]:
dict_agg = {
    'response' : ('response_id', 'nunique'),
    'impression' : ('impression_id', 'nunique'),
    'viewable_impression' : ('viewable_impression_id', 'nunique'),
    'click' : ('click_id', 'nunique')
}

In [15]:
def func_get_funnel(df, groupby, dict_agg):
    
    temp_df = df\
                .groupby(groupby)\
                .agg(**dict_agg)\
                .reset_index()

    # temp_df['render rate'] = (temp_df['impression']*100.00/temp_df['response']).round(2)
    temp_df['viewability'] = (temp_df['viewable_impression']*100.00/temp_df['impression']).round(2)
    temp_df['ctr'] = (temp_df['click']*100.00/temp_df['viewable_impression']).round(2)
    
    return temp_df

In [25]:
func_get_funnel(df, ['overall'], dict_agg)

,overall,response,impression,viewable_impression,click,viewability,ctr
0,Overall,16496359,9768849,8041857,43038,82.32,0.54

In [26]:
func_get_funnel(df, ['campaign'], dict_agg)

,campaign,response,impression,viewable_impression,click,viewability,ctr
0,1. Learn More,8525048,4889657,3997838,21646,81.76,0.54
1,2. Prebook Now,5951203,3535301,2899939,14794,82.03,0.51
2,3. Buy Now,2021023,1344745,1144798,6600,85.13,0.58

In [27]:
func_get_funnel(df, ['pagename'], dict_agg)

,pagename,response,impression,viewable_impression,click,viewability,ctr
0,CaptainSearchScreen,6137504,4111632,3275596,23863,79.67,0.73
1,PostOrderScreen,10358855,5657217,4766261,19175,84.25,0.40

In [28]:
func_get_funnel(df, ['slot'], dict_agg)

,slot,response,impression,viewable_impression,click,viewability,ctr
0,CaptainSearch,6137504,4111632,3275596,23863,79.67,0.73
1,PostOrderArrived,2437460,812997,705209,1241,86.74,0.18
2,PostOrderOnTheWay,5124917,3298976,2734558,7803,82.89,0.29
3,PostOrderStarted,2796478,1545244,1326494,10131,85.84,0.76

In [48]:
func_get_funnel(df, ['campaign','slot'], dict_agg)

,campaign,slot,response,impression,viewable_impression,click,viewability,ctr
0,1. Learn More,CaptainSearch,2780507,1874593,1433335,10406,76.46,0.73
1,1. Learn More,PostOrderArrived,2032360,673028,582327,1027,86.52,0.18
2,1. Learn More,PostOrderOnTheWay,2351074,1556397,1295387,4347,83.23,0.34
3,1. Learn More,PostOrderStarted,1361107,785639,686789,5866,87.42,0.85
4,2. Prebook Now,CaptainSearch,2380124,1586258,1304117,9614,82.21,0.74
5,2. Prebook Now,PostOrderArrived,405110,139973,122884,214,87.79,0.17
6,2. Prebook Now,PostOrderOnTheWay,2007776,1210674,975301,1989,80.56,0.20
7,2. Prebook Now,PostOrderStarted,1158193,598396,497637,2977,83.16,0.60
8,3. Buy Now,CaptainSearch,977665,651550,538787,3845,82.69,0.71
9,3. Buy Now,PostOrderArrived,1,1,1,0,100.00,0.00
10,3. Buy Now,PostOrderOnTheWay,766107,531935,463896,1467,87.21,0.32
11,3. Buy Now,PostOrderStarted,277250,161259,142114,1288,88.13,0.91

In [29]:
func_get_funnel(df, ['service'], dict_agg)

,service,response,impression,viewable_impression,click,viewability,ctr
0,,47249,33282,26545,140,79.76,0.53
1,Auto,5855568,3612280,2914329,12554,80.68,0.43
2,Auto C2C,8438,4265,3254,28,76.30,0.86
3,Auto NCR,20815,12445,10357,94,83.22,0.91
4,Auto Pet,2348,1113,817,4,73.41,0.49
5,Auto Pool,19829,9497,6778,120,71.37,1.77
6,AutoPremium,1113,679,529,2,77.91,0.38
7,Bike Lite,1590715,876332,741395,3614,84.60,0.49
8,Bike Metro,265754,150890,129711,478,85.96,0.37
9,Bike Pink,10197,4704,3655,112,77.70,3.06
10,C2C,170699,89794,74354,332,82.81,0.45
11,CabEconomy,1794849,1139406,909709,5686,79.84,0.63
12,CabPremium,22443,13914,12047,65,86.58,0.54
13,E rickshaw,33677,18239,14762,109,80.94,0.74
14,Link,6652695,3802039,3193642,19702,84.00,0.62

In [30]:
func_get_funnel(df, ['taxi_ltr_segment'], dict_agg)

,taxi_ltr_segment,response,impression,viewable_impression,click,viewability,ctr
0,HH,1578342,984399,827553,6315,84.07,0.76
1,PHH,14564830,8603963,7073605,35000,82.21,0.49

In [31]:
func_get_funnel(df, ['taxi_retention_segments'], dict_agg)

,taxi_retention_segments,response,impression,viewable_impression,click,viewability,ctr
0,DORMANT,321473,161215,126330,1372,78.36,1.09
1,ELITE,5529303,3178821,2570235,11271,80.85,0.44
2,GOLD,3040810,1853644,1546655,8272,83.44,0.53
3,HH,1432872,912043,771028,5552,84.54,0.72
4,INACTIVE,130150,65200,51754,627,79.38,1.21
5,PLATINUM,3908900,2321312,1910614,9275,82.31,0.49
6,PRIME,237910,137240,112888,485,82.26,0.43
7,SILVER,1541754,958887,811654,4461,84.65,0.55

In [32]:
func_get_funnel(df, ['taxi_income_segment'], dict_agg)

,taxi_income_segment,response,impression,viewable_impression,click,viewability,ctr
0,HIGH_INCOME,7037870,4410919,3588465,16809,81.35,0.47
1,LOW_INCOME,1061429,556321,464553,3323,83.50,0.72
2,MEDIUM_INCOME,6160157,3395129,2836596,15712,83.55,0.55
3,UNKNOWN,1883716,1225993,1011544,5471,82.51,0.54

In [42]:
df_manufacturer = func_get_funnel(df, ['manufacturer'], dict_agg)
df_manufacturer

,manufacturer,response,impression,viewable_impression,click,viewability,ctr
0,10.or,4,2,1,0,50.00,0.00
1,1091f2d336c60ba8,1,1,1,0,100.00,0.00
2,10or,4641,2668,2235,6,83.77,0.27
3,1280051cee867aa7,3,1,1,0,100.00,0.00
4,13e952b0288a0725,1,1,0,0,0.00,NaN
...,...,...,...,...,...,...,...
614,zopo,32,21,20,0,95.24,0.00
615,zte,668,374,308,1,82.35,0.32
616,zuk,2166,1334,1081,3,81.03,0.28
617,zuum,4,4,3,0,75.00,0.00
618,zyrex,2,2,2,0,100.00,0.00

In [44]:
df_manufacturer.sort_values(by='response', ascending=False).to_clipboard(index=False)

In [33]:
func_get_funnel(df, ['taxi_regularity_segment'], dict_agg)

,taxi_regularity_segment,response,impression,viewable_impression,click,viewability,ctr
0,BI_WEEKLY,3271746,1970233,1639699,8828,83.22,0.54
1,DAILY,4819969,2751452,2220597,9876,80.71,0.44
2,MONTHLY,1410567,872223,731613,4076,83.88,0.56
3,RARE_NEED,475908,299426,253547,1527,84.68,0.60
4,UNKNOWN,1578342,984399,827553,6315,84.07,0.76
5,WEEKLY,4586640,2710629,2228149,10693,82.20,0.48

In [34]:
func_get_funnel(df, ['campaign','taxi_income_segment'], dict_agg)

,campaign,taxi_income_segment,response,impression,viewable_impression,click,viewability,ctr
0,1. Learn More,HIGH_INCOME,3621311,2203039,1780312,8607,80.81,0.48
1,1. Learn More,LOW_INCOME,548415,278473,231129,1689,83.00,0.73
2,1. Learn More,MEDIUM_INCOME,3217905,1714836,1423031,7907,82.98,0.56
3,1. Learn More,UNKNOWN,962049,607814,499542,2757,82.19,0.55
4,2. Prebook Now,HIGH_INCOME,2526880,1587489,1287954,5510,81.13,0.43
5,2. Prebook Now,LOW_INCOME,390029,204519,169645,1176,82.95,0.69
6,2. Prebook Now,MEDIUM_INCOME,2213644,1224051,1017899,5470,83.16,0.54
7,2. Prebook Now,UNKNOWN,686249,448835,368164,1848,82.03,0.50
8,3. Buy Now,HIGH_INCOME,889997,620693,520451,2692,83.85,0.52
9,3. Buy Now,LOW_INCOME,123083,73424,63862,459,86.98,0.72
10,3. Buy Now,MEDIUM_INCOME,729012,456613,395983,2336,86.72,0.59
11,3. Buy Now,UNKNOWN,235494,169412,143891,866,84.94,0.60

In [35]:
func_get_funnel(df, ['yyyymmdd','campaign'], dict_agg)

,yyyymmdd,campaign,response,impression,viewable_impression,click,viewability,ctr
0,20241121,1. Learn More,8525048,4889657,3997838,21646,81.76,0.54
1,20241121,2. Prebook Now,1619421,877217,685560,1758,78.15,0.26
2,20241122,2. Prebook Now,2300407,1310589,1121215,4048,85.55,0.36
3,20241123,2. Prebook Now,689201,446888,367012,2599,82.13,0.71
4,20241124,2. Prebook Now,694594,456259,371187,3012,81.35,0.81
5,20241125,2. Prebook Now,647580,444348,354965,3377,79.88,0.95
6,20241126,3. Buy Now,2021023,1344745,1144798,6600,85.13,0.58

In [36]:
func_get_funnel(df, ['slot', 'service'], dict_agg)

,slot,service,response,impression,viewable_impression,click,viewability,ctr
0,CaptainSearch,,11257,10503,7915,74,75.36,0.93
1,CaptainSearch,Auto,2107726,1503976,1153110,5623,76.67,0.49
2,CaptainSearch,Auto C2C,3262,1662,1099,18,66.13,1.64
3,CaptainSearch,Auto NCR,7541,5617,4619,63,82.23,1.36
4,CaptainSearch,Auto Pet,1127,516,333,1,64.53,0.30
5,CaptainSearch,Auto Pool,8721,6068,3966,113,65.36,2.85
6,CaptainSearch,AutoPremium,389,276,205,1,74.28,0.49
7,CaptainSearch,Bike Lite,583209,351274,294546,2059,83.85,0.70
8,CaptainSearch,Bike Metro,94797,57856,50684,207,87.60,0.41
9,CaptainSearch,Bike Pink,5087,3553,2679,108,75.40,4.03
10,CaptainSearch,C2C,60375,28608,22623,199,79.08,0.88
11,CaptainSearch,CabEconomy,700810,537196,406819,3518,75.73,0.86
12,CaptainSearch,CabPremium,15,13,13,1,100.00,7.69
13,CaptainSearch,E rickshaw,13501,8241,6354,74,77.10,1.16
14,CaptainSearch,Link,2539715,1596301,1320656,11806,82.73,0.89
15,PostOrderArrived,Auto,896018,305691,260474,489,85.21,0.19
16,PostOrderArrived,Auto C2C,1388,510,438,3,85.88,0.68
17,PostOrderArrived,Auto NCR,3122,938,791,2,84.33,0.25
18,PostOrderArrived,Auto Pet,287,89,68,0,76.40,0.00
19,PostOrderArrived,Auto Pool,1531,288,256,0,88.89,0.00
20,PostOrderArrived,AutoPremium,212,55,49,0,89.09,0.00
21,PostOrderArrived,Bike Lite,252731,87145,76603,108,87.90,0.14
22,PostOrderArrived,Bike Metro,38919,16248,13884,18,85.45,0.13
23,PostOrderArrived,Bike Pink,639,149,118,0,79.19,0.00
24,PostOrderArrived,C2C,29598,12962,11465,23,88.45,0.20
25,PostOrderArrived,CabEconomy,240109,74075,63885,142,86.24,0.22
26,PostOrderArrived,CabPremium,1,0,0,0,NaN,NaN
27,PostOrderArrived,E rickshaw,4557,1334,1133,2,84.93,0.18
28,PostOrderArrived,Link,968348,313513,276045,454,88.05,0.16
29,PostOrderOnTheWay,,35992,22779,18630,66,81.79,0.35
30,PostOrderOnTheWay,Auto,1813204,1177005,962566,2602,81.78,0.27
31,PostOrderOnTheWay,Auto C2C,2371,1381,1115,6,80.74,0.54
32,PostOrderOnTheWay,Auto NCR,6900,3896,3242,13,83.21,0.40
33,PostOrderOnTheWay,Auto Pet,618,360,284,2,78.89,0.70
34,PostOrderOnTheWay,Auto Pool,8425,2402,1916,3,79.77,0.16
35,PostOrderOnTheWay,AutoPremium,351,260,201,0,77.31,0.00
36,PostOrderOnTheWay,Bike Lite,498087,314459,263530,570,83.80,0.22
37,PostOrderOnTheWay,Bike Metro,79666,51503,43356,74,84.18,0.17
38,PostOrderOnTheWay,Bike Pink,3949,722,610,2,84.49,0.33
39,PostOrderOnTheWay,C2C,45494,30422,25206,61,82.85,0.24
40,PostOrderOnTheWay,CabEconomy,555333,343863,281237,1035,81.79,0.37
41,PostOrderOnTheWay,CabPremium,16229,10116,8520,41,84.22,0.48
42,PostOrderOnTheWay,E rickshaw,11558,6303,5268,19,83.58,0.36
43,PostOrderOnTheWay,Link,2046742,1333507,1118879,3309,83.90,0.30
44,PostOrderStarted,Auto,1038620,625608,538179,3840,86.02,0.71
45,PostOrderStarted,Auto C2C,1417,712,602,1,84.55,0.17
46,PostOrderStarted,Auto NCR,3252,1994,1705,16,85.51,0.94
47,PostOrderStarted,Auto Pet,316,148,132,1,89.19,0.76
48,PostOrderStarted,Auto Pool,1152,739,640,4,86.60,0.62
49,PostOrderStarted,AutoPremium,161,88,74,1,84.09,1.35
50,PostOrderStarted,Bike Lite,256688,123454,106716,877,86.44,0.82
51,PostOrderStarted,Bike Metro,52372,25283,21787,179,86.17,0.82
52,PostOrderStarted,Bike Pink,522,280,248,2,88.57,0.81
53,PostOrderStarted,C2C,35232,17802,15060,49,84.60,0.33
54,PostOrderStarted,CabEconomy,298597,184272,157768,991,85.62,0.63
55,PostOrderStarted,CabPremium,6198,3785,3514,23,92.84,0.65
56,PostOrderStarted,E rickshaw,4061,2361,2007,14,85.01,0.70
57,PostOrderStarted,Link,1097890,558718,478062,4133,85.56,0.86

In [37]:
func_get_funnel(df, ['slot', 'taxi_income_segment'], dict_agg)

,slot,taxi_income_segment,response,impression,viewable_impression,click,viewability,ctr
0,CaptainSearch,HIGH_INCOME,2640947,1843497,1458868,9113,79.14,0.62
1,CaptainSearch,LOW_INCOME,382837,233826,188580,1930,80.65,1.02
2,CaptainSearch,MEDIUM_INCOME,2250288,1431199,1150859,8636,80.41,0.75
3,CaptainSearch,UNKNOWN,707740,506305,405340,2811,80.06,0.69
4,PostOrderArrived,HIGH_INCOME,1025946,372948,318799,510,85.48,0.16
5,PostOrderArrived,LOW_INCOME,161071,45107,39626,102,87.85,0.26
6,PostOrderArrived,MEDIUM_INCOME,932040,277634,245926,439,88.58,0.18
7,PostOrderArrived,UNKNOWN,271986,107042,92117,152,86.06,0.17
8,PostOrderOnTheWay,HIGH_INCOME,2159579,1490931,1215997,3159,81.56,0.26
9,PostOrderOnTheWay,LOW_INCOME,340053,191169,161025,570,84.23,0.35
10,PostOrderOnTheWay,MEDIUM_INCOME,1942075,1152489,972580,2764,84.39,0.28
11,PostOrderOnTheWay,UNKNOWN,567516,405013,337032,1069,83.22,0.32
12,PostOrderStarted,HIGH_INCOME,1211398,703543,594801,4027,84.54,0.68
13,PostOrderStarted,LOW_INCOME,177468,86219,75322,721,87.36,0.96
14,PostOrderStarted,MEDIUM_INCOME,1035754,533807,467231,3873,87.53,0.83
15,PostOrderStarted,UNKNOWN,336474,207633,177055,1439,85.27,0.81

In [39]:
func_get_funnel(df, ['campaign', 'manufacturer'], dict_agg)

,campaign,manufacturer,response,impression,viewable_impression,click,viewability,ctr
0,1. Learn More,10or,2496,1387,1182,4,85.22,0.34
1,1. Learn More,1427bc9f038c2d38,10,5,4,0,80.00,0.00
2,1. Learn More,145002bd5330a7dc,5,3,3,0,100.00,0.00
3,1. Learn More,147a20bd36ff03ee,9,5,4,0,80.00,0.00
4,1. Learn More,1926d2d9f0cc152c,11,7,5,0,71.43,0.00
...,...,...,...,...,...,...,...,...
1122,3. Buy Now,ziox,1,1,1,0,100.00,0.00
1123,3. Buy Now,zopo,7,2,2,0,100.00,0.00
1124,3. Buy Now,zte,67,51,43,0,84.31,0.00
1125,3. Buy Now,zuk,294,207,167,0,80.68,0.00
1126,3. Buy Now,zuum,3,3,2,0,66.67,0.00

In [45]:
df_model = func_get_funnel(df, ['manufacturer','model'], dict_agg)
df_model

,manufacturer,model,response,impression,viewable_impression,click,viewability,ctr
0,10.or,e,4,2,1,0,50.00,0.00
1,1091f2d336c60ba8,ec8ed0dd4e8d2732,1,1,1,0,100.00,0.00
2,10or,10or g,4,2,1,0,50.00,0.00
3,10or,10or g2,73,42,38,0,90.48,0.00
4,10or,d2,197,117,97,1,82.91,1.03
...,...,...,...,...,...,...,...,...
6317,zuk,zuk z2131,52,36,31,0,86.11,0.00
6318,zuk,zuk z2132,1488,925,753,2,81.41,0.27
6319,zuum,akus p1,1,1,1,0,100.00,0.00
6320,zuum,akus z,3,3,2,0,66.67,0.00
6321,zyrex,zt216_2,2,2,2,0,100.00,0.00

In [47]:
df_model.sort_values(by='response', ascending=False).to_clipboard(index=False)

### Appography cat

In [16]:
category_columns = ['ai',
                'camerafilter',
                'courier',
                'dating',
                'deliveryfood',
                'deliverygrocery',
                'devotional',
                'driverapp',
                'ecommerce',
                'educational',
                'entertainment',
                'fantasysports',
                'financeinvestment',
                'financenews',
                'financetransactions',
                'gaming',
                'government',
                'health',
                'homesecurity',
                'insurance',
                'jobsearch',
                'news',
                'office',
                'ott',
                'social',
                'streamingmusic',
                'telecom',
                'tools',
                'travelbookings',
                'travelmetro',
                'travelridehailing',
                'vehicle']

In [ ]:
agg_rules = {
    'response_id': ('response', 'nunique'),
    'impression_id': ('impression', 'nunique'),
    'viewable_impression_id': ('viewable_impression', 'nunique'),
    'click_id': ('click', 'nunique'),
}


results = []


for col in category_columns:
    print(col)
    filtered_df = df[df[col] == 1]
    
    agg_result = filtered_df.agg({key: func for key, (_, func) in agg_rules.items()})
    
    result_row = {'Step': col}
    result_row.update({name: agg_result[key] for key, (name, _) in agg_rules.items()})
    results.append(result_row)

funnel_df = pd.DataFrame(results)

ai
camerafilter
courier
dating
deliveryfood
deliverygrocery
devotional
driverapp
ecommerce
educational
entertainment
fantasysports
financeinvestment
financenews
financetransactions
gaming
government
health
homesecurity
insurance
jobsearch
news
office
ott
social
streamingmusic
telecom
tools
travelbookings
travelmetro
travelridehailing
vehicle

In [22]:
funnel_df

               category  response  impression  viewable_impression  click
0                    ai   2643566     1631592              1337224   5916
1          camerafilter   2431244     1470682              1205074   5392
2               courier   2327289     1396575              1140966   5098
3                dating    675010      405149               328079   1310
4          deliveryfood  11112508     6704607              5500246  25986
5       deliverygrocery   8279602     5032892              4113194  19085
6            devotional    479932      299653               246659   1105
7             driverapp   1444949      844729               697205   4143
8             ecommerce  14617850     8745968              7195207  37612
9           educational   3276513     2001337              1641222   7244
10        entertainment   4147085     2548442              2083463   8729
11        fantasysports   2303219     1378923              1134755   6002
12    financeinvestment   7831382     4757538              3909047  18616
13          financenews    650205      401397               328042   1431
14  financetransactions  15889698     9451193              7781100  41284
15               gaming   6664201     4008656              3300963  17285
16           government   3444956     2112368              1734952   8028
17               health   1797103     1127956               915817   4093
18         homesecurity   3219947     1991852              1612972   6864
19            insurance    741433      456076               373272   1845
20            jobsearch   3103736     1874842              1539163   6251
21                 news   6479522     3828292              3149367  16171
22               office   8900254     5391337              4419760  20402
23                  ott  13456284     8085533              6652014  34146
24               social  16414642     9750617              8027625  42953
25       streamingmusic  13783427     8283118              6813298  35071
26              telecom       566         363                  303      1
27                tools  16433227     9761489              8036470  43002
28       travelbookings  10247167     6161346              5067741  25516
29          travelmetro   1167139      712468               584622   2377
30    travelridehailing  11517505     6933208              5689235  28020
31              vehicle   1475731      910130               748171   3497

In [23]:
def func_get_funnel_category(temp_df):

    # temp_df['render rate'] = (temp_df['impression']*100.00/temp_df['response']).round(2)
    temp_df['viewability'] = (temp_df['viewable_impression']*100.00/temp_df['impression']).round(2)
    temp_df['ctr'] = (temp_df['click']*100.00/temp_df['viewable_impression']).round(2)
    
    return temp_df

In [24]:
df_view = func_get_funnel_category(funnel_df)

In [26]:
df_view.sort_values(by = 'ctr', ascending=False)

,category,response,impression,viewable_impression,click,viewability,ctr
7,driverapp,1444949,844729,697205,4143,82.54,0.59
24,social,16414642,9750617,8027625,42953,82.33,0.54
27,tools,16433227,9761489,8036470,43002,82.33,0.54
14,financetransactions,15889698,9451193,7781100,41284,82.33,0.53
11,fantasysports,2303219,1378923,1134755,6002,82.29,0.53
8,ecommerce,14617850,8745968,7195207,37612,82.27,0.52
15,gaming,6664201,4008656,3300963,17285,82.35,0.52
23,ott,13456284,8085533,6652014,34146,82.27,0.51
21,news,6479522,3828292,3149367,16171,82.27,0.51
25,streamingmusic,13783427,8283118,6813298,35071,82.26,0.51
28,travelbookings,10247167,6161346,5067741,25516,82.25,0.50
19,insurance,741433,456076,373272,1845,81.84,0.49
30,travelridehailing,11517505,6933208,5689235,28020,82.06,0.49
12,financeinvestment,7831382,4757538,3909047,18616,82.17,0.48
4,deliveryfood,11112508,6704607,5500246,25986,82.04,0.47
31,vehicle,1475731,910130,748171,3497,82.20,0.47
22,office,8900254,5391337,4419760,20402,81.98,0.46
16,government,3444956,2112368,1734952,8028,82.13,0.46
5,deliverygrocery,8279602,5032892,4113194,19085,81.73,0.46
17,health,1797103,1127956,915817,4093,81.19,0.45
1,camerafilter,2431244,1470682,1205074,5392,81.94,0.45
6,devotional,479932,299653,246659,1105,82.31,0.45
2,courier,2327289,1396575,1140966,5098,81.70,0.45
13,financenews,650205,401397,328042,1431,81.73,0.44
9,educational,3276513,2001337,1641222,7244,82.01,0.44
0,ai,2643566,1631592,1337224,5916,81.96,0.44
18,homesecurity,3219947,1991852,1612972,6864,80.98,0.43
10,entertainment,4147085,2548442,2083463,8729,81.75,0.42
20,jobsearch,3103736,1874842,1539163,6251,82.10,0.41
29,travelmetro,1167139,712468,584622,2377,82.06,0.41
3,dating,675010,405149,328079,1310,80.98,0.40
26,telecom,566,363,303,1,83.47,0.33