## Imports

In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import datetime as datetime

from scipy import stats
from pyhive import presto
from datetime import datetime, timedelta

import warnings
warnings.filterwarnings('ignore')

In [2]:
pd.set_option('display.max_columns', 50)
pd.set_option('display.max_rows', 300)

In [3]:
## Connection
connection = presto.connect(
        host='presto-gateway.serving.data.production.internal',
        port=80,
        protocol='http',
        catalog='hive',
        username='manoj.ravirajan@rapido.bike'
)

## Datasets & Parameter

In [26]:
## Parameter 
date = '2025-04-23'

In [5]:
df_user_id = pd.read_clipboard()

In [27]:
df_user_id

                        userid
0     6065ce7ab268465285da51a8
1     6497d0bede3d5005a673e2a2
2     5d67e947d0286d106d6b8b62
3     67f5463bd8f16bfd7b031738
4     61ea6c40dd30a4601aa3d57d
...                        ...
5915  634c06c88cfdc930c60f60fb
5916  660809e9c0a712bb13744899
5917  6276a45b3a25c632ca91fa84
5918  638dee1f70e06564146c7311
5919  67aecdb97f8707108531ba85

[5920 rows x 1 columns]

In [28]:
user_list = df_user_id['userid'].tolist()
user_list_str = ",".join(f"'{user}'" for user in user_list) 
user_list_str

"'6065ce7ab268465285da51a8','6497d0bede3d5005a673e2a2','5d67e947d0286d106d6b8b62','67f5463bd8f16bfd7b031738','61ea6c40dd30a4601aa3d57d','62748b93b3bf0b54f2ba7385','645219848fac8a3d37c73408','634c1cdeda7f6869e84400c9','64d3a4333239a670f410752d','64c39438c30c5db9c1c88521','65bdb8f4c00e51505f82655e','636b77985842fd9dcd358101','67a487fb6b1ab98880fb705f','66bcc94b62e4ae8a9d95cf9f','5bef9fa3a10830571584ff54','64ad85e855032dc46a0dd200','67f00730ed1e8533f437363c','5da3f024a1f0a71c6068160c','67f34f877c1f22bf4f120dc0','62e948a9481e30916f6a2daa','6618dbdd1b19d0e256208739','5f9019ec685417195b74c661','61fec2ccd2ae4034a4969c75','60fd797bfe2f60218e87b394','67a978cd61be69072028dd4f','67079f224c37f80b92c300bd','6305b31874c82d39db0c1dd5','65911177d8a16ec69cbe4447','67f4fa95d25c76db414e1b13','6528ef2c0f89fee4fec9293b','67efa27139e9b33d8b2a5233','65dc12b6378e44f86948a6c3','67fa20884095574828102c2a','5fb157b190d779052abaa125','628cc155024f97286748b2f1','6800a5fd175faaecd25974af','6800c35776b63014d4ea07e9','65976fe45fb37fdb5cf58748','6417d1c622a14a158cdc7623','658ba499ae7d734a3ca3315b','67d660b27c212f660f8d7be1','5c684864f2edc733675c681d','66711d38ebd9071b57dd98d5','62ac8599523c18914fb44de8','668633d02fc5ffecabd4db60','67db9a58aed6495a8652afad','64521018116908978cbc123f','62c9813e551cdbeef6c0b71e','678373a7b86dec339ad419b4','675960ef646c803658447b71','627df9da3645c9ede291c54a','66dfe8915ad6b0afd7eefaae','620a81c357d2b2194aaf93f3','617cf9db80efdebb3ecbf86d','62c99ab6d46b677fbfa0b04f','5df51b1c732f142b594c1800','624dadcb1dfaa67e764b1e3a','651cd54f3ded45b08cc94716','66e44e0b963e6eb7fa3e9c24','679232694cb5f1800815b708','67fe13ba76b630038f135638','65f598d599627882e7321ff5','672f3c101bb3df6766743075','5da3faae941a7d1c51e49a71','62cecdbe551cdb6b54c47f82','60b76767270b9c7e1fdef25f','62776ddb0145ece2cc6bdf26','6436525a11bb7311c578a46d','62fb9e6f04cb1b0f2b0841b1','6056e590db7f1af3c22875fa','5e64be7fc9d6000805737f15','5d1ddae893686945e7122ee8','5da81fdfa1f0a71c606deec1','67e8fd9f3cccd3fbaa7c4725','633a98355212404bf4ef871c','647d449932948441433a7965','6800e647ffe62349eb4cca6f','637746e7b48cdd19d5fe4568','67a82b674b4bdc41e9c25645','5cc691a959e9ac1cec4f416d','5e4dd7141e97ff222aa7cc70','5db8239af53c5821426a5d76','65c759452c4677b281421d66','66bdb5b90eec1988e3c536df','5fdbb629bb140af5beb04427','62b7d30d4d15614abcbd9942','67f079653de6fb20cfec223c','67029ff592794407dab3ffe4','6753d6e6cc20d805e0d3084d','67433305b769b67250f51ab7','65c0687ad35f1a9b3cdeab2c','5d1f412f93686945e713fd78','5d2fe83f6ed7674e61173eb9','667e4401484253c4da6759e0','64cd23f4706c4b5fb590f008','6659ab903ccaa0328e3ae928','67c2bdd49eefcdf46d428c0f','642ae0ce56fe892f19c6005a','630b3ad7d2fba1441a2f02e6','676acd583f06d24c7c408529','67487654ba5ab6bcc6019c2c','5e03fd838669fa330a3c8f3b','67eb65734c7bf003879f99af','62a66f087d79670884e6dd7e','63ba76065f3d2e88d8b7aa7d','65561d12781f5cdf7a7d2169','65190b0172b35ff059a11ee0','678fad1f0705048de3507d09','6730334a3146e9a2750b3dc1','67fe8a18556aa00de249cc73','655cc1f53d863d35acbc594d','5d452316f3dbe16ba31cc86f','64f156ca38b71c23fc9682b2','67f7d348f624df51c02a8660','5c8296448c352421eae02769','5cca70e39c056e14a95b8370','62c8f96e9adb4e9c383032b4','62d0211c0945b6a70b96ef73','62257b263303c4796b95e936','6061d28d8ac5b1640f6578c9','6587eedb21a6369ef8236d76','67a42ceae70d3820f76b7b47','67f90726984f60487e297527','63a2f7d60910797e02582a2a','63104ce4953a69bc3b04cfb3','6383770339691bb7715b7039','5d2b5ee416609737fa4d4534','64b3fd418191080eaea8a5da','63f7a436f22ead895d8403e5','5c607a0af2edc7336754a40d','6596835a11a25b7ac486222f','67fd5fa5edbb78315fa63787','5ff6d2cad6b56d8bf38bbb3a','67ff942caee2b9e91b42f472','679b6e727d426b2045a29c63','5e5e1d619f365e504e706d33','6630441d6af91213b3131b4b','5c769889118ffc4ce4a9d9bc','5c9c61f78c352421eaff95ee','65c368b4027eac68c4528e95','6604f22b232c7b0e306f43b3','672320a50093752e1ada4ce6','63356835e90ec69fdd7a1673','6399be69f83df30e033ac788','67ff46c8df25cb27b2f09818','612f52f09db16ba27dee52bf','5db9b78c34054849200e93f6','6800869176b63075e5d575a2','660056bcd387a7dae47b967f','663f1bff641acf5db2051369','680078d969dc62154ed98bf7','64ecaa5c20a89f5a4fdad4d7','64e8b18d87b2305b1cdad085','6529598451cc8f3c8ebcfe38','620fe382d96a7a142dc44062','627a8dd34bf383ebca864f36','6457c32718815f656023a9f6','617d981b16ec526271d0b689','6800b931edbb783917ad2b8c','62296efeb46ca70eea997966','6799c0903928cf3c26d77f09','644293c5c79eb7132b6763cb','5d76575dd0286d106d8207ba','63c1582cf8a6e745af6934e8','6533f900b5145a4ba103a2e9','655a67ae5806533d753cf5cc','62a923637d79672344e8f0e9','67f4ac2a4953877df29d8b7c','63e9f7f1f7335cc1e877b32e','5d0e45bf5a41ab44a452fd04','67f8c0b512a9bc66fff2bb44','6415a17720601d478b3050f4','680094424ba94643f35c7c3e','5e15a88b013a515f248e0e39','67b830ce1dee5c3c7e0a6710','6304d2cdbec91f3c67ae12b5','67bb44a1925e764aa54fb523','67b1f0fd0c81f014f7194d1e','65cef3f82093ecb5fa3b3449','66da70269dc9f3732e5edf14','5b8f3d73d0e8d468374a8f75','5d7e6df4a24c96105e503e82','6760e1c3eac5bc46f3faea01','5d4318c2f3dbe16ba31a5531','68008818175faa027c4f6d7e','651669b52d06f324133203e7','6114cd3af3519d7bab40cbcf','6425852d07b00cd591e6a4b4','6800da18175faa9d686b906e','5d045f2b8819fb622ea1fc8d','6266c37c4e17b215e22f0605','649def1186f688034af5e514','655eb2330b830bd66300f4b8','626ed2787975627a6646b010','67feb5d33de6fb602495a1f7','5ca9cfa854bc7263ff2c06ab','6281e3435877653f77d09010','5b366b5846b23454b052258c','67f4ddbe9a5e2e205112362d','5c8915ed8c352421eae8638e','64e4944fb7550658ee0b010b','66c20a665e05c764596b06d8','61b4662e17dd6a6b1b10dab6','64a2b2e91934272ee1cc5913','621d85b3c1a4e475c560883c','6585319a47eef944644d0d4f','64e5a9c26e299fe0b6954165','6253b5f3469321ac8c178c5b','63709fc63a80374e50a9ab0c','62f340907410039a296bda53','5ab71d4ff045c1180fcb70f3','63fdb53cf22ead5f7f88589d','64566cda0b5c27fbf40d9bc4','61ee1b73ebef82b7d723e4cc','67caf02d5e07554c34aeb6f6','63d90d1d9c95c9b3ceb42074','624c0290317867cbc167ba75','6800ed1055a555211ad3c77f','678a3d9207125c4904ac6982','5e3d18931958930743077e15','6759712fbe59e3c9a797e399','672597cf6c5fc91404be04f9','5c61aec5f2edc7336755d5ab','6337e7d2abf2103eaa2a81de','644716adb4c61974167cebf3','62850bfd57862811afaa33ff','6301f1bbea5b5606f2b16db3','62f61ec96ba1456983e252aa','5cf8c863c0b26018f5dace64','5dc7a6e3907d93538e3fb0a9','623597378689db6ab78004e2','61609e9c77c7e66f31946ceb','66a70e1562966b79826f31ef','66a248f0d0f97d473b93f7d0','5e2c57f7c1d6058c7e7c6615','6782389209c88cf0e5b53027','653f6a1a22f0270dde9c2deb','65393dfad32f3b9d561d0d37','62e34ae2e10ad84f0bf769fb','639dae2fd7250c2259b3cd19','616508cad323b778608dc990','666a62288c8f8f186ea9321d','60369982f5d36b359ff78412','64a6377e7c100a5459c2dcf6','6788df2e1146e14111123f72','67dbe47a153c18db7ac08229','67f9022d12a9bc52190ab86a','5d4d80ed8e4dea74f23412e8','6427f4a1d47342f43636f241','663778b428c2842f415c7fd5','659bb33bbf02ad7b759cda8c','60371878f7d42e0a705b3162','676a8c3b8879cec6c823b5f9','64b2a6ccd7d8b4297b245478','6753bca6d1d5b1a3792d025a','5f76a29c7d99a7d8b6594069','65f3f45d0f9aeb56ecc180b1','6695f852e1288aed33022bb8','67667361cea6bef01f440c20','6212671d19276584dd57314f','6421bf5013361546ac9a14e8','67f3da19edbb78646e904bda','67c856f176d8f2faff372d12','66669061b0a14558a992482b','62c449662e60b088a3c6484b','63a85116be8a4bc36ce4c16a','679b8afecc6b70405cc902b5','65abf21458623c08dbb81345','64d72b8af57534f26c6228bc','66e2e3ff7cd0aac5d51c0c53','67f086fd3de6fb21a5f0bd2a','6303799304cb1b22a80da1b4','678a7b5db42e37627ff1a07c','65f021441bb93c31838a084b','61f5d04a6916b8b250aea69e','626e9b32e98a6429e19b6066','623dc3bfa198e1261c86c752','6184128616ec52e89dd4e298','63a81bd322a9925f14f13e00','5d5f7a26d0286d106d5ef10e','60a9b809c41d7441616eaac7','66ed74d65e1235801b90a3d4','628f2b02ef1d77e4b98f3ad1','645b4e338e5481220dd62e99','665a912c3258411ddd1c1db6','66bc75c78489e1e761d993e5','6780e8fa96025a5b562baf3c','672c5c6a9b2ab53789fc05c4','61337c188709d299da93c949','61a8d06617dd6aef8907fe59','63c54aa562e65c31dcc17bf0','63ba753adefaeda4c6efe013','6238464d6b6b642eaa72dd83','66abbcb9d12aac46fc3ef66b','5fc0f6aa89aaf22280020243','62e5285ca4cb44846c575afa','61ab995bf3de6f86e0429ae6','611b97d7feae77592d4514a6','6696685a84c4baacbdba684f','668966d7b0bfb9b5c93291ba','658668056b2e1995b6d47aa1','5d03c5888819fb622ea1a36e','5e240de06d833e02b9b64fae','680067d576b630b3cdca7dcc','6469c91297dc74b47b7107b5','648071e4821840d8509a5d35','6244e7ad5fd022073d68e111','610e05d04fd4bc6e61371555','66021bdfa9381bdbb90e3102','61835f3557f1440919b3d217','5e1c65ba3db8bb38d4ecd68d','62f7c7390b0d37448206897f','624459b66ec6e81501a84a56','6052dc04e027ecd554d141e4','5e205c379a0d23428ae47e05','62daba3f4171858ad7d426a5','5c02f76337ae362855a08cd3','62446575fbfa43bb4fc8962d','65c91a1b046a44249a9e8cc7','63bbf67cdc574582516e49f1','647828f0a5f7ee7f1a19e8db','61c8654e5379c00c3e4f7cff','6738e356099db54553076e43','5ff96873857d1b7e0827b18e','67a74200377ef5592cc1d7b0','636bca4b692d57dbb532cafe','65758bf73a49bb5df2974f00','62997fd8ac4545486e5f6636','5b767edba61e552665d2a2ba','61b3946c17dd6a1f1c105580','63e6336ea6c2a03207636f6a','641efeb9480d2da421991088','615b060677c7e628ba9128b8','62677587aa67dbd2951cc673','5d6ba809a24c96105e325323','63288c9bbb9d620445222027','67e15d336f7ffc81c068b9fc','614c13fae8f2231119ad3fc7','6800f89355a55525f3d78673','6619fb851adf1801a995505b','67fba4cb4574da4182a6b27e','614440a3de864c7652ff64f8','647899c2cc3c73516da9cc83','629efaca1b57e4bef8e9d7e3','5bb47ec57e7bc30a3837e543','6360e21065e89927145772ba','67f4ae5d548de91b8e896f78','634a58f3871c9aae4534f1a8','60f5634ad417d4c1ae7b769d','62553bf67ee6415209534121','6800e4d365f4156575f073c9','618c88c9c98cb31d8efb11d8','67ee55c40c337fe3e6c9f2cd','648a1cdc19c42e5c4dfa6859','680063df3de6fbdfbe11b5c6','62a17297ea951fdf5b4ddb3a','6264e67ae98a647fce954169','6317fb6a304c30dce0a9c15f','646c28119d063b88aa1c7905','5dd8b3c661ebec69bf977415','611ab28434b93d50ac2a9af6','62d4d795487992499a9321cf','654078587de97976d23d3d22','67f0d376e2dffc2cb37eee2c','6468e88b67f5830b68ee44cb','62a1d485e9b1783517b10e37','61e6c2cf533cf600b9300376','5c30bca14a267149c766ad9e','62975d351b57e41960e3c2cd','6800b930edbb786915ad2ae4','6800cfec3de6fb2d8d370a87','641d226e7678501845117304','5ce3679825ee3218d4d403a3','6193bd54ae4f737ac51b7a81','61c02573b125757b5a627363','5d4fe140bde10e0d5438630a','63451a4bee373c8625a46c25','67306eee453ffd04fe4a5be8','6786861fc80afa602d11b085','61bed773d97aca37e26ffa5f','640c640ed7506f918999d489','6204fae493d3533bd3ad86c6','5ccffc25538544065b3064fc','664458d454569f501f70c4d6','5eecd9cd384e5bc2d807066b','67f5f6f3371ee76e4b8ed866','6482103ea1908f73240b4dae','6367d1e3d58af770f5e3fcc4','6800f9e4edbb780c50c3bd38','5d49863bbde10e0d542fc31b','61c87eeb5379c048b34f97b6','5d589e0055fbf50d45facfbe','628cbb3b4133eb2977b24efc','674c552f1cda871b0dfb2983','647747a204ca446c6d984b77','5bba1c137e7bc30a38395510','66110c45b360994c2050c717','60d8902809aa99483a3a3b2c','61855f7457f144f231b58ab0','6800bb3e65f4155dace18e0a','61a88c4cf3de6f514b404769','5d650e4ea24c96105e2834d5','62970c84a6b6c180121b661c','652fa5fe14291b749646a5af','67207b98a0d6a157212139ed','63d5e3b0b5f442797d0cb164','67caead14b32de5d6f01f168','67f751aa4b621ac663ccd2d7','66dd8052f3f92770c294c0de','630b2ff4d2fba168e72efb08','679a1293cc6b70c05d879fe9','5d6f3323a24c96105e373a8b','65af2e3c414b1948bddbaa03','67538cd04bfc8f0c993390e0','6276b015307108a760dd658e','66cff2106451d3e90af56c91','6297642da81bc587a05a29ae','5f82f1d44dcf6e6db66446bb','67fe05d181679b0daf5b57ee','64504c83b4c619d16a83983b','6718a9a281ff2846363c2e1b','615c432177c7e6672591e3a8','638809ddf5188124ede03f3c','5c074ec85dd7396826204d02','612f9b409db16b6852ee8e78','68006a6e4ba9465cf84df003','665415c825544338e11f0009','6459eb79076303a8aeed1590','644268c68fac8ad7e8bbcb92','58f36a377841f858079d1176','5a471f0fc0fac01a33739eda','60b615fb270b9c2476de81fd','5d6fb54ca24c96105e385cef','6571a8a4f707ba8037cbea47','67f22b82bf723761dea0f0d5','62e144f0f114326fcc2389a1','5c3ffb684a267149c771d33f','6319f753cc53aa2c46fc3a37','653c70081eff51189f0e851c','6535f8cdf367442252565286','6309e3002aa8e8b13f205585','62618ee279756299643e55e5','67f7806d5c1c89f22452846f','64a99bebf1bf681533cb829f','6322e0d3f4bbd71f907999cc','672e1221bcd6dbb90bf2fc60','654de1fcb813b8d87a66aab0','67487044572ad21620e4b413','676a1b7f3a5d77030fb2dfac','653f612bc0d7139580910425','6503dbd299739d3fe54ce2a9','63f8eee4f22ead4eb984e4ab','6488333c6c8b963f1fb5158b','67313569453ffdab746ab34b','6800e793ffe623c3354d4209','67ff85ff3de6fb1c3ad334d7','5cc6c74d8d953538ab08947f','6336bf0ac5293b4de2615eb2','67dac415810ce72d4c5002cb','617be0c2ac7833d30b7895c0','67dac56e469b25dfc554f453','5f506dab817247ab9d9f2298','5e591719cf3bb6bc05e77170','6401cd9cb29bb552894b19c1','672210dd7643185b67fe6bf6','62d418ffdded03652dd7c19b','679235189dc91045a6676ad6','66a8429ad12aac3645ae23e5','64a93db48d231a79a92b8d97','67f65aa8fdf75a8cc93de769','5d864af1486b0b2147730851','63e7160c50f5bac525a1a9d6','617e0c0016ec52cb68d0db53','66b78e2ac9c97d765360fb74','5ccbd0cd803e586ac98d5c41','67b72b812a9fdb6f2e3dbac0','6163cda01368b5c827541b00','66235f4263ea43e0434c6503','6789ebca6d4d173d602baf99','62987a25ab4bf12ccc1b3a54','5ca5879a54bc7263ff260776','67f64e2aaaad83838a4856e9','60bb06e129a6947276b67717','61c8420dd8274047301fa020','67c45a391642f9fed47b430f','679f9977a663363bc9ec0670','6050b2b75e55c3e224cec9ff','6625d5239826f5372588ccd7','66646dd25b87d57496371a8b','5cf659ceca6e292111725127','6436db6f11bb7301ef79163e','61c67c7ed827402d871e0fc1','6678f4552150987b0b8caa1e','665358159712052e095a59ee','6800b67165f4157f73dfec32','60e7d4423dcf532bbda24529','673b850e07778868b175759f','67319a5d306b0e857877ef65','620cae6ebff4623eb504669b','6321f985f7110660b8b11c2c','623a595eb9a21edf07cb9560','6415e697cb8285408e24906c','6695f6cb5d498038f3384fe1','674b596e4616f5a042052ef7','5e25409b48bf6e0289868787','5d43dd348dbbed6b85475a8c','60254f55e32da9867eb15f4e','63071ad9ec87815528ae553d','679b9e98d9ca63de0fe75709','60bef9190e9c81ae1e29f472','6711298882689d15161d41ee','665c1a5aaeb8e47cc36c1df9','67c025d80bddf80c5b0e65bc','61654214d323b7a0628df693','659a9833c6d9a456a86ea3c7','668d2b0b7c4cd0db8cb7ebab','66611dbac26e625cfa6308db','64a6b2068b7d496c288adfb5','63f89d61f22eadd41784a799','67a83fe5fe267ebef4bc003f','66c0a60ef6eca8667dc6152c','61efb22d75b439b85d14846b','5faa9a9bb58b2402ac9d4997','66ece0fc602b906b8da9d062','61bb14b3f3de6ff3dd4e46a3','5c517c784a267149c77f9b2f','637a6a797014a584a7a0b973','627ce473dc46f3a8371c21b8','67065c003b7d239e93d232c8','6656112cd1fe78ae735c4f86','6776b5db8e4dc9f631b0776a','679b5b6ec7054c6825ecf884','5db83aa9f53c5821426a9e45','67ff61a3cb63581203a27bd4','624a754a3b51a56e31ea855b','647d9a0d07e797e924287332','68000c1f76b6304cb1b697ac','5ddf6081a5cb3035eee6adb3','64bf4c58388c215969ffa8c3','62bfd756dfa8205f1b7afd09','63d0f9b32c0b80fc283e1111','62dd73e9d8a2498589ab198b','61581cfe77c7e65b358f36a1','624d5b18ef4170891618ec62','639b1b30291a62bf64d922c2','670c7c2bc9b968946faada97','5ca2e8fd54bc7263ff2291ba','659dfd8a5bbd421f34cb5327','63ae965ee5120e89bb64da5f','668e888f1e00bb5da076192b','66db3e80f75502f8d5098f50','677a1fdba1789e5397587aa7','63ce5692f8873d3e00207bc1','5e36e90e72bb5c194dc26bd5','65e99bab53d95e46b571794c','674351ae3a7d6b4526f12323','6657492b78d1b24e582ecd92','641a7657e9d45aa75d8016a1','6195d24679d51272c754bd88','64a01dd466353da48ce50f87','63879275d87ef61792561a08','678f700cf8fb0727bc895b1f','67e93ebc6e1888665a7989d1','62343b8cb465c03109fe4d61','65911ca6a00f854f839ce64c','673f17b407b2b4e7e2f35b7b','61d706b3d94671065c55d17b','6224a6bed85cb7765678b3c6','6533e8c9cba8b168fc9208ec','5fc3a111014147b6810c1a3d','580d97a4e51a9c0e5d4fc6c6','6800ff5455a5553eddd99ba7','67c2c965913958ec47abe413','5c2d51cc4a267149c763da67','62993b621b57e42abde52426','638cb791941874c5cab3ec1b','638b022fd116256db624f774','5d52329c55fbf50d45f1d62f','64d9ac964874c05871fc06cb','62428034c18d82df091918fa','632a73dfe21bd9fe9ccd91ca','6792dc40f4ccba7ff2aedf43','67fdc1153d24f1ef0a1623a5','603877b74b0307d7d295c04e','62d52f3f0fcf30e3d79ae2ab','629ae3881b57e45705e67590','64929e90a17bb468b7f2ba91','67fe66c73de6fb200d7afe21','61e0ef0150f34b35808a91f9','6229bb39abd7a67dfe7cab4a','5e4e03bf7931cbc73ed54f31','5fd45f345e98cd58602f3b11','62de9ff1c389d9fece90d86c','6796334f57a7c42d377bc62c','612144e534b93ddb7c2e35d9','67b5ef8b4ea0e10d7e69bca7','67beb8a5e76cdbd0bbde4c17','677696bb5ef74d2d2593047f','57e3af5dc34a007c6193ffcc','57ca707aa06bb51f26506396','66a0722b511acac53ab695ec','6687aa9e659b59715819edad','662b1a13a769c38660b79b81','67c14ea0d0d1efcd4ee8c65f','66a9b3eeda3bf889c26b6001','66193629b60fdd7efbf11ca5','66c19bb4ec15cdadb251b963','6780fee0cd3f1b59b98e55a3','5c45e4864a267149c776b89d','66783307349851df69650fd8','68007c4c9fbafc22e501e7ba','6211d5adc00a73967fd17372','65e573fb777f4af0a6be7346','623b06c96e78d1142ff61042','67fe20772251da2c7ab4cf48','5df20e29732f142b59486f69','5ce7a6b125ee3218d4dc55ed','5cc7ece6c2b5730531920dd6','6496f38a6fd0b87980bbc10f','61caab6ebed6061c4c48bdc5','5b9b6af2feb84075c8d7c590','62f1cac19b353b1e0ddfad67','5c7613e1edf60f420c8e42df','658e53dabdcbb6e393c565f8','63e63f36d57d1c67ad010e4a','661431b2a2cf392667bb48be','67fe66673de6fb16157adc07','5d6fd753d0286d106d779e1c','62ddae1ecb61571165595837','6703807c78238382de2fb585','6642ddf29ce05683986f8672','673593e2bee1e46499e70b95','637347c2812105600c6a09a0','66611f91fb9908662f31e716','6630abc5b647b92e1f5e9efe','61d18e30a757463dc7e5c05a','636db1729ee45f5e4bc33f5d','67260c3641f91b631649ca95','656937735462623c89b5cab2','67ebbac7b7d3639a96097089','5c6658c9f2edc733675a167c','621383e149ef1a0fee0726e6','67599a70d6083d05f425ded5','61e45f4350f34bc8768d205b','676f99138cda0ce945093ec9','5f2b7fb66987fcbcf7892459','65a2153a65b0304ce283c814','6322c2e30f4eef05052e0c91','678e4a4bb0b7c54e48db7f01','5de1f7a1a77cc82ebe33ffc6','642d853f0470b785e3bd71ad','63d6227d63e6d4287896c22a','67cccc12fad5f207dc5cad00','63c6306d50d4d5a04b25e466','65b9de67b4b6e289479d4836','61288949be50ec4f0082ab9d','6501ce350ccb6570dd8a9613','628b826ca0c1d7f761df5586','624b5ae0a060e8af2ef2635d','5daff70181741b1c0511cb33','67bd9aaf925e7630ee0d5e46','66e9298616980859ed73d381','650d6dbc41bbcc3472f71e64','6757b5af47c62e0c245960f4','67f00fc539e9b3ea4c522081','5e65fb145b8dd323432cdd72','6668af1f3ee5f1238c6bab0a','66a64c7184aab3adfa97420f','617b77e1ac783351dd784027','5dd4f83f59e2e3257f79033f','61f63050d0c48fb6554b6e44','5d454232f3dbe16ba31d0641','596f2734f163636b3adc2591','5ca5f33954bc7263ff26f33b','662f9c6efeb895bca4ce0462','62c11e09d9dd89947b711a35','622478df8d17aef44ee144e9','5fc22c1d808c7a1ab0157fee','6709127fa0f29f30770a056a','67e675f62ff0b07d54ecdd8e','66d3deb1bedd5c360a876c24','64d50c19da3d2bdf3d8e57be','5a5254796ef24d6949ffaee0','6476924bea6166c5ebc4c5d6','5e13ffc689355c2289aca122','66e592154f8a1eb0e93c10c3','66acd750c18fd47650e86a9e','68010ccc4ba9464f4685821d','5c80a2c48c352421eadd5222','64e431bb61b00b62dd6df54f','66b443d6672c4031c630c028','625cead195921b044d1a79ec','65dd5ab9fc33e16621c4e223','5c761de4edf60f420c8e547d','649a901ea847d7cc76ae4fc7','625bc3b691957f07a0956937','671d020550f85d1eecf0f9c6','63398a7e0db9dc64d334dc2a','66cc6ae24854fe9a3e348312','67d429d3a6232cb5be5e3588','643e6c7e9efeb97de2c16cc3','65cc4a394359883fb0b77f5b','67ea85a7ba0d0c03137d3c5b','6195e960ae4f73777a1cfec0','673a29e5e3c30331bd20da6c','5e29f7710a873443c3f68626','603c635935f8d40aadd61e07','5c4206a34a267149c773abec','5d791af0a24c96105e47a7cc','64b787f8b63445801c4a1c0a','62ceeb8ee9e2515b1cf3d4e2','67f93e7eedbb781985428c9c','63f81e5d0bf080152f322a5a','6734ce651bb3dfe874665bcb','5c42a5a64a267149c773ebec','666d3e08abaca1165ddfb075','6801108a4ba946557f86b3ea','62276afff0b26b3b696497df','6800ec3965f415edd1f2e9b9','628b6104a0c1d7f184df3588','62e9f0cfd5c1cb1b8a95e46e','65f1302b7a8a772c0e94b7be','5cbdef8754bc7263ff4805ed','64266f8b7f1a07fedfcfd012','67f345f39dc0a8c600ed1ef2','6374d5e31295010b94f4c68a','645e149035ab9a4dcfa95c92','631b749c827617d2cdbbaa94','62bf021ca706daae3e204eb5','679e0b238e3fe2d0a5cb2448','63c113f2fdb7d867e8647e21','67fca1e176b6306a50994c07','5c4aedf84a267149c77ad6e0','65e317863e53f71b6899af67','612a157589020944885af28e','66457aa8092a0251f194aa23','63de9c0b99ac64944e692467','62a33ea0f3574adfca4d13c7','61880c77b281d77ed2c8d9a2','61d971f7b8360e3e4a6cb48f','675ae52560189bd048

In [29]:
## base

base_query = f"""

select
    customer_id,
    taxi_regularity_segment
from 
    datasets.iallocator_customer_segments
where 
    run_date = '{date}'
    and customer_id in ({user_list_str})

"""

df_base_query = pd.read_sql(base_query, connection)
df_base_query

                   customer_id taxi_regularity_segment
0     653e15571eff51a13d54158a                  WEEKLY
1     5d5a9bf8bde10e0d5447b06a               BI_WEEKLY
2     6571285099e7a1e489745174                 UNKNOWN
3     65e950e0843d7c36e3c6d472               BI_WEEKLY
4     63679f633738df647572e95a                 MONTHLY
...                        ...                     ...
5849  6239da426b6b644b7773c1be                  WEEKLY
5850  62d15acc4cf6aa81aefc4a10               BI_WEEKLY
5851  60b615fb270b9c2476de81fd               BI_WEEKLY
5852  5c90644a8c352421eaf15e74                 MONTHLY
5853  5d8f70a2a1f0a71c604d6f72               RARE_NEED

[5854 rows x 2 columns]

In [30]:
df_base_query.to_clipboard(index=False)