## Imports

In [1]:
import os
import time
import glob
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import datetime as datetime

from scipy import stats
from pyhive import presto
from datetime import datetime, timedelta

import warnings
warnings.filterwarnings('ignore')

In [2]:
pd.set_option('display.max_columns', 50)
pd.set_option('display.max_rows', 300)

In [3]:
## Connection
connection = presto.connect(
        host= 'processing-2.processing.data.production.internal',
    # 'presto-gateway.serving.data.production.internal',
        port=80,
        protocol='http',
        catalog='hive',
        username='manoj.ravirajan@rapido.bike'
)

## Datasets & Parameter

In [5]:
segment_query = f"""
    
    with base_segment as (
    
        select 
            customer_id,
            segment,
            category appCategory,
            use_case useCase
        from 
            hive.experiments_internal.customer_segment_appcategory_usecase_amj2025
        ),
    
    
        funnel as (
        
        select
            date_format(date_trunc('week', date_parse(yyyymmdd, '%Y%m%d')), '%Y%m%d') week_start_date,
            customer_id,
            order_id,
            modified_order_status,
            customer_set_pickup_ride_started_distance_meters,
            amount_breakup_bid_delta_total,
            bid_type,
            drop_location_hex_8
            
        from 
            orders.order_logs_fact
        where 
            yyyymmdd >= '20250217'  
            and yyyymmdd <= '20250316'
            and city_name = 'Bangalore'
            and service_obj_service_name in ('Auto','Auto Lite','Auto Pool','AutoPremium','CityAuto','Link','Bike Lite','Bike Pink','CabEconomy','Bike Metro', 'CabPremium')
            and channel_host in ('android','ios')
        )
        
        select
            base_segment.segment,
            -- base_segment.appCategory,
            -- base_segment.useCase,
            count(distinct funnel.customer_id) gross_customers,
            count(distinct order_id) gross_orders,
            count(distinct case when modified_order_status = 'dropped' then funnel.customer_id end) net_customers,
            count(distinct case when modified_order_status = 'dropped' then order_id end) net_orders,
            count(distinct case when modified_order_status = 'COBRM' then order_id end) cobrm_orders,
            count(distinct case when modified_order_status = 'COBRA' then order_id end) cobra_orders,
            count(distinct case when modified_order_status = 'OCARA' then order_id end) ocara_orders,
            count(distinct drop_location_hex_8) unique_dropHex8,
            count(distinct case when modified_order_status = 'dropped' and customer_set_pickup_ride_started_distance_meters <= 30.00 then order_id end) hap_orders,
            count(distinct case when amount_breakup_bid_delta_total = 0 then order_id end) zero_bid_gross,
            count(distinct case when amount_breakup_bid_delta_total < 0 then order_id end) negative_bid_gross,
            count(distinct case when amount_breakup_bid_delta_total > 0 then order_id end) positive_bid_gross,
            count(distinct case when modified_order_status = 'dropped' and amount_breakup_bid_delta_total = 0 then order_id end) zero_bid_net,
            count(distinct case when modified_order_status = 'dropped' and amount_breakup_bid_delta_total < 0 then order_id end) negative_bid_net,
            count(distinct case when modified_order_status = 'dropped' and amount_breakup_bid_delta_total > 0 then order_id end) positive_bid_net
            
        from 
            base_segment
        left join 
            funnel
            on base_segment.customer_id = funnel.customer_id
            -- and funnel.week_start_date = '20250310'
            
        group by 1
        order by 1

"""

df_segment_query_v1 = pd.read_sql(segment_query, connection)
df_segment_query_v1.head()

,segment,gross_customers,gross_orders,net_customers,net_orders,cobrm_orders,cobra_orders,ocara_orders,unique_dropHex8,hap_orders,zero_bid_gross,negative_bid_gross,positive_bid_gross,zero_bid_net,negative_bid_net,positive_bid_net
0,1-DAILY,108436,4529786,108307,2834222,28147,669144,759535,2461,2251873,2161538,644461,517442,1424899,416874,286801
1,2-WEEKLY,296366,4604073,294469,2819743,33846,709472,772900,2760,2153066,2430999,492294,452809,1570917,298908,241626
2,3-MONTHLY,1684397,8611910,1531599,5357798,73915,1316809,1378249,3093,3961379,4486045,548170,728502,2924472,335774,387243
3,4-OTHER,768154,2723132,701732,1772103,26625,362796,402323,2943,1270979,1335106,118479,211086,906476,76224,117162
4,5-INACTIVE,85110,431923,77426,275109,3423,66312,64703,2252,206650,204155,31836,30760,135884,20461,16258

In [6]:
df_segment_query_v1

,segment,gross_customers,gross_orders,net_customers,net_orders,cobrm_orders,cobra_orders,ocara_orders,unique_dropHex8,hap_orders,zero_bid_gross,negative_bid_gross,positive_bid_gross,zero_bid_net,negative_bid_net,positive_bid_net
0,1-DAILY,108436,4529786,108307,2834222,28147,669144,759535,2461,2251873,2161538,644461,517442,1424899,416874,286801
1,2-WEEKLY,296366,4604073,294469,2819743,33846,709472,772900,2760,2153066,2430999,492294,452809,1570917,298908,241626
2,3-MONTHLY,1684397,8611910,1531599,5357798,73915,1316809,1378249,3093,3961379,4486045,548170,728502,2924472,335774,387243
3,4-OTHER,768154,2723132,701732,1772103,26625,362796,402323,2943,1270979,1335106,118479,211086,906476,76224,117162
4,5-INACTIVE,85110,431923,77426,275109,3423,66312,64703,2252,206650,204155,31836,30760,135884,20461,16258

In [23]:
df_segment_query_v1.to_clipboard(index=False)

In [8]:
segment_query = f"""
    
    with base_segment as (
    
        select 
            customer_id,
            segment,
            category appCategory,
            use_case useCase
        from 
            hive.experiments_internal.customer_segment_appcategory_usecase_amj2025
        ),
        
        ao_rr_seesion as (
        
        select 
            week_start_date,
            customerid as customer_id,
            cast(ao_session as int) as ao_session,
            cast(fe_session as int) as fe_session,
            cast(rr_session as int) as rr_session
        from 
            hive.experiments_internal.customer_funnel_last90days_20250317
        where 
            week_start_date >= '20250217'
            and week_start_date <= '20250310'
        )
        
        
        select
            base_segment.segment,
            -- base_segment.appCategory,
            -- base_segment.useCase,
            sum(ao_session) ao_session,
            sum(fe_session) fe_session,
            sum(rr_session) rr_session
            
        from 
            base_segment
        left join 
            ao_rr_seesion
            on base_segment.customer_id = ao_rr_seesion.customer_id
            -- and ao_rr_seesion.week_start_date = '20250310'
            
        group by 1
        order by 1

"""

df_segment_query_v2 = pd.read_sql(segment_query, connection)
df_segment_query_v2.head()

      segment  ao_session  fe_session  rr_session
0     1-DAILY     5519284     4133553     3665006
1    2-WEEKLY     6312328     4786191     3805101
2   3-MONTHLY    13967458    10906978     7222324
3     4-OTHER     5093346     3976431     2274994
4  5-INACTIVE      303552      272022           0

In [9]:
df_segment_query_v2

      segment  ao_session  fe_session  rr_session
0     1-DAILY     5519284     4133553     3665006
1    2-WEEKLY     6312328     4786191     3805101
2   3-MONTHLY    13967458    10906978     7222324
3     4-OTHER     5093346     3976431     2274994
4  5-INACTIVE      303552      272022           0

In [24]:
df_segment_query_v2.to_clipboard(index=False)

In [11]:
segment_usecase_query = f"""
    
    with base_segment as (
    
        select 
            customer_id,
            segment,
            category appCategory,
            use_case useCase
        from 
            hive.experiments_internal.customer_segment_appcategory_usecase_amj2025
        ),
    
    
        funnel as (
        
        select
            date_format(date_trunc('week', date_parse(yyyymmdd, '%Y%m%d')), '%Y%m%d') week_start_date,
            customer_id,
            order_id,
            modified_order_status,
            customer_set_pickup_ride_started_distance_meters,
            amount_breakup_bid_delta_total,
            bid_type,
            drop_location_hex_8
            
        from 
            orders.order_logs_fact
        where 
            yyyymmdd >= '20250217'  
            and yyyymmdd <= '20250316'
            and city_name = 'Bangalore'
            and service_obj_service_name in ('Auto','Auto Lite','Auto Pool','AutoPremium','CityAuto','Link','Bike Lite','Bike Pink','CabEconomy','Bike Metro', 'CabPremium')
            and channel_host in ('android','ios')
        )
        
        
        select
            base_segment.segment,
            -- base_segment.appCategory,
            base_segment.useCase,
            count(distinct funnel.customer_id) gross_customers,
            count(distinct order_id) gross_orders,
            count(distinct case when modified_order_status = 'dropped' then funnel.customer_id end) net_customers,
            count(distinct case when modified_order_status = 'dropped' then order_id end) net_orders,
            count(distinct case when modified_order_status = 'COBRM' then order_id end) cobrm_orders,
            count(distinct case when modified_order_status = 'COBRA' then order_id end) cobra_orders,
            count(distinct case when modified_order_status = 'OCARA' then order_id end) ocara_orders,
            count(distinct drop_location_hex_8) unique_dropHex8,
            count(distinct case when modified_order_status = 'dropped' and customer_set_pickup_ride_started_distance_meters <= 30.00 then order_id end) hap_orders,
            count(distinct case when amount_breakup_bid_delta_total = 0 then order_id end) zero_bid_gross,
            count(distinct case when amount_breakup_bid_delta_total < 0 then order_id end) negative_bid_gross,
            count(distinct case when amount_breakup_bid_delta_total > 0 then order_id end) positive_bid_gross,
            count(distinct case when modified_order_status = 'dropped' and amount_breakup_bid_delta_total = 0 then order_id end) zero_bid_net,
            count(distinct case when modified_order_status = 'dropped' and amount_breakup_bid_delta_total < 0 then order_id end) negative_bid_net,
            count(distinct case when modified_order_status = 'dropped' and amount_breakup_bid_delta_total > 0 then order_id end) positive_bid_net            
        from 
            base_segment
        left join 
            funnel
            on base_segment.customer_id = funnel.customer_id
            -- and funnel.week_start_date = '20250310'
            
        group by 1,2
        order by 1,2

"""

df_segment_usecase_query_v1 = pd.read_sql(segment_usecase_query, connection)
df_segment_usecase_query_v1.head()

,segment,useCase,gross_customers,gross_orders,net_customers,net_orders,cobrm_orders,cobra_orders,ocara_orders,unique_dropHex8,hap_orders,zero_bid_gross,negative_bid_gross,positive_bid_gross,zero_bid_net,negative_bid_net,positive_bid_net
0,1-DAILY,a. office,87015,3735468,86963,2327455,23259,556212,631474,2384,1842115,1770343,531697,454943,1161531,342142,253641
1,1-DAILY,b. transit,10459,399892,10445,257640,2561,56117,64120,1787,207083,193298,60454,30297,131527,40231,16183
2,1-DAILY,c. other,10962,394426,10899,249127,2327,56815,63941,1706,202675,197897,52310,32202,131841,34501,16977
3,2-WEEKLY,a. office,208986,3431393,208037,2092400,25492,536271,574268,2621,1586010,1782361,377859,367378,1144956,228298,198386
4,2-WEEKLY,b. transit,41570,569220,41266,359951,4192,83945,92477,2231,277183,307894,57781,38720,206722,36095,19931

In [12]:
df_segment_usecase_query_v1

,segment,useCase,gross_customers,gross_orders,net_customers,net_orders,cobrm_orders,cobra_orders,ocara_orders,unique_dropHex8,hap_orders,zero_bid_gross,negative_bid_gross,positive_bid_gross,zero_bid_net,negative_bid_net,positive_bid_net
0,1-DAILY,a. office,87015,3735468,86963,2327455,23259,556212,631474,2384,1842115,1770343,531697,454943,1161531,342142,253641
1,1-DAILY,b. transit,10459,399892,10445,257640,2561,56117,64120,1787,207083,193298,60454,30297,131527,40231,16183
2,1-DAILY,c. other,10962,394426,10899,249127,2327,56815,63941,1706,202675,197897,52310,32202,131841,34501,16977
3,2-WEEKLY,a. office,208986,3431393,208037,2092400,25492,536271,574268,2621,1586010,1782361,377859,367378,1144956,228298,198386
4,2-WEEKLY,b. transit,41570,569220,41266,359951,4192,83945,92477,2231,277183,307894,57781,38720,206722,36095,19931
5,2-WEEKLY,c. other,45810,603460,45166,367392,4162,89256,106155,2196,289873,340744,56654,46711,219239,34515,23309
6,3-MONTHLY,a. office,706130,4651267,669183,2906039,38771,726063,719879,2800,2130914,2366587,332552,441132,1542601,203199,242158
7,3-MONTHLY,b. transit,314694,1461445,293232,942732,12361,213447,223299,2689,687056,768855,82387,99339,524738,52926,52698
8,3-MONTHLY,c. other,663573,2499198,569184,1509027,22783,377299,435071,2871,1143409,1350603,133231,188031,857133,79649,92387
9,4-OTHER,a. office,157657,946038,155912,622246,9111,133080,129354,2345,442122,451154,48945,85017,308743,31492,49407
10,4-OTHER,b. transit,107455,401034,106042,277940,3517,47970,53088,2323,188667,199955,16661,25959,146123,11538,15307
11,4-OTHER,c. other,503042,1376060,439778,871917,13997,181746,219881,2845,640190,683997,52873,100110,451610,33194,52448
12,5-INACTIVE,a. office,27612,227198,26614,145450,1713,35427,33079,1854,109665,104471,20212,17506,69719,13020,9608
13,5-INACTIVE,b. transit,15390,72429,14632,47548,584,10684,10380,1679,34725,34566,4750,4612,23913,3167,2410
14,5-INACTIVE,c. other,42108,132296,36180,82111,1126,20201,21244,2041,62260,65118,6874,8642,42252,4274,4240

In [25]:
df_segment_usecase_query_v1.to_clipboard(index=False)

In [13]:
segment_usecase_query = f"""
    
    with base_segment as (
    
        select 
            customer_id,
            segment,
            category appCategory,
            use_case useCase
        from 
            hive.experiments_internal.customer_segment_appcategory_usecase_amj2025
        ),
        
        ao_rr_seesion as (
        
        select 
            week_start_date,
            customerid as customer_id,
            cast(ao_session as int) as ao_session,
            cast(fe_session as int) as fe_session,
            cast(rr_session as int) as rr_session
        from 
            hive.experiments_internal.customer_funnel_last90days_20250317
        where 
            week_start_date >= '20250217'
            and week_start_date <= '20250310'
        )
        
        
        select
            base_segment.segment,
            -- base_segment.appCategory,
            base_segment.useCase,
            sum(ao_session) ao_session,
            sum(fe_session) fe_session,
            sum(rr_session) rr_session
            
        from 
            base_segment
        left join 
            ao_rr_seesion
            on base_segment.customer_id = ao_rr_seesion.customer_id
            -- and ao_rr_seesion.week_start_date = '20250310'
            
        group by 1,2
        order by 1,2

"""

df_segment_usecase_query_v2 = pd.read_sql(segment_usecase_query, connection)
df_segment_usecase_query_v2.head()

    segment     useCase  ao_session  fe_session  rr_session
0   1-DAILY   a. office     4581081     3397011     3021321
1   1-DAILY  b. transit      477470      373349      325367
2   1-DAILY    c. other      460733      363193      318318
3  2-WEEKLY   a. office     4705125     3529949     2833211
4  2-WEEKLY  b. transit      788059      616575      473381

In [14]:
df_segment_usecase_query_v2

       segment     useCase  ao_session  fe_session  rr_session
0      1-DAILY   a. office     4581081     3397011     3021321
1      1-DAILY  b. transit      477470      373349      325367
2      1-DAILY    c. other      460733      363193      318318
3     2-WEEKLY   a. office     4705125     3529949     2833211
4     2-WEEKLY  b. transit      788059      616575      473381
5     2-WEEKLY    c. other      819144      639667      498509
6    3-MONTHLY   a. office     7216680     5545021     3873522
7    3-MONTHLY  b. transit     2455760     1949696     1233180
8    3-MONTHLY    c. other     4295018     3412261     2115622
9      4-OTHER   a. office     1556383     1187187      768201
10     4-OTHER  b. transit      768965      604711      335520
11     4-OTHER    c. other     2767998     2184533     1171273
12  5-INACTIVE   a. office        2716        2074           0
13  5-INACTIVE  b. transit        2785        2197           0
14  5-INACTIVE    c. other      298051      267751           0

In [26]:
df_segment_usecase_query_v2.to_clipboard(index=False)

In [17]:
segment_appcat_usecase_query = f"""
    
    with base_segment as (
    
        select 
            customer_id,
            segment,
            category appCategory,
            use_case useCase
        from 
            hive.experiments_internal.customer_segment_appcategory_usecase_amj2025
        ),
    
    
        funnel as (
        
        select
            date_format(date_trunc('week', date_parse(yyyymmdd, '%Y%m%d')), '%Y%m%d') week_start_date,
            customer_id,
            order_id,
            modified_order_status,
            customer_set_pickup_ride_started_distance_meters,
            amount_breakup_bid_delta_total,
            bid_type,
            drop_location_hex_8
            
        from 
            orders.order_logs_fact
        where 
            yyyymmdd >= '20250217'  
            and yyyymmdd <= '20250316'
            and city_name = 'Bangalore'
            and service_obj_service_name in ('Auto','Auto Lite','Auto Pool','AutoPremium','CityAuto','Link','Bike Lite','Bike Pink','CabEconomy','Bike Metro', 'CabPremium')
            and channel_host in ('android','ios')
        )
        
        select
            base_segment.segment,
            base_segment.appCategory,
            base_segment.useCase,
            count(distinct funnel.customer_id) gross_customers,
            count(distinct order_id) gross_orders,
            count(distinct case when modified_order_status = 'dropped' then funnel.customer_id end) net_customers,
            count(distinct case when modified_order_status = 'dropped' then order_id end) net_orders,
            count(distinct case when modified_order_status = 'COBRM' then order_id end) cobrm_orders,
            count(distinct case when modified_order_status = 'COBRA' then order_id end) cobra_orders,
            count(distinct case when modified_order_status = 'OCARA' then order_id end) ocara_orders,
            count(distinct drop_location_hex_8) unique_dropHex8,
            count(distinct case when modified_order_status = 'dropped' and customer_set_pickup_ride_started_distance_meters <= 30.00 then order_id end) hap_orders,
            count(distinct case when amount_breakup_bid_delta_total = 0 then order_id end) zero_bid_gross,
            count(distinct case when amount_breakup_bid_delta_total < 0 then order_id end) negative_bid_gross,
            count(distinct case when amount_breakup_bid_delta_total > 0 then order_id end) positive_bid_gross,
            count(distinct case when modified_order_status = 'dropped' and amount_breakup_bid_delta_total = 0 then order_id end) zero_bid_net,
            count(distinct case when modified_order_status = 'dropped' and amount_breakup_bid_delta_total < 0 then order_id end) negative_bid_net,
            count(distinct case when modified_order_status = 'dropped' and amount_breakup_bid_delta_total > 0 then order_id end) positive_bid_net
            
        from 
            base_segment
        left join 
            funnel
            on base_segment.customer_id = funnel.customer_id
            -- and funnel.week_start_date = '20250310'
            
        group by 1,2,3
        order by 1,2,3

"""

df_segment_appcat_query_v1 = pd.read_sql(segment_appcat_usecase_query, connection)
df_segment_appcat_query_v1.head()

,segment,appCategory,useCase,gross_customers,gross_orders,net_customers,net_orders,cobrm_orders,cobra_orders,ocara_orders,unique_dropHex8,hap_orders,zero_bid_gross,negative_bid_gross,positive_bid_gross,zero_bid_net,negative_bid_net,positive_bid_net
0,1-DAILY,a. RHA - NQC,a. office,3869,161745,3853,103400,1245,23885,24417,1677,81691,73250,18816,10156,48813,12535,5370
1,1-DAILY,a. RHA - NQC,b. transit,954,36001,951,23263,290,5139,5332,1107,18463,16274,4635,2162,11033,3089,977
2,1-DAILY,a. RHA - NQC,c. other,985,36303,965,22334,307,5792,6056,1110,18363,17333,3952,2084,11235,2653,863
3,1-DAILY,a. RHA - QC,a. office,47635,2038893,47617,1264317,13473,318892,334864,2151,1004623,932620,293323,243569,611013,188562,133767
4,1-DAILY,a. RHA - QC,b. transit,5811,221703,5808,142142,1511,32037,35375,1614,114781,106341,34811,17468,72356,23230,9369

In [18]:
df_segment_appcat_query_v1

,segment,appCategory,useCase,gross_customers,gross_orders,net_customers,net_orders,cobrm_orders,cobra_orders,ocara_orders,unique_dropHex8,hap_orders,zero_bid_gross,negative_bid_gross,positive_bid_gross,zero_bid_net,negative_bid_net,positive_bid_net
0,1-DAILY,a. RHA - NQC,a. office,3869,161745,3853,103400,1245,23885,24417,1677,81691,73250,18816,10156,48813,12535,5370
1,1-DAILY,a. RHA - NQC,b. transit,954,36001,951,23263,290,5139,5332,1107,18463,16274,4635,2162,11033,3089,977
2,1-DAILY,a. RHA - NQC,c. other,985,36303,965,22334,307,5792,6056,1110,18363,17333,3952,2084,11235,2653,863
3,1-DAILY,a. RHA - QC,a. office,47635,2038893,47617,1264317,13473,318892,334864,2151,1004623,932620,293323,243569,611013,188562,133767
4,1-DAILY,a. RHA - QC,b. transit,5811,221703,5808,142142,1511,32037,35375,1614,114781,106341,34811,17468,72356,23230,9369
5,1-DAILY,a. RHA - QC,c. other,6108,218881,6076,137031,1504,32080,35511,1529,111523,109997,31194,18568,73000,20444,9588
6,1-DAILY,b. NRHA - NQC,a. office,3493,147813,3487,95603,971,23326,22088,1575,74866,63622,15766,9844,43036,10625,5339
7,1-DAILY,b. NRHA - NQC,b. transit,774,29379,771,19362,162,4317,4252,1024,15422,13397,2936,1557,9260,2049,807
8,1-DAILY,b. NRHA - NQC,c. other,876,30505,866,19828,177,4684,4462,931,16094,14267,3260,1588,9874,2116,830
9,1-DAILY,b. NRHA - QC,a. office,5804,245943,5800,160308,1455,38488,37154,1546,127345,117511,25065,24186,81210,17151,13685
10,1-DAILY,b. NRHA - QC,b. transit,1065,40803,1061,27319,196,5615,6140,1056,21842,21170,3717,2738,14910,2638,1492
11,1-DAILY,b. NRHA - QC,c. other,1139,40862,1138,27340,130,5726,5842,1030,22139,20897,3648,3318,14691,2557,1844
12,1-DAILY,c. iOS,a. office,26214,1141074,26206,703827,6115,151621,212951,1854,553590,583340,178727,167188,377459,113269,95480
13,1-DAILY,c. iOS,b. transit,1855,72006,1854,45554,402,9009,13021,1145,36575,36116,14355,6372,23968,9225,3538
14,1-DAILY,c. iOS,c. other,1854,67875,1854,42594,209,8533,12070,1020,34556,35403,10256,6644,23041,6731,3852
15,2-WEEKLY,a. RHA - NQC,a. office,10583,159622,10515,100032,1548,24283,25164,1938,75652,77660,12526,10565,51808,7817,5226
16,2-WEEKLY,a. RHA - NQC,b. transit,3480,47265,3427,30014,442,6732,7647,1550,22964,24801,3595,2808,16801,2270,1246
17,2-WEEKLY,a. RHA - NQC,c. other,4059,53180,3922,31790,491,7726,9991,1557,24807,28783,4132,3512,18315,2519,1337
18,2-WEEKLY,a. RHA - QC,a. office,114129,1881077,113632,1140940,14641,306100,308010,2398,871744,954241,214680,202860,611361,128776,108428
19,2-WEEKLY,a. RHA - QC,b. transit,22375,305986,22212,192572,2293,45939,49467,1991,149133,165298,33743,21431,110382,20934,10971
20,2-WEEKLY,a. RHA - QC,c. other,24452,323285,24113,195528,2419,48891,56170,1945,155230,183228,32687,25675,117247,19566,12759
21,2-WEEKLY,b. NRHA - NQC,a. office,10064,153615,10025,97589,1400,24439,23336,1856,73354,72718,10215,9740,49173,6630,5100
22,2-WEEKLY,b. NRHA - NQC,b. transit,3572,49181,3547,31246,430,7805,7538,1475,23712,24533,3544,2648,16607,2338,1295
23,2-WEEKLY,b. NRHA - NQC,c. other,3927,51153,3902,32103,368,7695,8241,1485,25052,26811,3156,2915,17788,2127,1515
24,2-WEEKLY,b. NRHA - QC,a. office,17074,261940,17019,169317,1837,41424,39708,1865,128271,134183,19639,22781,91776,13161,12550
25,2-WEEKLY,b. NRHA - QC,b. transit,5037,68730,5023,44949,474,10157,10411,1538,34219,38056,4987,4591,26608,3275,2461
26,2-WEEKLY,b. NRHA - QC,c. other,5599,72901,5567,46476,404,10791,11862,1476,36051,42070,5276,5760,28498,3450,2881
27,2-WEEKLY,c. iOS,a. office,57136,975139,56846,584522,6066,140025,178050,2033,436989,543559,120799,121432,340838,71914,67082
28,2-WEEKLY,c. iOS,b. transit,7106,98058,7057,61170,553,13312,17414,1519,47155,55206,11912,7242,36324,7278,3958
29,2-WEEKLY,c. iOS,c. other,7773,102941,7662,61495,480,14153,19891,1455,48733,59852,11403,8849,37391,6853,4817
30,3-MONTHLY,a. RHA - NQC,a. office,47780,281594,45082,180286,2934,40087,42543,2218,131642,138147,14114,16886,93104,8952,8473
31,3-MONTHLY,a. RHA - NQC,b. transit,31158,141478,28872,90957,1563,19240,21910,2102,65470,72144,6562,7984,49268,4398,3830
32,3-MONTHLY,a. RHA - NQC,c. other,64625,244662,54829,145564,3098,34674,45086,2366,109954,127167,11370,16185,80416,6796,6374
33,3-MONTHLY,a. RHA - QC,a. office,357747,2392093,338587,1484822,20159,390294,363364,2549,1099860,1198864,181233,234705,776734,110010,128164
34,3-MONTHLY,a. RHA - QC,b. transit,147628,697037,136866,447056,5462,105629,106125,2391,330409,368096,44468,49289,249291,28154,26402
35,3-MONTHLY,a. RHA - QC,c. other,319078,1199170,271541,719386,10168,189655,205971,2599,551285,651971,72408,93302,411085,42580,46029
36,3-MONTHLY,b. NRHA - NQC,a. office,61975,359332,59109,232002,3812,52055,53859,2285,167325,170840,16133,21284,116126,10624,10921
37,3-MONTHLY,b. NRHA - NQC,b. transit,42900,192650,40418,124362,2241,26725,29415,2208,88360,98984,7625,10769,68146,5093,5227
38,3-MONTHLY,b. NRHA - NQC,c. other,82755,317153,73011,195176,3735,44279,54000,2417,144747,163606,11938,18530,106381,7667,8518
39,3-MONTHLY,b. NRHA - QC,a. office,79417,471795,76056,308702,4056,73226,67643,2204,225556,230241,23795,36678,159348,15896,19977
40,3-MONTHLY,b. NRHA - QC,b. transit,45752,207636,43250,136677,1730,30140,30942,2058,98107,108292,9188,14175,75933,6211,7471
41,3-MONTHLY,b. NRHA - QC,c. other,91314,340634,81212,214757,3018,48786,56172,2275,159986,183570,13875,24984,122504,9173,12733
42,3-MONTHLY,c. iOS,a. office,159211,1146453,150349,700227,7810,170401,192470,2203,506531,628495,97277,131579,397289,57717,74623
43,3-MONTHLY,c. iOS,b. transit,47256,222644,43826,143680,1365,31713,34907,1939,104710,121339,14544,17122,82100,9070,9768
44,3-MONTHLY,c. iOS,c. other,105801,397579,88591,234144,2764,59905,73842,2127,177437,224289,23640,35030,136747,13433,18733
45,4-OTHER,a. RHA - NQC,a. office,14282,74286,14128,50121,719,9289,9749,1720,35642,34824,3310,4312,24431,2109,2412
46,4-OTHER,a. RHA - NQC,b. transit,13191,46970,13052,32662,563,4947,6303,1680,22135,23455,1946,2560,17271,1295,1457
47,4-OTHER,a. RHA - NQC,c. other,59028,160241,51875,100829,2035,19240,26613,2320,73751,78713,5342,9770,51915,3283,4498
48,4-OTHER,a. RHA - QC,a. office,68094,431587,67218,281083,4085,64874,57632,1997,202464,202076,24420,41571,136546,15526,24063
49,4-OTHER,a. RHA - QC,b. transit,38361,151949,37716,104653,1288,19790,19541,1928,72820,74107,7005,10367,53799,4854,6196
50,4-OTHER,a. RHA - QC,c. other,201243,545773,171586,341443,5111,79459,85436,2476,255497,272559,23154,43108,177061,14342,22722
51,4-OTHER,b. NRHA - NQC,a. office,23512,113654,23299,77507,1054,13446,15651,1847,53883,53013,4015,5878,37858,2772,3181
52,4-OTHER,b. NRHA - NQC,b. transit,25337,83801,25076,58188,786,8872,11621,1905,37711,43074,2632,4433,31629,1854,2418
53,4-OTHER,b. NRHA - NQC,c. other,96308,264895,88130,171339,3057,29845,42526,2485,122432,130535,8497,14535,88451,5596,7259
54,4-OTHER,b. NRHA - QC,a. office,20335,107222,20157,73474,925,14318,14202,1648,52189,49235,4517,7653,35461,3204,4455
55,4-OTHER,b. NRHA - QC,b. transit,17440,62890,17243,44131,490,7433,8283,1620,29675,31354,2251,4246,23332,1638,2418
56,4-OTHER,b. NRHA - QC,c. other,73574,199118,66369,130647,1725,24493,30845,2188,94786,98486,6635,13870,67994,4504,7415
57,4-OTHER,c. iOS,a. office,31434,219289,31110,140061,2328,31153,32120,1644,97944,112006,12683,25603,74447,7881,15296
58,4-OTHER,c. iOS,b. transit,13126,55424,12955,38306,390,6928,7340,1507,26326,27965,2827,4353,20092,1897,2818
59,4-OTHER,c. iOS,c. other,72889,206033,61818,127659,2069,28709,34461,2032,93724,103704,9245,18827,66189,5469,10554
60,5-INACTIVE,a. RHA - NQC,a. office,2418,17410,2327,11498,121,2429,2450,1217,8613,8101,1064,888,5528,751,450
61,5-INACTIVE,a. RHA - NQC,b. transit,1788,8522,1687,5466,84,1234,1371,1018,3962,3789,545,583,2609,305,254
62,5-INACTIVE,a. RHA - NQC,c. other,5016,15846,4291,9678,219,2270,2756,1398,7345,7641,759,1070,4901,525,440
63,5-INACTIVE,a. RHA - QC,a. office,17715,160149,17060,101342,1209,25420,23591,1676,77157,75465,16252,13447,49717,10294,7323
64,5-INACTIVE,a. RHA - QC,b. transit,8395,42641,7938,27953,319,6306,6148,1460,20834,21079,3146,2745,14469,2123,1459
65,5-INACTIVE,a. RHA - QC,c. other,23078,75648,19546,46581,552,12003,12087,1747,35863,38713,4523,5011,24812,2725,2520
66,5-INACTIVE,b. NRHA - NQC,a. office,2838,16972,2756,11423,149,2437,2278,1159,8249,7459,634,912,5196,466,539
67,5-INACTIVE,b. NRHA - NQC,b. transit,2384,8909,2301,5869,99,1292,1224,1037,4013,4091,398,531,2890,292,273
68,5-INACTIVE,b. NRHA - NQC,c. other,5950,17330,5320,11107,203,2289,2663,1436,8051,8051,684,1005,5431,421,491
69,5-INACTIVE,b. NRHA - QC,a. office,3490,23362,3362,15708,161,3523,3145,1144,11563,10631,1523,1591,7509,1090,926
70,5-INACTIVE,b. NRHA - QC,b. transit,2348,10301,2255,6937,73,1527,1345,1009,4961,4942,536,680,3506,368,378
71,5-INACTIVE,b. NRHA - QC,c. other,6397,18941,5670,12080,127,2892,2942,1336,8985,9281,758,1372,6195,523,694
72,5-INACTIVE,c. iOS,a. office,1151,9305,1109,5479,73,1618,1615,769,4083,2815,739,668,1769,419,370
73,5-INACTIVE,c. iOS,b. transit,475,2056,451,1323,9,325,292,556,955,665,125,73,439,79,46
74,5-INACTIVE,c. iOS,c. other,1667,4531,1353,2665,25,747,796,859,2016,1432,150,184,913,80,95

In [27]:
df_segment_appcat_query_v1.to_clipboard(index=False)

In [20]:
segment_appcat_usecase_query = f"""
    
    with base_segment as (
    
        select 
            customer_id,
            segment,
            category appCategory,
            use_case useCase
        from 
            hive.experiments_internal.customer_segment_appcategory_usecase_amj2025
        ),
            
        ao_rr_seesion as (
        
        select 
            week_start_date,
            customerid as customer_id,
            cast(ao_session as int) as ao_session,
            cast(fe_session as int) as fe_session,
            cast(rr_session as int) as rr_session
        from 
            hive.experiments_internal.customer_funnel_last90days_20250317
        where 
            week_start_date >= '20250217'
            and week_start_date <= '20250310'
        )
        
        
        select
            base_segment.segment,
            base_segment.appCategory,
            base_segment.useCase,
            sum(ao_session) ao_session,
            sum(fe_session) fe_session,
            sum(rr_session) rr_session
            
        from 
            base_segment
        left join 
            ao_rr_seesion
            on base_segment.customer_id = ao_rr_seesion.customer_id
            -- and ao_rr_seesion.week_start_date = '20250310'
            
        group by 1,2,3
        order by 1,2,3

"""

df_segment_appcat_query_v2 = pd.read_sql(segment_appcat_usecase_query, connection)
df_segment_appcat_query_v2.head()

   segment   appCategory     useCase  ao_session  fe_session  rr_session
0  1-DAILY  a. RHA - NQC   a. office      201645      157771      130770
1  1-DAILY  a. RHA - NQC  b. transit       42639       34485       28940
2  1-DAILY  a. RHA - NQC    c. other       41981       34221       28549
3  1-DAILY   a. RHA - QC   a. office     2235388     1819809     1623070
4  1-DAILY   a. RHA - QC  b. transit      248956      205342      179045

In [21]:
df_segment_appcat_query_v2

       segment    appCategory     useCase  ao_session  fe_session  rr_session
0      1-DAILY   a. RHA - NQC   a. office      201645      157771      130770
1      1-DAILY   a. RHA - NQC  b. transit       42639       34485       28940
2      1-DAILY   a. RHA - NQC    c. other       41981       34221       28549
3      1-DAILY    a. RHA - QC   a. office     2235388     1819809     1623070
4      1-DAILY    a. RHA - QC  b. transit      248956      205342      179045
5      1-DAILY    a. RHA - QC    c. other      238006      198706      174902
6      1-DAILY  b. NRHA - NQC   a. office      176592      136040      117424
7      1-DAILY  b. NRHA - NQC  b. transit       34383       27091       23401
8      1-DAILY  b. NRHA - NQC    c. other       34504       27474       24023
9      1-DAILY   b. NRHA - QC   a. office      271967      216462      194026
10     1-DAILY   b. NRHA - QC  b. transit       44409       36184       32750
11     1-DAILY   b. NRHA - QC    c. other       44554       36047       32467
12     1-DAILY         c. iOS   a. office     1695489     1066929      956031
13     1-DAILY         c. iOS  b. transit      107083       70247       61231
14     1-DAILY         c. iOS    c. other      101688       66745       58377
15    2-WEEKLY   a. RHA - NQC   a. office      226278      179128      131279
16    2-WEEKLY   a. RHA - NQC  b. transit       66337       53430       39162
17    2-WEEKLY   a. RHA - NQC    c. other       72889       59033       43151
18    2-WEEKLY    a. RHA - QC   a. office     2336270     1909674     1534291
19    2-WEEKLY    a. RHA - QC  b. transit      399254      329842      253748
20    2-WEEKLY    a. RHA - QC    c. other      412394      340507      265632
21    2-WEEKLY  b. NRHA - NQC   a. office      210878      163814      124188
22    2-WEEKLY  b. NRHA - NQC  b. transit       67621       53285       39478
23    2-WEEKLY  b. NRHA - NQC    c. other       68854       54261       41029
24    2-WEEKLY   b. NRHA - QC   a. office      332743      265443      211427
25    2-WEEKLY   b. NRHA - QC  b. transit       88186       71176       55967
26    2-WEEKLY   b. NRHA - QC    c. other       90566       72719       58369
27    2-WEEKLY         c. iOS   a. office     1598956     1011890      832026
28    2-WEEKLY         c. iOS  b. transit      166661      108842       85026
29    2-WEEKLY         c. iOS    c. other      174441      113147       90328
30   3-MONTHLY   a. RHA - NQC   a. office      461207      370266      232889
31   3-MONTHLY   a. RHA - NQC  b. transit      247266      200547      118658
32   3-MONTHLY   a. RHA - NQC    c. other      441501      359147      204312
33   3-MONTHLY    a. RHA - QC   a. office     3391232     2804510     1971838
34   3-MONTHLY    a. RHA - QC  b. transit     1098706      917098      587551
35   3-MONTHLY    a. RHA - QC    c. other     1942596     1624490     1015085
36   3-MONTHLY  b. NRHA - NQC   a. office      597800      468873      293466
37   3-MONTHLY  b. NRHA - NQC  b. transit      338533      267784      158316
38   3-MONTHLY  b. NRHA - NQC    c. other      571834      450533      260748
39   3-MONTHLY   b. NRHA - QC   a. office      716731      578479      383439
40   3-MONTHLY   b. NRHA - QC  b. transit      338485      274775      171198
41   3-MONTHLY   b. NRHA - QC    c. other      564277      456366      280769
42   3-MONTHLY         c. iOS   a. office     2049710     1322893      991890
43   3-MONTHLY         c. iOS  b. transit      432770      289492      197457
44   3-MONTHLY         c. iOS    c. other      774810      521725      354708
45     4-OTHER   a. RHA - NQC   a. office      130587      103712       60481
46     4-OTHER   a. RHA - NQC  b. transit       91817       73330       39210
47     4-OTHER   a. RHA - NQC    c. other      337231      270127      135568
48     4-OTHER    a. RHA - QC   a. office      625535      514574      342129
49     4-OTHER    a. RHA - QC  b. transit      262714      218750      125681
50     4-OTHER    a. RHA - QC    c. other     1019005      854724      464434
51     4-OTHER  b. NRHA - NQC   a. office      214067      164942       92510
52     4-OTHER  b. NRHA - NQC  b. transit      175884      136021       69744
53     4-OTHER  b. NRHA - NQC    c. other      572870      440376      221539
54     4-OTHER   b. NRHA - QC   a. office      180158      144265       84893
55     4-OTHER   b. NRHA - QC  b. transit      122142       98631       51735
56     4-OTHER   b. NRHA - QC    c. other      403425      324096      166471
57     4-OTHER         c. iOS   a. office      406036      259694      188188
58     4-OTHER         c. iOS  b. transit      116408       77979       49150
59     4-OTHER         c. iOS    c. other      435467      295210      183261
60  5-INACTIVE   a. RHA - NQC   a. office         256         195           0
61  5-INACTIVE   a. RHA - NQC  b. transit         341         271           0
62  5-INACTIVE   a. RHA - NQC    c. other       40957       37502           0
63  5-INACTIVE    a. RHA - QC   a. office        1160         943           0
64  5-INACTIVE    a. RHA - QC  b. transit        1159         931           0
65  5-INACTIVE    a. RHA - QC    c. other      125124      118935           0
66  5-INACTIVE  b. NRHA - NQC   a. office         363         278           0
67  5-INACTIVE  b. NRHA - NQC  b. transit         668         528           0
68  5-INACTIVE  b. NRHA - NQC    c. other       48148       42797           0
69  5-INACTIVE   b. NRHA - QC   a. office         433         370           0
70  5-INACTIVE   b. NRHA - QC  b. transit         415         354           0
71  5-INACTIVE   b. NRHA - QC    c. other       41657       38451           0
72  5-INACTIVE         c. iOS   a. office         504         288           0
73  5-INACTIVE         c. iOS  b. transit         202         113           0
74  5-INACTIVE         c. iOS    c. other       42165       30066           0

In [28]:
df_segment_appcat_query_v2.to_clipboard(index=False)