
<div class="alert alert-block alert-info">  
    
## Import & Connections
</div>

In [1]:
import numpy as np
import pandas as pd
import hashlib
import glob
import time
import os
import re
import matplotlib.pyplot as plt

from scipy import stats
from pyhive import presto
from datetime import datetime, timedelta

import warnings
warnings.filterwarnings('ignore')

In [2]:
pd.set_option('display.max_rows', 300)
pd.set_option('display.max_columns', 50)

In [3]:
connection = presto.connect(
        host='presto-gateway.serving.data.production.internal',
        port=80,
        protocol='http',
        catalog='hive',
        username='manoj.ravirajan@rapido.bike'
)

In [59]:
start_date = '20250130'
end_date = '20250205'
response_type = 'ONLINE_SALES'
pagename = 'PostOrderScreen'
campaign_name = 'Exp2|Urban Company Bangalore' # Exp2_HeroV2_TataNeu
format = 'heroBannerV2'

In [56]:
print(os.getcwd())
local_dataset = '/Users/E2074/local-datasets/customer/ads-monetisation/page-format-experiment/hero-banner'
print(local_dataset)

/Users/E2074/analytics/customer/Ads-Monetisation/page-format-experiment
/Users/E2074/local-datasets/customer/ads-monetisation/page-format-experiment/hero-banner

<div class="alert alert-block alert-warning">  
    
## Datasets & Functions
</div>

In [57]:
start = datetime.strptime(start_date, '%Y%m%d')
end = datetime.strptime(end_date, '%Y%m%d')

# Generate the list of dates
date_range = [(start + timedelta(days=i)).strftime('%Y%m%d') for i in range((end - start).days + 1)]
print(date_range)

['20250202', '20250203', '20250204', '20250205']

In [58]:
def get_customer_metadata(date_range):

    all_df = []
    
    for date in date_range:
    
        customer_metadata = f"""
        
            with response as (
    
                select
                    distinct
                    yyyymmdd,
                    city,
                    os,
                    json_extract_scalar(metadata1, '$.campaignName') AS campaignName,
                    json_extract_scalar(metadata1, '$.slotUnitId') AS slotUnitId,
                    userid,
                    service,
                    orderstatus,
                    -- totalcardcount,
                    -- cardposition,
                    coalesce(aduuid, adid) response_id
                from 
                    canonical.iceberg_log_telemetry_ads_impressions_immutable
                where 
                    yyyymmdd = '{date}'
                    and os = 'android'
                    and responsetype = '{response_type}'
                    and eventname = 'Ad_Response'
                    and pagename = '{pagename}'
                    and format = '{format}'
                    and regexp_like(metadata1, '{campaign_name}')
                ),
                
                impression as (
                
                select
                    distinct
                    yyyymmdd,
                    userid,
                    coalesce(aduuid, adid) impression_id
                from 
                    canonical.iceberg_log_telemetry_ads_impressions_immutable
                where 
                    yyyymmdd = '{date}'
                    and os = 'android'
                    and responsetype = '{response_type}'
                    and eventname = 'Ad_Impression'
                    and pagename = '{pagename}'
                    and format = '{format}'
                    and regexp_like(metadata1, '{campaign_name}')
                ),
                
                viewable_impression as (
                
                select
                    distinct
                    yyyymmdd,
                    userid,
                    coalesce(aduuid, adid) viewable_impression_id
                from 
                    canonical.iceberg_log_telemetry_ads_impressions_immutable
                where 
                    yyyymmdd = '{date}'
                    and os = 'android'
                    and responsetype = '{response_type}'
                    and eventname = 'Ad_Viewable_Impression'
                    and pagename = '{pagename}'
                    and format = '{format}'
                    and regexp_like(metadata1, '{campaign_name}')
                ),
                
                click as (
                
                select
                    distinct
                    yyyymmdd,
                    userid,
                    coalesce(aduuid, adid) click_id
                from 
                    canonical.iceberg_log_telemetry_ads_impressions_immutable
                where 
                    yyyymmdd = '{date}'
                    and os = 'android'
                    and responsetype = '{response_type}'
                    and eventname = 'Ad_Click'
                    and pagename = '{pagename}'
                    and format = '{format}'
                )
                
                select
                    a.*,
                    impression_id,
                    coalesce(click_id, viewable_impression_id) viewable_impression_id,
                    click_id
                from 
                    response a
                left join 
                    impression b
                    on a.yyyymmdd = b.yyyymmdd
                    and a.userid = b.userid
                    and a.response_id = b.impression_id
                left join 
                    viewable_impression c
                    on b.yyyymmdd = c.yyyymmdd
                    and b.userid = c.userid
                    and b.impression_id = c.viewable_impression_id
                left join 
                    click d
                    on b.yyyymmdd = d.yyyymmdd
                    and b.userid = d.userid
                    and b.impression_id = d.click_id
        """
        
        df = pd.read_sql(customer_metadata, connection)
        all_df.append(df)
        df.to_parquet(local_dataset + '/data_dump/Exp3_{}_{}.parquet'.format(campaign_name,date), index=False)
    
    # Concatenate all DataFrames
    final_df = pd.concat(all_df, ignore_index=True)

    return final_df


# df_data = get_customer_metadata(date_range)

In [61]:
def get_customer_segment():    
    
    customer_segment = f"""
    
        with response as (

            select
                distinct
                userid
            from 
                canonical.iceberg_log_telemetry_ads_impressions_immutable
            where 
                yyyymmdd >= '{start_date}'
                and yyyymmdd <= '{end_date}'
                and os = 'android'
                and responsetype = '{response_type}'
                and eventname = 'Ad_Response'
                and pagename = '{pagename}'
                and format = '{format}'
                and regexp_like(metadata1, '{campaign_name}')
            ),

            segment as (
    
            select
                customer_id,
                gender_tag,
                taxi_ltr_segment,
                taxi_retention_segments,
                taxi_regularity_segment,
                taxi_fe_regularity_segment,
                taxi_income_segment,
                taxi_service_affinity,
                taxi_gc_tag
            from 
                datasets.iallocator_customer_segments
            where 
                run_date = '2025-01-29'
            )
            
            select
                userid,
                coalesce(gender_tag, 'UNKNOWN') gender,
                coalesce(taxi_ltr_segment, 'NEW') ltr_segment,
                coalesce(taxi_retention_segments, 'UNKNOWN') retention_segments,
                coalesce(taxi_regularity_segment, 'UNKNOWN') regularity_segment,
                coalesce(taxi_fe_regularity_segment, 'UNKNOWN') fe_regularity_segment,
                coalesce(taxi_income_segment, 'UNKNOWN') income_segment,
                coalesce(taxi_service_affinity, 'UNKNOWN') service_affinity,
                coalesce(taxi_gc_tag, 'UNKNOWN') gc_tag
            from 
                response
            left join 
                segment
                on userid = customer_id
            
    """
    
    df = pd.read_sql(customer_segment, connection)
    df.to_parquet(local_dataset + '/Exp3_customer_segment.parquet', index=False)

    return df

# df_data = get_customer_segment()


<div class="alert alert-block alert-info">  
    
## Load data
</div>

In [63]:
def get_customer_metadata(prefix):
    
    parquet_files = glob.glob(os.path.join(local_dataset + '/data_dump/', f'{prefix}*.parquet'))
    
    customer_metadata = pd.concat([pd.read_parquet(file) for file in parquet_files], ignore_index=True)
    customer_segment = pd.read_parquet(local_dataset + f'/{prefix}_customer_segment.parquet')
    
    df = pd.merge(customer_metadata, customer_segment, how='left', on = 'userid')
    return df

In [64]:
df_exp1 = get_customer_metadata('Exp1')
df_exp2 = get_customer_metadata('Exp2')
df_exp3 = get_customer_metadata('Exp3')

In [65]:
df_exp1['Experiment'] = 'Experiment-1'
df_exp2['Experiment'] = 'Experiment-2'
df_exp3['Experiment'] = 'Experiment-3'

In [66]:
frames = [df_exp1, df_exp2, df_exp3]
df_data = pd.concat(frames)

In [67]:
df_data.head(2)

,yyyymmdd,city,os,campaignName,slotUnitId,userid,service,orderstatus,response_id,impression_id,viewable_impression_id,click_id,gender,ltr_segment,retention_segments,regularity_segment,fe_regularity_segment,income_segment,service_affinity,gc_tag,Experiment
0,20250119,Hyderabad,android,Exp1_HeroV2_TataNeu,PostOrderStarted2,676f87131d37e3d34876a364,Auto,started,6097aab4-4c2c-4293-806c-82b6db31000f676f87131d...,6097aab4-4c2c-4293-806c-82b6db31000f676f87131d...,6097aab4-4c2c-4293-806c-82b6db31000f676f87131d...,None,MALE,HH,HH,UNKNOWN,MONTHLY,LOW_INCOME,UNKNOWN,UNKNOWN,Experiment-1
1,20250119,Bangalore,android,Exp1_HeroV2_TataNeu,PostOrderOnTheWay2,66a5dff7fc10f2126b031cf1,Auto,onTheWay,f753d406-7a63-4071-889d-c80d4ce3b72166a5dff7fc...,f753d406-7a63-4071-889d-c80d4ce3b72166a5dff7fc...,f753d406-7a63-4071-889d-c80d4ce3b72166a5dff7fc...,None,FEMALE,PHH,GOLD,BI_WEEKLY,BI_WEEKLY,MEDIUM_INCOME,UNKNOWN,UNKNOWN,Experiment-1

In [68]:
df_data['yyyymmdd'].value_counts().sort_index(ascending=True)

yyyymmdd
20250117        90
20250118    306764
20250119    308269
20250120    309985
20250121    308642
20250122    303250
20250123    288764
20250124    287889
20250125    295176
20250126    299580
20250127    307895
20250128    304114
20250129    307860
20250130    256182
20250131    556251
20250201    538629
20250202    303467
20250203    456373
20250204    547681
20250205    561682
Name: count, dtype: int64

<div class="alert alert-block alert-warning">  
    
## Funnel Func
</div>

In [70]:

def get_funnel(df, groupby):

    df_temp = df\
                .groupby(groupby)\
                .agg(responses = ('response_id', 'nunique'),
                     impression = ('impression_id', 'nunique'),
                     viewable_impression = ('viewable_impression_id', 'nunique'),
                     click = ('click_id', 'nunique'),
                    )\
                .reset_index()

    df_temp['% render rate'] = (df_temp['impression']*100.00/df_temp['responses']).round(2)
    df_temp['% view'] = (df_temp['viewable_impression']*100.00/df_temp['impression']).round(2)
    df_temp['% ctr'] = (df_temp['click']*100.00/df_temp['viewable_impression']).round(2)

    df_temp['format'] = format
    
    columns = ['format'] + groupby + ['responses', 'impression', 'viewable_impression', 'click', '% render rate', '% view', '% ctr']
    
    return df_temp[columns].sort_values(by=['Experiment', '% ctr'], ascending=[True, False])

<div class="alert alert-block alert-success">  
    
## Analysis
</div>

In [71]:
df_data.head(5)

,yyyymmdd,city,os,campaignName,slotUnitId,userid,service,orderstatus,response_id,impression_id,viewable_impression_id,click_id,gender,ltr_segment,retention_segments,regularity_segment,fe_regularity_segment,income_segment,service_affinity,gc_tag,Experiment
0,20250119,Hyderabad,android,Exp1_HeroV2_TataNeu,PostOrderStarted2,676f87131d37e3d34876a364,Auto,started,6097aab4-4c2c-4293-806c-82b6db31000f676f87131d...,6097aab4-4c2c-4293-806c-82b6db31000f676f87131d...,6097aab4-4c2c-4293-806c-82b6db31000f676f87131d...,None,MALE,HH,HH,UNKNOWN,MONTHLY,LOW_INCOME,UNKNOWN,UNKNOWN,Experiment-1
1,20250119,Bangalore,android,Exp1_HeroV2_TataNeu,PostOrderOnTheWay2,66a5dff7fc10f2126b031cf1,Auto,onTheWay,f753d406-7a63-4071-889d-c80d4ce3b72166a5dff7fc...,f753d406-7a63-4071-889d-c80d4ce3b72166a5dff7fc...,f753d406-7a63-4071-889d-c80d4ce3b72166a5dff7fc...,None,FEMALE,PHH,GOLD,BI_WEEKLY,BI_WEEKLY,MEDIUM_INCOME,UNKNOWN,UNKNOWN,Experiment-1
2,20250119,Bangalore,android,Exp1_HeroV2_TataNeu,PostOrderOnTheWay2,672d535d323c904f9840cfbe,Link,onTheWay,5973be36-c638-412f-ac05-b6515030844f672d535d32...,5973be36-c638-412f-ac05-b6515030844f672d535d32...,5973be36-c638-412f-ac05-b6515030844f672d535d32...,None,MALE,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN,MEDIUM_INCOME,UNKNOWN,UNKNOWN,Experiment-1
3,20250119,Hyderabad,android,Exp1_HeroV2_TataNeu,PostOrderStarted2,6208fc428e29c807291bdaf0,Link,started,c7c2e995-5399-426f-a9b6-3035b605d3026208fc428e...,c7c2e995-5399-426f-a9b6-3035b605d3026208fc428e...,c7c2e995-5399-426f-a9b6-3035b605d3026208fc428e...,None,MALE,PHH,SILVER,MONTHLY,MONTHLY,MEDIUM_INCOME,UNKNOWN,UNKNOWN,Experiment-1
4,20250119,Bangalore,android,Exp1_HeroV2_TataNeu,PostOrderStarted2,64e5b8af7284de2fb4552e7d,Auto,started,ff12a600-4f51-4499-b9d9-0546f142aecb64e5b8af72...,ff12a600-4f51-4499-b9d9-0546f142aecb64e5b8af72...,None,None,MALE,PHH,DORMANT,RARE_NEED,UNKNOWN,HIGH_INCOME,UNKNOWN,UNKNOWN,Experiment-1

#### Bivariate data

In [72]:
get_funnel(df_data, ['Experiment', 'os']).pivot(index = ['Experiment'] , 
                                                columns = ['os'] , 
                                                values =['% render rate', '% view',	'% ctr', 'impression', 'viewable_impression', 'click'])

,% render rate,% view,% ctr,impression,viewable_impression,click
os,android,android,android,android,android,android
Experiment,,,,,,
Experiment-1,80.37,74.23,0.28,1235236.0,916891.0,2568.0
Experiment-2,76.94,75.00,0.04,1609017.0,1206824.0,526.0
Experiment-3,82.23,78.80,0.37,2648106.0,2086748.0,7618.0

In [73]:
get_funnel(df_data, ['Experiment', 'campaignName', 'os']).pivot(index = ['Experiment', 'campaignName'] , 
                                                columns = ['os'] , 
                                                values =['% render rate', '% view',	'% ctr', 'impression', 'viewable_impression', 'click'])

                                     % render rate  % view   % ctr impression  \
os                                         android android android    android
Experiment   campaignName
Experiment-1 Exp1_HeroV2_TataNeu             80.37   74.23    0.28  1235236.0
Experiment-2 Exp2_HeroV2_TataNeu             76.94   75.00    0.04  1609017.0
Experiment-3 Exp2_HeroV2_TataNeu             82.01   77.83    0.21  1512501.0
             Urban Company Bangalore         82.53   80.10    0.56  1135607.0

                                     viewable_impression   click
os                                               android android
Experiment   campaignName
Experiment-1 Exp1_HeroV2_TataNeu                916891.0  2568.0
Experiment-2 Exp2_HeroV2_TataNeu               1206824.0   526.0
Experiment-3 Exp2_HeroV2_TataNeu               1177124.0  2512.0
             Urban Company Bangalore            909626.0  5106.0

In [74]:
display(get_funnel(df_data, ['Experiment', 'campaignName', 'yyyymmdd']))

,format,Experiment,campaignName,yyyymmdd,responses,impression,viewable_impression,click,% render rate,% view,% ctr
2,heroBannerV2,Experiment-1,Exp1_HeroV2_TataNeu,20250119,308269,249208,182981,560,80.84,73.43,0.31
3,heroBannerV2,Experiment-1,Exp1_HeroV2_TataNeu,20250120,309985,249442,185623,522,80.47,74.42,0.28
4,heroBannerV2,Experiment-1,Exp1_HeroV2_TataNeu,20250121,308642,246705,182847,504,79.93,74.12,0.28
1,heroBannerV2,Experiment-1,Exp1_HeroV2_TataNeu,20250118,306764,247421,184633,498,80.66,74.62,0.27
5,heroBannerV2,Experiment-1,Exp1_HeroV2_TataNeu,20250122,303250,242379,180758,484,79.93,74.58,0.27
0,heroBannerV2,Experiment-1,Exp1_HeroV2_TataNeu,20250117,90,81,49,0,90.00,60.49,0.00
7,heroBannerV2,Experiment-2,Exp2_HeroV2_TataNeu,20250124,287889,229817,171179,89,79.83,74.48,0.05
9,heroBannerV2,Experiment-2,Exp2_HeroV2_TataNeu,20250126,299580,217592,159638,78,72.63,73.37,0.05
6,heroBannerV2,Experiment-2,Exp2_HeroV2_TataNeu,20250123,288764,230328,171207,76,79.76,74.33,0.04
8,heroBannerV2,Experiment-2,Exp2_HeroV2_TataNeu,20250125,295176,213687,158669,61,72.39,74.25,0.04
10,heroBannerV2,Experiment-2,Exp2_HeroV2_TataNeu,20250127,307895,220694,164910,73,71.68,74.72,0.04
11,heroBannerV2,Experiment-2,Exp2_HeroV2_TataNeu,20250128,304114,246080,188255,71,80.92,76.50,0.04
12,heroBannerV2,Experiment-2,Exp2_HeroV2_TataNeu,20250129,307860,250819,192966,78,81.47,76.93,0.04
24,heroBannerV2,Experiment-3,Urban Company Bangalore,20250203,153305,128853,105995,970,84.05,82.26,0.92
14,heroBannerV2,Experiment-3,Exp2_HeroV2_TataNeu,20250131,310972,257741,212239,1564,82.88,82.35,0.74
22,heroBannerV2,Experiment-3,Urban Company Bangalore,20250201,239114,197677,159217,883,82.67,80.54,0.55
25,heroBannerV2,Experiment-3,Urban Company Bangalore,20250204,238494,196606,156288,831,82.44,79.49,0.53
21,heroBannerV2,Experiment-3,Urban Company Bangalore,20250131,245279,201863,161410,846,82.30,79.96,0.52
26,heroBannerV2,Experiment-3,Urban Company Bangalore,20250205,243591,200978,159731,800,82.51,79.48,0.50
20,heroBannerV2,Experiment-3,Urban Company Bangalore,20250130,256163,209612,166971,776,81.83,79.66,0.46
19,heroBannerV2,Experiment-3,Exp2_HeroV2_TataNeu,20250205,318091,266789,216360,617,83.87,81.10,0.29
15,heroBannerV2,Experiment-3,Exp2_HeroV2_TataNeu,20250201,299515,241865,183515,100,80.75,75.87,0.05
16,heroBannerV2,Experiment-3,Exp2_HeroV2_TataNeu,20250202,303441,247287,186126,85,81.49,75.27,0.05
17,heroBannerV2,Experiment-3,Exp2_HeroV2_TataNeu,20250203,303068,246217,186285,72,81.24,75.66,0.04
18,heroBannerV2,Experiment-3,Exp2_HeroV2_TataNeu,20250204,309187,252585,192587,74,81.69,76.25,0.04
13,heroBannerV2,Experiment-3,Exp2_HeroV2_TataNeu,20250130,19,17,12,0,89.47,70.59,0.00
23,heroBannerV2,Experiment-3,Urban Company Bangalore,20250202,26,18,14,0,69.23,77.78,0.00

In [75]:
display(get_funnel(df_data, ['Experiment', 'campaignName', 'slotUnitId']))

,format,Experiment,campaignName,slotUnitId,responses,impression,viewable_impression,click,% render rate,% view,% ctr
2,heroBannerV2,Experiment-1,Exp1_HeroV2_TataNeu,PostOrderStarted2,377491,297946,237042,1208,78.93,79.56,0.51
1,heroBannerV2,Experiment-1,Exp1_HeroV2_TataNeu,PostOrderOnTheWay2,814829,663489,451745,1011,81.43,68.09,0.22
0,heroBannerV2,Experiment-1,Exp1_HeroV2_TataNeu,PostOrderArrived2,344680,273801,228104,349,79.44,83.31,0.15
5,heroBannerV2,Experiment-2,Exp2_HeroV2_TataNeu,PostOrderStarted3,499504,374509,299872,236,74.98,80.07,0.08
4,heroBannerV2,Experiment-2,Exp2_HeroV2_TataNeu,PostOrderOnTheWay3,1116571,859955,593652,228,77.02,69.03,0.04
3,heroBannerV2,Experiment-2,Exp2_HeroV2_TataNeu,PostOrderArrived3,475203,374553,313300,62,78.82,83.65,0.02
10,heroBannerV2,Experiment-3,Urban Company Bangalore,PostOrderStarted3,480745,388961,342921,2733,80.91,88.16,0.80
9,heroBannerV2,Experiment-3,Urban Company Bangalore,PostOrderOnTheWay3,895227,746646,566705,2373,83.40,75.90,0.42
8,heroBannerV2,Experiment-3,Exp2_HeroV2_TataNeu,PostOrderStarted3,460013,373255,306768,956,81.14,82.19,0.31
7,heroBannerV2,Experiment-3,Exp2_HeroV2_TataNeu,PostOrderOnTheWay3,970699,807803,583076,1235,83.22,72.18,0.21
6,heroBannerV2,Experiment-3,Exp2_HeroV2_TataNeu,PostOrderArrived3,413581,331443,287280,321,80.14,86.68,0.11

In [76]:
display(get_funnel(df_data, ['Experiment', 'campaignName', 'service']))

,format,Experiment,campaignName,service,responses,impression,viewable_impression,click,% render rate,% view,% ctr
11,heroBannerV2,Experiment-1,Exp1_HeroV2_TataNeu,CabPremium,8232,6424,5184,52,78.04,80.70,1.00
2,heroBannerV2,Experiment-1,Exp1_HeroV2_TataNeu,Auto NCR,1450,1159,862,5,79.93,74.37,0.58
10,heroBannerV2,Experiment-1,Exp1_HeroV2_TataNeu,CabEconomy,398889,317314,231210,712,79.55,72.86,0.31
9,heroBannerV2,Experiment-1,Exp1_HeroV2_TataNeu,C2C,4097,3221,2325,7,78.62,72.18,0.30
6,heroBannerV2,Experiment-1,Exp1_HeroV2_TataNeu,Bike Lite,40495,33138,24675,72,81.83,74.46,0.29
0,heroBannerV2,Experiment-1,Exp1_HeroV2_TataNeu,Auto,473986,379414,281705,761,80.05,74.25,0.27
13,heroBannerV2,Experiment-1,Exp1_HeroV2_TataNeu,Link,589296,478048,358403,938,81.12,74.97,0.26
7,heroBannerV2,Experiment-1,Exp1_HeroV2_TataNeu,Bike Metro,18804,15116,11610,21,80.39,76.81,0.18
1,heroBannerV2,Experiment-1,Exp1_HeroV2_TataNeu,Auto C2C,173,128,85,0,73.99,66.41,0.00
3,heroBannerV2,Experiment-1,Exp1_HeroV2_TataNeu,Auto Pet,361,277,126,0,76.73,45.49,0.00
4,heroBannerV2,Experiment-1,Exp1_HeroV2_TataNeu,Auto Pool,7,7,7,0,100.00,100.00,0.00
5,heroBannerV2,Experiment-1,Exp1_HeroV2_TataNeu,AutoPremium,416,338,221,0,81.25,65.38,0.00
8,heroBannerV2,Experiment-1,Exp1_HeroV2_TataNeu,Bike Pink,39,30,22,0,76.92,73.33,0.00
12,heroBannerV2,Experiment-1,Exp1_HeroV2_TataNeu,E rickshaw,755,622,456,0,82.38,73.31,0.00
26,heroBannerV2,Experiment-2,Exp2_HeroV2_TataNeu,CabPremium,44546,33515,22981,136,75.24,68.57,0.59
25,heroBannerV2,Experiment-2,Exp2_HeroV2_TataNeu,CabEconomy,480608,361070,263513,93,75.13,72.98,0.04
14,heroBannerV2,Experiment-2,Exp2_HeroV2_TataNeu,Auto,582221,436898,329392,107,75.04,75.39,0.03
20,heroBannerV2,Experiment-2,Exp2_HeroV2_TataNeu,Bike Lite,62018,50790,38410,11,81.90,75.63,0.03
28,heroBannerV2,Experiment-2,Exp2_HeroV2_TataNeu,Link,885175,697582,530223,177,78.81,76.01,0.03
21,heroBannerV2,Experiment-2,Exp2_HeroV2_TataNeu,Bike Metro,26679,21441,16619,2,80.37,77.51,0.01
15,heroBannerV2,Experiment-2,Exp2_HeroV2_TataNeu,Auto C2C,314,253,188,0,80.57,74.31,0.00
16,heroBannerV2,Experiment-2,Exp2_HeroV2_TataNeu,Auto NCR,1219,996,720,0,81.71,72.29,0.00
17,heroBannerV2,Experiment-2,Exp2_HeroV2_TataNeu,Auto Pet,264,119,75,0,45.08,63.03,0.00
18,heroBannerV2,Experiment-2,Exp2_HeroV2_TataNeu,Auto Pool,3,3,3,0,100.00,100.00,0.00
19,heroBannerV2,Experiment-2,Exp2_HeroV2_TataNeu,AutoPremium,348,296,197,0,85.06,66.55,0.00
22,heroBannerV2,Experiment-2,Exp2_HeroV2_TataNeu,Bike Pink,105,82,62,0,78.10,75.61,0.00
23,heroBannerV2,Experiment-2,Exp2_HeroV2_TataNeu,C2C,6446,4913,3639,0,76.22,74.07,0.00
24,heroBannerV2,Experiment-2,Exp2_HeroV2_TataNeu,Cab SUV,285,233,166,0,81.75,71.24,0.00
27,heroBannerV2,Experiment-2,Exp2_HeroV2_TataNeu,E rickshaw,1047,826,636,0,78.89,77.00,0.00
49,heroBannerV2,Experiment-3,Urban Company Bangalore,CabPremium,15205,11892,9006,95,78.21,75.73,1.05
42,heroBannerV2,Experiment-3,Urban Company Bangalore,Auto C2C,755,625,527,4,82.78,84.32,0.76
50,heroBannerV2,Experiment-3,Urban Company Bangalore,Link,345966,288782,240779,1564,83.47,83.38,0.65
45,heroBannerV2,Experiment-3,Urban Company Bangalore,Bike Lite,65461,55132,45978,295,84.22,83.40,0.64
46,heroBannerV2,Experiment-3,Urban Company Bangalore,C2C,13170,10796,9446,56,81.97,87.50,0.59
43,heroBannerV2,Experiment-3,Urban Company Bangalore,Auto Pet,2344,2022,1441,8,86.26,71.27,0.56
47,heroBannerV2,Experiment-3,Urban Company Bangalore,Cab SUV,3662,3042,2308,12,83.07,75.87,0.52
41,heroBannerV2,Experiment-3,Urban Company Bangalore,Auto,801699,660187,518172,2656,82.35,78.49,0.51
48,heroBannerV2,Experiment-3,Urban Company Bangalore,CabEconomy,122749,99023,78794,404,80.67,79.57,0.51
39,heroBannerV2,Experiment-3,Exp2_HeroV2_TataNeu,E rickshaw,2259,1885,1438,7,83.44,76.29,0.49
38,heroBannerV2,Experiment-3,Exp2_HeroV2_TataNeu,CabPremium,26846,21566,15395,68,80.33,71.39,0.44
44,heroBannerV2,Experiment-3,Urban Company Bangalore,Auto Pool,4961,4106,3175,12,82.77,77.33,0.38
36,heroBannerV2,Experiment-3,Exp2_HeroV2_TataNeu,Cab SUV,2522,2015,1468,5,79.90,72.85,0.34
32,heroBannerV2,Experiment-3,Exp2_HeroV2_TataNeu,Bike Lite,133696,111810,90800,301,83.63,81.21,0.33
35,heroBannerV2,Experiment-3,Exp2_HeroV2_TataNeu,C2C,15349,12513,10240,32,81.52,81.83,0.31
34,heroBannerV2,Experiment-3,Exp2_HeroV2_TataNeu,Bike Pink,485,416,344,1,85.77,82.69,0.29
29,heroBannerV2,Experiment-3,Exp2_HeroV2_TataNeu,Auto,637226,523920,407304,1030,82.22,77.74,0.25
37,heroBannerV2,Experiment-3,Exp2_HeroV2_TataNeu,CabEconomy,270060,217452,163254,283,80.52,75.08,0.17
40,heroBannerV2,Experiment-3,Exp2_HeroV2_TataNeu,Link,728100,598157,468390,762,82.15,78.31,0.16
33,heroBannerV2,Experiment-3,Exp2_HeroV2_TataNeu,Bike Metro,26100,21420,17477,23,82.07,81.59,0.13
30,heroBannerV2,Experiment-3,Exp2_HeroV2_TataNeu,Auto C2C,1277,1043,812,0,81.68,77.85,0.00
31,heroBannerV2,Experiment-3,Exp2_HeroV2_TataNeu,AutoPremium,373,304,202,0,81.50,66.45,0.00

In [77]:
display(get_funnel(df_data, ['Experiment', 'campaignName', 'gender']))

,format,Experiment,campaignName,gender,responses,impression,viewable_impression,click,% render rate,% view,% ctr
3,heroBannerV2,Experiment-1,Exp1_HeroV2_TataNeu,UNKNOWN,135736,111869,81189,336,82.42,72.58,0.41
2,heroBannerV2,Experiment-1,Exp1_HeroV2_TataNeu,OTHERS,6246,5231,3597,14,83.75,68.76,0.39
0,heroBannerV2,Experiment-1,Exp1_HeroV2_TataNeu,FEMALE,307611,248961,186104,522,80.93,74.75,0.28
1,heroBannerV2,Experiment-1,Exp1_HeroV2_TataNeu,MALE,1087407,869175,646001,1696,79.93,74.32,0.26
7,heroBannerV2,Experiment-2,Exp2_HeroV2_TataNeu,UNKNOWN,163795,130323,95642,47,79.56,73.39,0.05
4,heroBannerV2,Experiment-2,Exp2_HeroV2_TataNeu,FEMALE,433361,334747,254139,94,77.24,75.92,0.04
5,heroBannerV2,Experiment-2,Exp2_HeroV2_TataNeu,MALE,1485363,1137018,852136,383,76.55,74.94,0.04
6,heroBannerV2,Experiment-2,Exp2_HeroV2_TataNeu,OTHERS,8759,6929,4907,2,79.11,70.82,0.04
15,heroBannerV2,Experiment-3,Urban Company Bangalore,UNKNOWN,77680,65480,51626,399,84.29,78.84,0.77
12,heroBannerV2,Experiment-3,Urban Company Bangalore,FEMALE,508198,420268,334252,2064,82.70,79.53,0.62
13,heroBannerV2,Experiment-3,Urban Company Bangalore,MALE,784118,644739,519786,2626,82.22,80.62,0.51
14,heroBannerV2,Experiment-3,Urban Company Bangalore,OTHERS,5976,5120,3962,17,85.68,77.38,0.43
8,heroBannerV2,Experiment-3,Exp2_HeroV2_TataNeu,FEMALE,465230,384907,302710,823,82.73,78.64,0.27
11,heroBannerV2,Experiment-3,Exp2_HeroV2_TataNeu,UNKNOWN,144423,120220,91002,215,83.24,75.70,0.24
10,heroBannerV2,Experiment-3,Exp2_HeroV2_TataNeu,OTHERS,6797,5702,4168,9,83.89,73.10,0.22
9,heroBannerV2,Experiment-3,Exp2_HeroV2_TataNeu,MALE,1227843,1001672,779244,1465,81.58,77.79,0.19

In [78]:
display(get_funnel(df_data, ['Experiment', 'campaignName', 'ltr_segment']))

,format,Experiment,campaignName,ltr_segment,responses,impression,viewable_impression,click,% render rate,% view,% ctr
1,heroBannerV2,Experiment-1,Exp1_HeroV2_TataNeu,NEW,106177,88154,63460,286,83.03,71.99,0.45
3,heroBannerV2,Experiment-1,Exp1_HeroV2_TataNeu,UNKNOWN,26853,22306,14806,59,83.07,66.38,0.40
0,heroBannerV2,Experiment-1,Exp1_HeroV2_TataNeu,HH,181661,147854,107697,383,81.39,72.84,0.36
2,heroBannerV2,Experiment-1,Exp1_HeroV2_TataNeu,PHH,1222309,976922,730928,1840,79.92,74.82,0.25
7,heroBannerV2,Experiment-2,Exp2_HeroV2_TataNeu,UNKNOWN,37354,29958,19500,15,80.20,65.09,0.08
4,heroBannerV2,Experiment-2,Exp2_HeroV2_TataNeu,HH,242651,191551,139534,89,78.94,72.84,0.06
5,heroBannerV2,Experiment-2,Exp2_HeroV2_TataNeu,NEW,123517,99547,72346,41,80.59,72.68,0.06
6,heroBannerV2,Experiment-2,Exp2_HeroV2_TataNeu,PHH,1687756,1287961,975444,381,76.31,75.74,0.04
13,heroBannerV2,Experiment-3,Urban Company Bangalore,NEW,45011,38418,30055,274,85.35,78.23,0.91
15,heroBannerV2,Experiment-3,Urban Company Bangalore,UNKNOWN,12249,10409,7304,64,84.98,70.17,0.88
12,heroBannerV2,Experiment-3,Urban Company Bangalore,HH,92206,77538,62384,458,84.09,80.46,0.73
14,heroBannerV2,Experiment-3,Urban Company Bangalore,PHH,1226506,1009242,809883,4310,82.29,80.25,0.53
9,heroBannerV2,Experiment-3,Exp2_HeroV2_TataNeu,NEW,107065,89531,67059,169,83.62,74.90,0.25
8,heroBannerV2,Experiment-3,Exp2_HeroV2_TataNeu,HH,197304,162258,123378,302,82.24,76.04,0.24
11,heroBannerV2,Experiment-3,Exp2_HeroV2_TataNeu,UNKNOWN,25985,21666,15206,34,83.38,70.18,0.22
10,heroBannerV2,Experiment-3,Exp2_HeroV2_TataNeu,PHH,1513939,1239046,971481,2007,81.84,78.41,0.21

In [79]:
display(get_funnel(df_data, ['Experiment', 'campaignName', 'retention_segments']))

,format,Experiment,campaignName,retention_segments,responses,impression,viewable_impression,click,% render rate,% view,% ctr
8,heroBannerV2,Experiment-1,Exp1_HeroV2_TataNeu,UNKNOWN,133030,110460,78266,345,83.03,70.85,0.44
4,heroBannerV2,Experiment-1,Exp1_HeroV2_TataNeu,INACTIVE,117273,94972,70251,259,80.98,73.97,0.37
3,heroBannerV2,Experiment-1,Exp1_HeroV2_TataNeu,HH,74987,60854,44202,147,81.15,72.64,0.33
0,heroBannerV2,Experiment-1,Exp1_HeroV2_TataNeu,DORMANT,251107,200864,149262,447,79.99,74.31,0.30
7,heroBannerV2,Experiment-1,Exp1_HeroV2_TataNeu,SILVER,119183,94967,71123,205,79.68,74.89,0.29
2,heroBannerV2,Experiment-1,Exp1_HeroV2_TataNeu,GOLD,222855,177961,132976,360,79.86,74.72,0.27
6,heroBannerV2,Experiment-1,Exp1_HeroV2_TataNeu,PRIME,11408,9091,6857,17,79.69,75.43,0.25
5,heroBannerV2,Experiment-1,Exp1_HeroV2_TataNeu,PLATINUM,275544,219749,164667,378,79.75,74.93,0.23
1,heroBannerV2,Experiment-1,Exp1_HeroV2_TataNeu,ELITE,331613,266318,199287,410,80.31,74.83,0.21
12,heroBannerV2,Experiment-2,Exp2_HeroV2_TataNeu,HH,111403,87643,63717,36,78.67,72.70,0.06
13,heroBannerV2,Experiment-2,Exp2_HeroV2_TataNeu,INACTIVE,140275,109958,81177,52,78.39,73.83,0.06
17,heroBannerV2,Experiment-2,Exp2_HeroV2_TataNeu,UNKNOWN,160871,129505,91846,56,80.50,70.92,0.06
9,heroBannerV2,Experiment-2,Exp2_HeroV2_TataNeu,DORMANT,303743,232831,174564,92,76.65,74.97,0.05
16,heroBannerV2,Experiment-2,Exp2_HeroV2_TataNeu,SILVER,156987,120342,90561,49,76.66,75.25,0.05
11,heroBannerV2,Experiment-2,Exp2_HeroV2_TataNeu,GOLD,307794,235366,177735,75,76.47,75.51,0.04
14,heroBannerV2,Experiment-2,Exp2_HeroV2_TataNeu,PLATINUM,392250,298293,226866,85,76.05,76.05,0.04
10,heroBannerV2,Experiment-2,Exp2_HeroV2_TataNeu,ELITE,500334,381666,289902,78,76.28,75.96,0.03
15,heroBannerV2,Experiment-2,Exp2_HeroV2_TataNeu,PRIME,17621,13413,10456,3,76.12,77.95,0.03
35,heroBannerV2,Experiment-3,Urban Company Bangalore,UNKNOWN,57260,48827,37359,338,85.27,76.51,0.90
31,heroBannerV2,Experiment-3,Urban Company Bangalore,INACTIVE,52262,43623,35414,290,83.47,81.18,0.82
30,heroBannerV2,Experiment-3,Urban Company Bangalore,HH,48192,40544,32540,222,84.13,80.26,0.68
27,heroBannerV2,Experiment-3,Urban Company Bangalore,DORMANT,143832,119298,97140,636,82.94,81.43,0.65
33,heroBannerV2,Experiment-3,Urban Company Bangalore,PRIME,13278,10828,8913,53,81.55,82.31,0.59
34,heroBannerV2,Experiment-3,Urban Company Bangalore,SILVER,74736,61595,50257,297,82.42,81.59,0.59
29,heroBannerV2,Experiment-3,Urban Company Bangalore,GOLD,178418,147398,119538,684,82.61,81.10,0.57
32,heroBannerV2,Experiment-3,Urban Company Bangalore,PLATINUM,290315,239247,193131,976,82.41,80.72,0.51
28,heroBannerV2,Experiment-3,Urban Company Bangalore,ELITE,517679,424247,335334,1610,81.95,79.04,0.48
21,heroBannerV2,Experiment-3,Exp2_HeroV2_TataNeu,HH,87521,71993,54862,147,82.26,76.20,0.27
26,heroBannerV2,Experiment-3,Exp2_HeroV2_TataNeu,UNKNOWN,133050,111197,82265,203,83.58,73.98,0.25
24,heroBannerV2,Experiment-3,Exp2_HeroV2_TataNeu,PRIME,13731,11094,8869,21,80.80,79.94,0.24
22,heroBannerV2,Experiment-3,Exp2_HeroV2_TataNeu,INACTIVE,126856,103942,79761,186,81.94,76.74,0.23
19,heroBannerV2,Experiment-3,Exp2_HeroV2_TataNeu,ELITE,430997,354548,278438,612,82.26,78.53,0.22
23,heroBannerV2,Experiment-3,Exp2_HeroV2_TataNeu,PLATINUM,354725,290111,228238,479,81.78,78.67,0.21
20,heroBannerV2,Experiment-3,Exp2_HeroV2_TataNeu,GOLD,274030,223893,175610,348,81.70,78.43,0.20
18,heroBannerV2,Experiment-3,Exp2_HeroV2_TataNeu,DORMANT,282300,230787,179303,347,81.75,77.69,0.19
25,heroBannerV2,Experiment-3,Exp2_HeroV2_TataNeu,SILVER,141083,114936,89778,169,81.47,78.11,0.19

In [80]:
display(get_funnel(df_data, ['Experiment', 'campaignName', 'regularity_segment']))

,format,Experiment,campaignName,regularity_segment,responses,impression,viewable_impression,click,% render rate,% view,% ctr
4,heroBannerV2,Experiment-1,Exp1_HeroV2_TataNeu,UNKNOWN,314691,258314,185963,728,82.08,71.99,0.39
3,heroBannerV2,Experiment-1,Exp1_HeroV2_TataNeu,RARE_NEED,165352,132299,98981,314,80.01,74.82,0.32
2,heroBannerV2,Experiment-1,Exp1_HeroV2_TataNeu,MONTHLY,156668,125357,94207,266,80.01,75.15,0.28
0,heroBannerV2,Experiment-1,Exp1_HeroV2_TataNeu,BI_WEEKLY,284728,227132,170173,443,79.77,74.92,0.26
5,heroBannerV2,Experiment-1,Exp1_HeroV2_TataNeu,WEEKLY,343799,273712,205336,496,79.61,75.02,0.24
1,heroBannerV2,Experiment-1,Exp1_HeroV2_TataNeu,DAILY,271762,218422,162231,321,80.37,74.27,0.20
9,heroBannerV2,Experiment-2,Exp2_HeroV2_TataNeu,RARE_NEED,209150,160571,121654,86,76.77,75.76,0.07
10,heroBannerV2,Experiment-2,Exp2_HeroV2_TataNeu,UNKNOWN,403522,321056,231380,145,79.56,72.07,0.06
6,heroBannerV2,Experiment-2,Exp2_HeroV2_TataNeu,BI_WEEKLY,384758,293843,222598,91,76.37,75.75,0.04
8,heroBannerV2,Experiment-2,Exp2_HeroV2_TataNeu,MONTHLY,202239,154842,117002,52,76.56,75.56,0.04
11,heroBannerV2,Experiment-2,Exp2_HeroV2_TataNeu,WEEKLY,480232,363836,276633,98,75.76,76.03,0.04
7,heroBannerV2,Experiment-2,Exp2_HeroV2_TataNeu,DAILY,411377,314869,237557,54,76.54,75.45,0.02
22,heroBannerV2,Experiment-3,Urban Company Bangalore,UNKNOWN,149466,126365,99743,796,84.54,78.93,0.80
21,heroBannerV2,Experiment-3,Urban Company Bangalore,RARE_NEED,105864,87945,71653,476,83.07,81.47,0.66
20,heroBannerV2,Experiment-3,Urban Company Bangalore,MONTHLY,107142,88426,72100,432,82.53,81.54,0.60
18,heroBannerV2,Experiment-3,Urban Company Bangalore,BI_WEEKLY,227587,188101,152313,882,82.65,80.97,0.58
23,heroBannerV2,Experiment-3,Urban Company Bangalore,WEEKLY,361603,297076,239219,1214,82.16,80.52,0.51
19,heroBannerV2,Experiment-3,Urban Company Bangalore,DAILY,424310,347694,274598,1306,81.94,78.98,0.48
16,heroBannerV2,Experiment-3,Exp2_HeroV2_TataNeu,UNKNOWN,330354,273455,205643,505,82.78,75.20,0.25
13,heroBannerV2,Experiment-3,Exp2_HeroV2_TataNeu,DAILY,329727,271522,212405,459,82.35,78.23,0.22
14,heroBannerV2,Experiment-3,Exp2_HeroV2_TataNeu,MONTHLY,190175,155098,121194,267,81.56,78.14,0.22
15,heroBannerV2,Experiment-3,Exp2_HeroV2_TataNeu,RARE_NEED,197752,161542,126465,271,81.69,78.29,0.21
17,heroBannerV2,Experiment-3,Exp2_HeroV2_TataNeu,WEEKLY,446602,364888,287299,581,81.70,78.74,0.20
12,heroBannerV2,Experiment-3,Exp2_HeroV2_TataNeu,BI_WEEKLY,349683,285996,224118,429,81.79,78.36,0.19

In [81]:
display(get_funnel(df_data, ['Experiment', 'campaignName', 'fe_regularity_segment']))

,format,Experiment,campaignName,fe_regularity_segment,responses,impression,viewable_impression,click,% render rate,% view,% ctr
4,heroBannerV2,Experiment-1,Exp1_HeroV2_TataNeu,UNKNOWN,340366,277050,203632,767,81.40,73.50,0.38
3,heroBannerV2,Experiment-1,Exp1_HeroV2_TataNeu,RARE_NEED,82809,66926,49015,156,80.82,73.24,0.32
2,heroBannerV2,Experiment-1,Exp1_HeroV2_TataNeu,MONTHLY,222492,178440,132604,398,80.20,74.31,0.30
0,heroBannerV2,Experiment-1,Exp1_HeroV2_TataNeu,BI_WEEKLY,365754,292048,217862,573,79.85,74.60,0.26
5,heroBannerV2,Experiment-1,Exp1_HeroV2_TataNeu,WEEKLY,226766,180782,135698,311,79.72,75.06,0.23
1,heroBannerV2,Experiment-1,Exp1_HeroV2_TataNeu,DAILY,298813,239990,178080,363,80.31,74.20,0.20
10,heroBannerV2,Experiment-2,Exp2_HeroV2_TataNeu,UNKNOWN,417577,328412,243326,172,78.65,74.09,0.07
9,heroBannerV2,Experiment-2,Exp2_HeroV2_TataNeu,RARE_NEED,115927,90175,66518,37,77.79,73.77,0.06
8,heroBannerV2,Experiment-2,Exp2_HeroV2_TataNeu,MONTHLY,297169,228458,170526,78,76.88,74.64,0.05
6,heroBannerV2,Experiment-2,Exp2_HeroV2_TataNeu,BI_WEEKLY,495514,378643,285964,107,76.41,75.52,0.04
11,heroBannerV2,Experiment-2,Exp2_HeroV2_TataNeu,WEEKLY,316987,240409,182491,65,75.84,75.91,0.04
7,heroBannerV2,Experiment-2,Exp2_HeroV2_TataNeu,DAILY,448104,342920,257999,67,76.53,75.24,0.03
22,heroBannerV2,Experiment-3,Urban Company Bangalore,UNKNOWN,177367,148537,119554,918,83.75,80.49,0.77
21,heroBannerV2,Experiment-3,Urban Company Bangalore,RARE_NEED,58122,48252,38683,257,83.02,80.17,0.66
20,heroBannerV2,Experiment-3,Urban Company Bangalore,MONTHLY,156966,130184,105165,644,82.94,80.78,0.61
18,heroBannerV2,Experiment-3,Urban Company Bangalore,BI_WEEKLY,299901,247460,199859,1095,82.51,80.76,0.55
23,heroBannerV2,Experiment-3,Urban Company Bangalore,WEEKLY,234539,192857,155298,818,82.23,80.52,0.53
19,heroBannerV2,Experiment-3,Urban Company Bangalore,DAILY,449077,368317,291067,1374,82.02,79.03,0.47
16,heroBannerV2,Experiment-3,Exp2_HeroV2_TataNeu,UNKNOWN,376088,309843,237143,550,82.39,76.54,0.23
13,heroBannerV2,Experiment-3,Exp2_HeroV2_TataNeu,DAILY,363207,299141,234105,512,82.36,78.26,0.22
14,heroBannerV2,Experiment-3,Exp2_HeroV2_TataNeu,MONTHLY,265565,217084,168827,371,81.74,77.77,0.22
12,heroBannerV2,Experiment-3,Exp2_HeroV2_TataNeu,BI_WEEKLY,444279,363070,284119,579,81.72,78.25,0.20
17,heroBannerV2,Experiment-3,Exp2_HeroV2_TataNeu,WEEKLY,297475,243266,191477,383,81.78,78.71,0.20
15,heroBannerV2,Experiment-3,Exp2_HeroV2_TataNeu,RARE_NEED,97679,80097,61453,117,82.00,76.72,0.19

In [82]:
display(get_funnel(df_data, ['Experiment', 'campaignName', 'income_segment']))

,format,Experiment,campaignName,income_segment,responses,impression,viewable_impression,click,% render rate,% view,% ctr
3,heroBannerV2,Experiment-1,Exp1_HeroV2_TataNeu,UNKNOWN,399929,319864,234221,809,79.98,73.23,0.35
2,heroBannerV2,Experiment-1,Exp1_HeroV2_TataNeu,MEDIUM_INCOME,481159,409883,310877,833,85.19,75.85,0.27
1,heroBannerV2,Experiment-1,Exp1_HeroV2_TataNeu,LOW_INCOME,81433,70527,53452,138,86.61,75.79,0.26
0,heroBannerV2,Experiment-1,Exp1_HeroV2_TataNeu,HIGH_INCOME,574479,434962,318341,788,75.71,73.19,0.25
7,heroBannerV2,Experiment-2,Exp2_HeroV2_TataNeu,UNKNOWN,517611,398078,295021,163,76.91,74.11,0.06
4,heroBannerV2,Experiment-2,Exp2_HeroV2_TataNeu,HIGH_INCOME,783527,564398,416591,170,72.03,73.81,0.04
5,heroBannerV2,Experiment-2,Exp2_HeroV2_TataNeu,LOW_INCOME,117432,97458,74111,27,82.99,76.04,0.04
6,heroBannerV2,Experiment-2,Exp2_HeroV2_TataNeu,MEDIUM_INCOME,672708,549083,421101,166,81.62,76.69,0.04
15,heroBannerV2,Experiment-3,Urban Company Bangalore,UNKNOWN,281741,229233,182771,1212,81.36,79.73,0.66
14,heroBannerV2,Experiment-3,Urban Company Bangalore,MEDIUM_INCOME,410207,361920,292288,1778,88.23,80.76,0.61
13,heroBannerV2,Experiment-3,Urban Company Bangalore,LOW_INCOME,68370,61083,49234,297,89.34,80.60,0.60
12,heroBannerV2,Experiment-3,Urban Company Bangalore,HIGH_INCOME,615654,483371,385333,1819,78.51,79.72,0.47
9,heroBannerV2,Experiment-3,Exp2_HeroV2_TataNeu,LOW_INCOME,99627,87194,68784,182,87.52,78.89,0.26
11,heroBannerV2,Experiment-3,Exp2_HeroV2_TataNeu,UNKNOWN,453458,367502,282098,667,81.04,76.76,0.24
10,heroBannerV2,Experiment-3,Exp2_HeroV2_TataNeu,MEDIUM_INCOME,597000,516002,408402,874,86.43,79.15,0.21
8,heroBannerV2,Experiment-3,Exp2_HeroV2_TataNeu,HIGH_INCOME,694208,541803,417840,789,78.05,77.12,0.19

In [83]:
display(get_funnel(df_data, ['Experiment', 'campaignName', 'service_affinity']))

,format,Experiment,campaignName,service_affinity,responses,impression,viewable_impression,click,% render rate,% view,% ctr
7,heroBannerV2,Experiment-1,Exp1_HeroV2_TataNeu,UNKNOWN,831450,669981,495667,1647,80.58,73.98,0.33
1,heroBannerV2,Experiment-1,Exp1_HeroV2_TataNeu,LINK_AUTO,40703,32898,24933,71,80.82,75.79,0.28
4,heroBannerV2,Experiment-1,Exp1_HeroV2_TataNeu,ONLY_AUTO,187133,148500,110964,287,79.36,74.72,0.26
0,heroBannerV2,Experiment-1,Exp1_HeroV2_TataNeu,AUTO_CAB,17062,13216,9738,21,77.46,73.68,0.22
2,heroBannerV2,Experiment-1,Exp1_HeroV2_TataNeu,LINK_CAB,10504,8557,6190,13,81.46,72.34,0.21
3,heroBannerV2,Experiment-1,Exp1_HeroV2_TataNeu,NO_AFFINITY,93241,74078,54367,116,79.45,73.39,0.21
5,heroBannerV2,Experiment-1,Exp1_HeroV2_TataNeu,ONLY_CAB,50931,39807,28737,61,78.16,72.19,0.21
6,heroBannerV2,Experiment-1,Exp1_HeroV2_TataNeu,ONLY_LINK,305976,248199,186295,352,81.12,75.06,0.19
10,heroBannerV2,Experiment-2,Exp2_HeroV2_TataNeu,LINK_CAB,14748,11684,8440,5,79.22,72.24,0.06
15,heroBannerV2,Experiment-2,Exp2_HeroV2_TataNeu,UNKNOWN,1069839,830306,618696,346,77.61,74.51,0.06
8,heroBannerV2,Experiment-2,Exp2_HeroV2_TataNeu,AUTO_CAB,22930,16574,12288,6,72.28,74.14,0.05
13,heroBannerV2,Experiment-2,Exp2_HeroV2_TataNeu,ONLY_CAB,74222,55816,40085,19,75.20,71.82,0.05
11,heroBannerV2,Experiment-2,Exp2_HeroV2_TataNeu,NO_AFFINITY,122831,90197,66762,24,73.43,74.02,0.04
9,heroBannerV2,Experiment-2,Exp2_HeroV2_TataNeu,LINK_AUTO,57706,43846,33721,9,75.98,76.91,0.03
12,heroBannerV2,Experiment-2,Exp2_HeroV2_TataNeu,ONLY_AUTO,267689,196660,148898,38,73.47,75.71,0.03
14,heroBannerV2,Experiment-2,Exp2_HeroV2_TataNeu,ONLY_LINK,461313,363934,277934,79,78.89,76.37,0.03
26,heroBannerV2,Experiment-3,Urban Company Bangalore,LINK_CAB,1693,1413,1171,13,83.46,82.87,1.11
31,heroBannerV2,Experiment-3,Urban Company Bangalore,UNKNOWN,475018,395179,319235,2151,83.19,80.78,0.67
24,heroBannerV2,Experiment-3,Urban Company Bangalore,AUTO_CAB,24747,19607,15351,87,79.23,78.29,0.57
25,heroBannerV2,Experiment-3,Urban Company Bangalore,LINK_AUTO,53703,44849,36488,209,83.51,81.36,0.57
30,heroBannerV2,Experiment-3,Urban Company Bangalore,ONLY_LINK,174869,146293,120867,671,83.66,82.62,0.56
29,heroBannerV2,Experiment-3,Urban Company Bangalore,ONLY_CAB,32528,25797,20227,101,79.31,78.41,0.50
27,heroBannerV2,Experiment-3,Urban Company Bangalore,NO_AFFINITY,111853,91915,73753,359,82.17,80.24,0.49
28,heroBannerV2,Experiment-3,Urban Company Bangalore,ONLY_AUTO,501561,410554,322534,1515,81.86,78.56,0.47
16,heroBannerV2,Experiment-3,Exp2_HeroV2_TataNeu,AUTO_CAB,19782,15623,12000,30,78.98,76.81,0.25
20,heroBannerV2,Experiment-3,Exp2_HeroV2_TataNeu,ONLY_AUTO,272845,223627,174638,439,81.96,78.09,0.25
21,heroBannerV2,Experiment-3,Exp2_HeroV2_TataNeu,ONLY_CAB,50171,39965,30165,72,79.66,75.48,0.24
18,heroBannerV2,Experiment-3,Exp2_HeroV2_TataNeu,LINK_CAB,10187,8321,6324,13,81.68,76.00,0.21
23,heroBannerV2,Experiment-3,Exp2_HeroV2_TataNeu,UNKNOWN,949686,778069,602101,1266,81.93,77.38,0.21
17,heroBannerV2,Experiment-3,Exp2_HeroV2_TataNeu,LINK_AUTO,57667,47626,37583,77,82.59,78.91,0.20
22,heroBannerV2,Experiment-3,Exp2_HeroV2_TataNeu,ONLY_LINK,401208,331875,262534,519,82.72,79.11,0.20
19,heroBannerV2,Experiment-3,Exp2_HeroV2_TataNeu,NO_AFFINITY,82747,67395,51779,96,81.45,76.83,0.19

In [84]:
display(get_funnel(df_data, ['Experiment', 'campaignName', 'gc_tag']))

,format,Experiment,campaignName,gc_tag,responses,impression,viewable_impression,click,% render rate,% view,% ctr
2,heroBannerV2,Experiment-1,Exp1_HeroV2_TataNeu,UNKNOWN,1226827,989524,733136,2146,80.66,74.09,0.29
1,heroBannerV2,Experiment-1,Exp1_HeroV2_TataNeu,NON_GC,285660,226145,168919,395,79.17,74.69,0.23
0,heroBannerV2,Experiment-1,Exp1_HeroV2_TataNeu,GC,24513,19567,14836,27,79.82,75.82,0.18
4,heroBannerV2,Experiment-2,Exp2_HeroV2_TataNeu,NON_GC,387649,293408,221812,87,75.69,75.60,0.04
5,heroBannerV2,Experiment-2,Exp2_HeroV2_TataNeu,UNKNOWN,1668105,1288163,963980,433,77.22,74.83,0.04
3,heroBannerV2,Experiment-2,Exp2_HeroV2_TataNeu,GC,35524,27446,21032,6,77.26,76.63,0.03
11,heroBannerV2,Experiment-3,Urban Company Bangalore,UNKNOWN,1126103,931967,744718,4304,82.76,79.91,0.58
9,heroBannerV2,Experiment-3,Urban Company Bangalore,GC,25456,20785,16741,90,81.65,80.54,0.54
10,heroBannerV2,Experiment-3,Urban Company Bangalore,NON_GC,224413,182855,148167,712,81.48,81.03,0.48
6,heroBannerV2,Experiment-3,Exp2_HeroV2_TataNeu,GC,30856,25280,20154,56,81.93,79.72,0.28
8,heroBannerV2,Experiment-3,Exp2_HeroV2_TataNeu,UNKNOWN,1452496,1193794,926620,2034,82.19,77.62,0.22
7,heroBannerV2,Experiment-3,Exp2_HeroV2_TataNeu,NON_GC,360941,293427,230350,422,81.30,78.50,0.18

#### Multivariate data

In [85]:
get_funnel(df_data, ['Experiment', 'slotUnitId', 'campaignName', 'os']).pivot(index = ['slotUnitId', 'Experiment', 'campaignName'] , 
                                                columns = ['os'] , 
                                                values =['% render rate', '% view',	'% ctr'])

                                                        % render rate  % view  \
os                                                            android android
slotUnitId         Experiment   campaignName
PostOrderArrived2  Experiment-1 Exp1_HeroV2_TataNeu             79.44   83.31
PostOrderArrived3  Experiment-2 Exp2_HeroV2_TataNeu             78.82   83.65
                   Experiment-3 Exp2_HeroV2_TataNeu             80.14   86.68
PostOrderOnTheWay2 Experiment-1 Exp1_HeroV2_TataNeu             81.43   68.09
PostOrderOnTheWay3 Experiment-2 Exp2_HeroV2_TataNeu             77.02   69.03
                   Experiment-3 Exp2_HeroV2_TataNeu             83.22   72.18
                                Urban Company Bangalore         83.40   75.90
PostOrderStarted2  Experiment-1 Exp1_HeroV2_TataNeu             78.93   79.56
PostOrderStarted3  Experiment-2 Exp2_HeroV2_TataNeu             74.98   80.07
                   Experiment-3 Exp2_HeroV2_TataNeu             81.14   82.19
                                Urban Company Bangalore         80.91   88.16

                                                          % ctr
os                                                      android
slotUnitId         Experiment   campaignName
PostOrderArrived2  Experiment-1 Exp1_HeroV2_TataNeu        0.15
PostOrderArrived3  Experiment-2 Exp2_HeroV2_TataNeu        0.02
                   Experiment-3 Exp2_HeroV2_TataNeu        0.11
PostOrderOnTheWay2 Experiment-1 Exp1_HeroV2_TataNeu        0.22
PostOrderOnTheWay3 Experiment-2 Exp2_HeroV2_TataNeu        0.04
                   Experiment-3 Exp2_HeroV2_TataNeu        0.21
                                Urban Company Bangalore    0.42
PostOrderStarted2  Experiment-1 Exp1_HeroV2_TataNeu        0.51
PostOrderStarted3  Experiment-2 Exp2_HeroV2_TataNeu        0.08
                   Experiment-3 Exp2_HeroV2_TataNeu        0.31
                                Urban Company Bangalore    0.80

In [86]:
display(get_funnel(df_data, ['Experiment', 'yyyymmdd', 'campaignName', 'slotUnitId']))

,format,Experiment,yyyymmdd,campaignName,slotUnitId,responses,impression,viewable_impression,click,% render rate,% view,% ctr
11,heroBannerV2,Experiment-1,20250120,Exp1_HeroV2_TataNeu,PostOrderStarted2,76107,59952,48204,255,78.77,80.40,0.53
14,heroBannerV2,Experiment-1,20250121,Exp1_HeroV2_TataNeu,PostOrderStarted2,75996,59921,47442,251,78.85,79.17,0.53
8,heroBannerV2,Experiment-1,20250119,Exp1_HeroV2_TataNeu,PostOrderStarted2,74963,59392,47102,239,79.23,79.31,0.51
17,heroBannerV2,Experiment-1,20250122,Exp1_HeroV2_TataNeu,PostOrderStarted2,74745,58754,46554,234,78.61,79.24,0.50
5,heroBannerV2,Experiment-1,20250118,Exp1_HeroV2_TataNeu,PostOrderStarted2,75663,59910,47727,229,79.18,79.66,0.48
7,heroBannerV2,Experiment-1,20250119,Exp1_HeroV2_TataNeu,PostOrderOnTheWay2,165695,135676,90853,245,81.88,66.96,0.27
4,heroBannerV2,Experiment-1,20250118,Exp1_HeroV2_TataNeu,PostOrderOnTheWay2,162179,132496,90925,197,81.70,68.62,0.22
10,heroBannerV2,Experiment-1,20250120,Exp1_HeroV2_TataNeu,PostOrderOnTheWay2,164947,134768,91716,197,81.70,68.05,0.21
13,heroBannerV2,Experiment-1,20250121,Exp1_HeroV2_TataNeu,PostOrderOnTheWay2,162654,131467,89499,189,80.83,68.08,0.21
16,heroBannerV2,Experiment-1,20250122,Exp1_HeroV2_TataNeu,PostOrderOnTheWay2,159296,129032,88726,183,81.00,68.76,0.21
6,heroBannerV2,Experiment-1,20250119,Exp1_HeroV2_TataNeu,PostOrderArrived2,67611,54140,45026,76,80.08,83.17,0.17
3,heroBannerV2,Experiment-1,20250118,Exp1_HeroV2_TataNeu,PostOrderArrived2,68922,55015,45981,72,79.82,83.58,0.16
9,heroBannerV2,Experiment-1,20250120,Exp1_HeroV2_TataNeu,PostOrderArrived2,68931,54722,45703,70,79.39,83.52,0.15
15,heroBannerV2,Experiment-1,20250122,Exp1_HeroV2_TataNeu,PostOrderArrived2,69209,54593,45478,67,78.88,83.30,0.15
12,heroBannerV2,Experiment-1,20250121,Exp1_HeroV2_TataNeu,PostOrderArrived2,69992,55317,45906,64,79.03,82.99,0.14
0,heroBannerV2,Experiment-1,20250117,Exp1_HeroV2_TataNeu,PostOrderArrived2,15,14,10,0,93.33,71.43,0.00
1,heroBannerV2,Experiment-1,20250117,Exp1_HeroV2_TataNeu,PostOrderOnTheWay2,58,50,26,0,86.21,52.00,0.00
2,heroBannerV2,Experiment-1,20250117,Exp1_HeroV2_TataNeu,PostOrderStarted2,17,17,13,0,100.00,76.47,0.00
29,heroBannerV2,Experiment-2,20250126,Exp2_HeroV2_TataNeu,PostOrderStarted3,70791,48942,38757,37,69.14,79.19,0.10
23,heroBannerV2,Experiment-2,20250124,Exp2_HeroV2_TataNeu,PostOrderStarted3,69506,55057,44018,38,79.21,79.95,0.09
20,heroBannerV2,Experiment-2,20250123,Exp2_HeroV2_TataNeu,PostOrderStarted3,70048,55409,44167,36,79.10,79.71,0.08
32,heroBannerV2,Experiment-2,20250127,Exp2_HeroV2_TataNeu,PostOrderStarted3,73241,49643,39842,31,67.78,80.26,0.08
26,heroBannerV2,Experiment-2,20250125,Exp2_HeroV2_TataNeu,PostOrderStarted3,70932,49009,38786,29,69.09,79.14,0.07
35,heroBannerV2,Experiment-2,20250128,Exp2_HeroV2_TataNeu,PostOrderStarted3,71897,57429,46548,31,79.88,81.05,0.07
38,heroBannerV2,Experiment-2,20250129,Exp2_HeroV2_TataNeu,PostOrderStarted3,73089,59020,47754,34,80.75,80.91,0.07
22,heroBannerV2,Experiment-2,20250124,Exp2_HeroV2_TataNeu,PostOrderOnTheWay3,151912,122344,83696,39,80.54,68.41,0.05
19,heroBannerV2,Experiment-2,20250123,Exp2_HeroV2_TataNeu,PostOrderOnTheWay3,152790,123151,84123,31,80.60,68.31,0.04
28,heroBannerV2,Experiment-2,20250126,Exp2_HeroV2_TataNeu,PostOrderOnTheWay3,161722,115953,77355,32,71.70,66.71,0.04
31,heroBannerV2,Experiment-2,20250127,Exp2_HeroV2_TataNeu,PostOrderOnTheWay3,164053,115848,79069,32,70.62,68.25,0.04
37,heroBannerV2,Experiment-2,20250129,Exp2_HeroV2_TataNeu,PostOrderOnTheWay3,164598,135646,97176,38,82.41,71.64,0.04
21,heroBannerV2,Experiment-2,20250124,Exp2_HeroV2_TataNeu,PostOrderArrived3,66471,52416,43465,12,78.86,82.92,0.03
25,heroBannerV2,Experiment-2,20250125,Exp2_HeroV2_TataNeu,PostOrderOnTheWay3,157843,112792,76895,26,71.46,68.17,0.03
34,heroBannerV2,Experiment-2,20250128,Exp2_HeroV2_TataNeu,PostOrderOnTheWay3,163653,134221,95338,30,82.02,71.03,0.03
18,heroBannerV2,Experiment-2,20250123,Exp2_HeroV2_TataNeu,PostOrderArrived3,65926,51768,42917,9,78.52,82.90,0.02
27,heroBannerV2,Experiment-2,20250126,Exp2_HeroV2_TataNeu,PostOrderArrived3,67067,52697,43526,9,78.57,82.60,0.02
30,heroBannerV2,Experiment-2,20250127,Exp2_HeroV2_TataNeu,PostOrderArrived3,70601,55203,45999,10,78.19,83.33,0.02
33,heroBannerV2,Experiment-2,20250128,Exp2_HeroV2_TataNeu,PostOrderArrived3,68564,54430,46369,10,79.39,85.19,0.02
24,heroBannerV2,Experiment-2,20250125,Exp2_HeroV2_TataNeu,PostOrderArrived3,66401,51886,42988,6,78.14,82.85,0.01
36,heroBannerV2,Experiment-2,20250129,Exp2_HeroV2_TataNeu,PostOrderArrived3,70173,56153,48036,6,80.02,85.54,0.01
63,heroBannerV2,Experiment-3,20250203,Urban Company Bangalore,PostOrderStarted3,56668,46822,41538,541,82.63,88.71,1.30
46,heroBannerV2,Experiment-3,20250131,Exp2_HeroV2_TataNeu,PostOrderStarted3,81037,66645,57331,534,82.24,86.02,0.93
53,heroBannerV2,Experiment-3,20250201,Urban Company Bangalore,PostOrderStarted3,85211,69069,60724,496,81.06,87.92,0.82
45,heroBannerV2,Experiment-3,20250131,Exp2_HeroV2_TataNeu,PostOrderOnTheWay3,160620,135289,103552,839,84.23,76.54,0.81
43,heroBannerV2,Experiment-3,20250130,Urban Company Bangalore,PostOrderStarted3,89116,71434,62843,474,80.16,87.97,0.75
48,heroBannerV2,Experiment-3,20250131,Urban Company Bangalore,PostOrderStarted3,85792,69303,60993,425,80.78,88.01,0.70
73,heroBannerV2,Experiment-3,20250205,Urban Company Bangalore,PostOrderStarted3,82579,66654,58841,404,80.72,88.28,0.69
68,heroBannerV2,Experiment-3,20250204,Urban Company Bangalore,PostOrderStarted3,81373,65676,57979,393,80.71,88.28,0.68
62,heroBannerV2,Experiment-3,20250203,Urban Company Bangalore,PostOrderOnTheWay3,96637,82031,64457,429,84.89,78.58,0.67
71,heroBannerV2,Experiment-3,20250205,Exp2_HeroV2_TataNeu,PostOrderStarted3,83819,69682,58487,293,83.13,83.93,0.50
67,heroBannerV2,Experiment-3,20250204,Urban Company Bangalore,PostOrderOnTheWay3,157121,130930,98309,438,83.33,75.09,0.45
47,heroBannerV2,Experiment-3,20250131,Urban Company Bangalore,PostOrderOnTheWay3,159487,132560,100417,421,83.12,75.75,0.42
52,heroBannerV2,Experiment-3,20250201,Urban Company Bangalore,PostOrderOnTheWay3,153903,128608,98493,387,83.56,76.58,0.39
72,heroBannerV2,Experiment-3,20250205,Urban Company Bangalore,PostOrderOnTheWay3,161012,134324,100890,396,83.42,75.11,0.39
44,heroBannerV2,Experiment-3,20250131,Exp2_HeroV2_TataNeu,PostOrderArrived3,69315,55807,51356,191,80.51,92.02,0.37
42,heroBannerV2,Experiment-3,20250130,Urban Company Bangalore,PostOrderOnTheWay3,167047,138178,104128,302,82.72,75.36,0.29
70,heroBannerV2,Experiment-3,20250205,Exp2_HeroV2_TataNeu,PostOrderOnTheWay3,160494,136870,103781,243,85.28,75.82,0.23
69,heroBannerV2,Experiment-3,20250205,Exp2_HeroV2_TataNeu,PostOrderArrived3,73778,60237,54092,81,81.65,89.80,0.15
51,heroBannerV2,Experiment-3,20250201,Exp2_HeroV2_TataNeu,PostOrderStarted3,72896,58258,47053,39,79.92,80.77,0.08
66,heroBannerV2,Experiment-3,20250204,Exp2_HeroV2_TataNeu,PostOrderStarted3,74335,59908,48442,36,80.59,80.86,0.07
61,heroBannerV2,Experiment-3,20250203,Exp2_HeroV2_TataNeu,PostOrderStarted3,73650,59089,47594,29,80.23,80.55,0.06
50,heroBannerV2,Experiment-3,20250201,Exp2_HeroV2_TataNeu,PostOrderOnTheWay3,159566,130338,91419,48,81.68,70.14,0.05
55,heroBannerV2,Experiment-3,20250202,Exp2_HeroV2_TataNeu,PostOrderOnTheWay3,162233,134114,93357,46,82.67,69.61,0.05
56,heroBannerV2,Experiment-3,20250202,Exp2_HeroV2_TataNeu,PostOrderStarted3,74271,59669,47857,25,80.34,80.20,0.05
49,heroBannerV2,Experiment-3,20250201,Exp2_HeroV2_TataNeu,PostOrderArrived3,67053,53269,45043,13,79.44,84.56,0.03
54,heroBannerV2,Experiment-3,20250202,Exp2_HeroV2_TataNeu,PostOrderArrived3,66937,53504,44912,14,79.93,83.94,0.03
59,heroBannerV2,Experiment-3,20250203,Exp2_HeroV2_TataNeu,PostOrderArrived3,67240,53441,45214,13,79.48,84.61,0.03
60,heroBannerV2,Experiment-3,20250203,Exp2_HeroV2_TataNeu,PostOrderOnTheWay3,162178,133687,93477,30,82.43,69.92,0.03
65,heroBannerV2,Experiment-3,20250204,Exp2_HeroV2_TataNeu,PostOrderOnTheWay3,165596,137494,97484,29,83.03,70.90,0.03
64,heroBannerV2,Experiment-3,20250204,Exp2_HeroV2_TataNeu,PostOrderArrived3,69256,55183,46661,9,79.68,84.56,0.02
39,heroBannerV2,Experiment-3,20250130,Exp2_HeroV2_TataNeu,PostOrderArrived3,2,2,2,0,100.00,100.00,0.00
40,heroBannerV2,Experiment-3,20250130,Exp2_HeroV2_TataNeu,PostOrderOnTheWay3,12,11,6,0,91.67,54.55,0.00
41,heroBannerV2,Experiment-3,20250130,Exp2_HeroV2_TataNeu,PostOrderStarted3,5,4,4,0,80.00,100.00,0.00
57,heroBannerV2,Experiment-3,20250202,Urban Company Bangalore,PostOrderOnTheWay3,20,15,11,0,75.00,73.33,0.00
58,heroBannerV2,Experiment-3,20250202,Urban Company Bangalore,PostOrderStarted3,6,3,3,0,50.00,100.00,0.00