## Imports

In [1]:
import os
import time
import glob
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import datetime as datetime

from scipy import stats
from pyhive import presto
from datetime import datetime, timedelta
from sklearn.tree import DecisionTreeRegressor, export_text

import warnings
warnings.filterwarnings('ignore')

In [2]:
pd.set_option('display.max_columns', 50)
pd.set_option('display.max_rows', 300)

In [3]:
## Connection
connection = presto.connect(
        host= 
    # 'processing.processing.data.production.internal',
    # 'processing-2.processing.data.production.internal',
    'presto-gateway.serving.data.production.internal',
        port=80,
        protocol='http',
        catalog='hive',
        username='manoj.ravirajan@rapido.bike'
)

In [4]:
print(os.getcwd())
local_dataset = '/Users/E2074/local-datasets/customer/geo-consistency'
print(local_dataset)

/Users/E2074/analytics/customer/segmentation/segment-appography
/Users/E2074/local-datasets/customer/geo-consistency

## Datasets & Parameter

In [5]:
city = 'Bangalore'
date_str = '20250316'

In [6]:
base_query = f"""

with funnel as (
    
    select 
        -- week_start_date,
        customerid as customer_id,
        SUM(cast(ao_session as int)) as ao_session,
        SUM(cast(fe_session as int)) as fe_session,
        SUM(cast(rr_session as int)) as rr_session
    from 
        hive.experiments_internal.customer_funnel_last90days_20250317
    where 
        week_start_date = '20250310'
    group by 1
    ),
    
    appo as (
    
    select 
        userid,
        deliveryFood,
        deliveryGrocery,
        driverApp,
        fantasySports,
        financeInvestment,
        gaming,
        health,
        homeSecurity,
        office,
        ott,
        streamingMusic,
        travelBookings,
        travelRidehailing
    
    from 
        reports.sql_ingestion_customer_appography_category_view 
    where 
        yyyymmdd = '20250330'
    ),

    segment as (

    select 
        customer_id, 
        segment  
    from 
        hive.experiments_internal.customer_segment_amj25
    )
    
    select
        funnel.customer_id,
        segment,
        deliveryFood,
        deliveryGrocery,
        driverApp,
        fantasySports,
        financeInvestment,
        gaming,
        health,
        homeSecurity,
        office,
        ott,
        streamingMusic,
        travelBookings,
        travelRidehailing,
        ao_session,
        fe_session,
        rr_session
    from 
        segment  
    join 
        appo
        on appo.userid = segment.customer_id
    left join 
        funnel
        on funnel.customer_id = segment.customer_id

"""

# df_base_query = pd.read_sql(base_query, connection)

In [8]:
print(df_base_query.shape)
display(df_base_query.head())

(4110361, 18)

,customer_id,segment,deliveryFood,deliveryGrocery,driverApp,fantasySports,financeInvestment,gaming,health,homeSecurity,office,ott,streamingMusic,travelBookings,travelRidehailing,ao_session,fe_session,rr_session
0,6291deea4480f6e8dbc5de3d,1-DAILY,1,1,0,0,1,1,1,1,1,1,1,1,1,251,154,170
1,639c7da3ad27b5845f899d1b,5-INACTIVE,1,1,0,0,1,0,0,0,1,1,1,1,1,0,0,0
2,63be17aafbf87ea29744f366,4-OTHER,1,1,0,0,1,1,1,1,1,1,1,1,1,1,1,1
3,670d0f854618974072145131,3-MONTHLY,0,0,0,0,0,0,0,0,1,0,1,0,1,18,14,11
4,5d0bba711c64cc470f65f803,3-MONTHLY,1,1,0,1,1,0,0,1,1,1,1,1,1,74,59,51

In [28]:
# df_base_query.to_parquet('prunning-dump.parquet', index=False)

In [7]:
df_base_query = pd.read_parquet('prunning-dump.parquet')
df_base_query.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4110361 entries, 0 to 4110360
Data columns (total 18 columns):
 #   Column             Dtype
---  ------             -----
 0   customer_id        object
 1   segment            object
 2   deliveryFood       int64
 3   deliveryGrocery    int64
 4   driverApp          int64
 5   fantasySports      int64
 6   financeInvestment  int64
 7   gaming             int64
 8   health             int64
 9   homeSecurity       int64
 10  office             int64
 11  ott                int64
 12  streamingMusic     int64
 13  travelBookings     int64
 14  travelRidehailing  int64
 15  ao_session         int64
 16  fe_session         int64
 17  rr_session         int64
dtypes: int64(16), object(2)
memory usage: 564.5+ MB

In [9]:
print(df_base_query.shape)
df_base_query.head(5)

(4110361, 18)

,customer_id,segment,deliveryFood,deliveryGrocery,driverApp,fantasySports,financeInvestment,gaming,health,homeSecurity,office,ott,streamingMusic,travelBookings,travelRidehailing,ao_session,fe_session,rr_session
0,6291deea4480f6e8dbc5de3d,1-DAILY,1,1,0,0,1,1,1,1,1,1,1,1,1,251,154,170
1,639c7da3ad27b5845f899d1b,5-INACTIVE,1,1,0,0,1,0,0,0,1,1,1,1,1,0,0,0
2,63be17aafbf87ea29744f366,4-OTHER,1,1,0,0,1,1,1,1,1,1,1,1,1,1,1,1
3,670d0f854618974072145131,3-MONTHLY,0,0,0,0,0,0,0,0,1,0,1,0,1,18,14,11
4,5d0bba711c64cc470f65f803,3-MONTHLY,1,1,0,1,1,0,0,1,1,1,1,1,1,74,59,51

In [10]:
def data_agg(df, column_list):
    df_temp = df\
                .groupby(column_list)\
                .agg(customers = ('customer_id', 'nunique'),
                     ao_session = ('ao_session', 'sum'),
                     fe_session = ('fe_session', 'sum'),
                     rr_session = ('rr_session', 'sum')
                    )\
                .reset_index()\
                .sort_values(by=column_list, ascending=False)

    df_temp['total_customer'] = df_base_query.customer_id.nunique()
    df_temp['cux_distr'] = round( df_temp['customers']*100.00/df_temp['total_customer'] ,0)
    df_temp['fe2rr'] = round( df_temp['rr_session']*100.00/df_temp['fe_session'] ,0)
    df_temp['ao2fe'] = round( df_temp['fe_session']*100.00/df_temp['ao_session'] ,0)
    df_temp['ao2rr'] = round( df_temp['rr_session']*100.00/df_temp['ao_session'] ,0)
    
    
    return df_temp

In [11]:
df_analysis = data_agg(df_base_query, ['travelRidehailing', 'deliveryFood', 'deliveryGrocery', 'travelBookings'])
df_analysis

,travelRidehailing,deliveryFood,deliveryGrocery,travelBookings,customers,ao_session,fe_session,rr_session,total_customer,cux_distr,fe2rr,ao2fe,ao2rr
15,1,1,1,1,1289720,26101172,21885470,15877072,4110361,31.0,73.0,84.0,61.0
14,1,1,1,0,372754,8345580,6875933,5040633,4110361,9.0,73.0,82.0,60.0
13,1,1,0,1,341141,4697872,3865916,2588676,4110361,8.0,67.0,82.0,55.0
12,1,1,0,0,126274,2301967,1854224,1321035,4110361,3.0,71.0,81.0,57.0
11,1,0,1,1,132369,1974000,1637011,974630,4110361,3.0,60.0,83.0,49.0
10,1,0,1,0,94066,1692770,1374577,907997,4110361,2.0,66.0,81.0,54.0
9,1,0,0,1,311653,4144182,3386932,1984136,4110361,8.0,59.0,82.0,48.0
8,1,0,0,0,198882,3307498,2639115,1707402,4110361,5.0,65.0,80.0,52.0
7,0,1,1,1,119076,1760530,1447975,932621,4110361,3.0,64.0,82.0,53.0
6,0,1,1,0,100633,1729871,1393493,979373,4110361,2.0,70.0,81.0,57.0
5,0,1,0,1,99647,1177672,954693,583898,4110361,2.0,61.0,81.0,50.0
4,0,1,0,0,77189,1178335,930887,633547,4110361,2.0,68.0,79.0,54.0
3,0,0,1,1,69336,877569,713039,403534,4110361,2.0,57.0,81.0,46.0
2,0,0,1,0,90979,1333643,1058197,677445,4110361,2.0,64.0,79.0,51.0
1,0,0,0,1,311276,3599249,2868442,1565776,4110361,8.0,55.0,80.0,44.0
0,0,0,0,0,375366,5257042,4076567,2536360,4110361,9.0,62.0,78.0,48.0

In [12]:
df_analysis = data_agg(df_base_query, ['travelRidehailing', 'deliveryFood', 'deliveryGrocery'])
df_analysis

,travelRidehailing,deliveryFood,deliveryGrocery,customers,ao_session,fe_session,rr_session,total_customer,cux_distr,fe2rr,ao2fe,ao2rr
7,1,1,1,1662474,34446752,28761403,20917705,4110361,40.0,73.0,83.0,61.0
6,1,1,0,467415,6999839,5720140,3909711,4110361,11.0,68.0,82.0,56.0
5,1,0,1,226435,3666770,3011588,1882627,4110361,6.0,63.0,82.0,51.0
4,1,0,0,510535,7451680,6026047,3691538,4110361,12.0,61.0,81.0,50.0
3,0,1,1,219709,3490401,2841468,1911994,4110361,5.0,67.0,81.0,55.0
2,0,1,0,176836,2356007,1885580,1217445,4110361,4.0,65.0,80.0,52.0
1,0,0,1,160315,2211212,1771236,1080979,4110361,4.0,61.0,80.0,49.0
0,0,0,0,686642,8856291,6945009,4102136,4110361,17.0,59.0,78.0,46.0

In [51]:
df_analysis.to_clipboard(index=False)

In [13]:
df_analysis = data_agg(df_base_query, ['travelRidehailing', 'deliveryFood', 'deliveryGrocery','financeInvestment'])
df_analysis

,travelRidehailing,deliveryFood,deliveryGrocery,financeInvestment,customers,ao_session,fe_session,rr_session,total_customer,cux_distr,fe2rr,ao2fe,ao2rr
15,1,1,1,1,1081763,22008283,18444700,13575556,4110361,26.0,74.0,84.0,62.0
14,1,1,1,0,580711,12438469,10316703,7342149,4110361,14.0,71.0,83.0,59.0
13,1,1,0,1,261864,3644085,2997264,2051570,4110361,6.0,68.0,82.0,56.0
12,1,1,0,0,205551,3355754,2722876,1858141,4110361,5.0,68.0,81.0,55.0
11,1,0,1,1,94161,1426933,1182687,731722,4110361,2.0,62.0,83.0,51.0
10,1,0,1,0,132274,2239837,1828901,1150905,4110361,3.0,63.0,82.0,51.0
9,1,0,0,1,190777,2494433,2039809,1238726,4110361,5.0,61.0,82.0,50.0
8,1,0,0,0,319758,4957247,3986238,2452812,4110361,8.0,62.0,80.0,49.0
7,0,1,1,1,89232,1311632,1075240,723667,4110361,2.0,67.0,82.0,55.0
6,0,1,1,0,130477,2178769,1766228,1188327,4110361,3.0,67.0,81.0,55.0
5,0,1,0,1,65583,784616,633833,411991,4110361,2.0,65.0,81.0,53.0
4,0,1,0,0,111253,1571391,1251747,805454,4110361,3.0,64.0,80.0,51.0
3,0,0,1,1,45273,575495,466343,282069,4110361,1.0,60.0,81.0,49.0
2,0,0,1,0,115042,1635717,1304893,798910,4110361,3.0,61.0,80.0,49.0
1,0,0,0,1,154889,1750700,1394476,829389,4110361,4.0,59.0,80.0,47.0
0,0,0,0,0,531753,7105591,5550533,3272747,4110361,13.0,59.0,78.0,46.0

In [38]:
# 'driverApp',	'fantasySports',	'gaming','health',	'homeSecurity',	'office',	'ott',	'streamingMusic'
df_analysis = data_agg(df_base_query, [ 'travelRidehailing', 'deliveryFood', 'deliveryGrocery', 'driverApp'	])
df_analysis

# 'travelRidehailing', 'deliveryFood', 'deliveryGrocery','financeInvestment'
# 'driverApp', 'office', 'homeSecurity', 'health'


# 'fantasySports',	'gaming', 'ott', 'streamingMusic'

,travelRidehailing,deliveryFood,deliveryGrocery,driverApp,customers,ao_session,fe_session,rr_session,total_customer,cux_distr,fe2rr,ao2fe,ao2rr
15,1,1,1,1,192222,3143602,2602959,1716441,4110361,5.0,66.0,83.0,55.0
14,1,1,1,0,1470252,31303150,26158444,19201264,4110361,36.0,73.0,84.0,61.0
13,1,1,0,1,60978,812361,662710,407105,4110361,1.0,61.0,82.0,50.0
12,1,1,0,0,406437,6187478,5057430,3502606,4110361,10.0,69.0,82.0,57.0
11,1,0,1,1,35961,506373,413320,233801,4110361,1.0,57.0,82.0,46.0
10,1,0,1,0,190474,3160397,2598268,1648826,4110361,5.0,63.0,82.0,52.0
9,1,0,0,1,69386,924928,755266,410707,4110361,2.0,54.0,82.0,44.0
8,1,0,0,0,441149,6526752,5270781,3280831,4110361,11.0,62.0,81.0,50.0
7,0,1,1,1,36024,458364,368893,227782,4110361,1.0,62.0,80.0,50.0
6,0,1,1,0,183685,3032037,2472575,1684212,4110361,4.0,68.0,82.0,56.0
5,0,1,0,1,24164,278492,221783,132052,4110361,1.0,60.0,80.0,47.0
4,0,1,0,0,152672,2077515,1663797,1085393,4110361,4.0,65.0,80.0,52.0
3,0,0,1,1,24543,279489,222738,123998,4110361,1.0,56.0,80.0,44.0
2,0,0,1,0,135772,1931723,1548498,956981,4110361,3.0,62.0,80.0,50.0
1,0,0,0,1,71799,826624,651465,362029,4110361,2.0,56.0,79.0,44.0
0,0,0,0,0,614843,8029667,6293544,3740107,4110361,15.0,59.0,78.0,47.0

In [15]:
def decision_tree(df, grouper):
    # 2. Define Features (App Category Flags) and Target (FE2R)
    X = df[grouper]
    y = df['fe2rr']

    # 3. Create Decision Tree Regressor
    tree_model = DecisionTreeRegressor(
        max_depth=5,     # limit depth so that tree is interpretable
        min_samples_leaf=2,  # minimum samples in each leaf
        random_state=42
    )
    
    # 4. Fit the model
    tree_model.fit(X, y)
    
    # 5. Visualize tree rules
    tree_rules = export_text(tree_model, feature_names=list(X.columns))
    print(tree_rules)

In [37]:
decision_tree(df_analysis, ['travelRidehailing', 'deliveryFood', 'deliveryGrocery','financeInvestment'])

|--- deliveryFood <= 0.50
|   |--- travelRidehailing <= 0.50
|   |   |--- deliveryGrocery <= 0.50
|   |   |   |--- value: [59.00]
|   |   |--- deliveryGrocery >  0.50
|   |   |   |--- value: [60.50]
|   |--- travelRidehailing >  0.50
|   |   |--- deliveryGrocery <= 0.50
|   |   |   |--- value: [61.50]
|   |   |--- deliveryGrocery >  0.50
|   |   |   |--- value: [62.50]
|--- deliveryFood >  0.50
|   |--- travelRidehailing <= 0.50
|   |   |--- deliveryGrocery <= 0.50
|   |   |   |--- value: [64.50]
|   |   |--- deliveryGrocery >  0.50
|   |   |   |--- value: [67.00]
|   |--- travelRidehailing >  0.50
|   |   |--- deliveryGrocery <= 0.50
|   |   |   |--- value: [68.00]
|   |   |--- deliveryGrocery >  0.50
|   |   |   |--- value: [72.50]

In [38]:
decision_tree(data_agg(df_base_query, ['travelRidehailing', 'deliveryFood', 'deliveryGrocery']), 
              ['travelRidehailing', 'deliveryFood', 'deliveryGrocery'])

|--- deliveryFood <= 0.50
|   |--- deliveryGrocery <= 0.50
|   |   |--- value: [60.00]
|   |--- deliveryGrocery >  0.50
|   |   |--- value: [62.00]
|--- deliveryFood >  0.50
|   |--- travelRidehailing <= 0.50
|   |   |--- value: [66.00]
|   |--- travelRidehailing >  0.50
|   |   |--- value: [70.50]

In [39]:
decision_tree(data_agg(df_base_query, ['travelRidehailing', 'deliveryFood', 'deliveryGrocery', 'travelBookings']), 
              ['travelRidehailing', 'deliveryFood', 'deliveryGrocery','travelBookings'])

|--- deliveryFood <= 0.50
|   |--- travelBookings <= 0.50
|   |   |--- travelRidehailing <= 0.50
|   |   |   |--- value: [63.00]
|   |   |--- travelRidehailing >  0.50
|   |   |   |--- value: [65.50]
|   |--- travelBookings >  0.50
|   |   |--- travelRidehailing <= 0.50
|   |   |   |--- value: [56.00]
|   |   |--- travelRidehailing >  0.50
|   |   |   |--- value: [59.50]
|--- deliveryFood >  0.50
|   |--- travelRidehailing <= 0.50
|   |   |--- travelBookings <= 0.50
|   |   |   |--- value: [69.00]
|   |   |--- travelBookings >  0.50
|   |   |   |--- value: [62.50]
|   |--- travelRidehailing >  0.50
|   |   |--- deliveryGrocery <= 0.50
|   |   |   |--- value: [69.00]
|   |   |--- deliveryGrocery >  0.50
|   |   |   |--- value: [73.00]

In [36]:
decision_tree(df_analysis, [  'office', 'homeSecurity', 'health'	])

|--- homeSecurity <= 0.50
|   |--- office <= 0.50
|   |   |--- health <= 0.50
|   |   |   |--- value: [59.50]
|   |   |--- health >  0.50
|   |   |   |--- value: [62.00]
|   |--- office >  0.50
|   |   |--- health <= 0.50
|   |   |   |--- value: [65.00]
|   |   |--- health >  0.50
|   |   |   |--- value: [69.50]
|--- homeSecurity >  0.50
|   |--- office <= 0.50
|   |   |--- health <= 0.50
|   |   |   |--- value: [69.00]
|   |   |--- health >  0.50
|   |   |   |--- value: [72.50]
|   |--- office >  0.50
|   |   |--- health <= 0.50
|   |   |   |--- value: [74.00]
|   |   |--- health >  0.50
|   |   |   |--- value: [80.00]

## Analysis

In [40]:
grouper = ['segment', 'travelRidehailing', 'deliveryFood', 'deliveryGrocery','financeInvestment']

df_analysis = data_agg(df_base_query, grouper).sort_values(by='segment', ascending=True)
df_analysis

,segment,travelRidehailing,deliveryFood,deliveryGrocery,financeInvestment,customers,ao_session,fe_session,rr_session,total_customer,cux_distr,fe2rr,ao2fe,ao2rr
0,1-DAILY,0,0,0,0,3770,585329,453556,386133,4110361,0.0,85.0,77.0,66.0
15,1-DAILY,1,1,1,1,32684,4532332,3744350,3364108,4110361,1.0,90.0,83.0,74.0
14,1-DAILY,1,1,1,0,18889,2759437,2262402,1982556,4110361,0.0,88.0,82.0,72.0
13,1-DAILY,1,1,0,1,3311,465608,376299,331292,4110361,0.0,88.0,81.0,71.0
12,1-DAILY,1,1,0,0,3823,564185,450637,390843,4110361,0.0,87.0,80.0,69.0
11,1-DAILY,1,0,1,1,1241,179757,146071,124469,4110361,0.0,85.0,81.0,69.0
10,1-DAILY,1,0,1,0,2286,345555,279972,233827,4110361,0.0,84.0,81.0,68.0
9,1-DAILY,1,0,0,1,1773,267001,212840,179697,4110361,0.0,84.0,80.0,67.0
1,1-DAILY,0,0,0,1,807,118426,92836,80424,4110361,0.0,87.0,78.0,68.0
7,1-DAILY,0,1,1,1,998,133002,107877,98150,4110361,0.0,91.0,81.0,74.0
6,1-DAILY,0,1,1,0,2053,294709,237402,212864,4110361,0.0,90.0,81.0,72.0
5,1-DAILY,0,1,0,1,489,68279,54271,49108,4110361,0.0,90.0,79.0,72.0
4,1-DAILY,0,1,0,0,1165,168369,133216,117239,4110361,0.0,88.0,79.0,70.0
3,1-DAILY,0,0,1,1,307,42698,34281,30296,4110361,0.0,88.0,80.0,71.0
2,1-DAILY,0,0,1,0,1083,158810,125480,108347,4110361,0.0,86.0,79.0,68.0
8,1-DAILY,1,0,0,0,4177,661010,523700,434420,4110361,0.0,83.0,79.0,66.0
31,2-WEEKLY,1,1,1,1,87753,5309413,4408320,3546169,4110361,2.0,80.0,83.0,67.0
30,2-WEEKLY,1,1,1,0,48143,2965973,2438739,1901924,4110361,1.0,78.0,82.0,64.0
29,2-WEEKLY,1,1,0,1,11586,686420,554071,439030,4110361,0.0,79.0,81.0,64.0
28,2-WEEKLY,1,1,0,0,10690,662833,531210,412563,4110361,0.0,78.0,80.0,62.0
27,2-WEEKLY,1,0,1,1,4179,258698,211460,155885,4110361,0.0,74.0,82.0,60.0
26,2-WEEKLY,1,0,1,0,6502,413016,334123,243256,4110361,0.0,73.0,81.0,59.0
24,2-WEEKLY,1,0,0,0,12057,799168,638567,463552,4110361,0.0,73.0,80.0,58.0
25,2-WEEKLY,1,0,0,1,6107,380019,305545,225216,4110361,0.0,74.0,80.0,59.0
22,2-WEEKLY,0,1,1,0,6680,397949,320133,253313,4110361,0.0,79.0,80.0,64.0
21,2-WEEKLY,0,1,0,1,1787,102127,81027,65358,4110361,0.0,81.0,79.0,64.0
19,2-WEEKLY,0,0,1,1,1308,77441,61515,47720,4110361,0.0,78.0,79.0,62.0
18,2-WEEKLY,0,0,1,0,3854,238618,189584,142476,4110361,0.0,75.0,79.0,60.0
17,2-WEEKLY,0,0,0,1,3140,190853,149736,114350,4110361,0.0,76.0,78.0,60.0
16,2-WEEKLY,0,0,0,0,12552,829040,647662,477628,4110361,0.0,74.0,78.0,58.0
23,2-WEEKLY,0,1,1,1,4023,229543,185411,149482,4110361,0.0,81.0,81.0,65.0
20,2-WEEKLY,0,1,0,0,3922,234189,185551,145591,4110361,0.0,78.0,79.0,62.0
39,3-MONTHLY,0,1,1,1,42517,747469,612915,398380,4110361,1.0,65.0,82.0,53.0
32,3-MONTHLY,0,0,0,0,190847,3865787,3031699,1767879,4110361,5.0,58.0,78.0,46.0
33,3-MONTHLY,0,0,0,1,54527,961870,766153,460688,4110361,1.0,60.0,80.0,48.0
34,3-MONTHLY,0,0,1,0,47984,914429,730319,434574,4110361,1.0,60.0,80.0,48.0
35,3-MONTHLY,0,0,1,1,19125,334514,270882,162510,4110361,0.0,60.0,81.0,49.0
36,3-MONTHLY,0,1,0,0,44155,839622,668044,417627,4110361,1.0,63.0,80.0,50.0
37,3-MONTHLY,0,1,0,1,24873,426310,343942,222569,4110361,1.0,65.0,81.0,52.0
38,3-MONTHLY,0,1,1,0,61619,1171175,949532,602814,4110361,1.0,63.0,81.0,51.0
40,3-MONTHLY,1,0,0,0,122943,2535530,2046320,1207066,4110361,3.0,59.0,81.0,48.0
42,3-MONTHLY,1,0,1,0,57833,1145364,936006,554935,4110361,1.0,59.0,82.0,48.0
43,3-MONTHLY,1,0,1,1,41049,758044,629273,371488,4110361,1.0,59.0,83.0,49.0
44,3-MONTHLY,1,1,0,0,85674,1620264,1318978,849656,4110361,2.0,64.0,81.0,52.0
45,3-MONTHLY,1,1,0,1,107678,1871217,1541867,1019162,4110361,3.0,66.0,82.0,54.0
46,3-MONTHLY,1,1,1,0,277798,5553709,4628419,2993946,4110361,7.0,65.0,83.0,54.0
47,3-MONTHLY,1,1,1,1,529238,10157662,8556757,5800068,4110361,13.0,68.0,84.0,57.0
41,3-MONTHLY,1,0,0,1,72293,1312548,1075266,641213,4110361,2.0,60.0,82.0,49.0
63,4-OTHER,1,1,1,1,314732,1825778,1558674,865211,4110361,8.0,56.0,85.0,47.0
62,4-OTHER,1,1,1,0,171057,1047392,880851,463723,4110361,4.0,53.0,84.0,44.0
60,4-OTHER,1,1,0,0,78533,464482,380592,205079,4110361,2.0,54.0,82.0,44.0
59,4-OTHER,1,0,1,1,34098,203863,170742,79880,4110361,1.0,47.0,84.0,39.0
58,4-OTHER,1,0,1,0,48306,301659,247323,118887,4110361,1.0,48.0,82.0,39.0
57,4-OTHER,1,0,0,1,81688,478511,393021,192600,4110361,2.0,49.0,82.0,40.0
56,4-OTHER,1,0,0,0,137505,877376,701022,347774,4110361,3.0,50.0,80.0,40.0
61,4-OTHER,1,1,0,1,103494,567132,473442,262086,4110361,3.0,55.0,83.0,46.0
54,4-OTHER,0,1,1,0,46091,288753,234901,119336,4110361,1.0,51.0,81.0,41.0
53,4-OTHER,0,1,0,1,29931,174239,141760,74956,4110361,1.0,53.0,81.0,43.0
52,4-OTHER,0,1,0,0,48669,305911,243580,124997,4110361,1.0,51.0,80.0,41.0
51,4-OTHER,0,0,1,1,18327,108605,88432,41543,4110361,0.0,47.0,81.0,38.0
50,4-OTHER,0,0,1,0,48132,295943,234259,113513,4110361,1.0,48.0,79.0,38.0
49,4-OTHER,0,0,0,1,75419,441453,350596,173927,4110361,2.0,50.0,79.0,39.0
48,4-OTHER,0,0,0,0,261759,1698238,1305818,641107,4110361,6.0,49.0,77.0,38.0
55,4-OTHER,0,1,1,1,31320,183057,151537,77655,4110361,1.0,51.0,83.0,42.0
78,5-INACTIVE,1,1,1,0,64824,111958,106292,0,4110361,2.0,0.0,95.0,0.0
77,5-INACTIVE,1,1,0,1,35795,53708,51585,0,4110361,1.0,0.0,96.0,0.0
76,5-INACTIVE,1,1,0,0,26831,43990,41459,0,4110361,1.0,0.0,94.0,0.0
75,5-INACTIVE,1,0,1,1,13594,26571,25141,0,4110361,0.0,0.0,95.0,0.0
74,5-INACTIVE,1,0,1,0,17347,34243,31477,0,4110361,0.0,0.0,92.0,0.0
73,5-INACTIVE,1,0,0,1,28916,56354,53137,0,4110361,1.0,0.0,94.0,0.0
72,5-INACTIVE,1,0,0,0,43076,84163,76629,0,4110361,1.0,0.0,91.0,0.0
68,5-INACTIVE,0,1,0,0,13342,23300,21356,0,4110361,0.0,0.0,92.0,0.0
70,5-INACTIVE,0,1,1,0,14034,26183,24260,0,4110361,0.0,0.0,93.0,0.0
69,5-INACTIVE,0,1,0,1,8503,13661,12833,0,4110361,0.0,0.0,94.0,0.0
67,5-INACTIVE,0,0,1,1,6206,12237,11233,0,4110361,0.0,0.0,92.0,0.0
66,5-INACTIVE,0,0,1,0,13989,27917,25251,0,4110361,0.0,0.0,90.0,0.0
65,5-INACTIVE,0,0,0,1,20996,38098,35155,0,4110361,1.0,0.0,92.0,0.0
64,5-INACTIVE,0,0,0,0,62825,127197,111798,0,4110361,2.0,0.0,88.0,0.0
71,5-INACTIVE,0,1,1,1,10374,18561,17500,0,4110361,0.0,0.0,94.0,0.0
79,5-INACTIVE,1,1,1,1,117356,183098,176599,0,4110361,3.0,0.0,96.0,0.0

In [39]:
grouper = ['travelRidehailing', 'deliveryFood', 'deliveryGrocery', 'driverApp']

df_analysis = data_agg(df_base_query, grouper)
df_analysis

,travelRidehailing,deliveryFood,deliveryGrocery,driverApp,customers,ao_session,fe_session,rr_session,total_customer,cux_distr,fe2rr,ao2fe,ao2rr
15,1,1,1,1,192222,3143602,2602959,1716441,4110361,5.0,66.0,83.0,55.0
14,1,1,1,0,1470252,31303150,26158444,19201264,4110361,36.0,73.0,84.0,61.0
13,1,1,0,1,60978,812361,662710,407105,4110361,1.0,61.0,82.0,50.0
12,1,1,0,0,406437,6187478,5057430,3502606,4110361,10.0,69.0,82.0,57.0
11,1,0,1,1,35961,506373,413320,233801,4110361,1.0,57.0,82.0,46.0
10,1,0,1,0,190474,3160397,2598268,1648826,4110361,5.0,63.0,82.0,52.0
9,1,0,0,1,69386,924928,755266,410707,4110361,2.0,54.0,82.0,44.0
8,1,0,0,0,441149,6526752,5270781,3280831,4110361,11.0,62.0,81.0,50.0
7,0,1,1,1,36024,458364,368893,227782,4110361,1.0,62.0,80.0,50.0
6,0,1,1,0,183685,3032037,2472575,1684212,4110361,4.0,68.0,82.0,56.0
5,0,1,0,1,24164,278492,221783,132052,4110361,1.0,60.0,80.0,47.0
4,0,1,0,0,152672,2077515,1663797,1085393,4110361,4.0,65.0,80.0,52.0
3,0,0,1,1,24543,279489,222738,123998,4110361,1.0,56.0,80.0,44.0
2,0,0,1,0,135772,1931723,1548498,956981,4110361,3.0,62.0,80.0,50.0
1,0,0,0,1,71799,826624,651465,362029,4110361,2.0,56.0,79.0,44.0
0,0,0,0,0,614843,8029667,6293544,3740107,4110361,15.0,59.0,78.0,47.0

In [42]:
grouper = ['segment', 'travelRidehailing', 'deliveryFood', 'deliveryGrocery']

df_analysis = data_agg(df_base_query, grouper).sort_values(by=['segment','travelRidehailing', 'deliveryFood', 'deliveryGrocery'], ascending=[True, False, False, False])
df_analysis

,segment,travelRidehailing,deliveryFood,deliveryGrocery,customers,ao_session,fe_session,rr_session,total_customer,cux_distr,fe2rr,ao2fe,ao2rr
7,1-DAILY,1,1,1,51573,7291769,6006752,5346664,4110361,1.0,89.0,82.0,73.0
6,1-DAILY,1,1,0,7134,1029793,826936,722135,4110361,0.0,87.0,80.0,70.0
5,1-DAILY,1,0,1,3527,525312,426043,358296,4110361,0.0,84.0,81.0,68.0
4,1-DAILY,1,0,0,5950,928011,736540,614117,4110361,0.0,83.0,79.0,66.0
3,1-DAILY,0,1,1,3051,427711,345279,311014,4110361,0.0,90.0,81.0,73.0
2,1-DAILY,0,1,0,1654,236648,187487,166347,4110361,0.0,89.0,79.0,70.0
1,1-DAILY,0,0,1,1390,201508,159761,138643,4110361,0.0,87.0,79.0,69.0
0,1-DAILY,0,0,0,4577,703755,546392,466557,4110361,0.0,85.0,78.0,66.0
15,2-WEEKLY,1,1,1,135896,8275386,6847059,5448093,4110361,3.0,80.0,83.0,66.0
14,2-WEEKLY,1,1,0,22276,1349253,1085281,851593,4110361,1.0,78.0,80.0,63.0
13,2-WEEKLY,1,0,1,10681,671714,545583,399141,4110361,0.0,73.0,81.0,59.0
12,2-WEEKLY,1,0,0,18164,1179187,944112,688768,4110361,0.0,73.0,80.0,58.0
11,2-WEEKLY,0,1,1,10703,627492,505544,402795,4110361,0.0,80.0,81.0,64.0
10,2-WEEKLY,0,1,0,5709,336316,266578,210949,4110361,0.0,79.0,79.0,63.0
9,2-WEEKLY,0,0,1,5162,316059,251099,190196,4110361,0.0,76.0,79.0,60.0
8,2-WEEKLY,0,0,0,15692,1019893,797398,591978,4110361,0.0,74.0,78.0,58.0
23,3-MONTHLY,1,1,1,807036,15711371,13185176,8794014,4110361,20.0,67.0,84.0,56.0
22,3-MONTHLY,1,1,0,193352,3491481,2860845,1868818,4110361,5.0,65.0,82.0,54.0
21,3-MONTHLY,1,0,1,98882,1903408,1565279,926423,4110361,2.0,59.0,82.0,49.0
20,3-MONTHLY,1,0,0,195236,3848078,3121586,1848279,4110361,5.0,59.0,81.0,48.0
19,3-MONTHLY,0,1,1,104136,1918644,1562447,1001194,4110361,3.0,64.0,81.0,52.0
18,3-MONTHLY,0,1,0,69028,1265932,1011986,640196,4110361,2.0,63.0,80.0,51.0
17,3-MONTHLY,0,0,1,67109,1248943,1001201,597084,4110361,2.0,60.0,80.0,48.0
16,3-MONTHLY,0,0,0,245374,4827657,3797852,2228567,4110361,6.0,59.0,79.0,46.0
31,4-OTHER,1,1,1,485789,2873170,2439525,1328934,4110361,12.0,54.0,85.0,46.0
30,4-OTHER,1,1,0,182027,1031614,854034,467165,4110361,4.0,55.0,83.0,45.0
29,4-OTHER,1,0,1,82404,505522,418065,198767,4110361,2.0,48.0,83.0,39.0
28,4-OTHER,1,0,0,219193,1355887,1094043,540374,4110361,5.0,49.0,81.0,40.0
27,4-OTHER,0,1,1,77411,471810,386438,196991,4110361,2.0,51.0,82.0,42.0
26,4-OTHER,0,1,0,78600,480150,385340,199953,4110361,2.0,52.0,80.0,42.0
25,4-OTHER,0,0,1,66459,404548,322691,155056,4110361,2.0,48.0,80.0,38.0
24,4-OTHER,0,0,0,337178,2139691,1656414,815034,4110361,8.0,49.0,77.0,38.0
39,5-INACTIVE,1,1,1,182180,295056,282891,0,4110361,4.0,0.0,96.0,0.0
38,5-INACTIVE,1,1,0,62626,97698,93044,0,4110361,2.0,0.0,95.0,0.0
37,5-INACTIVE,1,0,1,30941,60814,56618,0,4110361,1.0,0.0,93.0,0.0
36,5-INACTIVE,1,0,0,71992,140517,129766,0,4110361,2.0,0.0,92.0,0.0
35,5-INACTIVE,0,1,1,24408,44744,41760,0,4110361,1.0,0.0,93.0,0.0
34,5-INACTIVE,0,1,0,21845,36961,34189,0,4110361,1.0,0.0,93.0,0.0
33,5-INACTIVE,0,0,1,20195,40154,36484,0,4110361,0.0,0.0,91.0,0.0
32,5-INACTIVE,0,0,0,83821,165295,146953,0,4110361,2.0,0.0,89.0,0.0

### All category