In [3]:
import os
import h3 as h3
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import datetime as datetime

from scipy import stats
from pyhive import presto
from keplergl import KeplerGl
from datetime import datetime, timedelta

import warnings
warnings.filterwarnings('ignore')

In [4]:
pd.set_option('display.max_columns', 50)
pd.set_option('display.max_rows', 300)

In [5]:
## Connection
connection = presto.connect(
        host='presto-gateway.serving.data.production.internal',
        port=80,
        protocol='http',
        catalog='hive',
        username='manoj.ravirajan@rapido.bike'
)## Parameter

## Requirement 

### Userbase CSV for this Campaign


		a. Cities -> Hyderabad/Kolkata/Bangalore
        b. Condition → Users who do not have age present in our system and are 90->21 days active in above cities.

In [50]:
## Userbase_Age_Campaign


Userbase_Age_Campaign = f"""

        WITH order_logs_snapshot AS (

            SELECT
                city_name,
                customer_id,
                customer_obj_mobile customer_mobile
            FROM 
                orders.order_logs_snapshot
            WHERE 
                yyyymmdd >= '20231017' 
                AND yyyymmdd <= '20231106'
                -- yyyymmdd >= DATE_FORMAT(CURRENT_DATE - INTERVAL '21' DAY, '%Y%m%d') 
                -- 20230916 & 20231006
                AND city_name IN ('Hyderabad', 'Kolkata', 'Bangalore')
                AND service_obj_service_name IN ('Link', 'Auto') --, 'Auto Pool', 'CabEconomy')
                AND order_id IS NOT NULL
                AND order_status = 'dropped'
                AND (spd_fraud_flag is null or spd_fraud_flag=false)
            GROUP BY 1,2,3
            ),

            iallocator_customer_metrics AS (

            SELECT 
                run_date,
                customer_id,
                CASE 
                WHEN (cast(year_of_birth as int) BETWEEN 1940 AND 2015) THEN (2023 - cast(year_of_birth as int))
                END age

            FROM 
                datasets.iallocator_customer_metrics 
            WHERE 
                run_date = '2023-11-05'
                -- run_date = DATE_FORMAT( CURRENT_DATE - INTERVAL '2' day, '%Y-%m-%d')
                -- 20231005
            ),

            customer_metrics AS (

            select 
                CASE 
                WHEN age < 18 THEN 'Below 18'
                WHEN age >= 18 AND age <= 25 THEN '18 to 25'
                WHEN age >= 26 AND age <= 40 THEN '26 to 40'
                WHEN age >= 41 AND age <= 55 THEN '41 to 55'
                WHEN age > 55 THEN '55 +'
                WHEN age IS NULL THEN 'Unknown'
                END age,
                customer_id
            from 
                iallocator_customer_metrics
            ),

            customer_single_view AS (

            select 
                customerId 
            from 
                datasets.customer_single_view 
            where 
                dateOfBirth is null 
                and registrationCity IN ('hyderabad', 'kolkata', 'bangalore')
            )

            SELECT
                -- city_name,
                COALESCE(ols.customer_id, cm.customer_id, cs.customerId) customer_id,
                customer_mobile
            FROM 
                order_logs_snapshot ols 
            JOIN 
                customer_metrics cm 
                ON ols.customer_id = cm.customer_id
                AND age = 'Unknown' 

            JOIN 
                customer_single_view cs
                ON ols.customer_id = cs.customerId
            GROUP BY 1,2
"""

df_Userbase_Age_Campaign = pd.read_sql(Userbase_Age_Campaign, connection)
df_Userbase_Age_Campaign.head()

                      customer_id customer_mobile
0        6258fd22c4bf3a515ce6d486      9640416868
1        63553d2534b53750bf6ce638      7406968570
2        653289bd6ddedf69b3bd9386      9390997407
3        629a062eac45453d305fde54      7339531344
4        623602246b6b6469c9714d40      6305023049
...                           ...             ...
1648879  6528c063c61c341a897aeb64      9449462040
1648880  630dba0d23c71f4d250d19e3      9440911675
1648881  61cc25db4004b94cb874c074      9515450148
1648882  63cbf608e58e9c70b12d6bb9      8660944032
1648883  627b939cc75b90d272075d68      7993434542

[1648884 rows x 2 columns]

In [53]:
df_Age_Campaign_Result.to_csv(data_path + 'campaign/df_Userbase_Age_Campaign_v1.csv')

In [14]:
## old

df_Userbase_Age_Campaign.shape

(1673005, 2)

In [15]:
df_Userbase_Age_Campaign[['customer_id','customer_mobile']].to_csv('Userbase_Age_Campaign_Active_21days_Ban_Hyd_Kol.csv', index=False)

90 days gross customer - 8272625 <br>
90 days dropped customer - 6872783 <br>
21 days dropped customer - 1692599 <br>
14 days dropped customer - 1294295 <br>

In [115]:
os.getcwd()
current_path = os.getcwd()

data_path = """/Users/rapido/local-datasets/customer/Ads-Monetisation/experiment-dump/"""
data_path

'/Users/rapido/local-datasets/customer/Ads-Monetisation/experiment-dump/'

In [116]:
df_Userbase_Age_Campaign = pd.read_csv(data_path + 
                                       'Userbase_Age_Campaign_Active_21days_Ban_Hyd_Kol.csv')

## Sent -> Imp -> Clicked

In [105]:
start_date = '20231107'
end_date = '20231114'
campaign_id = '1699432148'

In [106]:
## customer_notification_sent_immutable
notification_sent = f"""
                        
    select 
        identity profile_identity,
        phone profile_phone,
        campaign_id,
        campaign_name,
        identity || phone unique_id_notification_sent
    from 
        clevertap.customer_notification_sent_immutable
    where 
        yyyymmdd >= '{start_date}' 
        and yyyymmdd <= '{end_date}'
        and campaign_id = '{campaign_id}'
    group by 1,2,3,4,5  
                            
"""

df_notification_sent = pd.read_sql(notification_sent, connection)


## customer_push_impressions_immutable
push_impressions = f"""
                        
    select 
        profile_identity,
        profile_phone,
        profile_identity || profile_phone unique_id_push_impressions
    from 
        clevertap.customer_push_impressions_immutable 
    where 
        yyyymmdd >= '{start_date}' 
        and yyyymmdd <= '{end_date}'
        and event_props_wzrk_pid = '{campaign_id}'
    group by 1,2,3 
                            
"""

df_push_impressions = pd.read_sql(push_impressions, connection)

## customer_notification_clicked_immutable
notification_clicked = f"""
                        
    select 
        profile_identity,
        profile_phone,
        profile_identity || profile_phone unique_id_notification_clicked
    from 
        clevertap.customer_notification_clicked_immutable 
    where 
        yyyymmdd >= '{start_date}' 
        and yyyymmdd <= '{end_date}'
        and event_props_campaign_id = '{campaign_id}'
    group by 1,2,3
                            
"""

df_notification_clicked = pd.read_sql(notification_clicked, connection)

In [107]:
df_notification_sent['profile_identity'] = df_notification_sent['profile_identity'].str.split(',')
df_notification_sent = df_notification_sent.explode('profile_identity')
df_notification_sent.to_csv(data_path + 'campaign/df_notification_sent.csv')

df_push_impressions['profile_identity'] = df_push_impressions['profile_identity'].str.split(',')
df_push_impressions = df_push_impressions.explode('profile_identity')
df_push_impressions.to_csv(data_path + 'campaign/df_push_impressions.csv')

df_notification_clicked['profile_identity'] = df_notification_clicked['profile_identity'].str.split(',')
df_notification_clicked = df_notification_clicked.explode('profile_identity')
df_notification_clicked.to_csv(data_path + 'campaign/df_notification_clicked.csv')

profile_identity_columns_lists = df_notification_clicked['profile_identity'].dropna().tolist()
profile_identity_columns_lists = tuple(profile_identity_columns_lists)

In [108]:
## customer_single_view
customer_single_view = f"""
    select 
        customerId,
        dateOfBirth 
    from 
        datasets.customer_single_view 
    where 
        customerId IN {profile_identity_columns_lists}
        and dateOfBirth is not null
"""

df_customer_single_view = pd.read_sql(customer_single_view, connection)

In [109]:
df_customer_single_view.to_csv(data_path + 'campaign/df_customer_single_view.csv')

In [110]:
print(df_notification_sent.shape)
print(df_push_impressions.shape)
print(df_notification_clicked.shape)
print(df_customer_single_view.shape)

(751972, 5)
(495741, 3)
(3167, 3)
(191, 2)

In [111]:
df_push_impressions['profile_identity_imp'] = df_push_impressions['profile_identity']
df_push_impressions['profile_phone_imp'] = df_push_impressions['profile_phone']
df_notification_clicked['profile_identity_click'] = df_notification_clicked['profile_identity']
df_notification_clicked['profile_phone_click'] = df_notification_clicked['profile_phone']


df_sent_imp = pd.merge(df_notification_sent,
                       df_push_impressions,
                       how='left',
                       on=['profile_identity', 'profile_phone']
                      )

df_pn_merge = pd.merge(df_sent_imp,
                       df_notification_clicked,
                       how='left',
                       left_on=['profile_identity_imp', 'profile_phone_imp'],
                       right_on=['profile_identity', 'profile_phone'] 
                      )

df_pn_merge = df_pn_merge[['campaign_id', 'campaign_name', 
                 'profile_identity_x', 'profile_phone_x', 'unique_id_notification_sent',
                 'profile_identity_imp', 'profile_phone_imp', 'unique_id_push_impressions',
                 'profile_identity_click', 'profile_phone_click' , 'unique_id_notification_clicked']]

In [112]:
df_pn_final = pd.merge(df_pn_merge,
                       df_customer_single_view,
                       how='left',
                       left_on='profile_identity_click',
                       right_on='customerId'
                      )
df_pn_final.head()

,campaign_id,campaign_name,profile_identity_x,profile_phone_x,unique_id_notification_sent,profile_identity_imp,profile_phone_imp,unique_id_push_impressions,profile_identity_click,profile_phone_click,unique_id_notification_clicked,customerId,dateOfBirth
0,1699432148,PN_Age_Signal_Wednesday_English_Nov_08,64e20dd92ec04378bd98959b,919849817724,64e20dd92ec04378bd98959b919849817724,NaN,NaN,NaN,None,None,None,NaN,NaN
1,1699432148,PN_Age_Signal_Wednesday_English_Nov_08,634543ed630369646e3fb29b,919894062445,634543ed630369646e3fb29b919894062445,NaN,NaN,NaN,None,None,None,NaN,NaN
2,1699432148,PN_Age_Signal_Wednesday_English_Nov_08,649f0c220ec724d526b53b01,919848883945,649f0c220ec724d526b53b01919848883945,649f0c220ec724d526b53b01,919848883945,649f0c220ec724d526b53b01919848883945,NaN,NaN,NaN,NaN,NaN
3,1699432148,PN_Age_Signal_Wednesday_English_Nov_08,63778fb2386d4c2a028248d4,918276932014,63778fb2386d4c2a028248d4918276932014,63778fb2386d4c2a028248d4,918276932014,63778fb2386d4c2a028248d4918276932014,NaN,NaN,NaN,NaN,NaN
4,1699432148,PN_Age_Signal_Wednesday_English_Nov_08,62ac1a79523c18b36bb3ef89,919949590866,62ac1a79523c18b36bb3ef89919949590866,62ac1a79523c18b36bb3ef89,919949590866,62ac1a79523c18b36bb3ef89919949590866,NaN,NaN,NaN,NaN,NaN

In [130]:
df_pn_funnel = df_pn_final \
                    .groupby(['campaign_id', 'campaign_name']) \
                    .agg(pn_sent = pd.NamedAgg('unique_id_notification_sent', 'nunique'),
                         pn_imp = pd.NamedAgg('unique_id_push_impressions', 'nunique'),
                         pn_click = pd.NamedAgg('unique_id_notification_clicked', 'nunique'),
                         dbo_added = pd.NamedAgg('customerId', 'nunique')
                        ) \
                    .reset_index()

df_pn_funnel['base_shared'] = df_Userbase_Age_Campaign.customer_mobile.nunique()
df_pn_funnel['sent_to_imp %'] = df_pn_funnel['pn_imp']*100.00/df_pn_funnel['pn_sent']
df_pn_funnel['imp_to_click %'] = df_pn_funnel['pn_click']*100.00/df_pn_funnel['pn_imp']
df_pn_funnel['click_to_added %'] = df_pn_funnel['dbo_added']*100.00/df_pn_funnel['pn_click']
df_pn_funnel = df_pn_funnel[['campaign_id', 'campaign_name', 'base_shared', 
                             'pn_sent', 'pn_imp', 'pn_click', 'dbo_added', 
                             'sent_to_imp %', 'imp_to_click %', 'click_to_added %']]

In [131]:
df_pn_funnel.round(2)

,campaign_id,campaign_name,base_shared,pn_sent,pn_imp,pn_click,dbo_added,sent_to_imp %,imp_to_click %,click_to_added %
0,1699432148,PN_Age_Signal_Wednesday_English_Nov_08,1673005,702968,465606,2367,142,66.23,0.51,6.0

In [132]:
702968/1673005

0.42018284464182715

## Other check

In [117]:
df_Userbase_Age_Campaign

                      customer_id  customer_mobile
0        64fb030c588b8835b433ca3f       7675024468
1        6411414e3fdc1cb30a2b2231       8123563210
2        64f2f29234850c0e9a4610da       9844190433
3        61fa87606916b8b146b18e53       9573750907
4        61a60d220d37fd2d374b1c10       9676030266
...                           ...              ...
1673000  6336aa48e90ec6448d7ad4e3       9538698894
1673001  615973e577c7e65990901667       7032089979
1673002  636c8f996a828365bde43e8c       9494229468
1673003  63287744747b4180e1b369ee       8919551890
1673004  6532e4feefd5eab4bc1debf3       9749441059

[1673005 rows x 2 columns]

In [120]:
df_notification_sent

,profile_identity,profile_phone,campaign_id,campaign_name,unique_id_notification_sent
0,64e20dd92ec04378bd98959b,919849817724,1699432148,PN_Age_Signal_Wednesday_English_Nov_08,64e20dd92ec04378bd98959b919849817724
1,634543ed630369646e3fb29b,919894062445,1699432148,PN_Age_Signal_Wednesday_English_Nov_08,634543ed630369646e3fb29b919894062445
2,649f0c220ec724d526b53b01,919848883945,1699432148,PN_Age_Signal_Wednesday_English_Nov_08,649f0c220ec724d526b53b01919848883945
3,63778fb2386d4c2a028248d4,918276932014,1699432148,PN_Age_Signal_Wednesday_English_Nov_08,63778fb2386d4c2a028248d4918276932014
4,62ac1a79523c18b36bb3ef89,919949590866,1699432148,PN_Age_Signal_Wednesday_English_Nov_08,62ac1a79523c18b36bb3ef89919949590866
...,...,...,...,...,...
708797,624d251adc05efc0793d3e67,917207727711,1699432148,PN_Age_Signal_Wednesday_English_Nov_08,624d251adc05efc0793d3e67917207727711
708798,62dd18ffb88548e2354ba281,917989856050,1699432148,PN_Age_Signal_Wednesday_English_Nov_08,62dd18ffb88548e2354ba281917989856050
708799,6290efc8e5106f60d19e8f74,918016229517,1699432148,PN_Age_Signal_Wednesday_English_Nov_08,6290efc8e5106f60d19e8f74918016229517
708800,6108e84adf98a55f2d8917ce,919581040000,1699432148,PN_Age_Signal_Wednesday_English_Nov_08,"6108e84adf98a55f2d8917ce,614033128709d217b79c7..."
708800,614033128709d217b79c7b81,919581040000,1699432148,PN_Age_Signal_Wednesday_English_Nov_08,"6108e84adf98a55f2d8917ce,614033128709d217b79c7..."

In [125]:
df_test = pd.merge(df_Userbase_Age_Campaign,
                   df_notification_sent,
                   how='left',
                   left_on='customer_id',
                   right_on='profile_identity'
                  )
df_test

,customer_id,customer_mobile,new_customer_id,profile_identity,profile_phone,campaign_id,campaign_name,unique_id_notification_sent
0,64fb030c588b8835b433ca3f,7675024468,[64fb030c588b8835b433ca3f],NaN,NaN,NaN,NaN,NaN
1,6411414e3fdc1cb30a2b2231,8123563210,[6411414e3fdc1cb30a2b2231],6411414e3fdc1cb30a2b2231,918123563210,1699432148,PN_Age_Signal_Wednesday_English_Nov_08,6411414e3fdc1cb30a2b2231918123563210
2,64f2f29234850c0e9a4610da,9844190433,[64f2f29234850c0e9a4610da],64f2f29234850c0e9a4610da,919844190433,1699432148,PN_Age_Signal_Wednesday_English_Nov_08,64f2f29234850c0e9a4610da919844190433
3,61fa87606916b8b146b18e53,9573750907,[61fa87606916b8b146b18e53],NaN,NaN,NaN,NaN,NaN
4,61a60d220d37fd2d374b1c10,9676030266,[61a60d220d37fd2d374b1c10],NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
1673000,6336aa48e90ec6448d7ad4e3,9538698894,[6336aa48e90ec6448d7ad4e3],NaN,NaN,NaN,NaN,NaN
1673001,615973e577c7e65990901667,7032089979,[615973e577c7e65990901667],NaN,NaN,NaN,NaN,NaN
1673002,636c8f996a828365bde43e8c,9494229468,[636c8f996a828365bde43e8c],NaN,NaN,NaN,NaN,NaN
1673003,63287744747b4180e1b369ee,8919551890,[63287744747b4180e1b369ee],NaN,NaN,NaN,NaN,NaN
1673004,6532e4feefd5eab4bc1debf3,9749441059,[6532e4feefd5eab4bc1debf3],NaN,NaN,NaN,NaN,NaN

In [127]:
df_test.agg({'customer_id':'nunique',
             'customer_mobile':'nunique',
             'profile_phone' : 'nunique'
            })

customer_id        1673005
customer_mobile    1673005
profile_phone       702664
dtype: int64

In [133]:
df_pn_final.groupby(['dateOfBirth']).agg({'customerId':'nunique'})

             customerId
dateOfBirth
1901-03-15            1
1956-01-31            1
1971-04-24            1
1974-01-04            1
1975-04-08            1
1975-07-24            1
1979-06-01            1
1979-06-12            1
1980-06-15            2
1980-08-30            1
1982-02-04            1
1982-06-12            1
1983-01-20            1
1983-05-11            1
1983-08-26            1
1983-08-31            1
1984-01-01            1
1985-05-02            1
1985-07-18            1
1986-03-22            1
1986-06-13            1
1986-07-10            1
1986-08-15            2
1987-01-09            1
1987-06-16            1
1987-07-01            1
1988-01-19            1
1988-02-25            1
1988-08-26            1
1989-01-19            1
1989-06-09            1
1989-09-29            1
1989-10-10            1
1989-11-15            1
1990-04-04            1
1990-06-11            1
1990-07-16            1
1990-09-29            1
1990-11-07            1
1990-12-07            1
1991-01-10            1
1991-07-10            1
1991-09-07            1
1991-10-10            1
1992-03-12            1
1992-06-06            1
1992-07-25            1
1992-08-15            1
1992-11-30            1
1993-01-04            1
1993-06-06            1
1993-06-08            1
1993-06-15            1
1993-07-02            1
1993-07-18            2
1993-10-04            1
1993-11-11            1
1994-05-23            1
1994-07-12            1
1994-08-06            1
1994-11-23            1
1994-12-08            1
1995-04-03            1
1995-04-24            1
1995-04-27            1
1995-05-15            1
1995-06-08            1
1995-06-15            1
1995-06-25            1
1995-07-19            1
1995-07-23            1
1995-12-23            1
1996-06-19            2
1996-08-01            1
1996-09-21            1
1997-01-14            1
1997-04-29            1
1997-06-08            1
1997-06-12            1
1997-08-28            1
1997-11-10            1
1998-03-04            1
1998-03-06            1
1998-03-17            1
1998-05-23            1
1998-06-25            1
1998-06-26            1
1998-07-27            1
1998-10-22            1
1998-12-01            1
1999-04-20            1
1999-07-12            1
1999-10-23            1
1999-11-06            1
2000-02-05            1
2000-04-20            1
2000-05-10            1
2000-08-09            1
2000-08-10            1
2001-01-01            1
2001-01-02            1
2001-02-18            1
2001-06-14            1
2001-07-24            1
2001-08-09            1
2001-08-27            1
2001-10-14            1
2001-11-11            1
2001-12-20            1
2001-12-27            1
2002-01-16            1
2002-03-16            1
2002-07-13            1
2002-09-03            1
2003-04-06            1
2004-03-07            1
2004-04-07            1
2004-11-21            1
2005-06-15            1
2005-08-14            1
2006-04-03            1
2007-02-26            1
2007-03-30            1
2007-07-01            1
2007-10-26            1
2008-09-30            1
2008-10-31            1
2009-03-15            1
2011-08-01            1
2011-11-08            8
2018-03-25            1

## Age and gender ad-hoc

In [6]:
ad_hoc_query = """

        WITH 
            iallocator_customer_metrics AS (

            SELECT 
                run_date,
                customer_id,
                CASE 
                WHEN (cast(year_of_birth as int) BETWEEN 1940 AND 2015) THEN (2023 - cast(year_of_birth as int))
                END age

            FROM 
                datasets.iallocator_customer_metrics 
            WHERE 
                run_date = '2023-11-24'
                -- run_date = DATE_FORMAT( CURRENT_DATE - INTERVAL '2' day, '%Y-%m-%d')
                -- 20231005
                
                AND customer_id = '6288c6694281e53bbe33d133'
                
            ),

            customer_metrics AS (

            select 
                CASE 
                WHEN age < 18 THEN 'Below 18'
                WHEN age >= 18 AND age <= 25 THEN '18 to 25'
                WHEN age >= 26 AND age <= 40 THEN '26 to 40'
                WHEN age >= 41 AND age <= 55 THEN '41 to 55'
                WHEN age > 55 THEN '55 +'
                WHEN age IS NULL THEN 'Unknown'
                END age,
                customer_id
            from 
                iallocator_customer_metrics
            ),

            customer_single_view AS (

            select 
                customerId,
                gender
            from 
                datasets.customer_single_view 
            where 
                dateOfBirth is null 
                AND customerId = '6288c6694281e53bbe33d133'
                -- and registrationCity IN ('hyderabad', 'kolkata', 'bangalore')
            )

            SELECT
            
                *
                
            FROM 
                customer_metrics cm 
            JOIN 
                customer_single_view cs
                ON cm.customer_id = cs.customerId

"""

In [7]:
df_ad_hoc_query = pd.read_sql(ad_hoc_query, connection)
df_ad_hoc_query.head()

DatabaseError: Execution failed on sql:

        WITH
            iallocator_customer_metrics AS (

            SELECT
                run_date,
                customer_id,
                CASE
                WHEN (cast(year_of_birth as int) BETWEEN 1940 AND 2015) THEN (2023 - cast(year_of_birth as int))
                END age

            FROM
                datasets.iallocator_customer_metrics
            WHERE
                run_date = '2023-11-24'
                -- run_date = DATE_FORMAT( CURRENT_DATE - INTERVAL '2' day, '%Y-%m-%d')
                -- 20231005

                AND customer_id = '6288c6694281e53bbe33d133'

            ),

            customer_metrics AS (

            select
                CASE
                WHEN age < 18 THEN 'Below 18'
                WHEN age >= 18 AND age <= 25 THEN '18 to 25'
                WHEN age >= 26 AND age <= 40 THEN '26 to 40'
                WHEN age >= 41 AND age <= 55 THEN '41 to 55'
                WHEN age > 55 THEN '55 +'
                WHEN age IS NULL THEN 'Unknown'
                END age,
                customer_id
            from
                iallocator_customer_metrics
            ),

            customer_single_view AS (

            select
                customerId,
                gender
            from
                datasets.customer_single_view
            where
                dateOfBirth is null
                AND customerId = '6288c6694281e53bbe33d133'
                -- and registrationCity IN ('hyderabad', 'kolkata', 'bangalore')
            )

            SELECT

                *

            FROM
                customer_metrics cm
            JOIN
                customer_single_view cs
                ON cm.customer_id = cs.customerId


Unexpected status code 503
b'no healthy upstream'
unable to rollback