## Imports

In [1]:
import glob
import os
import re
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import datetime as datetime

import time

from scipy import stats
from pyhive import presto
from datetime import datetime, timedelta

import warnings
warnings.filterwarnings('ignore')

In [2]:
pd.set_option('display.max_columns', 50)
pd.set_option('display.max_rows', 300)

In [3]:
## Connection
connection = presto.connect(
        host='processing-2.processing.data.production.internal' ,
    # 'presto-gateway.serving.data.production.internal',
        port=80,
        protocol='http',
        catalog='hive',
        username='manoj.ravirajan@rapido.bike'
)

presto_port = '80'
username = 'manoj.ravirajan@rapido.bike'
conn1 = presto.connect('bi-presto.serving.data.production.internal', presto_port, username)
conn2 = presto.connect('bi-trino-2.serving.data.production.internal', presto_port, username)
conn3= presto.connect('processing-2.processing.data.production.internal',presto_port,username)
conn4= presto.connect('processing.processing.data.production.internal',presto_port,username)

In [4]:
local_path = '/Users/E2074/local-datasets/customer/segmentation/consideration/'
local_path

'/Users/E2074/local-datasets/customer/segmentation/consideration/'

In [5]:
city = 'bangalore'
city_name = 'Bangalore'

## Ignore following steps and go to <b>Customer Segment</b> Section directly

## Datasets & Parameter

In [6]:
start_date = datetime.strptime("2025-03-03", "%Y-%m-%d")

run_date = [(start_date + timedelta(weeks=i)).strftime("%Y-%m-%d") for i in range(10)]
run_date

['2025-03-03',
 '2025-03-10',
 '2025-03-17',
 '2025-03-24',
 '2025-03-31',
 '2025-04-07',
 '2025-04-14',
 '2025-04-21',
 '2025-04-28',
 '2025-05-05']

In [7]:
def get_segment_customer_base(run_date):
    start_time = time.time()

    ltr_segment = ['HH', 'PHH']
    df_list = []
    
    for segment in ltr_segment:
        base_query = f"""
    
            with base as (
                select 
                    customer_id,
                    taxi_ltr_segment,
                    -- taxi_lifetime_rides,
                    date_diff( 'day', DATE(taxi_lifetime_first_ride_date), DATE(DATE_PARSE(run_date, '%Y-%m-%d'))) rapido_firstride_age
                from 
                    datasets.iallocator_customer_segments
                where 
                    run_date = date_format(date('{run_date}'), '%Y-%m-%d')
                    and taxi_lifetime_last_ride_city = '{city_name}'
                    and taxi_ltr_segment = '{segment}'
                ),
                
                active_week as (
                
                select
                    customerid,
                    91 max_active_days,
                    total_active_days,
                    isAct_w01,
                    isAct_w02,
                    isAct_w03,
                    isAct_w04,
                    isAct_w05,
                    isAct_w06,
                    isAct_w07,
                    isAct_w08,
                    isAct_w09,
                    isAct_w10,
                    isAct_w11,
                    isAct_w12,
                    isAct_w13,
                    13 max_active_weeks,
                    (isAct_w01 + isAct_w02 + isAct_w03 + isAct_w04 + isAct_w05 + isAct_w06 + isAct_w07 + isAct_w08 + isAct_w09 + isAct_w10 + isAct_w11 + isAct_w12 + isAct_w13) total_active_weeks,
                    act_days_w01,
                    act_days_w02,
                    act_days_w03,
                    act_days_w04,
                    act_days_w05,
                    act_days_w06,
                    act_days_w07,
                    act_days_w08,
                    act_days_w09,
                    act_days_w10,
                    act_days_w11,
                    act_days_w12,
                    act_days_w13,
                    net_rides
                from
                    (
                    select
                        customerid,
                        sum(rr_active_day) total_active_days,
                        max(case when day >= date_format(date('{run_date}') - interval '91' day, '%Y-%m-%d') and day <= date_format(date('{run_date}') - interval '85' day, '%Y-%m-%d')  and rr_active_day > 0 then 1 else 0 end ) isAct_w01,
                        max(case when day >= date_format(date('{run_date}') - interval '84' day, '%Y-%m-%d') and day <= date_format(date('{run_date}') - interval '78' day, '%Y-%m-%d')  and rr_active_day > 0 then 1 else 0 end ) isAct_w02,
                        max(case when day >= date_format(date('{run_date}') - interval '77' day, '%Y-%m-%d') and day <= date_format(date('{run_date}') - interval '71' day, '%Y-%m-%d')  and rr_active_day > 0 then 1 else 0 end ) isAct_w03,
                        max(case when day >= date_format(date('{run_date}') - interval '70' day, '%Y-%m-%d') and day <= date_format(date('{run_date}') - interval '64' day, '%Y-%m-%d')  and rr_active_day > 0 then 1 else 0 end ) isAct_w04,
                        max(case when day >= date_format(date('{run_date}') - interval '63' day, '%Y-%m-%d') and day <= date_format(date('{run_date}') - interval '57' day, '%Y-%m-%d')  and rr_active_day > 0 then 1 else 0 end ) isAct_w05,
                        max(case when day >= date_format(date('{run_date}') - interval '56' day, '%Y-%m-%d') and day <= date_format(date('{run_date}') - interval '50' day, '%Y-%m-%d')  and rr_active_day > 0 then 1 else 0 end ) isAct_w06,
                        max(case when day >= date_format(date('{run_date}') - interval '49' day, '%Y-%m-%d') and day <= date_format(date('{run_date}') - interval '43' day, '%Y-%m-%d')  and rr_active_day > 0 then 1 else 0 end ) isAct_w07,
                        max(case when day >= date_format(date('{run_date}') - interval '42' day, '%Y-%m-%d') and day <= date_format(date('{run_date}') - interval '36' day, '%Y-%m-%d')  and rr_active_day > 0 then 1 else 0 end ) isAct_w08,
                        max(case when day >= date_format(date('{run_date}') - interval '35' day, '%Y-%m-%d') and day <= date_format(date('{run_date}') - interval '29' day, '%Y-%m-%d')  and rr_active_day > 0 then 1 else 0 end ) isAct_w09,
                        max(case when day >= date_format(date('{run_date}') - interval '28' day, '%Y-%m-%d') and day <= date_format(date('{run_date}') - interval '22' day, '%Y-%m-%d')  and rr_active_day > 0 then 1 else 0 end ) isAct_w10,
                        max(case when day >= date_format(date('{run_date}') - interval '21' day, '%Y-%m-%d') and day <= date_format(date('{run_date}') - interval '15' day, '%Y-%m-%d')  and rr_active_day > 0 then 1 else 0 end ) isAct_w11,
                        max(case when day >= date_format(date('{run_date}') - interval '14' day, '%Y-%m-%d') and day <= date_format(date('{run_date}') - interval '8' day, '%Y-%m-%d')  and rr_active_day > 0 then 1 else 0 end ) isAct_w12,
                        max(case when day >= date_format(date('{run_date}') - interval '7' day, '%Y-%m-%d') and day <= date_format(date('{run_date}') - interval '1' day, '%Y-%m-%d')  and rr_active_day > 0 then 1 else 0 end ) isAct_w13,
                        
                        count(distinct case when day >= date_format(date('{run_date}') - interval '91' day, '%Y-%m-%d') and day <= date_format(date('{run_date}') - interval '85' day, '%Y-%m-%d')  and rr_active_day > 0 then day end ) act_days_w01,
                        count(distinct case when day >= date_format(date('{run_date}') - interval '84' day, '%Y-%m-%d') and day <= date_format(date('{run_date}') - interval '78' day, '%Y-%m-%d')  and rr_active_day > 0 then day end ) act_days_w02,
                        count(distinct case when day >= date_format(date('{run_date}') - interval '77' day, '%Y-%m-%d') and day <= date_format(date('{run_date}') - interval '71' day, '%Y-%m-%d')  and rr_active_day > 0 then day end ) act_days_w03,
                        count(distinct case when day >= date_format(date('{run_date}') - interval '70' day, '%Y-%m-%d') and day <= date_format(date('{run_date}') - interval '64' day, '%Y-%m-%d')  and rr_active_day > 0 then day end ) act_days_w04,
                        count(distinct case when day >= date_format(date('{run_date}') - interval '63' day, '%Y-%m-%d') and day <= date_format(date('{run_date}') - interval '57' day, '%Y-%m-%d')  and rr_active_day > 0 then day end ) act_days_w05,
                        count(distinct case when day >= date_format(date('{run_date}') - interval '56' day, '%Y-%m-%d') and day <= date_format(date('{run_date}') - interval '50' day, '%Y-%m-%d')  and rr_active_day > 0 then day end ) act_days_w06,
                        count(distinct case when day >= date_format(date('{run_date}') - interval '49' day, '%Y-%m-%d') and day <= date_format(date('{run_date}') - interval '43' day, '%Y-%m-%d')  and rr_active_day > 0 then day end ) act_days_w07,
                        count(distinct case when day >= date_format(date('{run_date}') - interval '42' day, '%Y-%m-%d') and day <= date_format(date('{run_date}') - interval '36' day, '%Y-%m-%d')  and rr_active_day > 0 then day end ) act_days_w08,
                        count(distinct case when day >= date_format(date('{run_date}') - interval '35' day, '%Y-%m-%d') and day <= date_format(date('{run_date}') - interval '29' day, '%Y-%m-%d')  and rr_active_day > 0 then day end ) act_days_w09,
                        count(distinct case when day >= date_format(date('{run_date}') - interval '28' day, '%Y-%m-%d') and day <= date_format(date('{run_date}') - interval '22' day, '%Y-%m-%d')  and rr_active_day > 0 then day end ) act_days_w10,
                        count(distinct case when day >= date_format(date('{run_date}') - interval '21' day, '%Y-%m-%d') and day <= date_format(date('{run_date}') - interval '15' day, '%Y-%m-%d')  and rr_active_day > 0 then day end ) act_days_w11,
                        count(distinct case when day >= date_format(date('{run_date}') - interval '14' day, '%Y-%m-%d') and day <= date_format(date('{run_date}') - interval '8' day, '%Y-%m-%d')  and rr_active_day > 0 then day end ) act_days_w12,
                        count(distinct case when day >= date_format(date('{run_date}') - interval '7' day, '%Y-%m-%d') and day <= date_format(date('{run_date}') - interval '1' day, '%Y-%m-%d')  and rr_active_day > 0 then day end ) act_days_w13,
                        sum(net_rides_daily) net_rides
                    
                    from    
                        (
                        select 
                            day,
                            customerid, 
                            -- max(fe_sessions_unique_daily) fe_session, 
                            -- sum(rr_sessions_unique_daily) rr_session, 
                            max(case when rr_sessions_unique_daily > 0 then 1 else 0 end) rr_active_day,
                            sum(net_rides_daily) net_rides_daily
                        from 
                            datasets.customer_rf_daily_kpi
                        where 
                            day >= date_format(date('{run_date}') - interval '91' day, '%Y-%m-%d')
                            and day <= date_format(date('{run_date}') - interval '1' day, '%Y-%m-%d')
                            and city = '{city_name}'
                            and service_name in ('Auto','Auto Lite','Auto Pool','AutoPremium','CityAuto','Link','Bike Lite','Bike Pink','CabEconomy','Bike Metro', 'CabPremium', 'Auto NCR')
                            -- and customerid = '6288c6694281e53bbe33d133'
                        group by 1,2
                        )
                    group by 1
                    )
                )
                
                select
                    *
                from
                    base
                left join 
                    active_week
                    on base.customer_id = active_week.customerid
            """

        df_segment = pd.read_sql(base_query, conn4)
        df_segment['run_date'] = run_date
        df_list.append(df_segment)
        print(f"Fetched data for segment: {segment}")
    
    # Concatenate all segment dataframes
    df_base_query = pd.concat(df_list, ignore_index=True)

    df_base_query.to_parquet(local_path + city + '/customer_base_{}.parquet'.format(run_date), index=False)
    end_time = time.time()
    print(f"Executed - Time taken: {end_time - start_time:.4f} seconds")

In [8]:
"""
for i in run_date:
    
    print('Starting - ', i)
    get_segment_customer_base(i)
"""

"\nfor i in run_date:\n    \n    print('Starting - ', i)\n    get_segment_customer_base(i)\n"

In [9]:
# Find all matching parquet files
file_paths = glob.glob(os.path.join(local_path + city + '/customer_base_*.parquet'))

# Dictionary to store dynamically created DataFrames
dfs = {}

for path in file_paths:
    filename = os.path.basename(path)
    # Get last 10 characters of the filename without extension
    name_part = os.path.splitext(filename)[0][-10:]
    # Remove special characters
    cleaned_name = re.sub(r'\W+', '', name_part)
    # Create a dynamic dataframe name
    df_name = f'df_{cleaned_name}'
    # Read the parquet file
    dfs[df_name] = pd.read_parquet(path)

In [10]:
df_list = list(dfs.keys())
df_list

['df_20250414',
 'df_20250331',
 'df_20250317',
 'df_20250428',
 'df_20250407',
 'df_20250421',
 'df_20250505',
 'df_20250310',
 'df_20250324',
 'df_20250303']

## Feature Engineering

In [11]:
def get_feature_engineering(df):
    
    print('feature engineering part')
    # Adding required active month fields
    df['isAct_m01'] = np.where(df[['isAct_w01', 'isAct_w02', 'isAct_w03', 'isAct_w04']].sum(axis=1) >= 1, 1, 0)
    df['isAct_m02'] = np.where(df[['isAct_w05', 'isAct_w06', 'isAct_w07', 'isAct_w08']].sum(axis=1) >= 1, 1, 0)
    df['isAct_m03'] = np.where(df[['isAct_w09', 'isAct_w10', 'isAct_w11', 'isAct_w12', 'isAct_w13']].sum(axis=1) >= 1, 1, 0)
    
    df['max_active_months'] = 3
    df['total_active_months'] = df[['isAct_m01', 'isAct_m02', 'isAct_m03']].sum(axis=1)
    
    df['days_since_1st_ride_in_3months'] = np.where(df['rapido_firstride_age']>=91,91,df['rapido_firstride_age'])
    df['weeks_since_1st_ride_in_3months'] = np.ceil(df['days_since_1st_ride_in_3months']/7)
    df['months_since_1st_ride_in_3months'] = np.ceil(df['days_since_1st_ride_in_3months']/31)

    df["customerid"] = df["customerid"].fillna('NA')
    df.fillna(0,inplace=True)


    # Adding required derived percentage fields for making thresholds
    df['active_days_percet'] = (df['total_active_days']/df['days_since_1st_ride_in_3months']).round(2)
    df['active_weeks_percet'] = (df['total_active_weeks']/df['weeks_since_1st_ride_in_3months']).round(2)
    df['active_months_percet'] = (df['total_active_months']/df['months_since_1st_ride_in_3months']).round(2)

    return df

## Segmentation

In [12]:
def get_segment(df):

    print('segmentation part')
    
    df['hh_monthly_segment'] = np.where((df['taxi_ltr_segment'].isin(['HH'])) & (df['active_months_percet'] >= 0.66), '1-HH-MONTHLY', None)
    df['hh_quarterly_segment'] = np.where((df['taxi_ltr_segment'].isin(['HH'])) & (df['total_active_days'] > 0), '2-HH-QUARTERLY', None)
    df['hh_inactive_segment'] = np.where((df['taxi_ltr_segment'].isin(['HH'])), '3-HH-INACTIVE',  None)
    
    df['daily_segment'] = np.where((df['taxi_ltr_segment'].isin(['PHH']))& (df['active_days_percet'] >= 0.45), '4-DAILY', None)
    df['weekly_segment'] = np.where((df['taxi_ltr_segment'].isin(['PHH'])) & (df['active_weeks_percet'] >= 0.70), '5-WEEKLY', None)
    df['monthly_segment'] = np.where((df['taxi_ltr_segment'].isin(['PHH'])) & (df['active_months_percet'] >= 0.66), '6-MONTHLY', None)
    df['quarterly_segment'] = np.where((df['taxi_ltr_segment'].isin(['PHH'])) & df['total_active_days'] > 0, '7-QUARTERLY', None)
    df['inactive_segment'] = np.where((df['taxi_ltr_segment'].isin(['PHH'])) & (df['total_active_days'] == 0), '8-INACTIVE', None)
    df['new_segment'] = np.where((~df['taxi_ltr_segment'].isin(['HH', 'PHH'])), '9-NEW', None)
    df['segment'] = df['hh_monthly_segment']\
                        .fillna(df['hh_quarterly_segment'])\
                        .fillna(df['hh_inactive_segment'])\
                        .fillna(df['daily_segment'])\
                        .fillna(df['weekly_segment'])\
                        .fillna(df['monthly_segment'])\
                        .fillna(df['quarterly_segment'])\
                        .fillna(df['inactive_segment'])\
                        .fillna(df['new_segment'])\
                        .fillna('check')
    
    df['updated_segment'] = df['segment']
    
    df.loc[((df['updated_segment']=='7-QUARTERLY')& (df['weeks_since_1st_ride_in_3months']<=8)), 'updated_segment'] = '6-MONTHLY'
    df.loc[((df['updated_segment'] == '5-WEEKLY') & (df['weeks_since_1st_ride_in_3months']<=2)), 'updated_segment'] = '6-MONTHLY'

    return df

## Execution

In [13]:
df_list

['df_20250414',
 'df_20250331',
 'df_20250317',
 'df_20250428',
 'df_20250407',
 'df_20250421',
 'df_20250505',
 'df_20250310',
 'df_20250324',
 'df_20250303']

In [14]:
for df_name in df_list:
    print(df_name)
    df = dfs[df_name]
    df_temp = get_feature_engineering(df)
    df_final = get_segment(df_temp)
    df_final.to_parquet(local_path + city + '/segment/{}.parquet'.format(df_name), index=False)
    
    print('---')

df_20250414
feature engineering part
segmentation part
---
df_20250331
feature engineering part
segmentation part
---
df_20250317
feature engineering part
segmentation part
---
df_20250428
feature engineering part
segmentation part
---
df_20250407
feature engineering part
segmentation part
---
df_20250421
feature engineering part
segmentation part
---
df_20250505
feature engineering part
segmentation part
---
df_20250310
feature engineering part
segmentation part
---
df_20250324
feature engineering part
segmentation part
---
df_20250303
feature engineering part
segmentation part
---

## Customer Segment

In [6]:
folder_path = '/Users/E2074/local-datasets/customer/segmentation/consideration/' + city + '/segment/'

# Get all parquet files in the folder
parquet_files = glob.glob(os.path.join(folder_path, '*.parquet'))

# Read and concatenate all parquet files into a single DataFrame
df_segment_concat = pd.concat([pd.read_parquet(file) for file in parquet_files], ignore_index=True)

In [7]:
df_segment_concat.head(1)

,customer_id,taxi_ltr_segment,rapido_firstride_age,customerid,max_active_days,total_active_days,isAct_w01,isAct_w02,isAct_w03,isAct_w04,isAct_w05,isAct_w06,isAct_w07,isAct_w08,isAct_w09,isAct_w10,isAct_w11,isAct_w12,isAct_w13,max_active_weeks,total_active_weeks,act_days_w01,act_days_w02,act_days_w03,act_days_w04,...,act_days_w13,net_rides,run_date,isAct_m01,isAct_m02,isAct_m03,max_active_months,total_active_months,days_since_1st_ride_in_3months,weeks_since_1st_ride_in_3months,months_since_1st_ride_in_3months,active_days_percet,active_weeks_percet,active_months_percet,hh_monthly_segment,hh_quarterly_segment,hh_inactive_segment,daily_segment,weekly_segment,monthly_segment,quarterly_segment,inactive_segment,new_segment,segment,updated_segment
0,655464126305aa25be30b18f,HH,502,NA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,2025-03-31,0,0,0,3,0,91,13.0,3.0,0.0,0.0,0.0,None,None,3-HH-INACTIVE,None,None,None,None,None,None,3-HH-INACTIVE,3-HH-INACTIVE

In [8]:
df_segment_concat.shape

(94679458, 58)

In [9]:
df_segment_concat.segment.unique()

array(['3-HH-INACTIVE', '1-HH-MONTHLY', '2-HH-QUARTERLY', '6-MONTHLY',
       '8-INACTIVE', '7-QUARTERLY', '5-WEEKLY', '4-DAILY'], dtype=object)

## Stability

In [10]:
# Reducing df memory 
df_segment_concat = df_segment_concat[['run_date', 'customer_id', 'updated_segment']]

In [11]:
df_segment_concat.run_date.unique()

array(['2025-03-31', '2025-03-17', '2025-04-14', '2025-05-05',
       '2025-04-21', '2025-04-07', '2025-04-28', '2025-03-10',
       '2025-03-03', '2025-03-24'], dtype=object)

In [12]:
df_base = df_segment_concat[df_segment_concat['run_date'].isin(['2025-03-03'])].reset_index(drop=True)
df_base

           run_date               customer_id updated_segment
0        2025-03-03  65e2ba096e7643720c5b32af   3-HH-INACTIVE
1        2025-03-03  64e6c5eb143ba3ba6f49c168   3-HH-INACTIVE
2        2025-03-03  5d7a9dcda24c96105e4a06ae   3-HH-INACTIVE
3        2025-03-03  657780b9a53a4a14eef9747a   3-HH-INACTIVE
4        2025-03-03  63c652e1926f77641546978e   3-HH-INACTIVE
...             ...                       ...             ...
9192848  2025-03-03  62a0921b71bfd2cef5b84bd8      8-INACTIVE
9192849  2025-03-03  653684a5b5145a243b746d25       6-MONTHLY
9192850  2025-03-03  5e25c1416f37f902ba1ad77b       6-MONTHLY
9192851  2025-03-03  64d6d3e25d2459332c79452a      8-INACTIVE
9192852  2025-03-03  63c0dde5291d3ad6ed20eecb       6-MONTHLY

[9192853 rows x 3 columns]

In [13]:
df_stability_window = df_segment_concat[~df_segment_concat['run_date'].isin(['2025-03-03'])].sort_values(by=['run_date']).reset_index(drop=True)
df_stability_window

            run_date               customer_id updated_segment
0         2025-03-10  63e9f56f16de16125fd64cbe       6-MONTHLY
1         2025-03-10  62bd6760ba38cb83dd724c0f     7-QUARTERLY
2         2025-03-10  6239b37e6b6b6492c673a5d6       6-MONTHLY
3         2025-03-10  5fb218a20a41becbbe886ee3        5-WEEKLY
4         2025-03-10  5a89a27af62cc32e4f023917     7-QUARTERLY
...              ...                       ...             ...
85486600  2025-05-05  65c320d70753e6514331b97b      8-INACTIVE
85486601  2025-05-05  6770e34c2d02e72cdf707ced       6-MONTHLY
85486602  2025-05-05  60155bdba71b1dbfe3192174      8-INACTIVE
85486603  2025-05-05  61f1fc176916b8680dac3f15      8-INACTIVE
85486604  2025-05-05  673c7cb062fb00d50df3a192      8-INACTIVE

[85486605 rows x 3 columns]

In [14]:
df_stability_window.run_date.unique()

array(['2025-03-10', '2025-03-17', '2025-03-24', '2025-03-31',
       '2025-04-07', '2025-04-14', '2025-04-21', '2025-04-28',
       '2025-05-05'], dtype=object)

In [15]:
df_merge = pd.merge(df_base, df_stability_window, how='left', on='customer_id')
df_merge

,run_date_x,customer_id,updated_segment_x,run_date_y,updated_segment_y
0,2025-03-03,65e2ba096e7643720c5b32af,3-HH-INACTIVE,2025-03-10,3-HH-INACTIVE
1,2025-03-03,65e2ba096e7643720c5b32af,3-HH-INACTIVE,2025-03-17,3-HH-INACTIVE
2,2025-03-03,65e2ba096e7643720c5b32af,3-HH-INACTIVE,2025-03-24,3-HH-INACTIVE
3,2025-03-03,65e2ba096e7643720c5b32af,3-HH-INACTIVE,2025-03-31,3-HH-INACTIVE
4,2025-03-03,65e2ba096e7643720c5b32af,3-HH-INACTIVE,2025-04-07,3-HH-INACTIVE
...,...,...,...,...,...
80786646,2025-03-03,63c0dde5291d3ad6ed20eecb,6-MONTHLY,2025-04-07,6-MONTHLY
80786647,2025-03-03,63c0dde5291d3ad6ed20eecb,6-MONTHLY,2025-04-14,6-MONTHLY
80786648,2025-03-03,63c0dde5291d3ad6ed20eecb,6-MONTHLY,2025-04-21,6-MONTHLY
80786649,2025-03-03,63c0dde5291d3ad6ed20eecb,6-MONTHLY,2025-04-28,6-MONTHLY
80786650,2025-03-03,63c0dde5291d3ad6ed20eecb,6-MONTHLY,2025-05-05,6-MONTHLY

In [16]:
df_merge_pivot = df_merge.groupby(['run_date_x', 'run_date_y', 'updated_segment_x', 'updated_segment_y']).agg(customers=('customer_id','nunique')).reset_index()

In [17]:
df_merge_pivot

     run_date_x  run_date_y updated_segment_x updated_segment_y  customers
0    2025-03-03  2025-03-10      1-HH-MONTHLY      1-HH-MONTHLY     324129
1    2025-03-03  2025-03-10      1-HH-MONTHLY    2-HH-QUARTERLY      73830
2    2025-03-03  2025-03-10      1-HH-MONTHLY     3-HH-INACTIVE         13
3    2025-03-03  2025-03-10      1-HH-MONTHLY           4-DAILY       1642
4    2025-03-03  2025-03-10      1-HH-MONTHLY          5-WEEKLY       3867
..          ...         ...               ...               ...        ...
413  2025-03-03  2025-05-05        8-INACTIVE           4-DAILY        165
414  2025-03-03  2025-05-05        8-INACTIVE          5-WEEKLY          4
415  2025-03-03  2025-05-05        8-INACTIVE         6-MONTHLY      72037
416  2025-03-03  2025-05-05        8-INACTIVE       7-QUARTERLY     204619
417  2025-03-03  2025-05-05        8-INACTIVE        8-INACTIVE    1702026

[418 rows x 5 columns]

In [18]:
df_merge_pivot.pivot(index = ['run_date_x', 'updated_segment_x', 'updated_segment_y'] , columns = ['run_date_y'], values =['customers']).fillna(0)

                                                customers             \
run_date_y                                     2025-03-10 2025-03-17
run_date_x updated_segment_x updated_segment_y
2025-03-03 1-HH-MONTHLY      1-HH-MONTHLY        324129.0   251211.0
                             2-HH-QUARTERLY       73830.0   128486.0
                             3-HH-INACTIVE           13.0       26.0
                             4-DAILY               1642.0     1227.0
                             5-WEEKLY              3867.0     8845.0
                             6-MONTHLY            13473.0    24663.0
                             7-QUARTERLY            570.0     1523.0
                             8-INACTIVE               0.0        0.0
           2-HH-QUARTERLY    1-HH-MONTHLY         33539.0    47177.0
                             2-HH-QUARTERLY      447579.0   371821.0
                             3-HH-INACTIVE        54426.0   104452.0
                             4-DAILY                 17.0       22.0
                             5-WEEKLY                57.0      209.0
                             6-MONTHLY             4595.0    10704.0
                             7-QUARTERLY           5522.0     9238.0
                             8-INACTIVE              57.0      152.0
           3-HH-INACTIVE     1-HH-MONTHLY          7232.0     6816.0
                             2-HH-QUARTERLY       20798.0    38706.0
                             3-HH-INACTIVE      2738781.0  2709141.0
                             4-DAILY                515.0      376.0
                             5-WEEKLY                 0.0        0.0
                             6-MONTHLY              272.0      842.0
                             7-QUARTERLY           4817.0    11103.0
                             8-INACTIVE            1599.0     2499.0
           4-DAILY           4-DAILY             109889.0   102812.0
                             5-WEEKLY              7624.0    12750.0
                             6-MONTHLY             2579.0     4013.0
                             7-QUARTERLY              1.0        5.0
                             8-INACTIVE               0.0        0.0
           5-WEEKLY          4-DAILY               6459.0    10046.0
                             5-WEEKLY            288129.0   259999.0
                             6-MONTHLY            33252.0    56019.0
                             7-QUARTERLY              0.0        1.0
                             8-INACTIVE               0.0        0.0
           6-MONTHLY         4-DAILY               1348.0     2654.0
                             5-WEEKLY             26819.0    44420.0
                             6-MONTHLY          1765441.0  1637277.0
                             7-QUARTERLY         150685.0   242892.0
                             8-INACTIVE               2.0        2.0
           7-QUARTERLY       4-DAILY                  1.0       42.0
                             5-WEEKLY                 0.0        0.0
                             6-MONTHLY           122277.0   197211.0
                             7-QUARTERLY         756367.0   601166.0
                             8-INACTIVE           75572.0   142663.0
           8-INACTIVE        4-DAILY                  6.0        3.0
                             5-WEEKLY                 0.0        0.0
                             6-MONTHLY              129.0      136.0
                             7-QUARTERLY          41686.0    74881.0
                             8-INACTIVE         1990760.0  1949874.0

                                                                      \
run_date_y                                     2025-03-24 2025-03-31
run_date_x updated_segment_x updated_segment_y
2025-03-03 1-HH-MONTHLY      1-HH-MONTHLY        197074.0   159057.0
                             2-HH-QUARTERLY      167481.0   191869.0
                             3-HH-INACTIVE           31.0       34.0
                             4-DAILY               1062.0      977.0
                             5-WEEKLY             11274.0    10839.0
                             6-MONTHLY            35795.0    48942.0
                             7-QUARTERLY           2047.0     1852.0
                             8-INACTIVE               2.0        4.0
           2-HH-QUARTERLY    1-HH-MONTHLY         51556.0    45868.0
                             2-HH-QUARTERLY      316732.0   276983.0
                             3-HH-INACTIVE       144222.0   179151.0
                             4-DAILY                 20.0        9.0
                             5-WEEKLY               166.0      140.0
                             6-MONTHLY            17378.0    24077.0
                             7-QUARTERLY          11695.0    13731.0
                             8-INACTIVE             249.0      402.0
           3-HH-INACTIVE     1-HH-MONTHLY          6471.0     6174.0
                             2-HH-QUARTERLY       56332.0    72382.0
                             3-HH-INACTIVE      2679776.0  2651597.0
                             4-DAILY                281.0      233.0
                             5-WEEKLY               499.0      803.0
                             6-MONTHLY              724.0      652.0
                             7-QUARTERLY          18050.0    25289.0
                             8-INACTIVE            3259.0     4072.0
           4-DAILY           4-DAILY              98528.0    95924.0
                             5-WEEKLY             15494.0    15390.0
                             6-MONTHLY             5737.0     7498.0
                             7-QUARTERLY             44.0      129.0
                             8-INACTIVE               0.0        0.0
           5-WEEKLY          4-DAILY              14089.0    19442.0
                             5-WEEKLY            240463.0   223764.0
                             6-MONTHLY            71394.0    80479.0
                             7-QUARTERLY              3.0      271.0
                             8-INACTIVE               0.0        0.0
           6-MONTHLY         4-DAILY               4522.0     6744.0
                             5-WEEKLY             62142.0    84922.0
                             6-MONTHLY          1567630.0  1528856.0
                             7-QUARTERLY         284055.0   284866.0
                             8-INACTIVE               2.0        2.0
           7-QUARTERLY       4-DAILY                188.0      493.0
                             5-WEEKLY                 0.0        0.0
                             6-MONTHLY           235533.0   242304.0
                             7-QUARTERLY         502440.0   445426.0
                             8-INACTIVE          193776.0   234427.0
           8-INACTIVE        4-DAILY                  3.0        2.0
                             5-WEEKLY                 4.0        4.0
                             6-MONTHLY              125.0      119.0
                             7-QUARTERLY         108332.0   138910.0
                             8-INACTIVE         1909979.0  1872713.0

                                                                      \
run_date_y                                     2025-04-07 2025-04-14
run_date_x updated_segment_x updated_segment_y
2025-03-03 1-HH-MONTHLY      1-HH-MONTHLY        132016.0   116188.0
                             2-HH-QUARTERLY      196331.0   193087.0
                             3-HH-INACTIVE         9356.0    16189.0
                             4-DAILY                895.0      837.0
                             5-WEEKLY             10377.0    10737.0
                             6-MONTHLY            61474.0    69777.0
                             7-QUARTERLY           1854.0     4205.0
                             8-INACTIVE              58.0      103.0
           2-HH-QUARTERLY    1-HH-MONTHLY         54425.0    52418.0
                             2-HH-QUARTERLY      233842.0   199598.0
                             3-HH-INACTIVE       202739.0   228180.0
                             4-DAILY                  9.0        8.0
                             5-WEEKLY               250.0      205.0
                             6-MONTHLY            32749.0    38344.0
                             7-QUARTERLY          14133.0    17288.0
                             8-INACTIVE             505.0      641.0
           3-HH-INACTIVE     1-HH-MONTHLY             0.0     6342.0
                             2-HH-QUARTERLY       98264.0   107526.0
                             3-HH-INACTIVE      2617913.0  2587754.0
                             4-DAILY                215.0      195.0
                             5-WEEKLY               670.0      506.0
                             6-MONTHLY             1033.0     8272.0
                             7-QUARTERLY          33848.0    35692.0
                             8-INACTIVE            4927.0     5655.0
           4-DAILY           4-DAILY              93687.0    89592.0
                             5-WEEKLY             16215.0    17521.0
                             6-MONTHLY             8922.0    10512.0
                             7-QUARTERLY            383.0      777.0
                             8-INACTIVE               0.0        2.0
           5-WEEKLY          4-DAILY              24036.0    26195.0
                             5-WEEKLY            210799.0   197856.0
                             6-MONTHLY            88554.0    97450.0
                             7-QUARTERLY            993.0     1225.0
                             8-INACTIVE               0.0        0.0
           6-MONTHLY         4-DAILY               9218.0    11543.0
                             5-WEEKLY            104699.0   116790.0
                             6-MONTHLY          1466693.0  1396951.0
                             7-QUARTERLY         287718.0   306871.0
                             8-INACTIVE           30992.0    57314.0
           7-QUARTERLY       4-DAILY                893.0     1408.0
                             5-WEEKLY              1098.0     3133.0
                             6-MONTHLY           286126.0   304673.0
                             7-QUARTERLY         385743.0   346244.0
                             8-INACTIVE          241548.0   252406.0
           8-INACTIVE        4-DAILY                  2.0        3.0
                             5-WEEKLY                 5.0        5.0
                             6-MONTHLY              102.0    22343.0
                             7-QUARTERLY         174359.0   181236.0
                             8-INACTIVE         1830620.0  1794578.0

                                                                      \
run_date_y                                     2025-04-21 2025-04-28
run_date_x updated_segment_x updated_segment_y
2025-03-03 1-HH-MONTHLY      1-HH-MONTHLY        105883.0    98533.0
                             2-HH-QUARTERLY      187477.0   181362.0
                             3-HH-INACTIVE        21509.0    26190.0
                             4-DAILY                787.0      774.0
                             5-WEEKLY              9457.0     8471.0
                             6-MONTHLY            78273.0    84928.0
                             7-QUARTERLY           6376.0     8485.0
                             8-INACTIVE             146.0      202.0
           2-HH-QUARTERLY    1-HH-MONTHLY         47809.0    40450.0
                             2-HH-QUARTERLY      167803.0   138135.0
                             3-HH-INACTIVE       254187.0   282543.0
                             4-DAILY                 15.0       24.0
                             5-WEEKLY               211.0      312.0
                             6-MONTHLY            43293.0    47104.0
                             7-QUARTERLY          20725.0    23831.0
                             8-INACTIVE             783.0      933.0
           3-HH-INACTIVE     1-HH-MONTHLY         10023.0    13271.0
                             2-HH-QUARTERLY      119552.0   127119.0
                             3-HH-INACTIVE      2557398.0  2533114.0
                             4-DAILY                187.0      187.0
                             5-WEEKLY               683.0      517.0
                             6-MONTHLY            14658.0    21267.0
                             7-QUARTERLY          37984.0    39909.0
                             8-INACTIVE            6427.0     7029.0
           4-DAILY           4-DAILY              86083.0    82539.0
                             5-WEEKLY             18335.0    19673.0
                             6-MONTHLY            11711.0    13308.0
                             7-QUARTERLY           1523.0     2044.0
                             8-INACTIVE              27.0       76.0
           5-WEEKLY          4-DAILY              27872.0    28999.0
                             5-WEEKLY            186038.0   174361.0
                             6-MONTHLY           104733.0   112607.0
                             7-QUARTERLY           2257.0     5054.0
                             8-INACTIVE               1.0        4.0
           6-MONTHLY         4-DAILY              13259.0    14796.0
                             5-WEEKLY            127177.0   132766.0
                             6-MONTHLY          1340168.0  1302249.0
                             7-QUARTERLY         317507.0   320936.0
                             8-INACTIVE           79994.0   102293.0
           7-QUARTERLY       4-DAILY               2006.0     2676.0
                             5-WEEKLY              5812.0     9179.0
                             6-MONTHLY           312524.0   309886.0
                             7-QUARTERLY         315895.0   293587.0
                             8-INACTIVE          263965.0   279510.0
           8-INACTIVE        4-DAILY                 22.0       79.0
                             5-WEEKLY                 4.0        5.0
                             6-MONTHLY            39664.0    56312.0
                             7-QUARTERLY         191802.0   196505.0
                             8-INACTIVE         1759738.0  1732431.0


run_date_y                                     2025-05-05
run_date_x updated_segment_x updated_segment_y
2025-03-03 1-HH-MONTHLY      1-HH-MONTHLY         89864.0
                             2-HH-QUARTERLY      161204.0
                             3-HH-INACTIVE        45903.0
                             4-DAILY                728.0
                             5-WEEKLY              8399.0
                             6-MONTHLY            91936.0
                             7-QUARTERLY           9493.0
                             8-INACTIVE             294.0
           2-HH-QUARTERLY    1-HH-MONTHLY         36823.0
                             2-HH-QUARTERLY      122614.0
                             3-HH-INACTIVE       292362.0
                             4-DAILY                 42.0
                             5-WEEKLY               513.0
                             6-MONTHLY            52844.0
                             7-QUARTERLY          25275.0
                             8-INACTIVE            1087.0
           3-HH-INACTIVE     1-HH-MONTHLY         16594.0
                             2-HH-QUARTERLY      136982.0
                             3-HH-INACTIVE      2504958.0
                             4-DAILY                191.0
                             5-WEEKLY               438.0
                             6-MONTHLY            27394.0
                             7-QUARTERLY          43153.0
                             8-INACTIVE            7783.0
           4-DAILY           4-DAILY              78539.0
                             5-WEEKLY             20823.0
                             6-MONTHLY            14768.0
                             7-QUARTERLY           2752.0
                             8-INACTIVE             222.0
           5-WEEKLY          4-DAILY              29594.0
                             5-WEEKLY            164190.0
                             6-MONTHLY           116973.0
                             7-QUARTERLY           8745.0
                             8-INACTIVE              16.0
           6-MONTHLY         4-DAILY              16153.0
                             5-WEEKLY            140817.0
                             6-MONTHLY          1261029.0
                             7-QUARTERLY         314018.0
                             8-INACTIVE          132149.0
           7-QUARTERLY       4-DAILY               3165.0
                             5-WEEKLY             11327.0
                             6-MONTHLY           315161.0
                             7-QUARTERLY         279305.0
                             8-INACTIVE          279677.0
           8-INACTIVE        4-DAILY                165.0
                             5-WEEKLY                 4.0
                             6-MONTHLY            72037.0
                             7-QUARTERLY         204619.0
                             8-INACTIVE         1702026.0

In [19]:
df_base.groupby(['run_date', 'updated_segment']).agg(customers=('customer_id','nunique')).reset_index()

     run_date updated_segment  customers
0  2025-03-03    1-HH-MONTHLY     419656
1  2025-03-03  2-HH-QUARTERLY     548198
2  2025-03-03   3-HH-INACTIVE    2778987
3  2025-03-03         4-DAILY     122112
4  2025-03-03        5-WEEKLY     333348
5  2025-03-03       6-MONTHLY    1973724
6  2025-03-03     7-QUARTERLY     974298
7  2025-03-03      8-INACTIVE    2042530

## Previous Segment Stability

### taxi_regularity_segment

In [58]:
run_date

['2025-03-03',
 '2025-03-10',
 '2025-03-17',
 '2025-03-24',
 '2025-03-31',
 '2025-04-07',
 '2025-04-14',
 '2025-04-21',
 '2025-04-28',
 '2025-05-05']

In [75]:
def get_previous_segment_customer_base(run_date):
    
    base_query = f"""
    
    select 
        run_date, 
        customer_id, 
        taxi_regularity_segment
        -- taxi_fe_regularity_segment 
    from 
        datasets.iallocator_customer_segments 
    where 
        run_date = date_format(date('{run_date}'), '%Y-%m-%d')
        and taxi_lifetime_last_ride_city = 'Bangalore'
        and taxi_regularity_segment != 'UNKNOWN' 
    """
    
    df_base_query = pd.read_sql(base_query, conn2)
    df_base_query['run_date'] = run_date
    print('executed - ', run_date)

    df_base_query.to_parquet(local_path + '/prev_segment/prev_customer_base_{}.parquet'.format(run_date), index=False)

In [76]:
for i in run_date[2:]:
    
    print('starting - ', i)
    get_previous_segment_customer_base(i)

starting -  2025-03-17
executed -  2025-03-17
starting -  2025-03-24
executed -  2025-03-24
starting -  2025-03-31
executed -  2025-03-31
starting -  2025-04-07
executed -  2025-04-07
starting -  2025-04-14
executed -  2025-04-14
starting -  2025-04-21
executed -  2025-04-21
starting -  2025-04-28
executed -  2025-04-28
starting -  2025-05-05
executed -  2025-05-05

In [79]:
folder_path = '/Users/E2074/local-datasets/customer/segmentation/consideration/stability/prev_segment'

# Get all parquet files in the folder
prev_parquet_files = glob.glob(os.path.join(folder_path, '*.parquet'))

# Read and concatenate all parquet files into a single DataFrame
df_previous_segment_concat = pd.concat([pd.read_parquet(file) for file in prev_parquet_files], ignore_index=True)

In [80]:
df_previous_segment_concat.head(1)

     run_date               customer_id taxi_regularity_segment
0  2025-03-31  5b8a7049d8073f681de07441               RARE_NEED

In [81]:
df_previous_segment_concat.shape

(56364524, 3)

### Stability

In [84]:
df_previous_segment_concat.run_date.unique()

array(['2025-03-31', '2025-03-17', '2025-04-14', '2025-04-28',
       '2025-04-07', '2025-04-21', '2025-03-10', '2025-05-05',
       '2025-03-03', '2025-03-24'], dtype=object)

In [82]:
df_base_prev = df_previous_segment_concat[df_previous_segment_concat['run_date'].isin(['2025-03-03'])].reset_index(drop=True)
df_base_prev

           run_date               customer_id taxi_regularity_segment
0        2025-03-03  6454d93a62374ed412653df1                   DAILY
1        2025-03-03  640ab57a9dba1afb507ad37d                 MONTHLY
2        2025-03-03  5d46f66a8dbbed6b854b9411               RARE_NEED
3        2025-03-03  672e01c57a90cba7fd4bb026               BI_WEEKLY
4        2025-03-03  657bf4a4f275491ea5f8a2cd               RARE_NEED
...             ...                       ...                     ...
5446007  2025-03-03  677bc089f30833be453a1ee8                   DAILY
5446008  2025-03-03  6717be255763f6f606549a8c                  WEEKLY
5446009  2025-03-03  62b4463d68ed98eb74b1a8c8               RARE_NEED
5446010  2025-03-03  6688b91bf4352e8b9471f06d                 MONTHLY
5446011  2025-03-03  64631423718a270a602b5795                 MONTHLY

[5446012 rows x 3 columns]

In [83]:
df_stability_window_prev = df_previous_segment_concat[~df_previous_segment_concat['run_date'].isin(['2025-03-03'])].sort_values(by=['run_date']).reset_index(drop=True)
df_stability_window_prev

            run_date               customer_id taxi_regularity_segment
0         2025-03-10  623c8014b9a21e17a1ccffb3                  WEEKLY
1         2025-03-10  634fdfc14282cecc855b269e               RARE_NEED
2         2025-03-10  5c917e3a8c352421eaf2d740               RARE_NEED
3         2025-03-10  5c4e8cc64a267149c77d6266               RARE_NEED
4         2025-03-10  6221c6afc1a4e4690d63894b               BI_WEEKLY
...              ...                       ...                     ...
50918507  2025-05-05  62316b5c3a5bedb28fbeaa16               RARE_NEED
50918508  2025-05-05  5c1c2fe2e9ba5b22438983a5               RARE_NEED
50918509  2025-05-05  634bd990fe45b5d3814353e4               RARE_NEED
50918510  2025-05-05  5c931cc08c352421eaf4a4c2                  WEEKLY
50918511  2025-05-05  63b12d348256073cbd32da54               BI_WEEKLY

[50918512 rows x 3 columns]

In [85]:
df_stability_window_prev.run_date.unique()

array(['2025-03-10', '2025-03-17', '2025-03-24', '2025-03-31',
       '2025-04-07', '2025-04-14', '2025-04-21', '2025-04-28',
       '2025-05-05'], dtype=object)

In [87]:
df_merge_prev = pd.merge(df_base_prev, df_stability_window_prev, how='left', on='customer_id')
df_merge_prev

,run_date_x,customer_id,taxi_regularity_segment_x,run_date_y,taxi_regularity_segment_y
0,2025-03-03,6454d93a62374ed412653df1,DAILY,2025-03-10,DAILY
1,2025-03-03,6454d93a62374ed412653df1,DAILY,2025-03-17,DAILY
2,2025-03-03,6454d93a62374ed412653df1,DAILY,2025-03-24,DAILY
3,2025-03-03,6454d93a62374ed412653df1,DAILY,2025-03-31,DAILY
4,2025-03-03,6454d93a62374ed412653df1,DAILY,2025-04-07,DAILY
...,...,...,...,...,...
47414424,2025-03-03,64631423718a270a602b5795,MONTHLY,2025-04-07,BI_WEEKLY
47414425,2025-03-03,64631423718a270a602b5795,MONTHLY,2025-04-14,BI_WEEKLY
47414426,2025-03-03,64631423718a270a602b5795,MONTHLY,2025-04-21,BI_WEEKLY
47414427,2025-03-03,64631423718a270a602b5795,MONTHLY,2025-04-28,BI_WEEKLY
47414428,2025-03-03,64631423718a270a602b5795,MONTHLY,2025-05-05,BI_WEEKLY

In [88]:
df_merge_pivot_prev = df_merge_prev.groupby(['run_date_x', 'run_date_y', 'taxi_regularity_segment_x', 'taxi_regularity_segment_y']).agg(customers=('customer_id','nunique')).reset_index()
df_merge_pivot_prev

,run_date_x,run_date_y,taxi_regularity_segment_x,taxi_regularity_segment_y,customers
0,2025-03-03,2025-03-10,BI_WEEKLY,BI_WEEKLY,699039
1,2025-03-03,2025-03-10,BI_WEEKLY,DAILY,5764
2,2025-03-03,2025-03-10,BI_WEEKLY,MONTHLY,112066
3,2025-03-03,2025-03-10,BI_WEEKLY,WEEKLY,68657
4,2025-03-03,2025-03-10,DAILY,BI_WEEKLY,4167
5,2025-03-03,2025-03-10,DAILY,DAILY,229567
6,2025-03-03,2025-03-10,DAILY,WEEKLY,13761
7,2025-03-03,2025-03-10,MONTHLY,BI_WEEKLY,96079
8,2025-03-03,2025-03-10,MONTHLY,MONTHLY,602270
9,2025-03-03,2025-03-10,MONTHLY,RARE_NEED,101734
10,2025-03-03,2025-03-10,RARE_NEED,MONTHLY,74919
11,2025-03-03,2025-03-10,RARE_NEED,RARE_NEED,2687514
12,2025-03-03,2025-03-10,WEEKLY,BI_WEEKLY,68656
13,2025-03-03,2025-03-10,WEEKLY,DAILY,14488
14,2025-03-03,2025-03-10,WEEKLY,WEEKLY,600345
15,2025-03-03,2025-03-17,BI_WEEKLY,BI_WEEKLY,585691
16,2025-03-03,2025-03-17,BI_WEEKLY,DAILY,11095
17,2025-03-03,2025-03-17,BI_WEEKLY,MONTHLY,178838
18,2025-03-03,2025-03-17,BI_WEEKLY,WEEKLY,99802
19,2025-03-03,2025-03-17,DAILY,BI_WEEKLY,7460
20,2025-03-03,2025-03-17,DAILY,DAILY,216499
21,2025-03-03,2025-03-17,DAILY,WEEKLY,21478
22,2025-03-03,2025-03-17,MONTHLY,BI_WEEKLY,132910
23,2025-03-03,2025-03-17,MONTHLY,MONTHLY,481937
24,2025-03-03,2025-03-17,MONTHLY,RARE_NEED,177401
25,2025-03-03,2025-03-17,RARE_NEED,BI_WEEKLY,14103
26,2025-03-03,2025-03-17,RARE_NEED,MONTHLY,115143
27,2025-03-03,2025-03-17,RARE_NEED,RARE_NEED,2620906
28,2025-03-03,2025-03-17,WEEKLY,BI_WEEKLY,97050
29,2025-03-03,2025-03-17,WEEKLY,DAILY,21864
30,2025-03-03,2025-03-17,WEEKLY,WEEKLY,556689
31,2025-03-03,2025-03-24,BI_WEEKLY,BI_WEEKLY,504225
32,2025-03-03,2025-03-24,BI_WEEKLY,DAILY,15187
33,2025-03-03,2025-03-24,BI_WEEKLY,MONTHLY,215338
34,2025-03-03,2025-03-24,BI_WEEKLY,RARE_NEED,8877
35,2025-03-03,2025-03-24,BI_WEEKLY,WEEKLY,125694
36,2025-03-03,2025-03-24,DAILY,BI_WEEKLY,10245
37,2025-03-03,2025-03-24,DAILY,DAILY,209415
38,2025-03-03,2025-03-24,DAILY,WEEKLY,25869
39,2025-03-03,2025-03-24,MONTHLY,BI_WEEKLY,150006
40,2025-03-03,2025-03-24,MONTHLY,DAILY,1189
41,2025-03-03,2025-03-24,MONTHLY,MONTHLY,407412
42,2025-03-03,2025-03-24,MONTHLY,RARE_NEED,225322
43,2025-03-03,2025-03-24,MONTHLY,WEEKLY,2924
44,2025-03-03,2025-03-24,RARE_NEED,BI_WEEKLY,31569
45,2025-03-03,2025-03-24,RARE_NEED,MONTHLY,141029
46,2025-03-03,2025-03-24,RARE_NEED,RARE_NEED,2567379
47,2025-03-03,2025-03-24,WEEKLY,BI_WEEKLY,118165
48,2025-03-03,2025-03-24,WEEKLY,DAILY,29705
49,2025-03-03,2025-03-24,WEEKLY,WEEKLY,524933
50,2025-03-03,2025-03-31,BI_WEEKLY,BI_WEEKLY,444861
51,2025-03-03,2025-03-31,BI_WEEKLY,DAILY,16870
52,2025-03-03,2025-03-31,BI_WEEKLY,MONTHLY,223079
53,2025-03-03,2025-03-31,BI_WEEKLY,RARE_NEED,28496
54,2025-03-03,2025-03-31,BI_WEEKLY,WEEKLY,148896
55,2025-03-03,2025-03-31,DAILY,BI_WEEKLY,11815
56,2025-03-03,2025-03-31,DAILY,DAILY,202080
57,2025-03-03,2025-03-31,DAILY,MONTHLY,1184
58,2025-03-03,2025-03-31,DAILY,WEEKLY,28041
59,2025-03-03,2025-03-31,MONTHLY,BI_WEEKLY,157861
60,2025-03-03,2025-03-31,MONTHLY,DAILY,3066
61,2025-03-03,2025-03-31,MONTHLY,MONTHLY,356773
62,2025-03-03,2025-03-31,MONTHLY,RARE_NEED,253809
63,2025-03-03,2025-03-31,MONTHLY,WEEKLY,9449
64,2025-03-03,2025-03-31,RARE_NEED,BI_WEEKLY,48870
65,2025-03-03,2025-03-31,RARE_NEED,DAILY,291
66,2025-03-03,2025-03-31,RARE_NEED,MONTHLY,163126
67,2025-03-03,2025-03-31,RARE_NEED,RARE_NEED,2517043
68,2025-03-03,2025-03-31,RARE_NEED,WEEKLY,127
69,2025-03-03,2025-03-31,WEEKLY,BI_WEEKLY,132950
70,2025-03-03,2025-03-31,WEEKLY,DAILY,35427
71,2025-03-03,2025-03-31,WEEKLY,MONTHLY,3731
72,2025-03-03,2025-03-31,WEEKLY,WEEKLY,494840
73,2025-03-03,2025-04-07,BI_WEEKLY,BI_WEEKLY,405279
74,2025-03-03,2025-04-07,BI_WEEKLY,DAILY,18428
75,2025-03-03,2025-04-07,BI_WEEKLY,MONTHLY,215882
76,2025-03-03,2025-04-07,BI_WEEKLY,RARE_NEED,52090
77,2025-03-03,2025-04-07,BI_WEEKLY,WEEKLY,166447
78,2025-03-03,2025-04-07,DAILY,BI_WEEKLY,12899
79,2025-03-03,2025-04-07,DAILY,DAILY,198343
80,2025-03-03,2025-04-07,DAILY,MONTHLY,2827
81,2025-03-03,2025-04-07,DAILY,WEEKLY,29692
82,2025-03-03,2025-04-07,MONTHLY,BI_WEEKLY,165776
83,2025-03-03,2025-04-07,MONTHLY,DAILY,4174
84,2025-03-03,2025-04-07,MONTHLY,MONTHLY,316540
85,2025-03-03,2025-04-07,MONTHLY,RARE_NEED,270342
86,2025-03-03,2025-04-07,MONTHLY,WEEKLY,19295
87,2025-03-03,2025-04-07,RARE_NEED,BI_WEEKLY,66215
88,2025-03-03,2025-04-07,RARE_NEED,DAILY,1330
89,2025-03-03,2025-04-07,RARE_NEED,MONTHLY,185537
90,2025-03-03,2025-04-07,RARE_NEED,RARE_NEED,2464213
91,2025-03-03,2025-04-07,RARE_NEED,WEEKLY,1950
92,2025-03-03,2025-04-07,WEEKLY,BI_WEEKLY,137910
93,2025-03-03,2025-04-07,WEEKLY,DAILY,43261
94,2025-03-03,2025-04-07,WEEKLY,MONTHLY,12474
95,2025-03-03,2025-04-07,WEEKLY,WEEKLY,472501
96,2025-03-03,2025-04-14,BI_WEEKLY,BI_WEEKLY,374065
97,2025-03-03,2025-04-14,BI_WEEKLY,DAILY,19432
98,2025-03-03,2025-04-14,BI_WEEKLY,MONTHLY,205185
99,2025-03-03,2025-04-14,BI_WEEKLY,RARE_NEED,76034
100,2025-03-03,2025-04-14,BI_WEEKLY,WEEKLY,178082
101,2025-03-03,2025-04-14,DAILY,BI_WEEKLY,14050
102,2025-03-03,2025-04-14,DAILY,DAILY,190465
103,2025-03-03,2025-04-14,DAILY,MONTHLY,3830
104,2025-03-03,2025-04-14,DAILY,RARE_NEED,802
105,2025-03-03,2025-04-14,DAILY,WEEKLY,32917
106,2025-03-03,2025-04-14,MONTHLY,BI_WEEKLY,167899
107,2025-03-03,2025-04-14,MONTHLY,DAILY,5047
108,2025-03-03,2025-04-14,MONTHLY,MONTHLY,283897
109,2025-03-03,2025-04-14,MONTHLY,RARE_NEED,284823
110,2025-03-03,2025-04-14,MONTHLY,WEEKLY,29347
111,2025-03-03,2025-04-14,RARE_NEED,BI_WEEKLY,82465
112,2025-03-03,2025-04-14,RARE_NEED,DAILY,2357
113,2025-03-03,2025-04-14,RARE_NEED,MONTHLY,202297
114,2025-03-03,2025-04-14,RARE_NEED,RARE_NEED,2415988
115,2025-03-03,2025-04-14,RARE_NEED,WEEKLY,5463
116,2025-03-03,2025-04-14,WEEKLY,BI_WEEKLY,142187
117,2025-03-03,2025-04-14,WEEKLY,DAILY,48862
118,2025-03-03,2025-04-14,WEEKLY,MONTHLY,22231
119,2025-03-03,2025-04-14,WEEKLY,RARE_NEED,987
120,2025-03-03,2025-04-14,WEEKLY,WEEKLY,447916
121,2025-03-03,2025-04-21,BI_WEEKLY,BI_WEEKLY,343834
122,2025-03-03,2025-04-21,BI_WEEKLY,DAILY,20543
123,2025-03-03,2025-04-21,BI_WEEKLY,MONTHLY,198833
124,2025-03-03,2025-04-21,BI_WEEKLY,RARE_NEED,96429
125,2025-03-03,2025-04-21,BI_WEEKLY,WEEKLY,187236
126,2025-03-03,2025-04-21,DAILY,BI_WEEKLY,14960
127,2025-03-03,2025-04-21,DAILY,DAILY,183326
128,2025-03-03,2025-04-21,DAILY,MONTHLY,4720
129,2025-03-03,2025-04-21,DAILY,RARE_NEED,1947
130,2025-03-03,2025-04-21,DAILY,WEEKLY,35222
131,2025-03-03,2025-04-21,MONTHLY,BI_WEEKLY,175803
132,2025-03-03,2025-04-21,MONTHLY,DAILY,5673
133,2025-03-03,2025-04-21,MONTHLY,MONTHLY,252052
134,2025-03-03,2025-04-21,MONTHLY,RARE_NEED,295621
135,2025-03-03,2025-04-21,MONTHLY,WEEKLY,36586
136,2025-03-03,2025-04-21,RARE_NEED,BI_WEEKLY,97862
137,2025-03-03,2025-04-21,RARE_NEED,DAILY,3397
138,2025-03-03,2025-04-21,RARE_NEED,MONTHLY,215803
139,2025-03-03,2025-04-21,RARE_NEED,RARE_NEED,2370149
140,2025-03-03,2025-04-21,RARE_NEED,WEEKLY,10327
141,2025-03-03,2025-04-21,WEEKLY,BI_WEEKLY,144341
142,2025-03-03,2025-04-21,WEEKLY,DAILY,54058
143,2025-03-03,2025-04-21,WEEKLY,MONTHLY,30872
144,2025-03-03,2025-04-21,WEEKLY,RARE_NEED,4212
145,2025-03-03,2025-04-21,WEEKLY,WEEKLY,424311
146,2025-03-03,2025-04-28,BI_WEEKLY,BI_WEEKLY,319919
147,2025-03-03,2025-04-28,BI_WEEKLY,DAILY,21751
148,2025-03-03,2025-04-28,BI_WEEKLY,MONTHLY,192074
149,2025-03-03,2025-04-28,BI_WEEKLY,RARE_NEED,121051
150,2025-03-03,2025-04-28,BI_WEEKLY,WEEKLY,189110
151,2025-03-03,2025-04-28,DAILY,BI_WEEKLY,15935
152,2025-03-03,2025-04-28,DAILY,DAILY,177138
153,2025-03-03,2025-04-28,DAILY,MONTHLY,5502
154,2025-03-03,2025-04-28,DAILY,RARE_NEED,3337
155,2025-03-03,2025-04-28,DAILY,WEEKLY,38363
156,2025-03-03,2025-04-28,MONTHLY,BI_WEEKLY,176678
157,2025-03-03,2025-04-28,MONTHLY,DAILY,6201
158,2025-03-03,2025-04-28,MONTHLY,MONTHLY,229178
159,2025-03-03,2025-04-28,MONTHLY,RARE_NEED,307239
160,2025-03-03,2025-04-28,MONTHLY,WEEKLY,42907
161,2025-03-03,2025-04-28,RARE_NEED,BI_WEEKLY,107628
162,2025-03-03,2025-04-28,RARE_NEED,DAILY,4395
163,2025-03-03,2025-04-28,RARE_NEED,MONTHLY,224917
164,2025-03-03,2025-04-28,RARE_NEED,RARE_NEED,2336210
165,2025-03-03,2025-04-28,RARE_NEED,WEEKLY,15441
166,2025-03-03,2025-04-28,WEEKLY,BI_WEEKLY,148087
167,2025-03-03,2025-04-28,WEEKLY,DAILY,58487
168,2025-03-03,2025-04-28,WEEKLY,MONTHLY,39409
169,2025-03-03,2025-04-28,WEEKLY,RARE_NEED,9466
170,2025-03-03,2025-04-28,WEEKLY,WEEKLY,401452
171,2025-03-03,2025-05-05,BI_WEEKLY,BI_WEEKLY,301030
172,2025-03-03,2025-05-05,BI_WEEKLY,DAILY,22673
173,2025-03-03,2025-05-05,BI_WEEKLY,MONTHLY,181918
174,2025-03-03,2025-05-05,BI_WEEKLY,RARE_NEED,139648
175,2025-03-03,2025-05-05,BI_WEEKLY,WEEKLY,194246
176,2025-03-03,2025-05-05,DAILY,BI_WEEKLY,16725
177,2025-03-03,2025-05-05,DAILY,DAILY,169725
178,2025-03-03,2025-05-05,DAILY,MONTHLY,6168
179,2025-03-03,2025-05-05,DAILY,RARE_NEED,4872
180,2025-03-03,2025-05-05,DAILY,WEEKLY,41346
181,2025-03-03,2025-05-05,MONTHLY,BI_WEEKLY,179050
182,2025-03-03,2025-05-05,MONTHLY,DAILY,6742
183,2025-03-03,2025-05-05,MONTHLY,MONTHLY,210626
184,2025-03-03,2025-05-05,MONTHLY,RARE_NEED,310601
185,2025-03-03,2025-05-05,MONTHLY,WEEKLY,51142
186,2025-03-03,2025-05-05,RARE_NEED,BI_WEEKLY,121660
187,2025-03-03,2025-05-05,RARE_NEED,DAILY,5408
188,2025-03-03,2025-05-05,RARE_NEED,MONTHLY,233347
189,2025-03-03,2025-05-05,RARE_NEED,RARE_NEED,2296465
190,2025-03-03,2025-05-05,RARE_NEED,WEEKLY,21749
191,2025-03-03,2025-05-05,WEEKLY,BI_WEEKLY,147990
192,2025-03-03,2025-05-05,WEEKLY,DAILY,61967
193,2025-03-03,2025-05-05,WEEKLY,MONTHLY,44515
194,2025-03-03,2025-05-05,WEEKLY,RARE_NEED,16345
195,2025-03-03,2025-05-05,WEEKLY,WEEKLY,382316

In [89]:
df_merge_pivot_prev.pivot(index = ['run_date_x', 'taxi_regularity_segment_x', 'taxi_regularity_segment_y'] , columns = ['run_date_y'], values =['customers']).fillna(0)

                                                                customers  \
run_date_y                                                     2025-03-10
run_date_x taxi_regularity_segment_x taxi_regularity_segment_y
2025-03-03 BI_WEEKLY                 BI_WEEKLY                   699039.0
                                     DAILY                         5764.0
                                     MONTHLY                     112066.0
                                     RARE_NEED                        0.0
                                     WEEKLY                       68657.0
           DAILY                     BI_WEEKLY                     4167.0
                                     DAILY                       229567.0
                                     MONTHLY                          0.0
                                     RARE_NEED                        0.0
                                     WEEKLY                       13761.0
           MONTHLY                   BI_WEEKLY                    96079.0
                                     DAILY                            0.0
                                     MONTHLY                     602270.0
                                     RARE_NEED                   101734.0
                                     WEEKLY                           0.0
           RARE_NEED                 BI_WEEKLY                        0.0
                                     DAILY                            0.0
                                     MONTHLY                      74919.0
                                     RARE_NEED                  2687514.0
                                     WEEKLY                           0.0
           WEEKLY                    BI_WEEKLY                    68656.0
                                     DAILY                        14488.0
                                     MONTHLY                          0.0
                                     RARE_NEED                        0.0
                                     WEEKLY                      600345.0

                                                                           \
run_date_y                                                     2025-03-17
run_date_x taxi_regularity_segment_x taxi_regularity_segment_y
2025-03-03 BI_WEEKLY                 BI_WEEKLY                   585691.0
                                     DAILY                        11095.0
                                     MONTHLY                     178838.0
                                     RARE_NEED                        0.0
                                     WEEKLY                       99802.0
           DAILY                     BI_WEEKLY                     7460.0
                                     DAILY                       216499.0
                                     MONTHLY                          0.0
                                     RARE_NEED                        0.0
                                     WEEKLY                       21478.0
           MONTHLY                   BI_WEEKLY                   132910.0
                                     DAILY                            0.0
                                     MONTHLY                     481937.0
                                     RARE_NEED                   177401.0
                                     WEEKLY                           0.0
           RARE_NEED                 BI_WEEKLY                    14103.0
                                     DAILY                            0.0
                                     MONTHLY                     115143.0
                                     RARE_NEED                  2620906.0
                                     WEEKLY                           0.0
           WEEKLY                    BI_WEEKLY                    97050.0
                                     DAILY                        21864.0
                                     MONTHLY                          0.0
                                     RARE_NEED                        0.0
                                     WEEKLY                      556689.0

                                                                           \
run_date_y                                                     2025-03-24
run_date_x taxi_regularity_segment_x taxi_regularity_segment_y
2025-03-03 BI_WEEKLY                 BI_WEEKLY                   504225.0
                                     DAILY                        15187.0
                                     MONTHLY                     215338.0
                                     RARE_NEED                     8877.0
                                     WEEKLY                      125694.0
           DAILY                     BI_WEEKLY                    10245.0
                                     DAILY                       209415.0
                                     MONTHLY                          0.0
                                     RARE_NEED                        0.0
                                     WEEKLY                       25869.0
           MONTHLY                   BI_WEEKLY                   150006.0
                                     DAILY                         1189.0
                                     MONTHLY                     407412.0
                                     RARE_NEED                   225322.0
                                     WEEKLY                        2924.0
           RARE_NEED                 BI_WEEKLY                    31569.0
                                     DAILY                            0.0
                                     MONTHLY                     141029.0
                                     RARE_NEED                  2567379.0
                                     WEEKLY                           0.0
           WEEKLY                    BI_WEEKLY                   118165.0
                                     DAILY                        29705.0
                                     MONTHLY                          0.0
                                     RARE_NEED                        0.0
                                     WEEKLY                      524933.0

                                                                           \
run_date_y                                                     2025-03-31
run_date_x taxi_regularity_segment_x taxi_regularity_segment_y
2025-03-03 BI_WEEKLY                 BI_WEEKLY                   444861.0
                                     DAILY                        16870.0
                                     MONTHLY                     223079.0
                                     RARE_NEED                    28496.0
                                     WEEKLY                      148896.0
           DAILY                     BI_WEEKLY                    11815.0
                                     DAILY                       202080.0
                                     MONTHLY                       1184.0
                                     RARE_NEED                        0.0
                                     WEEKLY                       28041.0
           MONTHLY                   BI_WEEKLY                   157861.0
                                     DAILY                         3066.0
                                     MONTHLY                     356773.0
                                     RARE_NEED                   253809.0
                                     WEEKLY                        9449.0
           RARE_NEED                 BI_WEEKLY                    48870.0
                                     DAILY                          291.0
                                     MONTHLY                     163126.0
                                     RARE_NEED                  2517043.0
                                     WEEKLY                         127.0
           WEEKLY                    BI_WEEKLY                   132950.0
                                     DAILY                        35427.0
                                     MONTHLY                       3731.0
                                     RARE_NEED                        0.0
                                     WEEKLY                      494840.0

                                                                           \
run_date_y                                                     2025-04-07
run_date_x taxi_regularity_segment_x taxi_regularity_segment_y
2025-03-03 BI_WEEKLY                 BI_WEEKLY                   405279.0
                                     DAILY                        18428.0
                                     MONTHLY                     215882.0
                                     RARE_NEED                    52090.0
                                     WEEKLY                      166447.0
           DAILY                     BI_WEEKLY                    12899.0
                                     DAILY                       198343.0
                                     MONTHLY                       2827.0
                                     RARE_NEED                        0.0
                                     WEEKLY                       29692.0
           MONTHLY                   BI_WEEKLY                   165776.0
                                     DAILY                         4174.0
                                     MONTHLY                     316540.0
                                     RARE_NEED                   270342.0
                                     WEEKLY                       19295.0
           RARE_NEED                 BI_WEEKLY                    66215.0
                                     DAILY                         1330.0
                                     MONTHLY                     185537.0
                                     RARE_NEED                  2464213.0
                                     WEEKLY                        1950.0
           WEEKLY                    BI_WEEKLY                   137910.0
                                     DAILY                        43261.0
                                     MONTHLY                      12474.0
                                     RARE_NEED                        0.0
                                     WEEKLY                      472501.0

                                                                           \
run_date_y                                                     2025-04-14
run_date_x taxi_regularity_segment_x taxi_regularity_segment_y
2025-03-03 BI_WEEKLY                 BI_WEEKLY                   374065.0
                                     DAILY                        19432.0
                                     MONTHLY                     205185.0
                                     RARE_NEED                    76034.0
                                     WEEKLY                      178082.0
           DAILY                     BI_WEEKLY                    14050.0
                                     DAILY                       190465.0
                                     MONTHLY                       3830.0
                                     RARE_NEED                      802.0
                                     WEEKLY                       32917.0
           MONTHLY                   BI_WEEKLY                   167899.0
                                     DAILY                         5047.0
                                     MONTHLY                     283897.0
                                     RARE_NEED                   284823.0
                                     WEEKLY                       29347.0
           RARE_NEED                 BI_WEEKLY                    82465.0
                                     DAILY                         2357.0
                                     MONTHLY                     202297.0
                                     RARE_NEED                  2415988.0
                                     WEEKLY                        5463.0
           WEEKLY                    BI_WEEKLY                   142187.0
                                     DAILY                        48862.0
                                     MONTHLY                      22231.0
                                     RARE_NEED                      987.0
                                     WEEKLY                      447916.0

                                                                           \
run_date_y                                                     2025-04-21
run_date_x taxi_regularity_segment_x taxi_regularity_segment_y
2025-03-03 BI_WEEKLY                 BI_WEEKLY                   343834.0
                                     DAILY                        20543.0
                                     MONTHLY                     198833.0
                                     RARE_NEED                    96429.0
                                     WEEKLY                      187236.0
           DAILY                     BI_WEEKLY                    14960.0
                                     DAILY                       183326.0
                                     MONTHLY                       4720.0
                                     RARE_NEED                     1947.0
                                     WEEKLY                       35222.0
           MONTHLY                   BI_WEEKLY                   175803.0
                                     DAILY                         5673.0
                                     MONTHLY                     252052.0
                                     RARE_NEED                   295621.0
                                     WEEKLY                       36586.0
           RARE_NEED                 BI_WEEKLY                    97862.0
                                     DAILY                         3397.0
                                     MONTHLY                     215803.0
                                     RARE_NEED                  2370149.0
                                     WEEKLY                       10327.0
           WEEKLY                    BI_WEEKLY                   144341.0
                                     DAILY                        54058.0
                                     MONTHLY                      30872.0
                                     RARE_NEED                     4212.0
                                     WEEKLY                      424311.0

                                                                           \
run_date_y                                                     2025-04-28
run_date_x taxi_regularity_segment_x taxi_regularity_segment_y
2025-03-03 BI_WEEKLY                 BI_WEEKLY                   319919.0
                                     DAILY                        21751.0
                                     MONTHLY                     192074.0
                                     RARE_NEED                   121051.0
                                     WEEKLY                      189110.0
           DAILY                     BI_WEEKLY                    15935.0
                                     DAILY                       177138.0
                                     MONTHLY                       5502.0
                                     RARE_NEED                     3337.0
                                     WEEKLY                       38363.0
           MONTHLY                   BI_WEEKLY                   176678.0
                                     DAILY                         6201.0
                                     MONTHLY                     229178.0
                                     RARE_NEED                   307239.0
                                     WEEKLY                       42907.0
           RARE_NEED                 BI_WEEKLY                   107628.0
                                     DAILY                         4395.0
                                     MONTHLY                     224917.0
                                     RARE_NEED                  2336210.0
                                     WEEKLY                       15441.0
           WEEKLY                    BI_WEEKLY                   148087.0
                                     DAILY                        58487.0
                                     MONTHLY                      39409.0
                                     RARE_NEED                     9466.0
                                     WEEKLY                      401452.0


run_date_y                                                     2025-05-05
run_date_x taxi_regularity_segment_x taxi_regularity_segment_y
2025-03-03 BI_WEEKLY                 BI_WEEKLY                   301030.0
                                     DAILY                        22673.0
                                     MONTHLY                     181918.0
                                     RARE_NEED                   139648.0
                                     WEEKLY                      194246.0
           DAILY                     BI_WEEKLY                    16725.0
                                     DAILY                       169725.0
                                     MONTHLY                       6168.0
                                     RARE_NEED                     4872.0
                                     WEEKLY                       41346.0
           MONTHLY                   BI_WEEKLY                   179050.0
                                     DAILY                         6742.0
                                     MONTHLY                     210626.0
                                     RARE_NEED                   310601.0
                                     WEEKLY                       51142.0
           RARE_NEED                 BI_WEEKLY                   121660.0
                                     DAILY                         5408.0
                                     MONTHLY                     233347.0
                                     RARE_NEED                  2296465.0
                                     WEEKLY                       21749.0
           WEEKLY                    BI_WEEKLY                   147990.0
                                     DAILY                        61967.0
                                     MONTHLY                      44515.0
                                     RARE_NEED                    16345.0
                                     WEEKLY                      382316.0

In [91]:
df_merge_pivot_prev.pivot(index = ['run_date_x', 'taxi_regularity_segment_x', 'taxi_regularity_segment_y'] , columns = ['run_date_y'], values =['customers']).fillna(0).to_clipboard(index=False)

In [92]:
df_base_prev.groupby(['run_date', 'taxi_regularity_segment']).agg(customers=('customer_id','nunique')).reset_index()

     run_date taxi_regularity_segment  customers
0  2025-03-03               BI_WEEKLY     901613
1  2025-03-03                   DAILY     254588
2  2025-03-03                 MONTHLY     810794
3  2025-03-03               RARE_NEED    2777777
4  2025-03-03                  WEEKLY     701240

### FE Regularity

In [6]:
run_date

['2025-03-03',
 '2025-03-10',
 '2025-03-17',
 '2025-03-24',
 '2025-03-31',
 '2025-04-07',
 '2025-04-14',
 '2025-04-21',
 '2025-04-28',
 '2025-05-05']

In [7]:
local_path

'/Users/E2074/local-datasets/customer/segmentation/consideration/stability2'

In [26]:
def get_previous_segment_customer_base(run_date):
    
    base_query = f"""
    
    select 
        run_date, 
        customer_id, 
        -- taxi_regularity_segment
        taxi_fe_regularity_segment 
    from 
        datasets.iallocator_customer_segments 
    where 
        run_date = date_format(date('{run_date}'), '%Y-%m-%d')
        and taxi_lifetime_last_ride_city = 'Bangalore'
        and taxi_fe_regularity_segment != 'UNKNOWN' 
    """
    
    df_base_query = pd.read_sql(base_query, conn4)
    df_base_query['run_date'] = run_date
    print('executed - ', run_date)

    df_base_query.to_parquet(local_path + '/prev_segment/prev_customer_base_{}.parquet'.format(run_date), index=False)

In [27]:
for i in run_date[3:]:
    
    print('starting - ', i)
    get_previous_segment_customer_base(i)

starting -  2025-03-24
executed -  2025-03-24
starting -  2025-03-31
executed -  2025-03-31
starting -  2025-04-07
executed -  2025-04-07
starting -  2025-04-14
executed -  2025-04-14
starting -  2025-04-21
executed -  2025-04-21
starting -  2025-04-28
executed -  2025-04-28
starting -  2025-05-05
executed -  2025-05-05

In [28]:
folder_path = '/Users/E2074/local-datasets/customer/segmentation/consideration/stability2/prev_segment'

# Get all parquet files in the folder
prev_parquet_files = glob.glob(os.path.join(folder_path, '*.parquet'))

# Read and concatenate all parquet files into a single DataFrame
df_previous_segment_concat = pd.concat([pd.read_parquet(file) for file in prev_parquet_files], ignore_index=True)

In [29]:
df_previous_segment_concat.head(1)

     run_date               customer_id taxi_fe_regularity_segment
0  2025-03-31  6474a5c8694393cc7e442e77                      DAILY

In [30]:
df_previous_segment_concat.shape

(35532535, 3)

### Stability

In [31]:
df_previous_segment_concat.run_date.unique()

array(['2025-03-31', '2025-03-17', '2025-04-14', '2025-04-28',
       '2025-04-07', '2025-04-21', '2025-03-10', '2025-05-05',
       '2025-03-03', '2025-03-24'], dtype=object)

In [32]:
df_base_prev = df_previous_segment_concat[df_previous_segment_concat['run_date'].isin(['2025-03-03'])].reset_index(drop=True)
df_base_prev

           run_date               customer_id taxi_fe_regularity_segment
0        2025-03-03  64e70e90be1489e998c46848                  BI_WEEKLY
1        2025-03-03  61dbe366fb8e4d610931ab58                  BI_WEEKLY
2        2025-03-03  661a4d851f79f98055656dc3                    MONTHLY
3        2025-03-03  5e33d682c725ca6c303e47e2                  RARE_NEED
4        2025-03-03  61619a34aa0ecd1f9713558f                  BI_WEEKLY
...             ...                       ...                        ...
3448101  2025-03-03  65d0a2f26e764329106ed317                    MONTHLY
3448102  2025-03-03  66384d8d5b3860598dc602e1                  BI_WEEKLY
3448103  2025-03-03  5d844ff1af794421566a1ef1                     WEEKLY
3448104  2025-03-03  6585c70a1093bb34fc3a09a0                     WEEKLY
3448105  2025-03-03  61e5682e93bdd008c8df9947                  BI_WEEKLY

[3448106 rows x 3 columns]

In [33]:
df_stability_window_prev = df_previous_segment_concat[~df_previous_segment_concat['run_date'].isin(['2025-03-03'])].sort_values(by=['run_date']).reset_index(drop=True)
df_stability_window_prev

            run_date               customer_id taxi_fe_regularity_segment
0         2025-03-10  5abdecea25abd634611d51aa                    MONTHLY
1         2025-03-10  62a735f41420e29d95401dc1                    MONTHLY
2         2025-03-10  67aa9d57fe551003ad9fe5d9                    MONTHLY
3         2025-03-10  67c341027c3ccf7a49876869                  RARE_NEED
4         2025-03-10  6730dedc8ea7d581ee78aa92                  BI_WEEKLY
...              ...                       ...                        ...
32084424  2025-05-05  67e38cabd25c76821790bfd1                  RARE_NEED
32084425  2025-05-05  6583d607cfe5392da9d31334                     WEEKLY
32084426  2025-05-05  639b49dbd79523ee6cce4771                     WEEKLY
32084427  2025-05-05  647dd4970b7c4a5f730081c2                  RARE_NEED
32084428  2025-05-05  65d16d826e76437e0a8f22c8                     WEEKLY

[32084429 rows x 3 columns]

In [34]:
df_stability_window_prev.run_date.unique()

array(['2025-03-10', '2025-03-17', '2025-03-24', '2025-03-31',
       '2025-04-07', '2025-04-14', '2025-04-21', '2025-04-28',
       '2025-05-05'], dtype=object)

In [35]:
df_merge_prev = pd.merge(df_base_prev, df_stability_window_prev, how='left', on='customer_id')
df_merge_prev

,run_date_x,customer_id,taxi_fe_regularity_segment_x,run_date_y,taxi_fe_regularity_segment_y
0,2025-03-03,64e70e90be1489e998c46848,BI_WEEKLY,2025-03-10,BI_WEEKLY
1,2025-03-03,64e70e90be1489e998c46848,BI_WEEKLY,2025-03-17,BI_WEEKLY
2,2025-03-03,64e70e90be1489e998c46848,BI_WEEKLY,2025-03-24,BI_WEEKLY
3,2025-03-03,64e70e90be1489e998c46848,BI_WEEKLY,2025-03-31,MONTHLY
4,2025-03-03,64e70e90be1489e998c46848,BI_WEEKLY,2025-04-07,MONTHLY
...,...,...,...,...,...
26076936,2025-03-03,61e5682e93bdd008c8df9947,BI_WEEKLY,2025-04-07,BI_WEEKLY
26076937,2025-03-03,61e5682e93bdd008c8df9947,BI_WEEKLY,2025-04-14,MONTHLY
26076938,2025-03-03,61e5682e93bdd008c8df9947,BI_WEEKLY,2025-04-21,MONTHLY
26076939,2025-03-03,61e5682e93bdd008c8df9947,BI_WEEKLY,2025-04-28,MONTHLY
26076940,2025-03-03,61e5682e93bdd008c8df9947,BI_WEEKLY,2025-05-05,MONTHLY

In [36]:
df_merge_pivot_prev = df_merge_prev.groupby(['run_date_x', 'run_date_y', 'taxi_fe_regularity_segment_x', 'taxi_fe_regularity_segment_y']).agg(customers=('customer_id','nunique')).reset_index()
df_merge_pivot_prev

,run_date_x,run_date_y,taxi_fe_regularity_segment_x,taxi_fe_regularity_segment_y,customers
0,2025-03-03,2025-03-10,BI_WEEKLY,BI_WEEKLY,852070
1,2025-03-03,2025-03-10,BI_WEEKLY,DAILY,9595
2,2025-03-03,2025-03-10,BI_WEEKLY,MONTHLY,119637
3,2025-03-03,2025-03-10,BI_WEEKLY,WEEKLY,55537
4,2025-03-03,2025-03-10,DAILY,BI_WEEKLY,6707
5,2025-03-03,2025-03-10,DAILY,DAILY,263169
6,2025-03-03,2025-03-10,DAILY,WEEKLY,14437
7,2025-03-03,2025-03-10,MONTHLY,BI_WEEKLY,119766
8,2025-03-03,2025-03-10,MONTHLY,MONTHLY,782052
9,2025-03-03,2025-03-10,MONTHLY,RARE_NEED,101823
10,2025-03-03,2025-03-10,RARE_NEED,MONTHLY,68392
11,2025-03-03,2025-03-10,RARE_NEED,RARE_NEED,425258
12,2025-03-03,2025-03-10,WEEKLY,BI_WEEKLY,55659
13,2025-03-03,2025-03-10,WEEKLY,DAILY,13805
14,2025-03-03,2025-03-10,WEEKLY,WEEKLY,380275
15,2025-03-03,2025-03-17,BI_WEEKLY,BI_WEEKLY,744171
16,2025-03-03,2025-03-17,BI_WEEKLY,DAILY,17325
17,2025-03-03,2025-03-17,BI_WEEKLY,MONTHLY,179325
18,2025-03-03,2025-03-17,BI_WEEKLY,WEEKLY,84522
19,2025-03-03,2025-03-17,DAILY,BI_WEEKLY,11878
20,2025-03-03,2025-03-17,DAILY,DAILY,247903
21,2025-03-03,2025-03-17,DAILY,WEEKLY,22008
22,2025-03-03,2025-03-17,MONTHLY,BI_WEEKLY,180067
23,2025-03-03,2025-03-17,MONTHLY,MONTHLY,621075
24,2025-03-03,2025-03-17,MONTHLY,RARE_NEED,153928
25,2025-03-03,2025-03-17,RARE_NEED,BI_WEEKLY,486
26,2025-03-03,2025-03-17,RARE_NEED,MONTHLY,98306
27,2025-03-03,2025-03-17,RARE_NEED,RARE_NEED,323727
28,2025-03-03,2025-03-17,WEEKLY,BI_WEEKLY,80343
29,2025-03-03,2025-03-17,WEEKLY,DAILY,20732
30,2025-03-03,2025-03-17,WEEKLY,WEEKLY,343519
31,2025-03-03,2025-03-24,BI_WEEKLY,BI_WEEKLY,655737
32,2025-03-03,2025-03-24,BI_WEEKLY,DAILY,25653
33,2025-03-03,2025-03-24,BI_WEEKLY,MONTHLY,222233
34,2025-03-03,2025-03-24,BI_WEEKLY,RARE_NEED,2730
35,2025-03-03,2025-03-24,BI_WEEKLY,WEEKLY,111079
36,2025-03-03,2025-03-24,DAILY,BI_WEEKLY,16592
37,2025-03-03,2025-03-24,DAILY,DAILY,239289
38,2025-03-03,2025-03-24,DAILY,WEEKLY,25985
39,2025-03-03,2025-03-24,MONTHLY,BI_WEEKLY,216432
40,2025-03-03,2025-03-24,MONTHLY,MONTHLY,512813
41,2025-03-03,2025-03-24,MONTHLY,RARE_NEED,181942
42,2025-03-03,2025-03-24,RARE_NEED,BI_WEEKLY,11882
43,2025-03-03,2025-03-24,RARE_NEED,MONTHLY,103174
44,2025-03-03,2025-03-24,RARE_NEED,RARE_NEED,265095
45,2025-03-03,2025-03-24,WEEKLY,BI_WEEKLY,97553
46,2025-03-03,2025-03-24,WEEKLY,DAILY,27889
47,2025-03-03,2025-03-24,WEEKLY,WEEKLY,317392
48,2025-03-03,2025-03-31,BI_WEEKLY,BI_WEEKLY,582524
49,2025-03-03,2025-03-31,BI_WEEKLY,DAILY,28262
50,2025-03-03,2025-03-31,BI_WEEKLY,MONTHLY,250545
51,2025-03-03,2025-03-31,BI_WEEKLY,RARE_NEED,16026
52,2025-03-03,2025-03-31,BI_WEEKLY,WEEKLY,128975
53,2025-03-03,2025-03-31,DAILY,BI_WEEKLY,20267
54,2025-03-03,2025-03-31,DAILY,DAILY,228773
55,2025-03-03,2025-03-31,DAILY,MONTHLY,1178
56,2025-03-03,2025-03-31,DAILY,WEEKLY,28900
57,2025-03-03,2025-03-31,MONTHLY,BI_WEEKLY,230360
58,2025-03-03,2025-03-31,MONTHLY,DAILY,3243
59,2025-03-03,2025-03-31,MONTHLY,MONTHLY,441977
60,2025-03-03,2025-03-31,MONTHLY,RARE_NEED,188610
61,2025-03-03,2025-03-31,MONTHLY,WEEKLY,4478
62,2025-03-03,2025-03-31,RARE_NEED,BI_WEEKLY,22335
63,2025-03-03,2025-03-31,RARE_NEED,MONTHLY,101601
64,2025-03-03,2025-03-31,RARE_NEED,RARE_NEED,226334
65,2025-03-03,2025-03-31,WEEKLY,BI_WEEKLY,114646
66,2025-03-03,2025-03-31,WEEKLY,DAILY,30864
67,2025-03-03,2025-03-31,WEEKLY,MONTHLY,1645
68,2025-03-03,2025-03-31,WEEKLY,WEEKLY,291856
69,2025-03-03,2025-04-07,BI_WEEKLY,BI_WEEKLY,528297
70,2025-03-03,2025-04-07,BI_WEEKLY,DAILY,31274
71,2025-03-03,2025-04-07,BI_WEEKLY,MONTHLY,256991
72,2025-03-03,2025-04-07,BI_WEEKLY,RARE_NEED,34138
73,2025-03-03,2025-04-07,BI_WEEKLY,WEEKLY,144627
74,2025-03-03,2025-04-07,DAILY,BI_WEEKLY,23128
75,2025-03-03,2025-04-07,DAILY,DAILY,222271
76,2025-03-03,2025-04-07,DAILY,MONTHLY,3229
77,2025-03-03,2025-04-07,DAILY,WEEKLY,31285
78,2025-03-03,2025-04-07,MONTHLY,BI_WEEKLY,234551
79,2025-03-03,2025-04-07,MONTHLY,DAILY,7067
80,2025-03-03,2025-04-07,MONTHLY,MONTHLY,390350
81,2025-03-03,2025-04-07,MONTHLY,RARE_NEED,183908
82,2025-03-03,2025-04-07,MONTHLY,WEEKLY,11991
83,2025-03-03,2025-04-07,RARE_NEED,BI_WEEKLY,32367
84,2025-03-03,2025-04-07,RARE_NEED,MONTHLY,101605
85,2025-03-03,2025-04-07,RARE_NEED,RARE_NEED,192834
86,2025-03-03,2025-04-07,WEEKLY,BI_WEEKLY,126065
87,2025-03-03,2025-04-07,WEEKLY,DAILY,35635
88,2025-03-03,2025-04-07,WEEKLY,MONTHLY,7345
89,2025-03-03,2025-04-07,WEEKLY,WEEKLY,269576
90,2025-03-03,2025-04-14,BI_WEEKLY,BI_WEEKLY,485892
91,2025-03-03,2025-04-14,BI_WEEKLY,DAILY,32179
92,2025-03-03,2025-04-14,BI_WEEKLY,MONTHLY,254509
93,2025-03-03,2025-04-14,BI_WEEKLY,RARE_NEED,52716
94,2025-03-03,2025-04-14,BI_WEEKLY,WEEKLY,152538
95,2025-03-03,2025-04-14,DAILY,BI_WEEKLY,25772
96,2025-03-03,2025-04-14,DAILY,DAILY,211433
97,2025-03-03,2025-04-14,DAILY,MONTHLY,5582
98,2025-03-03,2025-04-14,DAILY,WEEKLY,35183
99,2025-03-03,2025-04-14,MONTHLY,BI_WEEKLY,235612
100,2025-03-03,2025-04-14,MONTHLY,DAILY,8480
101,2025-03-03,2025-04-14,MONTHLY,MONTHLY,352557
102,2025-03-03,2025-04-14,MONTHLY,RARE_NEED,173342
103,2025-03-03,2025-04-14,MONTHLY,WEEKLY,18814
104,2025-03-03,2025-04-14,RARE_NEED,BI_WEEKLY,38313
105,2025-03-03,2025-04-14,RARE_NEED,DAILY,1576
106,2025-03-03,2025-04-14,RARE_NEED,MONTHLY,100814
107,2025-03-03,2025-04-14,RARE_NEED,RARE_NEED,164704
108,2025-03-03,2025-04-14,RARE_NEED,WEEKLY,1272
109,2025-03-03,2025-04-14,WEEKLY,BI_WEEKLY,133117
110,2025-03-03,2025-04-14,WEEKLY,DAILY,37384
111,2025-03-03,2025-04-14,WEEKLY,MONTHLY,15285
112,2025-03-03,2025-04-14,WEEKLY,WEEKLY,250255
113,2025-03-03,2025-04-21,BI_WEEKLY,BI_WEEKLY,452749
114,2025-03-03,2025-04-21,BI_WEEKLY,DAILY,34422
115,2025-03-03,2025-04-21,BI_WEEKLY,MONTHLY,244691
116,2025-03-03,2025-04-21,BI_WEEKLY,RARE_NEED,64766
117,2025-03-03,2025-04-21,BI_WEEKLY,WEEKLY,159504
118,2025-03-03,2025-04-21,DAILY,BI_WEEKLY,27675
119,2025-03-03,2025-04-21,DAILY,DAILY,203220
120,2025-03-03,2025-04-21,DAILY,MONTHLY,7461
121,2025-03-03,2025-04-21,DAILY,RARE_NEED,852
122,2025-03-03,2025-04-21,DAILY,WEEKLY,36650
123,2025-03-03,2025-04-21,MONTHLY,BI_WEEKLY,239042
124,2025-03-03,2025-04-21,MONTHLY,DAILY,9762
125,2025-03-03,2025-04-21,MONTHLY,MONTHLY,322278
126,2025-03-03,2025-04-21,MONTHLY,RARE_NEED,159353
127,2025-03-03,2025-04-21,MONTHLY,WEEKLY,27180
128,2025-03-03,2025-04-21,RARE_NEED,BI_WEEKLY,43981
129,2025-03-03,2025-04-21,RARE_NEED,DAILY,2740
130,2025-03-03,2025-04-21,RARE_NEED,MONTHLY,100215
131,2025-03-03,2025-04-21,RARE_NEED,RARE_NEED,141443
132,2025-03-03,2025-04-21,RARE_NEED,WEEKLY,3053
133,2025-03-03,2025-04-21,WEEKLY,BI_WEEKLY,134946
134,2025-03-03,2025-04-21,WEEKLY,DAILY,42050
135,2025-03-03,2025-04-21,WEEKLY,MONTHLY,22742
136,2025-03-03,2025-04-21,WEEKLY,RARE_NEED,948
137,2025-03-03,2025-04-21,WEEKLY,WEEKLY,232252
138,2025-03-03,2025-04-28,BI_WEEKLY,BI_WEEKLY,424435
139,2025-03-03,2025-04-28,BI_WEEKLY,DAILY,36452
140,2025-03-03,2025-04-28,BI_WEEKLY,MONTHLY,238639
141,2025-03-03,2025-04-28,BI_WEEKLY,RARE_NEED,73327
142,2025-03-03,2025-04-28,BI_WEEKLY,WEEKLY,160893
143,2025-03-03,2025-04-28,DAILY,BI_WEEKLY,30057
144,2025-03-03,2025-04-28,DAILY,DAILY,195829
145,2025-03-03,2025-04-28,DAILY,MONTHLY,8748
146,2025-03-03,2025-04-28,DAILY,RARE_NEED,2326
147,2025-03-03,2025-04-28,DAILY,WEEKLY,38890
148,2025-03-03,2025-04-28,MONTHLY,BI_WEEKLY,235073
149,2025-03-03,2025-04-28,MONTHLY,DAILY,10782
150,2025-03-03,2025-04-28,MONTHLY,MONTHLY,297850
151,2025-03-03,2025-04-28,MONTHLY,RARE_NEED,151518
152,2025-03-03,2025-04-28,MONTHLY,WEEKLY,34006
153,2025-03-03,2025-04-28,RARE_NEED,BI_WEEKLY,48624
154,2025-03-03,2025-04-28,RARE_NEED,DAILY,3197
155,2025-03-03,2025-04-28,RARE_NEED,MONTHLY,98413
156,2025-03-03,2025-04-28,RARE_NEED,RARE_NEED,122353
157,2025-03-03,2025-04-28,RARE_NEED,WEEKLY,4213
158,2025-03-03,2025-04-28,WEEKLY,BI_WEEKLY,138251
159,2025-03-03,2025-04-28,WEEKLY,DAILY,45192
160,2025-03-03,2025-04-28,WEEKLY,MONTHLY,29671
161,2025-03-03,2025-04-28,WEEKLY,RARE_NEED,3447
162,2025-03-03,2025-04-28,WEEKLY,WEEKLY,215366
163,2025-03-03,2025-05-05,BI_WEEKLY,BI_WEEKLY,402389
164,2025-03-03,2025-05-05,BI_WEEKLY,DAILY,38183
165,2025-03-03,2025-05-05,BI_WEEKLY,MONTHLY,228792
166,2025-03-03,2025-05-05,BI_WEEKLY,RARE_NEED,75978
167,2025-03-03,2025-05-05,BI_WEEKLY,WEEKLY,163940
168,2025-03-03,2025-05-05,DAILY,BI_WEEKLY,31924
169,2025-03-03,2025-05-05,DAILY,DAILY,187191
170,2025-03-03,2025-05-05,DAILY,MONTHLY,9797
171,2025-03-03,2025-05-05,DAILY,RARE_NEED,3582
172,2025-03-03,2025-05-05,DAILY,WEEKLY,41148
173,2025-03-03,2025-05-05,MONTHLY,BI_WEEKLY,235715
174,2025-03-03,2025-05-05,MONTHLY,DAILY,11868
175,2025-03-03,2025-05-05,MONTHLY,MONTHLY,278407
176,2025-03-03,2025-05-05,MONTHLY,RARE_NEED,139189
177,2025-03-03,2025-05-05,MONTHLY,WEEKLY,40623
178,2025-03-03,2025-05-05,RARE_NEED,BI_WEEKLY,53090
179,2025-03-03,2025-05-05,RARE_NEED,DAILY,3652
180,2025-03-03,2025-05-05,RARE_NEED,MONTHLY,96969
181,2025-03-03,2025-05-05,RARE_NEED,RARE_NEED,106161
182,2025-03-03,2025-05-05,RARE_NEED,WEEKLY,6320
183,2025-03-03,2025-05-05,WEEKLY,BI_WEEKLY,137471
184,2025-03-03,2025-05-05,WEEKLY,DAILY,48310
185,2025-03-03,2025-05-05,WEEKLY,MONTHLY,33910
186,2025-03-03,2025-05-05,WEEKLY,RARE_NEED,6916
187,2025-03-03,2025-05-05,WEEKLY,WEEKLY,202078

In [37]:
df_merge_pivot_prev.pivot(index = ['run_date_x', 'taxi_fe_regularity_segment_x', 'taxi_fe_regularity_segment_y'] , columns = ['run_date_y'], values =['customers']).fillna(0)

                                                                      customers  \
run_date_y                                                           2025-03-10
run_date_x taxi_fe_regularity_segment_x taxi_fe_regularity_segment_y
2025-03-03 BI_WEEKLY                    BI_WEEKLY                      852070.0
                                        DAILY                            9595.0
                                        MONTHLY                        119637.0
                                        RARE_NEED                           0.0
                                        WEEKLY                          55537.0
           DAILY                        BI_WEEKLY                        6707.0
                                        DAILY                          263169.0
                                        MONTHLY                             0.0
                                        RARE_NEED                           0.0
                                        WEEKLY                          14437.0
           MONTHLY                      BI_WEEKLY                      119766.0
                                        DAILY                               0.0
                                        MONTHLY                        782052.0
                                        RARE_NEED                      101823.0
                                        WEEKLY                              0.0
           RARE_NEED                    BI_WEEKLY                           0.0
                                        DAILY                               0.0
                                        MONTHLY                         68392.0
                                        RARE_NEED                      425258.0
                                        WEEKLY                              0.0
           WEEKLY                       BI_WEEKLY                       55659.0
                                        DAILY                           13805.0
                                        MONTHLY                             0.0
                                        RARE_NEED                           0.0
                                        WEEKLY                         380275.0

                                                                                 \
run_date_y                                                           2025-03-17
run_date_x taxi_fe_regularity_segment_x taxi_fe_regularity_segment_y
2025-03-03 BI_WEEKLY                    BI_WEEKLY                      744171.0
                                        DAILY                           17325.0
                                        MONTHLY                        179325.0
                                        RARE_NEED                           0.0
                                        WEEKLY                          84522.0
           DAILY                        BI_WEEKLY                       11878.0
                                        DAILY                          247903.0
                                        MONTHLY                             0.0
                                        RARE_NEED                           0.0
                                        WEEKLY                          22008.0
           MONTHLY                      BI_WEEKLY                      180067.0
                                        DAILY                               0.0
                                        MONTHLY                        621075.0
                                        RARE_NEED                      153928.0
                                        WEEKLY                              0.0
           RARE_NEED                    BI_WEEKLY                         486.0
                                        DAILY                               0.0
                                        MONTHLY                         98306.0
                                        RARE_NEED                      323727.0
                                        WEEKLY                              0.0
           WEEKLY                       BI_WEEKLY                       80343.0
                                        DAILY                           20732.0
                                        MONTHLY                             0.0
                                        RARE_NEED                           0.0
                                        WEEKLY                         343519.0

                                                                                 \
run_date_y                                                           2025-03-24
run_date_x taxi_fe_regularity_segment_x taxi_fe_regularity_segment_y
2025-03-03 BI_WEEKLY                    BI_WEEKLY                      655737.0
                                        DAILY                           25653.0
                                        MONTHLY                        222233.0
                                        RARE_NEED                        2730.0
                                        WEEKLY                         111079.0
           DAILY                        BI_WEEKLY                       16592.0
                                        DAILY                          239289.0
                                        MONTHLY                             0.0
                                        RARE_NEED                           0.0
                                        WEEKLY                          25985.0
           MONTHLY                      BI_WEEKLY                      216432.0
                                        DAILY                               0.0
                                        MONTHLY                        512813.0
                                        RARE_NEED                      181942.0
                                        WEEKLY                              0.0
           RARE_NEED                    BI_WEEKLY                       11882.0
                                        DAILY                               0.0
                                        MONTHLY                        103174.0
                                        RARE_NEED                      265095.0
                                        WEEKLY                              0.0
           WEEKLY                       BI_WEEKLY                       97553.0
                                        DAILY                           27889.0
                                        MONTHLY                             0.0
                                        RARE_NEED                           0.0
                                        WEEKLY                         317392.0

                                                                                 \
run_date_y                                                           2025-03-31
run_date_x taxi_fe_regularity_segment_x taxi_fe_regularity_segment_y
2025-03-03 BI_WEEKLY                    BI_WEEKLY                      582524.0
                                        DAILY                           28262.0
                                        MONTHLY                        250545.0
                                        RARE_NEED                       16026.0
                                        WEEKLY                         128975.0
           DAILY                        BI_WEEKLY                       20267.0
                                        DAILY                          228773.0
                                        MONTHLY                          1178.0
                                        RARE_NEED                           0.0
                                        WEEKLY                          28900.0
           MONTHLY                      BI_WEEKLY                      230360.0
                                        DAILY                            3243.0
                                        MONTHLY                        441977.0
                                        RARE_NEED                      188610.0
                                        WEEKLY                           4478.0
           RARE_NEED                    BI_WEEKLY                       22335.0
                                        DAILY                               0.0
                                        MONTHLY                        101601.0
                                        RARE_NEED                      226334.0
                                        WEEKLY                              0.0
           WEEKLY                       BI_WEEKLY                      114646.0
                                        DAILY                           30864.0
                                        MONTHLY                          1645.0
                                        RARE_NEED                           0.0
                                        WEEKLY                         291856.0

                                                                                 \
run_date_y                                                           2025-04-07
run_date_x taxi_fe_regularity_segment_x taxi_fe_regularity_segment_y
2025-03-03 BI_WEEKLY                    BI_WEEKLY                      528297.0
                                        DAILY                           31274.0
                                        MONTHLY                        256991.0
                                        RARE_NEED                       34138.0
                                        WEEKLY                         144627.0
           DAILY                        BI_WEEKLY                       23128.0
                                        DAILY                          222271.0
                                        MONTHLY                          3229.0
                                        RARE_NEED                           0.0
                                        WEEKLY                          31285.0
           MONTHLY                      BI_WEEKLY                      234551.0
                                        DAILY                            7067.0
                                        MONTHLY                        390350.0
                                        RARE_NEED                      183908.0
                                        WEEKLY                          11991.0
           RARE_NEED                    BI_WEEKLY                       32367.0
                                        DAILY                               0.0
                                        MONTHLY                        101605.0
                                        RARE_NEED                      192834.0
                                        WEEKLY                              0.0
           WEEKLY                       BI_WEEKLY                      126065.0
                                        DAILY                           35635.0
                                        MONTHLY                          7345.0
                                        RARE_NEED                           0.0
                                        WEEKLY                         269576.0

                                                                                 \
run_date_y                                                           2025-04-14
run_date_x taxi_fe_regularity_segment_x taxi_fe_regularity_segment_y
2025-03-03 BI_WEEKLY                    BI_WEEKLY                      485892.0
                                        DAILY                           32179.0
                                        MONTHLY                        254509.0
                                        RARE_NEED                       52716.0
                                        WEEKLY                         152538.0
           DAILY                        BI_WEEKLY                       25772.0
                                        DAILY                          211433.0
                                        MONTHLY                          5582.0
                                        RARE_NEED                           0.0
                                        WEEKLY                          35183.0
           MONTHLY                      BI_WEEKLY                      235612.0
                                        DAILY                            8480.0
                                        MONTHLY                        352557.0
                                        RARE_NEED                      173342.0
                                        WEEKLY                          18814.0
           RARE_NEED                    BI_WEEKLY                       38313.0
                                        DAILY                            1576.0
                                        MONTHLY                        100814.0
                                        RARE_NEED                      164704.0
                                        WEEKLY                           1272.0
           WEEKLY                       BI_WEEKLY                      133117.0
                                        DAILY                           37384.0
                                        MONTHLY                         15285.0
                                        RARE_NEED                           0.0
                                        WEEKLY                         250255.0

                                                                                 \
run_date_y                                                           2025-04-21
run_date_x taxi_fe_regularity_segment_x taxi_fe_regularity_segment_y
2025-03-03 BI_WEEKLY                    BI_WEEKLY                      452749.0
                                        DAILY                           34422.0
                                        MONTHLY                        244691.0
                                        RARE_NEED                       64766.0
                                        WEEKLY                         159504.0
           DAILY                        BI_WEEKLY                       27675.0
                                        DAILY                          203220.0
                                        MONTHLY                          7461.0
                                        RARE_NEED                         852.0
                                        WEEKLY                          36650.0
           MONTHLY                      BI_WEEKLY                      239042.0
                                        DAILY                            9762.0
                                        MONTHLY                        322278.0
                                        RARE_NEED                      159353.0
                                        WEEKLY                          27180.0
           RARE_NEED                    BI_WEEKLY                       43981.0
                                        DAILY                            2740.0
                                        MONTHLY                        100215.0
                                        RARE_NEED                      141443.0
                                        WEEKLY                           3053.0
           WEEKLY                       BI_WEEKLY                      134946.0
                                        DAILY                           42050.0
                                        MONTHLY                         22742.0
                                        RARE_NEED                         948.0
                                        WEEKLY                         232252.0

                                                                                 \
run_date_y                                                           2025-04-28
run_date_x taxi_fe_regularity_segment_x taxi_fe_regularity_segment_y
2025-03-03 BI_WEEKLY                    BI_WEEKLY                      424435.0
                                        DAILY                           36452.0
                                        MONTHLY                        238639.0
                                        RARE_NEED                       73327.0
                                        WEEKLY                         160893.0
           DAILY                        BI_WEEKLY                       30057.0
                                        DAILY                          195829.0
                                        MONTHLY                          8748.0
                                        RARE_NEED                        2326.0
                                        WEEKLY                          38890.0
           MONTHLY                      BI_WEEKLY                      235073.0
                                        DAILY                           10782.0
                                        MONTHLY                        297850.0
                                        RARE_NEED                      151518.0
                                        WEEKLY                          34006.0
           RARE_NEED                    BI_WEEKLY                       48624.0
                                        DAILY                            3197.0
                                        MONTHLY                         98413.0
                                        RARE_NEED                      122353.0
                                        WEEKLY                           4213.0
           WEEKLY                       BI_WEEKLY                      138251.0
                                        DAILY                           45192.0
                                        MONTHLY                         29671.0
                                        RARE_NEED                        3447.0
                                        WEEKLY                         215366.0


run_date_y                                                           2025-05-05
run_date_x taxi_fe_regularity_segment_x taxi_fe_regularity_segment_y
2025-03-03 BI_WEEKLY                    BI_WEEKLY                      402389.0
                                        DAILY                           38183.0
                                        MONTHLY                        228792.0
                                        RARE_NEED                       75978.0
                                        WEEKLY                         163940.0
           DAILY                        BI_WEEKLY                       31924.0
                                        DAILY                          187191.0
                                        MONTHLY                          9797.0
                                        RARE_NEED                        3582.0
                                        WEEKLY                          41148.0
           MONTHLY                      BI_WEEKLY                      235715.0
                                        DAILY                           11868.0
                                        MONTHLY                        278407.0
                                        RARE_NEED                      139189.0
                                        WEEKLY                          40623.0
           RARE_NEED                    BI_WEEKLY                       53090.0
                                        DAILY                            3652.0
                                        MONTHLY                         96969.0
                                        RARE_NEED                      106161.0
                                        WEEKLY                           6320.0
           WEEKLY                       BI_WEEKLY                      137471.0
                                        DAILY                           48310.0
                                        MONTHLY                         33910.0
                                        RARE_NEED                        6916.0

In [38]:
df_base_prev.groupby(['run_date', 'taxi_fe_regularity_segment']).agg(customers=('customer_id','nunique')).reset_index()

     run_date taxi_fe_regularity_segment  customers
0  2025-03-03                  BI_WEEKLY    1056482
1  2025-03-03                      DAILY     292637
2  2025-03-03                    MONTHLY    1047096
3  2025-03-03                  RARE_NEED     590726
4  2025-03-03                     WEEKLY     461165